export const FETCH_RATINGS_REVIEWS = 'FETCH_RATINGS_REVIEWS';
export const CHANGE_TAB_VIEW = 'CHANGE_TAB_VIEW';
export const ASYNC_FETCH = 'ASYNC_FETCH';
export const ASYNC_FETCH_SUCCESS = 'ASYNC_FETCH_SUCCESS';
export const ASYNC_FETCH_FAILURE = 'ASYNC_FETCH_FAILURE';
export const ASYNC_FETCH_INVALIDATE = 'ASYNC_FETCH_INVALIDATE';

export const CHANGE_CAPACITY = 'CHANGE_CAPACITY';
export const CHANGE_COLOR = 'CHANGE_COLOR';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const MAX_CHAR_LIMIT = 512;

