const cartJSON = 
/* 
{
  "statusCode": "00",
  "output": {
    "orderId": "SDCf5f50308e587661f31259b4ae42e4ba3{d4}",
    "redirectionURL": null,
    "isPOBODeviceInCart": false,
    "accGuestCheckoutEnabled": null,
    "dueTodayPOBOHeader": null,
    "isHLLPlanInOrder": true,
    "items": [
      {
        "deviceProdId": "dev8760136",
        "deviceManufactureName": "Google",
        "deviceProductDisplayName": "Pixel 2 XL",
        "colorName": "Black and White",
        "capacity": "64GB",
        "flow": "AAL",
        "mtn": null,
        "displayMtn": null,
        "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/GOOGLE_Taiman_Wht?$device-med$&fmt=jpeg&wid=75&hei=150",
        "deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/GOOGLE_Taiman_Wht?$device$&bgc=ffffff&wid=158&hei=300",
        "activationFee": "30.00",
        "waivedActivationFeePromo": false,
        "upgradeFee": "0.00",
        "waivedUpgradeFeePromo": false,
        "edgeDevice": true,
        "price": "35.41",
        "originalPrice": "35.41",
        "priceText": "Device payment",
        "priceSubTitle": "1st installment will appear on your bill.",
        "edgeItemDownPaymentAmount": "0.00",
        "installmentBalance": "0.00",
        "deviceEdgeUpAmount": "0.00",
        "deviceEdgeBuyOutAmount": "0.00",
        "protectionOption": {
          "name": "Total Mobile Protection",
          "price": "13.00",
          "originalPrice": "13.00",
          "featureType": "INS",
          "featureSkuId": "sku2880128",
          "hideEditProtection": false,
          "displayMsg": null,
          "tapOpted": false
        },
        "commerceItemId": "SDCf5f50308e587661f31259b4ae42e4ba3{d4}_device_1",
        "deviceSkuId": "sku2690601",
        "deviceSORId": "GA00152-US",
        "lacPrice": "40.00",
        "lacText": "Smartphone line access",
        "inventoryStatus": "1000",
        "inventoryAvailableDate": null,
        "hasEcpdDiscount": false,
        "hasEcpdDiscountForDevicePayment": false,
        "devicePromotionList": [
          
        ],
        "bicOfferApplied": false,
        "bicContractPrice": "0.00",
        "bicDiscountedContractPrice": "0.00",
        "bicSavings": "0.00",
        "myOfferWaiveUpgradeFee": false,
        "shipCommitInd": null,
        "promoLACMessage": null,
        "additionalFeatures": [
          
        ],
        "simDetails": null,
        "imeiId": null,
        "transferredFromMtn": null,
        "originalActivationFee": "30.00",
        "priceForFullRetailPriceListID": "849.99",
        "bicMessage": null,
        "bicMessagetooltip": null,
        "editDeviceUrl": "/od/pdp/dev8760136/?commerceItemId=SDCf5f50308e587661f31259b4ae42e4ba3%7Bd4%7D_device_1&deviceProdId=dev8760136&catalogRefId=sku2690601&editDevice=true&flow=AAL",
        "fullRetailPrice": "849.99",
        "fromSavedCart": false,
        "numberShareDevice": false,
        "numberSharedMtn": null,
        "itemOnJaxPlan": false,
        "humCarDetails": null,
        "poboAvailableDate": null,
        "planCommerceItemId": "SDCf5f50308e587661f31259b4ae42e4ba3{d4}_plan_1",
        "monthlyPriceAfterDownPaymentBeforeDiscount": 0.0,
        "originalFullRetailPrice": 0.0,
        "hasReducedRetailPrice": false,
        "hasReducedDueMonthly": false,
        "originalDueMonthly": 0.0,
        "lineAccessPromotionText": null,
        "downPaymentPromotionText": null,
        "contractTerm": "99",
        "deviceType": "SMARTPHONE",
        "activationFeeText": "One-time activation fee of $30.0 charged to your next monthly bill.",
        "promoOfferText": null,
        "promoApplied": false,
        "portIn": false,
        "deviceNickName": "Pixel 2 XL",
        "totalNumberShareExtension": 0,
        "originalUpgradeFee": "0.00",
        "totalSavings": null,
        "sbdOffer": null,
        "hostCommerceItemId": null,
        "trunkMtn": null,
        "discountedEdgeRetailPrice": "849.99",
        "displayImeiId": null,
        "featureDropped": false,
        "activationFeeWaived": false,
        "upgradeFeeWaived": false
      },
      {
        "deviceProdId": "dev8720045",
        "deviceManufactureName": "Apple",
        "deviceProductDisplayName": "iPhone&reg; 8 Plus",
        "colorName": "Space Gray",
        "capacity": "64GB",
        "flow": "AAL",
        "mtn": null,
        "displayMtn": null,
        "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iPhone8Plus-SpGry?$device-med$&fmt=jpeg&wid=75&hei=150",
        "deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/iPhone8Plus-SpGry?$device$&bgc=ffffff&wid=158&hei=300",
        "activationFee": "30.00",
        "waivedActivationFeePromo": false,
        "upgradeFee": "0.00",
        "waivedUpgradeFeePromo": false,
        "edgeDevice": true,
        "price": "33.33",
        "originalPrice": "33.33",
        "priceText": "Device payment",
        "priceSubTitle": "1st installment will appear on your bill.",
        "edgeItemDownPaymentAmount": "0.00",
        "installmentBalance": "0.00",
        "deviceEdgeUpAmount": "0.00",
        "deviceEdgeBuyOutAmount": "0.00",
        "protectionOption": {
          "name": "Decline Equipment Protection",
          "price": "0.00",
          "originalPrice": "0.00",
          "featureType": "INS",
          "featureSkuId": "sku401064",
          "hideEditProtection": false,
          "displayMsg": null,
          "tapOpted": false
        },
        "commerceItemId": "SDCf5f50308e587661f31259b4ae42e4ba3{d4}_device_2",
        "deviceSkuId": "sku2680218",
        "deviceSORId": "MQ962LL/A",
        "lacPrice": "80.00",
        "lacText": "Smartphone line access",
        "inventoryStatus": "1000",
        "inventoryAvailableDate": null,
        "hasEcpdDiscount": false,
        "hasEcpdDiscountForDevicePayment": false,
        "devicePromotionList": [
          
        ],
        "bicOfferApplied": false,
        "bicContractPrice": "0.00",
        "bicDiscountedContractPrice": "0.00",
        "bicSavings": "0.00",
        "myOfferWaiveUpgradeFee": false,
        "shipCommitInd": null,
        "promoLACMessage": null,
        "additionalFeatures": [
          
        ],
        "simDetails": null,
        "imeiId": null,
        "transferredFromMtn": null,
        "originalActivationFee": "30.00",
        "priceForFullRetailPriceListID": "799.99",
        "bicMessage": null,
        "bicMessagetooltip": null,
        "editDeviceUrl": "/od/pdp/dev8720045/?commerceItemId=SDCf5f50308e587661f31259b4ae42e4ba3%7Bd4%7D_device_2&deviceProdId=dev8720045&catalogRefId=sku2680218&editDevice=true&flow=AAL",
        "fullRetailPrice": "799.99",
        "fromSavedCart": false,
        "numberShareDevice": false,
        "numberSharedMtn": null,
        "itemOnJaxPlan": false,
        "humCarDetails": null,
        "poboAvailableDate": null,
        "planCommerceItemId": "SDCf5f50308e587661f31259b4ae42e4ba3{d4}_plan_1",
        "monthlyPriceAfterDownPaymentBeforeDiscount": 0.0,
        "originalFullRetailPrice": 0.0,
        "hasReducedRetailPrice": false,
        "hasReducedDueMonthly": false,
        "originalDueMonthly": 0.0,
        "lineAccessPromotionText": null,
        "downPaymentPromotionText": null,
        "contractTerm": "99",
        "deviceType": "SMARTPHONE",
        "activationFeeText": "One-time activation fee of $30.0 charged to your next monthly bill.",
        "promoOfferText": null,
        "promoApplied": false,
        "portIn": false,
        "deviceNickName": "iPhone&reg; 8 Plus",
        "totalNumberShareExtension": 0,
        "originalUpgradeFee": "0.00",
        "totalSavings": null,
        "sbdOffer": null,
        "hostCommerceItemId": null,
        "trunkMtn": null,
        "discountedEdgeRetailPrice": "799.99",
        "displayImeiId": null,
        "featureDropped": false,
        "activationFeeWaived": false,
        "upgradeFeeWaived": false
      }
    ],
    "existingDevices": null,
    "plans": {
      "planOnlyDueMonthly": "200.00",
      "dueMonthly": "200.00",
      "dueToday": "0.00",
      "items": [
        {
          "planType": "Go Unlimited",
          "planSorId": "99230",
          "planProdId": "plan2880001",
          "planSkuId": "sku2580028",
          "planLetter": "U",
          "planDescription": "<span>Shared unlimited talk, </span><span>text &amp; unlimited data </span>",
          "planDisplayName": "Go Unlimited",
          "planChangeURL": "/od/cust/auth/compatiblePlans?editPlan=true&planSorId=99230&flow=null&planCommId=SDCf5f50308e587661f31259b4ae42e4ba3{d4}_plan_1",
          "planImageURL": "//ss7.vzw.com/is/image/VerizonWireless/GoUnlimited_Logo_Carousel",
          "accountAccess": {
            "name": "Go Unlimited",
            "price": "200.00",
            "discountPrice": 0.0,
            "promoMessage": null,
            "hasEcpdDiscount": false,
            "planAmount": "200.00",
            "originalPlanAmount": "0.00"
          },
          "dueMonthly": 10.0,
          "dueMonthlyOriginal": 20.0,
          "planCommerceItemId": "SDCf5f50308e587661f31259b4ae42e4ba3{d4}_plan_1",
          "autoPayText": "you are getting $0.0 for paper-free billing and AutoPay.",
          "termsAndConditionKey": "TNC_GoUnlimited"
        }
      ],
      "newDevices": [
        {
          "name": "iPhone&reg; 8 Plus",
          "price": "40.00",
          "discountPrice": 0.0,
          "hasEcpdDiscount": false,
          "mtn": null,
          "listPrice": 40.0,
          "deviceLineItemId": "sku2680218",
          "discountPriceVal": "0.00",
          "planCommerceItemId": null,
          "nickName": null,
          "numberShareDevice": false,
          "featureDropped": false
        },
        {
          "name": "Pixel 2 XL",
          "price": "40.00",
          "discountPrice": 0.0,
          "hasEcpdDiscount": false,
          "mtn": null,
          "listPrice": 40.0,
          "deviceLineItemId": "SDCf5f50308e587661f31259b4ae42e4ba3{d4}_device_1",
          "discountPriceVal": "0.00",
          "planCommerceItemId": null,
          "nickName": null,
          "numberShareDevice": false,
          "featureDropped": false
        }
      ],
      "upgradeDevices": [
        
      ],
      "existingDevices": [
        {
          "name": null,
          "price": null,
          "discountPrice": 0.0,
          "hasEcpdDiscount": false,
          "mtn": "8283615157",
          "listPrice": 200.0,
          "deviceLineItemId": null,
          "discountPriceVal": null,
          "planCommerceItemId": "SDCf5f50308e587661f31259b4ae42e4ba3{d4}_plan_1",
          "nickName": "test",
          "numberShareDevice": false,
          "featureDropped": false
        },
        {
          "name": null,
          "price": null,
          "discountPrice": 0.0,
          "hasEcpdDiscount": false,
          "mtn": "8283615156",
          "listPrice": 200.0,
          "deviceLineItemId": null,
          "discountPriceVal": null,
          "planCommerceItemId": "SDCf5f50308e587661f31259b4ae42e4ba3{d4}_plan_1",
          "nickName": "test",
          "numberShareDevice": false,
          "featureDropped": false
        },
        {
          "name": null,
          "price": null,
          "discountPrice": 0.0,
          "hasEcpdDiscount": false,
          "mtn": "7274335800",
          "listPrice": 200.0,
          "deviceLineItemId": null,
          "discountPriceVal": null,
          "planCommerceItemId": "SDCf5f50308e587661f31259b4ae42e4ba3{d4}_plan_1",
          "nickName": "test",
          "numberShareDevice": false,
          "featureDropped": false
        },
        {
          "name": null,
          "price": null,
          "discountPrice": 0.0,
          "hasEcpdDiscount": false,
          "mtn": "7272129496",
          "listPrice": 200.0,
          "deviceLineItemId": null,
          "discountPriceVal": null,
          "planCommerceItemId": "SDCf5f50308e587661f31259b4ae42e4ba3{d4}_plan_1",
          "nickName": "test",
          "numberShareDevice": false,
          "featureDropped": false
        }
      ],
      "dueMonthlyPlanWithLAC": "200.00",
      "discountedDueMonthlyPlanWithLAC": "0.00",
      "existingDevicesLAC": "120.00",
      "discountedExistingDevicesLAC": "0.00"
    },
    "accessories": [
      
    ],
    "cartEdited": false,
    "iconicFlow": false,
    "removePromoCodeURL": "/od/cust/auth/cart/removePromoCode",
    "applyPromoCodeURL": "/od/cust/auth/cart/applyPromoCode",
    "clearCartURL": "/od/cust/auth/cart/clearCart",
    "addOrUpdateDeviceURL": "/od/cust/auth/cart/addOrUpdateDevice",
    "addOrRemoveAccessoryURL": "/od/cust/auth/cart/addOrRemoveAccessory",
    "changeZipCodeURL": "/od/cust/auth/cart/changezipcode/",
    "addOrUpdateFeatureURL": "/od/cust/auth/cart/addOrUpdateFeature",
    "initiateCheckoutURL": "/od/cust/auth/checkout/initiateCheckout",
    "guestCheckoutSignInURL": null,
    "accountMember": false,
    "accessoriesBundle": null,
    "taxDetails": {
      "taxPrice": "111.37",
      "cityStateString": "Hayesville, NC",
      "stateTaxLabel": null,
      "zipCode": null
    },
    "totalDueToday": "111.37",
    "totalDueMonthly": "81.74",
    "employeeDiscount": 0,
    "pastDueBalance": "0.00",
    "emptyCartFlag": false,
    "edgeContractDeviceInCart": true,
    "totalEdgeUpAmount": "0.00",
    "totalEdgeUpBuyOutAmount": "0.00",
    "totalEdgeOrderDownPayment": "0.00",
    "tradeInCredit": null,
    "tradeInPromoDetails": null,
    "promotionList": null,
    "cartMessages": {
      "cartReadyforCheckout": false,
      "message": "Line level plan is not selected, please choose plan and continue.",
      "code": "ERROR"
    },
    "cartItemCount": 2,
    "mailInRebateTotal": 0,
    "mailInRebateDetails": null,
    "promoCodes": null,
    "promoCodeHeader": "Promo code? Lucky you.",
    "promoCodeLabel": "Promo code",
    "addAnotherPromoCodeText": "Add another promo code",
    "applyBtn": "Apply",
    "emptyCartMessage": "There are no items in your cart",
    "shopBtn": "Shop",
    "tradeInPromoEligible": true,
    "eligibleForSingleDeviceRibbon": false,
    "eligibleForMultiDeviceAllocation": false,
    "retrieveCartSuccessful": false,
    "standaloneAccessories": false,
    "dueTodayText": "Due today",
    "dueMonthlyText": "Due Monthly",
    "mainCartHeader": "Time to review your cart.",
    "mainCartSubTitle": "Enjoy free 2-day shipping",
    "mainCartNextDayShippingMessage": null,
    "shopMoreBtnText": "Shop more",
    "checkoutBtn": "Check out",
    "editBtn": "Edit",
    "removeLinkText": "Remove",
    "mainCartFooterText": "Want to start over?",
    "mainCartFooterLinkText": "Emtpy your cart",
    "shopMoreLink": "/od/cust/auth/shoplanding/",
    "activationFeeText": "Activation Fee",
    "waivedActivationText": "Waived Activation Fee",
    "upgradeFeeText": "Upgrade Fee",
    "waivedUpgradeFeeText": "Waived Upgrade Fee",
    "saveBtnLabel": "Save",
    "zipCodeHeader": "Please enter a new ZIP code",
    "tradeInCreditHeader": "Trade-in Credit for this device",
    "tradeInFooterLink": "Tell me more",
    "tradeInOfferDetailsHeader": "Offer Details",
    "tradeInOfferDetailsMsg": "long block of text",
    "tradeInConfirmationBtn": "Got it",
    "lonelyCartMessage": "Your cart is lonely.",
    "lonelyCartSubMessage": null,
    "checkoutButtonURL": "/od/cust/auth/checkout/initiateCheckout",
    "tradeInUrl": "/od/trade-in/auth?gotoCart=true",
    "mainInRebateDetails": null,
    "deviceProtectionDetails": {
      "deviceProtectionDetailsHeader": "device protection details",
      "deviceProtectionDetailsSubTitle": "Five things you need to know about Equipment Protection",
      "deviceProtectionDetailsText": "<div> <p>Cost per Month and Individual Service Availability. Total Mobile Protection (TMP) Single Device and Total Mobile Protection Multi-Device are a combination of multiple products, each of which is available separately per device: Wireless Phone Protection (WPP) $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; Verizon Wireless Extended Warranty (EW) $3.00; and Verizon Tech Coach $7.00. You may also purchase Total Equipment Coverage (TEC) for $7.00/Basic Devices &amp; Tablets or for $9.00/Smartphones &amp; iPhone Devices. TEC is a combination of 2 products, each of which is available separately: WPP $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; and Verizon Wireless EW for $3.00.</p> <p> Applicability and Amount of Deductible.  For lost, stolen and damaged device claims, deductibles are $49 for basic phones and, depending on device, $49-$199 for smartphones and tablets. For a full list of deductibles click here <a href='http://phoneclaim.com/verizon/deductible' target='_blank'>http://phoneclaim.com/verizon/deductible.</a> </p> <p>Claim Limits for loss, stolen and damaged devices. Equipment claim maximum is $400 or $1,500, depending on device, and limited to three claims per 12-month period for TMP Single Device and up to nine claims per 12-month period for TMP Multi-Device.</p> <p>Covered and Replacement Equipment. If your device is lost, stolen or damaged, your accessories are covered too ï¿1Ž2 one each of the following: standard battery, standard car charger, standard case, standard home charger and standard earbud. It is our goal to provide you with a replacement device that is the same color and has the same features, but this cannot be guaranteed. If the same make and model you claim is not available, a similar make and model will be substituted. Your replacement device could be new or refurbished. You may also receive generic accessories with lost, stolen or damaged claims.</p> <p>Cancellation Policy. Change your mind? You can cancel your coverage at any time and receive a pro-rated refund of your monthly fee.</p> </div>"
    },
    "preOrderAlertMsg": "Your order contains one or more items that are not in stock. All items will ship together when everything is available.",
    "bicText": null,
    "hasSubmittedTradein": false,
    "cpcSucessful": true,
    "cpcSucessfulNotification": true,
    "protectionURL": "/od/cust/auth/protection",
    "itemsFromRetrievedCart": false,
    "totalActivationFee": "60.00",
    "itemOnJaxPlan": false,
    "anyLineFreeSPO": null,
    "paypalEnabled": false,
    "paypalApi": "/od/cust/auth/checkout/paypal/cmpilookup?triggerFrom=PAYMENT",
    "aalUrl": "/od/cust/auth/shop?flow=AAL",
    "eupUrl": "/od/cust/auth/shop?flow=EUP",
    "rawSubTotalDueToday": "0.00",
    "overallDueMonthly": "281.74",
    "additionalCharges": [
      {
        "taxPrice": "78.37",
        "cityStateString": null,
        "stateTaxLabel": "NC State Sales Tax",
        "zipCode": null
      },
      {
        "taxPrice": "78.37",
        "cityStateString": null,
        "stateTaxLabel": "NC State Sales Tax",
        "zipCode": null
      }
    ],
    "accessoryGWURL": "/od/cust/auth/accessories/",
    "accessoryPDPURL": "/od/cust/auth/accessoryDetails/",
    "removeTradeInURL": "/od/trade-in/removeTradeIn",
    "masterpassEnabled": false,
    "targetter": {
      "freeShippingText": "Free Shipping or In-Store Pickup",
      "freeShippingDesc": "Free shipping \n Free 2-day shipping when you order online M-F by 8PM EST, Sat by 2PM EST (excluding holidays), will deliver in two business days within the U.S. only (excluding AK & HI). 2-day orders placed after 2PM EST on Sat will deliver by Wednesday. Overnight shipping to destinations within the U.S. (excluding AK & HI) is generally available for orders placed M-F until 11PM EST, excluding holidays. Orders that contain a pre-order or backorder will ship via 2-day shipping on or prior to the committed date. Subject to credit authorization, verification and inventory availability.",
      "nextDayText": "Want it tomorrow? Order by 11PM ET w/Next Day Shipping. Pre-order devices excl'd",
      "nextDayDesc": "Depending on inventory availability for destinations within the US (excluding AK, HI) for orders placed M-F (excluding holidays). Next Day Shipping is not available for devices in pre-order status. Pre-order devices will ship as inventory becomes available",
      "contentText": "Keep your content.",
      "contentDesc": "Don't worry, we've got you covered. We'll make sure all of your pictures, contacts and content transfer from one phone to the other without issue.",
      "returnPolicyText": "14 day return policy",
      "returnPolicyDesc": "You may return or exchange wireless devices and accessories purchased from Verizon Wireless within 14 days of purchase. A restocking fee of $35 applies to any return or exchange of a wireless device (excluding Hawaii)."
    },
    "overallDiscountedAmount": "0.00",
    "ecpdDueTodayDiscountedAmount": "0.00",
    "ecpdDueMonthlySavings": "0.00",
    "devicesURL": null,
    "autoPayApplied": true,
    "cartURL": "/od/cust/auth/cart/getCartDetails?format=json",
    "byodUrl": "/od/cust/auth/shop?flow=NSO",
    "masterpassConfigInfo": null,
    "accessoryShopURL": "/accessories",
    "bicOfferMessage": null,
    "cartMFCompatible": true,
    "cartValidationDetailsVo": {
      "cartReadyforCheckout": false,
      "cartIncompleteCode": "Line level plan is not selected, please choose plan and continue.",
      "cartIncompleteMessage": "Line level plan is not selected, please choose plan and continue.",
      "orderId": "SDCf5f50308e587661f31259b4ae42e4ba3{d4}"
    },
    "tmpMdOpted": false,
    "tmpMd": null,
    "frontEndPersonalization": null,
    "allowAAL": true,
    "allowEUP": true,
    "splitShipment": false,
    "authenticated": true
  },
  "errorMap": null,
  "statusMessage": ""
};
*/


{"statusCode":"00","output":{"orderId":"SDC8627333ccf15cfba575eb44681839ddd{ss1}","isHLLPlanInOrder": true,"redirectionURL":null,"isPOBODeviceInCart":false,"accGuestCheckoutEnabled":null,"dueTodayPOBOHeader":null,"items":[{"deviceProdId":"dev8760136","deviceManufactureName":"Google","deviceProductDisplayName":"Pixel 2 XL","colorName":"Black and White","capacity":"64GB","flow":"AAL","mtn":null,"displayMtn":null,"deviceImageUrl":"https://ss7.vzw.com/is/image/VerizonWireless/GOOGLE_Taiman_Wht?$device-med$&fmt=jpeg&wid=75&hei=150","deviceImageUrlLarge":"https://ss7.vzw.com/is/image/VerizonWireless/GOOGLE_Taiman_Wht?$device$&bgc=ffffff&wid=158&hei=300","activationFee":"0.00","waivedActivationFeePromo":false,"upgradeFee":"0.00","waivedUpgradeFeePromo":false,"edgeDevice":true,"price":"22.91","originalPrice":"35.41","priceText":"Device payment","priceSubTitle":"1st installment will appear on your bill.","edgeItemDownPaymentAmount":"0.00","installmentBalance":"0.00","deviceEdgeUpAmount":"0.00","deviceEdgeBuyOutAmount":"0.00","protectionOption":{"name":"Total Mobile Protection","price":"13.00","originalPrice":"13.00","featureType":"INS","featureSkuId":"sku2880128","hideEditProtection":false,"displayMsg":null,"tapOpted":false},"commerceItemId":"SDC8627333ccf15cfba575eb44681839ddd{ss1}_device_1","deviceSkuId":"sku2690601","deviceSORId":"GA00152-US","lacPrice":"0.00","lacText":"Smartphone line access","inventoryStatus":"1000","inventoryAvailableDate":null,"hasEcpdDiscount":false,"hasEcpdDiscountForDevicePayment":false,"devicePromotionList":[{"promotionalMessage":null,"promoDescription":"UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION BIC YES","promoName":"UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION","promoAmount":"300.00","priceSubTitle":"1st installment will appear on your bill.","barCodeId":null,"itemCode":"GA00152-US","itemType":"ITA","sedOffer":true,"promoContentText":null}],"bicOfferApplied":false,"bicContractPrice":"0.00","bicDiscountedContractPrice":"0.00","bicSavings":"0.00","myOfferWaiveUpgradeFee":false,"shipCommitInd":null,"promoLACMessage":null,"additionalFeatures":[],"simDetails":null,"imeiId":null,"transferredFromMtn":null,"originalActivationFee":"0.00","priceForFullRetailPriceListID":"849.99","bicMessage":null,"bicMessagetooltip":null,"editDeviceUrl":"/od/pdp/dev8760136/?commerceItemId=SDC8627333ccf15cfba575eb44681839ddd%7Bss1%7D_device_1&deviceProdId=dev8760136&catalogRefId=sku2690601&editDevice=true&flow=AAL","fullRetailPrice":"849.99","fromSavedCart":false,"numberShareDevice":false,"numberSharedMtn":null,"itemOnJaxPlan":false,"humCarDetails":null,"poboAvailableDate":null,"planCommerceItemId":"SDC8627333ccf15cfba575eb44681839ddd{ss1}_plan_1","monthlyPriceAfterDownPaymentBeforeDiscount":0.0,"originalFullRetailPrice":0.0,"hasReducedRetailPrice":false,"hasReducedDueMonthly":false,"originalDueMonthly":0.0,"lineAccessPromotionText":null,"downPaymentPromotionText":null,"contractTerm":"99","deviceType":"SMARTPHONE","activationFeeText":null,"promoOfferText":null,"promoApplied":false,"portIn":false,"deviceNickName":"Pixel 2 XL","totalNumberShareExtension":0,"originalUpgradeFee":"0.00","totalSavings":"300.00","sbdOffer":null,"hostCommerceItemId":null,"trunkMtn":null,"discountedEdgeRetailPrice":"549.99","displayImeiId":null,"featureDropped":false,"upgradeFeeWaived":false,"activationFeeWaived":false}],"existingDevices":null,"plans":{"planOnlyDueMonthly":"0.00","dueMonthly":"0.00","dueToday":"0.00","items":[{"planType":"Test Plan 2G Smartphone","planSorId":"17991","planProdId":"plan5600003","planSkuId":"sku3060010","planLetter":null,"planDescription":"","planDisplayName":"Test Plan 2G Smartphone","planChangeURL":"/od/cust/auth/compatiblePlans?editPlan=true&planSorId=17991&flow=null&planCommId=SDC8627333ccf15cfba575eb44681839ddd{ss1}_plan_1","planImageURL":null,"accountAccess":{"name":"Test Plan 2G Smartphone","price":"0.00","discountPrice":0.0,"promoMessage":null,"hasEcpdDiscount":false,"planAmount":"0.00","originalPlanAmount":"0.00"},"dueMonthly":0.0,"dueMonthlyOriginal":0.0,"planCommerceItemId":"SDC8627333ccf15cfba575eb44681839ddd{ss1}_plan_1","autoPayText":"Save $0.0 when you signup for paper-free billing and AutoPay.","termsAndConditionKey":"TNC_TestPlan2GSmartphone"}],"newDevices":[{"name":"Pixel 2 XL","price":"65.00","discountPrice":0.0,"hasEcpdDiscount":false,"mtn":null,"listPrice":65.0,"deviceLineItemId":"sku2690601","discountPriceVal":"0.00","planCommerceItemId":null,"nickName":null,"numberShareDevice":false,"featureDropped":false}],"upgradeDevices":[],"existingDevices":[{"name":null,"price":null,"discountPrice":0.0,"hasEcpdDiscount":false,"mtn":"8156777298","listPrice":80.0,"deviceLineItemId":null,"discountPriceVal":null,"planCommerceItemId":"SDC8627333ccf15cfba575eb44681839ddd{ss1}_plan_1","nickName":"test","numberShareDevice":false,"featureDropped":false},{"name":null,"price":null,"discountPrice":0.0,"hasEcpdDiscount":false,"mtn":"8153708512","listPrice":80.0,"deviceLineItemId":null,"discountPriceVal":null,"planCommerceItemId":"SDC8627333ccf15cfba575eb44681839ddd{ss1}_plan_1","nickName":"test","numberShareDevice":false,"featureDropped":false},{"name":null,"price":null,"discountPrice":0.0,"hasEcpdDiscount":false,"mtn":"8155924916","listPrice":80.0,"deviceLineItemId":null,"discountPriceVal":null,"planCommerceItemId":"SDC8627333ccf15cfba575eb44681839ddd{ss1}_plan_1","nickName":"test","numberShareDevice":false,"featureDropped":false},{"name":null,"price":null,"discountPrice":0.0,"hasEcpdDiscount":false,"mtn":"8155925645","listPrice":80.0,"deviceLineItemId":null,"discountPriceVal":null,"planCommerceItemId":"SDC8627333ccf15cfba575eb44681839ddd{ss1}_plan_1","nickName":"test","numberShareDevice":false,"featureDropped":false}],"dueMonthlyPlanWithLAC":"235.00","discountedDueMonthlyPlanWithLAC":"0.00","existingDevicesLAC":"170.00","discountedExistingDevicesLAC":"0.00"},"accessories":[],"cartEdited":false,"iconicFlow":false,"removePromoCodeURL":"/od/cust/auth/cart/removePromoCode","applyPromoCodeURL":"/od/cust/auth/cart/applyPromoCode","clearCartURL":"/od/cust/auth/cart/clearCart","addOrUpdateDeviceURL":"/od/cust/auth/cart/addOrUpdateDevice","addOrRemoveAccessoryURL":"/od/cust/auth/cart/addOrRemoveAccessory","changeZipCodeURL":"/od/cust/auth/cart/changezipcode/","addOrUpdateFeatureURL":"/od/cust/auth/cart/addOrUpdateFeature","initiateCheckoutURL":"/od/cust/auth/checkout/initiateCheckout","guestCheckoutSignInURL":null,"accountMember":false,"accessoriesBundle":null,"taxDetails":{"taxPrice":"45.37","cityStateString":"Mission, TX","stateTaxLabel":null,"zipCode":null},"totalDueToday":"45.37","totalDueMonthly":"35.91","employeeDiscount":0,"pastDueBalance":"0.00","emptyCartFlag":false,"edgeContractDeviceInCart":true,"totalEdgeUpAmount":"0.00","totalEdgeUpBuyOutAmount":"0.00","totalEdgeOrderDownPayment":"0.00","tradeInCredit":null,"tradeInPromoDetails":null,"promotionList":[{"promoMsg":"UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION BIC YES","promoAmount":"300.00","barcode":null,"skuId":"GA00152-US","offerLevel":null}],"cartMessages":{"cartReadyforCheckout":true,"message":"","code":null},"cartItemCount":1,"mailInRebateTotal":0,"mailInRebateDetails":null,"promoCodes":[null],"promoCodeHeader":"Promo code? Lucky you.","promoCodeLabel":"Promo code","addAnotherPromoCodeText":"Add another promo code","applyBtn":"Apply","emptyCartMessage":"There are no items in your cart","shopBtn":"Shop","tradeInPromoEligible":true,"eligibleForSingleDeviceRibbon":false,"eligibleForMultiDeviceAllocation":false,"retrieveCartSuccessful":false,"standaloneAccessories":false,"dueTodayText":"Due today","dueMonthlyText":"Due Monthly","mainCartHeader":"Time to review your cart.","mainCartSubTitle":"Enjoy free 2-day shipping","mainCartNextDayShippingMessage":null,"shopMoreBtnText":"Shop more","checkoutBtn":"Check out","editBtn":"Edit","removeLinkText":"Remove","mainCartFooterText":"Want to start over?","mainCartFooterLinkText":"Emtpy your cart","shopMoreLink":"/od/cust/auth/shoplanding/","activationFeeText":"Activation Fee","waivedActivationText":"Waived Activation Fee","upgradeFeeText":"Upgrade Fee","waivedUpgradeFeeText":"Waived Upgrade Fee","saveBtnLabel":"Save","zipCodeHeader":"Please enter a new ZIP code","tradeInCreditHeader":"Trade-in Credit for this device","tradeInFooterLink":"Tell me more","tradeInOfferDetailsHeader":"Offer Details","tradeInOfferDetailsMsg":"long block of text","tradeInConfirmationBtn":"Got it","lonelyCartMessage":"Your cart is lonely.","lonelyCartSubMessage":null,"checkoutButtonURL":"/od/cust/auth/checkout/initiateCheckout","tradeInUrl":"/od/trade-in/auth?gotoCart=true","mainInRebateDetails":null,"deviceProtectionDetails":{"deviceProtectionDetailsHeader":"device protection details","deviceProtectionDetailsSubTitle":"Five things you need to know about Equipment Protection","deviceProtectionDetailsText":"<div> <p>Cost per Month and Individual Service Availability. Total Mobile Protection (TMP) Single Device and Total Mobile Protection Multi-Device are a combination of multiple products, each of which is available separately per device: Wireless Phone Protection (WPP) $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; Verizon Wireless Extended Warranty (EW) $3.00; and Verizon Tech Coach $7.00. You may also purchase Total Equipment Coverage (TEC) for $7.00/Basic Devices &amp; Tablets or for $9.00/Smartphones &amp; iPhone Devices. TEC is a combination of 2 products, each of which is available separately: WPP $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; and Verizon Wireless EW for $3.00.</p> <p> Applicability and Amount of Deductible.  For lost, stolen and damaged device claims, deductibles are $49 for basic phones and, depending on device, $49-$199 for smartphones and tablets. For a full list of deductibles click here <a href='http://phoneclaim.com/verizon/deductible' target='_blank'>http://phoneclaim.com/verizon/deductible.</a> </p> <p>Claim Limits for loss, stolen and damaged devices. Equipment claim maximum is $400 or $1,500, depending on device, and limited to three claims per 12-month period for TMP Single Device and up to nine claims per 12-month period for TMP Multi-Device.</p> <p>Covered and Replacement Equipment. If your device is lost, stolen or damaged, your accessories are covered too ï¿1Ž2 one each of the following: standard battery, standard car charger, standard case, standard home charger and standard earbud. It is our goal to provide you with a replacement device that is the same color and has the same features, but this cannot be guaranteed. If the same make and model you claim is not available, a similar make and model will be substituted. Your replacement device could be new or refurbished. You may also receive generic accessories with lost, stolen or damaged claims.</p> <p>Cancellation Policy. Change your mind? You can cancel your coverage at any time and receive a pro-rated refund of your monthly fee.</p> </div>"},"preOrderAlertMsg":"Your order contains one or more items that are not in stock. All items will ship together when everything is available.","bicText":null,"hasSubmittedTradein":false,"cpcSucessful":true,"cpcSucessfulNotification":true,"protectionURL":"/od/cust/auth/protection","itemsFromRetrievedCart":false,"totalActivationFee":"0.00","itemOnJaxPlan":false,"anyLineFreeSPO":null,"paypalEnabled":false,"paypalApi":"/od/cust/auth/checkout/paypal/cmpilookup?triggerFrom=PAYMENT","aalUrl":"/od/cust/auth/shop?flow=AAL","eupUrl":"/od/cust/auth/shop?flow=EUP","rawSubTotalDueToday":"0.00","overallDueMonthly":"205.91","additionalCharges":[{"taxPrice":"34.37","cityStateString":null,"stateTaxLabel":"TX State Sales Tax","zipCode":null},{"taxPrice":"34.37","cityStateString":null,"stateTaxLabel":"TX State Sales Tax","zipCode":null}],"accessoryGWURL":"/od/cust/auth/accessories/","accessoryPDPURL":"/od/cust/auth/accessoryDetails/","removeTradeInURL":"/od/trade-in/removeTradeIn","masterpassEnabled":false,"targetter":{"freeShippingText":"Free Shipping or In-Store Pickup","freeShippingDesc":"Free shipping \n Free 2-day shipping when you order online M-F by 8PM EST, Sat by 2PM EST (excluding holidays), will deliver in two business days within the U.S. only (excluding AK & HI). 2-day orders placed after 2PM EST on Sat will deliver by Wednesday. Overnight shipping to destinations within the U.S. (excluding AK & HI) is generally available for orders placed M-F until 11PM EST, excluding holidays. Orders that contain a pre-order or backorder will ship via 2-day shipping on or prior to the committed date. Subject to credit authorization, verification and inventory availability.","nextDayText":"Want it tomorrow? Order by 11PM ET w/Next Day Shipping. Pre-order devices excl'd","nextDayDesc":"Depending on inventory availability for destinations within the US (excluding AK, HI) for orders placed M-F (excluding holidays). Next Day Shipping is not available for devices in pre-order status. Pre-order devices will ship as inventory becomes available","contentText":"Keep your content.","contentDesc":"Don't worry, we've got you covered. We'll make sure all of your pictures, contacts and content transfer from one phone to the other without issue.","returnPolicyText":"14 day return policy","returnPolicyDesc":"You may return or exchange wireless devices and accessories purchased from Verizon Wireless within 14 days of purchase. A restocking fee of $35 applies to any return or exchange of a wireless device (excluding Hawaii)."},"overallDiscountedAmount":"0.00","ecpdDueTodayDiscountedAmount":"0.00","ecpdDueMonthlySavings":"0.00","devicesURL":null,"autoPayApplied":false,"cartURL":"/od/cust/auth/cart/getCartDetails?format=json","byodUrl":"/od/cust/auth/shop?flow=NSO","masterpassConfigInfo":null,"accessoryShopURL":"/accessories","bicOfferMessage":null,"cartMFCompatible":true,"cartValidationDetailsVo":{"cartReadyforCheckout":true,"cartIncompleteCode":null,"cartIncompleteMessage":null,"orderId":"SDC8627333ccf15cfba575eb44681839ddd{ss1}"},"tmpMdOpted":false,"tmpMd":null,"frontEndPersonalization":null,"allowAAL":true,"allowEUP":true,"splitShipment":false,"authenticated":true,"hllplanInOrder":true},"errorMap":null,"statusMessage":""};

export default cartJSON;
