const cartJSON = 
{
  "statusCode": "00",
  "output": {
    "instantCreditEligible": true,    
    "cartItemCount": 2,
    "instantTradeInDevicesCount": 3,
    "instantCreditPageURL": "/od/cust/auth/cart/instantcreditallocation",
    "instantCreditTradeinSummary": {
      "optionalDownPayment": [
        {
          "deviceTitle": "iPhone&reg; 8 down payment",
          "optionalDownPaymentAmt": "100.99"
        },
        {
          "deviceTitle": "iPhone&reg; 8 down payment",
          "optionalDownPaymentAmt": "142.01"
        }
      ],
      "twoYearDevicesInstantCredit": null,
      "fullRetailInstantCredit": null,
      "accessoriesInsantCredit": null,
      "taxesInstantCredit": "42.99",
      "accountCredit": "357.99",
      "instantCreditHeaderTxt": null
    },
    "instantCreditAppliedOnOrder": 142.01,
    "orderId": "S0b66b22710469c849f6754f5e64b2ab3{ss1}",
    "redirectionURL": null,
    "isPOBODeviceInCart": false,
    "accGuestCheckoutEnabled": false,
    "dueTodayPOBOHeader": null,
    "items": [
      {
        "deviceProdId": "dev8720046",
        "deviceManufactureName": "Apple",
        "deviceProductDisplayName": "iPhone&reg; 8",
        "colorName": "Space Gray",
        "capacity": "64GB",
        "flow": "AAL",
        "mtn": null,
        "displayMtn": null,
        "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iPhone8-SpGry?$device-med$&fmt=jpeg&wid=75&hei=150",
        "deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/iPhone8-SpGry?$device$&bgc=ffffff&wid=158&hei=300",
        "activationFee": "30.00",
        "waivedActivationFeePromo": false,
        "upgradeFee": "0.00",
        "waivedUpgradeFeePromo": false,
        "edgeDevice": true,
        "price": "0.01",
        "originalPrice": "29.16",
        "priceText": "Device payment",
        "priceSubTitle": "For 24 months, 0% APR.Retail Price: ",
        "edgeItemDownPaymentAmount": "0.00",
        "installmentBalance": "0.00",
        "deviceEdgeUpAmount": "0.00",
        "deviceEdgeBuyOutAmount": "0.00",
        "protectionOption": null,
        "commerceItemId": "S0b66b22710469c849f6754f5e64b2ab3{ss1}_device_1",
        "deviceSkuId": "sku2680236",
        "deviceSORId": "MQ722LL/A",
        "lacPrice": "0.00",
        "lacText": "Smartphone line access",
        "inventoryStatus": "1000",
        "inventoryAvailableDate": null,
        "hasEcpdDiscount": false,
        "hasEcpdDiscountForDevicePayment": false,
        "devicePromotionList": [
          {
            "promotionalMessage": null,
            "promoDescription": "UAT BUY IPHN 8 SAM GALAXY S8 GET IPHN 8 SAM GAL S8 BIC YES",
            "promoName": "UAT BUY IPHN 8 SAM GALAXY S8 GET IPHN 8 SAM GAL S8",
            "promoAmount": "699.75",
            "priceSubTitle": "1st installment will appear on your bill.",
            "barCodeId": null,
            "itemCode": "MQ722LL/A",
            "itemType": "ITP",
            "sedOffer": true,
            "isUpgradeFeeWaivedOffer": false,
            "promoBadgeMessages": null,
            "promoContentText": null
          }
        ],
        "bicOfferApplied": false,
        "bicContractPrice": "0.00",
        "bicDiscountedContractPrice": "0.00",
        "bicSavings": "0.00",
        "myOfferWaiveUpgradeFee": false,
        "shipCommitInd": null,
        "promoLACMessage": null,
        "additionalFeatures": [
          
        ],
        "simDetails": null,
        "imeiId": null,
        "transferredFromMtn": null,
        "originalActivationFee": "30.00",
        "protectionInEligible": false,
        "nickName": null,
        "priceForFullRetailPriceListID": "699.99",
        "bicMessage": null,
        "bicMessagetooltip": null,
        "editDeviceUrl": "/od/pdp/dev8720046/?commerceItemId=S0b66b22710469c849f6754f5e64b2ab3%7Bss1%7D_device_1&deviceProdId=dev8720046&catalogRefId=sku2680236&editDevice=true&flow=AAL",
        "fullRetailPrice": "699.99",
        "fromSavedCart": false,
        "numberShareDevice": false,
        "numberSharedMtn": null,
        "itemOnJaxPlan": false,
        "humCarDetails": null,
        "poboAvailableDate": null,
        "planCommerceItemId": null,
        "monthlyPriceAfterDownPaymentBeforeDiscount": 0.0,
        "originalFullRetailPrice": 0.0,
        "hasReducedRetailPrice": false,
        "hasReducedDueMonthly": false,
        "originalDueMonthly": 0.0,
        "lineAccessPromotionText": null,
        "downPaymentPromotionText": null,
        "contractTerm": "99",
        "deviceType": "SMARTPHONE",
        "activationFeeText": "One-time activation fee of $30.0 charged to your next monthly bill.",
        "promoOfferText": null,
        "promoApplied": false,
        "portIn": false,
        "deviceNickName": "iPhone&reg; 8",
        "totalNumberShareExtension": 0,
        "originalUpgradeFee": "0.00",
        "totalSavings": "699.75",
        "instantCreditAppliedAmount": "100.01",
        "instantCreditAppliedInfo": "Instant credit applied to optional down payment: -$100.04",
        "instantCreditAdjustedPrice": "99.76",
        "instantCreditFullRetailPrice": "0.24",
        "sbdOffer": null,
        "hostCommerceItemId": null,
        "trunkMtn": null,
        "discountedEdgeRetailPrice": "0.24",
        "displayImeiId": null,
        "featureDropped": false,
        "changePlanUrl": "",
        "upgradeFeeWaived": false,
        "activationFeeWaived": false
      },
      {
        "deviceProdId": "dev8720046",
        "deviceManufactureName": "Apple",
        "deviceProductDisplayName": "iPhone&reg; 8",
        "colorName": "Space Gray",
        "capacity": "64GB",
        "flow": "AAL",
        "mtn": null,
        "displayMtn": null,
        "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iPhone8-SpGry?$device-med$&fmt=jpeg&wid=75&hei=150",
        "deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/iPhone8-SpGry?$device$&bgc=ffffff&wid=158&hei=300",
        "activationFee": "30.00",
        "waivedActivationFeePromo": false,
        "upgradeFee": "0.00",
        "waivedUpgradeFeePromo": false,
        "edgeDevice": true,
        "price": "29.16",
        "originalPrice": "29.16",
        "priceText": "Device payment",
        "priceSubTitle": "For 24 months, 0% APR.Retail Price: ",
        "edgeItemDownPaymentAmount": "0.00",
        "installmentBalance": "0.00",
        "deviceEdgeUpAmount": "0.00",
        "deviceEdgeBuyOutAmount": "0.00",
        "protectionOption": null,
        "commerceItemId": "S0b66b22710469c849f6754f5e64b2ab3{ss1}_device_2",
        "deviceSkuId": "sku2680236",
        "deviceSORId": "MQ722LL/A",
        "lacPrice": "0.00",
        "lacText": "Smartphone line access",
        "inventoryStatus": "1000",
        "inventoryAvailableDate": null,
        "hasEcpdDiscount": false,
        "hasEcpdDiscountForDevicePayment": false,
        "devicePromotionList": [
          {
            "promotionalMessage": null,
            "promoDescription": "UAT BUY IPHN 8 SAM GALAXY S8 GET IPHN 8 SAM GAL S8 BIC YES",
            "promoName": "UAT BUY IPHN 8 SAM GALAXY S8 GET IPHN 8 SAM GAL S8",
            "promoAmount": "0.00",
            "priceSubTitle": "1st installment will appear on your bill.",
            "barCodeId": null,
            "itemCode": "MQ722LL/A",
            "itemType": "BOGT",
            "sedOffer": true,
            "isUpgradeFeeWaivedOffer": false,
            "promoBadgeMessages": null,
            "promoContentText": null
          }
        ],
        "bicOfferApplied": false,
        "bicContractPrice": "0.00",
        "bicDiscountedContractPrice": "0.00",
        "bicSavings": "0.00",
        "myOfferWaiveUpgradeFee": false,
        "shipCommitInd": null,
        "promoLACMessage": null,
        "additionalFeatures": [
          
        ],
        "simDetails": null,
        "imeiId": null,
        "transferredFromMtn": null,
        "originalActivationFee": "30.00",
        "protectionInEligible": false,
        "nickName": null,
        "priceForFullRetailPriceListID": "699.99",
        "bicMessage": null,
        "bicMessagetooltip": null,
        "editDeviceUrl": "/od/pdp/dev8720046/?commerceItemId=S0b66b22710469c849f6754f5e64b2ab3%7Bss1%7D_device_2&deviceProdId=dev8720046&catalogRefId=sku2680236&editDevice=true&flow=AAL",
        "fullRetailPrice": "699.99",
        "fromSavedCart": false,
        "numberShareDevice": false,
        "numberSharedMtn": null,
        "itemOnJaxPlan": false,
        "humCarDetails": null,
        "poboAvailableDate": null,
        "planCommerceItemId": null,
        "monthlyPriceAfterDownPaymentBeforeDiscount": 0.0,
        "originalFullRetailPrice": 0.0,
        "hasReducedRetailPrice": false,
        "hasReducedDueMonthly": false,
        "originalDueMonthly": 0.0,
        "lineAccessPromotionText": null,
        "downPaymentPromotionText": null,
        "contractTerm": "99",
        "deviceType": "SMARTPHONE",
        "activationFeeText": "One-time activation fee of $30.0 charged to your next monthly bill.",
        "promoOfferText": null,
        "promoApplied": false,
        "portIn": false,
        "deviceNickName": "iPhone&reg; 8",
        "totalNumberShareExtension": 0,
        "originalUpgradeFee": "0.00",
        "totalSavings": null,
        "instantCreditAppliedAmount": "142.0",
        "instantCreditAppliedInfo": "Instant credit applied to optional down payment: 142.0",
        "instantCreditAdjustedPrice": "557.99",
        "instantCreditFullRetailPrice": "699.99",
        "sbdOffer": null,
        "hostCommerceItemId": null,
        "trunkMtn": null,
        "discountedEdgeRetailPrice": "699.99",
        "displayImeiId": null,
        "featureDropped": false,
        "changePlanUrl": "",
        "upgradeFeeWaived": false,
        "activationFeeWaived": false
      }
    ],
    "existingDevices": null,
    "plans": {
      "planOnlyDueMonthly": "30.00",
      "dueMonthly": "30.00",
      "dueToday": "0.00",
      "items": [
        {
          "planType": "The Verizon Plan Small 1GB",
          "planSorId": "94156",
          "planProdId": "plan2440001",
          "planSkuId": "sku1700078",
          "planLetter": null,
          "planDescription": "",
          "planDisplayName": "The Verizon Plan Small 1GB",
          "planChangeURL": null,
          "planImageURL": "",
          "accountAccess": {
            "name": "The Verizon Plan Small 1GB",
            "price": "30.00",
            "discountPrice": "0.00",
            "promoMessage": null,
            "hasEcpdDiscount": false,
            "planAmount": "30.00",
            "originalPlanAmount": "30.00"
          },
          "dueMonthly": "30.00",
          "dueMonthlyOriginal": "0.00",
          "planCommerceItemId": null,
          "autoPayText": null,
          "termsAndConditionKey": null,
          "unitOfMeasure": "GB",
          "subsidyIndicator": false,
          "subsidyCost": null,
          "planSize": "1"
        }
      ],
      "newDevices": null,
      "upgradeDevices": null,
      "existingDevices": null,
      "dueMonthlyPlanWithLAC": null,
      "discountedDueMonthlyPlanWithLAC": null,
      "existingDevicesLAC": null,
      "discountedExistingDevicesLAC": null
    },
    "accessories": [
      {
        "scene7ImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/jbl-link-10-voice-activated-portable-speaker-black-jbllink10blkus-iset?$acc-med$",
        "name": "Link 10 Voice-Activated Speaker",
        "instantCreditAppliedInfo": "Instant credit applied to optimal down Payment: -$30.35",
        "instantCreditAdjustedPrice": "90.40",
        "quantity": 1,
        "commerceItemId": "S078068663cdf2a7ff54bd1c1f9378975{ss100}_accessory_1",
        "color": "Black",
        "size": null,
        "inventoryStatus": "1000",
        "inventoryAvailableDate": null,
        "prodId": "acc8520167",
        "skuId": "sku2630450",
        "sorId": "JBLLINK10BLKUS",
        "hasEcpdDiscount": false,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/jbl-link-10-voice-activated-portable-speaker-black-jbllink10blkus-iset?$acc-med$",
        "hasBogoDiscount": false,
        "price": 99.99,
        "wasPrice": 149.99,
        "discounted": true,
        "discountPercentage": 33.34,
        "discountPrice": 50.0,
        "editAccessoryUrl": "/accessories/jbl-link-10-voice-activated-speaker/?accProdId=acc8520167&accSkuId=sku2630450&action=edit&accCommerceId=S078068663cdf2a7ff54bd1c1f9378975{ss100}_accessory_1",
        "hideEditLink": false,
        "standaloneAccessory": true,
        "featureDropped": false
      }
    ],
    "cartEdited": false,
    "iconicFlow": false,
    "removePromoCodeURL": "/od/cust/auth/cart/removePromoCode",
    "applyPromoCodeURL": "/od/cust/auth/cart/applyPromoCode",
    "clearCartURL": "/od/cust/auth/cart/clearCart",
    "addOrUpdateDeviceURL": "/od/cust/auth/cart/addOrUpdateDevice",
    "addOrRemoveAccessoryURL": "/od/cust/auth/cart/addOrRemoveAccessory",
    "changeZipCodeURL": "/od/cust/auth/cart/changezipcode/",
    "addOrUpdateFeatureURL": "/od/cust/auth/cart/addOrUpdateFeature",
    "initiateCheckoutURL": "/od/cust/auth/checkout/initiateCheckout",
    "guestCheckoutSignInURL": null,
    "accountMember": false,
    "removeDeviceURL": null,
    "enableRemoveDeviceAndMMPlan": false,
    "accessoriesBundle": null,
    "taxDetails": {
      "taxPrice": "42.01",
      "cityStateString": "Rockville, MD",
      "stateTaxLabel": null,
      "zipCode": null,
      "totalSalesTax": "45.45",
      "instantCreditAppliedOnSaleTax": "17.10"
    },
    "totalDueToday": "42.01",
    "totalDueMonthly": "29.17",
    "employeeDiscount": 0,
    "pastDueBalance": "0.00",
    "emptyCartFlag": false,
    "edgeContractDeviceInCart": true,
    "totalEdgeUpAmount": "0.00",
    "totalEdgeUpBuyOutAmount": "0.00",
    "totalEdgeOrderDownPayment": "0.00",
    "tradeInCredit": "735.00",
    "tradeInPromoDetails": {
      "tradeInDeviceDppMsg": "We'll send you a prepaid box to mail in your trade-in. This is only an estimate until we receive and appraise your device.",
      "warningMessage": null,
      "tradeInDeviceHeaderMsg": "You'll see an estimated $735.00 credit within 1-2 bill cycles.",
      "tradeInCredit": "735.00",
      "tradeInSubmissionIdRequried": false,
      "tradeInSubmissionIdUrl": null,
      "tradeInDevices": [
        {
          "headerMsg": "Your estimated trade-in promo value is $XXX.XX",
          "activeDevice": null,
          "tradeInCredit": "215.00",
          "tradeInDeviceFooter": null,
          "offerDetailsMsg": null,
          "tradeInDeviceHeaderMsg": null,
          "tradeInCreditMsg": "Trade-in credit: $215.00",
          "bicApplied": false,
          "color": "Red",
          "dataWipeText": null,
          "deviceBrand": "Apple",
          "deviceId": "ID: 321456212351247",
          "discAmt": null,
          "disconnectedDate": null,
          "displayName": "iPhone 7",
          "dppCredit": "0.0",
          "dppAppliedCommerceItemId": "S0b66b22710469c849f6754f5e64b2ab3{ss1}_device_1",
          "dppAppliedMdn": null,
          "errorMessage": null,
          "modalOsName": null,
          "modelImage": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-red?$device-lg$",
          "modelName": null,
          "mtn": null,
          "nickName": null,
          "originalAppraisalPrice": "215.00",
          "price": null,
          "promoCodeError": null,
          "promoCreditType": null,
          "promoQualifyMessage": null,
          "promoValue": null,
          "shortDisplayName": null,
          "size": "128GB",
          "success": true,
          "regularPromoApplied": false,
          "existingAppraisedReferenceId": "02045702043406",
          "appraiseTradeInDeviceWithOutDeviceId": true,
          "flow": "AAL",
          "submissionId": "351245621245212",
          "commerceItemId": "S0b66b22710469c849f6754f5e64b2ab3{ss1}_device_1",
          "promoInfo": {
            "tradeInAmount": "XX.XX", // negative amount
            "promoMessage": "You’ll be receiving a trade-in promo credit in 1-2 billing cycles.",
            "promoTooltipMessage": "You’re getting $XXX off iPhone with select trade-ins in good working and cosmetic condition. You’ll see a [$XX.XX] monthly device payment on your bill, and a $29.16/mo trade-in credit in 1-2 billing cycles. This ends when the balance is fully paid, or if the line is terminated or transferred.If your credit takes 2 cycles to appear, you’ll see the credit for the first cycle on your second bill in addition to that month’s credit."
          }
        },
        {
          "headerMsg": "Your estimated trade-in promo value is $XXX.XX",
          "activeDevice": null,
          "tradeInCredit": "215.00",
          "tradeInDeviceFooter": null,
          "offerDetailsMsg": null,
          "tradeInDeviceHeaderMsg": null,
          "tradeInCreditMsg": "Trade-incredit: $215.00",
          "bicApplied": false,
          "color": "Red",
          "dataWipeText": null,
          "deviceBrand": "Apple",
          "deviceId": "ID: 321456212351247",
          "discAmt": null,
          "disconnectedDate": null,
          "displayName": "iPhone7",
          "dppCredit": "0.0",
          "dppAppliedCommerceItemId": null,
          "dppAppliedMdn": null,
          "errorMessage": null,
          "modalOsName": null,
          "modelImage": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-red?$device-lg$",
          "modelName": null,
          "mtn": null,
          "nickName": null,
          "originalAppraisalPrice": "215.00",
          "price": null,
          "promoCodeError": null,
          "promoCreditType": null,
          "promoQualifyMessage": null,
          "promoValue": null,
          "shortDisplayName": null,
          "size": "128GB",
          "success": true,
          "regularPromoApplied": false,
          "existingAppraisedReferenceId": "02045702043406",
          "appraiseTradeInDeviceWithOutDeviceId": true,
          "flow": "AAL",
          "submissionId": "351245621245212"
        },
        {
          "activeDevice": null,
          "tradeInCredit": "520.00",
          "tradeInDeviceFooter": null,
          "offerDetailsMsg": null,
          "tradeInDeviceHeaderMsg": null,
          "tradeInCreditMsg": "Trade-incredit: $520.00",
          "bicApplied": true,
          "color": "Gray",
          "dataWipeText": null,
          "deviceBrand": "Apple",
          "deviceId": "ID: 351245621245212",
          "discAmt": null,
          "disconnectedDate": null,
          "displayName": "iPhoneX",
          "dppCredit": "0.0",
          "dppAppliedCommerceItemId": null,
          "dppAppliedMdn": null,
          "errorMessage": null,
          "modalOsName": null,
          "modelImage": "https://ss7.vzw.com/is/image/VerizonWireless/iPhoneX-SpGry?$device-lg$",
          "modelName": null,
          "mtn": null,
          "nickName": null,
          "originalAppraisalPrice": "520.00",
          "price": null,
          "promoCodeError": null,
          "promoCreditType": null,
          "promoQualifyMessage": null,
          "promoValue": null,
          "shortDisplayName": null,
          "size": "64GB",
          "success": true,
          "regularPromoApplied": false,
          "existingAppraisedReferenceId": "02492409048768",
          "appraiseTradeInDeviceWithOutDeviceId": true,
          "flow": "AAL",
          "submissionId": "351245621245212",
          "headerMsg": "Your estimated trade-in promo value is $XXX.XX*",
        },
        {
          "activeDevice": null,
          "tradeInCredit": "520.00",
          "tradeInDeviceFooter": null,
          "offerDetailsMsg": null,
          "tradeInDeviceHeaderMsg": null,
          "tradeInCreditMsg": "Trade-incredit: $520.00",
          "bicApplied": true,
          "color": "Gray",
          "dataWipeText": null,
          "deviceBrand": "Apple",
          "deviceId": "ID: 351245621245212",
          "discAmt": null,
          "disconnectedDate": null,
          "displayName": "iPhoneX",
          "dppCredit": "0.0",
          "dppAppliedCommerceItemId": null,
          "dppAppliedMdn": null,
          "errorMessage": null,
          "modalOsName": null,
          "modelImage": "https://ss7.vzw.com/is/image/VerizonWireless/iPhoneX-SpGry?$device-lg$",
          "modelName": null,
          "mtn": null,
          "nickName": null,
          "originalAppraisalPrice": "520.00",
          "price": null,
          "promoCodeError": null,
          "promoCreditType": null,
          "promoQualifyMessage": null,
          "promoValue": null,
          "shortDisplayName": null,
          "size": "64GB",
          "success": true,
          "regularPromoApplied": false,
          "existingAppraisedReferenceId": "02492409048768",
          "appraiseTradeInDeviceWithOutDeviceId": true,
          "flow": "AAL",
          "submissionId": "351245621245212",
          "headerMsg": "Your estimated trade-in promo value is $XXX.XX*",
        }
      ],
      "orginaltradeInCredit": "735.00"
    },
    "promotionList": [
      {
        "promoMsg": "UATBUYIPHN8SAMGALAXYS8GETIPHN8SAMGALS8BICYES",
        "promoAmount": "699.75",
        "captalizedPromoMsg": "Uatbuyiphn8samgalaxys8getiphn8samgals8bicyes",
        "barcode": null,
        "skuId": "MQ722LL/A",
        "offerLevel": null
      }
    ],
    "cartMessages": {
      "cartReadyforCheckout": false,
      "message": "InsuranceNotSelected",
      "code": "ERROR"
    },
    "mailInRebateTotal": 0,
    "mailInRebateDetails": null,
    "promoCodes": [
      null
    ],
    "promoCodeHeader": "Promocode?Luckyyou.",
    "promoCodeLabel": "Promocode",
    "addAnotherPromoCodeText": "Addanotherpromocode",
    "applyBtn": "Apply",
    "emptyCartMessage": "Therearenoitemsinyourcart",
    "shopBtn": "Shop",
    "tradeInPromoEligible": true,
    "eligibleForSingleDeviceRibbon": false,
    "eligibleForMultiDeviceAllocation": false,
    "retrieveCartSuccessful": false,
    "standaloneAccessories": false,
    "dueTodayText": "Duetoday",
    "dueMonthlyText": "DueMonthly",
    "mainCartHeader": "Timetoreviewyourcart.",
    "mainCartSubTitle": "Enjoyfree2-dayshipping",
    "mainCartNextDayShippingMessage": "Wantittomorrow?Orderby11pmwithnextdayshipping",
    "shopMoreBtnText": "Shopmore",
    "checkoutBtn": "Checkout",
    "editBtn": "Edit",
    "removeLinkText": "Remove",
    "mainCartFooterText": "Wanttostartover?",
    "mainCartFooterLinkText": "Emtpyyourcart",
    "shopMoreLink": "/od/cust/auth/shoplanding/",
    "activationFeeText": "ActivationFee",
    "waivedActivationText": "WaivedActivationFee",
    "upgradeFeeText": "UpgradeFee",
    "waivedUpgradeFeeText": "WaivedUpgradeFee",
    "saveBtnLabel": "Save",
    "zipCodeHeader": "PleaseenteranewZIPcode",
    "tradeInCreditHeader": "Trade-inCreditforthisdevice",
    "tradeInFooterLink": "Tellmemore",
    "tradeInOfferDetailsHeader": "OfferDetails",
    "tradeInOfferDetailsMsg": "longblockoftext",
    "tradeInConfirmationBtn": "Gotit",
    "lonelyCartMessage": "Yourcartislonely.",
    "lonelyCartSubMessage": null,
    "checkoutButtonURL": "/od/cust/auth/checkout/initiateCheckout",
    "tradeInUrl": "/od/trade-in/auth?gotoCart=true",
    "mainInRebateDetails": null,
    "deviceProtectionDetails": {
      "deviceProtectionDetailsHeader": "deviceprotectiondetails",
      "deviceProtectionDetailsSubTitle": "FivethingsyouneedtoknowaboutEquipmentProtection",
      "deviceProtectionDetailsText": "<div><p>CostperMonthandIndividualServiceAvailability.TotalMobileProtection(TMP)SingleDeviceandTotalMobileProtectionMulti-Deviceareacombinationofmultipleproducts,           eachofwhichisavailableseparatelyperdevice: WirelessPhoneProtection(WPP)$5.00/BasicDevices&amp;Tabletsorfor$7.15/Smartphones&amp;iPhoneDevices;VerizonWirelessExtendedWarranty(EW)$3.00;andVerizonTechCoach$7.00.YoumayalsopurchaseTotalEquipmentCoverage(TEC)for$7.00/BasicDevices&amp;Tabletsorfor$9.00/Smartphones&amp;iPhoneDevices.TECisacombinationof2products,           eachofwhichisavailableseparately: WPP$5.00/BasicDevices&amp;Tabletsorfor$7.15/Smartphones&amp;iPhoneDevices;andVerizonWirelessEWfor$3.00.</p><p>ApplicabilityandAmountofDeductible.Forlost,           stolenanddamageddeviceclaims,           deductiblesare$49forbasicphonesand,           dependingondevice,           $49-$199forsmartphonesandtablets.Forafulllistofdeductiblesclickhere<ahref='http://phoneclaim.com/verizon/deductible'target='_blank'>http: //phoneclaim.com/verizon/deductible.</a></p><p>ClaimLimitsforloss,           stolenanddamageddevices.Equipmentclaimmaximumis$400or$1,           500,           dependingondevice,           andlimitedtothreeclaimsper12-monthperiodforTMPSingleDeviceanduptonineclaimsper12-monthperiodforTMPMulti-Device.</p><p>CoveredandReplacementEquipment.Ifyourdeviceislost,           stolenordamaged,           youraccessoriesarecoveredtooï¿1Ž2oneeachofthefollowing: standardbattery,           standardcarcharger,           standardcase,           standardhomechargerandstandardearbud.Itisourgoaltoprovideyouwithareplacementdevicethatisthesamecolorandhasthesamefeatures,           butthiscannotbeguaranteed.Ifthesamemakeandmodelyouclaimisnotavailable,           asimilarmakeandmodelwillbesubstituted.Yourreplacementdevicecouldbeneworrefurbished.Youmayalsoreceivegenericaccessorieswithlost,           stolenordamagedclaims.</p><p>CancellationPolicy.Changeyourmind?Youcancancelyourcoverageatanytimeandreceiveapro-ratedrefundofyourmonthlyfee.</p></div>"
    },
    "preOrderAlertMsg": "Yourordercontainsoneormoreitemsthatarenotinstock.Allitemswillshiptogetherwheneverythingisavailable.",
    "bicText": null,
    "hasSubmittedTradein": false,
    "cpcSucessful": false,
    "cpcSucessfulNotification": false,
    "protectionURL": "/od/cust/auth/protection",
    "itemsFromRetrievedCart": false,
    "totalActivationFee": "60.00",
    "itemOnJaxPlan": false,
    "anyLineFreeSPO": null,
    "paypalEnabled": false,
    "paypalApi": "/od/cust/auth/checkout/paypal/cmpilookup?triggerFrom=PAYMENT",
    "aalUrl": "/od/cust/auth/shop?flow=AAL",
    "eupUrl": "/od/cust/auth/shop?flow=EUP",
    "rawSubTotalDueToday": "0.00",
    "overallDueMonthly": "29.17",
    "additionalCharges": [
      {
        "taxPrice": "0.00",
        "cityStateString": null,
        "stateTaxLabel": "MDStateSalesTax",
        "zipCode": null
      }
    ],
    "accessoryGWURL": "/od/cust/auth/accessories/",
    "accessoryPDPURL": "/od/cust/auth/accessoryDetails/",
    "removeTradeInURL": "/od/trade-in/removeTradeIn",
    "masterpassEnabled": true,
    "targetter": {
      "freeShippingText": "FreeShippingorIn-StorePickup",
      "freeShippingDesc": "Freeshipping\nFree2-dayshippingwhenyouorderonlineM-Fby8PMEST,           Satby2PMEST(excludingholidays),           willdeliverintwobusinessdayswithintheU.S.only(excludingAK&HI).2-dayordersplacedafter2PMESTonSatwilldeliverbyWednesday.OvernightshippingtodestinationswithintheU.S.(excludingAK&HI)isgenerallyavailableforordersplacedM-Funtil11PMEST,           excludingholidays.Ordersthatcontainapre-orderorbackorderwillshipvia2-dayshippingonorpriortothecommitteddate.Subjecttocreditauthorization,           verificationandinventoryavailability.",
      "nextDayText": "Wantittomorrow?Orderby11PMETw/NextDayShipping.Pre-orderdevicesexcl'd",
      "nextDayDesc": "Depending on inventory availability for destinations within the US (excluding AK, HI) for orders placed M-F (excluding holidays). Next Day Shipping is not available for devices in pre-order status. Pre-order devices will ship as inventory becomes available",
      "contentText": "Keep your content.",
      "contentDesc": "Don'tworry,           we've got you covered. We'llmakesureallofyourpictures,           contactsandcontenttransferfromonephonetotheotherwithoutissue.",
      "returnPolicyText": "14dayreturnpolicy",
      "returnPolicyDesc": "YoumayreturnorexchangewirelessdevicesandaccessoriespurchasedfromVerizonWirelesswithin14daysofpurchase.Arestockingfeeof$35appliestoanyreturnorexchangeofawirelessdevice(excludingHawaii)."
    },
    "overallDiscountedAmount": "0.00",
    "ecpdDueTodayDiscountedAmount": "0.00",
    "ecpdDueMonthlySavings": "0.00",
    "devicesURL": "/od/devices/",
    "autoPayApplied": false,
    "globalPromotion": null,
    "cartURL": "/od/cust/auth/cart/getCartDetails?format=json",
    "byodUrl": "/od/cust/auth/shop?flow=NSO",
    "masterpassConfigInfo": {
      "checkoutId": "900f7d9b6a974cee9e0cad74fe8c1c20",
      "allowedCardTypes": [
        "master",
        "amex",
        "diners",
        "discover",
        "jcb",
        "maestro",
        "visa"
      ],
      "shippingLocationProfile": "US",
      "amount": "42.01",
      "cartId": "S0b66b22710469c849f6754f5e64b2ab3{             ss1           }",
      "currency": "USD",
      "suppress3Ds": false,
      "callbackUrl": "http: //wga0022alditdvb.uswin.ad.vzwcorp.com/od/cust/auth/checkout/masterpass/paymentData?fromCart=true"
    },
    "accessoryShopURL": "/accessories",
    "bicOfferMessage": null,
    "cartMFCompatible": true,
    "cartValidationDetailsVo": {
      "cartReadyforCheckout": false,
      "cartIncompleteCode": "ERROR",
      "cartIncompleteMessage": "InsuranceNotSelected",
      "orderId": "S0b66b22710469c849f6754f5e64b2ab3{             ss1           }"
    },
    "tmpMdOpted": false,
    "tmpMd": null,
    "frontEndPersonalization": null,
    "allowAAL": true,
    "allowEUP": true,
    "isHLLPlanInOrder": false,
    "accountLevelDiscountList": null,
    "planNotFoundRedirect": null,
    "protectionNotFoundRedirect": null,
    "splitShipment": false,
    "mmplanEnabled": false,
    "smartFamilyInCart": false,
    "authenticated": true
  },
  "errorMap": null,
  "statusMessage": ""
};

export default cartJSON;
