export const RESET_STATE = 'RESET_STATE';
export const ASYNC_FETCH = 'ASYNC_FETCH';
export const ASYNC_FETCH_SUCCESS = 'ASYNC_FETCH_SUCCESS';
export const ASYNC_FETCH_FAILURE = 'ASYNC_FETCH_FAILURE';
export const ASYNC_FETCH_INVALIDATE = 'ASYNC_FETCH_INVALIDATE';
export const ASYNC_FETCH_WITHMESSAGE = 'ASYNC_FETCH_WITHMESSAGE';
export const CHOOSE_PAYMENT_METHOD = 'CHOOSE_PAYMENT_METHOD';
export const SHIP_TO_TYPE = 'SHIP_TO_TYPE';
export const STORE_LIST = 'STORE_LIST';
export const MARKER_SELECTED = 'MARKER_SELECTED';
export const STORE_SELECTED = 'STORE_SELECTED';
export const MAP_CLICKED = 'MAP_CLICKED';
export const AGREEMENT_CLICKED = 'AGREEMENT_CLICKED';
export const LOAD_BILLING_FORM = 'LOAD_BILLING_FORM';
export const SAME_AS_SHIPPING = 'SAME_AS_SHIPPING';


export const API_SUCCESS_CODE = '00';
export const API_FAILURE_CODE = '01';

export const BILL_TO_ACCOUNT = 'BTA';
export const APPLE_PAY = 'APPLE_PAY';
export const CYBER_SOURCE_DATA = 'CYBER_SOURCE_DATA';

