export const RESET_STATE = 'RESET_STATE';
export const ASYNC_FETCH = 'ASYNC_FETCH';
export const ASYNC_FETCH_SUCCESS = 'ASYNC_FETCH_SUCCESS';
export const ASYNC_FETCH_FAILURE = 'ASYNC_FETCH_FAILURE';
export const ASYNC_FETCH_CLEAR = 'ASYNC_FETCH_CLEAR';
export const SET_CURRENT_PLAN = 'SET_CURRENT_PLAN';

export const API_SUCCESS_CODE = '00';
export const API_FAILURE_CODE = '01';

// compare plans
export const REQUEST_PLANS_COMPARE = 'REQUEST_PLANS_COMPARE';
export const SUCCESS_PLANS_COMPARE = 'SUCCESS_PLANS_COMPARE';
export const INVALIDATE_PLANS_COMPARE = 'INVALIDATE_PLANS_COMPARE';
export const FAILURE_PLANS_COMPARE = 'FAILURE_PLANS_COMPARE';
