export const CHANGE_MDN_SELECTION_VIEW = 'mdnSelection/CHANGE_MDN_SELECTION_VIEW';
export const CHANGE_MDN_SELECTED = 'mdnSelection/CHANGE_MDN_SELECTED';
export const MDN_SELECTION_VIEW = 'MDN_SELECTION_VIEW';

