const cartJSON = {
	"statusCode": "00",
	"output": {
		"instantCreditAppliedSalesTaxInfo": null,
		"instantCreditEligible": false,
		"instantCreditPageURL": null,
		"instantCreditRemovedMsg": null,
		"instantCreditRemovedComboMsg": null,
		"instantCreditTradeinSummary": {
			"optionalDownPayment": null,
			"twoYearDevicesInstantCredit": null,
			"fullRetailInstantCredit": null,
			"accessoriesInsantCredit": null,
			"taxesInstantCredit": null,
			"dueTodayInstantCredit": null,
			"accountCredit": null,
			"instantCreditHeaderTxt": null,
			"totalInstantCredit": null
		},
		"instantCreditAppliedOnOrder": 0.0,
		"orderId": "S5f9261bc0ead138ecdd7874efb6577c0{s3}",
		"redirectionURL": null,
		"isPOBODeviceInCart": false,
		"accGuestCheckoutEnabled": false,
		"dueTodayPOBOHeader": null,
		"items": [{
			"deviceProdId": "dev10320067",
			"deviceManufactureName": "Motorola",
			"deviceProductDisplayName": "moto z<sup>3</sup>",
			"colorName": "Ceramic Black",
			"capacity": "64GB",
			"flow": "AAL",
			"mtn": null,
			"displayMtn": null,
			"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/motorola-moto-z3-exclusive-black?$device-med$&fmt=jpeg&wid=75&hei=150",
			"deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/motorola-moto-z3-exclusive-black?$device$&bgc=ffffff&wid=158&hei=300",
			"activationFee": "30.00",
			"waivedActivationFeePromo": false,
			"upgradeFee": "0.00",
			"waivedUpgradeFeePromo": false,
			"edgeDevice": true,
			"price": "10.00",
			"originalPrice": "20.00",
			"priceText": "Monthly Device payment",
			"priceSubTitle": "You'll see the first installment in your next billing cycle. For 24 months, 0% APR.Retail Price: $480.00",
			"edgeItemDownPaymentAmount": "0.00",
			"installmentBalance": "0.00",
			"deviceEdgeUpAmount": "0.00",
			"deviceEdgeBuyOutAmount": "0.00",
			"protectionOption": {
				"name": "Decline Equipment Protection",
				"price": "0.00",
				"originalPrice": "0.00",
				"featureType": "INS",
				"featureSkuId": "sku401064",
				"hideEditProtection": false,
				"displayMsg": "You have declined equipment protection. Without it, replacing your device may cost as much as the retail price of $480.00. Your new device is only eligible for 30 days.",
				"tapOpted": false
			},
			"commerceItemId": "S5f9261bc0ead138ecdd7874efb6577c0{s3}_device_1",
			"deviceSkuId": "sku3100342",
			"deviceSORId": "MOTXT192917",
			"lacPrice": "0.00",
			"lacText": "Smartphone line access",
			"inventoryStatus": "1000",
			"inventoryAvailableDate": null,
			"hasEcpdDiscount": false,
			"hasEcpdDiscountForDevicePayment": false,
			"devicePromotionList": [],
			"bicOfferApplied": true,
			"bicContractPrice": "20.00",
			"bicDiscountedContractPrice": "10.00",
			"bicSavings": "10.00",
			"myOfferWaiveUpgradeFee": false,
			"shipCommitInd": null,
			"promoLACMessage": null,
			"additionalFeatures": [],
			"simDetails": null,
			"imeiId": null,
			"transferredFromMtn": null,
			"originalActivationFee": "30.00",
			"protectionInEligible": false,
			"nickName": "",
			"e911AddressMissing": false,
			"planChanged": true,
			"priceForFullRetailPriceListID": "480.00",
			"bicMessage": null,
			"bicMessagetooltip": null,
			"editDeviceUrl": "/od/pdp/dev10320067/?commerceItemId=S5f9261bc0ead138ecdd7874efb6577c0%7Bs3%7D_device_1&deviceProdId=dev10320067&catalogRefId=sku3100342&editDevice=true&flow=AAL",
			"e911AddressUpdateUrl": null,
			"fullRetailPrice": "480.00",
			"fromSavedCart": false,
			"numberShareDevice": false,
			"numberSharedMtn": null,
			"itemOnJaxPlan": false,
			"humCarDetails": null,
			"poboAvailableDate": null,
			"planCommerceItemId": "S5f9261bc0ead138ecdd7874efb6577c0{s3}_plan_1",
			"monthlyPriceAfterDownPaymentBeforeDiscount": 0.0,
			"originalFullRetailPrice": 0.0,
			"hasReducedRetailPrice": false,
			"hasReducedDueMonthly": false,
			"originalDueMonthly": 0.0,
			"lineAccessPromotionText": null,
			"downPaymentPromotionText": null,
			"contractTerm": "99",
			"deviceType": "SMARTPHONE",
			"activationFeeText": "One-time activation fee of $30.0 charged to your next monthly bill.",
			"promoOfferText": null,
			"promoApplied": false,
			"portIn": false,
			"deviceNickName": "moto z<sup>3</sup>",
			"totalNumberShareExtension": 0,
			"originalUpgradeFee": "0.00",
			"totalSavings": "240.00",
			"instantCreditAppliedAmount": null,
			"instantCreditAppliedInfo": null,
			"instantCreditAdjustedPrice": null,
			"instantCreditFullRetailPrice": null,
			"sbdOffer": {
				"sbdHeaderMsg": "GET MOTO Z3 FOR 10 00 MONTH DPP ACT",
				"sbdPromoMsg": "GET MOTO Z3 FOR 10 00 MONTH DPP ACTIVATIONS ONLY DIRECT AND AGENTS- BIC YES",
				"sbdDiscountAmount": "240.00",
				"sbdItemMonthlyAmount": "10.00",
				"itemRetailPrice": "480.00",
				"itemMonthlyPrice": "20.00",
				"itemStrikeThroughPrice": "20.00",
				"sbdPromoId": "200590",
				"noOfBicOccurences": 24,
				"sbdHeaderMsgHTML": "<span class='color_blue bold block'>Congratulations! </span> You are getting this device for only $10.00/mo. instead of $20.00/mo for 24 mos.",
				"promoBadgeMessages": [{
					"badgeText": "You’ll be receiving a promo credit in 1-2 billing cycles.",
					"badgeToolTip": "You'll see a $20.00 monthly device payment on your bill, and a $10.00 monthly promo credit in 1-2 billing cycles. This ends when the balance is fully paid, or if the line is terminated or transferred. If your credit takes 2 cycles to appear, you'll see the credit for the first cycle on your second bill in addition to that month's credit.",
					"badgeToolTipUrl": null,
					"badgeImage": "",
					"placement": "ITEM-HEADER",
					"pageId": null
				}],
				"ignorePricing": false,
				"sbdNegativeAmt": "10.00",
				"bicBogoType": "",
				"offerSubmitRequiredInd": "N"
			},
			"hostCommerceItemId": null,
			"trunkMtn": null,
			"discountedEdgeRetailPrice": "240.00",
			"displayImeiId": null,
			"featureDropped": false,
			"changePlanUrl": "/digital/cpc/cpcExploreMMPlan?rci=Y&editMMPlan=true&planSorId=17991&lineItemId=S5f9261bc0ead138ecdd7874efb6577c0{s3}_device_1#/plans/0",
			"allowStackWithTrade": null,
			"modDevice": false,
			"isModConnected": true,
			"dueMonthlyTotalDuration": null,
			"dueMonthlyPrice": null,
			"upgradeFeeWaived": false,
			"activationFeeWaived": false,
			"policyEnabled": true,
			"editNPANXXButton": true,
			"editNPANXXRedirect": "/od/cust/auth/checkout/npaNxxNumber"
		}, {
			"deviceProdId": "dev10720043",
			"deviceManufactureName": "Motorola",
			"deviceProductDisplayName": "5G MOTO MOD",
			"colorName": "Black",
			"capacity": null,
			"flow": "AAL",
			"mtn": null,
			"displayMtn": null,
			"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/palm-dubs-gold?$device-med$&fmt=jpeg&wid=75&hei=150",
			"deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/palm-dubs-gold?$device$&bgc=ffffff&wid=158&hei=300",
			"activationFee": "0.00",
			"waivedActivationFeePromo": false,
			"upgradeFee": "0.00",
			"waivedUpgradeFeePromo": false,
			"edgeDevice": true,
			"price": "50.00",
			"originalPrice": "50.00",
			"priceText": null,
			"priceSubTitle": null,
			"edgeItemDownPaymentAmount": "0.00",
			"installmentBalance": "0.00",
			"deviceEdgeUpAmount": "0.00",
			"deviceEdgeBuyOutAmount": "0.00",
			"protectionOption": null,
			"commerceItemId": "S5f9261bc0ead138ecdd7874efb6577c0{s3}_device_2",
			"deviceSkuId": "sku3370005",
			"deviceSORId": "MOT5GMOD",
			"lacPrice": "0.00",
			"lacText": "Connected devices line access",
			"inventoryStatus": "1000",
			"inventoryAvailableDate": null,
			"hasEcpdDiscount": false,
			"hasEcpdDiscountForDevicePayment": false,
			"devicePromotionList": null,
			"bicOfferApplied": false,
			"bicContractPrice": "0.00",
			"bicDiscountedContractPrice": "0.00",
			"bicSavings": "0.00",
			"myOfferWaiveUpgradeFee": false,
			"shipCommitInd": null,
			"promoLACMessage": null,
			"additionalFeatures": [],
			"simDetails": null,
			"imeiId": null,
			"transferredFromMtn": null,
			"originalActivationFee": "0.00",
			"protectionInEligible": false,
			"nickName": null,
			"e911AddressMissing": false,
			"planChanged": false,
			"priceForFullRetailPriceListID": "50.00",
			"bicMessage": null,
			"bicMessagetooltip": null,
			"editDeviceUrl": "/od/pdp/dev10720043/?commerceItemId=S5f9261bc0ead138ecdd7874efb6577c0%7Bs3%7D_device_2&deviceProdId=dev10720043&catalogRefId=sku3370005&editDevice=true&flow=AAL",
			"e911AddressUpdateUrl": null,
			"fullRetailPrice": "50.00",
			"fromSavedCart": false,
			"numberShareDevice": false,
			"numberSharedMtn": null,
			"itemOnJaxPlan": false,
			"humCarDetails": null,
			"poboAvailableDate": null,
			"planCommerceItemId": "S5f9261bc0ead138ecdd7874efb6577c0{s3}_plan_2",
			"monthlyPriceAfterDownPaymentBeforeDiscount": 0.0,
			"originalFullRetailPrice": 0.0,
			"hasReducedRetailPrice": false,
			"hasReducedDueMonthly": false,
			"originalDueMonthly": 0.0,
			"lineAccessPromotionText": null,
			"downPaymentPromotionText": null,
			"contractTerm": "0",
			"deviceType": "Connected Devices",
			"activationFeeText": null,
			"promoOfferText": null,
			"promoApplied": false,
			"portIn": false,
			"deviceNickName": "5G MOTO MOD",
			"totalNumberShareExtension": 0,
			"originalUpgradeFee": "0.00",
			"totalSavings": "0.00",
			"instantCreditAppliedAmount": null,
			"instantCreditAppliedInfo": null,
			"instantCreditAdjustedPrice": null,
			"instantCreditFullRetailPrice": null,
			"sbdOffer": null,
			"hostCommerceItemId": null,
			"trunkMtn": null,
			"discountedEdgeRetailPrice": null,
			"displayImeiId": null,
			"featureDropped": false,
			"changePlanUrl": "",
			"allowStackWithTrade": null,
			"modDevice": true,
			"isModConnected": false,
			"dueMonthlyTotalDuration": "For the first 3 months.$10.00/month after that.",
			"dueMonthlyPrice": "0.0",
			"upgradeFeeWaived": false,
			"activationFeeWaived": false,
			"policyEnabled": true,
			"editNPANXXButton": false,
			"editNPANXXRedirect": "/od/cust/auth/checkout/npaNxxNumber"
		}],
		"existingDevices": null,
		"plans": {
			"planOnlyDueMonthly": "40.00",
			"dueMonthly": "40.00",
			"dueToday": "0.00",
			"items": [{
				"planType": "Go Unlimited",
				"planSorId": "17991",
				"planProdId": "plan5600003",
				"planSkuId": "sku3070053",
				"planLetter": null,
				"planDescription": "",
				"planDisplayName": "Go Unlimited",
				"planChangeURL": "/digital/cpc/cpcExploreMMPlan?rci=Y?editMMPlan=true&planSorId=17991&flow=AAL&planCommId=S5f9261bc0ead138ecdd7874efb6577c0{s3}_plan_1",
				"planImageURL": "//ss7.vzw.com/is/image/VerizonWireless/U_083s_022317",
				"accountAccess": {
					"name": "Go Unlimited",
					"price": "40.00",
					"discountPrice": "0.00",
					"promoMessage": null,
					"hasEcpdDiscount": false,
					"planAmount": "40.00",
					"originalPlanAmount": "40.00"
				},
				"dueMonthly": "40.00",
				"dueMonthlyOriginal": "40.00",
				"planCommerceItemId": "S5f9261bc0ead138ecdd7874efb6577c0{s3}_plan_1",
				"autoPayText": "You are getting $5.00 for paper-free billing and AutoPay.",
				"termsAndConditionKey": "TNC_GoUnlimited",
				"unitOfMeasure": "GB",
				"subsidyIndicator": false,
				"subsidyCost": null,
				"appleMusicIndicator": false,
				"appleMusicMessage": "<img src='https://ss7.vzw.com/is/image/VerizonWireless/apple-music-logo-black?$pngalpha$&scl=1' width='100px' alt='Apple music logo' /><span class='fontSize_4 pad10 onlyLeftPad'>Apple Music free for 6 Months.</span>",
				"planSize": "9999"
			}, {
				"planType": "5G MOD Plan",
				"planSorId": "21629",
				"planProdId": "plan40003",
				"planSkuId": "sku30014",
				"planLetter": null,
				"planDescription": "",
				"planDisplayName": "5G MOD Plan",
				"planChangeURL": null,
				"planImageURL": "",
				"accountAccess": {
					"name": "5G MOD Plan",
					"price": "0.00",
					"discountPrice": "0.00",
					"promoMessage": null,
					"hasEcpdDiscount": false,
					"planAmount": "0.00",
					"originalPlanAmount": "0.00"
				},
				"dueMonthly": "0.00",
				"dueMonthlyOriginal": "0.00",
				"planCommerceItemId": "S5f9261bc0ead138ecdd7874efb6577c0{s3}_plan_2",
				"autoPayText": null,
				"termsAndConditionKey": "TNC_5GMODPlan",
				"unitOfMeasure": null,
				"subsidyIndicator": false,
				"subsidyCost": null,
				"appleMusicIndicator": false,
				"appleMusicMessage": null,
				"planSize": null
			}],
			"newDevices": null,
			"upgradeDevices": null,
			"existingDevices": null,
			"dueMonthlyPlanWithLAC": null,
			"discountedDueMonthlyPlanWithLAC": null,
			"existingDevicesLAC": null,
			"discountedExistingDevicesLAC": null
		},
		"accessories": [],
		"selectedShippingType": {
			"type": "SHIPPING",
			"shippingTypeName": "FREE 2 Day by 8pm",
			"price": 0.0,
			"discountPrice": 0.0,
			"estimatedDeliveryDate": null,
			"selectedFormattedWindow": null
		},
		"cartEdited": false,
		"iconicFlow": false,
		"removePromoCodeURL": "/od/cust/auth/cart/removePromoCode",
		"applyPromoCodeURL": "/od/cust/auth/cart/applyPromoCode",
		"clearCartURL": "/od/cust/auth/cart/clearCart",
		"addOrUpdateDeviceURL": "/od/cust/auth/cart/addOrUpdateDevice",
		"addOrRemoveAccessoryURL": "/od/cust/auth/cart/addOrRemoveAccessory",
		"changeZipCodeURL": "/od/cust/auth/cart/changezipcode/",
		"addOrUpdateFeatureURL": "/od/cust/cart/addOrUpdateFeature",
		"initiateCheckoutURL": "/od/cust/checkout/initiateCheckout",
		"guestCheckoutSignInURL": null,
		"accountMember": false,
		"removeDeviceURL": "/digital/cpc/removeDevice",
		"enableRemoveDeviceAndMMPlan": true,
		"enableCartAccAjaxCall": true,
		"accessoriesBundle": null,
		"taxDetails": {
			"taxPrice": "31.80",
			"cityStateString": "Fort Lauderdale, FL",
			"stateTaxLabel": null,
			"zipCode": null,
			"totalSalesTax": null,
			"instantCreditAppliedOnSaleTax": null
		},
		"totalDueToday": "81.80",
		"totalDueMonthly": "10.00",
		"employeeDiscount": 0,
		"pastDueBalance": "0.00",
		"emptyCartFlag": false,
		"edgeContractDeviceInCart": true,
		"totalEdgeUpAmount": "0.00",
		"totalEdgeUpBuyOutAmount": "0.00",
		"totalEdgeOrderDownPayment": "0.00",
		"tradeInCredit": null,
		"tradeInPromoDetails": null,
		"promotionList": [],
		"cartMessages": {
			"cartReadyforCheckout": true,
			"message": "",
			"code": null
		},
		"cartItemCount": 2,
		"mailInRebateTotal": 0,
		"mailInRebateDetails": null,
		"promoCodes": [],
		"promoCodeHeader": "Promo code? Lucky you.",
		"promoCodeLabel": "Promo code",
		"addAnotherPromoCodeText": "Add another promo code",
		"applyBtn": "Apply",
		"emptyCartMessage": "There are no items in your cart",
		"shopBtn": "Shop",
		"tradeInPromoEligible": true,
		"eligibleForSingleDeviceRibbon": false,
		"eligibleForMultiDeviceAllocation": false,
		"retrieveCartSuccessful": false,
		"standaloneAccessories": false,
		"dueTodayText": "Due today",
		"dueMonthlyText": "Due Monthly",
		"mainCartHeader": "Time to review your cart.",
		"mainCartSubTitle": "Enjoy free 2-day shipping.",
		"mainCartNextDayShippingMessage": null,
		"shopMoreBtnText": "Shop more",
		"checkoutBtn": "Check out",
		"editBtn": "Edit",
		"removeLinkText": "Remove",
		"mainCartFooterText": "Want to start over?",
		"mainCartFooterLinkText": "Emtpy your cart",
		"shopMoreLink": "/od/cust/auth/shoplanding/",
		"activationFeeText": "Activation Fee",
		"waivedActivationText": "Waived Activation Fee.",
		"upgradeFeeText": "Upgrade Fee",
		"waivedUpgradeFeeText": "Waived Upgrade Fee",
		"saveBtnLabel": "Save",
		"zipCodeHeader": "Please enter a new ZIP code",
		"tradeInCreditHeader": "Trade-in Credit for this device",
		"tradeInFooterLink": "Tell me more",
		"tradeInOfferDetailsHeader": "Offer Details",
		"tradeInOfferDetailsMsg": "long block of text",
		"tradeInConfirmationBtn": "Got it",
		"lonelyCartMessage": "Your cart is lonely.",
		"lonelyCartSubMessage": null,
		"checkoutButtonURL": "/od/cust/auth/checkout/initiateCheckout",
		"tradeInUrl": "/od/trade-in/auth?gotoCart=true",
		"mainInRebateDetails": null,
		"deviceProtectionDetails": {
			"deviceProtectionDetailsHeader": "device protection details",
			"deviceProtectionDetailsSubTitle": "Five things you need to know about Equipment Protection",
			"deviceProtectionDetailsText": "<div> <p>Cost per Month and Individual Service Availability. Total Mobile Protection (TMP) Single Device and Total Mobile Protection Multi-Device are a combination of multiple products, each of which is available separately per device: Wireless Phone Protection (WPP) $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; Verizon Wireless Extended Warranty (EW) $3.00; and Verizon Tech Coach $7.00. You may also purchase Total Equipment Coverage (TEC) for $7.00/Basic Devices &amp; Tablets or for $9.00/Smartphones &amp; iPhone Devices. TEC is a combination of 2 products, each of which is available separately: WPP $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; and Verizon Wireless EW for $3.00.</p> <p> Applicability and Amount of Deductible.  For lost, stolen and damaged device claims, deductibles are $49 for basic phones and, depending on device, $49-$199 for smartphones and tablets. For a full list of deductibles click here <a href='http://phoneclaim.com/verizon/deductible' target='_blank'>http://phoneclaim.com/verizon/deductible.</a> </p> <p>Claim Limits for loss, stolen and damaged devices. Equipment claim maximum is $400 or $1,500, depending on device, and limited to three claims per 12-month period for TMP Single Device and up to nine claims per 12-month period for TMP Multi-Device.</p> <p>Covered and Replacement Equipment. If your device is lost, stolen or damaged, your accessories are covered too ï¿1Ž2 one each of the following: standard battery, standard car charger, standard case, standard home charger and standard earbud. It is our goal to provide you with a replacement device that is the same color and has the same features, but this cannot be guaranteed. If the same make and model you claim is not available, a similar make and model will be substituted. Your replacement device could be new or refurbished. You may also receive generic accessories with lost, stolen or damaged claims.</p> <p>Cancellation Policy. Change your mind? You can cancel your coverage at any time and receive a pro-rated refund of your monthly fee.</p> </div>"
		},
		"preOrderAlertMsg": "Your order contains one or more items that are not in stock. All items will ship together when everything is available.",
		"bicText": null,
		"hasSubmittedTradein": false,
		"cpcSucessful": true,
		"cpcSucessfulNotification": true,
		"protectionURL": "/od/cust/auth/protection",
		"itemsFromRetrievedCart": false,
		"totalActivationFee": "30.00",
		"itemOnJaxPlan": false,
		"anyLineFreeSPO": null,
		"paypalEnabled": true,
		"paypalApi": "/od/cust/auth/checkout/paypal/cmpilookup?triggerFrom=PAYMENT",
		"aalUrl": "/od/cust/auth/shop?flow=AAL",
		"eupUrl": "/od/cust/auth/shop?flow=EUP",
		"rawSubTotalDueToday": "50.00",
		"overallDueMonthly": "50.00",
		"additionalCharges": [{
			"taxPrice": "31.80",
			"cityStateString": null,
			"stateTaxLabel": "FL State Sales Tax",
			"zipCode": null,
			"totalSalesTax": null,
			"instantCreditAppliedOnSaleTax": null
		}],
		"accessoryGWURL": "/od/cust/auth/accessories/",
		"accessoryPDPURL": "/od/cust/auth/accessoryDetails/",
		"removeTradeInURL": "/od/trade-in/removeTradeIn",
		"masterpassEnabled": true,
		"enablePromoCodeForAgent": false,
		"enableTradeInForAgent": false,
		"targetter": {
			"freeShippingText": "Free Shipping or In-Store Pickup",
			"freeShippingDesc": "Free shipping \n Free 2-day shipping when you order online M-F by 8PM EST, Sat by 2PM EST (excluding holidays), will deliver in two business days within the U.S. only (excluding AK & HI). 2-day orders placed after 2PM EST on Sat will deliver by Wednesday. Overnight shipping to destinations within the U.S. (excluding AK & HI) is generally available for orders placed M-F until 11PM EST, excluding holidays. Orders that contain a pre-order or backorder will ship via 2-day shipping on or prior to the committed date. Subject to credit authorization, verification and inventory availability.",
			"nextDayText": "Want it tomorrow? Order by 11PM ET w/Next Day Shipping. Pre-order devices excl'd",
			"nextDayDesc": "Depending on inventory availability for destinations within the US (excluding AK, HI) for orders placed M-F (excluding holidays). Next Day Shipping is not available for devices in pre-order status. Pre-order devices will ship as inventory becomes available",
			"contentText": "Keep your content.",
			"contentDesc": "Don't worry, we've got you covered. We'll make sure all of your pictures, contacts and content transfer from one phone to the other without issue.",
			"returnPolicyText": "14 day return policy",
			"returnPolicyDesc": "You may return or exchange wireless devices and accessories purchased from Verizon Wireless within 14 days of purchase. A restocking fee of $50 applies to any return or exchange of a wireless device (excluding Hawaii)."
		},
		"overallDiscountedAmount": "0.00",
		"ecpdDueTodayDiscountedAmount": "0.00",
		"ecpdDueMonthlySavings": "0.00",
		"devicesURL": "/devices",
		"autoPayApplied": true,
		"instantTradeInDevicesCount": 0,
		"showHeadsUpMsg": false,
		"showMessageForNonStackablePromo": false,
		"nonStackablePromoMessage": null,
		"globalPromotion": [],
		"cartURL": "/od/cust/auth/cart/getCartDetails?format=json",
		"byodUrl": "/od/cust/auth/shop?flow=NSO",
		"masterpassConfigInfo": {
			"checkoutId": "2753b27922fc43329d7213464683752f",
			"allowedCardTypes": ["master", "amex", "diners", "discover", "jcb", "maestro", "visa"],
			"shippingLocationProfile": "US",
			"amount": "81.8",
			"cartId": "S5f9261bc0ead138ecdd7874efb6577c0{s3}",
			"currency": "USD",
			"suppress3Ds": false,
			"callbackUrl": "https://vzwqa3.verizonwireless.com/od/cust/auth/checkout/masterpass/paymentData?fromCart=true"
		},
		"accessoryShopURL": "/accessories",
		"bicOfferMessage": "You'll see a $10.00/mo credit within 1-2 billing cycles.",
		"cartMFCompatible": true,
		"cartValidationDetailsVo": {
			"cartReadyforCheckout": true,
			"cartIncompleteCode": null,
			"cartIncompleteMessage": null,
			"orderId": "S5f9261bc0ead138ecdd7874efb6577c0{s3}"
		},
		"tmpMdOpted": false,
		"tmpMd": null,
		"frontEndPersonalization": null,
		"allowAAL": true,
		"allowEUP": true,
		"isHLLPlanInOrder": true,
		"accountLevelDiscountList": null,
		"planNotFoundRedirect": null,
		"protectionNotFoundRedirect": null,
		"enableSaveCartLink": false,
		"saveCartURL": null,
		"isSingleModConnectedDevice": true,
		"mmplanEnabled": true,
		"ispuselectedAtPdp": false,
		"smartFamilyInCart": false,
		"authenticated": true,
		"splitShipment": false
	},
	"errorMap": null,
	"statusMessage": ""
};

export default cartJSON;