

const mdnJSON = {
	"statusCode": "00",
	"errorMap": null,
	"output": {
		"mtnDetailsList": [{
				"upgradeEligbile": true,
				"displayMtn": "646.530.2890",
				"mtn": "6465302890",
				"encryptedMTN": "9mmcU5p7RSjZHwSjhbr6kw==",
				"upgradeMessage": null,
				"nickname": "TOM PHILLIPS",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iPhone8Plus-Gld?$device-thumb$",
				"inEligibleCode": null,
				"inEligibleDetails": null,
				"loanInfo": {
					"title": "Want to upgrade early?",
					"subtitle": "You're $362.63 into paying off your current device",
					"paidToDate": "$362.63 Paid to date",
					"totalPrice": "$869.99 total price",
					"returnOptionTitle": null,
					"returnOptionDescription": null,
					"returnOptionLegal": null,
					"keepOptionTitle": "Pay $507.36 and Keep your device",
					"keepOptionDescription": "Pay off your remaining balance and keep your old device",
					"keepOptionLegal": "Trade-in value can be used towards a new device or promotion.",
					"legalDisclaimer": "Subject to credit authorization, account standing and other qualifying conditions. Taxes and fees not included.",
					"bogoInd": null,
					"bogoPresent": false,
					"bogoUpgradeMessage": "",
					"displayReturnOption": false,
					"displayKeepOption": true,
					"deviceMismatchText": "The device associated with 6465302890 doesn't match the device ID on your original monthly device payment agreement. In order to complete an early device upgrade, please activate your original device. If you choose to upgrade this line without activating the original device, you will have to pay off the existing balance of $507.36. If you have any questions, you can call 1.800.922.0204 for more information.",
					"returnOptionAmt": null,
					"keepOptionAmt": "$507.36",
					"edgeUpRequiredPercentage": "50",
					"paidAmountPercentage": "42.0",
					"upgradeSummary": null,
					"deviceAgreementText": "Check out your full Device Payment Agreement online at MyVerizon.com.",
					"deviceAgreementLink": null
				},
				"annualUpgradeMessage": null,
				"deviceType": "Smartphone",
				"familyType": "Phone",
				"familyTypeRestricted": false,
				"contractTermMisMatch": false,
				"brand": null,
				"deviceId": "353011091665380",
				"twoYearContract": null,
				"annualUpgrade": false,
				"displayDeviceName": "Apple&reg; iPhone&reg; 8 Plus 64GB in Gold",
				"deviceName": "IPHONE 8 PLUS GOLD 64GB VZ",
				"eligibleUpgradeTypeList": ["Retail", "Edge", "2 Year"],
				"mtnAddedToTheCart": false,
				"lineSharingIndicator": null,
				"buyoutRestrictedForEdge": false,
				"showTransferUpgrade": false,
				"transferUpgradeInProgress": false,
				"transferredFromMtn": null,
				"transferredToMtn": null,
				"tradeinPromoInfo": null,
				"upgradeEligibilityDate": "06/24/2019",
				"clickTransferUpgrade": false,
				"alwaysEligibleForUpgrade": false,
				"sorDeviceType": "4GE",
				"daccCode": "01057",
				"deviceProdId": "dev8720045",
				"estimatedTradeInValue": "0.00",
				"fiveGOrFourGDevice": false,
				"annualUpgradeWarning": false
			}, {
				"upgradeEligbile": true,
				"displayMtn": "646.630.1592",
				"mtn": "6466301592",
				"encryptedMTN": "WT0es2XaQUIIjabtWMmRdA==",
				"upgradeMessage": null,
				"nickname": "TYLER PHILLIPS",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone6s-rsgld-front?$device-thumb$",
				"inEligibleCode": null,
				"inEligibleDetails": null,
				"loanInfo": {
					"title": "Here's how you can upgrade today.",
					"subtitle": "You have a balance of $206.19",
					"paidToDate": "$343.80 Paid to date",
					"totalPrice": "$549.99 total price",
					"returnOptionTitle": null,
					"returnOptionDescription": null,
					"returnOptionLegal": null,
					"keepOptionTitle": null,
					"keepOptionDescription": "To upgrade this device, it must be paid off in full. If you would like to upgrade today, just pay off the remaining balance of $206.19.",
					"keepOptionLegal": null,
					"legalDisclaimer": null,
					"bogoInd": null,
					"bogoPresent": false,
					"bogoUpgradeMessage": "",
					"displayReturnOption": false,
					"displayKeepOption": false,
					"deviceMismatchText": null,
					"returnOptionAmt": null,
					"keepOptionAmt": "$206.19",
					"edgeUpRequiredPercentage": "100",
					"paidAmountPercentage": "63.0",
					"upgradeSummary": null,
					"deviceAgreementText": "Check out your full Device Payment Agreement online at MyVerizon.com.",
					"deviceAgreementLink": null
				},
				"annualUpgradeMessage": null,
				"deviceType": "Smartphone",
				"familyType": "Phone",
				"familyTypeRestricted": false,
				"contractTermMisMatch": false,
				"brand": null,
				"deviceId": "353797081176240",
				"twoYearContract": null,
				"annualUpgrade": false,
				"displayDeviceName": "Apple&reg; iPhone&reg; 6s 32GB in Rose Gold",
				"deviceName": "iPhone 6S 32GB Rose Gold",
				"eligibleUpgradeTypeList": ["Retail", "Edge", "2 Year"],
				"mtnAddedToTheCart": false,
				"lineSharingIndicator": null,
				"buyoutRestrictedForEdge": false,
				"showTransferUpgrade": false,
				"transferUpgradeInProgress": false,
				"transferredFromMtn": null,
				"transferredToMtn": null,
				"tradeinPromoInfo": null,
				"upgradeEligibilityDate": "01/05/2019",
				"clickTransferUpgrade": false,
				"alwaysEligibleForUpgrade": false,
				"sorDeviceType": "4GE",
				"daccCode": "00867",
				"deviceProdId": "dev5160002",
				"estimatedTradeInValue": "0.00",
				"fiveGOrFourGDevice": false,
				"annualUpgradeWarning": false
			}, {
				"upgradeEligbile": true,
				"displayMtn": "646.877.2725",
				"mtn": "6468772725",
				"encryptedMTN": "GwXY0QOTAp9ehygFv4APlg==",
				"upgradeMessage": null,
				"nickname": "DAVE PHILLIPS",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-red?$device-thumb$",
				"inEligibleCode": null,
				"inEligibleDetails": null,
				"loanInfo": {
					"title": "Want to upgrade early?",
					"subtitle": "You're $66.73 into paying off your current device",
					"paidToDate": "$66.73 Paid to date",
					"totalPrice": "$799.99 total price",
					"returnOptionTitle": null,
					"returnOptionDescription": null,
					"returnOptionLegal": null,
					"keepOptionTitle": "Pay $733.26 and Keep your device",
					"keepOptionDescription": "Pay off your remaining balance and keep your old device",
					"keepOptionLegal": "Trade-in value can be used towards a new device or promotion.",
					"legalDisclaimer": "Subject to credit authorization, account standing and other qualifying conditions. Taxes and fees not included.",
					"bogoInd": "BX",
					"bogoPresent": false,
					"bogoUpgradeMessage": "",
					"displayReturnOption": false,
					"displayKeepOption": true,
					"deviceMismatchText": "The device associated with 6468772725 doesn't match the device ID on your original monthly device payment agreement. In order to complete an early device upgrade, please activate your original device. If you choose to upgrade this line without activating the original device, you will have to pay off the existing balance of $733.26. If you have any questions, you can call 1.800.922.0204 for more information.",
					"returnOptionAmt": null,
					"keepOptionAmt": "$733.26",
					"edgeUpRequiredPercentage": "50",
					"paidAmountPercentage": "8.0",
					"upgradeSummary": null,
					"deviceAgreementText": "Check out your full Device Payment Agreement online at MyVerizon.com.",
					"deviceAgreementLink": null
				},
				"annualUpgradeMessage": null,
				"deviceType": "Smartphone",
				"familyType": "Phone",
				"familyTypeRestricted": false,
				"contractTermMisMatch": false,
				"brand": null,
				"deviceId": "355838088201961",
				"twoYearContract": null,
				"annualUpgrade": false,
				"displayDeviceName": "Apple&reg; iPhone&reg; 7 Plus (PRODUCT) RED Special Edition 128GB",
				"deviceName": "iPhone 7 Plus Red 128GB",
				"eligibleUpgradeTypeList": ["Retail", "Edge", "2 Year"],
				"mtnAddedToTheCart": false,
				"lineSharingIndicator": null,
				"buyoutRestrictedForEdge": false,
				"showTransferUpgrade": false,
				"transferUpgradeInProgress": false,
				"transferredFromMtn": null,
				"transferredToMtn": null,
				"tradeinPromoInfo": null,
				"upgradeEligibilityDate": "02/09/2020",
				"clickTransferUpgrade": false,
				"alwaysEligibleForUpgrade": false,
				"sorDeviceType": "4GE",
				"daccCode": "00970",
				"deviceProdId": "dev6640013",
				"estimatedTradeInValue": "0.00",
				"fiveGOrFourGDevice": false,
				"annualUpgradeWarning": false
			}, {
				"upgradeEligbile": true,
				"displayMtn": "917.750.5746",
				"mtn": "9177505746",
				"encryptedMTN": "g6JSe0ZY0xXrs6TCbE8vvg==",
				"upgradeMessage": null,
				"nickname": "TYLER PHILLIPS",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iPhone8Plus-SpGry?$device-thumb$",
				"inEligibleCode": null,
				"inEligibleDetails": null,
				"loanInfo": {
					"title": "Want to upgrade early?",
					"subtitle": "You're $66.73 into paying off your current device",
					"paidToDate": "$66.73 Paid to date",
					"totalPrice": "$799.99 total price",
					"returnOptionTitle": "Return your device and pay $333.26",
					"returnOptionDescription": "Send in your device after you upgrade if it's in working condition and you're all set. ",
					"returnOptionLegal": "The device you return will be applied to your remaining balance and cant be used as a trade-in towards a new device or promotion.",
					"keepOptionTitle": "Pay $733.26 and Keep your device",
					"keepOptionDescription": "Pay off your remaining balance and keep your old device",
					"keepOptionLegal": "Trade-in value can be used towards a new device or promotion.",
					"legalDisclaimer": "Subject to credit authorization, account standing and other qualifying conditions. Taxes and fees not included.",
					"bogoInd": "GX",
					"bogoPresent": false,
					"bogoUpgradeMessage": "",
					"displayReturnOption": true,
					"displayKeepOption": true,
					"deviceMismatchText": null,
					"returnOptionAmt": "$333.26",
					"keepOptionAmt": "$733.26",
					"edgeUpRequiredPercentage": "50",
					"paidAmountPercentage": "8.0",
					"upgradeSummary": null,
					"deviceAgreementText": "Upgrade Program Terms and Conditions.",
					"deviceAgreementLink": "https://www.verizonwireless.com/support/upgrade-program-legal/"
				},
				"annualUpgradeMessage": {
					"subTitle": "You may still upgrade to this device, but you will no longer have the benefits of the annual upgrade program.",
					"acceptButtonText": "Accept",
					"title": "Your new device is not eligible for annual upgrade.",
					"cancelButtonText": "Cancel"
				},
				"deviceType": "Smartphone",
				"familyType": "Phone",
				"familyTypeRestricted": false,
				"contractTermMisMatch": false,
				"brand": null,
				"deviceId": "353011090197427",
				"twoYearContract": null,
				"annualUpgrade": true,
				"displayDeviceName": "Apple&reg; iPhone&reg; 8 Plus 64GB in Space Gray",
				"deviceName": "IPHONE 8 PLUS SP GRAY 64GB VZ",
				"eligibleUpgradeTypeList": ["Retail", "Edge", "2 Year"],
				"mtnAddedToTheCart": false,
				"lineSharingIndicator": null,
				"buyoutRestrictedForEdge": false,
				"showTransferUpgrade": false,
				"transferUpgradeInProgress": false,
				"transferredFromMtn": null,
				"transferredToMtn": null,
				"tradeinPromoInfo": null,
				"upgradeEligibilityDate": "02/09/2020",
				"clickTransferUpgrade": false,
				"alwaysEligibleForUpgrade": false,
				"sorDeviceType": "4GE",
				"daccCode": "01057",
				"deviceProdId": "dev8720045",
				"estimatedTradeInValue": "0.00",
				"fiveGOrFourGDevice": false,
				"annualUpgradeWarning": false
			}, {
				"upgradeEligbile": true,
				"displayMtn": "832.942.9886",
				"mtn": "8329429886",
				"encryptedMTN": "iSsdpUohe7BY+Ae4zb20Tw==",
				"upgradeMessage": null,
				"nickname": "TYLER PHILLIPS NEW",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/generic_phone?$device-thumb$",
				"inEligibleCode": null,
				"inEligibleDetails": null,
				"loanInfo": null,
				"annualUpgradeMessage": null,
				"deviceType": "Internet",
				"familyType": "Tablet Internet Home",
				"familyTypeRestricted": true,
				"contractTermMisMatch": false,
				"brand": null,
				"deviceId": "358041080014808",
				"twoYearContract": {
					"title": "Want to upgrade early?",
					"subTitle": "You can upgrade today by buying your device or wait until your contract ends in 2915165 days.",
					"endDate": "12/31/9999",
					"daysPercentage": "-399237.6712328767",
					"description": "Your device was purchased under a 2-year contract agreement. You can upgrade to a new phone today at the retail price or you can wait until your contract ends.",
					"downpaymentPercentageFor2D": null,
					"contractTermText": null,
					"mtnSummarPageSubText": null,
					"daysRemainingText": null,
					"mtnSummaryPageSubTitle": null,
					"mtnSummaryPageTitle": null
				},
				"annualUpgrade": false,
				"displayDeviceName": "5G Home Outdoor",
				"deviceName": "Samsung 5G CPE Outdoor",
				"eligibleUpgradeTypeList": ["Retail"],
				"mtnAddedToTheCart": false,
				"lineSharingIndicator": null,
				"buyoutRestrictedForEdge": false,
				"showTransferUpgrade": false,
				"transferUpgradeInProgress": false,
				"transferredFromMtn": null,
				"transferredToMtn": null,
				"tradeinPromoInfo": null,
				"upgradeEligibilityDate": "12/31/9999",
				"clickTransferUpgrade": false,
				"alwaysEligibleForUpgrade": false,
				"sorDeviceType": "5GL",
				"daccCode": "01109",
				"deviceProdId": "dev10160018",
				"estimatedTradeInValue": "0.00",
				"fiveGOrFourGDevice": true,
				"annualUpgradeWarning": false
			}
		],
		"accountLevelInEligibleCode": null,
		"accountLevelInEligibleMessage": null,
		"sharedCartDetailsInfo": null,
		"selectedMTN": null,
		"aalRedirect": null,
		"accountLevelInEligibleDetails": null,
		"cartRedirect": "/od/cust/auth/cart/getCartDetails",
		"shopLandingRedirect": "/od/cust/auth/shoplanding/",
		"mtnMainTitle": "Would you like to upgrade or add a new device?",
		"catergoryCode": null,
		"unlimitedPlan": "Y",
		"pastDueDetails": null,
		"submitAddALineUrl": "/od/cust/auth/submitaddaline",
		"transferGiverMTNs": null,
		"transferTakerMTNs": null,
		"transferUpgradeUrl": "/od/cust/auth/account/transferUpgrade",
		"customerType": "B2C",
		"edgeEligible": true,
		"ajaxCallUrl": "/od/cust/auth/submitSummary",
		"ajaxCallSelectedMTN": "/od/cust/auth/mtnDetail/json?flow=EUP&t=",
		"redirectURL": null,
		"myOfferRedirectURL": null,
		"sharedPlan": false,
		"submitByodRedirectUrl": "/od/cust/auth/byod/bring-your-own-device",
		"aalboxEnable": true,
		"byodAllowed": true,
		"aalAllowed": true,
		"sharedCartRetrieved": null
	},
	"cpcRequired": false
};

export default mdnJSON;
