
 const cartJSON =
 {
  "statusCode": "00",
  "output": {
    "orderId": "SDC93c15697bcb30de3cb53e503a4ac50f0{ss100}",
    "redirectionURL": null,
    "isPOBODeviceInCart": false,
    "dueTodayPOBOHeader": null,
    "items": [
      {
        "deviceProdId": "dev6640012",
        "deviceManufactureName": "Apple",
        "deviceProductDisplayName": "iPhone&reg; 7",
        "colorName": "Gold",
        "capacity": "128GB",
        "flow": "EUP",
        "mtn": "5204562794",
        "displayMtn": "520.456.2794",
        "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-med$&fmt=jpeg&wid=75&hei=150",
        "deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device$&bgc=ffffff&wid=158&hei=300",
        "activationFee": "0.00",
        "waivedActivationFeePromo": false,
        "upgradeFee": "30.00",
        "waivedUpgradeFeePromo": false,
        "edgeDevice": true,
        "price": "27.08",
        "priceText": "Device payment",
        "priceSubTitle": "For 24 months, 0% APR.Retail Price: $649.99",
        "edgeItemDownPaymentAmount": "0.00",
        "installmentBalance": "0.00",
        "deviceEdgeUpAmount": "0.00",
        "deviceEdgeBuyOutAmount": "0.00",
        "protectionOption": {
          "name": "Total Mobile Protection",
          "price": "11.00",
          "featureType": "INS",
          "featureSkuId": "sku1230442",
          "hideEditProtection": false,
          "displayMsg": null
        },
        "commerceItemId": "SDC93c15697bcb30de3cb53e503a4ac50f0{ss100}_device_1",
        "deviceSkuId": "sku2150057",
        "deviceSORId": "MNAL2LL/A",
        "lacPrice": "20.00",
        "lacText": "SMARTPHONE line access",
        "inventoryStatus": "1000",
        "inventoryAvailableDate": null,
        "hasEcpdDiscount": true,
        "hasEcpdDiscountForDevicePayment": false,
        "devicePromotionList": [],
        "bicOfferApplied": false,
        "bicContractPrice": 0,
        "bicDiscountedContractPrice": 0,
        "bicSavings": 0,
        "myOfferWaiveUpgradeFee": false,
        "shipCommitInd": null,
        "promoLACMessage": null,
        "additionalFeatures": [],
        "bicMessage": null,
        "bicMessagetooltip": null,
        "editDeviceUrl": "/preorder/device/expressconfig/?commerceItemId=SDC93c15697bcb30de3cb53e503a4ac50f0%7Bss100%7D_device_1&deviceProdId=dev6640012&deviceSkuId=sku2150057&editDevice=true&flow=EUP",
        "fullRetailPrice": "649.99",
        "fromSavedCart": false,
        "numberShareDevice": false,
        "numberSharedMtn": null,
        "itemOnJaxPlan": false,
        "humCarDetails": null,
        "monthlyPriceAfterDownPaymentBeforeDiscount": 0,
        "originalFullRetailPrice": 0,
        "hasReducedRetailPrice": false,
        "hasReducedDueMonthly": false,
        "originalDueMonthly": 0,
        "lineAccessPromotionText": null,
        "downPaymentPromotionText": null,
        "contractTerm": "99",
        "deviceType": null,
        "activationFeeText": null,
        "promoOfferText": null,
        "promoApplied": false,
        "portIn": false,
        "deviceNickName": "HANK                  HENDERSO-2794",
        "totalNumberShareExtension": 0,
        "sbdOffer": null,
        "hostCommerceItemId": null,
        "trunkMtn": null
      }
    ],
    "accessories": [
      {
        "scene7ImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/universal-leather-case-iset-unisdpchlg1?$acc-med$",
        "name": "Universal Vegan Leather Pouch with Belt Clip - Large",
        "quantity": 1,
        "commerceItemId": "SDC93c15697bcb30de3cb53e503a4ac50f0{ss100}_accessory_2",
        "color": null,
        "size": null,
        "inventoryStatus": "1000",
        "inventoryAvailableDate": null,
        "prodId": "acc1960133",
        "skuId": "sku850133",
        "sorId": "UNISDPCHLG1",
        "hasEcpdDiscount": false,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/universal-leather-case-iset-unisdpchlg1?$acc-med$",
        "hasBogoDiscount": false,
        "price": 30,
        "wasPrice": 30,
        "discounted": false,
        "discountPercentage": 0,
        "discountPrice": 0,
        "editAccessoryUrl": "/preorder/accessoryDetails/?accProdId=acc1960133&action=edit&accCommerceId=SDC93c15697bcb30de3cb53e503a4ac50f0{ss100}_accessory_2&contractTerm=0&deviceSkuId=null#/chooseColor/skuId=sku850133"
      },
      {
        "scene7ImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/rugged-nylon-case-large-a-rugbaglgblk3?$acc-med$",
        "name": "Rugged Nylon Case - Large",
        "quantity": 1,
        "commerceItemId": "SDC93c15697bcb30de3cb53e503a4ac50f0{ss100}_accessory_3",
        "color": null,
        "size": null,
        "inventoryStatus": "1000",
        "inventoryAvailableDate": null,
        "prodId": "acc3440077",
        "skuId": "sku1230379",
        "sorId": "RUGBAGLGBLK3",
        "hasEcpdDiscount": false,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/rugged-nylon-case-large-a-rugbaglgblk3?$acc-med$",
        "hasBogoDiscount": false,
        "price": 9.99,
        "wasPrice": 19.99,
        "discounted": true,
        "discountPercentage": 50.03,
        "discountPrice": 10,
        "editAccessoryUrl": "/preorder/accessoryDetails/?accProdId=acc3440077&action=edit&accCommerceId=SDC93c15697bcb30de3cb53e503a4ac50f0{ss100}_accessory_3&contractTerm=0&deviceSkuId=null#/chooseColor/skuId=sku1230379"
      }
    ],
    "accessoriesBundle": [
      {
        "discountedPrice": "89.99",
        "imgUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphone7-tech21-evo-check-case-bundle-6453-gg-bundle-iset?$acc-med$",
        "regularPrice": "109.97",
        "savedPrice": "19.98",
        "displayName": "Tech 21 Evo Check Case Bundle for iPhone 8/7/6s/6",
        "bundleDescription": null,
        "skuID": "sku2690302",
        "commerceItemId": "SDC93c15697bcb30de3cb53e503a4ac50f0{ss100}_accessory_1",
        "discountPercentage": "18.17",
        "discounted": true,
        "accessoriesDetails": [
          {
            "brand": "",
            "displayName": "Tech 21 Evo Check Case",
            "capacity": 10,
            "productID": "sku2120069",
            "pdpUrl": null,
            "skuDetails": [
              {
                "name": "Evo Check Case for iPhone 8/7 - Smokey/Black",
                "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/tech21-evo-check-case-iphone-6-6s-smokey-black-t21-5329-iset?$acc-med$",
                "price": "39.99",
                "discountedPrice": "37.99",
                "preSelected": false,
                "id": "sku2120069",
                "color": false,
                "comingSoonAcc": false,
                "inCart": false,
                "pdpUrl": null,
                "available": false
              }
            ]
          },
          {
            "brand": "",
            "displayName": "InvisibleShield Glass+ Screen Protector for iPhone 8/7/6s/6",
            "capacity": 10,
            "productID": "sku2120020",
            "pdpUrl": null,
            "skuDetails": [
              {
                "name": "InvisibleShield Glass+ Screen Protector for iPhone 8/7/6s/6",
                "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/zagg-invisibleshield-glass-iphone-6-iset-ip6glc-f00?$acc-med$",
                "price": "39.99",
                "discountedPrice": "34.01",
                "preSelected": false,
                "id": "sku2120020",
                "color": false,
                "comingSoonAcc": false,
                "inCart": false,
                "pdpUrl": null,
                "available": false
              }
            ]
          },
          {
            "brand": "",
            "displayName": "Lightning Car Charger",
            "capacity": 10,
            "productID": "sku2180048",
            "pdpUrl": null,
            "skuDetails": [
              {
                "name": "Lightning Car Charger",
                "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/vzw-2-4a-apple-lightning-vehicle-charger-vpc24lght-m-iset?$acc-med$",
                "price": "29.99",
                "discountedPrice": "17.99",
                "preSelected": false,
                "id": "sku2180048",
                "color": false,
                "comingSoonAcc": false,
                "inCart": false,
                "pdpUrl": null,
                "available": false
              }
            ]
          }
        ]
      }
    ],
    "taxDetails": {
      "taxPrice": "12.16",
      "cityStateString": "Huachuca City, AZ",
      "stateTaxLabel": null,
      "zipCode": null
    },
    "totalDueToday": "172.14",
    "totalDueMonthly": "58.08",
    "employeeDiscount": 0,
    "pastDueBalance": "0.00",
    "emptyCartFlag": false,
    "edgeContractDeviceInCart": true,
    "totalEdgeUpAmount": "0.00",
    "totalEdgeUpBuyOutAmount": "0.00",
    "totalEdgeOrderDownPayment": "0.00",
    "tradeInCredit": null,
    "tradeInPromoDetails": null,
    "promotionList": [],
    "cartMessages": {
      "cartReadyforCheckout": true,
      "message": null,
      "code": null
    },
    "cartItemCount": 4,
    "mailInRebateTotal": 0,
    "mailInRebateDetails": null,
    "promoCodes": [],
    "promoCodeHeader": "Promo code? Lucky you.",
    "promoCodeLabel": "Promo code",
    "addAnotherPromoCodeText": "Add another promo code",
    "applyBtn": "Apply",
    "emptyCartMessage": "There are no items in your cart",
    "shopBtn": "Shop",
    "tradeInPromoEligible": true,
    "eligibleForSingleDeviceRibbon": false,
    "eligibleForMultiDeviceAllocation": false,
    "retrieveCartSuccessful": false,
    "standaloneAccessories": false,
    "dueTodayText": "Due today",
    "dueMonthlyText": "Due Monthly",
    "mainCartHeader": "Time to review your cart.",
    "mainCartSubTitle": "Enjoy free 2-day shipping.",
    "shopMoreBtnText": "Shop more",
    "checkoutBtn": "Check out",
    "editBtn": "Edit",
    "removeLinkText": "Remove",
    "mainCartFooterText": "Want to start over?",
    "mainCartFooterLinkText": "Emtpy your cart",
    "shopMoreLink": "/preorder/shoplanding/",
    "activationFeeText": "Activation Fee",
    "waivedActivationText": "Waived Activation Fee",
    "upgradeFeeText": "Upgrade Fee",
    "waivedUpgradeFeeText": "Waived Upgrade Fee",
    "saveBtnLabel": "Save",
    "zipCodeHeader": "Please enter a new ZIP code",
    "tradeInCreditHeader": "Trade-in Credit for this device",
    "tradeInFooterLink": "Tell me more",
    "tradeInOfferDetailsHeader": "Offer Details",
    "tradeInOfferDetailsMsg": "long block of text",
    "tradeInConfirmationBtn": "Got it",
    "lonelyCartMessage": "Your cart is lonely.",
    "checkoutButtonURL": "/preorder/checkout/initiateCheckout",
    "tradeInUrl": "/preorder/promos/tradeauth?gotoCart=true",
    "mainInRebateDetails": null,
    "deviceProtectionDetails": {
      "deviceProtectionDetailsHeader": "device protection details",
      "deviceProtectionDetailsSubTitle": "Five things you need to know about Equipment Protection",
      "deviceProtectionDetailsText": "<div> <p>Cost per Month and Individual Service Availability. Total Mobile Protection (TMP) Single Device and Total Mobile Protection Multi-Device are a combination of multiple products, each of which is available separately per device: Wireless Phone Protection (WPP) $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; Verizon Wireless Extended Warranty (EW) $3.00; and Verizon Tech Coach $7.00. You may also purchase Total Equipment Coverage (TEC) for $7.00/Basic Devices &amp; Tablets or for $9.00/Smartphones &amp; iPhone Devices. TEC is a combination of 2 products, each of which is available separately: WPP $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; and Verizon Wireless EW for $3.00.</p> <p> Applicability and Amount of Deductible.  For lost, stolen and damaged device claims, deductibles are $49 for basic phones and, depending on device, $49-$199 for smartphones and tablets. For a full list of deductibles click here <a href='http://phoneclaim.com/verizon/deductible' target='_blank'>http://phoneclaim.com/verizon/deductible.</a> </p> <p>Claim Limits for loss, stolen and damaged devices. Equipment claim maximum is $400 or $1,500, depending on device, and limited to three claims per 12-month period for TMP Single Device and up to nine claims per 12-month period for TMP Multi-Device.</p> <p>Covered and Replacement Equipment. If your device is lost, stolen or damaged, your accessories are covered too ï¿1Ž2 one each of the following: standard battery, standard car charger, standard case, standard home charger and standard earbud. It is our goal to provide you with a replacement device that is the same color and has the same features, but this cannot be guaranteed. If the same make and model you claim is not available, a similar make and model will be substituted. Your replacement device could be new or refurbished. You may also receive generic accessories with lost, stolen or damaged claims.</p> <p>Cancellation Policy. Change your mind? You can cancel your coverage at any time and receive a pro-rated refund of your monthly fee.</p> </div>"
    },
    "preOrderAlertMsg": "Your order contains one or more items that are not in stock. All items will ship together when everything is available.",
    "bicText": null,
    "hasSubmittedTradein": false,
    "cpcSucessful": false,
    "cpcSucessfulNotification": false,
    "protectionURL": "/preorder/protection",
    "itemsFromRetrievedCart": false,
    "totalActivationFee": "0.00",
    "itemOnJaxPlan": false,
    "anyLineFreeSPO": null,
    "bicOfferMessage": null,
    "cartMFCompatible": false,
    "cartValidationDetailsVo": {
      "cartReadyforCheckout": true,
      "cartIncompleteCode": null,
      "cartIncompleteMessage": null,
      "orderId": "SDC93c15697bcb30de3cb53e503a4ac50f0{ss100}"
    },
    "cartEdited": false,
    "iconicFlow": false,
    "plans": {
      "planOnlyDueMonthly": "35.00",
      "dueMonthly": "35.00",
      "dueToday": "0.00",
      "items": [
        {
          "planType": "The new Verizon Plan Small 2 GB",
          "planSorId": "96325",
          "planProdId": "plan2880001",
          "planSkuId": "sku2040014",
          "planLetter": null,
          "planDescription": "",
          "planDisplayName": "The new Verizon Plan Small 2 GB",
          "planChangeURL": null,
          "planImageURL": null,
          "accountAccess": {
            "name": "The new Verizon Plan Small 2 GB",
            "price": "35.00",
            "discountPrice": 0,
            "promoMessage": null,
            "hasEcpdDiscount": false,
            "planAmount": "35.00"
          }
        }
      ]
    },
    "removePromoCodeURL": "/preorder/cart/removePromoCode",
    "applyPromoCodeURL": "/preorder/cart/applyPromoCode",
    "clearCartURL": "/preorder/cart/clearCart",
    "addOrUpdateDeviceURL": "/preorder/cart/addOrUpdateDevice",
    "addOrRemoveAccessoryURL": "/preorder/cart/addOrRemoveAccessory",
    "changeZipCodeURL": "/preordercart/changeZipCode/",
    "addOrUpdateFeatureURL": "/preorder/cart/addOrUpdateFeature",
    "initiateCheckoutURL": "/preorder/checkout/initiateCheckout",
    "splitShipment": false
  },
  "errorMap": null,
  "statusMessage": ""
};

 export default cartJSON;
