const mdnJSON  ={
  "statusCode": "00",
  "errorMap": null,
  "output": {
    "mtnDetailsList": [
      {
        "upgradeEligbile": false,
        "displayMtn": "916.217.2242",
        "mtn": "9162172242",
        "encryptedMTN": "Jx21f7CsmMqYObha/B6DnA==",
        "upgradeMessage": null,
        "nickname": "DON                 K BOWER-2242",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iphone4_white?$device-thumb$",
        "inEligibleCode": "12",
        "inEligibleDetails": null,
        "loanInfo": null,
        "annualUpgradeMessage": null,
        "deviceType": "Smartphone",
        "familyType": "Phone",
        "familyTypeRestricted": false,
        "contractTermMisMatch": false,
        "brand": "Apple",
        "deviceId": "",
        "twoYearContract": null,
        "annualUpgrade": false,
        "displayDeviceName": "Apple&reg; iPhone&reg; 4",
        "deviceName": "IPHONE 4 WHITE 8 GB",
        "eligibleUpgradeTypeList": [
          "Retail"
        ],
        "mtnAddedToTheCart": false,
        "lineSharingIndicator": null,
        "buyoutRestrictedForEdge": false,
        "alwaysEligibleForUpgrade": false,
        "sorDeviceType": " ",
        "daccCode": "00518",
        "deviceProdId": "dev440045",
        "annualUpgradeWarning": false
      },
      {
        "upgradeEligbile": false,
        "displayMtn": "916.217.9342",
        "mtn": "9162179342",
        "encryptedMTN": "+6bqgdDvO36YObha/B6DnA==",
        "upgradeMessage": null,
        "nickname": "DON                 K BOWER-9342",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iPhone5S-SpGray?$device-thumb$",
        "inEligibleCode": "12",
        "inEligibleDetails": null,
        "loanInfo": null,
        "annualUpgradeMessage": null,
        "deviceType": "Smartphone",
        "familyType": "Phone",
        "familyTypeRestricted": false,
        "contractTermMisMatch": false,
        "brand": "Apple",
        "deviceId": "356962062588870",
        "twoYearContract": null,
        "annualUpgrade": false,
        "displayDeviceName": "Apple&reg; iPhone&reg; 5s 16GB in Space Gray",
        "deviceName": "iPhone 5S Space Gray 16GB",
        "eligibleUpgradeTypeList": [
          "Retail"
        ],
        "mtnAddedToTheCart": false,
        "lineSharingIndicator": null,
        "buyoutRestrictedForEdge": false,
        "alwaysEligibleForUpgrade": false,
        "sorDeviceType": "4GE",
        "daccCode": "00733",
        "deviceProdId": "dev1040044",
        "annualUpgradeWarning": false
      },
      {
        "upgradeEligbile": false,
        "displayMtn": "916.224.8398",
        "mtn": "9162248398",
        "encryptedMTN": "zhlKWa/baEylxXhwY297Fg==",
        "upgradeMessage": null,
        "nickname": "DON                 K BOWER-8398",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-ipad-mini3-gold?$device-thumb$",
        "inEligibleCode": "12",
        "inEligibleDetails": null,
        "loanInfo": null,
        "annualUpgradeMessage": null,
        "deviceType": "Tablet",
        "familyType": "Tablet Internet Home",
        "familyTypeRestricted": true,
        "contractTermMisMatch": false,
        "brand": "Apple",
        "deviceId": "355894062992730",
        "twoYearContract": null,
        "annualUpgrade": false,
        "displayDeviceName": "Apple&reg; iPad&reg; mini 3 16GB in Gold",
        "deviceName": "IPAD MINI 3 16GB GOLD",
        "eligibleUpgradeTypeList": [
          "Retail"
        ],
        "mtnAddedToTheCart": false,
        "lineSharingIndicator": null,
        "buyoutRestrictedForEdge": false,
        "alwaysEligibleForUpgrade": false,
        "sorDeviceType": "4GE",
        "daccCode": "00684",
        "deviceProdId": "dev3360007",
        "annualUpgradeWarning": false
      }
    ],
    "accountLevelInEligibleCode": null,
    "accountLevelInEligibleMessage": null,
    "selectedMTN": "9162179342",
    "aalRedirect": null,
    "accountLevelInEligibleDetails": {
      "accountLevelEUPInEligibleDetails": {
        "accountLevelInEligibleCode": "12",
        "accountLevelInEligibleMessage": null,
        "accountLevelInEligibleDetails": {
          "title": "You have a plan change pending.",
          "subTitle": "To continue with your order, you need to cancel your scheduled plan change. Do you want to do this?.",
          "buttonText": "Yes, cancel my plan change.",
          "linkText": "No, don't cancel my plan change",
          "linkURL": null,
          "customerServiceNumber": "(800) 922-0204",
          "cancelPlanChangeURL": "/od/cust/auth/cancelPendingOrder/?pendingOrderNo=691147449"
        },
        "planType": null
      },
      "accountLevelAALInEligibleDetails": null
    },
    "cartRedirect": "/od/cust/auth/cart/getCartDetails",
    "shopLandingRedirect": "/od/cust/auth/shoplanding/",
    "mtnMainTitle": "Would you like to upgrade or add a new device?",
    "catergoryCode": null,
    "unlimitedPlan": "N",
    "pastDueDetails": null,
    "submitAddALineUrl": "/od/cust/auth/submitaddaline",
    "customerType": null,
    "edgeEligible": true,
    "ajaxCallUrl": "/od/cust/auth/submitSummary",
    "ajaxCallSelectedMTN": "/od/cust/auth/mtnDetail/json?flow=EUP&t=",
    "redirectURL": null,
    "sharedPlan": true,
    "aalAllowed": true,
    "aalboxEnable": true
  },
  "cpcRequired": false
}

export default mdnJSON;
