export const ASYNC_FETCH = 'ASYNC_FETCH';
export const ASYNC_FETCH_SUCCESS = 'ASYNC_FETCH_SUCCESS';
export const ASYNC_FETCH_FAILURE = 'ASYNC_FETCH_FAILURE';
export const ASYNC_FETCH_INVALIDATE = 'ASYNC_FETCH_INVALIDATE';
export const UPDATE_ADDRESSINFO_RESPONSE = 'UPDATE_ADDRESSINFO_RESPONSE';
export const ADDRESS_VALIDATION_FAILED = 'ADDRESS_VALIDATION_FAILED';

