const json = 

{
  "output": {
    "title": "You're all set.",
    "subtitle": null,
    "orderId": "90915825259623",
    "estimatedDelivery": "",
    "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/1.3_MV_BuyandUpgrade_ConfirmationPage_Interstital?$device-med$",
    "tradeInStatus": false,
    "confirmationMessage": "Thanks for ordering from verizonwireless.com. Your order receipt is sent to VZW@VZW.COM.",
    "doneButtonText": "Got it",
    "doneButtonLink": "/od/cust/auth/shoplanding/",
    "userNote": "TODO",
    "notNowButtonText": "TODO",
    "notNowButtonLink": "TODO",
    "learnHowButtonText": null,
    "learnHowButtonLink": "/od/cust/auth/learnHow",
    "numberOfDevice": 1,
    "confirmationNumberText": "Confirmation Number",
    "iconicFlow": true,
    "protectionURL": null,
    "accessoriesURL": null,
    "tapFlag": false,
    "cjmTagUrl": null,
    "pepperJamTagUrl": null,
    "selectedPaymentMode": null,
    "confirmationEmail": "VZW@VZW.COM",
    "plans": {
      "dueMonthly": "50.00",
      "dueToday": "0.00",
      "planOnlyDueMonthly": "50.00",
      "items": [
        {
          "planType": "The new Verizon Plan Medium 4 GB",
          "lineAccessCharges": [
            {
              "name": "Apple iPhone&reg; XS Max 64GB in Silver",
              "mtn": "7703019294",
              "price": "20.00",
              "discountPrice": "0.00",
              "retailPrice": "0.00",
              "hasEcpdDiscount": false,
              "promoMessage": null,
              "originalPrice": "20.00",
              "wasPrice": "20.00",
              "deviceName": "iPhone&reg; XS Max",
              "color": "Silver",
              "size": "64GB",
              "introText": null,
              "smartFamily": false,
              "freeTrial": false,
              "tapfeature": false,
              "amountAfterInstantCredit": "0.00",
              "disountedInstantCreditAmt": "0.00",
              "instantCreditAmount": "0.00"
            }
          ],
          "accountAccess": {
            "name": "The new Verizon Plan Medium 4 GB",
            "mtn": null,
            "price": "50.00",
            "discountPrice": "0.00",
            "retailPrice": "0.00",
            "hasEcpdDiscount": false,
            "promoMessage": null,
            "originalPrice": "0.00",
            "wasPrice": "0.00",
            "deviceName": null,
            "color": null,
            "size": null,
            "introText": null,
            "smartFamily": false,
            "freeTrial": false,
            "tapfeature": false,
            "amountAfterInstantCredit": "0.00",
            "disountedInstantCreditAmt": "0.00",
            "instantCreditAmount": "0.00"
          },
          "accountLevelFeatures": null,
          "totalMonthlyPlanCost": "50.00",
          "spoBadgeMessage": null,
          "planDisplayName": "The new Verizon Plan Medium 4 GB",
          "planImageURL": null,
          "planLetter": null,
          "planDescrption": null,
          "planDescription": null,
          "quantity": 0,
          "skuId": null,
          "productId": null,
          "itemAmount": null,
          "itemAmountOriginal": null,
          "dueMonthly": null,
          "dueMonthlyOriginal": null,
          "itemDiscount": null,
          "displayName": null,
          "skuDisplayName": null,
          "listPrice": null,
          "rawTotalAmount": null,
          "planGroupCode": null,
          "autoPayEnabled": false,
          "numberSharePlan": false,
          "planCommerceItemId": null,
          "autoPayPrice": null,
          "autoPayText": null,
          "termsAndConditionKey": null,
          "unitOfMeasure": null,
          "planSize": null,
          "planChanged": false,
          "cpcDone": false
        }
      ],
      "upgradeDevices": null,
      "newDevices": null,
      "existingDevices": null,
      "dueMonthlyPlanWithLAC": null,
      "discountedDueMonthlyPlanWithLAC": null,
      "hasEcpdDiscount": false,
      "totalLineAccessCharges": "20.00"
    },
    "tradeInDevicesDetails": null,
    "tradeInPromoDetails": null,
    "transformedTradeInPromoDetails": null,
    "subOrders": null,
    "comboOrder": false,
    "totalDueToday": "120.40",
    "totalDueMonthly": "110.83",
    "subTotalDueToday": "0.00",
    "securityDepositAmount": "0.00",
    "stateSalesTax": "90.40",
    "stateSalesTaxOriginal": null,
    "stateSalesTaxInstantCredit": null,
    "employeeDiscount": "0.00",
    "pastDueExist": false,
    "pastDueAmountPaid": false,
    "pastDueAmount": "0.00",
    "shippingInfo": {
      "shippingInfoUpdated": false,
      "sameAsBilling": true,
      "ispuEligibleFlag": true,
      "addressInfo": {
        "firstName": "KENNY",
        "lastName": "REYES",
        "companyName": null,
        "address1": "101 MURPHY INDUSTRIAL BLVD",
        "address2": null,
        "city": "Bremen",
        "state": "GA",
        "zipcode": "30110",
        "businessName": null,
        "postalCode": null,
        "email": "VZW@VZW.COM",
        "phoneNumber": "7705875888"
      },
      "contactInfo": {
        "emailAddress": "VZW@VZW.COM",
        "phoneNumber": "7705875888",
        "firstName": "KENNY",
        "lastName": "REYES",
        "smsMdn": null,
        "activeSMSCapableMtnList": null
      },
      "shippingTypesInfo": null,
      "storeDetail": {
        "storeHeader": null,
        "storeName": null,
        "storeAddress": null,
        "deviceAvailable": false,
        "distance": null,
        "appendedStoreTiming": null,
        "longitude": null,
        "storeId": null,
        "netaceLocationCode": null,
        "latitude": null,
        "seoUrlName": null,
        "storeClosingTime": null,
        "directStore": null
      },
      "tradeIn": false,
      "tradeInAddress": null,
      "nonSddEligibleMsg": null,
      "selectedSDDWindow": null,
      "selectedSDDFormattedWindow": null,
      "poboMessage": null,
      "vendorShippingTypesInfo": null,
      "verizonCommerceItemsNames": [
        "iPhone&reg; XS Max"
      ],
      "vendorCommerceItemsNames": null,
      "vendorShippingOptionExists": false,
      "ispudetailsInfo": {
        "storeAddress": null,
        "storeHours": null,
        "storeId": null,
        "storeName": null,
        "phoneNumber": null,
        "distance": null,
        "totalItems": 0,
        "availItems": 0,
        "latitdude": 0.0,
        "longtitude": 0.0,
        "availItemName": null,
        "directStore": null
      }
    },
    "billingInfo": {
      "billToAccountEligible": true,
      "creditCardZipEditable": false,
      "billingAddress": {
        "firstName": "KENNY",
        "lastName": "REYES",
        "businessName": null,
        "zipcode": "30110",
        "state": "GA",
        "address2": null,
        "address1": "101 MURPHY INDUSTRIAL BLVD",
        "companyName": null,
        "city": "Bremen",
        "sameAsShipping": false
      },
      "masterpass3DSecure": null,
      "billToAccountNumber": "#XXXXXXX-0001",
      "creditCardInfo": {
        "savedCardNickName": null,
        "preselectCard": null,
        "creditCardNumber": null,
        "creditCardExpMonth": null,
        "creditCardExpYear": null,
        "billingZipCode": null,
        "creditCardType": null,
        "creditCardVerificationNumber": null,
        "creditCardBIN": null,
        "cvvRequired": false
      },
      "selectedPaymentMode": "BTA",
      "giftCardList": [

      ],
      "savedCardInfo": null,
      "applePayResponseInfo": null,
      "masterpassResponseInfo": {
        "emailAddress": null,
        "cardType": null,
        "lastDigits": null,
        "creditCardBIN": null,
        "masterpassSelected": false
      },
      "masterpassError": false,
      "masterpassErrorMessage": null,
      "cybersourecPreAuthFailure": false,
      "cybersourecPreAuthFailureErrorMessage": null,
      "paypalEmailAddress": null,
      "expirationMonths": null,
      "expirationYears": null
    },
    "devices": {
      "dueMonthly": 90.83,
      "totalActivationFee": 0.0,
      "deviceTotalDueMonthly": 45.83,
      "dueToday": 0.0,
      "accessories": [

      ],
      "accessoriesBundle": [

      ],
      "globalPromotions": [

      ],
      "items": [
        {
          "deviceName": "iPhone&reg; XS Max",
          "dueMonthly": "45.83",
          "dueToday": "0.00",
          "upgradeFee": "30.00",
          "originalUpgradeFee": "30.00",
          "activationFee": "0.00",
          "dueTodayOriginal": "0.00",
          "dueMonthlyOriginal": null,
          "dueTodayDiscounted": false,
          "dueMonthlyDiscounted": false,
          "mtn": "7703019294",
          "sorId": "MT6G2LL/A",
          "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphonexs-max-silver?$device-med$&fmt=jpeg&wid=75&hei=150",
          "protectionFeature": {
            "name": "Verizon Protect Multi-Device",
            "mtn": null,
            "price": "45.00",
            "priceTerm":"/mo.",
            "discountPrice": "0.00",
            "retailPrice": "0.00",
            "hasEcpdDiscount": false,
            "promoMessage": null,
            "originalPrice": "0.00",
            "wasPrice": "0.00",
            "deviceName": null,
            "color": null,
            "size": null,
            "introText": null,
            "smartFamily": false,
            "freeTrial": false,
            "tapfeature": true,
            "amountAfterInstantCredit": "0.00",
            "disountedInstantCreditAmt": "0.00",
            "instantCreditAmount": "0.00"
          },
          "optionalFeatures": [

          ],
          "installmentBalance": "1099.99",
          "edgeRetailPrice": "1099.99",
          "edgeItemDownPaymentAmount": "0.00",
          "mailInRebateAmount": "0.00",
          "transferredFromMtn": null,
          "devicePromotionList": [

          ],
          "bicOfferApplied": false,
          "bicContractPrice": "0.00",
          "bicDiscountedContractPrice": "-1.00",
          "bicAdditionalContractText": null,
          "bicMessageMap": null,
          "edgeUpAmount": 0.0,
          "displayDeviceDueMonthly": 110.83,
          "deviceLACFee": "20.00",
          "manufactureName": "Apple",
          "color": "Silver",
          "colorCode": "#d7d7d7",
          "size": "64GB",
          "displayName": "iPhone&reg; XS Max",
          "contractTerm": "99",
          "edgeUpBuyOutAmount": 0.0,
          "fullRetailPrice": "1099.99",
          "alwaysEligibleForUpgrade": false,
          "numberShareDevice": false,
          "activationFeeText": null,
          "numberSharedMtn": null,
          "promoContentText": null,
          "itemOnJaxPlan": false,
          "humCarDetails": null,
          "simDetails": null,
          "imeiId": null,
          "displayImeiId": null,
          "poboDateLabel": null,
          "nickName": null,
          "planCommerceItemId": null,
          "displayMtn": null,
          "dppContractDetails": "You'll see the first installment in your next billing cycle. 24 months,0% APR; Retail price: $1099.99",
          "optionalDownpaymentInstantCredit": null,
          "twoYearInstantCreditAmount": null,
          "fullRetailInstantCreditAmount": null,
          "twoYearPriceOrginal": null,
          "twoYearPriceInstantCreditApplied": null,
          "instantCreditAppliedAmount": 0.0,
          "instantCreditAdjustedPrice": "$0.00",
          "instantCreditFullRetailPrice": null,
          "tradeinPromoDetails": null,
          "numberSharedDeviceName": null,
          "productDetails": {
            "manufacturerDisplayName": "Apple",
            "brandName": "Apple",
            "displayName": "iPhone&reg; XS Max",
            "deviceId": "dev10640019",
            "skuColors": {
              "Silver": {
                "color": "Silver",
                "anySkusInStock": true,
                "allSkusOutOfStock": false,
                "allSkusPreOrder": false,
                "allSkusBackOrder": false,
                "skus": [
                  {
                    "intCapacity": 64,
                    "deviceSkuId": "sku3180118",
                    "deviceSorId": "MT6G2LL/A",
                    "displayName": "Apple&reg; iPhone&reg; Xs Max 64GB in Silver",
                    "capacity": "64GB",
                    "colorCode": "#d7d7d7",
                    "colorName": "Silver",
                    "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphonexs-max-silver?$device-lg$",
                    "inventoryStatus": "1000",
                    "instorePickupFlag": true,
                    "devicePrice": [
                      {
                        "displayOriginalPrice": "45.83",
                        "displayDiscountedPrice": "45.83",
                        "displayEdgeFullRetailPrice": "1099.99",
                        "listPrice": 45.83,
                        "discountPrice": 45.83,
                        "priceListId": "Edge",
                        "contractTerm": 99,
                        "contractDetail": "/mo.",
                        "originalPrice": 45.83,
                        "edgePrice": true,
                        "contractName": "24 Monthly Payments",
                        "discountedPrice": 45.83,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": 1099.99,
                        "contractTitle": "Monthly Device Payment",
                        "loanTerm": "24",
                        "edgeContractText": "$0 Down (for qualified customers) $45.83/mo for 24 months; 0% APR Retail Price: $1099.99",
                        "promoBadgeMessages": null
                      },
                      {
                        "displayOriginalPrice": "1099.99",
                        "displayDiscountedPrice": "1099.99",
                        "displayEdgeFullRetailPrice": null,
                        "listPrice": 1099.99,
                        "discountPrice": 1099.99,
                        "priceListId": "FullRetail",
                        "contractTerm": 0,
                        "contractDetail": null,
                        "originalPrice": 1099.99,
                        "edgePrice": false,
                        "contractName": "Retail Price",
                        "discountedPrice": 1099.99,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": null,
                        "contractTitle": "No Early Termination Fee",
                        "loanTerm": null,
                        "edgeContractText": null,
                        "promoBadgeMessages": null
                      }
                    ]
                  },
                  {
                    "intCapacity": 256,
                    "deviceSkuId": "sku3180121",
                    "deviceSorId": "MT6K2LL/A",
                    "displayName": "Apple&reg; iPhone&reg; Xs Max 256GB in Silver",
                    "capacity": "256GB",
                    "colorCode": "#d7d7d7",
                    "colorName": "Silver",
                    "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphonexs-max-silver?$device-lg$",
                    "inventoryStatus": "1001",
                    "instorePickupFlag": true,
                    "devicePrice": [
                      {
                        "displayOriginalPrice": "52.08",
                        "displayDiscountedPrice": "52.08",
                        "displayEdgeFullRetailPrice": "1249.99",
                        "listPrice": 52.08,
                        "discountPrice": 52.08,
                        "priceListId": "Edge",
                        "contractTerm": 99,
                        "contractDetail": "/mo.",
                        "originalPrice": 52.08,
                        "edgePrice": true,
                        "contractName": "24 Monthly Payments",
                        "discountedPrice": 52.08,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": 1249.99,
                        "contractTitle": "Monthly Device Payment",
                        "loanTerm": "24",
                        "edgeContractText": "$0 Down (for qualified customers) $52.08/mo for 24 months; 0% APR Retail Price: $1249.99",
                        "promoBadgeMessages": null
                      },
                      {
                        "displayOriginalPrice": "1249.99",
                        "displayDiscountedPrice": "1249.99",
                        "displayEdgeFullRetailPrice": null,
                        "listPrice": 1249.99,
                        "discountPrice": 1249.99,
                        "priceListId": "FullRetail",
                        "contractTerm": 0,
                        "contractDetail": null,
                        "originalPrice": 1249.99,
                        "edgePrice": false,
                        "contractName": "Retail Price",
                        "discountedPrice": 1249.99,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": null,
                        "contractTitle": "No Early Termination Fee",
                        "loanTerm": null,
                        "edgeContractText": null,
                        "promoBadgeMessages": null
                      }
                    ]
                  },
                  {
                    "intCapacity": 512,
                    "deviceSkuId": "sku3180124",
                    "deviceSorId": "MT6N2LL/A",
                    "displayName": "Apple&reg; iPhone&reg; Xs Max 512GB in Silver",
                    "capacity": "512GB",
                    "colorCode": "#d7d7d7",
                    "colorName": "Silver",
                    "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphonexs-max-silver?$device-lg$",
                    "inventoryStatus": "1000",
                    "instorePickupFlag": true,
                    "devicePrice": [
                      {
                        "displayOriginalPrice": "60.41",
                        "displayDiscountedPrice": "60.41",
                        "displayEdgeFullRetailPrice": "1449.99",
                        "listPrice": 60.41,
                        "discountPrice": 60.41,
                        "priceListId": "Edge",
                        "contractTerm": 99,
                        "contractDetail": "/mo.",
                        "originalPrice": 60.41,
                        "edgePrice": true,
                        "contractName": "24 Monthly Payments",
                        "discountedPrice": 60.41,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": 1449.99,
                        "contractTitle": "Monthly Device Payment",
                        "loanTerm": "24",
                        "edgeContractText": "$0 Down (for qualified customers) $60.41/mo for 24 months; 0% APR Retail Price: $1449.99",
                        "promoBadgeMessages": null
                      },
                      {
                        "displayOriginalPrice": "1449.99",
                        "displayDiscountedPrice": "1449.99",
                        "displayEdgeFullRetailPrice": null,
                        "listPrice": 1449.99,
                        "discountPrice": 1449.99,
                        "priceListId": "FullRetail",
                        "contractTerm": 0,
                        "contractDetail": null,
                        "originalPrice": 1449.99,
                        "edgePrice": false,
                        "contractName": "Retail Price",
                        "discountedPrice": 1449.99,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": null,
                        "contractTitle": "No Early Termination Fee",
                        "loanTerm": null,
                        "edgeContractText": null,
                        "promoBadgeMessages": null
                      }
                    ]
                  }
                ]
              },
              "Space Gray": {
                "color": "Space Gray",
                "anySkusInStock": true,
                "allSkusOutOfStock": false,
                "allSkusPreOrder": false,
                "allSkusBackOrder": false,
                "skus": [
                  {
                    "intCapacity": 64,
                    "deviceSkuId": "sku3180117",
                    "deviceSorId": "MT6F2LL/A",
                    "displayName": "Apple&reg; iPhone&reg; Xs Max 64GB in Space Gray",
                    "capacity": "64GB",
                    "colorCode": "#807F84",
                    "colorName": "Space Gray",
                    "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphonexs-max-spacegrey?$device-lg$",
                    "inventoryStatus": "1000",
                    "instorePickupFlag": true,
                    "devicePrice": [
                      {
                        "displayOriginalPrice": "45.83",
                        "displayDiscountedPrice": "45.83",
                        "displayEdgeFullRetailPrice": "1099.99",
                        "listPrice": 45.83,
                        "discountPrice": 45.83,
                        "priceListId": "Edge",
                        "contractTerm": 99,
                        "contractDetail": "/mo.",
                        "originalPrice": 45.83,
                        "edgePrice": true,
                        "contractName": "24 Monthly Payments",
                        "discountedPrice": 45.83,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": 1099.99,
                        "contractTitle": "Monthly Device Payment",
                        "loanTerm": "24",
                        "edgeContractText": "$0 Down (for qualified customers) $45.83/mo for 24 months; 0% APR Retail Price: $1099.99",
                        "promoBadgeMessages": null
                      },
                      {
                        "displayOriginalPrice": "1099.99",
                        "displayDiscountedPrice": "1099.99",
                        "displayEdgeFullRetailPrice": null,
                        "listPrice": 1099.99,
                        "discountPrice": 1099.99,
                        "priceListId": "FullRetail",
                        "contractTerm": 0,
                        "contractDetail": null,
                        "originalPrice": 1099.99,
                        "edgePrice": false,
                        "contractName": "Retail Price",
                        "discountedPrice": 1099.99,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": null,
                        "contractTitle": "No Early Termination Fee",
                        "loanTerm": null,
                        "edgeContractText": null,
                        "promoBadgeMessages": null
                      }
                    ]
                  },
                  {
                    "intCapacity": 256,
                    "deviceSkuId": "sku3180120",
                    "deviceSorId": "MT6J2LL/A",
                    "displayName": "Apple&reg; iPhone&reg; Xs Max 256GB in Space Gray",
                    "capacity": "256GB",
                    "colorCode": "#807F84",
                    "colorName": "Space Gray",
                    "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphonexs-max-spacegrey?$device-lg$",
                    "inventoryStatus": "1000",
                    "instorePickupFlag": true,
                    "devicePrice": [
                      {
                        "displayOriginalPrice": "52.08",
                        "displayDiscountedPrice": "52.08",
                        "displayEdgeFullRetailPrice": "1249.99",
                        "listPrice": 52.08,
                        "discountPrice": 52.08,
                        "priceListId": "Edge",
                        "contractTerm": 99,
                        "contractDetail": "/mo.",
                        "originalPrice": 52.08,
                        "edgePrice": true,
                        "contractName": "24 Monthly Payments",
                        "discountedPrice": 52.08,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": 1249.99,
                        "contractTitle": "Monthly Device Payment",
                        "loanTerm": "24",
                        "edgeContractText": "$0 Down (for qualified customers) $52.08/mo for 24 months; 0% APR Retail Price: $1249.99",
                        "promoBadgeMessages": null
                      },
                      {
                        "displayOriginalPrice": "1249.99",
                        "displayDiscountedPrice": "1249.99",
                        "displayEdgeFullRetailPrice": null,
                        "listPrice": 1249.99,
                        "discountPrice": 1249.99,
                        "priceListId": "FullRetail",
                        "contractTerm": 0,
                        "contractDetail": null,
                        "originalPrice": 1249.99,
                        "edgePrice": false,
                        "contractName": "Retail Price",
                        "discountedPrice": 1249.99,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": null,
                        "contractTitle": "No Early Termination Fee",
                        "loanTerm": null,
                        "edgeContractText": null,
                        "promoBadgeMessages": null
                      }
                    ]
                  },
                  {
                    "intCapacity": 512,
                    "deviceSkuId": "sku3180123",
                    "deviceSorId": "MT6M2LL/A",
                    "displayName": "Apple&reg; iPhone&reg; Xs Max 512GB in Space Gray",
                    "capacity": "512GB",
                    "colorCode": "#807F84",
                    "colorName": "Space Gray",
                    "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphonexs-max-spacegrey?$device-lg$",
                    "inventoryStatus": "1001",
                    "instorePickupFlag": true,
                    "devicePrice": [
                      {
                        "displayOriginalPrice": "60.41",
                        "displayDiscountedPrice": "60.41",
                        "displayEdgeFullRetailPrice": "1449.99",
                        "listPrice": 60.41,
                        "discountPrice": 60.41,
                        "priceListId": "Edge",
                        "contractTerm": 99,
                        "contractDetail": "/mo.",
                        "originalPrice": 60.41,
                        "edgePrice": true,
                        "contractName": "24 Monthly Payments",
                        "discountedPrice": 60.41,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": 1449.99,
                        "contractTitle": "Monthly Device Payment",
                        "loanTerm": "24",
                        "edgeContractText": "$0 Down (for qualified customers) $60.41/mo for 24 months; 0% APR Retail Price: $1449.99",
                        "promoBadgeMessages": null
                      },
                      {
                        "displayOriginalPrice": "1449.99",
                        "displayDiscountedPrice": "1449.99",
                        "displayEdgeFullRetailPrice": null,
                        "listPrice": 1449.99,
                        "discountPrice": 1449.99,
                        "priceListId": "FullRetail",
                        "contractTerm": 0,
                        "contractDetail": null,
                        "originalPrice": 1449.99,
                        "edgePrice": false,
                        "contractName": "Retail Price",
                        "discountedPrice": 1449.99,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": null,
                        "contractTitle": "No Early Termination Fee",
                        "loanTerm": null,
                        "edgeContractText": null,
                        "promoBadgeMessages": null
                      }
                    ]
                  }
                ]
              },
              "Gold": {
                "color": "Gold",
                "anySkusInStock": false,
                "allSkusOutOfStock": true,
                "allSkusPreOrder": false,
                "allSkusBackOrder": false,
                "skus": [
                  {
                    "intCapacity": 64,
                    "deviceSkuId": "sku3180119",
                    "deviceSorId": "MT6H2LL/A",
                    "displayName": "Apple&reg; iPhone&reg; Xs Max 64GB in Gold",
                    "capacity": "64GB",
                    "colorCode": "#CFBEA9",
                    "colorName": "Gold",
                    "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphonexs-max-gold?$device-lg$",
                    "inventoryStatus": "1001",
                    "instorePickupFlag": true,
                    "devicePrice": [
                      {
                        "displayOriginalPrice": "45.83",
                        "displayDiscountedPrice": "45.83",
                        "displayEdgeFullRetailPrice": "1099.99",
                        "listPrice": 45.83,
                        "discountPrice": 45.83,
                        "priceListId": "Edge",
                        "contractTerm": 99,
                        "contractDetail": "/mo.",
                        "originalPrice": 45.83,
                        "edgePrice": true,
                        "contractName": "24 Monthly Payments",
                        "discountedPrice": 45.83,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": 1099.99,
                        "contractTitle": "Monthly Device Payment",
                        "loanTerm": "24",
                        "edgeContractText": "$0 Down (for qualified customers) $45.83/mo for 24 months; 0% APR Retail Price: $1099.99",
                        "promoBadgeMessages": null
                      },
                      {
                        "displayOriginalPrice": "1099.99",
                        "displayDiscountedPrice": "1099.99",
                        "displayEdgeFullRetailPrice": null,
                        "listPrice": 1099.99,
                        "discountPrice": 1099.99,
                        "priceListId": "FullRetail",
                        "contractTerm": 0,
                        "contractDetail": null,
                        "originalPrice": 1099.99,
                        "edgePrice": false,
                        "contractName": "Retail Price",
                        "discountedPrice": 1099.99,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": null,
                        "contractTitle": "No Early Termination Fee",
                        "loanTerm": null,
                        "edgeContractText": null,
                        "promoBadgeMessages": null
                      }
                    ]
                  },
                  {
                    "intCapacity": 256,
                    "deviceSkuId": "sku3180122",
                    "deviceSorId": "MT6L2LL/A",
                    "displayName": "Apple&reg; iPhone&reg; Xs Max 256GB in Gold",
                    "capacity": "256GB",
                    "colorCode": "#CFBEA9",
                    "colorName": "Gold",
                    "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphonexs-max-gold?$device-lg$",
                    "inventoryStatus": "1001",
                    "instorePickupFlag": true,
                    "devicePrice": [
                      {
                        "displayOriginalPrice": "52.08",
                        "displayDiscountedPrice": "52.08",
                        "displayEdgeFullRetailPrice": "1249.99",
                        "listPrice": 52.08,
                        "discountPrice": 52.08,
                        "priceListId": "Edge",
                        "contractTerm": 99,
                        "contractDetail": "/mo.",
                        "originalPrice": 52.08,
                        "edgePrice": true,
                        "contractName": "24 Monthly Payments",
                        "discountedPrice": 52.08,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": 1249.99,
                        "contractTitle": "Monthly Device Payment",
                        "loanTerm": "24",
                        "edgeContractText": "$0 Down (for qualified customers) $52.08/mo for 24 months; 0% APR Retail Price: $1249.99",
                        "promoBadgeMessages": null
                      },
                      {
                        "displayOriginalPrice": "1249.99",
                        "displayDiscountedPrice": "1249.99",
                        "displayEdgeFullRetailPrice": null,
                        "listPrice": 1249.99,
                        "discountPrice": 1249.99,
                        "priceListId": "FullRetail",
                        "contractTerm": 0,
                        "contractDetail": null,
                        "originalPrice": 1249.99,
                        "edgePrice": false,
                        "contractName": "Retail Price",
                        "discountedPrice": 1249.99,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": null,
                        "contractTitle": "No Early Termination Fee",
                        "loanTerm": null,
                        "edgeContractText": null,
                        "promoBadgeMessages": null
                      }
                    ]
                  },
                  {
                    "intCapacity": 512,
                    "deviceSkuId": "sku3180125",
                    "deviceSorId": "MT6P2LL/A",
                    "displayName": "Apple&reg; iPhone&reg; Xs Max 512GB in Gold",
                    "capacity": "512GB",
                    "colorCode": "#CFBEA9",
                    "colorName": "Gold",
                    "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphonexs-max-gold?$device-lg$",
                    "inventoryStatus": "1001",
                    "instorePickupFlag": true,
                    "devicePrice": [
                      {
                        "displayOriginalPrice": "60.41",
                        "displayDiscountedPrice": "60.41",
                        "displayEdgeFullRetailPrice": "1449.99",
                        "listPrice": 60.41,
                        "discountPrice": 60.41,
                        "priceListId": "Edge",
                        "contractTerm": 99,
                        "contractDetail": "/mo.",
                        "originalPrice": 60.41,
                        "edgePrice": true,
                        "contractName": "24 Monthly Payments",
                        "discountedPrice": 60.41,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": 1449.99,
                        "contractTitle": "Monthly Device Payment",
                        "loanTerm": "24",
                        "edgeContractText": "$0 Down (for qualified customers) $60.41/mo for 24 months; 0% APR Retail Price: $1449.99",
                        "promoBadgeMessages": null
                      },
                      {
                        "displayOriginalPrice": "1449.99",
                        "displayDiscountedPrice": "1449.99",
                        "displayEdgeFullRetailPrice": null,
                        "listPrice": 1449.99,
                        "discountPrice": 1449.99,
                        "priceListId": "FullRetail",
                        "contractTerm": 0,
                        "contractDetail": null,
                        "originalPrice": 1449.99,
                        "edgePrice": false,
                        "contractName": "Retail Price",
                        "discountedPrice": 1449.99,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": null,
                        "contractTitle": "No Early Termination Fee",
                        "loanTerm": null,
                        "edgeContractText": null,
                        "promoBadgeMessages": null
                      }
                    ]
                  }
                ]
              }
            }
          },
          "deviceSkuId": "sku3180118",
          "promoOfferText": null,
          "promoApplied": false,
          "commerceItemId": "S7b47622d913cf62870b4d8ff1b101ec9_device_1",
          "loanTerm": 24,
          "sbdHeaderMsg": null,
          "percentage": null,
          "waivedActivationFeePromo": false,
          "flow": "EUP",
          "protectionIneligible": false,
          "modDevice": false,
          "dueMonthlyTotalDuration": null,
          "edgeDevice": true,
          "eupdevice": false,
          "accessory": false,
          "amountAfterInstantCredit": "0.00",
          "disountedInstantCreditAmt": "0.00",
          "instantCreditAmount": "0.00"
        }
      ],
      "buddyUpgrade": false
    },
    "accessories": null,
    "selectedShippingType": {
      "type": "SHIPPING",
      "shippingTypeName": "FREE 2 Day by 8pm",
      "price": 0.0,
      "discountPrice": 0.0,
      "estimatedDeliveryDate": null,
      "selectedFormattedWindow": null,
      "estimatedDeliveryDateText": "Tue 9/4",
     "description": "Estimated to arrive on Tue, Sep 4 if ordered by 4pm today. Signature required."
    },
    "balanceCreditCardAmount": null,
    "cpcOrder": false,
    "totalDueMonthlyPlanAndDevice": "110.83",
    "deviceConfigInfo": {
      "devices": [
        {
          "deviceId": "S7b47622d913cf62870b4d8ff1b101ec9_device_1",
          "deviceName": "iPhone&reg; XS Max",
          "deviceSetupMode": null,
          "mtnNumber": "7703019294",
          "flow": "EUP",
          "serviceAddress": {
            "firstName": "KENNY",
            "lastName": "REYES",
            "address1": "101 MURPHY INDUSTRIAL BLVD",
            "address2": "",
            "city": "Bremen",
            "state": "GA",
            "zipCode": "30110",
            "emailAddress": "VZW@VZW.COM",
            "phoneNumber": "7705875888"
          },
          "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphonexs-max-silver?$device-med$&fmt=jpeg&wid=75&hei=150",
          "mobileAppImageName": null,
          "npaNxxnumber": null,
          "npnxxCustomerSelection": null,
          "npaNxxdetails": null,
          "manufactureName": "Apple",
          "color": "Silver",
          "size": "64GB",
          "numberShareDevice": false,
          "numberSharedMtn": null,
          "deviceNickName": null,
          "numberSharedDeviceName": null,
          "displayImeiId": null,
          "modDevice": false,
          "dueMonthlyTotalDuration": null,
          "portInDetails": null
        }
      ],
      "npaNxxdetails": {
        "zipCode": null,
        "state": null,
        "city": null,
        "success": false,
        "mtns": null,
        "states": null,
        "cities": null
      },
      "deviceAddressUpdated": false,
      "accessories": null
    },
    "checkoutStates": {
      "shippingAddressRequired": false,
      "shippingAddressChangeRequired": false,
      "shippingNameChangeRequired": false,
      "poBoxShippingAddress": false,
      "shippingAddressValidationError": false,
      "shippingMethodRequired": false,
      "paymentRequired": false,
      "pastDuePaymentRequired": false,
      "showPaymentSection": true,
      "showShippingAddress": true,
      "showDeliveryMethod": true,
      "newCard": false,
      "cvvNeeded": false,
      "contactInfoRequired": false,
      "instantCreditAllocationsChanged": false,
      "instantCreditOrder": false,
      "tradesExceedItems": false,
      "creditCardZipEditable": false,
      "vzProtect": true,
      "vzProtectMultiDevice": true,
      "batteryShippingNotAllowedStates": false,
      "disableSubmitOrderForOPALUser": false
    },
    "totalEdgeItemDownPaymentAmount": "0.00",
    "totalEdgeUpAmount": "0.00",
    "totalEdgeUpBuyOutAmount": "0.00",
    "creditApplicationNumber": "484000094",
    "locationCode": "0862001",
    "selectedVendorShippingType": null,
    "standaloneAccessories": false,
    "accountLevelDiscountList": null,
    "militaryDiscInfoText": null,
    "militaryInfoURL": null,
    "recAccessoriesEnabled": true,
    "accessoryGWURL": "/od/cust/auth/accessories/",
    "instantCreditDetails": {
      "totalInstantCredit": null,
      "optionalDownPayment": null,
      "twoYearDevicesInstantCredit": null,
      "fullRetailInstantCredit": null,
      "accessoriesInsantCredit": null,
      "taxesInstantCredit": null,
      "accountCredit": null
    },
    "bicRepresentationChangeEnabled": true,
    "appleMusicEnrollUrl": "https://myvpostpay.verizonwireless.com/ui/acct/secure/appmusic",
    "firstRespondersInfoURL": null,
    "multiOrderDetails": null,
    "numberShareRequiredDevice": false,
    "splitShipment": false,
    "isHLLPlanInOrder": false,
    "totalUpgradeFee": "0.00",
    "totalOrderTax": "0.00",
    "totalSurcharges": "0.00",
    "totalOrderTaxTooltip": "Tax is based on the sales price of your device(s)."
  }
};

export default json;