window.confirmationJSON = {
	"output": {
		"title": "You're all set.",
		"subtitle": null,
		"orderId": "986066977215347",
		"estimatedDelivery": "",
		"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/1.3_MV_BuyandUpgrade_ConfirmationPage_Interstital?$device-med$",
		"tradeInStatus": false,
		"confirmationMessage": "Thanks for ordering from verizonwireless.com. Your order receipt is sent to BOUNCETEST@VERIZON.COM.",
		"doneButtonText": "Got it",
		"doneButtonLink": "/od/cust/auth/shoplanding/",
		"userNote": "TODO",
		"notNowButtonText": "TODO",
		"notNowButtonLink": "TODO",
		"learnHowButtonText": null,
		"learnHowButtonLink": "/od/cust/auth/learnHow",
		"numberOfDevice": 1,
		"confirmationNumberText": "Confirmation Number",
		"iconicFlow": true,
		"protectionURL": null,
		"accessoriesURL": null,
		"tapFlag": false,
		"cjmTagUrl": null,
		"pepperJamTagUrl": null,
		"selectedPaymentMode": null,
		"confirmationEmail": "BOUNCETEST@VERIZON.COM",
		"plans": {
			"dueMonthly": null,
			"dueToday": null,
			"planOnlyDueMonthly": null,
			"items": [{
				"planType": null,
				"lineAccessCharges": null,
				"accountAccess": null,
				"accountLevelFeatures": null,
				"totalMonthlyPlanCost": null,
				"spoBadgeMessage": null,
				"planDisplayName": "TEST PLAN 2G SMARTPHONE",
				"planImageURL": "//ss7.vzw.com/is/image/VerizonWireless/U_083s_022317",
				"planLetter": null,
				"planDescrption": null,
				"planDescription": null,
				"quantity": 0,
				"skuId": "sku3160033",
				"productId": "plan5600003",
				"itemAmount": "0.00",
				"itemAmountOriginal": "55.00",
				"dueMonthly": "55.00",
				"dueMonthlyOriginal": "55.00",
				"itemDiscount": null,
				"displayName": null,
				"skuDisplayName": null,
				"listPrice": "55.00",
				"rawTotalAmount": "0.00",
				"planGroupCode": null,
				"autoPayEnabled": false,
				"numberSharePlan": false,
				"planCommerceItemId": "Sdf02c6920f2289b63306ff28169f40f0{ss3}_plan_1",
				"autoPayPrice": "5.00",
				"autoPayText": "Save an additional $5.00/mo per line on our unlimited plans by signing up for paper-free billing and Auto Pay.",
				"termsAndConditionKey": null,
				"unitOfMeasure": "GB",
				"planSize": "9999"
			}],
			"upgradeDevices": null,
			"newDevices": null,
			"existingDevices": [

			],
			"dueMonthlyPlanWithLAC": null,
			"discountedDueMonthlyPlanWithLAC": null,
			"hasEcpdDiscount": false,
			"totalLineAccessCharges": null
		},
		"tradeInDevicesDetails": null,
		"tradeInPromoDetails": null,
		"transformedTradeInPromoDetails": null,
		"subOrders": null,
		"comboOrder": false,
		"totalDueToday": "0.00",
		"totalDueMonthly": "31.74",
		"subTotalDueToday": "0.00",
		"securityDepositAmount": "0.00",
		"stateSalesTax": "0.00",
		"employeeDiscount": "0.00",
		"pastDueExist": false,
		"pastDueAmountPaid": false,
		"pastDueAmount": "0.00",
		"shippingInfo": {
			"shippingInfoUpdated": false,
			"sameAsBilling": true,
			"ispuEligibleFlag": true,
			"addressInfo": {
				"firstName": "RAVI",
				"lastName": "HENDERSON",
				"companyName": null,
				"address1": "11545 NO FRANK LOYD WRIGHT BLV",
				"address2": null,
				"city": "Scottsdale",
				"state": "AZ",
				"zipcode": "85259",
				"businessName": null,
				"postalCode": null,
				"email": "BOUNCETEST@VERIZON.COM",
				"phoneNumber": "9605809929"
			},
			"contactInfo": {
				"emailAddress": "BOUNCETEST@VERIZON.COM",
				"phoneNumber": "9605809929",
				"firstName": "RAVI",
				"lastName": "HENDERSON",
				"smsMdn": null,
				"activeSMSCapableMtnList": [
					"4802016197",
					"4802685140",
					"4802685913",
					"5207304414"
				]
			},
			"shippingTypesInfo": null,
			"storeDetail": {
				"storeHeader": null,
				"storeName": null,
				"storeAddress": null,
				"deviceAvailable": false,
				"distance": null,
				"appendedStoreTiming": null,
				"longitude": null,
				"storeId": null,
				"netaceLocationCode": null,
				"latitude": null,
				"seoUrlName": null,
				"storeClosingTime": null
			},
			"tradeIn": false,
			"tradeInAddress": null,
			"nonSddEligibleMsg": null,
			"selectedSDDWindow": null,
			"poboMessage": null,
			"ispudetailsInfo": {
				"storeAddress": null,
				"storeHours": null,
				"storeId": null,
				"storeName": null,
				"phoneNumber": null,
				"distance": null,
				"totalItems": 0,
				"availItems": 0,
				"latitdude": 0.0,
				"longtitude": 0.0,
				"availItemName": null
			}
		},
		"billingInfo": {
			"billToAccountEligible": false,
			"creditCardZipEditable": false,
			"billingAddress": {
				"firstName": "RAVI",
				"lastName": "HENDERSON",
				"businessName": null,
				"zipcode": "85259",
				"state": "AZ",
				"address2": null,
				"address1": "11545 NO FRANK LOYD WRIGHT BLV",
				"companyName": null,
				"city": "Scottsdale",
				"sameAsShipping": false
			},
			"masterpass3DSecure": null,
			"billToAccountNumber": null,
			"creditCardInfo": {
				"savedCardNickName": null,
				"preselectCard": null,
				"creditCardNumber": "XXXX XXXX XXXX-1111",
				"creditCardExpMonth": "02",
				"creditCardExpYear": "2020",
				"billingZipCode": null,
				"creditCardType": "visa",
				"creditCardVerificationNumber": null,
				"creditCardBIN": null,
				"cvvRequired": false
			},
			"selectedPaymentMode": "newCard",
			"giftCardList": [

			],
			"savedCardInfo": null,
			"applePayResponseInfo": null,
			"masterpassResponseInfo": {
				"emailAddress": null,
				"cardType": null,
				"lastDigits": null,
				"creditCardBIN": null,
				"masterpassSelected": false
			},
			"masterpassError": false,
			"masterpassErrorMessage": null,
			"paypalEmailAddress": null,
			"expirationMonths": null,
			"expirationYears": null
		},
		"devices": {
			"dueMonthly": 31.74,
			"totalActivationFee": 0.0,
			"deviceTotalDueMonthly": 18.74,
			"dueToday": 0.0,
			"accessories": [

			],
			"accessoriesBundle": [

			],
			"globalPromotions": [{
				"badgeText": "Music lovers, this one's for you. Get 45 million songs free for 6 months with Unlimited. Then $9.99/mo after. Cancel anytime. Learn more.",
				"badgeToolTip": "http://vzwqa2.verizonwireless.com/apple-music/",
				"badgeImage": "",
				"placement": "HEADERMSG",
				"pageId": "ORDER-CONFIMATION",
				"promoType": "PLAN_OFFER"
			}],
			"items": [{
				"deviceName": "iPhone&reg; 6s",
				"dueMonthly": "18.74",
				"dueToday": "0.00",
				"upgradeFee": "0.00",
				"originalUpgradeFee": "0.00",
				"activationFee": "30.00",
				"dueTodayOriginal": "0.00",
				"dueMonthlyOriginal": null,
				"dueTodayDiscounted": false,
				"dueMonthlyDiscounted": false,
				"mtn": null,
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone6s-spgry-front?$device-med$&fmt=jpeg&wid=75&hei=150",
				"protectionFeature": {
					"name": "Total Mobile Protection",
					"mtn": null,
					"price": "13.00",
					"discountPrice": "0.00",
					"retailPrice": "0.00",
					"hasEcpdDiscount": false,
					"promoMessage": null,
					"originalPrice": "0.00",
					"wasPrice": "0.00",
					"deviceName": null,
					"color": null,
					"size": null,
					"introText": null,
					"smartFamily": false,
					"freeTrial": false,
					"tapfeature": false,
					"disountedInstantCreditAmt": "0.00",
					"instantCreditAmount": "0.00",
					"amountAfterInstantCredit": "0.00"
				},
				"optionalFeatures": [

				],
				"installmentBalance": "449.99",
				"edgeRetailPrice": "449.99",
				"edgeItemDownPaymentAmount": "0.00",
				"mailInRebateAmount": "0.00",
				"transferredFromMtn": null,
				"devicePromotionList": [

				],
				"bicOfferApplied": false,
				"bicContractPrice": "0.00",
				"bicDiscountedContractPrice": "-1.00",
				"bicAdditionalContractText": null,
				"bicMessageMap": null,
				"edgeUpAmount": 0.0,
				"displayDeviceDueMonthly": 31.74,
				"deviceLACFee": "0.00",
				"manufactureName": "Apple",
				"color": "Space Gray",
				"colorCode": "#807F84",
				"size": "32GB",
				"displayName": "iPhone&reg; 6s",
				"contractTerm": "99",
				"edgeUpBuyOutAmount": 0.0,
				"fullRetailPrice": "449.99",
				"alwaysEligibleForUpgrade": false,
				"numberShareDevice": false,
				"activationFeeText": "One-time activation fee of $30.00 charged to your next monthly bill.",
				"numberSharedMtn": null,
				"promoContentText": null,
				"itemOnJaxPlan": false,
				"humCarDetails": null,
				"simDetails": null,
				"imeiId": null,
				"displayImeiId": null,
				"poboDateLabel": null,
				"nickName": "480-772-XXXX",
				"planCommerceItemId": "Sdf02c6920f2289b63306ff28169f40f0{ss3}_plan_1",
				"displayMtn": null,
				"promoOfferText": null,
				"promoApplied": false,
				"commerceItemId": "Sdf02c6920f2289b63306ff28169f40f0{ss3}_device_1",
				"loanTerm": 24,
				"sbdHeaderMsg": null,
				"percentage": null,
				"waivedActivationFeePromo": false,
				"flow": "AAL",
				"protectionIneligible": false,
				"disountedInstantCreditAmt": "0.00",
				"accessory": false,
				"edgeDevice": true,
				"eupdevice": false,
				"instantCreditAmount": "0.00",
				"amountAfterInstantCredit": "0.00"
			}],
			"buddyUpgrade": false
		},
		"accessories": null,
		"selectedShippingType": {
			"type": "SHIPPING",
			"shippingTypeName": "FREE 2 Day by 8pm",
			"price": 0.0,
			"discountPrice": 0.0,
			"estimatedDeliveryDate": "2018-06-25 00:00:00"
		},
		"balanceCreditCardAmount": "0.00",
		"cpcOrder": true,
		"totalDueMonthlyPlanAndDevice": "86.74",
		"deviceConfigInfo": {
			"devices": [{
				"deviceId": "Sdf02c6920f2289b63306ff28169f40f0{ss3}_device_1",
				"deviceName": "iPhone&reg; 6s",
				"deviceSetupMode": null,
				"mtnNumber": null,
				"flow": "AAL",
				"serviceAddress": {
					"firstName": "RAVI",
					"lastName": "HENDERSON",
					"address1": "11545 NO FRANK LOYD WRIGHT BLV",
					"address2": "",
					"city": "Scottsdale",
					"state": "AZ",
					"zipCode": "85259",
					"emailAddress": "BOUNCETEST@VERIZON.COM",
					"phoneNumber": "9605809929"
				},
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone6s-spgry-front?$device-med$&fmt=jpeg&wid=75&hei=150",
				"mobileAppImageName": null,
				"npaNxxnumber": "480-772-XXXX",
				"npnxxCustomerSelection": null,
				"npaNxxdetails": null,
				"manufactureName": "Apple",
				"color": "Space Gray",
				"size": "32GB",
				"numberShareDevice": false,
				"numberSharedMtn": null,
				"deviceNickName": null,
				"numberSharedDeviceName": null,
				"displayImeiId": null,
				"portInDetails": null
			}],
			"npaNxxdetails": {
				"zipCode": null,
				"state": null,
				"city": null,
				"success": false,
				"mtns": null,
				"states": null,
				"cities": null
			},
			"deviceAddressUpdated": false,
			"accessories": null
		},
		"checkoutStates": {
			"shippingAddressRequired": false,
			"shippingAddressChangeRequired": false,
			"poBoxShippingAddress": false,
			"shippingAddressValidationError": false,
			"shippingMethodRequired": false,
			"paymentRequired": false,
			"pastDuePaymentRequired": false,
			"showPaymentSection": true,
			"showShippingAddress": true,
			"showDeliveryMethod": true,
			"newCard": false,
			"cvvNeeded": false,
			"contactInfoRequired": false
		},
		"totalEdgeItemDownPaymentAmount": "0.00",
		"totalEdgeUpAmount": "0.00",
		"totalEdgeUpBuyOutAmount": "0.00",
		"standaloneAccessories": false,
		"accountLevelDiscountList": null,
		"militaryDiscInfoText": "Learn about our special discounts for military families.",
		"militaryInfoURL": "https://www.verizonwireless.com/military/",
		"recAccessoriesEnabled": false,
		"accessoryGWURL": "/od/cust/auth/accessories/",
		"multiOrderDetails": null,
		"hasRio": false,
		"splitShipment": false,
		"isHLLPlanInOrder": true
	}
}