window.confirmationJSON = {
	"output": {
		"title": "You're all set.",
		"subtitle": null,
		"orderId": "924042361501589",
		"estimatedDelivery": "",
		"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/1.3_MV_BuyandUpgrade_ConfirmationPage_Interstital?$device-med$",
		"tradeInStatus": false,
		"confirmationMessage": "Thanks for ordering from verizonwireless.com. Your order receipt is sent to WINOTLVYVO@VZW.COM.",
		"doneButtonText": "Got it",
		"doneButtonLink": "/od/cust/auth/shoplanding/",
		"userNote": "TODO",
		"notNowButtonText": "TODO",
		"notNowButtonLink": "TODO",
		"learnHowButtonText": null,
		"learnHowButtonLink": "/od/cust/auth/learnHow",
		"numberOfDevice": 1,
		"confirmationNumberText": "Confirmation Number",
		"iconicFlow": true,
		"protectionURL": null,
		"accessoriesURL": null,
		"tapFlag": false,
		"cjmTagUrl": null,
		"pepperJamTagUrl": null,
		"selectedPaymentMode": null,
		"confirmationEmail": "WINOTLVYVO@VZW.COM",
		"plans": {
			"dueMonthly": "170.00",
			"dueToday": "0.00",
			"planOnlyDueMonthly": "170.00",
			"items": [{
				"planType": "Beyond Unlimited",
				"lineAccessCharges": [{
					"name": "Apple iPhone&reg; 7 Plus 32GB in Black",
					"mtn": "5125579423",
					"price": "85.00",
					"discountPrice": "0.00",
					"retailPrice": "0.00",
					"hasEcpdDiscount": false,
					"promoMessage": null,
					"originalPrice": "85.00",
					"wasPrice": "85.00",
					"deviceName": "iPhone&reg; 7 Plus",
					"color": "Black",
					"size": "32GB",
					"instantCreditAmount": "0.00",
					"amountAfterInstantCredit": "0.00",
					"disountedInstantCreditAmt": "0.00"
				}],
				"accountAccess": {
					"name": "Beyond Unlimited",
					"mtn": null,
					"price": "170.00",
					"discountPrice": "0.00",
					"retailPrice": "0.00",
					"hasEcpdDiscount": false,
					"promoMessage": null,
					"originalPrice": "0.00",
					"wasPrice": "0.00",
					"deviceName": null,
					"color": null,
					"size": null,
					"instantCreditAmount": "0.00",
					"amountAfterInstantCredit": "0.00",
					"disountedInstantCreditAmt": "0.00"
				},
				"accountLevelFeatures": null,
				"totalMonthlyPlanCost": "170.00",
				"spoBadgeMessage": null,
				"planDisplayName": "Beyond Unlimited",
				"planImageURL": "//ss7.vzw.com/is/image/VerizonWireless/BeyondUnlimited_Logo_Carousel",
				"planLetter": null,
				"planDescrption": "<span>Shared unlimited talk, </span><span>text &amp;  unlimited data </span>",
				"planDescription": "<span>Shared unlimited talk, </span><span>text &amp;  unlimited data </span>"
			}],
			"upgradeDevices": [{
				"name": "iPhone&reg; 7 Plus",
				"price": "85.00",
				"discountPrice": 0.0,
				"hasEcpdDiscount": false,
				"mtn": "5125579423",
				"listPrice": 85.0,
				"deviceLineItemId": null,
				"discountPriceVal": "0.00"
			}],
			"newDevices": [],
			"existingDevices": [{
				"name": "LG Octane&trade;",
				"price": "85.00",
				"discountPrice": 0.0,
				"hasEcpdDiscount": false,
				"mtn": "2108340918",
				"listPrice": 85.0,
				"deviceLineItemId": null,
				"discountPriceVal": "0.00"
			}],
			"dueMonthlyPlanWithLAC": "170.00",
			"discountedDueMonthlyPlanWithLAC": "0.00",
			"hasEcpdDiscount": false,
			"totalLineAccessCharges": "85.00"
		},
		"featureList": [{
			"id": "Sd4f970a4b3cbf35510542304413a00fa{ss100}_feature_1",
			"quantity": 1,
			"type": "INSUR,D",
			"skuId": "sku401064",
			"productId": "sfo80072",
			"sorId": "66332",
			"itemAmount": 0.0,
			"itemAmountOriginal": 0.0,
			"dueMonthly": 0.0,
			"dueMonthlyOriginal": null,
			"itemDiscount": 0.0,
			"displayName": "Decline Equipment Protection",
			"skuDisplayName": null,
			"listPrice": 0.0,
			"rawTotalAmount": 0.0,
			"pricingDetails": [{
				"pricingAdjustmentId": null,
				"itemId": "Sd4f970a4b3cbf35510542304413a00fa{ss100}_feature_1",
				"orderId": "Sd4f970a4b3cbf35510542304413a00fa{ss100}",
				"offerId": null,
				"offerAmount": 0.0,
				"description": "List Price description",
				"offerType": null,
				"priceListId": null,
				"listPrice": 0.0,
				"offerName": null,
				"creationDate": 1525938958199,
				"lastModifiedDate": 1525938958199,
				"version": 1
			}],
			"orderId": "Sd4f970a4b3cbf35510542304413a00fa{ss100}",
			"version": 1,
			"delete": false,
			"inventoryLevel": 0,
			"taxDetails": null,
			"itemTaxes": 0.0,
			"deviceLineItemId": "Sd4f970a4b3cbf35510542304413a00fa{ss100}_device_1",
			"featureCharge": 0.0,
			"featureType": "INS",
			"lastModifiedDate": 1525938933238
		}, {
			"id": "Sd4f970a4b3cbf35510542304413a00fa{ss100}_feature_2",
			"quantity": 0,
			"type": null,
			"skuId": "sku2560179",
			"productId": "sfo80079",
			"sorId": "85433",
			"itemAmount": 0.0,
			"itemAmountOriginal": 0.0,
			"dueMonthly": 85.0,
			"dueMonthlyOriginal": null,
			"itemDiscount": 0.0,
			"displayName": "Phone Plan",
			"skuDisplayName": null,
			"listPrice": 85.0,
			"rawTotalAmount": 0.0,
			"pricingDetails": [{
				"pricingAdjustmentId": null,
				"itemId": "Sd4f970a4b3cbf35510542304413a00fa{ss100}_feature_2",
				"orderId": null,
				"offerId": null,
				"offerAmount": 0.0,
				"description": "List Price description",
				"offerType": null,
				"priceListId": null,
				"listPrice": 85.0,
				"offerName": null,
				"creationDate": 1525938958199,
				"lastModifiedDate": 1525938958199,
				"version": 1
			}],
			"orderId": null,
			"version": 0,
			"delete": false,
			"inventoryLevel": 0,
			"taxDetails": null,
			"itemTaxes": 0.0,
			"deviceLineItemId": "Sd4f970a4b3cbf35510542304413a00fa{ss100}_device_1",
			"featureCharge": 0.0,
			"featureType": "LAC",
			"lastModifiedDate": null
		}],
		"accessoryList": [{
			"id": "Sd4f970a4b3cbf35510542304413a00fa{ss100}_accessory_1",
			"quantity": 1,
			"type": null,
			"skuId": "sku1760050",
			"productId": "acc5240003",
			"sorId": "S5556LL/A",
			"itemAmount": 129.97,
			"itemAmountOriginal": 0.0,
			"dueMonthly": 0.0,
			"dueMonthlyOriginal": null,
			"itemDiscount": 0.0,
			"displayName": "AppleCare+ for iPhone 8, 7, 6s, or 6",
			"skuDisplayName": "AppleCare+ for iPhone 8, 7, 6s, or 6",
			"listPrice": 129.97,
			"rawTotalAmount": 129.97,
			"pricingDetails": [{
				"pricingAdjustmentId": null,
				"itemId": "Sd4f970a4b3cbf35510542304413a00fa{ss100}_accessory_1",
				"orderId": "Sd4f970a4b3cbf35510542304413a00fa{ss100}",
				"offerId": null,
				"offerAmount": 0.0,
				"description": "List Price description",
				"offerType": null,
				"priceListId": null,
				"listPrice": 129.97,
				"offerName": null,
				"creationDate": 1525938958199,
				"lastModifiedDate": 1525938958199,
				"version": 1
			}],
			"orderId": "Sd4f970a4b3cbf35510542304413a00fa{ss100}",
			"version": 1,
			"delete": false,
			"inventoryLevel": 1000,
			"taxDetails": null,
			"itemTaxes": 0.0,
			"deviceLineItemId": "Sd4f970a4b3cbf35510542304413a00fa{ss100}_device_1",
			"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/applecareplus-cc3000?$acc-med$",
			"bogoType": null,
			"recycleStateInd": null,
			"color": null,
			"size": null,
			"capacity": null,
			"lastModifiedDate": 1525938933340,
			"deviceManufacturerName": "Apple",
			"accessoryType": "INLINE_ACCESSORIES",
			"ispuEligibleFlag": true,
			"bundleSkuLineItems": null,
			"bundleDesciption": null,
			"vzwSbdOfferlist": [],
			"promotions": null,
			"purchasePath": "EUP",
			"appleCare": true,
			"expectedShippingDate": null,
			"shipCommitInd": null,
			"sameDayDelivery": false,
			"recycleCreditAllocatedAmount": 0.0,
			"ecpdItemAmount": null,
			"ecpdItemDiscount": 0.0,
			"standaloneaccessory": false,
			"batteryAccessory": false,
			"accSeoUrl": ""
		}, {
			"id": "Sd4f970a4b3cbf35510542304413a00fa{ss100}_accessory_2",
			"quantity": 1,
			"type": null,
			"skuId": "sku2120065",
			"productId": "acc6640065",
			"sorId": "I7LLGC-F00",
			"itemAmount": 39.99,
			"itemAmountOriginal": 0.0,
			"dueMonthly": 0.0,
			"dueMonthlyOriginal": null,
			"itemDiscount": 0.0,
			"displayName": "InvisibleShield Glass+ Screen Protector for iPhone 8 Plus/7 Plus/6s Plus/6 Plus",
			"skuDisplayName": "InvisibleShield Glass+ Screen Protector for iPhone 8 Plus/7 Plus/6s Plus/6 Plus",
			"listPrice": 39.99,
			"rawTotalAmount": 39.99,
			"pricingDetails": [{
				"pricingAdjustmentId": null,
				"itemId": "Sd4f970a4b3cbf35510542304413a00fa{ss100}_accessory_2",
				"orderId": "Sd4f970a4b3cbf35510542304413a00fa{ss100}",
				"offerId": null,
				"offerAmount": 0.0,
				"description": "List Price description",
				"offerType": null,
				"priceListId": null,
				"listPrice": 39.99,
				"offerName": null,
				"creationDate": 1525938958199,
				"lastModifiedDate": 1525938958199,
				"version": 1
			}],
			"orderId": "Sd4f970a4b3cbf35510542304413a00fa{ss100}",
			"version": 1,
			"delete": false,
			"inventoryLevel": 1000,
			"taxDetails": null,
			"itemTaxes": 0.0,
			"deviceLineItemId": "Sd4f970a4b3cbf35510542304413a00fa{ss100}_device_1",
			"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/zagg-invisibleshield-glass-iphone-6-plus-iset-ippglc-f00?$acc-med$",
			"bogoType": null,
			"recycleStateInd": null,
			"color": null,
			"size": null,
			"capacity": null,
			"lastModifiedDate": 1525938955894,
			"deviceManufacturerName": "ZAGG",
			"accessoryType": "INLINE_ACCESSORIES",
			"ispuEligibleFlag": true,
			"bundleSkuLineItems": null,
			"bundleDesciption": null,
			"vzwSbdOfferlist": [],
			"promotions": null,
			"purchasePath": "EUP",
			"appleCare": false,
			"expectedShippingDate": null,
			"shipCommitInd": null,
			"sameDayDelivery": false,
			"recycleCreditAllocatedAmount": 0.0,
			"ecpdItemAmount": null,
			"ecpdItemDiscount": 0.0,
			"standaloneaccessory": false,
			"batteryAccessory": false,
			"accSeoUrl": ""
		}],
		"paymentGroup": null,
		"contactInfo": {
			"id": null,
			"emailAddress": "WINOTLVYVO@VZW.COM",
			"phoneNumber": "5207420265",
			"lastName": "MANNING",
			"firstName": "RAVI",
			"zipCode": "75088",
			"orderId": null,
			"userId": null,
			"npaNxxNumber": null,
			"address1": "8701 LAKEVIEW PKWY STE 111-144",
			"address2": null,
			"city": "Rowlett",
			"state": "TX",
			"addressVerified": true,
			"textAlertOptin": false,
			"newsLetterOptin": false,
			"paperFreeBillingIndicatorFlag": false,
			"middleName": null,
			"firmName": null,
			"businessName": null,
			"apartmentNum": "111-1",
			"addressDirection": "",
			"poBox": "",
			"streetNumber": "8701",
			"streetName": "LAKEVIEW",
			"streetType": "PKWY",
			"ruralRoute": null,
			"ruralDel": "",
			"zipCode4": null,
			"zipCode5": null,
			"faxNumber": null,
			"addressType": null,
			"country": "",
			"prefix": null,
			"suffix": null,
			"postbox": null,
			"companyname": null,
			"ruralrte": "",
			"county": null,
			"address3": null,
			"postalcode": "75088",
			"version": 0,
			"lastModifiedDate": null,
			"addressConfirmationStatus": null
		},
		"tradeInDevicesDetails": null,
		"tradeInPromoDetails": null,
		"transformedTradeInPromoDetails": null,
		"subOrders": null,
		"comboOrder": false,
		"totalDueToday": "169.96",
		"totalDueMonthly": "15.41",
		"subTotalDueToday": "169.96",
		"securityDepositAmount": "0.00",
		"stateSalesTax": "0.00",
		"employeeDiscount": "0.00",
		"pastDueExist": false,
		"pastDueAmountPaid": false,
		"pastDueAmount": "0.00",
		"shippingInfo": {
			"shippingInfoUpdated": false,
			"sameAsBilling": true,
			"ispuEligibleFlag": true,
			"addressInfo": {
				"firstName": "RAVI",
				"lastName": "MANNING",
				"companyName": null,
				"address1": "8701 LAKEVIEW PKWY STE 111-144",
				"address2": null,
				"city": "Rowlett",
				"state": "TX",
				"zipcode": "75088",
				"businessName": null,
				"postalCode": null,
				"email": "WINOTLVYVO@VZW.COM",
				"phoneNumber": "5207420265"
			},
			"contactInfo": {
				"emailAddress": "WINOTLVYVO@VZW.COM",
				"phoneNumber": "5207420265",
				"firstName": "RAVI",
				"lastName": "MANNING",
				"smsMdn": null,
				"activeSMSCapableMtnList": ["5125579423"]
			},
			"shippingTypesInfo": [{
				"estimatedDeliveryDate": "2018-05-14 00:00:00",
				"estimatedDeliveryDateText": "Mon 5/14",
				"shippingDescription": "Free 2 Day by 8pm",
				"shippingOptionId": "SHP002",
				"shippingCost": "0.00",
				"shortDescription": "Free 2 Day by 8pm",
				"active": true,
				"addedShippingOptionId": true,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Mon, May 14 if ordered by 4pm today. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}, {
				"estimatedDeliveryDate": "2018-05-11 00:00:00",
				"estimatedDeliveryDateText": "Fri 5/11",
				"shippingDescription": "Next Day by 8pm",
				"shippingOptionId": "SHP004",
				"shippingCost": "12.99",
				"shortDescription": "Next Day by 8pm",
				"active": true,
				"addedShippingOptionId": false,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Fri, May 11. Next Day by 8pm. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}, {
				"estimatedDeliveryDate": "2018-05-11 10:30:00",
				"estimatedDeliveryDateText": "Fri 5/11 by 10:30AM",
				"shippingDescription": "Next Day by 10:30am",
				"shippingOptionId": "SHP005",
				"shippingCost": "14.99",
				"shortDescription": "Next Day by 10:30am",
				"active": true,
				"addedShippingOptionId": false,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Fri, May 11. Next Day by 10:30am. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}],
			"storeDetail": {
				"storeHeader": null,
				"storeName": null,
				"storeAddress": null,
				"deviceAvailable": false,
				"distance": null,
				"appendedStoreTiming": null,
				"longitude": null,
				"storeId": null,
				"netaceLocationCode": null,
				"latitude": null,
				"seoUrlName": null,
				"storeClosingTime": null
			},
			"tradeIn": false,
			"tradeInAddress": null,
			"nonSddEligibleMsg": null,
			"selectedSDDWindow": null,
			"poboMessage": null,
			"ispudetailsInfo": {
				"storeAddress": null,
				"storeHours": null,
				"storeId": null,
				"storeName": null,
				"phoneNumber": null,
				"distance": null,
				"totalItems": 0,
				"availItems": 0,
				"latitdude": 0.0,
				"longtitude": 0.0,
				"availItemName": null
			}
		},
		"billingInfo": {
			"billToAccountEligible": true,
			"creditCardZipEditable": false,
			"billingAddress": {
				"firstName": "RAVI",
				"lastName": "MANNING",
				"businessName": null,
				"zipcode": "75088",
				"state": "TX",
				"address2": null,
				"address1": "8701 LAKEVIEW PKWY STE 111-144",
				"companyName": null,
				"city": "Rowlett"
			},
			"masterpass3DSecure": null,
			"billToAccountNumber": "#XXXXXXX-0001",
			"creditCardInfo": {
				"savedCardNickName": null,
				"preselectCard": null,
				"creditCardNumber": null,
				"creditCardExpMonth": null,
				"creditCardExpYear": null,
				"billingZipCode": null,
				"creditCardType": null,
				"creditCardVerificationNumber": null,
				"creditCardBIN": null,
				"cvvRequired": false
			},
			"selectedPaymentMode": "BTA",
			"giftCardList": [],
			"savedCardInfo": [{
				"savedCardNickName": "BOGUS",
				"preselectCard": null,
				"creditCardNumber": "XXXX-XXXX-XXXX-9844",
				"creditCardExpMonth": "12",
				"creditCardExpYear": "29",
				"billingZipCode": "75028",
				"creditCardType": "masterCard",
				"creditCardVerificationNumber": null,
				"creditCardBIN": "505429",
				"cvvRequired": false
			}],
			"applePayResponseInfo": null,
			"masterpassResponseInfo": {
				"emailAddress": null,
				"cardType": null,
				"lastDigits": null,
				"creditCardBIN": null
			},
			"masterpassError": false,
			"masterpassErrorMessage": null,
			"paypalEmailAddress": null,
			"expirationMonths": ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
			"expirationYears": ["2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027"]
		},
		"devices": {
			"dueMonthly": 15.41,
			"totalActivationFee": 0.0,
			"deviceTotalDueMonthly": 15.41,
			"dueToday": 0.0,
			"accessories": [{
				"scene7ImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/applecareplus-cc3000?$acc-med$",
				"name": "AppleCare+ for iPhone 8, 7, 6s, or 6",
				"actualPrice": 129.97,
				"originalPrice": 129.97,
				"percentageOffTxt": null,
				"itemTotal": 129.97,
				"quantity": 1,
				"commerceItemId": "Sd4f970a4b3cbf35510542304413a00fa{ss100}_accessory_1",
				"color": null,
				"size": null,
				"inventoryStatus": "",
				"inventoryAvailableDate": "",
				"prodId": "acc5240003",
				"skuId": "sku1760050",
				"sorId": "S5556LL/A",
				"promoMessage": null,
				"hasEcpdDiscount": false,
				"mobileAppImageName": "",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/applecareplus-cc3000?$acc-med$",
				"hasBogoDiscount": false,
				"price": 129.97,
				"discountPrice": 0.0,
				"retailPrice": 129.97,
				"associatedDeviceSkus": null,
				"prodName": "",
				"discounted": false
			}, {
				"scene7ImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/zagg-invisibleshield-glass-iphone-6-plus-iset-ippglc-f00?$acc-med$",
				"name": "InvisibleShield Glass+ Screen Protector for iPhone 8 Plus/7 Plus/6s Plus/6 Plus",
				"actualPrice": 39.99,
				"originalPrice": 39.99,
				"percentageOffTxt": null,
				"itemTotal": 39.99,
				"quantity": 1,
				"commerceItemId": "Sd4f970a4b3cbf35510542304413a00fa{ss100}_accessory_2",
				"color": null,
				"size": null,
				"inventoryStatus": "",
				"inventoryAvailableDate": "",
				"prodId": "acc6640065",
				"skuId": "sku2120065",
				"sorId": "I7LLGC-F00",
				"promoMessage": null,
				"hasEcpdDiscount": false,
				"mobileAppImageName": "",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/zagg-invisibleshield-glass-iphone-6-plus-iset-ippglc-f00?$acc-med$",
				"hasBogoDiscount": false,
				"price": 39.99,
				"discountPrice": 0.0,
				"retailPrice": 39.99,
				"associatedDeviceSkus": null,
				"prodName": "",
				"discounted": false
			}],
			"accessoriesBundle": [],
			"items": [{
				"deviceName": "iPhone&reg; 7 Plus",
				"dueMonthly": "15.41",
				"dueToday": "0.00",
				"upgradeFee": "0.00",
				"originalUpgradeFee": "30.00",
				"activationFee": "0.00",
				"dueTodayOriginal": "0.00",
				"dueMonthlyOriginal": "27.92",
				"dueTodayDiscounted": false,
				"dueMonthlyDiscounted": true,
				"mtn": "5125579423",
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-matblk?$device-med$&fmt=jpeg&wid=75&hei=150",
				"protectionFeature": {
					"name": "Decline Equipment Protection",
					"mtn": null,
					"price": "0.00",
					"discountPrice": "0.00",
					"retailPrice": "0.00",
					"hasEcpdDiscount": false,
					"promoMessage": null,
					"originalPrice": "0.00",
					"wasPrice": "0.00",
					"deviceName": null,
					"color": null,
					"size": null,
					"instantCreditAmount": "0.00",
					"amountAfterInstantCredit": "0.00",
					"disountedInstantCreditAmt": "0.00"
				},
				"optionalFeatures": [],
				"installmentBalance": "369.99",
				"edgeRetailPrice": "669.99",
				"edgeItemDownPaymentAmount": "0.00",
				"mailInRebateAmount": "0.00",
				"transferredFromMtn": null,
				"devicePromotionList": [{
					"promotionalMessage": null,
					"promoDescription": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION BIC YES",
					"promoName": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION",
					"promoAmount": "0",
					"priceSubTitle": "1st installment will appear on your bill.",
					"barCodeId": null,
					"itemCode": "MNR12LL/A",
					"itemType": "ITA",
					"sedOffer": true,
					"isUpgradeFeeWaivedOffer": false,
					"promoContentText": null
				}, {
					"promotionalMessage": null,
					"promoDescription": "UAT WAIVED UPGRADE FEE WITH SMT PH ONLINE ONLY UPG 2YR DPP - BIC YES",
					"promoName": "UAT WAIVED UPGRADE FEE WITH SMT PH ONLINE ONLY UPG",
					"promoAmount": "30.0",
					"priceSubTitle": "1st installment will appear on your bill.",
					"barCodeId": null,
					"itemCode": "UPGRADEFEE30",
					"itemType": "ITP",
					"sedOffer": true,
					"isUpgradeFeeWaivedOffer": true,
					"promoContentText": null
				}],
				"bicOfferApplied": false,
				"bicContractPrice": "0.00",
				"bicDiscountedContractPrice": "-1.00",
				"bicAdditionalContractText": null,
				"bicMessageMap": null,
				"edgeUpAmount": 0.0,
				"displayDeviceDueMonthly": 15.41,
				"deviceLACFee": "85.00",
				"manufactureName": "Apple",
				"color": "Black",
				"colorCode": "#000000",
				"size": "32GB",
				"displayName": "iPhone&reg; 7 Plus",
				"contractTerm": "99",
				"edgeUpBuyOutAmount": 0.0,
				"fullRetailPrice": "669.99",
				"alwaysEligibleForUpgrade": false,
				"numberShareDevice": false,
				"activationFeeText": null,
				"numberSharedMtn": null,
				"promoContentText": null,
				"itemOnJaxPlan": true,
				"humCarDetails": null,
				"simDetails": null,
				"imeiId": null,
				"displayImeiId": null,
				"poboDateLabel": null,
				"promoOfferText": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION",
				"promoApplied": true,
				"commerceItemId": "Sd4f970a4b3cbf35510542304413a00fa{ss100}_device_1",
				"loanTerm": 24,
				"sbdHeaderMsg": null,
				"percentage": null,
				"waivedActivationFeePromo": false,
				"flow": "EUP",
				"edgeDevice": true,
				"instantCreditAmount": "0.00",
				"amountAfterInstantCredit": "0.00",
				"eupdevice": false,
				"accessory": false,
				"disountedInstantCreditAmt": "0.00"
			}],
			"buddyUpgrade": false
		},
		"accessories": null,
		"selectedShippingType": {
			"type": "SHIPPING",
			"shippingTypeName": "FREE 2 Day by 8pm",
			"price": 0.0,
			"discountPrice": 0.0,
			"estimatedDeliveryDate": "2018-05-14 00:00:00"
		},
		"dueMonthlyView": {
			"title": "Due Monthly (device only)",
			"dueMonthlyPrice": "15.41",
			"items": [{
				"name": "iPhone&reg; 7 Plus",
				"description": "iPhone&reg; 7 Plus",
				"manufacturer": "Apple",
				"color": "Black",
				"size": "32GB",
				"priceBreakDown": [{
					"lable": "Decline Equipment Protection",
					"price": "0.00",
					"description": null,
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 0.0,
					"itemStrikeThroughPrice": 0.0,
					"noOfBicOccurences": 0
				}, {
					"lable": "Device Payment",
					"price": "15.41",
					"description": "For 24 months, 0% APR with down payment. Reduced retail price: <span class='textDecLineThrough red'>$669.99</span> $369.99",
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 15.41,
					"itemStrikeThroughPrice": 27.92,
					"noOfBicOccurences": 0
				}],
				"edge": true
			}],
			"tmpMd": null
		},
		"balanceCreditCardAmount": "169.96",
		"cpcOrder": true,
		"totalDueMonthlyPlanAndDevice": "185.41",
		"deviceConfigInfo": {
			"devices": [{
				"deviceId": "Sd4f970a4b3cbf35510542304413a00fa{ss100}_device_1",
				"deviceName": "iPhone&reg; 7 Plus",
				"deviceSetupMode": null,
				"mtnNumber": "5125579423",
				"flow": "EUP",
				"serviceAddress": {
					"firstName": "RAVI",
					"lastName": "MANNING",
					"address1": "8701 LAKEVIEW PKWY STE 111-144",
					"address2": "",
					"city": "Rowlett",
					"state": "TX",
					"zipCode": "75088",
					"emailAddress": "WINOTLVYVO@VZW.COM",
					"phoneNumber": "5207420265"
				},
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-matblk?$device-med$&fmt=jpeg&wid=75&hei=150",
				"mobileAppImageName": null,
				"npaNxxnumber": null,
				"npnxxCustomerSelection": null,
				"npaNxxdetails": null,
				"manufactureName": "Apple",
				"color": "Black",
				"size": "32GB",
				"numberShareDevice": false,
				"numberSharedMtn": null,
				"deviceNickName": null,
				"numberSharedDeviceName": null,
				"portInDetails": null
			}],
			"npaNxxdetails": {
				"zipCode": "75088",
				"state": "TX",
				"city": "Rowlett",
				"success": true,
				"mtns": ["214-287-XXXX", "214-288-XXXX", "214-316-XXXX", "214-317-XXXX", "214-406-XXXX", "214-412-XXXX", "214-422-XXXX", "214-437-XXXX", "214-470-XXXX", "214-490-XXXX", "214-531-XXXX", "214-557-XXXX", "214-587-XXXX", "214-601-XXXX", "214-604-XXXX", "214-605-XXXX", "214-608-XXXX", "214-629-XXXX", "214-662-XXXX", "214-681-XXXX", "214-717-XXXX", "214-724-XXXX", "214-766-XXXX", "214-784-XXXX", "214-790-XXXX", "214-846-XXXX", "214-883-XXXX", "214-907-XXXX", "214-918-XXXX", "214-930-XXXX", "214-960-XXXX", "214-984-XXXX"],
				"states": null,
				"cities": null
			},
			"deviceAddressUpdated": false,
			"accessories": null
		},
		"checkoutStates": {
			"shippingAddressRequired": false,
			"shippingAddressChangeRequired": false,
			"shippingMethodRequired": false,
			"paymentRequired": false,
			"pastDuePaymentRequired": false,
			"showPaymentSection": true,
			"showShippingAddress": true,
			"showDeliveryMethod": true,
			"newCard": false,
			"cvvNeeded": false
		},
		"totalEdgeItemDownPaymentAmount": "0.00",
		"totalEdgeUpAmount": "0.00",
		"totalEdgeUpBuyOutAmount": "0.00",
		"multiOrderDetails": null,
		"hasRio": false,
		"splitShipment": false
	}
};