window.confirmationJSON = {
	"output": {
		"title": "You're all set.",
		"subtitle": null,
		"orderId": "422662866407624",
		"estimatedDelivery": "",
		"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/1.3_MV_BuyandUpgrade_ConfirmationPage_Interstital?$device-med$",
		"tradeInStatus": false,
		"confirmationMessage": "Thanks for ordering from verizonwireless.com. Your order receipt is sent to VZW@VZW.COM.",
		"doneButtonText": "Got it",
		"doneButtonLink": "/od/cust/auth/shoplanding/",
		"userNote": "TODO",
		"notNowButtonText": "TODO",
		"notNowButtonLink": "TODO",
		"learnHowButtonText": null,
		"learnHowButtonLink": "/od/cust/auth/learnHow",
		"numberOfDevice": 1,
		"confirmationNumberText": "Confirmation Number",
		"iconicFlow": true,
		"protectionURL": null,
		"accessoriesURL": null,
		"tapFlag": false,
		"cjmTagUrl": null,
		"pepperJamTagUrl": null,
		"selectedPaymentMode": null,
		"confirmationEmail": "VZW@VZW.COM",
		"plans": {
			"dueMonthly": "155.00",
			"dueToday": "0.00",
			"planOnlyDueMonthly": "155.00",
			"items": [{
				"planType": "Go Unlimited",
				"lineAccessCharges": [{
					"name": "Apple iPhone&reg; 7 Plus 32GB in Black",
					"mtn": null,
					"price": "45.00",
					"discountPrice": "0.00",
					"retailPrice": "0.00",
					"hasEcpdDiscount": false,
					"promoMessage": null,
					"originalPrice": "22.50",
					"wasPrice": "22.50",
					"deviceName": "iPhone&reg; 7 Plus",
					"color": "Black",
					"size": "32GB",
					"instantCreditAmount": "0.00",
					"amountAfterInstantCredit": "0.00",
					"disountedInstantCreditAmt": "0.00",
					"tapfeature": false
				}],
				"accountAccess": {
					"name": "Go Unlimited",
					"mtn": null,
					"price": "155.00",
					"discountPrice": "0.00",
					"retailPrice": "0.00",
					"hasEcpdDiscount": false,
					"promoMessage": null,
					"originalPrice": "0.00",
					"wasPrice": "0.00",
					"deviceName": null,
					"color": null,
					"size": null,
					"instantCreditAmount": "0.00",
					"amountAfterInstantCredit": "0.00",
					"disountedInstantCreditAmt": "0.00",
					"tapfeature": false
				},
				"accountLevelFeatures": null,
				"totalMonthlyPlanCost": "155.00",
				"spoBadgeMessage": null,
				"planDisplayName": "Go Unlimited",
				"planImageURL": null,
				"planLetter": null,
				"planDescrption": null,
				"planDescription": null,
				"quantity": 0,
				"skuId": null,
				"productId": null,
				"itemAmount": null,
				"itemAmountOriginal": null,
				"dueMonthly": null,
				"dueMonthlyOriginal": null,
				"itemDiscount": null,
				"displayName": null,
				"skuDisplayName": null,
				"listPrice": null,
				"rawTotalAmount": null,
				"planGroupCode": null,
				"autoPayEnabled": false,
				"numberSharePlan": false,
				"planCommerceItemId": null,
				"autoPayPrice": null,
				"autoPayText": null,
				"termsAndConditionKey": null,
				"unitOfMeasure": null,
				"planSize": null
			}],
			"upgradeDevices": [],
			"newDevices": [{
				"name": "iPhone&reg; 7 Plus",
				"price": "45.00",
				"discountPrice": 45.0,
				"hasEcpdDiscount": true,
				"mtn": null,
				"listPrice": 45.0,
				"deviceLineItemId": "S7b501d0005a2327ff50d90b3aea9dce3{ss3}_device_1",
				"discountPriceVal": "45.00",
				"planCommerceItemId": null,
				"nickName": null,
				"numberShareDevice": false,
				"featureDropped": false
			}],
			"existingDevices": [{
				"name": "Apple&reg; iPhone&reg; 7 Plus 128GB in Jet Black",
				"price": "45.00",
				"discountPrice": 22.5,
				"hasEcpdDiscount": true,
				"mtn": "2155127957",
				"listPrice": 45.0,
				"deviceLineItemId": null,
				"discountPriceVal": "22.50",
				"planCommerceItemId": null,
				"nickName": null,
				"numberShareDevice": false,
				"featureDropped": false
			}, {
				"name": "Apple&reg; iPhone&reg; 6 Plus 128GB in Space Gray",
				"price": "45.00",
				"discountPrice": 22.5,
				"hasEcpdDiscount": true,
				"mtn": "2817346748",
				"listPrice": 45.0,
				"deviceLineItemId": null,
				"discountPriceVal": "22.50",
				"planCommerceItemId": null,
				"nickName": null,
				"numberShareDevice": false,
				"featureDropped": false
			}, {
				"name": "Apple&reg; iPhone&reg; SE 16GB in Rose Gold",
				"price": "45.00",
				"discountPrice": 22.5,
				"hasEcpdDiscount": true,
				"mtn": "2817348728",
				"listPrice": 45.0,
				"deviceLineItemId": null,
				"discountPriceVal": "22.50",
				"planCommerceItemId": null,
				"nickName": null,
				"numberShareDevice": false,
				"featureDropped": false
			}, {
				"name": "Verizon Ellipsis&reg; 10 16GB in Black",
				"price": "20.00",
				"discountPrice": 10.0,
				"hasEcpdDiscount": true,
				"mtn": "7137022989",
				"listPrice": 20.0,
				"deviceLineItemId": null,
				"discountPriceVal": "10.00",
				"planCommerceItemId": null,
				"nickName": null,
				"numberShareDevice": false,
				"featureDropped": false
			}, {
				"name": "LG Octane&trade;",
				"price": "45.00",
				"discountPrice": 22.5,
				"hasEcpdDiscount": true,
				"mtn": "7245505275",
				"listPrice": 45.0,
				"deviceLineItemId": null,
				"discountPriceVal": "22.50",
				"planCommerceItemId": null,
				"nickName": null,
				"numberShareDevice": false,
				"featureDropped": false
			}, {
				"name": "Apple&reg; Watch Series 3, 38mm Space Gray Aluminum Case with Black Sport Band",
				"price": "10.00",
				"discountPrice": 5.0,
				"hasEcpdDiscount": true,
				"mtn": "8323747528",
				"listPrice": 10.0,
				"deviceLineItemId": null,
				"discountPriceVal": "5.00",
				"planCommerceItemId": null,
				"nickName": null,
				"numberShareDevice": false,
				"featureDropped": false
			}, {
				"name": "GizmoGadget&trade; by LG in Navy",
				"price": "5.00",
				"discountPrice": 2.5,
				"hasEcpdDiscount": true,
				"mtn": "8323899914",
				"listPrice": 5.0,
				"deviceLineItemId": null,
				"discountPriceVal": "2.50",
				"planCommerceItemId": null,
				"nickName": null,
				"numberShareDevice": false,
				"featureDropped": false
			}, {
				"name": "Apple&reg; iPhone&reg; 8 Plus 64GB in Gold",
				"price": "45.00",
				"discountPrice": 22.5,
				"hasEcpdDiscount": true,
				"mtn": "8326557748",
				"listPrice": 45.0,
				"deviceLineItemId": null,
				"discountPriceVal": "22.50",
				"planCommerceItemId": null,
				"nickName": null,
				"numberShareDevice": false,
				"featureDropped": false
			}, {
				"name": "GizmoGadget&trade; by LG in Navy",
				"price": "5.00",
				"discountPrice": 2.5,
				"hasEcpdDiscount": true,
				"mtn": "8327029542",
				"listPrice": 5.0,
				"deviceLineItemId": null,
				"discountPriceVal": "2.50",
				"planCommerceItemId": null,
				"nickName": null,
				"numberShareDevice": false,
				"featureDropped": false
			}],
			"dueMonthlyPlanWithLAC": "310.00",
			"discountedDueMonthlyPlanWithLAC": "155.00",
			"hasEcpdDiscount": true,
			"totalLineAccessCharges": "45.00"
		},
		"tradeInDevicesDetails": null,
		"tradeInPromoDetails": null,
		"transformedTradeInPromoDetails": {
			"tradeInDeviceDppMsg": "We'll send you a prepaid box to mail in your trade-in. This is only an estimate until we receive and appraise your device.",
			"warningMessage": null,
			"tradeInDeviceHeaderMsg": "You'll see an estimated $200.00 credit within 1-2 bill cycles.",
			"tradeInCredit": "-200.00",
			"tradeInDevices": [{
				"activeDevice": null,
				"tradeInCredit": "200.00",
				"tradeInDeviceFooter": null,
				"offerDetailsMsg": null,
				"tradeInDeviceHeaderMsg": null,
				"tradeInCreditMsg": "Trade-in credit: $200.00",
				"bicApplied": null,
				"color": "Rose Gold",
				"dataWipeText": null,
				"deviceBrand": null,
				"deviceId": "ID: 355434072744826",
				"discAmt": null,
				"disconnectedDate": null,
				"displayName": "iPhone SE",
				"dppCredit": "0.0",
				"dppAppliedCommerceItemId": null,
				"dppAppliedMdn": null,
				"errorMessage": null,
				"modalOsName": null,
				"modelImage": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iPhoneSE_rsGld?$device-lg$",
				"modelName": null,
				"mtn": null,
				"nickName": null,
				"originalAppraisalPrice": "72.00",
				"price": null,
				"promoCodeError": null,
				"promoCreditType": null,
				"promoQualifyMessage": null,
				"promoValue": null,
				"shortDisplayName": null,
				"size": "16GB",
				"success": true,
				"regularPromoApplied": null,
				"existingAppraisedReferenceId": null,
				"appraiseTradeInDeviceWithOutDeviceId": false,
				"flow": null
			}],
			"orginaltradeInCredit": null
		},
		"subOrders": null,
		"comboOrder": false,
		"totalDueToday": "22.20",
		"totalDueMonthly": "15.41",
		"subTotalDueToday": "0.00",
		"securityDepositAmount": "0.00",
		"stateSalesTax": "22.20",
		"employeeDiscount": "0.00",
		"pastDueExist": false,
		"pastDueAmountPaid": false,
		"pastDueAmount": "0.00",
		"shippingInfo": {
			"shippingInfoUpdated": false,
			"sameAsBilling": false,
			"ispuEligibleFlag": true,
			"addressInfo": {
				"firstName": "BEN",
				"lastName": "BOWER",
				"companyName": null,
				"address1": "1317 SITZWATER STREET APT 201",
				"address2": null,
				"city": "Philadelphia",
				"state": "PA",
				"zipcode": "19147",
				"businessName": null,
				"postalCode": null,
				"email": "VZW@VZW.COM",
				"phoneNumber": "6926164614"
			},
			"contactInfo": {
				"emailAddress": "VZW@VZW.COM",
				"phoneNumber": "6926164614",
				"firstName": "BEN",
				"lastName": "BOWER",
				"smsMdn": "",
				"activeSMSCapableMtnList": ["8326557748", "8323747528", "8327029542", "2155127957", "7245505275", "8323899914", "2817346748", "2817348728", "7137022989"]
			},
			"shippingTypesInfo": null,
			"storeDetail": {
				"storeHeader": null,
				"storeName": "",
				"storeAddress": "731 W Sproul Rd Springfield PA 19064 ",
				"deviceAvailable": false,
				"distance": null,
				"appendedStoreTiming": "Sun : 11:00 AM 06:00 PM | Mon - Sat : 10:00 AM 08:00 PM",
				"longitude": "-75.3514",
				"storeId": "1096406",
				"netaceLocationCode": null,
				"latitude": "39.936398",
				"seoUrlName": null,
				"storeClosingTime": null
			},
			"tradeIn": false,
			"tradeInAddress": null,
			"nonSddEligibleMsg": null,
			"selectedSDDWindow": null,
			"poboMessage": null,
			"ispudetailsInfo": {
				"storeAddress": {
					"firstName": null,
					"lastName": null,
					"companyName": null,
					"address1": "731 W Sproul Rd",
					"address2": null,
					"city": "Springfield",
					"state": "PA",
					"zipcode": "19064",
					"businessName": null,
					"postalCode": null,
					"email": null,
					"phoneNumber": null
				},
				"storeHours": {
					"Sun": "11:00 AM 06:00 PM         ",
					"Mon - Sat": "10:00 AM 08:00 PM         "
				},
				"storeId": "1096406",
				"storeName": "",
				"phoneNumber": null,
				"distance": null,
				"totalItems": 0,
				"availItems": 0,
				"latitdude": 39.936398,
				"longtitude": -75.3514,
				"availItemName": null
			}
		},
		"billingInfo": {
			"billToAccountEligible": true,
			"creditCardZipEditable": false,
			"billingAddress": {
				"firstName": "BEN",
				"lastName": "BOWER",
				"businessName": null,
				"zipcode": "19147",
				"state": "PA",
				"address2": null,
				"address1": "1317 SITZWATER STREET APT 201",
				"companyName": null,
				"city": "Philadelphia",
				"sameAsShipping": false
			},
			"masterpass3DSecure": null,
			"billToAccountNumber": "#XXXXXXX-0001",
			"creditCardInfo": {
				"savedCardNickName": null,
				"preselectCard": null,
				"creditCardNumber": null,
				"creditCardExpMonth": null,
				"creditCardExpYear": null,
				"billingZipCode": null,
				"creditCardType": null,
				"creditCardVerificationNumber": null,
				"creditCardBIN": null,
				"cvvRequired": false
			},
			"selectedPaymentMode": "BTA",
			"giftCardList": [],
			"savedCardInfo": null,
			"applePayResponseInfo": null,
			"masterpassResponseInfo": {
				"emailAddress": null,
				"cardType": null,
				"lastDigits": null,
				"creditCardBIN": null
			},
			"masterpassError": false,
			"masterpassErrorMessage": null,
			"paypalEmailAddress": null,
			"expirationMonths": null,
			"expirationYears": null
		},
		"devices": {
			"dueMonthly": 15.41,
			"totalActivationFee": 0.0,
			"deviceTotalDueMonthly": 15.41,
			"dueToday": 0.0,
			"accessories": [],
			"accessoriesBundle": [],
			"items": [{
				"deviceName": "iPhone&reg; 7 Plus",
				"dueMonthly": "15.41",
				"dueToday": "0.00",
				"upgradeFee": "0.00",
				"originalUpgradeFee": "0.00",
				"activationFee": "0.00",
				"dueTodayOriginal": "0.00",
				"dueMonthlyOriginal": "27.92",
				"dueTodayDiscounted": false,
				"dueMonthlyDiscounted": true,
				"mtn": null,
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-matblk?$device-med$&fmt=jpeg&wid=75&hei=150",
				"protectionFeature": {
					"name": "Total Mobile Protection Multi-Device",
					"mtn": null,
					"price": "-",
					"discountPrice": "0.00",
					"retailPrice": "0.00",
					"hasEcpdDiscount": false,
					"promoMessage": null,
					"originalPrice": "0.00",
					"wasPrice": "0.00",
					"deviceName": null,
					"color": null,
					"size": null,
					"instantCreditAmount": "0.00",
					"amountAfterInstantCredit": "0.00",
					"disountedInstantCreditAmt": "0.00",
					"tapfeature": true
				},
				"optionalFeatures": [],
				"installmentBalance": "369.99",
				"edgeRetailPrice": "669.99",
				"edgeItemDownPaymentAmount": "0.00",
				"mailInRebateAmount": "0.00",
				"transferredFromMtn": null,
				"devicePromotionList": [{
					"promotionalMessage": null,
					"promoDescription": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION BIC YES",
					"promoName": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION",
					"promoAmount": "300.00",
					"priceSubTitle": "1st installment will appear on your bill.",
					"barCodeId": null,
					"itemCode": "MNR12LL/A",
					"itemType": "ITA",
					"sedOffer": true,
					"isUpgradeFeeWaivedOffer": false,
					"promoContentText": null
				}],
				"bicOfferApplied": false,
				"bicContractPrice": "0.00",
				"bicDiscountedContractPrice": "-1.00",
				"bicAdditionalContractText": null,
				"bicMessageMap": null,
				"edgeUpAmount": 0.0,
				"displayDeviceDueMonthly": 15.41,
				"deviceLACFee": "45.00",
				"manufactureName": "Apple",
				"color": "Black",
				"colorCode": "#000000",
				"size": "32GB",
				"displayName": "iPhone&reg; 7 Plus",
				"contractTerm": "99",
				"edgeUpBuyOutAmount": 0.0,
				"fullRetailPrice": "669.99",
				"alwaysEligibleForUpgrade": false,
				"numberShareDevice": false,
				"activationFeeText": "Waived Activation Fee",
				"numberSharedMtn": null,
				"promoContentText": null,
				"itemOnJaxPlan": true,
				"humCarDetails": null,
				"simDetails": null,
				"imeiId": null,
				"displayImeiId": null,
				"poboDateLabel": null,
				"nickName": null,
				"planCommerceItemId": null,
				"displayMtn": null,
				"promoOfferText": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION",
				"promoApplied": true,
				"commerceItemId": "S7b501d0005a2327ff50d90b3aea9dce3{ss3}_device_1",
				"loanTerm": 24,
				"sbdHeaderMsg": null,
				"percentage": null,
				"waivedActivationFeePromo": false,
				"flow": "AAL",
				"edgeDevice": true,
				"instantCreditAmount": "0.00",
				"amountAfterInstantCredit": "0.00",
				"accessory": false,
				"eupdevice": false,
				"disountedInstantCreditAmt": "0.00"
			}],
			"buddyUpgrade": false
		},
		"accessories": null,
		"selectedShippingType": {
			"type": "ISPU",
			"shippingTypeName": "In Store Pick Up",
			"price": 0.0,
			"discountPrice": 0.0,
			"estimatedDeliveryDate": null
		},
		"balanceCreditCardAmount": "22.20",
		"cpcOrder": false,
		"totalDueMonthlyPlanAndDevice": "60.41",
		"deviceConfigInfo": {
			"devices": [{
				"deviceId": "S7b501d0005a2327ff50d90b3aea9dce3{ss3}_device_1",
				"deviceName": "iPhone&reg; 7 Plus",
				"deviceSetupMode": null,
				"mtnNumber": null,
				"flow": "AAL",
				"serviceAddress": {
					"firstName": "BEN",
					"lastName": "BOWER",
					"address1": "1317 SITZWATER STREET APT 201",
					"address2": "",
					"city": "Philadelphia",
					"state": "PA",
					"zipCode": "19147",
					"emailAddress": "VZW@VZW.COM",
					"phoneNumber": "6926164614"
				},
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-matblk?$device-med$&fmt=jpeg&wid=75&hei=150",
				"mobileAppImageName": null,
				"npaNxxnumber": "302-542-XXXX",
				"npnxxCustomerSelection": "new",
				"npaNxxdetails": null,
				"manufactureName": "Apple",
				"color": "Black",
				"size": "32GB",
				"numberShareDevice": false,
				"numberSharedMtn": null,
				"deviceNickName": null,
				"numberSharedDeviceName": null,
				"portInDetails": null
			}],
			"npaNxxdetails": {
				"zipCode": null,
				"state": null,
				"city": null,
				"success": false,
				"mtns": null,
				"states": null,
				"cities": null
			},
			"deviceAddressUpdated": false,
			"accessories": null
		},
		"checkoutStates": {
			"shippingAddressRequired": false,
			"shippingAddressChangeRequired": false,
			"poBoxShippingAddress": false,
			"shippingAddressValidationError": false,
			"shippingMethodRequired": false,
			"paymentRequired": false,
			"pastDuePaymentRequired": false,
			"showPaymentSection": true,
			"showShippingAddress": true,
			"showDeliveryMethod": true,
			"newCard": false,
			"cvvNeeded": true,
			"contactInfoRequired": false
		},
		"totalEdgeItemDownPaymentAmount": "0.00",
		"totalEdgeUpAmount": "0.00",
		"totalEdgeUpBuyOutAmount": "0.00",
		"multiOrderDetails": null,
		"hasRio": false,
		"splitShipment": false,
		"isHLLPlanInOrder": false
	}
};