window.confirmationJSON = {
	"output": {
		"title": "You're all set.",
		"subtitle": null,
		"orderId": "924042307573690",
		"estimatedDelivery": "",
		"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/1.3_MV_BuyandUpgrade_ConfirmationPage_Interstital?$device-med$",
		"tradeInStatus": false,
		"confirmationMessage": "Thanks for ordering from verizonwireless.com. Your order receipt is sent to WINOTLVYVO@VZW.COM.",
		"doneButtonText": "Got it",
		"doneButtonLink": "/od/cust/auth/shoplanding/",
		"userNote": "TODO",
		"notNowButtonText": "TODO",
		"notNowButtonLink": "TODO",
		"learnHowButtonText": null,
		"learnHowButtonLink": "/od/cust/auth/learnHow",
		"numberOfDevice": 1,
		"confirmationNumberText": "Confirmation Number",
		"iconicFlow": true,
		"protectionURL": null,
		"accessoriesURL": null,
		"tapFlag": false,
		"cjmTagUrl": null,
		"pepperJamTagUrl": null,
		"selectedPaymentMode": null,
		"confirmationEmail": "WINOTLVYVO@VZW.COM",
		"plans": {
			"dueMonthly": "195.00",
			"dueToday": "0.00",
			"planOnlyDueMonthly": "195.00",
			"items": [{
				"planType": "Beyond Unlimited",
				"lineAccessCharges": [{
					"name": "Apple iPhone&reg; 4s 32GB in White",
					"mtn": null,
					"price": "65.00",
					"discountPrice": "0.00",
					"retailPrice": "0.00",
					"hasEcpdDiscount": false,
					"promoMessage": null,
					"originalPrice": "65.00",
					"wasPrice": "65.00",
					"deviceName": "iPhone&reg; 4s",
					"color": "White",
					"size": "32GB",
					"instantCreditAmount": "0.00",
					"amountAfterInstantCredit": "0.00",
					"disountedInstantCreditAmt": "0.00"
				}],
				"accountAccess": {
					"name": "Beyond Unlimited",
					"mtn": null,
					"price": "195.00",
					"discountPrice": "0.00",
					"retailPrice": "0.00",
					"hasEcpdDiscount": false,
					"promoMessage": null,
					"originalPrice": "0.00",
					"wasPrice": "0.00",
					"deviceName": null,
					"color": null,
					"size": null,
					"instantCreditAmount": "0.00",
					"amountAfterInstantCredit": "0.00",
					"disountedInstantCreditAmt": "0.00"
				},
				"accountLevelFeatures": null,
				"totalMonthlyPlanCost": "195.00",
				"spoBadgeMessage": null,
				"planDisplayName": "Beyond Unlimited",
				"planImageURL": null,
				"planLetter": null,
				"planDescrption": null,
				"planDescription": null
			}],
			"upgradeDevices": [],
			"newDevices": [{
				"name": "iPhone&reg; 4s",
				"price": "65.00",
				"discountPrice": 0.0,
				"hasEcpdDiscount": false,
				"mtn": null,
				"listPrice": 65.0,
				"deviceLineItemId": "S41b5dda5cb299b43e1a044200f169028{ss100}_device_1",
				"discountPriceVal": "0.00"
			}],
			"existingDevices": [{
				"name": "LG Octane&trade;",
				"price": "65.00",
				"discountPrice": 0.0,
				"hasEcpdDiscount": false,
				"mtn": "2108340918",
				"listPrice": 65.0,
				"deviceLineItemId": null,
				"discountPriceVal": "0.00"
			}, {
				"name": "Samsung Galaxy Note&reg; 3 in Black",
				"price": "65.00",
				"discountPrice": 0.0,
				"hasEcpdDiscount": false,
				"mtn": "5125579423",
				"listPrice": 65.0,
				"deviceLineItemId": null,
				"discountPriceVal": "0.00"
			}],
			"dueMonthlyPlanWithLAC": "195.00",
			"discountedDueMonthlyPlanWithLAC": "0.00",
			"hasEcpdDiscount": false,
			"totalLineAccessCharges": "65.00"
		},
		"featureList": [{
			"id": "S41b5dda5cb299b43e1a044200f169028{ss100}_feature_1",
			"quantity": 0,
			"type": null,
			"skuId": "sku2560179",
			"productId": "sfo80079",
			"sorId": "85433",
			"itemAmount": 0.0,
			"itemAmountOriginal": 0.0,
			"dueMonthly": 65.0,
			"dueMonthlyOriginal": null,
			"itemDiscount": 0.0,
			"displayName": "Phone Plan",
			"skuDisplayName": null,
			"listPrice": 65.0,
			"rawTotalAmount": 0.0,
			"pricingDetails": [{
				"pricingAdjustmentId": null,
				"itemId": "S41b5dda5cb299b43e1a044200f169028{ss100}_feature_1",
				"orderId": null,
				"offerId": null,
				"offerAmount": 0.0,
				"description": "List Price description",
				"offerType": null,
				"priceListId": null,
				"listPrice": 65.0,
				"offerName": null,
				"creationDate": 1525950652330,
				"lastModifiedDate": 1525950652330,
				"version": 1
			}],
			"orderId": null,
			"version": 0,
			"delete": false,
			"inventoryLevel": 0,
			"taxDetails": null,
			"itemTaxes": 0.0,
			"deviceLineItemId": "S41b5dda5cb299b43e1a044200f169028{ss100}_device_1",
			"featureCharge": 0.0,
			"featureType": "LAC",
			"lastModifiedDate": null
		}],
		"accessoryList": [{
			"id": "S41b5dda5cb299b43e1a044200f169028{ss100}_accessory_1",
			"quantity": 1,
			"type": null,
			"skuId": "sku10179",
			"productId": "acc40178",
			"sorId": "326223-0080",
			"itemAmount": 99.98,
			"itemAmountOriginal": 0.0,
			"dueMonthly": 0.0,
			"dueMonthlyOriginal": null,
			"itemDiscount": 0.0,
			"displayName": "Bose MIE2i mobile headset",
			"skuDisplayName": "Bose MIE2i mobile headset",
			"listPrice": 99.98,
			"rawTotalAmount": 99.98,
			"pricingDetails": [{
				"pricingAdjustmentId": null,
				"itemId": "S41b5dda5cb299b43e1a044200f169028{ss100}_accessory_1",
				"orderId": "S41b5dda5cb299b43e1a044200f169028{ss100}",
				"offerId": null,
				"offerAmount": 0.0,
				"description": "List Price description",
				"offerType": null,
				"priceListId": null,
				"listPrice": 99.98,
				"offerName": null,
				"creationDate": 1525950652330,
				"lastModifiedDate": 1525950652330,
				"version": 1
			}],
			"orderId": "S41b5dda5cb299b43e1a044200f169028{ss100}",
			"version": 1,
			"delete": false,
			"inventoryLevel": 1000,
			"taxDetails": [{
				"taxLineItemId": null,
				"lineItemId": "S41b5dda5cb299b43e1a044200f169028{ss100}_accessory_1",
				"itemType": "accessory",
				"sorSkuId": "326223-0080",
				"taxType": "taxes_fees",
				"taxAmount": 6.25,
				"taxDescription": "TX State Sales Tax",
				"version": 0,
				"orderId": "S41b5dda5cb299b43e1a044200f169028{ss100}",
				"createdDate": 1525950657380
			}, {
				"taxLineItemId": null,
				"lineItemId": "S41b5dda5cb299b43e1a044200f169028{ss100}_accessory_1",
				"itemType": "accessory",
				"sorSkuId": "326223-0080",
				"taxType": "taxes_fees",
				"taxAmount": 1.0,
				"taxDescription": "TX Local Sales Tax",
				"version": 0,
				"orderId": "S41b5dda5cb299b43e1a044200f169028{ss100}",
				"createdDate": 1525950657380
			}, {
				"taxLineItemId": null,
				"lineItemId": "S41b5dda5cb299b43e1a044200f169028{ss100}_accessory_1",
				"itemType": "accessory",
				"sorSkuId": "326223-0080",
				"taxType": "taxes_fees",
				"taxAmount": 1.0,
				"taxDescription": "TX Local Sales Tax",
				"version": 0,
				"orderId": "S41b5dda5cb299b43e1a044200f169028{ss100}",
				"createdDate": 1525950657380
			}],
			"itemTaxes": 8.25,
			"deviceLineItemId": null,
			"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/bose_mie2_mobile_heads?$acc-med$",
			"bogoType": null,
			"recycleStateInd": null,
			"color": null,
			"size": null,
			"capacity": null,
			"lastModifiedDate": 1525950499366,
			"deviceManufacturerName": "Bose",
			"accessoryType": "INLINE_ACCESSORIES",
			"ispuEligibleFlag": true,
			"bundleSkuLineItems": null,
			"bundleDesciption": null,
			"vzwSbdOfferlist": [],
			"promotions": null,
			"purchasePath": "AAL",
			"appleCare": false,
			"expectedShippingDate": null,
			"shipCommitInd": null,
			"sameDayDelivery": false,
			"recycleCreditAllocatedAmount": 0.0,
			"ecpdItemAmount": null,
			"ecpdItemDiscount": 0.0,
			"standaloneaccessory": false,
			"batteryAccessory": false,
			"accSeoUrl": ""
		}],
		"paymentGroup": null,
		"contactInfo": {
			"id": null,
			"emailAddress": "WINOTLVYVO@VZW.COM",
			"phoneNumber": "5207420265",
			"lastName": "MANNING",
			"firstName": "RAVI",
			"zipCode": "75088",
			"orderId": null,
			"userId": null,
			"npaNxxNumber": null,
			"address1": "8701 LAKEVIEW PKWY STE 111-144",
			"address2": null,
			"city": "Rowlett",
			"state": "TX",
			"addressVerified": true,
			"textAlertOptin": false,
			"newsLetterOptin": false,
			"paperFreeBillingIndicatorFlag": false,
			"middleName": null,
			"firmName": null,
			"businessName": null,
			"apartmentNum": "111-1",
			"addressDirection": "",
			"poBox": "",
			"streetNumber": "8701",
			"streetName": "LAKEVIEW",
			"streetType": "PKWY",
			"ruralRoute": null,
			"ruralDel": "",
			"zipCode4": null,
			"zipCode5": null,
			"faxNumber": null,
			"addressType": null,
			"country": "",
			"prefix": null,
			"suffix": null,
			"postbox": null,
			"companyname": null,
			"ruralrte": "",
			"county": null,
			"address3": null,
			"postalcode": "75088",
			"version": 0,
			"lastModifiedDate": null,
			"addressConfirmationStatus": null
		},
		"tradeInDevicesDetails": null,
		"tradeInPromoDetails": null,
		"transformedTradeInPromoDetails": {
			"tradeInDeviceDppMsg": "We'll send you a prepaid box to mail in your trade-in. This is only an estimate until we receive and appraise your device.",
			"warningMessage": null,
			"tradeInDeviceHeaderMsg": "You'll see an estimated $200.00 credit within 1-2 bill cycles.",
			"tradeInCredit": "-200.00",
			"tradeInDevices": [{
				"activeDevice": null,
				"tradeInCredit": "200.00",
				"tradeInDeviceFooter": null,
				"offerDetailsMsg": null,
				"tradeInDeviceHeaderMsg": null,
				"tradeInCreditMsg": "Trade-in credit: $200.00",
				"bicApplied": null,
				"color": "Black",
				"dataWipeText": null,
				"deviceBrand": null,
				"deviceId": "ID: 990004661602320",
				"discAmt": null,
				"disconnectedDate": null,
				"displayName": "Galaxy Note 3",
				"dppCredit": "8.33",
				"dppAppliedCommerceItemId": null,
				"dppAppliedMdn": null,
				"errorMessage": null,
				"modalOsName": null,
				"modelImage": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_Note3_Black?$device-lg$",
				"modelName": null,
				"mtn": null,
				"nickName": null,
				"originalAppraisalPrice": "32.00",
				"price": null,
				"promoCodeError": null,
				"promoCreditType": null,
				"promoQualifyMessage": null,
				"promoValue": null,
				"shortDisplayName": null,
				"size": "32GB",
				"success": true,
				"regularPromoApplied": null,
				"existingAppraisedReferenceId": null,
				"appraiseTradeInDeviceWithOutDeviceId": false,
				"flow": null
			}, {
				"activeDevice": null,
				"tradeInCredit": "0.00",
				"tradeInDeviceFooter": null,
				"offerDetailsMsg": null,
				"tradeInDeviceHeaderMsg": null,
				"tradeInCreditMsg": "Trade-in credit: $0.00",
				"bicApplied": null,
				"color": "Black",
				"dataWipeText": null,
				"deviceBrand": null,
				"deviceId": "ID: A0000049529CC0",
				"discAmt": null,
				"disconnectedDate": null,
				"displayName": "Home Phone Connect F256",
				"dppCredit": "0.0",
				"dppAppliedCommerceItemId": null,
				"dppAppliedMdn": null,
				"errorMessage": null,
				"modalOsName": null,
				"modelImage": "https://ss7.vzw.com/is/image/VerizonWireless/home_phone_connect_f256vw?$device-lg$",
				"modelName": null,
				"mtn": null,
				"nickName": null,
				"originalAppraisalPrice": "0.00",
				"price": null,
				"promoCodeError": null,
				"promoCreditType": null,
				"promoQualifyMessage": null,
				"promoValue": null,
				"shortDisplayName": null,
				"size": null,
				"success": true,
				"regularPromoApplied": null,
				"existingAppraisedReferenceId": null,
				"appraiseTradeInDeviceWithOutDeviceId": false,
				"flow": null
			}],
			"orginaltradeInCredit": null
		},
		"subOrders": null,
		"comboOrder": false,
		"totalDueToday": "108.23",
		"totalDueMonthly": "0.00",
		"subTotalDueToday": "99.98",
		"securityDepositAmount": "0.00",
		"stateSalesTax": "8.25",
		"employeeDiscount": "0.00",
		"pastDueExist": false,
		"pastDueAmountPaid": false,
		"pastDueAmount": "0.00",
		"shippingInfo": {
			"shippingInfoUpdated": false,
			"sameAsBilling": true,
			"ispuEligibleFlag": false,
			"addressInfo": {
				"firstName": "RAVI",
				"lastName": "MANNING",
				"companyName": null,
				"address1": "8701 LAKEVIEW PKWY STE 111-144",
				"address2": null,
				"city": "Rowlett",
				"state": "TX",
				"zipcode": "75088",
				"businessName": null,
				"postalCode": null,
				"email": "WINOTLVYVO@VZW.COM",
				"phoneNumber": "5207420265"
			},
			"contactInfo": {
				"emailAddress": "WINOTLVYVO@VZW.COM",
				"phoneNumber": "5207420265",
				"firstName": "RAVI",
				"lastName": "MANNING",
				"smsMdn": null,
				"activeSMSCapableMtnList": ["5125579423"]
			},
			"shippingTypesInfo": [{
				"estimatedDeliveryDate": "2018-05-14 00:00:00",
				"estimatedDeliveryDateText": "Mon 5/14",
				"shippingDescription": "Free 2 Day by 8pm",
				"shippingOptionId": "SHP002",
				"shippingCost": "0.00",
				"shortDescription": "Free 2 Day by 8pm",
				"active": true,
				"addedShippingOptionId": true,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Mon, May 14 if ordered by 4pm today. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}, {
				"estimatedDeliveryDate": "2018-05-11 00:00:00",
				"estimatedDeliveryDateText": "Fri 5/11",
				"shippingDescription": "Next Day by 8pm",
				"shippingOptionId": "SHP004",
				"shippingCost": "12.99",
				"shortDescription": "Next Day by 8pm",
				"active": true,
				"addedShippingOptionId": false,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Fri, May 11. Next Day by 8pm. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}, {
				"estimatedDeliveryDate": "2018-05-11 10:30:00",
				"estimatedDeliveryDateText": "Fri 5/11 by 10:30AM",
				"shippingDescription": "Next Day by 10:30am",
				"shippingOptionId": "SHP005",
				"shippingCost": "14.99",
				"shortDescription": "Next Day by 10:30am",
				"active": true,
				"addedShippingOptionId": false,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Fri, May 11. Next Day by 10:30am. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}],
			"storeDetail": {
				"storeHeader": null,
				"storeName": null,
				"storeAddress": null,
				"deviceAvailable": false,
				"distance": null,
				"appendedStoreTiming": null,
				"longitude": null,
				"storeId": null,
				"netaceLocationCode": null,
				"latitude": null,
				"seoUrlName": null,
				"storeClosingTime": null
			},
			"tradeIn": true,
			"tradeInAddress": {
				"firstName": "RAVI",
				"lastName": "MANNING",
				"address1": "8701 LAKEVIEW PKWY STE 111-144",
				"address2": null,
				"city": "Rowlett",
				"state": "TX",
				"zipcode": "75088",
				"companyName": null
			},
			"nonSddEligibleMsg": null,
			"selectedSDDWindow": null,
			"poboMessage": null,
			"ispudetailsInfo": {
				"storeAddress": null,
				"storeHours": null,
				"storeId": null,
				"storeName": null,
				"phoneNumber": null,
				"distance": null,
				"totalItems": 0,
				"availItems": 0,
				"latitdude": 0.0,
				"longtitude": 0.0,
				"availItemName": null
			}
		},
		"billingInfo": {
			"billToAccountEligible": true,
			"creditCardZipEditable": false,
			"billingAddress": {
				"firstName": "RAVI",
				"lastName": "MANNING",
				"businessName": null,
				"zipcode": "75088",
				"state": "TX",
				"address2": null,
				"address1": "8701 LAKEVIEW PKWY STE 111-144",
				"companyName": null,
				"city": "Rowlett"
			},
			"masterpass3DSecure": null,
			"billToAccountNumber": "#XXXXXXX-0001",
			"creditCardInfo": {
				"savedCardNickName": null,
				"preselectCard": null,
				"creditCardNumber": null,
				"creditCardExpMonth": null,
				"creditCardExpYear": null,
				"billingZipCode": null,
				"creditCardType": null,
				"creditCardVerificationNumber": null,
				"creditCardBIN": null,
				"cvvRequired": false
			},
			"selectedPaymentMode": "BTA",
			"giftCardList": [],
			"savedCardInfo": [{
				"savedCardNickName": "BOGUS",
				"preselectCard": null,
				"creditCardNumber": "XXXX-XXXX-XXXX-9844",
				"creditCardExpMonth": "12",
				"creditCardExpYear": "29",
				"billingZipCode": "75028",
				"creditCardType": "masterCard",
				"creditCardVerificationNumber": null,
				"creditCardBIN": "505429",
				"cvvRequired": false
			}],
			"applePayResponseInfo": null,
			"masterpassResponseInfo": {
				"emailAddress": null,
				"cardType": null,
				"lastDigits": null,
				"creditCardBIN": null
			},
			"masterpassError": false,
			"masterpassErrorMessage": null,
			"paypalEmailAddress": null,
			"expirationMonths": ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
			"expirationYears": ["2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027"]
		},
		"devices": {
			"dueMonthly": 0.0,
			"totalActivationFee": 0.0,
			"deviceTotalDueMonthly": 0.0,
			"dueToday": 0.0,
			"accessories": [{
				"scene7ImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/bose_mie2_mobile_heads?$acc-med$",
				"name": "Bose MIE2i mobile headset",
				"actualPrice": 99.98,
				"originalPrice": 99.98,
				"percentageOffTxt": null,
				"itemTotal": 99.98,
				"quantity": 1,
				"commerceItemId": "S41b5dda5cb299b43e1a044200f169028{ss100}_accessory_1",
				"color": null,
				"size": null,
				"inventoryStatus": "",
				"inventoryAvailableDate": "",
				"prodId": "acc40178",
				"skuId": "sku10179",
				"sorId": "326223-0080",
				"promoMessage": null,
				"hasEcpdDiscount": false,
				"mobileAppImageName": "",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/bose_mie2_mobile_heads?$acc-med$",
				"hasBogoDiscount": false,
				"price": 99.98,
				"discountPrice": 0.0,
				"retailPrice": 99.98,
				"associatedDeviceSkus": null,
				"prodName": "",
				"discounted": false
			}],
			"accessoriesBundle": [],
			"items": [{
				"deviceName": "iPhone&reg; 4s",
				"dueMonthly": "0.00",
				"dueToday": "0.00",
				"upgradeFee": "0.00",
				"originalUpgradeFee": "0.00",
				"activationFee": "30.00",
				"dueTodayOriginal": "0.00",
				"dueMonthlyOriginal": null,
				"dueTodayDiscounted": false,
				"dueMonthlyDiscounted": false,
				"mtn": null,
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iphone_4s_white?$device-med$&fmt=jpeg&wid=75&hei=150",
				"protectionFeature": null,
				"optionalFeatures": [],
				"installmentBalance": "0.00",
				"edgeRetailPrice": "0.00",
				"edgeItemDownPaymentAmount": "0.00",
				"mailInRebateAmount": "0.00",
				"transferredFromMtn": null,
				"devicePromotionList": [],
				"bicOfferApplied": false,
				"bicContractPrice": "0.00",
				"bicDiscountedContractPrice": "0.00",
				"bicAdditionalContractText": null,
				"bicMessageMap": null,
				"edgeUpAmount": 0.0,
				"displayDeviceDueMonthly": 0.0,
				"deviceLACFee": "65.00",
				"manufactureName": "Apple",
				"color": "White",
				"colorCode": "#FFFFFF",
				"size": "32GB",
				"displayName": "iPhone&reg; 4s",
				"contractTerm": "48",
				"edgeUpBuyOutAmount": 0.0,
				"fullRetailPrice": "0.00",
				"alwaysEligibleForUpgrade": false,
				"numberShareDevice": false,
				"activationFeeText": null,
				"numberSharedMtn": null,
				"promoContentText": null,
				"itemOnJaxPlan": true,
				"humCarDetails": null,
				"simDetails": null,
				"imeiId": "99000088000000",
				"displayImeiId": "0000",
				"poboDateLabel": null,
				"promoOfferText": null,
				"promoApplied": false,
				"commerceItemId": "S41b5dda5cb299b43e1a044200f169028{ss100}_device_1",
				"loanTerm": null,
				"sbdHeaderMsg": null,
				"percentage": null,
				"waivedActivationFeePromo": false,
				"flow": "NSO",
				"edgeDevice": false,
				"instantCreditAmount": "0.00",
				"amountAfterInstantCredit": "0.00",
				"disountedInstantCreditAmt": "0.00",
				"accessory": false,
				"eupdevice": false
			}],
			"buddyUpgrade": false
		},
		"accessories": null,
		"selectedShippingType": {
			"type": "SHIPPING",
			"shippingTypeName": "FREE 2 Day by 8pm",
			"price": 0.0,
			"discountPrice": 0.0,
			"estimatedDeliveryDate": "2018-05-14 00:00:00"
		},
		"dueMonthlyView": {
			"title": "Due Monthly (device only)",
			"dueMonthlyPrice": "0.00",
			"items": [{
				"name": "iPhone&reg; 4s",
				"description": "iPhone&reg; 4s",
				"manufacturer": "Apple",
				"color": "White",
				"size": "32GB",
				"priceBreakDown": [],
				"edge": false
			}],
			"tmpMd": null
		},
		"balanceCreditCardAmount": "108.23",
		"cpcOrder": false,
		"totalDueMonthlyPlanAndDevice": "65.00",
		"deviceConfigInfo": {
			"devices": [{
				"deviceId": "S41b5dda5cb299b43e1a044200f169028{ss100}_device_1",
				"deviceName": "iPhone&reg; 4s",
				"deviceSetupMode": null,
				"mtnNumber": null,
				"flow": "NSO",
				"serviceAddress": {
					"firstName": "RAVI",
					"lastName": "MANNING",
					"address1": "8701 LAKEVIEW PKWY STE 111-144",
					"address2": "",
					"city": "Rowlett",
					"state": "TX",
					"zipCode": "75088",
					"emailAddress": "WINOTLVYVO@VZW.COM",
					"phoneNumber": "5207420265"
				},
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iphone_4s_white?$device-med$&fmt=jpeg&wid=75&hei=150",
				"mobileAppImageName": null,
				"npaNxxnumber": "214-287-XXXX",
				"npnxxCustomerSelection": null,
				"npaNxxdetails": null,
				"manufactureName": "Apple",
				"color": "White",
				"size": "32GB",
				"numberShareDevice": false,
				"numberSharedMtn": null,
				"deviceNickName": null,
				"numberSharedDeviceName": null,
				"portInDetails": null
			}],
			"npaNxxdetails": {
				"zipCode": "75088",
				"state": "TX",
				"city": "Rowlett",
				"success": true,
				"mtns": ["214-287-XXXX", "214-288-XXXX", "214-316-XXXX", "214-317-XXXX", "214-406-XXXX", "214-412-XXXX", "214-422-XXXX", "214-437-XXXX", "214-470-XXXX", "214-490-XXXX", "214-531-XXXX", "214-557-XXXX", "214-587-XXXX", "214-601-XXXX", "214-604-XXXX", "214-605-XXXX", "214-608-XXXX", "214-629-XXXX", "214-662-XXXX", "214-681-XXXX", "214-717-XXXX", "214-724-XXXX", "214-766-XXXX", "214-784-XXXX", "214-790-XXXX", "214-846-XXXX", "214-883-XXXX", "214-907-XXXX", "214-918-XXXX", "214-930-XXXX", "214-960-XXXX", "214-984-XXXX"],
				"states": null,
				"cities": null
			},
			"deviceAddressUpdated": false,
			"accessories": null
		},
		"checkoutStates": {
			"shippingAddressRequired": false,
			"shippingAddressChangeRequired": false,
			"shippingMethodRequired": false,
			"paymentRequired": false,
			"pastDuePaymentRequired": false,
			"showPaymentSection": true,
			"showShippingAddress": false,
			"showDeliveryMethod": false,
			"newCard": false,
			"cvvNeeded": false
		},
		"totalEdgeItemDownPaymentAmount": "0.00",
		"totalEdgeUpAmount": "0.00",
		"totalEdgeUpBuyOutAmount": "0.00",
		"multiOrderDetails": null,
		"hasRio": false,
		"splitShipment": false
	}
};