
window.confirmationJSON = 
{
	"output": {
		"title": "You're all set.",
		"subtitle": null,
		"orderId": "67062224303304",
		"estimatedDelivery": "",
		"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/1.3_MV_BuyandUpgrade_ConfirmationPage_Interstital?$device-med$",
		"tradeInStatus": false,
		"confirmationMessage": "Thanks for ordering from verizonwireless.com. Your order receipt is sent to VZW@VZW.COM.",
		"doneButtonText": "Got it",
		"doneButtonLink": "/od/cust/auth/shoplanding/",
		"userNote": "TODO",
		"notNowButtonText": "TODO",
		"notNowButtonLink": "TODO",
		"learnHowButtonText": null,
		"learnHowButtonLink": "/od/cust/auth/learnHow",
		"numberOfDevice": 2,
		"confirmationNumberText": "Confirmation Number",
		"iconicFlow": true,
		"protectionURL": null,
		"accessoriesURL": null,
		"tapFlag": false,
		"cjmTagUrl": null,
		"pepperJamTagUrl": null,
		"selectedPaymentMode": null,
		"confirmationEmail": "VZW@VZW.COM",
		"plans": {
			"dueMonthly": "55.00",
			"dueToday": "0.00",
			"planOnlyDueMonthly": "55.00",
			"items": [{
					"planType": "Beyond Unlimited",
					"lineAccessCharges": [],
					"accountAccess": {
						"name": "Beyond Unlimited",
						"mtn": null,
						"price": "55.00",
						"discountPrice": "0.00",
						"retailPrice": "0.00",
						"hasEcpdDiscount": false,
						"promoMessage": null,
						"originalPrice": "0.00",
						"wasPrice": "0.00",
						"deviceName": null,
						"color": null,
						"size": null,
						"introText": null,
						"smartFamily": false,
						"freeTrial": false,
						"tapfeature": false,
						"instantCreditAmount": "0.00",
						"amountAfterInstantCredit": "0.00",
						"disountedInstantCreditAmt": "0.00"
					},
					"accountLevelFeatures": null,
					"totalMonthlyPlanCost": "55.00",
					"spoBadgeMessage": null,
					"planDisplayName": "Beyond Unlimited",
					"planImageURL": null,
					"planLetter": null,
					"planDescrption": null,
					"planDescription": null,
					"quantity": 0,
					"skuId": null,
					"productId": null,
					"itemAmount": null,
					"itemAmountOriginal": null,
					"dueMonthly": null,
					"dueMonthlyOriginal": null,
					"itemDiscount": null,
					"displayName": null,
					"skuDisplayName": null,
					"listPrice": null,
					"rawTotalAmount": null,
					"planGroupCode": null,
					"autoPayEnabled": false,
					"numberSharePlan": false,
					"planCommerceItemId": null,
					"autoPayPrice": null,
					"autoPayText": null,
					"termsAndConditionKey": null,
					"unitOfMeasure": null,
					"planSize": null
				}, {
					"planType": "5G MOD Plan",
					"lineAccessCharges": null,
					"accountAccess": {
						"name": "5G MOD Plan",
						"mtn": null,
						"price": "0.00",
						"discountPrice": "0.00",
						"retailPrice": "0.00",
						"hasEcpdDiscount": false,
						"promoMessage": null,
						"originalPrice": "0.00",
						"wasPrice": "0.00",
						"deviceName": null,
						"color": null,
						"size": null,
						"introText": null,
						"smartFamily": false,
						"freeTrial": false,
						"tapfeature": false,
						"instantCreditAmount": "0.00",
						"amountAfterInstantCredit": "0.00",
						"disountedInstantCreditAmt": "0.00"
					},
					"accountLevelFeatures": null,
					"totalMonthlyPlanCost": "0.00",
					"spoBadgeMessage": null,
					"planDisplayName": "5G MOD Plan",
					"planImageURL": null,
					"planLetter": null,
					"planDescrption": null,
					"planDescription": null,
					"quantity": 0,
					"skuId": null,
					"productId": null,
					"itemAmount": null,
					"itemAmountOriginal": null,
					"dueMonthly": null,
					"dueMonthlyOriginal": null,
					"itemDiscount": null,
					"displayName": null,
					"skuDisplayName": null,
					"listPrice": null,
					"rawTotalAmount": null,
					"planGroupCode": null,
					"autoPayEnabled": false,
					"numberSharePlan": false,
					"planCommerceItemId": null,
					"autoPayPrice": null,
					"autoPayText": null,
					"termsAndConditionKey": null,
					"unitOfMeasure": null,
					"planSize": null
				}
			],
			"upgradeDevices": [],
			"newDevices": [{
					"name": "moto z<sup>3</sup>",
					"price": "55.00",
					"discountPrice": 0.0,
					"hasEcpdDiscount": false,
					"mtn": null,
					"listPrice": 55.0,
					"deviceLineItemId": "S1026120e8c1acd0f25f73643241e4a0f{d4}_device_1",
					"discountPriceVal": "0.00",
					"planCommerceItemId": null,
					"nickName": null,
					"numberShareDevice": false,
					"featureDropped": false,
					"deviceType": null,
					"trunkMtn": null,
					"changePlanUrl": null,
					"rioDevice": false
				}, {
					"name": "5G Test Device",
					"price": "0.00",
					"discountPrice": 0.0,
					"hasEcpdDiscount": false,
					"mtn": null,
					"listPrice": 0.0,
					"deviceLineItemId": "S1026120e8c1acd0f25f73643241e4a0f{d4}_device_2",
					"discountPriceVal": "0.00",
					"planCommerceItemId": null,
					"nickName": null,
					"numberShareDevice": false,
					"featureDropped": false,
					"deviceType": null,
					"trunkMtn": null,
					"changePlanUrl": null,
					"rioDevice": false
				}
			],
			"existingDevices": null,
			"dueMonthlyPlanWithLAC": null,
			"discountedDueMonthlyPlanWithLAC": null,
			"hasEcpdDiscount": false,
			"totalLineAccessCharges": "0.00"
		},
		"tradeInDevicesDetails": null,
		"tradeInPromoDetails": null,
		"transformedTradeInPromoDetails": null,
		"subOrders": null,
		"comboOrder": false,
		"totalDueToday": "517.20",
		"totalDueMonthly": "0.00",
		"subTotalDueToday": "480.00",
		"securityDepositAmount": "0.00",
		"stateSalesTax": "37.20",
		"stateSalesTaxOriginal": null,
		"stateSalesTaxInstantCredit": null,
		"employeeDiscount": "0.00",
		"pastDueExist": false,
		"pastDueAmountPaid": false,
		"pastDueAmount": "0.00",
		"shippingInfo": {
			"shippingInfoUpdated": false,
			"sameAsBilling": true,
			"ispuEligibleFlag": false,
			"addressInfo": {
				"firstName": "OPQ CORP            ",
				"lastName": "",
				"companyName": null,
				"address1": "3210 SILVERADO TRL N",
				"address2": null,
				"city": "Saint Helena",
				"state": "CA",
				"zipcode": "94574",
				"businessName": null,
				"postalCode": null,
				"email": "VZW@VZW.COM",
				"phoneNumber": "7079182798"
			},
			"contactInfo": {
				"emailAddress": "VZW@VZW.COM",
				"phoneNumber": "7079182798",
				"firstName": "OPQ CORP            ",
				"lastName": "",
				"smsMdn": null,
				"activeSMSCapableMtnList": ["7073268198", "7073390795", "7073396661"]
			},
			"shippingTypesInfo": null,
			"storeDetail": {
				"storeHeader": null,
				"storeName": null,
				"storeAddress": null,
				"deviceAvailable": false,
				"distance": null,
				"appendedStoreTiming": null,
				"longitude": null,
				"storeId": null,
				"netaceLocationCode": null,
				"latitude": null,
				"seoUrlName": null,
				"storeClosingTime": null,
				"directStore": null
			},
			"tradeIn": true,
			"tradeInAddress": {
				"firstName": "OPQ CORP            ",
				"lastName": "",
				"address1": "3210 SILVERADO TRL N",
				"address2": null,
				"city": "Saint Helena",
				"state": "CA",
				"zipcode": "94574",
				"companyName": null
			},
			"nonSddEligibleMsg": null,
			"selectedSDDWindow": null,
			"selectedSDDFormattedWindow": null,
			"poboMessage": null,
			"vendorShippingTypesInfo": null,
			"verizonCommerceItemsNames": ["moto z<sup>3</sup>", "5G Test Device"],
			"vendorCommerceItemsNames": null,
			"vendorShippingOptionExists": false,
			"ispudetailsInfo": {
				"storeAddress": null,
				"storeHours": null,
				"storeId": null,
				"storeName": null,
				"phoneNumber": null,
				"distance": null,
				"totalItems": 0,
				"availItems": 0,
				"latitdude": 0.0,
				"longtitude": 0.0,
				"availItemName": null,
				"directStore": null
			}
		},
		"billingInfo": {
			"billToAccountEligible": true,
			"creditCardZipEditable": false,
			"billingAddress": {
				"firstName": "OPQ CORP            ",
				"lastName": "",
				"businessName": null,
				"zipcode": "94574",
				"state": "CA",
				"address2": null,
				"address1": "3210 SILVERADO TRL N",
				"companyName": null,
				"city": "Saint Helena",
				"sameAsShipping": false
			},
			"masterpass3DSecure": null,
			"billToAccountNumber": "#XXXXXXX-0001",
			"creditCardInfo": {
				"savedCardNickName": null,
				"preselectCard": null,
				"creditCardNumber": null,
				"creditCardExpMonth": null,
				"creditCardExpYear": null,
				"billingZipCode": null,
				"creditCardType": null,
				"creditCardVerificationNumber": null,
				"creditCardBIN": null,
				"cvvRequired": false
			},
			"selectedPaymentMode": "BTA",
			"giftCardList": [],
			"savedCardInfo": null,
			"applePayResponseInfo": null,
			"masterpassResponseInfo": {
				"emailAddress": null,
				"cardType": null,
				"lastDigits": null,
				"creditCardBIN": null,
				"masterpassSelected": false
			},
			"masterpassError": false,
			"masterpassErrorMessage": null,
			"cybersourecPreAuthFailure": false,
			"cybersourecPreAuthFailureErrorMessage": null,
			"paypalEmailAddress": null,
			"expirationMonths": null,
			"expirationYears": null
		},
		"devices": {
			"dueMonthly": 0.0,
			"totalActivationFee": 0.0,
			"deviceTotalDueMonthly": 0.0,
			"dueToday": 480.0,
			"accessories": [],
			"accessoriesBundle": [],
			"globalPromotions": [],
			"items": [{
					"deviceName": "moto z<sup>3</sup>",
					"dueMonthly": "0.00",
					"dueToday": "480.00",
					"upgradeFee": "0.00",
					"originalUpgradeFee": "0.00",
					"activationFee": "30.00",
					"dueTodayOriginal": "480.00",
					"dueMonthlyOriginal": null,
					"dueTodayDiscounted": false,
					"dueMonthlyDiscounted": false,
					"mtn": null,
					"sorId": "MOTXT192917",
					"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/motorola-moto-z3-exclusive-black?$device-med$&fmt=jpeg&wid=75&hei=150",
					"protectionFeature": {
						"name": "Decline Equipment Protection",
						"mtn": null,
						"price": "0.00",
						"discountPrice": "0.00",
						"retailPrice": "0.00",
						"hasEcpdDiscount": false,
						"promoMessage": null,
						"originalPrice": "0.00",
						"wasPrice": "0.00",
						"deviceName": null,
						"color": null,
						"size": null,
						"introText": null,
						"smartFamily": false,
						"freeTrial": false,
						"tapfeature": false,
						"instantCreditAmount": "0.00",
						"amountAfterInstantCredit": "0.00",
						"disountedInstantCreditAmt": "0.00"
					},
					"optionalFeatures": [],
					"installmentBalance": "0.00",
					"edgeRetailPrice": "480.00",
					"edgeItemDownPaymentAmount": "0.00",
					"mailInRebateAmount": "0.00",
					"transferredFromMtn": null,
					"devicePromotionList": [],
					"bicOfferApplied": false,
					"bicContractPrice": "0.00",
					"bicDiscountedContractPrice": "0.00",
					"bicAdditionalContractText": null,
					"bicMessageMap": null,
					"edgeUpAmount": 0.0,
					"displayDeviceDueMonthly": 0.0,
					"deviceLACFee": "0.00",
					"manufactureName": "Motorola",
					"color": "Ceramic Black",
					"colorCode": "#000000",
					"size": "64GB",
					"displayName": "moto z<sup>3</sup>",
					"contractTerm": "0",
					"edgeUpBuyOutAmount": 0.0,
					"fullRetailPrice": "480.00",
					"alwaysEligibleForUpgrade": false,
					"numberShareDevice": false,
					"activationFeeText": null,
					"numberSharedMtn": null,
					"promoContentText": null,
					"itemOnJaxPlan": false,
					"humCarDetails": null,
					"simDetails": null,
					"imeiId": null,
					"displayImeiId": null,
					"poboDateLabel": null,
					"nickName": null,
					"planCommerceItemId": null,
					"displayMtn": null,
					"dppContractDetails": "You'll see the first installment in your next billing cycle. 24 months,0% APR; Retail price: $480.00",
					"optionalDownpaymentInstantCredit": null,
					"twoYearInstantCreditAmount": null,
					"fullRetailInstantCreditAmount": null,
					"twoYearPriceOrginal": null,
					"twoYearPriceInstantCreditApplied": null,
					"instantCreditAppliedAmount": 0.0,
					"instantCreditAdjustedPrice": "$0.00",
					"instantCreditFullRetailPrice": null,
					"tradeinPromoDetails": {
						"tradeInDeviceDppMsg": null,
						"warningMessage": null,
						"tradeInDevicesVos": null,
						"promotionalMessage": null,
						"promotionTooltip": null,
						"promoAmount": null,
						"bicApplied": false
					},
					"numberSharedDeviceName": null,
					"promoOfferText": null,
					"promoApplied": false,
					"commerceItemId": "S1026120e8c1acd0f25f73643241e4a0f{d4}_device_1",
					"loanTerm": null,
					"sbdHeaderMsg": null,
					"percentage": null,
					"waivedActivationFeePromo": false,
					"flow": "AAL",
					"protectionIneligible": false,
					"modDevice": false,
					"dueMonthlyTotalDuration": null,
					"accessory": false,
					"eupdevice": false,
					"edgeDevice": false,
					"instantCreditAmount": "0.00",
					"amountAfterInstantCredit": "0.00",
					"disountedInstantCreditAmt": "0.00"
				}, {
					"deviceName": "5G Test Device",
					"dueMonthly": "0.00",
					"dueToday": "0.00",
					"upgradeFee": "0.00",
					"originalUpgradeFee": "0.00",
					"activationFee": "0.00",
					"dueTodayOriginal": "0.00",
					"dueMonthlyOriginal": null,
					"dueTodayDiscounted": false,
					"dueMonthlyDiscounted": false,
					"mtn": null,
					"sorId": "5GTESTDEVICE",
					"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/generic_phone?$device-thumb$",
					"protectionFeature": null,
					"optionalFeatures": [],
					"installmentBalance": "0.00",
					"edgeRetailPrice": "0.00",
					"edgeItemDownPaymentAmount": "0.00",
					"mailInRebateAmount": "0.00",
					"transferredFromMtn": null,
					"devicePromotionList": [],
					"bicOfferApplied": false,
					"bicContractPrice": "0.00",
					"bicDiscountedContractPrice": "0.00",
					"bicAdditionalContractText": null,
					"bicMessageMap": null,
					"edgeUpAmount": 0.0,
					"displayDeviceDueMonthly": 0.0,
					"deviceLACFee": "0.00",
					"manufactureName": "Motorola",
					"color": null,
					"colorCode": null,
					"size": null,
					"displayName": "5G Test Device",
					"contractTerm": "0",
					"edgeUpBuyOutAmount": 0.0,
					"fullRetailPrice": "0.00",
					"alwaysEligibleForUpgrade": false,
					"numberShareDevice": false,
					"activationFeeText": null,
					"numberSharedMtn": null,
					"promoContentText": null,
					"itemOnJaxPlan": false,
					"humCarDetails": null,
					"simDetails": null,
					"imeiId": null,
					"displayImeiId": null,
					"poboDateLabel": null,
					"nickName": null,
					"planCommerceItemId": null,
					"displayMtn": null,
					"dppContractDetails": "You'll see the first installment in your next billing cycle. 24 months,0% APR; Retail price: $0.00",
					"optionalDownpaymentInstantCredit": null,
					"twoYearInstantCreditAmount": null,
					"fullRetailInstantCreditAmount": null,
					"twoYearPriceOrginal": null,
					"twoYearPriceInstantCreditApplied": null,
					"instantCreditAppliedAmount": 0.0,
					"instantCreditAdjustedPrice": "$0.00",
					"instantCreditFullRetailPrice": null,
					"tradeinPromoDetails": {
						"tradeInDeviceDppMsg": null,
						"warningMessage": null,
						"tradeInDevicesVos": null,
						"promotionalMessage": null,
						"promotionTooltip": null,
						"promoAmount": null,
						"bicApplied": false
					},
					"numberSharedDeviceName": null,
					"promoOfferText": null,
					"promoApplied": false,
					"commerceItemId": "S1026120e8c1acd0f25f73643241e4a0f{d4}_device_2",
					"loanTerm": null,
					"sbdHeaderMsg": null,
					"percentage": null,
					"waivedActivationFeePromo": false,
					"flow": "AAL",
					"protectionIneligible": false,
					"modDevice": true,
					"dueMonthlyTotalDuration": "after 3 months",
					"accessory": false,
					"eupdevice": false,
					"edgeDevice": false,
					"instantCreditAmount": "0.00",
					"amountAfterInstantCredit": "0.00",
					"disountedInstantCreditAmt": "0.00"
				}
			],
			"buddyUpgrade": false
		},
		"accessories": null,
		"selectedShippingType": {
			"type": "SHIPPING",
			"shippingTypeName": "FREE 2 Day by 8pm",
			"price": 0.0,
			"discountPrice": 0.0,
			"estimatedDeliveryDate": null,
			"selectedFormattedWindow": null
		},
		"balanceCreditCardAmount": "517.20",
		"cpcOrder": false,
		"totalDueMonthlyPlanAndDevice": "55.00",
		"deviceConfigInfo": {
			"devices": [{
					"deviceId": "S1026120e8c1acd0f25f73643241e4a0f{d4}_device_1",
					"deviceName": "moto z<sup>3</sup>",
					"deviceSetupMode": null,
					"mtnNumber": null,
					"flow": "AAL",
					"serviceAddress": {
						"firstName": "OPQ CORP            ",
						"lastName": "",
						"address1": "3210 SILVERADO TRL N",
						"address2": "",
						"city": "Saint Helena",
						"state": "CA",
						"zipCode": "94574",
						"emailAddress": "VZW@VZW.COM",
						"phoneNumber": "7079182798"
					},
					"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/motorola-moto-z3-exclusive-black?$device-med$&fmt=jpeg&wid=75&hei=150",
					"mobileAppImageName": null,
					"npaNxxnumber": "440-781-XXXX",
					"npnxxCustomerSelection": null,
					"npaNxxdetails": null,
					"manufactureName": "Motorola",
					"color": "Ceramic Black",
					"size": "64GB",
					"numberShareDevice": false,
					"numberSharedMtn": null,
					"deviceNickName": null,
					"numberSharedDeviceName": null,
					"displayImeiId": null,
					"modDevice": false,
					"dueMonthlyTotalDuration": null,
					"portInDetails": null
				}, {
					"deviceId": "S1026120e8c1acd0f25f73643241e4a0f{d4}_device_2",
					"deviceName": "5G Test Device",
					"deviceSetupMode": null,
					"mtnNumber": null,
					"flow": "AAL",
					"serviceAddress": {
						"firstName": "OPQ CORP            ",
						"lastName": "",
						"address1": "3210 SILVERADO TRL N",
						"address2": "",
						"city": "Saint Helena",
						"state": "CA",
						"zipCode": "94574",
						"emailAddress": "VZW@VZW.COM",
						"phoneNumber": "7079182798"
					},
					"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/generic_phone?$device-thumb$",
					"mobileAppImageName": null,
					"npaNxxnumber": "440-781-XXXX",
					"npnxxCustomerSelection": null,
					"npaNxxdetails": null,
					"manufactureName": "Motorola",
					"color": null,
					"size": null,
					"numberShareDevice": false,
					"numberSharedMtn": null,
					"deviceNickName": null,
					"numberSharedDeviceName": null,
					"displayImeiId": null,
					"modDevice": true,
					"dueMonthlyTotalDuration": "after 3 months",
					"portInDetails": null
				}
			],
			"npaNxxdetails": {
				"zipCode": "94574",
				"state": "CA",
				"city": "Saint Helena",
				"success": true,
				"mtns": ["440-781-XXXX", "440-785-XXXX", "440-823-XXXX", "440-829-XXXX", "440-840-XXXX", "440-856-XXXX", "440-862-XXXX", "440-897-XXXX"],
				"states": null,
				"cities": null
			},
			"deviceAddressUpdated": false,
			"accessories": null
		},
		"checkoutStates": {
			"shippingAddressRequired": false,
			"shippingAddressChangeRequired": false,
			"poBoxShippingAddress": false,
			"shippingAddressValidationError": false,
			"shippingMethodRequired": false,
			"paymentRequired": false,
			"pastDuePaymentRequired": false,
			"showPaymentSection": true,
			"showShippingAddress": true,
			"showDeliveryMethod": true,
			"newCard": false,
			"cvvNeeded": true,
			"contactInfoRequired": false,
			"instantCreditAllocationsChanged": false,
			"instantCreditOrder": false,
			"tradesExceedItems": false,
			"creditCardZipEditable": false,
			"vzProtect": false,
			"vzProtectMultiDevice": false,
			"batteryShippingNotAllowedStates": false,
			"disableSubmitOrderForOPALUser": false
		},
		"totalEdgeItemDownPaymentAmount": "0.00",
		"totalEdgeUpAmount": "0.00",
		"totalEdgeUpBuyOutAmount": "0.00",
		"creditApplicationNumber": "590970247",
		"locationCode": "W233601",
		"selectedVendorShippingType": null,
		"standaloneAccessories": false,
		"accountLevelDiscountList": null,
		"militaryDiscInfoText": null,
		"militaryInfoURL": null,
		"recAccessoriesEnabled": true,
		"accessoryGWURL": "/od/cust/auth/accessories/",
		"instantCreditDetails": {
			"totalInstantCredit": null,
			"optionalDownPayment": null,
			"twoYearDevicesInstantCredit": null,
			"fullRetailInstantCredit": null,
			"accessoriesInsantCredit": null,
			"taxesInstantCredit": null,
			"accountCredit": null
		},
		"bicRepresentationChangeEnabled": true,
		"appleMusicEnrollUrl": "https://myvpostpay.verizonwireless.com/ui/acct/secure/appmusic",
		"multiOrderDetails": null,
		"numberShareRequiredDevice": false,
		"splitShipment": false,
		"isHLLPlanInOrder": false
	}
};


/*
{
	"output": {
	  "title": "You're all set.",
	  "subtitle": null,
	  "orderId": "924042362448974",
	  "estimatedDelivery": "",
	  "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/1.3_MV_BuyandUpgrade_ConfirmationPage_Interstital?$device-med$",
	  "tradeInStatus": false,
	  "confirmationMessage": "Thanks for ordering from verizonwireless.com. Your order receipt is sent to WINOTLVYVO@VZW.COM.",
	  "doneButtonText": "Got it",
	  "doneButtonLink": "/od/cust/auth/shoplanding/",
	  "userNote": "TODO",
	  "notNowButtonText": "TODO",
	  "notNowButtonLink": "TODO",
	  "learnHowButtonText": null,
	  "learnHowButtonLink": "/od/cust/auth/learnHow",
	  "numberOfDevice": 2,
	  "confirmationNumberText": "Confirmation Number",
	  "iconicFlow": true,
	  "protectionURL": null,
	  "accessoriesURL": null,
	  "tapFlag": false,
	  "cjmTagUrl": null,
	  "pepperJamTagUrl": null,
	  "selectedPaymentMode": null,
	  "confirmationEmail": "WINOTLVYVO@VZW.COM",
	  "plans": {
		"dueMonthly": "195.00",
		"dueToday": "0.00",
		"planOnlyDueMonthly": "195.00",
		"items": [
		  {
			"planType": "Beyond Unlimited",
			"lineAccessCharges": [
			  {
				"name": "Apple iPhone&reg; 7 Plus 32GB in Black",
				"mtn": "5125579423",
				"price": "65.00",
				"discountPrice": "0.00",
				"retailPrice": "0.00",
				"hasEcpdDiscount": false,
				"promoMessage": null,
				"originalPrice": "0.00",
				"wasPrice": "0.00",
				"deviceName": "iPhone&reg; 7 Plus",
				"color": "Black",
				"size": "32GB",
				"instantCreditAmount": "0.00",
				"amountAfterInstantCredit": "0.00",
				"disountedInstantCreditAmt": "0.00"
			  },
			  {
				"name": "Google Pixel XL, Phone by Google 32GB in Quite Black",
				"mtn": null,
				"price": "65.00",
				"discountPrice": "0.00",
				"retailPrice": "0.00",
				"hasEcpdDiscount": false,
				"promoMessage": null,
				"originalPrice": "0.00",
				"wasPrice": "0.00",
				"deviceName": "Pixel XL, Phone by Google",
				"color": "Quite Black",
				"size": "32GB",
				"instantCreditAmount": "0.00",
				"amountAfterInstantCredit": "0.00",
				"disountedInstantCreditAmt": "0.00"
			  }
			],
			"accountAccess": {
			  "name": "Beyond Unlimited",
			  "mtn": null,
			  "price": "195.00",
			  "discountPrice": "0.00",
			  "retailPrice": "0.00",
			  "hasEcpdDiscount": false,
			  "promoMessage": null,
			  "originalPrice": "0.00",
			  "wasPrice": "0.00",
			  "deviceName": null,
			  "color": null,
			  "size": null,
			  "instantCreditAmount": "0.00",
			  "amountAfterInstantCredit": "0.00",
			  "disountedInstantCreditAmt": "0.00"
			},
			"accountLevelFeatures": null,
			"totalMonthlyPlanCost": "195.00",
			"spoBadgeMessage": null,
			"planDisplayName": "Beyond Unlimited",
			"planImageURL": null,
			"planLetter": null,
			"planDescrption": null,
			"planDescription": null
		  }
		],
		"upgradeDevices": [
		  {
			"name": "iPhone&reg; 7 Plus",
			"price": "65.00",
			"discountPrice": 0.0,
			"hasEcpdDiscount": false,
			"mtn": "5125579423",
			"listPrice": 65.0,
			"deviceLineItemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_device_1",
			"discountPriceVal": "0.00"
		  }
		],
		"newDevices": [
		  {
			"name": "Pixel XL, Phone by Google",
			"price": "65.00",
			"discountPrice": 0.0,
			"hasEcpdDiscount": false,
			"mtn": null,
			"listPrice": 65.0,
			"deviceLineItemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_device_2",
			"discountPriceVal": "0.00"
		  }
		],
		"existingDevices": [
		  {
			"name": "LG Octane&trade;",
			"price": "65.00",
			"discountPrice": 0.0,
			"hasEcpdDiscount": false,
			"mtn": "2108340918",
			"listPrice": 65.0,
			"deviceLineItemId": null,
			"discountPriceVal": "0.00"
		  }
		],
		"dueMonthlyPlanWithLAC": "195.00",
		"discountedDueMonthlyPlanWithLAC": "0.00",
		"hasEcpdDiscount": false,
		"totalLineAccessCharges": "130.00"
	  },
	  "featureList": [
		{
		  "id": "Se074cbdce387b0c9837c665fbe1306e4{d3}_feature_1",
		  "quantity": 1,
		  "type": "INSUR,I",
		  "skuId": "sku2880128",
		  "productId": "sfo80072",
		  "sorId": "85915",
		  "itemAmount": 0.0,
		  "itemAmountOriginal": 13.0,
		  "dueMonthly": 13.0,
		  "dueMonthlyOriginal": null,
		  "itemDiscount": 0.0,
		  "displayName": "Total Mobile Protection",
		  "skuDisplayName": null,
		  "listPrice": 13.0,
		  "rawTotalAmount": 0.0,
		  "pricingDetails": [
			{
			  "pricingAdjustmentId": null,
			  "itemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_feature_1",
			  "orderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}",
			  "offerId": null,
			  "offerAmount": 0.0,
			  "description": "List Price description",
			  "offerType": null,
			  "priceListId": null,
			  "listPrice": 13.0,
			  "offerName": null,
			  "creationDate": 1525952151583,
			  "lastModifiedDate": 1525952151583,
			  "version": 1
			}
		  ],
		  "orderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}",
		  "version": 1,
		  "delete": false,
		  "inventoryLevel": 0,
		  "taxDetails": null,
		  "itemTaxes": 0.0,
		  "deviceLineItemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_device_1",
		  "featureCharge": 0.0,
		  "featureType": "INS",
		  "lastModifiedDate": 1525952147261
		},
		{
		  "id": "Se074cbdce387b0c9837c665fbe1306e4{d3}_feature_2",
		  "quantity": 1,
		  "type": "NAF,VMDF",
		  "skuId": "sku2560179",
		  "productId": "sfo80079",
		  "sorId": "85433",
		  "itemAmount": 0.0,
		  "itemAmountOriginal": 0.0,
		  "dueMonthly": 0.0,
		  "dueMonthlyOriginal": null,
		  "itemDiscount": 0.0,
		  "displayName": "Phone Plan",
		  "skuDisplayName": null,
		  "listPrice": 0.0,
		  "rawTotalAmount": 0.0,
		  "pricingDetails": [
			{
			  "pricingAdjustmentId": null,
			  "itemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_feature_2",
			  "orderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}",
			  "offerId": null,
			  "offerAmount": 0.0,
			  "description": "List Price description",
			  "offerType": null,
			  "priceListId": null,
			  "listPrice": 0.0,
			  "offerName": null,
			  "creationDate": 1525952151583,
			  "lastModifiedDate": 1525952151583,
			  "version": 1
			}
		  ],
		  "orderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}",
		  "version": 1,
		  "delete": false,
		  "inventoryLevel": 0,
		  "taxDetails": null,
		  "itemTaxes": 0.0,
		  "deviceLineItemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_device_1",
		  "featureCharge": 0.0,
		  "featureType": "LAC",
		  "lastModifiedDate": 1525952147263
		},
		{
		  "id": "Se074cbdce387b0c9837c665fbe1306e4{d3}_feature_3",
		  "quantity": 1,
		  "type": "NAF,VMDF",
		  "skuId": "sku2560179",
		  "productId": "sfo80079",
		  "sorId": "85433",
		  "itemAmount": 0.0,
		  "itemAmountOriginal": 0.0,
		  "dueMonthly": 0.0,
		  "dueMonthlyOriginal": null,
		  "itemDiscount": 0.0,
		  "displayName": "Phone Plan",
		  "skuDisplayName": null,
		  "listPrice": 0.0,
		  "rawTotalAmount": 0.0,
		  "pricingDetails": [
			{
			  "pricingAdjustmentId": null,
			  "itemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_feature_3",
			  "orderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}",
			  "offerId": null,
			  "offerAmount": 0.0,
			  "description": "List Price description",
			  "offerType": null,
			  "priceListId": null,
			  "listPrice": 0.0,
			  "offerName": null,
			  "creationDate": 1525952151583,
			  "lastModifiedDate": 1525952151583,
			  "version": 1
			}
		  ],
		  "orderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}",
		  "version": 1,
		  "delete": false,
		  "inventoryLevel": 0,
		  "taxDetails": null,
		  "itemTaxes": 0.0,
		  "deviceLineItemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_device_2",
		  "featureCharge": 0.0,
		  "featureType": "LAC",
		  "lastModifiedDate": 1525952147266
		},
		{
		  "id": "Se074cbdce387b0c9837c665fbe1306e4{d3}_feature_4",
		  "quantity": 1,
		  "type": null,
		  "skuId": "sku2880234",
		  "productId": "spo1640003",
		  "sorId": "1167",
		  "itemAmount": 0.0,
		  "itemAmountOriginal": 39.0,
		  "dueMonthly": 39.0,
		  "dueMonthlyOriginal": null,
		  "itemDiscount": 0.0,
		  "displayName": "Total Mobile Protection Multi-Device",
		  "skuDisplayName": null,
		  "listPrice": 39.0,
		  "rawTotalAmount": 0.0,
		  "pricingDetails": [
			{
			  "pricingAdjustmentId": null,
			  "itemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_feature_4",
			  "orderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}",
			  "offerId": null,
			  "offerAmount": 0.0,
			  "description": "List Price description",
			  "offerType": null,
			  "priceListId": null,
			  "listPrice": 39.0,
			  "offerName": null,
			  "creationDate": 1525952151583,
			  "lastModifiedDate": 1525952151583,
			  "version": 1
			}
		  ],
		  "orderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}",
		  "version": 1,
		  "delete": false,
		  "inventoryLevel": 0,
		  "taxDetails": null,
		  "itemTaxes": 0.0,
		  "deviceLineItemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_device_2",
		  "featureCharge": 0.0,
		  "featureType": "SPO",
		  "lastModifiedDate": 1525952147267
		}
	  ],
	  "accessoryList": [
		{
		  "id": "Se074cbdce387b0c9837c665fbe1306e4{d3}_accessory_1",
		  "quantity": 1,
		  "type": null,
		  "skuId": "sku1760050",
		  "productId": "acc5240003",
		  "sorId": "S5556LL/A",
		  "itemAmount": 129.97,
		  "itemAmountOriginal": 0.0,
		  "dueMonthly": 0.0,
		  "dueMonthlyOriginal": null,
		  "itemDiscount": 0.0,
		  "displayName": "AppleCare+ for iPhone 8, 7, 6s, or 6",
		  "skuDisplayName": "AppleCare+ for iPhone 8, 7, 6s, or 6",
		  "listPrice": 129.97,
		  "rawTotalAmount": 129.97,
		  "pricingDetails": [
			{
			  "pricingAdjustmentId": null,
			  "itemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_accessory_1",
			  "orderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}",
			  "offerId": null,
			  "offerAmount": 0.0,
			  "description": "List Price description",
			  "offerType": null,
			  "priceListId": null,
			  "listPrice": 129.97,
			  "offerName": null,
			  "creationDate": 1525952151583,
			  "lastModifiedDate": 1525952151583,
			  "version": 1
			}
		  ],
		  "orderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}",
		  "version": 1,
		  "delete": false,
		  "inventoryLevel": 1000,
		  "taxDetails": [
			{
			  "taxLineItemId": null,
			  "lineItemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_accessory_1",
			  "itemType": "accessory",
			  "sorSkuId": "S5556LL/A",
			  "taxType": "taxes_fees",
			  "taxAmount": 8.12,
			  "taxDescription": "TX State Sales Tax",
			  "version": 0,
			  "orderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}",
			  "createdDate": 1525951784085
			},
			{
			  "taxLineItemId": null,
			  "lineItemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_accessory_1",
			  "itemType": "accessory",
			  "sorSkuId": "S5556LL/A",
			  "taxType": "taxes_fees",
			  "taxAmount": 1.3,
			  "taxDescription": "TX Local Sales Tax",
			  "version": 0,
			  "orderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}",
			  "createdDate": 1525951784085
			},
			{
			  "taxLineItemId": null,
			  "lineItemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_accessory_1",
			  "itemType": "accessory",
			  "sorSkuId": "S5556LL/A",
			  "taxType": "taxes_fees",
			  "taxAmount": 1.3,
			  "taxDescription": "TX Local Sales Tax",
			  "version": 0,
			  "orderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}",
			  "createdDate": 1525951784085
			}
		  ],
		  "itemTaxes": 10.72,
		  "deviceLineItemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_device_1",
		  "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/applecareplus-cc3000?$acc-med$",
		  "bogoType": null,
		  "recycleStateInd": null,
		  "color": null,
		  "size": null,
		  "capacity": null,
		  "lastModifiedDate": 1525951641480,
		  "deviceManufacturerName": "Apple",
		  "accessoryType": "INLINE_ACCESSORIES",
		  "ispuEligibleFlag": true,
		  "bundleSkuLineItems": null,
		  "bundleDesciption": null,
		  "vzwSbdOfferlist": [
			
		  ],
		  "promotions": null,
		  "purchasePath": "EUP",
		  "appleCare": true,
		  "expectedShippingDate": null,
		  "shipCommitInd": null,
		  "sameDayDelivery": false,
		  "recycleCreditAllocatedAmount": 0.0,
		  "ecpdItemAmount": null,
		  "ecpdItemDiscount": 0.0,
		  "standaloneaccessory": false,
		  "batteryAccessory": false,
		  "accSeoUrl": ""
		},
		{
		  "id": "Se074cbdce387b0c9837c665fbe1306e4{d3}_accessory_2",
		  "quantity": 1,
		  "type": null,
		  "skuId": "sku2920042",
		  "productId": "12100003",
		  "sorId": null,
		  "itemAmount": 214.95999999999998,
		  "itemAmountOriginal": 0.0,
		  "dueMonthly": 0.0,
		  "dueMonthlyOriginal": null,
		  "itemDiscount": 0.0,
		  "displayName": "Presidio Clear Power, Protection, & Stereo Bundle for iPhone 8 Plus",
		  "skuDisplayName": null,
		  "listPrice": 214.95999999999998,
		  "rawTotalAmount": 214.95999999999998,
		  "pricingDetails": [
			{
			  "pricingAdjustmentId": null,
			  "itemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_accessory_2",
			  "orderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}",
			  "offerId": null,
			  "offerAmount": 0.0,
			  "description": "List Price description",
			  "offerType": null,
			  "priceListId": null,
			  "listPrice": 214.95999999999998,
			  "offerName": null,
			  "creationDate": 1525952151583,
			  "lastModifiedDate": 1525952151583,
			  "version": 1
			}
		  ],
		  "orderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}",
		  "version": 1,
		  "delete": false,
		  "inventoryLevel": 0,
		  "taxDetails": null,
		  "itemTaxes": 0.0,
		  "deviceLineItemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_device_1",
		  "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone-8-plus-7-15960-ga-enhanced-bundle-iset?$acc-med$",
		  "bogoType": null,
		  "recycleStateInd": null,
		  "color": null,
		  "size": null,
		  "capacity": null,
		  "lastModifiedDate": 1525951641530,
		  "deviceManufacturerName": null,
		  "accessoryType": "BUNDLE_ACCESSORIES",
		  "ispuEligibleFlag": true,
		  "bundleSkuLineItems": [
			{
			  "brand": "",
			  "displayName": "Presidio Clear for iPhone 8 Plus",
			  "capacity": 10,
			  "productID": "sku2640024",
			  "skuDetails": [
				{
				  "id": "sku2640024",
				  "quantity": 1,
				  "type": null,
				  "skuId": "sku2640024",
				  "productId": null,
				  "sorId": "103124-5085",
				  "itemAmount": 44.99,
				  "itemAmountOriginal": 0.0,
				  "dueMonthly": 0.0,
				  "dueMonthlyOriginal": null,
				  "itemDiscount": 0.0,
				  "displayName": "Presidio Clear for iPhone 8 Plus/7 Plus/6s Plus/6 Plus",
				  "skuDisplayName": "Speck Presidio Clear for iP8/iP7/iP6s/iP6 Plus - Clear/Clear",
				  "listPrice": 44.99,
				  "rawTotalAmount": 44.99,
				  "pricingDetails": [
					{
					  "pricingAdjustmentId": null,
					  "itemId": "sku2640024",
					  "orderId": null,
					  "offerId": null,
					  "offerAmount": 0.0,
					  "description": "List Price description",
					  "offerType": null,
					  "priceListId": null,
					  "listPrice": 44.99,
					  "offerName": null,
					  "creationDate": 1525952151583,
					  "lastModifiedDate": 1525952151583,
					  "version": 1
					}
				  ],
				  "orderId": null,
				  "version": 0,
				  "delete": false,
				  "inventoryLevel": 0,
				  "taxDetails": [
					{
					  "taxLineItemId": null,
					  "lineItemId": "sku2640024",
					  "itemType": "accessory",
					  "sorSkuId": "103124-5085",
					  "taxType": "taxes_fees",
					  "taxAmount": 0.45,
					  "taxDescription": "TX Local Sales Tax",
					  "version": 0,
					  "orderId": null,
					  "createdDate": 1525951784085
					},
					{
					  "taxLineItemId": null,
					  "lineItemId": "sku2640024",
					  "itemType": "accessory",
					  "sorSkuId": "103124-5085",
					  "taxType": "taxes_fees",
					  "taxAmount": 2.82,
					  "taxDescription": "TX State Sales Tax",
					  "version": 0,
					  "orderId": null,
					  "createdDate": 1525951784085
					},
					{
					  "taxLineItemId": null,
					  "lineItemId": "sku2640024",
					  "itemType": "accessory",
					  "sorSkuId": "103124-5085",
					  "taxType": "taxes_fees",
					  "taxAmount": 0.45,
					  "taxDescription": "TX Local Sales Tax",
					  "version": 0,
					  "orderId": null,
					  "createdDate": 1525951784085
					}
				  ],
				  "itemTaxes": 3.72,
				  "deviceLineItemId": null,
				  "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/speck-presidio-clear-ip7-ip6s-ip6-plus-clear-clear-103124-5085-iset?$acc-med$",
				  "bogoType": null,
				  "recycleStateInd": null,
				  "color": false,
				  "size": null,
				  "capacity": null,
				  "lastModifiedDate": null,
				  "deviceManufacturerName": null,
				  "accessoryType": null,
				  "ispuEligibleFlag": false,
				  "bundleSkuLineItems": null,
				  "bundleDesciption": null,
				  "vzwSbdOfferlist": [
					
				  ],
				  "promotions": null,
				  "purchasePath": null,
				  "appleCare": false,
				  "expectedShippingDate": null,
				  "shipCommitInd": null,
				  "sameDayDelivery": false,
				  "recycleCreditAllocatedAmount": 0.0,
				  "ecpdItemAmount": null,
				  "ecpdItemDiscount": 0.0,
				  "standaloneaccessory": false,
				  "batteryAccessory": false,
				  "accSeoUrl": null,
				  "name": "Presidio Clear for iPhone 8 Plus/7 Plus/6s Plus/6 Plus",
				  "price": "44.99",
				  "discountedPrice": "34.99",
				  "preSelected": false,
				  "comingSoonAcc": false,
				  "inCart": false,
				  "learnMoreLink": "/od/cust/auth/accessoryDetails/?accProdId=acc8560024",
				  "discount_price": null,
				  "available": false
				}
			  ]
			},
			{
			  "brand": "",
			  "displayName": "ZAGG InvisibleShield Glass+ Screen Protector for iPhone 8 Plus",
			  "capacity": 10,
			  "productID": "sku2120065",
			  "skuDetails": [
				{
				  "id": "sku2120065",
				  "quantity": 1,
				  "type": null,
				  "skuId": "sku2120065",
				  "productId": null,
				  "sorId": "I7LLGC-F00",
				  "itemAmount": 39.99,
				  "itemAmountOriginal": 0.0,
				  "dueMonthly": 0.0,
				  "dueMonthlyOriginal": null,
				  "itemDiscount": 0.0,
				  "displayName": "InvisibleShield Glass+ Screen Protector for iPhone 8 Plus/7 Plus/6s Plus/6 Plus",
				  "skuDisplayName": "ZAGG InvisibleShield Glass for iP8/iP7/iP6/iP6s Plus",
				  "listPrice": 39.99,
				  "rawTotalAmount": 39.99,
				  "pricingDetails": [
					{
					  "pricingAdjustmentId": null,
					  "itemId": "sku2120065",
					  "orderId": null,
					  "offerId": null,
					  "offerAmount": 0.0,
					  "description": "List Price description",
					  "offerType": null,
					  "priceListId": null,
					  "listPrice": 39.99,
					  "offerName": null,
					  "creationDate": 1525952151583,
					  "lastModifiedDate": 1525952151583,
					  "version": 1
					}
				  ],
				  "orderId": null,
				  "version": 0,
				  "delete": false,
				  "inventoryLevel": 0,
				  "taxDetails": [
					{
					  "taxLineItemId": null,
					  "lineItemId": "sku2120065",
					  "itemType": "accessory",
					  "sorSkuId": "I7LLGC-F00",
					  "taxType": "taxes_fees",
					  "taxAmount": 0.4,
					  "taxDescription": "TX Local Sales Tax",
					  "version": 0,
					  "orderId": null,
					  "createdDate": 1525951784085
					},
					{
					  "taxLineItemId": null,
					  "lineItemId": "sku2120065",
					  "itemType": "accessory",
					  "sorSkuId": "I7LLGC-F00",
					  "taxType": "taxes_fees",
					  "taxAmount": 2.49,
					  "taxDescription": "TX State Sales Tax",
					  "version": 0,
					  "orderId": null,
					  "createdDate": 1525951784085
					},
					{
					  "taxLineItemId": null,
					  "lineItemId": "sku2120065",
					  "itemType": "accessory",
					  "sorSkuId": "I7LLGC-F00",
					  "taxType": "taxes_fees",
					  "taxAmount": 0.4,
					  "taxDescription": "TX Local Sales Tax",
					  "version": 0,
					  "orderId": null,
					  "createdDate": 1525951784085
					}
				  ],
				  "itemTaxes": 3.29,
				  "deviceLineItemId": null,
				  "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/zagg-invisibleshield-glass-iphone-6-plus-iset-ippglc-f00?$acc-med$",
				  "bogoType": null,
				  "recycleStateInd": null,
				  "color": false,
				  "size": null,
				  "capacity": null,
				  "lastModifiedDate": null,
				  "deviceManufacturerName": null,
				  "accessoryType": null,
				  "ispuEligibleFlag": false,
				  "bundleSkuLineItems": null,
				  "bundleDesciption": null,
				  "vzwSbdOfferlist": [
					
				  ],
				  "promotions": null,
				  "purchasePath": null,
				  "appleCare": false,
				  "expectedShippingDate": null,
				  "shipCommitInd": null,
				  "sameDayDelivery": false,
				  "recycleCreditAllocatedAmount": 0.0,
				  "ecpdItemAmount": null,
				  "ecpdItemDiscount": 0.0,
				  "standaloneaccessory": false,
				  "batteryAccessory": false,
				  "accSeoUrl": null,
				  "name": "InvisibleShield Glass+ Screen Protector for iPhone 8 Plus/7 Plus/6s Plus/6 Plus",
				  "price": "39.99",
				  "discountedPrice": "32.5",
				  "preSelected": false,
				  "comingSoonAcc": false,
				  "inCart": false,
				  "learnMoreLink": "/od/cust/auth/accessoryDetails/?accProdId=acc6640065",
				  "discount_price": null,
				  "available": false
				}
			  ]
			},
			{
			  "brand": "",
			  "displayName": "Lightning Wall Charger",
			  "capacity": 10,
			  "productID": "sku2180059",
			  "skuDetails": [
				{
				  "id": "sku2180059",
				  "quantity": 1,
				  "type": null,
				  "skuId": "sku2180059",
				  "productId": null,
				  "sorId": "TVL24LGHT-M",
				  "itemAmount": 29.99,
				  "itemAmountOriginal": 0.0,
				  "dueMonthly": 0.0,
				  "dueMonthlyOriginal": null,
				  "itemDiscount": 0.0,
				  "displayName": "Lightning Wall Charger",
				  "skuDisplayName": "Verizon 2.4A Apple Lightning Travel Charger",
				  "listPrice": 29.99,
				  "rawTotalAmount": 29.99,
				  "pricingDetails": [
					{
					  "pricingAdjustmentId": null,
					  "itemId": "sku2180059",
					  "orderId": null,
					  "offerId": null,
					  "offerAmount": 0.0,
					  "description": "List Price description",
					  "offerType": null,
					  "priceListId": null,
					  "listPrice": 29.99,
					  "offerName": null,
					  "creationDate": 1525952151583,
					  "lastModifiedDate": 1525952151583,
					  "version": 1
					}
				  ],
				  "orderId": null,
				  "version": 0,
				  "delete": false,
				  "inventoryLevel": 0,
				  "taxDetails": [
					{
					  "taxLineItemId": null,
					  "lineItemId": "sku2180059",
					  "itemType": "accessory",
					  "sorSkuId": "TVL24LGHT-M",
					  "taxType": "taxes_fees",
					  "taxAmount": 0.3,
					  "taxDescription": "TX Local Sales Tax",
					  "version": 0,
					  "orderId": null,
					  "createdDate": 1525951784085
					},
					{
					  "taxLineItemId": null,
					  "lineItemId": "sku2180059",
					  "itemType": "accessory",
					  "sorSkuId": "TVL24LGHT-M",
					  "taxType": "taxes_fees",
					  "taxAmount": 0.3,
					  "taxDescription": "TX Local Sales Tax",
					  "version": 0,
					  "orderId": null,
					  "createdDate": 1525951784085
					},
					{
					  "taxLineItemId": null,
					  "lineItemId": "sku2180059",
					  "itemType": "accessory",
					  "sorSkuId": "TVL24LGHT-M",
					  "taxType": "taxes_fees",
					  "taxAmount": 1.88,
					  "taxDescription": "TX State Sales Tax",
					  "version": 0,
					  "orderId": null,
					  "createdDate": 1525951784085
					}
				  ],
				  "itemTaxes": 2.48,
				  "deviceLineItemId": null,
				  "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/vzw-2-4a-apple-lightning-travel-charger-tvl24lght-m-iset?$acc-med$",
				  "bogoType": null,
				  "recycleStateInd": null,
				  "color": false,
				  "size": null,
				  "capacity": null,
				  "lastModifiedDate": null,
				  "deviceManufacturerName": null,
				  "accessoryType": null,
				  "ispuEligibleFlag": false,
				  "bundleSkuLineItems": null,
				  "bundleDesciption": null,
				  "vzwSbdOfferlist": [
					
				  ],
				  "promotions": null,
				  "purchasePath": null,
				  "appleCare": false,
				  "expectedShippingDate": null,
				  "shipCommitInd": null,
				  "sameDayDelivery": false,
				  "recycleCreditAllocatedAmount": 0.0,
				  "ecpdItemAmount": null,
				  "ecpdItemDiscount": 0.0,
				  "standaloneaccessory": false,
				  "batteryAccessory": false,
				  "accSeoUrl": null,
				  "name": "Lightning Wall Charger",
				  "price": "29.99",
				  "discountedPrice": "22.5",
				  "preSelected": false,
				  "comingSoonAcc": false,
				  "inCart": false,
				  "learnMoreLink": "/od/cust/auth/accessoryDetails/?accProdId=acc6880031",
				  "discount_price": null,
				  "available": false
				}
			  ]
			},
			{
			  "brand": "",
			  "displayName": "Braven Stryde 360",
			  "capacity": 10,
			  "productID": "sku2490050",
			  "skuDetails": [
				{
				  "id": "sku2490050",
				  "quantity": 1,
				  "type": null,
				  "skuId": "sku2490050",
				  "productId": null,
				  "sorId": "BBRVFCSG",
				  "itemAmount": 99.99,
				  "itemAmountOriginal": 0.0,
				  "dueMonthly": 0.0,
				  "dueMonthlyOriginal": null,
				  "itemDiscount": 0.0,
				  "displayName": "Stryde 360 - Silver/Green",
				  "skuDisplayName": "Braven Stryde 360 Degree Sound - Silver Green",
				  "listPrice": 99.99,
				  "rawTotalAmount": 99.99,
				  "pricingDetails": [
					{
					  "pricingAdjustmentId": null,
					  "itemId": "sku2490050",
					  "orderId": null,
					  "offerId": null,
					  "offerAmount": 0.0,
					  "description": "List Price description",
					  "offerType": null,
					  "priceListId": null,
					  "listPrice": 99.99,
					  "offerName": null,
					  "creationDate": 1525952151583,
					  "lastModifiedDate": 1525952151583,
					  "version": 1
					}
				  ],
				  "orderId": null,
				  "version": 0,
				  "delete": false,
				  "inventoryLevel": 0,
				  "taxDetails": [
					{
					  "taxLineItemId": null,
					  "lineItemId": "sku2490050",
					  "itemType": "accessory",
					  "sorSkuId": "BBRVFCSG",
					  "taxType": "taxes_fees",
					  "taxAmount": 6.25,
					  "taxDescription": "TX State Sales Tax",
					  "version": 0,
					  "orderId": null,
					  "createdDate": 1525951784085
					},
					{
					  "taxLineItemId": null,
					  "lineItemId": "sku2490050",
					  "itemType": "accessory",
					  "sorSkuId": "BBRVFCSG",
					  "taxType": "taxes_fees",
					  "taxAmount": 1.0,
					  "taxDescription": "TX Local Sales Tax",
					  "version": 0,
					  "orderId": null,
					  "createdDate": 1525951784085
					},
					{
					  "taxLineItemId": null,
					  "lineItemId": "sku2490050",
					  "itemType": "accessory",
					  "sorSkuId": "BBRVFCSG",
					  "taxType": "taxes_fees",
					  "taxAmount": 1.0,
					  "taxDescription": "TX Local Sales Tax",
					  "version": 0,
					  "orderId": null,
					  "createdDate": 1525951784085
					}
				  ],
				  "itemTaxes": 8.25,
				  "deviceLineItemId": null,
				  "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/braven-stryde-360-silver-green-bbrvfcsg-iset?$acc-med$",
				  "bogoType": null,
				  "recycleStateInd": null,
				  "color": false,
				  "size": null,
				  "capacity": null,
				  "lastModifiedDate": null,
				  "deviceManufacturerName": null,
				  "accessoryType": null,
				  "ispuEligibleFlag": false,
				  "bundleSkuLineItems": null,
				  "bundleDesciption": null,
				  "vzwSbdOfferlist": [
					
				  ],
				  "promotions": null,
				  "purchasePath": null,
				  "appleCare": false,
				  "expectedShippingDate": null,
				  "shipCommitInd": null,
				  "sameDayDelivery": false,
				  "recycleCreditAllocatedAmount": 0.0,
				  "ecpdItemAmount": null,
				  "ecpdItemDiscount": 0.0,
				  "standaloneaccessory": false,
				  "batteryAccessory": false,
				  "accSeoUrl": null,
				  "name": "Stryde 360 - Silver/Green",
				  "price": "99.99",
				  "discountedPrice": "50.0",
				  "preSelected": false,
				  "comingSoonAcc": false,
				  "inCart": false,
				  "learnMoreLink": "/od/cust/auth/accessoryDetails/?accProdId=acc7960018",
				  "discount_price": null,
				  "available": false
				}
			  ]
			}
		  ],
		  "bundleDesciption": null,
		  "vzwSbdOfferlist": null,
		  "promotions": null,
		  "purchasePath": "EUP",
		  "appleCare": false,
		  "expectedShippingDate": null,
		  "shipCommitInd": null,
		  "sameDayDelivery": false,
		  "recycleCreditAllocatedAmount": 0.0,
		  "ecpdItemAmount": null,
		  "ecpdItemDiscount": 0.0,
		  "standaloneaccessory": false,
		  "batteryAccessory": false,
		  "accSeoUrl": ""
		},
		{
		  "id": "Se074cbdce387b0c9837c665fbe1306e4{d3}_accessory_3",
		  "quantity": 1,
		  "type": null,
		  "skuId": "sku2260117",
		  "productId": "acc6640066",
		  "sorId": "77-54483",
		  "itemAmount": 59.99,
		  "itemAmountOriginal": 0.0,
		  "dueMonthly": 0.0,
		  "dueMonthlyOriginal": null,
		  "itemDiscount": 0.0,
		  "displayName": "Defender Series Case for iPhone 8 Plus/7 Plus",
		  "skuDisplayName": "Defender Series Case for iPhone 8 Plus/7 Plus - Black",
		  "listPrice": 59.99,
		  "rawTotalAmount": 59.99,
		  "pricingDetails": [
			{
			  "pricingAdjustmentId": null,
			  "itemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_accessory_3",
			  "orderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}",
			  "offerId": null,
			  "offerAmount": 0.0,
			  "description": "List Price description",
			  "offerType": null,
			  "priceListId": null,
			  "listPrice": 59.99,
			  "offerName": null,
			  "creationDate": 1525952151583,
			  "lastModifiedDate": 1525952151583,
			  "version": 1
			}
		  ],
		  "orderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}",
		  "version": 1,
		  "delete": false,
		  "inventoryLevel": 1000,
		  "taxDetails": [
			{
			  "taxLineItemId": null,
			  "lineItemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_accessory_3",
			  "itemType": "accessory",
			  "sorSkuId": "77-54483",
			  "taxType": "taxes_fees",
			  "taxAmount": 0.6,
			  "taxDescription": "TX Local Sales Tax",
			  "version": 0,
			  "orderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}",
			  "createdDate": 1525951784085
			},
			{
			  "taxLineItemId": null,
			  "lineItemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_accessory_3",
			  "itemType": "accessory",
			  "sorSkuId": "77-54483",
			  "taxType": "taxes_fees",
			  "taxAmount": 3.75,
			  "taxDescription": "TX State Sales Tax",
			  "version": 0,
			  "orderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}",
			  "createdDate": 1525951784085
			},
			{
			  "taxLineItemId": null,
			  "lineItemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_accessory_3",
			  "itemType": "accessory",
			  "sorSkuId": "77-54483",
			  "taxType": "taxes_fees",
			  "taxAmount": 0.6,
			  "taxDescription": "TX Local Sales Tax",
			  "version": 0,
			  "orderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}",
			  "createdDate": 1525951784085
			}
		  ],
		  "itemTaxes": 4.95,
		  "deviceLineItemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_device_1",
		  "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/otterbox-defender-series-case-iphone-6s-plus-black-77-54169-iset?$acc-med$",
		  "bogoType": null,
		  "recycleStateInd": null,
		  "color": "Black",
		  "size": null,
		  "capacity": null,
		  "lastModifiedDate": 1525951748825,
		  "deviceManufacturerName": "OtterBox",
		  "accessoryType": "INLINE_ACCESSORIES",
		  "ispuEligibleFlag": true,
		  "bundleSkuLineItems": null,
		  "bundleDesciption": null,
		  "vzwSbdOfferlist": [
			
		  ],
		  "promotions": null,
		  "purchasePath": "EUP",
		  "appleCare": false,
		  "expectedShippingDate": null,
		  "shipCommitInd": null,
		  "sameDayDelivery": false,
		  "recycleCreditAllocatedAmount": 0.0,
		  "ecpdItemAmount": null,
		  "ecpdItemDiscount": 0.0,
		  "standaloneaccessory": false,
		  "batteryAccessory": false,
		  "accSeoUrl": ""
		},
		{
		  "id": "Se074cbdce387b0c9837c665fbe1306e4{d3}_accessory_4",
		  "quantity": 1,
		  "type": null,
		  "skuId": "sku2300258",
		  "productId": "9900002",
		  "sorId": null,
		  "itemAmount": 109.97,
		  "itemAmountOriginal": 0.0,
		  "dueMonthly": 0.0,
		  "dueMonthlyOriginal": null,
		  "itemDiscount": 0.0,
		  "displayName": "Universal Lightning Power Bundle",
		  "skuDisplayName": null,
		  "listPrice": 109.97,
		  "rawTotalAmount": 109.97,
		  "pricingDetails": [
			{
			  "pricingAdjustmentId": null,
			  "itemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_accessory_4",
			  "orderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}",
			  "offerId": null,
			  "offerAmount": 0.0,
			  "description": "List Price description",
			  "offerType": null,
			  "priceListId": null,
			  "listPrice": 109.97,
			  "offerName": null,
			  "creationDate": 1525952151583,
			  "lastModifiedDate": 1525952151583,
			  "version": 1
			}
		  ],
		  "orderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}",
		  "version": 1,
		  "delete": false,
		  "inventoryLevel": 0,
		  "taxDetails": null,
		  "itemTaxes": 0.0,
		  "deviceLineItemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_device_2",
		  "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/vzw-universal-lightning-power-bundle-15885-gg-bundle-iset?$acc-med$",
		  "bogoType": null,
		  "recycleStateInd": null,
		  "color": null,
		  "size": null,
		  "capacity": null,
		  "lastModifiedDate": 1525952147389,
		  "deviceManufacturerName": null,
		  "accessoryType": "BUNDLE_ACCESSORIES",
		  "ispuEligibleFlag": true,
		  "bundleSkuLineItems": [
			{
			  "brand": "",
			  "displayName": "Lightning Wall Charger",
			  "capacity": 10,
			  "productID": "sku2180059",
			  "skuDetails": [
				{
				  "id": "sku2180059",
				  "quantity": 1,
				  "type": null,
				  "skuId": "sku2180059",
				  "productId": null,
				  "sorId": "TVL24LGHT-M",
				  "itemAmount": 29.99,
				  "itemAmountOriginal": 0.0,
				  "dueMonthly": 0.0,
				  "dueMonthlyOriginal": null,
				  "itemDiscount": 0.0,
				  "displayName": "Lightning Wall Charger",
				  "skuDisplayName": "Verizon 2.4A Apple Lightning Travel Charger",
				  "listPrice": 29.99,
				  "rawTotalAmount": 29.99,
				  "pricingDetails": [
					{
					  "pricingAdjustmentId": null,
					  "itemId": "sku2180059",
					  "orderId": null,
					  "offerId": null,
					  "offerAmount": 0.0,
					  "description": "List Price description",
					  "offerType": null,
					  "priceListId": null,
					  "listPrice": 29.99,
					  "offerName": null,
					  "creationDate": 1525952151583,
					  "lastModifiedDate": 1525952151583,
					  "version": 1
					}
				  ],
				  "orderId": null,
				  "version": 0,
				  "delete": false,
				  "inventoryLevel": 0,
				  "taxDetails": null,
				  "itemTaxes": 0.0,
				  "deviceLineItemId": null,
				  "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/vzw-2-4a-apple-lightning-travel-charger-tvl24lght-m-iset?$acc-med$",
				  "bogoType": null,
				  "recycleStateInd": null,
				  "color": false,
				  "size": null,
				  "capacity": null,
				  "lastModifiedDate": null,
				  "deviceManufacturerName": null,
				  "accessoryType": null,
				  "ispuEligibleFlag": false,
				  "bundleSkuLineItems": null,
				  "bundleDesciption": null,
				  "vzwSbdOfferlist": [
					
				  ],
				  "promotions": null,
				  "purchasePath": null,
				  "appleCare": false,
				  "expectedShippingDate": null,
				  "shipCommitInd": null,
				  "sameDayDelivery": false,
				  "recycleCreditAllocatedAmount": 0.0,
				  "ecpdItemAmount": null,
				  "ecpdItemDiscount": 0.0,
				  "standaloneaccessory": false,
				  "batteryAccessory": false,
				  "accSeoUrl": null,
				  "name": "Lightning Wall Charger",
				  "price": "29.99",
				  "discountedPrice": "0.0",
				  "preSelected": false,
				  "comingSoonAcc": false,
				  "inCart": false,
				  "learnMoreLink": "/od/cust/auth/accessoryDetails/?accProdId=acc6880031",
				  "discount_price": null,
				  "available": false
				}
			  ]
			},
			{
			  "brand": "",
			  "displayName": "Lightning Car Charger",
			  "capacity": 10,
			  "productID": "sku2180048",
			  "skuDetails": [
				{
				  "id": "sku2180048",
				  "quantity": 1,
				  "type": null,
				  "skuId": "sku2180048",
				  "productId": null,
				  "sorId": "VPC24LGHT-M",
				  "itemAmount": 29.99,
				  "itemAmountOriginal": 0.0,
				  "dueMonthly": 0.0,
				  "dueMonthlyOriginal": null,
				  "itemDiscount": 0.0,
				  "displayName": "Lightning Car Charger",
				  "skuDisplayName": "Verizon 2.4A Apple Lightning Vehicle Charger",
				  "listPrice": 29.99,
				  "rawTotalAmount": 29.99,
				  "pricingDetails": [
					{
					  "pricingAdjustmentId": null,
					  "itemId": "sku2180048",
					  "orderId": null,
					  "offerId": null,
					  "offerAmount": 0.0,
					  "description": "List Price description",
					  "offerType": null,
					  "priceListId": null,
					  "listPrice": 29.99,
					  "offerName": null,
					  "creationDate": 1525952151583,
					  "lastModifiedDate": 1525952151583,
					  "version": 1
					}
				  ],
				  "orderId": null,
				  "version": 0,
				  "delete": false,
				  "inventoryLevel": 0,
				  "taxDetails": null,
				  "itemTaxes": 0.0,
				  "deviceLineItemId": null,
				  "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/vzw-2-4a-apple-lightning-vehicle-charger-vpc24lght-m-iset?$acc-med$",
				  "bogoType": null,
				  "recycleStateInd": null,
				  "color": false,
				  "size": null,
				  "capacity": null,
				  "lastModifiedDate": null,
				  "deviceManufacturerName": null,
				  "accessoryType": null,
				  "ispuEligibleFlag": false,
				  "bundleSkuLineItems": null,
				  "bundleDesciption": null,
				  "vzwSbdOfferlist": [
					
				  ],
				  "promotions": null,
				  "purchasePath": null,
				  "appleCare": false,
				  "expectedShippingDate": null,
				  "shipCommitInd": null,
				  "sameDayDelivery": false,
				  "recycleCreditAllocatedAmount": 0.0,
				  "ecpdItemAmount": null,
				  "ecpdItemDiscount": 0.0,
				  "standaloneaccessory": false,
				  "batteryAccessory": false,
				  "accSeoUrl": null,
				  "name": "Lightning Car Charger",
				  "price": "29.99",
				  "discountedPrice": "0.0",
				  "preSelected": false,
				  "comingSoonAcc": false,
				  "inCart": false,
				  "learnMoreLink": "/od/cust/auth/accessoryDetails/?accProdId=acc6880020",
				  "discount_price": null,
				  "available": false
				}
			  ]
			},
			{
			  "brand": "",
			  "displayName": "powerstation 6000 - Space Gray",
			  "capacity": 10,
			  "productID": "sku2090609",
			  "skuDetails": [
				{
				  "id": "sku2090609",
				  "quantity": 1,
				  "type": null,
				  "skuId": "sku2090609",
				  "productId": null,
				  "sorId": "MOPHPS62GRY",
				  "itemAmount": 49.99,
				  "itemAmountOriginal": 0.0,
				  "dueMonthly": 0.0,
				  "dueMonthlyOriginal": null,
				  "itemDiscount": 0.0,
				  "displayName": "powerstation 6000 - Space Gray",
				  "skuDisplayName": "mophie powerstation 6000 - Space Gray",
				  "listPrice": 49.99,
				  "rawTotalAmount": 49.99,
				  "pricingDetails": [
					{
					  "pricingAdjustmentId": null,
					  "itemId": "sku2090609",
					  "orderId": null,
					  "offerId": null,
					  "offerAmount": 0.0,
					  "description": "List Price description",
					  "offerType": null,
					  "priceListId": null,
					  "listPrice": 49.99,
					  "offerName": null,
					  "creationDate": 1525952151583,
					  "lastModifiedDate": 1525952151583,
					  "version": 1
					}
				  ],
				  "orderId": null,
				  "version": 0,
				  "delete": false,
				  "inventoryLevel": 0,
				  "taxDetails": null,
				  "itemTaxes": 0.0,
				  "deviceLineItemId": null,
				  "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/mophie-powerstation-6200-space-gray-mophps62gry-iset?$acc-med$",
				  "bogoType": null,
				  "recycleStateInd": null,
				  "color": false,
				  "size": null,
				  "capacity": null,
				  "lastModifiedDate": null,
				  "deviceManufacturerName": null,
				  "accessoryType": null,
				  "ispuEligibleFlag": false,
				  "bundleSkuLineItems": null,
				  "bundleDesciption": null,
				  "vzwSbdOfferlist": [
					
				  ],
				  "promotions": null,
				  "purchasePath": null,
				  "appleCare": false,
				  "expectedShippingDate": null,
				  "shipCommitInd": null,
				  "sameDayDelivery": false,
				  "recycleCreditAllocatedAmount": 0.0,
				  "ecpdItemAmount": null,
				  "ecpdItemDiscount": 0.0,
				  "standaloneaccessory": false,
				  "batteryAccessory": false,
				  "accSeoUrl": null,
				  "name": "powerstation 6000 - Space Gray",
				  "price": "49.99",
				  "discountedPrice": "0.0",
				  "preSelected": false,
				  "comingSoonAcc": false,
				  "inCart": false,
				  "learnMoreLink": "/od/cust/auth/accessoryDetails/?accProdId=acc6520126",
				  "discount_price": null,
				  "available": false
				}
			  ]
			}
		  ],
		  "bundleDesciption": null,
		  "vzwSbdOfferlist": null,
		  "promotions": null,
		  "purchasePath": "AAL",
		  "appleCare": false,
		  "expectedShippingDate": null,
		  "shipCommitInd": null,
		  "sameDayDelivery": false,
		  "recycleCreditAllocatedAmount": 0.0,
		  "ecpdItemAmount": null,
		  "ecpdItemDiscount": 0.0,
		  "standaloneaccessory": false,
		  "batteryAccessory": false,
		  "accSeoUrl": ""
		}
	  ],
	  "paymentGroup": null,
	  "contactInfo": {
		"id": null,
		"emailAddress": "WINOTLVYVO@VZW.COM",
		"phoneNumber": "5207420265",
		"lastName": "MANNING",
		"firstName": "RAVI",
		"zipCode": "75088",
		"orderId": null,
		"userId": null,
		"npaNxxNumber": null,
		"address1": "8701 LAKEVIEW PKWY STE 111-144",
		"address2": null,
		"city": "Rowlett",
		"state": "TX",
		"addressVerified": true,
		"textAlertOptin": false,
		"newsLetterOptin": false,
		"paperFreeBillingIndicatorFlag": false,
		"middleName": null,
		"firmName": null,
		"businessName": null,
		"apartmentNum": "111-1",
		"addressDirection": "",
		"poBox": "",
		"streetNumber": "8701",
		"streetName": "LAKEVIEW",
		"streetType": "PKWY",
		"ruralRoute": null,
		"ruralDel": "",
		"zipCode4": null,
		"zipCode5": null,
		"faxNumber": null,
		"addressType": null,
		"country": "",
		"prefix": null,
		"suffix": null,
		"postbox": null,
		"companyname": null,
		"ruralrte": "",
		"county": null,
		"address3": null,
		"postalcode": "75088",
		"version": 0,
		"lastModifiedDate": null,
		"addressConfirmationStatus": null
	  },
	  "tradeInDevicesDetails": null,
	  "tradeInPromoDetails": null,
	  "transformedTradeInPromoDetails": {
		"tradeInDeviceDppMsg": "We'll send you a prepaid box to mail in your trade-in. This is only an estimate until we receive and appraise your device.",
		"warningMessage": null,
		"tradeInDeviceHeaderMsg": "You'll see an estimated $32.00 credit within 1-2 bill cycles.",
		"tradeInCredit": "32.00",
		"tradeInDevices": [
		  {
			"activeDevice": null,
			"tradeInCredit": "32.00",
			"tradeInDeviceFooter": null,
			"offerDetailsMsg": null,
			"tradeInDeviceHeaderMsg": null,
			"tradeInCreditMsg": "Trade-in credit: $32.00",
			"bicApplied": false,
			"color": "Black",
			"dataWipeText": null,
			"deviceBrand": "Samsung",
			"deviceId": "ID: 990004661602320",
			"discAmt": null,
			"disconnectedDate": null,
			"displayName": "Galaxy Note 3",
			"dppCredit": "0.0",
			"dppAppliedCommerceItemId": null,
			"dppAppliedMdn": null,
			"errorMessage": null,
			"modalOsName": null,
			"modelImage": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_Note3_Black?$device-lg$",
			"modelName": null,
			"mtn": null,
			"nickName": null,
			"originalAppraisalPrice": "32.00",
			"price": null,
			"promoCodeError": null,
			"promoCreditType": null,
			"promoQualifyMessage": null,
			"promoValue": null,
			"shortDisplayName": null,
			"size": "32GB",
			"success": true,
			"regularPromoApplied": false,
			"existingAppraisedReferenceId": "00539061583774",
			"appraiseTradeInDeviceWithOutDeviceId": true,
			"flow": "AAL"
		  }
		],
		"orginaltradeInCredit": "32.00"
	  },
	  "subOrders": [
		{
		  "subOrderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_suborder_1",
		  "taxCalculated": false,
		  "clientOrderType": null,
		  "creditWriteValidated": false,
		  "clientReferenceNumber": "924042362448974",
		  "creditApplicationNumber": null,
		  "posOrderNumber": "1021117",
		  "suborderType": "EUP",
		  "subOrderStatus": null,
		  "lastModifiedDate": null,
		  "createdDate": 1525952160117,
		  "orderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}",
		  "version": 0,
		  "creditApplicationNum": "838008219",
		  "transactionId": null
		},
		{
		  "subOrderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_suborder_2",
		  "taxCalculated": false,
		  "clientOrderType": null,
		  "creditWriteValidated": false,
		  "clientReferenceNumber": "924042359205012",
		  "creditApplicationNumber": null,
		  "posOrderNumber": "1021118",
		  "suborderType": "AAL",
		  "subOrderStatus": null,
		  "lastModifiedDate": null,
		  "createdDate": 1525952160117,
		  "orderId": "Se074cbdce387b0c9837c665fbe1306e4{d3}",
		  "version": 0,
		  "creditApplicationNum": "839008219",
		  "transactionId": null
		}
	  ],
	  "comboOrder": true,
	  "totalDueToday": "514.89",
	  "totalDueMonthly": "82.82",
	  "subTotalDueToday": "514.89",
	  "securityDepositAmount": "0.00",
	  "stateSalesTax": "0.00",
	  "employeeDiscount": "514.89",
	  "pastDueExist": false,
	  "pastDueAmountPaid": false,
	  "pastDueAmount": "0.00",
	  "shippingInfo": {
		"shippingInfoUpdated": false,
		"sameAsBilling": true,
		"ispuEligibleFlag": false,
		"addressInfo": {
		  "firstName": "RAVI",
		  "lastName": "MANNING",
		  "companyName": null,
		  "address1": "8701 LAKEVIEW PKWY STE 111-144",
		  "address2": null,
		  "city": "Rowlett",
		  "state": "TX",
		  "zipcode": "75088",
		  "businessName": null,
		  "postalCode": null,
		  "email": "WINOTLVYVO@VZW.COM",
		  "phoneNumber": "5207420265"
		},
		"contactInfo": {
		  "emailAddress": "WINOTLVYVO@VZW.COM",
		  "phoneNumber": "5207420265",
		  "firstName": "RAVI",
		  "lastName": "MANNING",
		  "smsMdn": null,
		  "activeSMSCapableMtnList": [
			"5125579423"
		  ]
		},
		"shippingTypesInfo": [
		  {
			"estimatedDeliveryDate": "2018-05-14 00:00:00",
			"estimatedDeliveryDateText": "Mon 5/14",
			"shippingDescription": "Free 2 Day by 8pm",
			"shippingOptionId": "SHP002",
			"shippingCost": "0.00",
			"shortDescription": "Free 2 Day by 8pm",
			"active": true,
			"addedShippingOptionId": true,
			"signatureRequired": "true",
			"description": "Estimated to arrive on Mon, May 14 if ordered by 4pm today. Signature required.",
			"depletionLocationCode": null,
			"sddAvailableWindows": null
		  }
		],
		"storeDetail": {
		  "storeHeader": null,
		  "storeName": null,
		  "storeAddress": null,
		  "deviceAvailable": false,
		  "distance": null,
		  "appendedStoreTiming": null,
		  "longitude": null,
		  "storeId": null,
		  "netaceLocationCode": null,
		  "latitude": null,
		  "seoUrlName": null,
		  "storeClosingTime": null
		},
		"tradeIn": true,
		"tradeInAddress": {
		  "firstName": "RAVI",
		  "lastName": "MANNING",
		  "address1": "8701 LAKEVIEW PKWY STE 111-144",
		  "address2": null,
		  "city": "Rowlett",
		  "state": "TX",
		  "zipcode": "75088",
		  "companyName": null
		},
		"nonSddEligibleMsg": null,
		"selectedSDDWindow": null,
		"poboMessage": null,
		"ispudetailsInfo": {
		  "storeAddress": null,
		  "storeHours": null,
		  "storeId": null,
		  "storeName": null,
		  "phoneNumber": null,
		  "distance": null,
		  "totalItems": 0,
		  "availItems": 0,
		  "latitdude": 0.0,
		  "longtitude": 0.0,
		  "availItemName": null
		}
	  },
	  "billingInfo": {
		"billToAccountEligible": true,
		"creditCardZipEditable": true,
		"billingAddress": {
		  "firstName": "RAVI",
		  "lastName": "MANNING",
		  "businessName": null,
		  "zipcode": "75088",
		  "state": "TX",
		  "address2": null,
		  "address1": "8701 LAKEVIEW PKWY STE 111-144",
		  "companyName": null,
		  "city": "Rowlett"
		},
		"masterpass3DSecure": null,
		"billToAccountNumber": "#XXXXXXX-0001",
		"creditCardInfo": {
		  "savedCardNickName": null,
		  "preselectCard": null,
		  "creditCardNumber": "XXXX XXXX XXXX-0002",
		  "creditCardExpMonth": "01",
		  "creditCardExpYear": "2020",
		  "billingZipCode": null,
		  "creditCardType": "visa",
		  "creditCardVerificationNumber": null,
		  "creditCardBIN": null,
		  "cvvRequired": false
		},
		"selectedPaymentMode": "newCard",
		"giftCardList": [
		  
		],
		"savedCardInfo": [
		  {
			"savedCardNickName": "BOGUS",
			"preselectCard": null,
			"creditCardNumber": "XXXX-XXXX-XXXX-9844",
			"creditCardExpMonth": "12",
			"creditCardExpYear": "29",
			"billingZipCode": "75028",
			"creditCardType": "masterCard",
			"creditCardVerificationNumber": null,
			"creditCardBIN": "505429",
			"cvvRequired": false
		  }
		],
		"applePayResponseInfo": null,
		"masterpassResponseInfo": {
		  "emailAddress": null,
		  "cardType": null,
		  "lastDigits": null,
		  "creditCardBIN": null
		},
		"masterpassError": false,
		"masterpassErrorMessage": null,
		"paypalEmailAddress": null,
		"expirationMonths": [
		  "01",
		  "02",
		  "03",
		  "04",
		  "05",
		  "06",
		  "07",
		  "08",
		  "09",
		  "10",
		  "11",
		  "12"
		],
		"expirationYears": [
		  "2018",
		  "2019",
		  "2020",
		  "2021",
		  "2022",
		  "2023",
		  "2024",
		  "2025",
		  "2026",
		  "2027"
		]
	  },
	  "devices": {
		"dueMonthly": 82.82,
		"totalActivationFee": 0.0,
		"deviceTotalDueMonthly": 30.82,
		"dueToday": 0.0,
		"accessories": [
		  {
			"scene7ImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/applecareplus-cc3000?$acc-med$",
			"name": "AppleCare+ for iPhone 8, 7, 6s, or 6",
			"actualPrice": 129.97,
			"originalPrice": 129.97,
			"percentageOffTxt": null,
			"itemTotal": 129.97,
			"quantity": 1,
			"commerceItemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_accessory_1",
			"color": null,
			"size": null,
			"inventoryStatus": "",
			"inventoryAvailableDate": "",
			"prodId": "acc5240003",
			"skuId": "sku1760050",
			"sorId": "S5556LL/A",
			"promoMessage": null,
			"hasEcpdDiscount": false,
			"mobileAppImageName": "",
			"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/applecareplus-cc3000?$acc-med$",
			"hasBogoDiscount": false,
			"price": 129.97,
			"discountPrice": 0.0,
			"retailPrice": 129.97,
			"associatedDeviceSkus": null,
			"prodName": "",
			"discounted": false
		  },
		  {
			"scene7ImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/otterbox-defender-series-case-iphone-6s-plus-black-77-54169-iset?$acc-med$",
			"name": "Defender Series Case for iPhone 8 Plus/7 Plus",
			"actualPrice": 59.99,
			"originalPrice": 59.99,
			"percentageOffTxt": null,
			"itemTotal": 59.99,
			"quantity": 1,
			"commerceItemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_accessory_3",
			"color": "Black",
			"size": null,
			"inventoryStatus": "",
			"inventoryAvailableDate": "",
			"prodId": "acc6640066",
			"skuId": "sku2260117",
			"sorId": "77-54483",
			"promoMessage": null,
			"hasEcpdDiscount": false,
			"mobileAppImageName": "",
			"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/otterbox-defender-series-case-iphone-6s-plus-black-77-54169-iset?$acc-med$",
			"hasBogoDiscount": false,
			"price": 59.99,
			"discountPrice": 0.0,
			"retailPrice": 59.99,
			"associatedDeviceSkus": null,
			"prodName": "",
			"discounted": false
		  }
		],
		"accessoriesBundle": [
		  {
			"discountedPrice": 214.96,
			"imgUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone-8-plus-7-15960-ga-enhanced-bundle-iset?$acc-med$",
			"regularPrice": 214.96,
			"savedPrice": 0.0,
			"displayName": "Presidio Clear Power, Protection, & Stereo Bundle for iPhone 8 Plus",
			"bundleDescription": null,
			"skuID": "sku2920042",
			"discountPercentage": null,
			"discounted": false
		  },
		  {
			"discountedPrice": 109.97,
			"imgUrl": "https://ss7.vzw.com/is/image/VerizonWireless/vzw-universal-lightning-power-bundle-15885-gg-bundle-iset?$acc-med$",
			"regularPrice": 109.97,
			"savedPrice": 0.0,
			"displayName": "Universal Lightning Power Bundle",
			"bundleDescription": null,
			"skuID": "sku2300258",
			"discountPercentage": null,
			"discounted": false
		  }
		],
		"items": [
		  {
			"deviceName": "iPhone&reg; 7 Plus",
			"dueMonthly": "15.41",
			"dueToday": "0.00",
			"upgradeFee": "0.00",
			"originalUpgradeFee": "30.00",
			"activationFee": "0.00",
			"dueTodayOriginal": "0.00",
			"dueMonthlyOriginal": "27.92",
			"modDevice": true,
			"dueTodayDiscounted": false,
			"dueMonthlyDiscounted": true,
			"mtn": "5125579423",
			"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-matblk?$device-med$&fmt=jpeg&wid=75&hei=150",
			"protectionFeature": {
			  "name": "Total Mobile Protection",
			  "mtn": null,
			  "price": "13.00",
			  "discountPrice": "0.00",
			  "retailPrice": "0.00",
			  "hasEcpdDiscount": false,
			  "promoMessage": null,
			  "originalPrice": "0.00",
			  "wasPrice": "0.00",
			  "deviceName": null,
			  "color": null,
			  "size": null,
			  "instantCreditAmount": "0.00",
			  "amountAfterInstantCredit": "0.00",
			  "disountedInstantCreditAmt": "0.00"
			},
			"optionalFeatures": [
			  
			],
			"installmentBalance": "369.99",
			"edgeRetailPrice": "669.99",
			"edgeItemDownPaymentAmount": "0.00",
			"mailInRebateAmount": "0.00",
			"transferredFromMtn": null,
			"devicePromotionList": [
			  {
				"promotionalMessage": null,
				"promoDescription": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION BIC YES",
				"promoName": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION",
				"promoAmount": "0",
				"priceSubTitle": "1st installment will appear on your bill.",
				"barCodeId": null,
				"itemCode": "MNR12LL/A",
				"itemType": "ITA",
				"sedOffer": true,
				"isUpgradeFeeWaivedOffer": false,
				"promoContentText": null
			  },
			  {
				"promotionalMessage": null,
				"promoDescription": "UAT WAIVED UPGRADE FEE WITH SMT PH ONLINE ONLY UPG 2YR DPP - BIC YES",
				"promoName": "UAT WAIVED UPGRADE FEE WITH SMT PH ONLINE ONLY UPG",
				"promoAmount": "30.0",
				"priceSubTitle": "1st installment will appear on your bill.",
				"barCodeId": null,
				"itemCode": "UPGRADEFEE30",
				"itemType": "ITP",
				"sedOffer": true,
				"isUpgradeFeeWaivedOffer": true,
				"promoContentText": null
			  }
			],
			"bicOfferApplied": false,
			"bicContractPrice": "0.00",
			"bicDiscountedContractPrice": "-1.00",
			"bicAdditionalContractText": null,
			"bicMessageMap": null,
			"edgeUpAmount": 0.0,
			"displayDeviceDueMonthly": 67.41,
			"deviceLACFee": "65.00",
			"manufactureName": "Apple",
			"color": "Black",
			"colorCode": "#000000",
			"size": "32GB",
			"displayName": "iPhone&reg; 7 Plus",
			"contractTerm": "99",
			"edgeUpBuyOutAmount": 0.0,
			"fullRetailPrice": "669.99",
			"alwaysEligibleForUpgrade": false,
			"numberShareDevice": false,
			"activationFeeText": null,
			"numberSharedMtn": null,
			"promoContentText": null,
			"itemOnJaxPlan": true,
			"humCarDetails": null,
			"simDetails": null,
			"imeiId": null,
			"displayImeiId": null,
			"poboDateLabel": null,
			"promoOfferText": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION",
			"promoApplied": true,
			"commerceItemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_device_1",
			"loanTerm": 24,
			"sbdHeaderMsg": null,
			"percentage": null,
			"waivedActivationFeePromo": false,
			"flow": "EUP",
			"edgeDevice": true,
			"instantCreditAmount": "0.00",
			"amountAfterInstantCredit": "0.00",
			"disountedInstantCreditAmt": "0.00",
			"accessory": false,
			"eupdevice": false
		  },
		  {
			"deviceName": "Pixel XL, Phone by Google",
			"dueMonthly": "15.41",
			"dueToday": "0.00",
			"upgradeFee": "0.00",
			"originalUpgradeFee": "0.00",
			"activationFee": "30.00",
			"dueTodayOriginal": "0.00",
			"modDevice": true,
			"dueMonthlyOriginal": "27.92",
			"dueTodayDiscounted": false,
			"dueMonthlyDiscounted": true,
			"mtn": null,
			"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Google_Marlin_Slate?$device-med$&fmt=jpeg&wid=75&hei=150",
			"protectionFeature": {
			  "name": "Total Mobile Protection Multi-Device",
			  "mtn": null,
			  "price": "-",
			  "discountPrice": "0.00",
			  "retailPrice": "0.00",
			  "hasEcpdDiscount": false,
			  "promoMessage": null,
			  "originalPrice": "0.00",
			  "wasPrice": "0.00",
			  "deviceName": null,
			  "color": null,
			  "size": null,
			  "instantCreditAmount": "0.00",
			  "amountAfterInstantCredit": "0.00",
			  "disountedInstantCreditAmt": "0.00"
			},
			"optionalFeatures": [
			  
			],
			"installmentBalance": "369.99",
			"edgeRetailPrice": "669.99",
			"edgeItemDownPaymentAmount": "0.00",
			"mailInRebateAmount": "0.00",
			"transferredFromMtn": null,
			"devicePromotionList": [
			  {
				"promotionalMessage": null,
				"promoDescription": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION BIC YES",
				"promoName": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION",
				"promoAmount": "300.00",
				"priceSubTitle": "1st installment will appear on your bill.",
				"barCodeId": null,
				"itemCode": "G-2PW2100-021-A",
				"itemType": "ITA",
				"sedOffer": true,
				"isUpgradeFeeWaivedOffer": false,
				"promoContentText": null
			  }
			],
			"bicOfferApplied": false,
			"bicContractPrice": "0.00",
			"bicDiscountedContractPrice": "-1.00",
			"bicAdditionalContractText": null,
			"bicMessageMap": null,
			"edgeUpAmount": 0.0,
			"displayDeviceDueMonthly": 15.41,
			"deviceLACFee": "65.00",
			"manufactureName": "Google",
			"color": "Quite Black",
			"colorCode": "#000000",
			"size": "32GB",
			"displayName": "Pixel XL, Phone by Google",
			"contractTerm": "99",
			"edgeUpBuyOutAmount": 0.0,
			"fullRetailPrice": "669.99",
			"alwaysEligibleForUpgrade": false,
			"numberShareDevice": false,
			"activationFeeText": "One-time activation fee of $30.00 charged to your next monthly bill.",
			"numberSharedMtn": null,
			"promoContentText": null,
			"itemOnJaxPlan": true,
			"humCarDetails": null,
			"simDetails": null,
			"imeiId": null,
			"displayImeiId": null,
			"poboDateLabel": null,
			"promoOfferText": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION",
			"promoApplied": true,
			"commerceItemId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_device_2",
			"loanTerm": 24,
			"sbdHeaderMsg": null,
			"percentage": null,
			"waivedActivationFeePromo": false,
			"flow": "AAL",
			"edgeDevice": true,
			"instantCreditAmount": "0.00",
			"amountAfterInstantCredit": "0.00",
			"disountedInstantCreditAmt": "0.00",
			"accessory": false,
			"eupdevice": false
		  }
		],
		"buddyUpgrade": false
	  },
	  "accessories": null,
	  "selectedShippingType": {
		"type": "SHIPPING",
		"shippingTypeName": "FREE 2 Day by 8pm",
		"price": 0.0,
		"discountPrice": 0.0,
		"estimatedDeliveryDate": "2018-05-14 00:00:00"
	  },
	  "dueMonthlyView": {
		"title": "Due Monthly (device only)",
		"dueMonthlyPrice": "82.82",
		"items": [
		  {
			"name": "iPhone&reg; 7 Plus",
			"description": "iPhone&reg; 7 Plus",
			"manufacturer": "Apple",
			"color": "Black",
			"size": "32GB",
			"priceBreakDown": [
			  {
				"lable": "Total Mobile Protection",
				"price": "13.00",
				"description": null,
				"linkText": null,
				"linkUrl": null,
				"originalPrice": 0.0,
				"tmpMdOpted": true,
				"discountedEdgeRetailPrice": null,
				"sbdPromoMsg": null,
				"sbdDiscountAmount": 0.0,
				"sbdItemMonthlyAmount": 0.0,
				"itemRetailPrice": 0.0,
				"itemMonthlyPrice": 0.0,
				"itemStrikeThroughPrice": 0.0,
				"noOfBicOccurences": 0
			  },
			  {
				"lable": "Device Payment",
				"price": "15.41",
				"description": "For 24 months, 0% APR with down payment. Reduced retail price: <span class='textDecLineThrough red'>$669.99</span> $369.99",
				"linkText": null,
				"linkUrl": null,
				"originalPrice": 0.0,
				"tmpMdOpted": false,
				"discountedEdgeRetailPrice": null,
				"sbdPromoMsg": null,
				"sbdDiscountAmount": 0.0,
				"sbdItemMonthlyAmount": 0.0,
				"itemRetailPrice": 0.0,
				"itemMonthlyPrice": 15.41,
				"itemStrikeThroughPrice": 27.92,
				"noOfBicOccurences": 0
			  }
			],
			"edge": true
		  },
		  {
			"name": "Pixel XL, Phone by Google",
			"description": "Pixel XL, Phone by Google",
			"manufacturer": "Google",
			"color": "Quite Black",
			"size": "32GB",
			"priceBreakDown": [
			  {
				"lable": "Total Mobile Protection Multi-Device",
				"price": "-",
				"description": null,
				"linkText": null,
				"linkUrl": null,
				"originalPrice": 0.0,
				"tmpMdOpted": true,
				"discountedEdgeRetailPrice": null,
				"sbdPromoMsg": null,
				"sbdDiscountAmount": 0.0,
				"sbdItemMonthlyAmount": 0.0,
				"itemRetailPrice": 0.0,
				"itemMonthlyPrice": 0.0,
				"itemStrikeThroughPrice": 0.0,
				"noOfBicOccurences": 0
			  },
			  {
				"lable": "Device Payment",
				"price": "15.41",
				"description": "For 24 months, 0% APR with down payment. Reduced retail price: <span class='textDecLineThrough red'>$669.99</span> $369.99",
				"linkText": null,
				"linkUrl": null,
				"originalPrice": 0.0,
				"tmpMdOpted": false,
				"discountedEdgeRetailPrice": null,
				"sbdPromoMsg": null,
				"sbdDiscountAmount": 0.0,
				"sbdItemMonthlyAmount": 0.0,
				"itemRetailPrice": 0.0,
				"itemMonthlyPrice": 15.41,
				"itemStrikeThroughPrice": 27.92,
				"noOfBicOccurences": 0
			  }
			],
			"edge": true
		  }
		],
		"tmpMd": {
		  "lable": "Total Mobile Protection Multi-Device",
		  "price": "39.00",
		  "description": "",
		  "linkText": null,
		  "linkUrl": null,
		  "originalPrice": 0.0,
		  "tmpMdOpted": true,
		  "discountedEdgeRetailPrice": null,
		  "sbdPromoMsg": null,
		  "sbdDiscountAmount": 0.0,
		  "sbdItemMonthlyAmount": 0.0,
		  "itemRetailPrice": 0.0,
		  "itemMonthlyPrice": 0.0,
		  "itemStrikeThroughPrice": 0.0,
		  "noOfBicOccurences": 0
		}
	  },
	  "balanceCreditCardAmount": "514.89",
	  "cpcOrder": false,
      "totalDueMonthlyPlanAndDevice": "212.82",      
	  "isHLLPlanInOrder": true,
	  "deviceConfigInfo": {
		"devices": [
		  {
			"deviceId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_device_1",
			"deviceName": "iPhone&reg; 7 Plus",
			"deviceSetupMode": null,
			"mtnNumber": "5125579423",
			"flow": "EUP",
			"serviceAddress": {
			  "firstName": "RAVI",
			  "lastName": "MANNING",
			  "address1": "8701 LAKEVIEW PKWY STE 111-144",
			  "address2": "",
			  "city": "Rowlett",
			  "state": "TX",
			  "zipCode": "75088",
			  "emailAddress": "WINOTLVYVO@VZW.COM",
			  "phoneNumber": "5207420265"
			},
			"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-matblk?$device-med$&fmt=jpeg&wid=75&hei=150",
			"mobileAppImageName": null,
			"npaNxxnumber": null,
			"modDevice": true,
			"npnxxCustomerSelection": null,
			"npaNxxdetails": null,
			"manufactureName": "Apple",
			"color": "Black",
			"size": "32GB",
			"numberShareDevice": false,
			"numberSharedMtn": null,
			"deviceNickName": null,
			"numberSharedDeviceName": null,
			"portInDetails": null
		  },
		  {
			"deviceId": "Se074cbdce387b0c9837c665fbe1306e4{d3}_device_2",
			"deviceName": "Pixel XL, Phone by Google",
			"deviceSetupMode": null,
			"mtnNumber": null,
			"flow": "AAL",
			"serviceAddress": {
			  "firstName": "RAVI",
			  "lastName": "MANNING",
			  "address1": "8701 LAKEVIEW PKWY STE 111-144",
			  "address2": "",
			  "city": "Rowlett",
			  "state": "TX",
			  "zipCode": "75088",
			  "emailAddress": "WINOTLVYVO@VZW.COM",
			  "phoneNumber": "5207420265"
			},
			"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Google_Marlin_Slate?$device-med$&fmt=jpeg&wid=75&hei=150",
			"mobileAppImageName": null,
			"npaNxxnumber": "214-287-XXXX",
			"modDevice": true,
			"npnxxCustomerSelection": null,
			"npaNxxdetails": null,
			"manufactureName": "Google",
			"color": "Quite Black",
			"size": "32GB",
			"numberShareDevice": false,
			"numberSharedMtn": null,
			"deviceNickName": null,
			"numberSharedDeviceName": null,
			"portInDetails": null
		  }
		],
		"npaNxxdetails": {
		  "zipCode": null,
		  "state": null,
		  "city": null,
		  "success": false,
		  "mtns": null,
		  "states": null,
		  "cities": null
		},
		"deviceAddressUpdated": false,
		"accessories": null
	  },
	  "checkoutStates": {
		"shippingAddressRequired": false,
		"shippingAddressChangeRequired": false,
		"shippingMethodRequired": false,
		"paymentRequired": false,
		"pastDuePaymentRequired": false,
		"showPaymentSection": true,
		"showShippingAddress": true,
		"showDeliveryMethod": true,
		"newCard": false,
		"cvvNeeded": false
	  },
	  "totalEdgeItemDownPaymentAmount": "0.00",
	  "totalEdgeUpAmount": "0.00",
	  "totalEdgeUpBuyOutAmount": "0.00",
	  "multiOrderDetails": [
		{
		  "clientOrderRefernceNumber": "924042362448974",
		  "flow": "EUP",
		  "subOrderId": null
		},
		{
		  "clientOrderRefernceNumber": "924042359205012",
		  "flow": "AAL",
		  "subOrderId": null
		}
	  ],
	  "hasRio": false,
	  "splitShipment": false
	}
};
*/