exports.submitProtectionJSON = {
  "output": {
    "tmpMdOpted": false,
    "checkoutStates": {
      "shippingAddressRequired": false,
      "shippingAddressChangeRequired": false,
      "shippingNameChangeRequired": false,
      "poBoxShippingAddress": false,
      "shippingAddressValidationError": false,
      "shippingMethodRequired": false,
      "paymentRequired": false,
      "pastDuePaymentRequired": false,
      "showPaymentSection": true,
      "showShippingAddress": true,
      "showDeliveryMethod": true,
      "newCard": false,
      "cvvNeeded": false,
      "contactInfoRequired": false,
      "instantCreditAllocationsChanged": false,
      "instantCreditOrder": false,
      "tradesExceedItems": false,
      "creditCardZipEditable": true,
      "vzProtect": false,
      "vzProtectMultiDevice": false,
      "batteryShippingNotAllowedStates": false,
      "disableSubmitOrderForOPALUser": false
    },
    "stepsCompleted": null,
    "shippingInfo": {
      "shippingInfoUpdated": false,
      "sameAsBilling": true,
      "ispuEligibleFlag": true,
      "addressInfo": {
        "firstName": "KENNY",
        "lastName": "REYES",
        "companyName": null,
        "address1": "101 MURPHY INDUSTRIAL BLVD",
        "address2": null,
        "city": "Bremen",
        "state": "GA",
        "zipcode": "30110",
        "businessName": null,
        "postalCode": null,
        "email": "VZW@VZW.COM",
        "phoneNumber": "7705875888"
      },
      "contactInfo": {
        "emailAddress": "VZW@VZW.COM",
        "phoneNumber": "7705875888",
        "firstName": "KENNY",
        "lastName": "REYES",
        "smsMdn": null,
        "activeSMSCapableMtnList": null
      },
      "shippingTypesInfo": [
        {
          "estimatedDeliveryDate": "2018-12-03 00:00:00",
          "estimatedDeliveryDateText": "Mon 12/3",
          "shippingDescription": "Free 2 Day by 8pm",
          "shippingOptionId": "SHP002",
          "shippingCost": "0.00",
          "shortDescription": "Free 2 Day by 8pm",
          "active": true,
          "addedShippingOptionId": true,
          "signatureRequired": "true",
          "description": "Estimated to arrive on Mon, Dec 3 if ordered by 4pm today. Signature required.",
          "depletionLocationCode": null,
          "sddAvailableWindows": null
        },
        {
          "estimatedDeliveryDate": "2018-11-30 00:00:00",
          "estimatedDeliveryDateText": "Fri 11/30",
          "shippingDescription": "Next Day by 8pm",
          "shippingOptionId": "SHP004",
          "shippingCost": "12.99",
          "shortDescription": "Next Day by 8pm",
          "active": true,
          "addedShippingOptionId": false,
          "signatureRequired": "true",
          "description": "Estimated to arrive on Fri, Nov 30. Next Day by 8pm. Signature required.",
          "depletionLocationCode": null,
          "sddAvailableWindows": null
        },
        {
          "estimatedDeliveryDate": "2018-11-30 10:30:00",
          "estimatedDeliveryDateText": "Fri 11/30 by 10:30AM",
          "shippingDescription": "Next Day by 10:30am",
          "shippingOptionId": "SHP005",
          "shippingCost": "14.99",
          "shortDescription": "Next Day by 10:30am",
          "active": true,
          "addedShippingOptionId": false,
          "signatureRequired": "true",
          "description": "Estimated to arrive on Fri, Nov 30. Next Day by 10:30am. Signature required.",
          "depletionLocationCode": null,
          "sddAvailableWindows": null
        }
      ],
      "storeDetail": {
        "storeHeader": null,
        "storeName": null,
        "storeAddress": null,
        "deviceAvailable": false,
        "distance": null,
        "appendedStoreTiming": null,
        "longitude": null,
        "storeId": null,
        "netaceLocationCode": null,
        "latitude": null,
        "seoUrlName": null,
        "storeClosingTime": null,
        "directStore": null
      },
      "tradeIn": false,
      "tradeInAddress": null,
      "nonSddEligibleMsg": null,
      "selectedSDDWindow": null,
      "selectedSDDFormattedWindow": null,
      "poboMessage": null,
      "vendorShippingTypesInfo": null,
      "verizonCommerceItemsNames": [
        "iPhone&reg; XS Max"
      ],
      "vendorCommerceItemsNames": null,
      "vendorShippingOptionExists": false,
      "ispudetailsInfo": {
        "storeAddress": null,
        "storeHours": null,
        "storeId": null,
        "storeName": null,
        "phoneNumber": null,
        "distance": null,
        "totalItems": 0,
        "availItems": 0,
        "latitdude": 0.0,
        "longtitude": 0.0,
        "availItemName": null,
        "directStore": null
      }
    },
    "billingInfo": {
      "billToAccountEligible": true,
      "creditCardZipEditable": false,
      "billingAddress": {
        "firstName": "KENNY",
        "lastName": "REYES",
        "businessName": null,
        "zipcode": "30110",
        "state": "GA",
        "address2": null,
        "address1": "101 MURPHY INDUSTRIAL BLVD",
        "companyName": null,
        "city": "Bremen",
        "sameAsShipping": false
      },
      "masterpass3DSecure": null,
      "billToAccountNumber": "XXXX-XXXX-XXXX-0001",
      "creditCardInfo": {
        "savedCardNickName": null,
        "preselectCard": null,
        "creditCardNumber": null,
        "creditCardExpMonth": null,
        "creditCardExpYear": null,
        "billingZipCode": null,
        "creditCardType": null,
        "creditCardVerificationNumber": null,
        "creditCardBIN": null,
        "cvvRequired": false
      },
      "selectedPaymentMode": "BTA",
      "giftCardList": [
        
      ],
      "savedCardInfo": [
        
      ],
      "applePayResponseInfo": null,
      "masterpassResponseInfo": {
        "emailAddress": null,
        "cardType": null,
        "lastDigits": null,
        "creditCardBIN": null,
        "masterpassSelected": false
      },
      "masterpassError": false,
      "masterpassErrorMessage": null,
      "cybersourecPreAuthFailure": false,
      "cybersourecPreAuthFailureErrorMessage": null,
      "paypalEmailAddress": null,
      "expirationMonths": [
        "01",
        "02",
        "03",
        "04",
        "05",
        "06",
        "07",
        "08",
        "09",
        "10",
        "11",
        "12"
      ],
      "expirationYears": [
        "2018",
        "2019",
        "2020",
        "2021",
        "2022",
        "2023",
        "2024",
        "2025",
        "2026",
        "2027"
      ]
    },
    "tradeInPromoDetails": null,
    "transformedTradeInPromoDetails": null,
    "deviceConfigInfo": {
      "devices": [
        {
          "deviceId": "S6581850f904afd2a8dffa315d043ada9_device_1",
          "deviceName": "iPhone&reg; XS Max",
          "deviceSetupMode": null,
          "mtnNumber": "",
          "flow": "EUP",
          "serviceAddress": {
            "firstName": "KENNY",
            "lastName": "REYES",
            "address1": "101 MURPHY INDUSTRIAL BLVD",
            "address2": "",
            "city": "Bremen",
            "state": "GA",
            "zipCode": "30110",
            "emailAddress": "VZW@VZW.COM",
            "phoneNumber": "7705875888"
          },
          "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphonexs-max-spacegrey?$device-med$&fmt=jpeg&wid=75&hei=150",
          "mobileAppImageName": null,
          "npaNxxnumber": null,
          "npnxxCustomerSelection": null,
          "npaNxxdetails": null,
          "manufactureName": "Apple",
          "color": "Space Gray",
          "size": "256GB",
          "numberShareDevice": false,
          "numberSharedMtn": null,
          "deviceNickName": null,
          "numberSharedDeviceName": null,
          "displayImeiId": null,
          "modDevice": false,
          "dueMonthlyTotalDuration": null,
          "portInDetails": null
        }
      ],
      "npaNxxdetails": {
        "zipCode": null,
        "state": null,
        "city": null,
        "success": false,
        "mtns": null,
        "states": null,
        "cities": null
      },
      "deviceAddressUpdated": false,
      "accessories": null
    },
    "termsAndConditionsInfo": {
      "edgeTerms": null,
      "partialMonthChargesText": null,
      "promotionTextCPC": null,
      "agreementText": "<h2>Customer Agreement</h2>\r\r<p><em>(Para una copia de este documento en espanol, visite nuestro website: vzw.com/espanol.)</em></p>\r\r<p><strong>Thanks for choosing Verizon. In this Customer Agreement (\"Agreement\"), you'll find important information about your wireless Service, including:</strong></p>\r\r<ul><li><strong>our ability to make changes to your Service or this Agreement's terms,</strong></li> <li><strong>our liability if things don't work as planned and how any disputes between us must be resolved in arbitration or small claims court.</strong></li></ul>\r\r<h3>My Service</h3>\r\r<p><strong>Your Service terms and conditions are part of this Agreement.</strong> Your Plan includes your monthly allowances and features, where you can use them (your \"Coverage Area\"), and their monthly and pay&ndash;per&ndash;use charges. You can also subscribe to several Optional Services, like international service plans or equipment protection services. Together, your Plan, features you use, and any Optional Services you select are your Service. Your billing and shipping addresses, and your primary place of use, must be within the areas served by the network Verizon owns and operates. The current version of this Agreement and the terms and conditions for your Service are available online at verizonwireless.com</p>\r\r<p>By using the Service you are agreeing to every provision of this Agreement whether or not you have read it. This agreement also applies to all lines on your account and anyone who uses your Service.</p> \r\r<h3>Cancellation</h3>\r<p><strong>You can cancel a line of Service within 14 days of accepting this Agreement without having to pay an early termination fee as long as you return, within the applicable return period, any equipment you purchased from us or one of our authorized agents at a discount in connection with your acceptance of this Agreement, but you'll still have to pay for your Service through that date. If you signed up for Prepaid Service, no refunds will be granted after 14 days or if your account has been activated. See vzw.com/returnpolicy for complete details and information on returning your equipment.</strong></p>\r\r<h3>My Privacy</h3>\r\r<p>We collect personal information about you. By entering into this Agreement, you consent to our data collection, use and sharing practices described in our Privacy Policy. It is your responsibility to notify people who connect devices through your mobile hotspot, Jetpack or wireless router that we will collect, use and share information about their device and use of the Service in accordance with our Privacy Policy. We provide you with choices to limit, in certain circumstances, our use of the data we have about you. You can review these choices at Verizon.com/Privacy#Limits. If there are additional specific advertising and marketing practices for which your consent is necessary, we will seek your consent (such as through the privacy&ndash;related notices you receive when you purchase or use our products and services) before engaging in those practices. You can find out how we use, share and protect the information we collect about you in the Verizon Privacy Policy, available at verizon.com/privacy.</p>\r\r<p>If you subscribe to Service for which usage charges are billed at the end of the billing period (\"Postpay Service\"), we may investigate your credit history at any time. If you'd like the name and address of any credit agency that gives us a credit report about you, just ask.</p>\r\r<p>Many services and applications offered through your device may be provided by third parties. Before you use, link to or download a service or application provided by a third party, you should review the terms of such service or application and applicable privacy policy. Personal information you submit may be read, collected or used by the service or application provider and/or other users of those forums.</p>\r\r<p>You consent to allow Verizon and anyone who collects on our behalf to contact you about your account status, including past due or current charges, using prerecorded calls, email and calls or messages delivered by an automatic telephone dialing system to any wireless phone number, other contact number or email address you provide. Verizon will treat any email address you provide as your private email that is not accessible by unauthorized third parties. Unless you notify us that your wireless service is based in a different time zone, calls will be made to your cellular device during permitted calling hours based upon the time zone affiliated with the mobile telephone number you provide.</p>\r\r<h3>What happens if my Postpay Service is canceled before the end of my contract term?</h3>\r\r<p>If you're signing up for Postpay Service, you're agreeing to subscribe to a line of Service either on a month&ndash;to&ndash;month basis or for a minimum contract term, as shown on your receipt or order confirmation. (If your Service is suspended without billing or at a reduced billing rate, that time doesn't count toward completing your contract term.) Once you've completed your contract term, you'll automatically become a customer on a month&ndash;to&ndash;month basis for that line of Service. <strong>If you purchased a device on a monthly installment agreement and cancel service, you should check that agreement to determine if you may have to immediately pay off the balance. If your line of service has a contract term and you cancel that line, or if we cancel it for good cause, during that contract term, you'll have to pay an early termination fee. If your contract term results from your purchase of an advanced device, your early termination fee will be &#36;350, which will decline by &#36;10 per month upon completion of months 7&ndash;17, &#36;20 per month upon completion of months 18&ndash;22, &#36;60 upon completion of month 23 and will be &#36;0 upon completion of the contract term. For other contract terms, your early termination fee will be &#36;175, which will decline by &#36;5 per month upon completion of months 7&ndash;17, &#36;10 per month upon completion of months 18&ndash;22, &#36;30 upon completion of month 23 and will be &#36;0 upon completion of your contract term. Cancellations will become effective on the last day of that month's billing cycle,</strong> and you are responsible for all charges incurred until then. Also, if you bought your wireless device from an authorized agent or third&ndash;party vendor, you should check whether it charges a separate termination fee.</p>\r\r<h3>Can I take my wireless phone number to another carrier?</h3>\r\r<p>You may be able to transfer, or \"port\", your wireless phone number to another carrier. If you port a number from us, we'll treat it as though you asked us to cancel your Service for that number. After the porting is completed, you won't be able to use our service for that number, but you'll remain responsible for all fees and charges through the end of that billing cycle, just like any other cancellation. If you're a Prepaid customer, you won't be entitled to a refund of any balance on your account. If you port a number to us, please be aware that we may not be able to provide some services right away, such as 911 location services. You don't have any rights to your wireless phone number, except for any right you may have to port it.</p>\r\r<h3>Can I have someone else manage my Postpay account?</h3>\r\r<p>No problem &ndash; just tell us by phone, in person, or in writing. You can appoint someone to manage your Postpay account. The person you appoint will be able to make changes to your account, including adding new lines of Service, buying new wireless devices, and extending your contract term. Any changes that person makes will be treated as modifications to this Agreement.</p>\r\r\r\r<h3>Can Verizon change this Agreement or my Service?</h3>\r\r<p>We may change prices or any other term of your Service or this Agreement at any time, but we'll provide notice first, including written notice if you have Postpay Service. If you use your Service after the change takes effect that means you're accepting the change. If you're a Postpay customer and a change to your Plan or this Agreement has a material adverse effect on you, you can cancel the line of Service that has been affected within 60 days of receiving the notice with no early termination fee if we fail to negate the change after you notify us of your objection to it. Notwithstanding this provision, if we make any changes to the dispute resolution provision of this Agreement, such changes will not affect the resolution of any disputes that arose before such change.</p>\r\r\r\r<h3>My wireless device</h3>\r\r\r\r<p>Your wireless device must comply with Federal Communications Commission regulations, be certified for use on our network, and be compatible with your Service. Please be aware that we may change your wireless device's software, applications or programming remotely, without notice. This could affect your stored data, or how you've programmed or use your wireless device. By activating Service that uses a SIM (Subscriber Identity Module) card, you agree we own the intellectual property and software in the SIM card, that we may change the software or other data in the SIM card remotely and without notice, and we may utilize any capacity in the SIM card for administrative, network, business and/or commercial purposes.</p>\r\r\r<h3>Internet Access</h3>\r\r<p><strong>If you download or use applications, services or software provided by third parties (including voice applications), 911 or E911, or other calling functionality, may work differently than services offered by us, or may not work at all. Please review all terms and conditions of such third&ndash;party products. Verizon Wireless is not responsible for any third&ndash;party information, content, applications or services you access, download or use on your device. You are responsible for maintaining virus and other Internet security protections when accessing these third&ndash;party products or services. For additional information, visit the Verizon Content Policy at responsibility.verizon.com/contentpolicy. For more information regarding content filters visit www.verizonwireless.com/solutions-and-services/content-filters/. For information about our network management practices for our broadband internet access services visit www.verizon.com/about/our-company/open-internet</strong></p>\r\r\r<h3>Where and how does Verizon wireless Service work?</h3>\r\r\r\r<p>Wireless devices use radio transmissions, so unfortunately you can't get Service if your device isn't in range of a transmission signal. And please be aware that even within your Coverage Area, many things can affect the availability and quality of your Service, including network capacity, your device, terrain, buildings, foliage and weather.</p>\r\r\r<h3>How does Verizon calculate my charges?</h3>\r\r<p>You agree to pay all access, usage and other charges that you or any other user of your wireless device incurred. If multiple wireless devices are associated with your account, you agree to pay all charges incurred by users of those wireless devices. For charges based on the amount of time used or data sent or received, we'll round up any fraction to the next full minute or, depending on how you're billed for data usage, the next full megabyte or gigabyte. For outgoing calls, usage time starts when you first press <strong>Send</strong> or the call connects to a network, and for incoming calls, it starts when the call connects to a network (which may be before it rings). Usage time may end several seconds after you press <strong>End</strong> or after the call disconnects. For calls made on our network, we charge only for calls that are answered, including by machines. For Postpay Service, usage cannot always be processed right away and may be included in a later bill, but the usage will still count towards your allowance for the month when the Service was used.</p>\r\r<h3>What Charges are set by Verizon?</h3>\r\r<p>Our charges may also include Federal Universal Service, Regulatory\rand Administrative Charges, and we may also include other charges related to our governmental costs. We set these charges; they aren't taxes, they aren't required by law, they are not necessarily related to anything the government does, they are kept by us in whole or in part, and the amounts and what they pay for may change.</p>\r\r\r<h3>Government Taxes, Fees and Surcharges</h3>\r\r<p>You must pay all taxes, fees and surcharges set by federal, state and local governments. Please note that we may not always be able to notify you in advance of changes to these charges.</p>\r\r\r<h3>What is roaming?</h3>\r\r<p>You're \"roaming\" whenever your wireless device connects to a network outside your Coverage Area or connects to another carrier's network, which could happen even within your Coverage Area. There may be higher rates or extra charges (including charges for long distance, tolls or calls that don't connect), and your data service may be limited or slowed, when roaming.</p>\r\r\r<h3>How can I prevent unintended charges on my bill?</h3>\r\r<p>Many services and applications are accessible on or through wireless devices, including purchases of games, movies, music and other content. Some of these services are provided by Verizon. Others are provided by third parties that may offer the option to bill the charges to your Verizon bill or other methods of payment. Charges may be one&ndash;time or recurring.\rThe amount and frequency of the charges will be disclosed to you or the person using your device or a device associated with your account at the time a purchase is made. If the purchaser chooses to have the charges billed to your account, such charges will become part of the amount due for that billing cycle. Verizon offers tools to block or restrict these services, and to block all billing for third&ndash;party services on your Verizon wireless bill, at verizonwireless.com/myverizon.  We do not support calls to 900, 976 and certain other international premium rate numbers.</p>\r\r\r<h3>How and when can I dispute charges?</h3>\r\r<p>If you're a Postpay customer, you can dispute your bill within 180 days of receiving it, but unless otherwise provided by law or unless you're disputing charges because your wireless device was lost or stolen, you still have to pay all charges until the dispute is resolved. If you're a Prepaid customer, you can dispute a charge within 180 days of the date the disputed charge was incurred. <strong>YOU MAY CALL US TO DISPUTE CHARGES ON YOUR BILL OR ANY SERVICE(S) FOR WHICH YOU WERE BILLED, BUT IF YOU WISH TO PRESERVE YOUR RIGHT TO BRING AN ARBITRATION OR SMALL CLAIMS CASE REGARDING SUCH DISPUTE, YOU MUST WRITE TO US AT THE CUSTOMER SERVICE ADDRESS ON YOUR BILL, OR SEND US A COMPLETED NOTICE OF DISPUTE FORM (AVAILABLE AT VERIZONWIRELESS.COM), WITHIN THE 180&ndash;DAY PERIOD MENTIONED ABOVE. IF YOU DO NOT NOTIFY US IN WRITING OF SUCH DISPUTE WITHIN THE 180&ndash;DAY PERIOD, YOU WILL HAVE WAIVED YOUR RIGHT TO DISPUTE THE BILL OR SUCH SERVICE(S) AND TO BRING AN ARBITRATION OR SMALL CLAIMS CASE REGARDING ANY SUCH DISPUTE.</strong></p>\r\r\r<h3>What are my rights for dropped calls or interrupted Service?</h3>\r\r<p>If you drop a call in your Coverage Area, redial. If it's answered within 5 minutes, call us within 90 days if you're a Postpay customer, or within 45 days if you're a Prepaid customer, and we'll give you a 1&ndash;minute airtime credit. If you're a Postpay customer and you lose Service in your Coverage Area for more than 24 hours in a row and we're at fault, call us within 180 days and we'll give you a credit for the time lost. Please be aware that these are your only rights for dropped calls or interrupted Service.</p>\r\r\r\r<h3>Billing and Payments</h3>\r\r<p>If you're a Postpay customer and we don't get your payment on time, we will charge you a late fee of up to 1.5 percent per month (18 percent per year) on the unpaid balance, or a flat &#36;5 per month, whichever is greater, if allowed by law in the state of your billing address. (If you choose to have your Service billed by another company (pursuant to a Verizon&ndash;approved program), late fees are set by that company and may be higher than our late fees.) Late fees are part of the rates and charges you agree to pay. If you fail to pay on time and we refer your account(s) to a third party for collection, a collection fee will be assessed and will be due at the time of the referral to the third party. The fee will be calculated at the maximum percentage permitted by applicable law, not to exceed 18 percent. We may require a deposit at the time of activation or afterward, or an increased deposit. We'll pay simple interest on any deposit at the rate the law requires. We may apply deposits or payments in any order to any amounts you owe us on any account. If your final credit balance is less than &#36;1, we will refund it only if you ask. If your service is suspended or terminated, you may have to pay a fee to have service reactivated.</p>\r\r<p>If you're a Prepaid customer, you may replenish your balance at any time before the expiration date by providing us with another payment. If you maintain a Prepaid account balance, it may not exceed &#36;1,000 and you may be prevented from replenishing if your balance reaches &#36;1,000. We may apply your payments to any amounts you may owe us if your earlier account replenishment payments had been reversed. We will suspend service when your account reaches the expiration date and any unused balance will be forfeited.</p>\r<p>We may charge you up to &#36;25 for any returned check. If you make a payment, or make a payment arrangement, through a call center representative, we may charge you an Agent Assistance Fee of &#36;7.00.</p>\r\r<h3>What if my wireless device gets lost or stolen?</h3>\r\r<p>We're here to help. It's important that you notify us right away, so we can suspend your Service to keep someone else from using it. If you're a Postpay customer and your wireless device is used after the loss or theft but before you report it, and you want a credit for any charges for that usage, we're happy to review your account activity and any other information you'd like us to consider. Keep in mind that you may be held responsible for the charges if you delayed reporting the loss or theft without good reason, but you don't have to pay any charges you dispute while they are being investigated. If you are a California customer and we haven't given you a courtesy suspension of recurring monthly charges during the past year, we'll give you one for 30 days or until you replace or recover your wireless device, whichever comes first.</p>\r\r\r<h3>What are Verizon's  rights to limit or end Service or end this Agreement?</h3>\r\r<p>We can, without notice, limit, suspend or end your Service or any agreement with you for\rany good cause, including, but not limited to: (1) if you: (a) breach this agreement; (b) resell your Service; (c) use your Service for any illegal purpose, including use that violates trade and economic sanctions and prohibitions promulgated by any US governmental agency;\r(d) install, deploy or use any regeneration equipment or similar mechanism (for example, a repeater) to originate, amplify, enhance, retransmit or regenerate an RF signal without our permission; (e) steal from or lie to us; or, if you're a Postpay customer; (f) do not pay your bill on time; (g) incur charges larger than a required deposit or billing limit, or materially in excess of your monthly access charges (even if we haven't yet billed the charges); (h) provide credit information we can't verify; or (i) are unable to pay us or go bankrupt; or (2) if you, any user of your device or any line of service on your account, or any account manager on your account: (a) threaten, harass, or use vulgar and/or inappropriate language toward our representatives; (b) interfere with our operations; (c) \"spam,\" or engage in other abusive messaging or calling; (d) modify your device from its manufacturer's specifications; or (e) use your Service in a way that negatively affects our network or other customers. We can also temporarily limit your Service for any operational or governmental reason.</p>\r\r\r<h3>Am I eligible for special discounts?</h3>\r\r<p>If you're a Postpay customer, you may be eligible for a discount if you are and remain affiliated with an organization that has an agreement with us. Unless your discount is through a government employee discount program, we may share certain information about your Service (including your name, your wireless telephone number and your total monthly charges) with your organization from time to time to make sure you're still eligible. We may adjust or remove your discount according to your organization's agreement with us, and remove your discount if your eligibility ends or your contract term expires. In any case, this won't be considered to have a material adverse effect on you.</p>\r\r\r<h3>DISCLAIMER OF WARRANTIES</h3>\r\r<p><strong>We make no representations or warranties, express or implied, including, to the extent permitted by applicable law, any implied warranty of merchantability or fitness for a particular purpose, about your Service, your wireless device, or any applications you access through your wireless device. We do not warrant that your wireless device will work perfectly or will not need occasional upgrades or modifications, or that it will not be negatively affected by network&ndash;related modifications, upgrades or similar activity.</p>\r\r<h3>WAIVERS AND LIMITATIONS OF LIABILITY</h3>\r\r<p><strong>You and Verizon both agree to limit claims against each other solely to direct damages. That means neither of us will claim any damages that are indirect, special, consequential, incidental, treble, or punitive. For example, disallowed damages include those arising out of a Service or device failure, unauthorized access or changes to your account or device, or the use of your account or device to access or make changes to an account with another entity, such as a financial entity, without authorization. This limitation and waiver will apply regardless of the theory of liability. It also applies if you bring a claim against one of our suppliers, to the extent we would be required to indemnify the supplier for the claim. </strong> You agree we aren't responsible for problems caused by you or others, or by any act of God. You also agree we aren't liable for missed or deleted voice mails or other messages, or for any information (like pictures) that gets lost or deleted if we work on your device. If another wireless carrier is involved in any problem (for example, while you're roaming), you also agree to any limitations of liability that it imposes.</p>\r\r\r<div style=\"width:auto;height:auto;border:2px solid black; padding: 5px;\">\r\r<h3>HOW DO I RESOLVE DISPUTES WITH VERIZON?</h3>\r\r<p><strong>WE HOPE TO MAKE YOU A HAPPY CUSTOMER, BUT IF THERE'S AN ISSUE THAT NEEDS TO BE RESOLVED, THIS SECTION OUTLINES WHAT'S EXPECTED OF BOTH OF US.</strong></p>\r\r\r\r<p><strong>YOU AND VERIZON BOTH AGREE TO RESOLVE DISPUTES ONLY BY ARBITRATION OR IN SMALL CLAIMS COURT. YOU UNDERSTAND THAT BY THIS AGREEMENT YOU ARE GIVING UP THE RIGHT TO BRING A CLAIM IN COURT OR IN FRONT OF A JURY. WHILE THE PROCEDURES MAY BE DIFFERENT, AN ARBITRATOR CAN AWARD YOU THE SAME DAMAGES AND RELIEF, AND MUST HONOR THE SAME TERMS IN THIS AGREEMENT, AS A COURT WOULD. IF THE LAW ALLOWS FOR AN AWARD OF ATTORNEYS' FEES, AN ARBITRATOR CAN AWARD THEM TOO. WE ALSO BOTH AGREE THAT:</strong></p>\r\r<p>(1) THE FEDERAL ARBITRATION ACT APPLIES TO THIS AGREEMENT. EXCEPT FOR SMALL CLAIMS COURT CASES, ANY DISPUTE THAT IN ANY WAY RELATES TO OR ARISES OUT OF THIS AGREEMENT OR FROM ANY EQUIPMENT, PRODUCTS AND SERVICES YOU RECEIVE FROM US (OR FROM ANY ADVERTISING FOR ANY SUCH PRODUCTS OR SERVICES), INCLUDING ANY DISPUTES YOU HAVE WITH OUR EMPLOYEES OR AGENTS, WILL BE RESOLVED BY ONE OR MORE NEUTRAL ARBITRATORS BEFORE THE AMERICAN ARBITRATION ASSOCIATION (\"AAA\") OR BETTER BUSINESS BUREAU (\"BBB\"). YOU CAN ALSO BRING ANY ISSUES YOU MAY HAVE TO THE ATTENTION OF FEDERAL, STATE, OR LOCAL GOVERNMENT AGENCIES, AND IF THE LAW ALLOWS, THEY CAN SEEK RELIEF AGAINST US FOR YOU. THIS AGREEMENT TO ARBITRATE CONTINUES TO APPLY EVEN AFTER YOU HAVE STOPPED RECEIVING SERVICE FROM US.</p>\r\r\r\r<p>(2) UNLESS YOU AND VERIZON AGREE OTHERWISE, THE ARBITRATION WILL TAKE PLACE IN THE COUNTY OF YOUR BILLING ADDRESS. FOR CLAIMS OVER $10,000, THE AAA'S CONSUMER ARBITRATION RULES WILL APPLY. FOR CLAIMS OF $10,000 OR LESS, THE PARTY BRINGING THE CLAIM CAN CHOOSE EITHER THE AAA'S CONSUMER ARBITRATION RULES OR THE BBB'S RULES FOR BINDING ARBITRATION OR, ALTERNATIVELY, CAN BRING AN INDIVIDUAL ACTION IN SMALL CLAIMS COURT. YOU CAN GET PROCEDURES, RULES AND FEE INFORMATION FROM THE AAA (WWW.ADR.ORG), THE BBB (WWW.BBB.ORG) OR FROM US. FOR CLAIMS OF $10,000 OR LESS, YOU CAN CHOOSE WHETHER YOU'D LIKE THE ARBITRATION CARRIED OUT BASED ONLY ON DOCUMENTS SUBMITTED TO THE ARBITRATOR, OR BY A HEARING IN PERSON OR BY PHONE.</p>\r\r\r\r<p><strong>(3) THIS AGREEMENT DOESN'T ALLOW CLASS OR COLLECTIVE ARBITRATIONS EVEN IF THE AAA OR BBB PROCEDURES OR RULES WOULD. NOTWITHSTANDING ANY OTHER PROVISION OF THIS AGREEMENT, THE ARBITRATOR MAY AWARD MONEY OR INJUNCTIVE RELIEF ONLY IN FAVOR OF THE INDIVIDUAL PARTY SEEKING RELIEF AND ONLY TO THE EXTENT NECESSARY TO PROVIDE RELIEF WARRANTED BY THAT PARTY'S INDIVIDUAL CLAIM. NO CLASS OR REPRESENTATIVE OR PRIVATE ATTORNEY GENERAL THEORIES OF LIABILITY OR PRAYERS FOR RELIEF MAY BE MAINTAINED IN ANY ARBITRATION HELD UNDER THIS AGREEMENT. ANY QUESTION REGARDING THE ENFORCEABILITY OR INTERPRETATION OF THIS PARAGRAPH SHALL BE DECIDED BY A COURT AND NOT THE ARBITRATOR.</strong></p>\r\r\r\r<p>(4) IF EITHER OF US INTENDS TO SEEK ARBITRATION UNDER THIS AGREEMENT, THE PARTY SEEKING ARBITRATION MUST FIRST NOTIFY THE OTHER PARTY OF THE DISPUTE IN WRITING AT LEAST 30 DAYS IN ADVANCE OF INITIATING THE ARBITRATION. NOTICE TO VERIZON SHOULD BE SENT TO VERIZON WIRELESS DISPUTE RESOLUTION MANAGER, ONE VERIZON WAY, BASKING RIDGE, NJ 07920. THE NOTICE MUST DESCRIBE THE NATURE OF THE CLAIM AND THE RELIEF BEING SOUGHT. IF WE ARE UNABLE TO RESOLVE OUR DISPUTE WITHIN 30 DAYS, EITHER PARTY MAY THEN PROCEED TO FILE A CLAIM FOR ARBITRATION. WE'LL REIMBURSE ANY FILING FEE THAT THE AAA OR BBB CHARGES YOU FOR ARBITRATION OF THE DISPUTE. IF YOU PROVIDE US WITH SIGNED WRITTEN NOTICE THAT YOU CANNOT PAY THE FILING FEE, VERIZON WILL PAY THE FEE DIRECTLY TO THE AAA OR BBB. IF THAT ARBITRATION PROCEEDS, WE'LL ALSO PAY ANY ADMINISTRATIVE AND ARBITRATOR FEES CHARGED LATER.</p>\r\r\r<p>(5) WE ALSO OFFER CUSTOMERS THE OPTION OF PARTICIPATING IN A FREE INTERNAL MEDIATION PROGRAM. THIS PROGRAM IS ENTIRELY VOLUNTARY AND DOES NOT AFFECT EITHER PARTY'S RIGHTS IN ANY OTHER ASPECT OF THESE DISPUTE RESOLUTION PROCEDURES. IN OUR VOLUNTARY MEDIATION PROGRAM, WE WILL ASSIGN AN EMPLOYEE WHO'S NOT DIRECTLY INVOLVED IN THE DISPUTE TO HELP BOTH SIDES REACH AN AGREEMENT. THAT PERSON HAS ALL THE RIGHTS AND PROTECTIONS OF A MEDIATOR AND THE PROCESS HAS ALL OF THE PROTECTIONS ASSOCIATED WITH MEDIATION. FOR EXAMPLE, NOTHING SAID IN THE MEDIATION CAN BE USED LATER IN AN ARBITRATION OR LAWSUIT. IF YOU'D LIKE TO KNOW MORE, PLEASE CONTACT US AT VERIZONWIRELESS.COM OR THROUGH CUSTOMER SERVICE. IF YOU'D LIKE TO START THE MEDIATION PROCESS, PLEASE GO TO VERIZONWIRELESS.COM OR CALL CUSTOMER SERVICE FOR A NOTICE OF DISPUTE FORM TO FILL OUT, AND MAIL, FAX OR EMAIL IT TO US ACCORDING TO THE DIRECTIONS ON THE FORM.</p>\r\r\r\r<p>(6) WE MAY, BUT ARE NOT OBLIGATED TO, MAKE A WRITTEN SETTLEMENT OFFER ANYTIME BEFORE THE ARBITRATION HEARING. THE AMOUNT OR TERMS OF ANY SETTLEMENT OFFER MAY NOT BE DISCLOSED TO THE ARBITRATOR UNTIL AFTER THE ARBITRATOR ISSUES AN AWARD ON THE CLAIM. IF YOU DON'T ACCEPT THE OFFER AND THE ARBITRATOR AWARDS YOU AN AMOUNT OF MONEY THAT'S MORE THAN OUR OFFER BUT LESS THAN $5,000, OR IF WE DON'T MAKE YOU AN OFFER, AND THE ARBITRATOR AWARDS YOU ANY AMOUNT OF MONEY BUT LESS THAN $5,000, THEN WE AGREE TO PAY YOU $5,000 INSTEAD OF THE AMOUNT AWARDED. IN THAT CASE WE ALSO AGREE TO PAY ANY REASONABLE ATTORNEYS' FEES AND EXPENSES, REGARDLESS OF WHETHER THE LAW REQUIRES IT FOR YOUR CASE. IF THE ARBITRATOR AWARDS YOU MORE THAN $5,000, THEN WE WILL PAY YOU ONLY THAT AMOUNT.</p>\r\r\r\r<p>(7) AN ARBITRATION AWARD AND ANY JUDGMENT CONFIRMING IT APPLY ONLY TO THAT SPECIFIC CASE; IT CAN'T BE USED IN ANY OTHER CASE EXCEPT TO ENFORCE THE AWARD ITSELF.</p>\r\r\r\r<p><strong>(8) IF FOR SOME REASON THE PROHIBITION ON CLASS ARBITRATIONS SET FORTH IN SUBSECTION (3) CANNOT BE ENFORCED AS TO ALL OR PART OF A DISPUTE, THEN THE AGREEMENT TO ARBITRATE WILL NOT APPLY TO THAT DISPUTE OR PART OF THE DISPUTE.</strong></p>\r\r\r\r<p><strong>(9) IF FOR ANY REASON A CLAIM PROCEEDS IN COURT RATHER THAN THROUGH ARBITRATION, YOU AND VERIZON AGREE THAT THERE WILL NOT BE A JURY TRIAL. YOU AND VERIZON UNCONDITIONALLY WAIVE ANY RIGHT TO TRIAL BY JURY IN ANY ACTION, PROCEEDING OR COUNTERCLAIM ARISING OUT OF OR RELATING TO THIS AGREEMENT IN ANY WAY. IN THE EVENT OF LITIGATION, THIS PARAGRAPH MAY BE FILED TO SHOW A WRITTEN CONSENT TO A TRIAL BY THE COURT.</strong></p></div>\r\r\r\r<h3>About this Agreement</h3>\r\r\r\r<p>If we don't enforce our rights under this agreement in one instance, that doesn't mean we won't or can't enforce those rights in any other instance. You cannot assign this Agreement or any of your rights or duties under it without our permission. However, we may assign this Agreement or any debt you owe us without notifying you. <strong>If you're a Postpay customer, please note that many notices we send to you will show up as messages on your monthly bill. If you have online billing, those notices will be deemed received by you when your online bill is available for viewing. If you get a paper bill, those notices will be deemed received by you three days after we mail the bill to you. If we send other notices to you, they will be considered received immediately if we send them to your wireless device, or to any email or fax number you've given us, or after three days if we mail them to your billing address. If you need to send notices to us, please send them to the customer service address on your latest bill.</strong></p>\r\r\r\r<p><strong>If you're a Prepaid customer and we send notices to you, they will be considered received immediately if we send them to your wireless device or to any email or fax number you've given us, or if we post them as a precall notification on your Service, or after three days if we mail them to the most current address we have for you. If you need to send notices to us, please send them to the Customer Service Prepaid address at verizonwireless.com/contactus</strong></p>\r\r<p><strong>If any part of this agreement, including anything regarding the arbitration process (except for the prohibition on class arbitrations as explained in part 8 of the dispute resolution section above), is ruled invalid, that part may be removed from this agreement.</strong></p>\r\r\r\r<p><strong>This agreement and the documents it incorporates form the entire agreement between us. You can't rely on any other documents, or on what's said by any Sales or Customer Service Representatives, and you have no other rights regarding Service or this agreement.</strong> This Agreement isn't for the benefit of any third party except our parent companies, affiliates, subsidiaries, agents, and predecessors and successors in interest. Except where we've agreed otherwise elsewhere in this agreement, this agreement and any disputes covered by it are governed by federal law and the laws of the state encompassing the area code of your wireless phone number when you accepted this agreement, without regard to the conflicts of laws and rules of that state.</p>\r\r\r\r<p>Last Updated: 10/23/18</p>",
      "eppTermsAndConditions": null,
      "eppCustomerType": false,
      "tradeinTermsandConditions": null,
      "humAgreement": null,
      "deviceProtectionTC": null
    },
    "orderId": "S6581850f904afd2a8dffa315d043ada9",
    "dueToday": "132.40",
    "dueMonthly": "79.08",
    "totalDueMonthlyPlanAndDevice": "79.08",
    "displayUpgradeFee": true,
    "instantCreditDetails": {
      "totalInstantCredit": null,
      "optionalDownPayment": null,
      "twoYearDevicesInstantCredit": null,
      "fullRetailInstantCredit": null,
      "accessoriesInsantCredit": null,
      "taxesInstantCredit": null,
      "accountCredit": null
    },
    "genericPromoMessageAI": null,
    "selectedVendorShippingType": null,
    "subtotalDueToday": "0.00",
    "totalOrderTax": "102.40",
    "depositAmount": "0.00",
    "employeeDiscount": "0.00",
    "saveAmount": "0.00",
    "totalUpgradeFee": "30.00",
    "recycleDeviceAppraise": "0.00",
    "edgeOrderTotalDownPayment": "0.00",
    "flow": null,
    "states": [
      "AK",
      "AL",
      "AR",
      "AZ",
      "CA",
      "CO",
      "CT",
      "DC",
      "DE",
      "FL",
      "GA",
      "HI",
      "IA",
      "ID",
      "IL",
      "IN",
      "KS",
      "KY",
      "LA",
      "MA",
      "MD",
      "ME",
      "MI",
      "MN",
      "MO",
      "MS",
      "MT",
      "NC",
      "ND",
      "NE",
      "NH",
      "NJ",
      "NM",
      "NV",
      "NY",
      "OH",
      "OK",
      "OR",
      "PA",
      "RI",
      "SC",
      "SD",
      "TN",
      "TX",
      "UT",
      "VA",
      "VT",
      "WA",
      "WI",
      "WV",
      "WY"
    ],
    "authInfo": {
      "clients": {
        "CARDINAL3DSECURE": {
          "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJTNjU4MTg1MGY5MDRhZmQyYThkZmZhMzE1ZDA0M2FkYTkiLCJpYXQiOjE1NDM0ODUyODYsImlzcyI6IjVhZDBiYmE3ZmY2MjZiMzEwY2MxMWJmOSIsIk9yZ1VuaXRJZCI6IjU1ZWY0OGUzZjcyM2FhNDMxYzlkZjE0OSIsIlBheWxvYWQiOnsiT3JkZXJEZXRhaWxzIjp7IkN1cnJlbmN5Q29kZSI6IlVTRCIsIkFtb3VudCI6IjEzMjQwIiwiT3JkZXJOdW1iZXIiOiJTNjU4MTg1MGY5MDRhZmQyYThkZmZhMzE1ZDA0M2FkYTkiLCJUcmFuc2FjdGlvbklkIjoiOWYwMWNiMjQtNzFmOS00N2E4LTg1NDMtNmFkZDVkYjZiOTg1In19LCJPYmplY3RpZnlQYXlsb2FkIjp0cnVlLCJSZWZlcmVuY2VJZCI6IlBPU0QxM2E3N2IwNzg5NTE0NzdkYjI1Njk5ZTUzYWM1NTZhMmFzMiIsImV4cCI6MTU0MzQ5MjQ4Nn0.hCzCsBzVFUDP4gebNRIWrXaU--4Vduif0K563UYvGd0",
          "tokenType": "JWT",
          "featuresList": {
            "binDetection": true
          }
        }
      }
    },
    "giftCard1Info": null,
    "giftCard2Info": null,
    "opalImpersonator": null,
    "stackableDataDescription": null,
    "stackbleDataAggregateTotals": null,
    "edgeUpBuyOutAmount": "0.00",
    "edgeupBuyOutMtnList": null,
    "tapFeatureDetails": null,
    "promotionList": null,
    "cpcOrder": false,
    "instantCreditAmount": "0.00",
    "loginMTN": null,
    "useISPUService": true,
    "smartFamilyInCart": false,
    "validateOrderURL": "/od/cust/auth/aiexpresscart/checkout/validateOrder",
    "dppInOrder": true,
    "submitAIOrderURL": "/od/cust/auth/aiexpresscart/checkout/submitOrder",
    "updateDeviceConfigurationURL": "/od/cust/auth/aiexpresscart/update",
    "standaloneAccessories": false,
    "amountAfterInstantCredit": "0.00",
    "datagapDisclosureAgreement": null,
    "pastDueAmount": "0.00",
    "pastDueExist": false,
    "pastDueAmountPaid": false,
    "plans": {
      "dueMonthly": "50.00",
      "dueToday": "0.00",
      "planOnlyDueMonthly": "50.00",
      "items": [
        {
          "planType": "The new Verizon Plan Medium 4 GB",
          "lineAccessCharges": [
            {
              "name": "Apple iPhone&reg; XS Max 256GB in Space Gray",
              "mtn": "",
              "price": "20.00",
              "discountPrice": "0.00",
              "retailPrice": "0.00",
              "hasEcpdDiscount": false,
              "promoMessage": null,
              "originalPrice": "20.00",
              "wasPrice": "20.00",
              "deviceName": "iPhone&reg; XS Max",
              "color": "Space Gray",
              "size": "256GB",
              "introText": null,
              "smartFamily": false,
              "freeTrial": false,
              "amountAfterInstantCredit": "0.00",
              "instantCreditAmount": "0.00",
              "tapfeature": false,
              "disountedInstantCreditAmt": "0.00"
            }
          ],
          "accountAccess": {
            "name": "The new Verizon Plan Medium 4 GB",
            "mtn": null,
            "price": "50.00",
            "discountPrice": "0.00",
            "retailPrice": "0.00",
            "hasEcpdDiscount": false,
            "promoMessage": null,
            "originalPrice": "0.00",
            "wasPrice": "0.00",
            "deviceName": null,
            "color": null,
            "size": null,
            "introText": null,
            "smartFamily": false,
            "freeTrial": false,
            "amountAfterInstantCredit": "0.00",
            "instantCreditAmount": "0.00",
            "tapfeature": false,
            "disountedInstantCreditAmt": "0.00"
          },
          "accountLevelFeatures": null,
          "totalMonthlyPlanCost": "50.00",
          "spoBadgeMessage": null,
          "planDisplayName": "The new Verizon Plan Medium 4 GB",
          "planImageURL": null,
          "planLetter": null,
          "planDescrption": null,
          "planDescription": null,
          "quantity": 0,
          "skuId": null,
          "productId": null,
          "itemAmount": null,
          "itemAmountOriginal": null,
          "dueMonthly": null,
          "dueMonthlyOriginal": null,
          "itemDiscount": null,
          "displayName": null,
          "skuDisplayName": null,
          "listPrice": null,
          "rawTotalAmount": null,
          "planGroupCode": null,
          "autoPayEnabled": false,
          "numberSharePlan": false,
          "planCommerceItemId": null,
          "autoPayPrice": null,
          "autoPayText": null,
          "termsAndConditionKey": null,
          "unitOfMeasure": null,
          "planSize": null,
          "planChanged": false,
          "cpcDone": false
        }
      ],
      "upgradeDevices": null,
      "newDevices": null,
      "existingDevices": null,
      "dueMonthlyPlanWithLAC": null,
      "discountedDueMonthlyPlanWithLAC": null,
      "hasEcpdDiscount": false,
      "totalLineAccessCharges": "20.00"
    },
    "devices": {
      "dueMonthly": 59.08,
      "totalActivationFee": 0.0,
      "deviceTotalDueMonthly": 52.08,
      "dueToday": 0.0,
      "accessories": [
        
      ],
      "accessoriesBundle": [
        
      ],
      "globalPromotions": [
        
      ],
      "items": [
        {
          "deviceName": "iPhone&reg; XS Max",
          "dueMonthly": "52.08",
          "dueToday": "0.00",
          "upgradeFee": "30.00",
          "originalUpgradeFee": "30.00",
          "activationFee": "0.00",
          "dueTodayOriginal": "0.00",
          "dueMonthlyOriginal": null,
          "dueTodayDiscounted": false,
          "dueMonthlyDiscounted": false,
          "mtn": "",
          "sorId": "MT6J2LL/A",
          "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphonexs-max-spacegrey?$device-med$&fmt=jpeg&wid=75&hei=150",
          "protectionFeature": {
            "name": "Tech Coach",
            "mtn": null,
            "price": "7.00",
            "discountPrice": "0.00",
            "retailPrice": "0.00",
            "hasEcpdDiscount": false,
            "promoMessage": null,
            "originalPrice": "0.00",
            "wasPrice": "0.00",
            "deviceName": null,
            "color": null,
            "size": null,
            "introText": null,
            "smartFamily": false,
            "freeTrial": false,
            "amountAfterInstantCredit": "0.00",
            "instantCreditAmount": "0.00",
            "tapfeature": false,
            "disountedInstantCreditAmt": "0.00"
          },
          "optionalFeatures": [
            
          ],
          "installmentBalance": "1249.99",
          "edgeRetailPrice": "1249.99",
          "edgeItemDownPaymentAmount": "0.00",
          "mailInRebateAmount": "0.00",
          "transferredFromMtn": null,
          "devicePromotionList": [
            
          ],
          "bicOfferApplied": false,
          "bicContractPrice": "0.00",
          "bicDiscountedContractPrice": "-1.00",
          "bicAdditionalContractText": null,
          "bicMessageMap": null,
          "edgeUpAmount": 0.0,
          "displayDeviceDueMonthly": 79.08,
          "deviceLACFee": "20.00",
          "manufactureName": "Apple",
          "color": "Space Gray",
          "colorCode": "#807F84",
          "size": "256GB",
          "displayName": "iPhone&reg; XS Max",
          "contractTerm": "99",
          "edgeUpBuyOutAmount": 0.0,
          "fullRetailPrice": "1249.99",
          "alwaysEligibleForUpgrade": false,
          "numberShareDevice": false,
          "activationFeeText": null,
          "numberSharedMtn": null,
          "promoContentText": null,
          "itemOnJaxPlan": false,
          "humCarDetails": null,
          "simDetails": null,
          "imeiId": null,
          "displayImeiId": null,
          "poboDateLabel": null,
          "nickName": null,
          "planCommerceItemId": null,
          "displayMtn": null,
          "dppContractDetails": "You'll see the first installment in your next billing cycle. 24 months,0% APR; Retail price: $1249.99",
          "optionalDownpaymentInstantCredit": null,
          "twoYearInstantCreditAmount": null,
          "fullRetailInstantCreditAmount": null,
          "twoYearPriceOrginal": null,
          "twoYearPriceInstantCreditApplied": null,
          "instantCreditAppliedAmount": 0.0,
          "instantCreditAdjustedPrice": "$0.00",
          "instantCreditFullRetailPrice": null,
          "tradeinPromoDetails": null,
          "numberSharedDeviceName": null,
          "productDetails": {
            "manufacturerDisplayName": "Apple",
            "brandName": "Apple",
            "displayName": "iPhone&reg; XS Max",
            "deviceId": "dev10640019",
            "skuColors": {
              "Silver": {
                "color": "Silver",
                "anySkusInStock": true,
                "allSkusOutOfStock": false,
                "allSkusPreOrder": false,
                "allSkusBackOrder": false,
                "skus": [
                  {
                    "intCapacity": 64,
                    "deviceSkuId": "sku3180118",
                    "deviceSorId": "MT6G2LL/A",
                    "displayName": "Apple&reg; iPhone&reg; Xs Max 64GB in Silver",
                    "capacity": "64GB",
                    "colorCode": "#d7d7d7",
                    "colorName": "Silver",
                    "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphonexs-max-silver?$device-lg$",
                    "inventoryStatus": "1000",
                    "instorePickupFlag": true,
                    "devicePrice": [
                      {
                        "displayOriginalPrice": "45.83",
                        "displayDiscountedPrice": "45.83",
                        "displayEdgeFullRetailPrice": "1099.99",
                        "listPrice": 45.83,
                        "discountPrice": 45.83,
                        "priceListId": "Edge",
                        "contractTerm": 99,
                        "contractDetail": "/mo.",
                        "originalPrice": 45.83,
                        "edgePrice": true,
                        "contractName": "24 Monthly Payments",
                        "discountedPrice": 45.83,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": 1099.99,
                        "contractTitle": "Monthly Device Payment",
                        "loanTerm": "24",
                        "edgeContractText": "$0 Down (for qualified customers) $45.83/mo for 24 months; 0% APR Retail Price: $1099.99",
                        "promoBadgeMessages": null
                      },
                      {
                        "displayOriginalPrice": "1099.99",
                        "displayDiscountedPrice": "1099.99",
                        "displayEdgeFullRetailPrice": null,
                        "listPrice": 1099.99,
                        "discountPrice": 1099.99,
                        "priceListId": "FullRetail",
                        "contractTerm": 0,
                        "contractDetail": null,
                        "originalPrice": 1099.99,
                        "edgePrice": false,
                        "contractName": "Retail Price",
                        "discountedPrice": 1099.99,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": null,
                        "contractTitle": "No Early Termination Fee",
                        "loanTerm": null,
                        "edgeContractText": null,
                        "promoBadgeMessages": null
                      }
                    ]
                  },
                  {
                    "intCapacity": 256,
                    "deviceSkuId": "sku3180121",
                    "deviceSorId": "MT6K2LL/A",
                    "displayName": "Apple&reg; iPhone&reg; Xs Max 256GB in Silver",
                    "capacity": "256GB",
                    "colorCode": "#d7d7d7",
                    "colorName": "Silver",
                    "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphonexs-max-silver?$device-lg$",
                    "inventoryStatus": "1001",
                    "instorePickupFlag": true,
                    "devicePrice": [
                      {
                        "displayOriginalPrice": "52.08",
                        "displayDiscountedPrice": "52.08",
                        "displayEdgeFullRetailPrice": "1249.99",
                        "listPrice": 52.08,
                        "discountPrice": 52.08,
                        "priceListId": "Edge",
                        "contractTerm": 99,
                        "contractDetail": "/mo.",
                        "originalPrice": 52.08,
                        "edgePrice": true,
                        "contractName": "24 Monthly Payments",
                        "discountedPrice": 52.08,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": 1249.99,
                        "contractTitle": "Monthly Device Payment",
                        "loanTerm": "24",
                        "edgeContractText": "$0 Down (for qualified customers) $52.08/mo for 24 months; 0% APR Retail Price: $1249.99",
                        "promoBadgeMessages": null
                      },
                      {
                        "displayOriginalPrice": "1249.99",
                        "displayDiscountedPrice": "1249.99",
                        "displayEdgeFullRetailPrice": null,
                        "listPrice": 1249.99,
                        "discountPrice": 1249.99,
                        "priceListId": "FullRetail",
                        "contractTerm": 0,
                        "contractDetail": null,
                        "originalPrice": 1249.99,
                        "edgePrice": false,
                        "contractName": "Retail Price",
                        "discountedPrice": 1249.99,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": null,
                        "contractTitle": "No Early Termination Fee",
                        "loanTerm": null,
                        "edgeContractText": null,
                        "promoBadgeMessages": null
                      }
                    ]
                  },
                  {
                    "intCapacity": 512,
                    "deviceSkuId": "sku3180124",
                    "deviceSorId": "MT6N2LL/A",
                    "displayName": "Apple&reg; iPhone&reg; Xs Max 512GB in Silver",
                    "capacity": "512GB",
                    "colorCode": "#d7d7d7",
                    "colorName": "Silver",
                    "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphonexs-max-silver?$device-lg$",
                    "inventoryStatus": "1000",
                    "instorePickupFlag": true,
                    "devicePrice": [
                      {
                        "displayOriginalPrice": "60.41",
                        "displayDiscountedPrice": "60.41",
                        "displayEdgeFullRetailPrice": "1449.99",
                        "listPrice": 60.41,
                        "discountPrice": 60.41,
                        "priceListId": "Edge",
                        "contractTerm": 99,
                        "contractDetail": "/mo.",
                        "originalPrice": 60.41,
                        "edgePrice": true,
                        "contractName": "24 Monthly Payments",
                        "discountedPrice": 60.41,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": 1449.99,
                        "contractTitle": "Monthly Device Payment",
                        "loanTerm": "24",
                        "edgeContractText": "$0 Down (for qualified customers) $60.41/mo for 24 months; 0% APR Retail Price: $1449.99",
                        "promoBadgeMessages": null
                      },
                      {
                        "displayOriginalPrice": "1449.99",
                        "displayDiscountedPrice": "1449.99",
                        "displayEdgeFullRetailPrice": null,
                        "listPrice": 1449.99,
                        "discountPrice": 1449.99,
                        "priceListId": "FullRetail",
                        "contractTerm": 0,
                        "contractDetail": null,
                        "originalPrice": 1449.99,
                        "edgePrice": false,
                        "contractName": "Retail Price",
                        "discountedPrice": 1449.99,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": null,
                        "contractTitle": "No Early Termination Fee",
                        "loanTerm": null,
                        "edgeContractText": null,
                        "promoBadgeMessages": null
                      }
                    ]
                  }
                ]
              },
              "Space Gray": {
                "color": "Space Gray",
                "anySkusInStock": true,
                "allSkusOutOfStock": false,
                "allSkusPreOrder": false,
                "allSkusBackOrder": false,
                "skus": [
                  {
                    "intCapacity": 64,
                    "deviceSkuId": "sku3180117",
                    "deviceSorId": "MT6F2LL/A",
                    "displayName": "Apple&reg; iPhone&reg; Xs Max 64GB in Space Gray",
                    "capacity": "64GB",
                    "colorCode": "#807F84",
                    "colorName": "Space Gray",
                    "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphonexs-max-spacegrey?$device-lg$",
                    "inventoryStatus": "1000",
                    "instorePickupFlag": true,
                    "devicePrice": [
                      {
                        "displayOriginalPrice": "45.83",
                        "displayDiscountedPrice": "45.83",
                        "displayEdgeFullRetailPrice": "1099.99",
                        "listPrice": 45.83,
                        "discountPrice": 45.83,
                        "priceListId": "Edge",
                        "contractTerm": 99,
                        "contractDetail": "/mo.",
                        "originalPrice": 45.83,
                        "edgePrice": true,
                        "contractName": "24 Monthly Payments",
                        "discountedPrice": 45.83,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": 1099.99,
                        "contractTitle": "Monthly Device Payment",
                        "loanTerm": "24",
                        "edgeContractText": "$0 Down (for qualified customers) $45.83/mo for 24 months; 0% APR Retail Price: $1099.99",
                        "promoBadgeMessages": null
                      },
                      {
                        "displayOriginalPrice": "1099.99",
                        "displayDiscountedPrice": "1099.99",
                        "displayEdgeFullRetailPrice": null,
                        "listPrice": 1099.99,
                        "discountPrice": 1099.99,
                        "priceListId": "FullRetail",
                        "contractTerm": 0,
                        "contractDetail": null,
                        "originalPrice": 1099.99,
                        "edgePrice": false,
                        "contractName": "Retail Price",
                        "discountedPrice": 1099.99,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": null,
                        "contractTitle": "No Early Termination Fee",
                        "loanTerm": null,
                        "edgeContractText": null,
                        "promoBadgeMessages": null
                      }
                    ]
                  },
                  {
                    "intCapacity": 256,
                    "deviceSkuId": "sku3180120",
                    "deviceSorId": "MT6J2LL/A",
                    "displayName": "Apple&reg; iPhone&reg; Xs Max 256GB in Space Gray",
                    "capacity": "256GB",
                    "colorCode": "#807F84",
                    "colorName": "Space Gray",
                    "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphonexs-max-spacegrey?$device-lg$",
                    "inventoryStatus": "1000",
                    "instorePickupFlag": true,
                    "devicePrice": [
                      {
                        "displayOriginalPrice": "52.08",
                        "displayDiscountedPrice": "52.08",
                        "displayEdgeFullRetailPrice": "1249.99",
                        "listPrice": 52.08,
                        "discountPrice": 52.08,
                        "priceListId": "Edge",
                        "contractTerm": 99,
                        "contractDetail": "/mo.",
                        "originalPrice": 52.08,
                        "edgePrice": true,
                        "contractName": "24 Monthly Payments",
                        "discountedPrice": 52.08,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": 1249.99,
                        "contractTitle": "Monthly Device Payment",
                        "loanTerm": "24",
                        "edgeContractText": "$0 Down (for qualified customers) $52.08/mo for 24 months; 0% APR Retail Price: $1249.99",
                        "promoBadgeMessages": null
                      },
                      {
                        "displayOriginalPrice": "1249.99",
                        "displayDiscountedPrice": "1249.99",
                        "displayEdgeFullRetailPrice": null,
                        "listPrice": 1249.99,
                        "discountPrice": 1249.99,
                        "priceListId": "FullRetail",
                        "contractTerm": 0,
                        "contractDetail": null,
                        "originalPrice": 1249.99,
                        "edgePrice": false,
                        "contractName": "Retail Price",
                        "discountedPrice": 1249.99,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": null,
                        "contractTitle": "No Early Termination Fee",
                        "loanTerm": null,
                        "edgeContractText": null,
                        "promoBadgeMessages": null
                      }
                    ]
                  },
                  {
                    "intCapacity": 512,
                    "deviceSkuId": "sku3180123",
                    "deviceSorId": "MT6M2LL/A",
                    "displayName": "Apple&reg; iPhone&reg; Xs Max 512GB in Space Gray",
                    "capacity": "512GB",
                    "colorCode": "#807F84",
                    "colorName": "Space Gray",
                    "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphonexs-max-spacegrey?$device-lg$",
                    "inventoryStatus": "1001",
                    "instorePickupFlag": true,
                    "devicePrice": [
                      {
                        "displayOriginalPrice": "60.41",
                        "displayDiscountedPrice": "60.41",
                        "displayEdgeFullRetailPrice": "1449.99",
                        "listPrice": 60.41,
                        "discountPrice": 60.41,
                        "priceListId": "Edge",
                        "contractTerm": 99,
                        "contractDetail": "/mo.",
                        "originalPrice": 60.41,
                        "edgePrice": true,
                        "contractName": "24 Monthly Payments",
                        "discountedPrice": 60.41,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": 1449.99,
                        "contractTitle": "Monthly Device Payment",
                        "loanTerm": "24",
                        "edgeContractText": "$0 Down (for qualified customers) $60.41/mo for 24 months; 0% APR Retail Price: $1449.99",
                        "promoBadgeMessages": null
                      },
                      {
                        "displayOriginalPrice": "1449.99",
                        "displayDiscountedPrice": "1449.99",
                        "displayEdgeFullRetailPrice": null,
                        "listPrice": 1449.99,
                        "discountPrice": 1449.99,
                        "priceListId": "FullRetail",
                        "contractTerm": 0,
                        "contractDetail": null,
                        "originalPrice": 1449.99,
                        "edgePrice": false,
                        "contractName": "Retail Price",
                        "discountedPrice": 1449.99,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": null,
                        "contractTitle": "No Early Termination Fee",
                        "loanTerm": null,
                        "edgeContractText": null,
                        "promoBadgeMessages": null
                      }
                    ]
                  }
                ]
              },
              "Gold": {
                "color": "Gold",
                "anySkusInStock": false,
                "allSkusOutOfStock": true,
                "allSkusPreOrder": false,
                "allSkusBackOrder": false,
                "skus": [
                  {
                    "intCapacity": 64,
                    "deviceSkuId": "sku3180119",
                    "deviceSorId": "MT6H2LL/A",
                    "displayName": "Apple&reg; iPhone&reg; Xs Max 64GB in Gold",
                    "capacity": "64GB",
                    "colorCode": "#CFBEA9",
                    "colorName": "Gold",
                    "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphonexs-max-gold?$device-lg$",
                    "inventoryStatus": "1001",
                    "instorePickupFlag": true,
                    "devicePrice": [
                      {
                        "displayOriginalPrice": "45.83",
                        "displayDiscountedPrice": "45.83",
                        "displayEdgeFullRetailPrice": "1099.99",
                        "listPrice": 45.83,
                        "discountPrice": 45.83,
                        "priceListId": "Edge",
                        "contractTerm": 99,
                        "contractDetail": "/mo.",
                        "originalPrice": 45.83,
                        "edgePrice": true,
                        "contractName": "24 Monthly Payments",
                        "discountedPrice": 45.83,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": 1099.99,
                        "contractTitle": "Monthly Device Payment",
                        "loanTerm": "24",
                        "edgeContractText": "$0 Down (for qualified customers) $45.83/mo for 24 months; 0% APR Retail Price: $1099.99",
                        "promoBadgeMessages": null
                      },
                      {
                        "displayOriginalPrice": "1099.99",
                        "displayDiscountedPrice": "1099.99",
                        "displayEdgeFullRetailPrice": null,
                        "listPrice": 1099.99,
                        "discountPrice": 1099.99,
                        "priceListId": "FullRetail",
                        "contractTerm": 0,
                        "contractDetail": null,
                        "originalPrice": 1099.99,
                        "edgePrice": false,
                        "contractName": "Retail Price",
                        "discountedPrice": 1099.99,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": null,
                        "contractTitle": "No Early Termination Fee",
                        "loanTerm": null,
                        "edgeContractText": null,
                        "promoBadgeMessages": null
                      }
                    ]
                  },
                  {
                    "intCapacity": 256,
                    "deviceSkuId": "sku3180122",
                    "deviceSorId": "MT6L2LL/A",
                    "displayName": "Apple&reg; iPhone&reg; Xs Max 256GB in Gold",
                    "capacity": "256GB",
                    "colorCode": "#CFBEA9",
                    "colorName": "Gold",
                    "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphonexs-max-gold?$device-lg$",
                    "inventoryStatus": "1001",
                    "instorePickupFlag": true,
                    "devicePrice": [
                      {
                        "displayOriginalPrice": "52.08",
                        "displayDiscountedPrice": "52.08",
                        "displayEdgeFullRetailPrice": "1249.99",
                        "listPrice": 52.08,
                        "discountPrice": 52.08,
                        "priceListId": "Edge",
                        "contractTerm": 99,
                        "contractDetail": "/mo.",
                        "originalPrice": 52.08,
                        "edgePrice": true,
                        "contractName": "24 Monthly Payments",
                        "discountedPrice": 52.08,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": 1249.99,
                        "contractTitle": "Monthly Device Payment",
                        "loanTerm": "24",
                        "edgeContractText": "$0 Down (for qualified customers) $52.08/mo for 24 months; 0% APR Retail Price: $1249.99",
                        "promoBadgeMessages": null
                      },
                      {
                        "displayOriginalPrice": "1249.99",
                        "displayDiscountedPrice": "1249.99",
                        "displayEdgeFullRetailPrice": null,
                        "listPrice": 1249.99,
                        "discountPrice": 1249.99,
                        "priceListId": "FullRetail",
                        "contractTerm": 0,
                        "contractDetail": null,
                        "originalPrice": 1249.99,
                        "edgePrice": false,
                        "contractName": "Retail Price",
                        "discountedPrice": 1249.99,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": null,
                        "contractTitle": "No Early Termination Fee",
                        "loanTerm": null,
                        "edgeContractText": null,
                        "promoBadgeMessages": null
                      }
                    ]
                  },
                  {
                    "intCapacity": 512,
                    "deviceSkuId": "sku3180125",
                    "deviceSorId": "MT6P2LL/A",
                    "displayName": "Apple&reg; iPhone&reg; Xs Max 512GB in Gold",
                    "capacity": "512GB",
                    "colorCode": "#CFBEA9",
                    "colorName": "Gold",
                    "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphonexs-max-gold?$device-lg$",
                    "inventoryStatus": "1001",
                    "instorePickupFlag": true,
                    "devicePrice": [
                      {
                        "displayOriginalPrice": "60.41",
                        "displayDiscountedPrice": "60.41",
                        "displayEdgeFullRetailPrice": "1449.99",
                        "listPrice": 60.41,
                        "discountPrice": 60.41,
                        "priceListId": "Edge",
                        "contractTerm": 99,
                        "contractDetail": "/mo.",
                        "originalPrice": 60.41,
                        "edgePrice": true,
                        "contractName": "24 Monthly Payments",
                        "discountedPrice": 60.41,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": 1449.99,
                        "contractTitle": "Monthly Device Payment",
                        "loanTerm": "24",
                        "edgeContractText": "$0 Down (for qualified customers) $60.41/mo for 24 months; 0% APR Retail Price: $1449.99",
                        "promoBadgeMessages": null
                      },
                      {
                        "displayOriginalPrice": "1449.99",
                        "displayDiscountedPrice": "1449.99",
                        "displayEdgeFullRetailPrice": null,
                        "listPrice": 1449.99,
                        "discountPrice": 1449.99,
                        "priceListId": "FullRetail",
                        "contractTerm": 0,
                        "contractDetail": null,
                        "originalPrice": 1449.99,
                        "edgePrice": false,
                        "contractName": "Retail Price",
                        "discountedPrice": 1449.99,
                        "upgradeFee": 0.0,
                        "edgeFullRetailPrice": null,
                        "contractTitle": "No Early Termination Fee",
                        "loanTerm": null,
                        "edgeContractText": null,
                        "promoBadgeMessages": null
                      }
                    ]
                  }
                ]
              }
            }
          },
          "deviceSkuId": "sku3180120",
          "promoOfferText": null,
          "promoApplied": false,
          "commerceItemId": "S6581850f904afd2a8dffa315d043ada9_device_1",
          "loanTerm": 24,
          "sbdHeaderMsg": null,
          "percentage": null,
          "waivedActivationFeePromo": false,
          "flow": "EUP",
          "protectionIneligible": false,
          "modDevice": false,
          "dueMonthlyTotalDuration": null,
          "amountAfterInstantCredit": "0.00",
          "instantCreditAmount": "0.00",
          "edgeDevice": true,
          "accessory": false,
          "eupdevice": false,
          "disountedInstantCreditAmt": "0.00"
        }
      ],
      "buddyUpgrade": false
    },
    "masterpassConfigInfo": {
      "checkoutId": "2753b27922fc43329d7213464683752f",
      "allowedCardTypes": [
        "master",
        "amex",
        "diners",
        "discover",
        "jcb",
        "maestro",
        "visa"
      ],
      "shippingLocationProfile": "US",
      "amount": "132.4",
      "cartId": "S6581850f904afd2a8dffa315d043ada9",
      "currency": "USD",
      "suppress3Ds": false,
      "callbackUrl": "https://vzwqa3.verizonwireless.com/od/cust/auth/checkout/masterpass/paymentData"
    },
    "masterpassEnabled": true,
    "paymentMethodRedesign": true,
    "accountLevelDiscountList": null,
    "militaryDiscount": 0.0,
    "accessories": null,
    "accessoriesBundle": null,
    "taxes": [
      {
        "name": "Taxes & Fees",
        "price": "102.40",
        "discountPrice": "0.00",
        "retailPrice": "0.00",
        "originalPrice": "0.00",
        "city": "Bremen",
        "state": "GA",
        "taxCalculated": true,
        "taxNotCalculatedMsg": null,
        "instantCreditApplied": null
      }
    ],
    "dueMonthlyView": {
      "title": "Due Monthly (device only)",
      "dueMonthlyPrice": "79.08",
      "items": [
        {
          "name": "iPhone&reg; XS Max",
          "description": "iPhone&reg; XS Max",
          "manufacturer": "Apple",
          "color": "Space Gray",
          "size": "256GB",
          "priceBreakDown": [
            {
              "lable": "Device Payment",
              "price": "52.08",
              "description": "For 24 months, 0% APR Retail price: $1249.99",
              "linkText": null,
              "linkUrl": null,
              "originalPrice": 0.0,
              "tmpMdOpted": false,
              "discountedEdgeRetailPrice": null,
              "introText": null,
              "sbdPromoTooltip": null,
              "sbdMonthlyPromoDiscount": null,
              "instantCreditDescription": null,
              "promoBadgeMessages": null,
              "tradeinPromoDetails": {
                "tradeInDeviceDppMsg": null,
                "warningMessage": null,
                "tradeInDevicesVos": null,
                "promotionalMessage": null,
                "promotionTooltip": null,
                "promoAmount": null,
                "bicApplied": false
              },
              "smartFamily": false,
              "freeTrial": false,
              "sbdPromoMsg": null,
              "sbdDiscountAmount": 0.0,
              "sbdItemMonthlyAmount": 0.0,
              "itemRetailPrice": 0.0,
              "itemMonthlyPrice": 52.08,
              "itemStrikeThroughPrice": 0.0,
              "noOfBicOccurences": 0,
              "frpBic": false
            },
            {
              "lable": "Line Access Charge",
              "price": "20.00",
              "description": null,
              "linkText": null,
              "linkUrl": null,
              "originalPrice": 0.0,
              "tmpMdOpted": false,
              "discountedEdgeRetailPrice": null,
              "introText": null,
              "sbdPromoTooltip": null,
              "sbdMonthlyPromoDiscount": null,
              "instantCreditDescription": null,
              "promoBadgeMessages": null,
              "tradeinPromoDetails": null,
              "smartFamily": false,
              "freeTrial": false,
              "sbdPromoMsg": null,
              "sbdDiscountAmount": 0.0,
              "sbdItemMonthlyAmount": 0.0,
              "itemRetailPrice": 0.0,
              "itemMonthlyPrice": 0.0,
              "itemStrikeThroughPrice": 0.0,
              "noOfBicOccurences": 0,
              "frpBic": false
            },
            {
              "lable": "Tech Coach",
              "price": "7.00",
              "description": null,
              "linkText": null,
              "linkUrl": null,
              "originalPrice": 0.0,
              "tmpMdOpted": false,
              "discountedEdgeRetailPrice": null,
              "introText": null,
              "sbdPromoTooltip": null,
              "sbdMonthlyPromoDiscount": null,
              "instantCreditDescription": null,
              "promoBadgeMessages": null,
              "tradeinPromoDetails": null,
              "smartFamily": false,
              "freeTrial": false,
              "sbdPromoMsg": null,
              "sbdDiscountAmount": 0.0,
              "sbdItemMonthlyAmount": 0.0,
              "itemRetailPrice": 0.0,
              "itemMonthlyPrice": 0.0,
              "itemStrikeThroughPrice": 0.0,
              "noOfBicOccurences": 0,
              "frpBic": false
            }
          ],
          "nickName": null,
          "planCommerceItemId": null,
          "displayMtn": "",
          "numberShareDevice": false,
          "commerceItemId": "S6581850f904afd2a8dffa315d043ada9_device_1",
          "edge": true,
          "modDevice": false,
          "dueMonthlyTotalDuration": null,
          "dueMonthlyPrice": null
        }
      ],
      "tmpMd": null
    },
    "dueTodayView": {
      "title": "Due in Next Bill",
      "dueTodayPrice": "132.40",
      "items": [
        {
          "name": "iPhone&reg; XS Max",
          "description": "iPhone&reg; XS Max",
          "manufacturer": "Apple",
          "color": "Space Gray",
          "size": "256GB",
          "priceBreakDown": [
            {
              "lable": "Upgrade Fee",
              "price": "30.00",
              "description": null,
              "linkText": null,
              "linkUrl": null,
              "originalPrice": 0.0,
              "tmpMdOpted": false,
              "discountedEdgeRetailPrice": null,
              "introText": null,
              "sbdPromoTooltip": null,
              "sbdMonthlyPromoDiscount": null,
              "instantCreditDescription": null,
              "promoBadgeMessages": null,
              "tradeinPromoDetails": null,
              "smartFamily": false,
              "freeTrial": false,
              "sbdPromoMsg": null,
              "sbdDiscountAmount": 0.0,
              "sbdItemMonthlyAmount": 0.0,
              "itemRetailPrice": 0.0,
              "itemMonthlyPrice": 0.0,
              "itemStrikeThroughPrice": 0.0,
              "noOfBicOccurences": 0,
              "frpBic": false
            }
          ],
          "nickName": null,
          "planCommerceItemId": null,
          "displayMtn": null,
          "numberShareDevice": false,
          "commerceItemId": null,
          "edge": false,
          "modDevice": false,
          "dueMonthlyTotalDuration": null,
          "dueMonthlyPrice": null
        }
      ],
      "accessories": [
        
      ],
      "accessoriesBundle": [
        
      ],
      "additionalCharges": {
        "title": "Additional Charges",
        "items": [
          {
            "name": "Taxes & Fees",
            "price": "102.40",
            "description": "Bremen, GA",
            "instantCreditDescription": null
          },
          {
            "name": "FREE 2 Day by 8pm",
            "price": "0.00",
            "description": null,
            "instantCreditDescription": null
          }
        ]
      },
      "price": null
    },
    "cartDetailURL": "/od/cust/auth/cart/getCartDetails",
    "validateAndPersistDeviceInfoURL": "/od/cust/auth/checkout/validateAndPersistDeviceInfo",
    "npaNxxNumberZipCodeURL": "/od/cust/auth/checkout/npaNxxNumberZipCode",
    "getMarketDetailsURL": "/od/cust/auth/checkout/getMarketDetails",
    "paypalCmpiLookupURL": "/od/cust/auth/checkout/paypal/cmpilookup?triggerFrom=PAYMENT",
    "smsAuthenticationComplete": false,
    "securePinPageUrl": "/od/cust/auth/checkout/securePin",
    "fetchSMSDevicesUrl": "/od/cust/auth/checkout/fetchSMSEnabledDevices",
    "sendSMSUrl": "/od/cust/auth/checkout/sendSMS",
    "validateAuthCodeUrl": "/od/cust/auth/checkout/validateAuthCode",
    "totalActivationFee": "0.00",
    "itemOnJaxPlan": false,
    "comboOrder": false,
    "anyLineFreeVO": null,
    "giftCardsEnabled": false,
    "giftCardsLimit": null,
    "giftCardsUsed": null,
    "submitGiftCardURL": null,
    "checkGiftCardBalanceURL": null,
    "removeGiftCardURL": null,
    "balanceCreditCardAmount": null,
    "totalGiftCardAmount": null,
    "reasonErrorCode": null,
    "reasonErrorMsg": null,
    "validAuthCode": false,
    "numOfAttempts": 0,
    "promoBanners": null,
    "cancelCartURL": "/od/cust/auth/cart/clearCart",
    "mmplanEnabled": false,
    "instantCreditPageURL": null,
    "payPalEnabled": true,
    "securePinEligible": false,
    "ispuBTAPaymentUpdated": false,
    "flipIspuToShipping": false,
    "iconicFlow": true,
    "updatePaymentInfoURL": "/od/cust/auth/checkout/updatePaymentInfo",
    "updateShippingInfoURL": "/od/cust/auth/checkout/updateShippingInfoAI",
    "updateBillingAddressInfoURL": null,
    "handleCardinalResponseURL": "/od/cust/auth/checkout/handleCardinal3DResponse",
    "pastDueCheckoutURL": "/od/cust/auth/checkout/pastDueCheckout",
    "updateDeviceServiceAddressURL": "/od/cust/auth/checkout/updateDeviceServiceAddress",
    "submitOrderURL": "/od/cust/auth/checkout/submitOrder",
    "storeDetailsURL": "/od/cust/auth/cart/checkInStoreAvailability",
    "protectionChangeURL": "/od/cust/auth/protection",
    "protectionRemoveURL": null,
    "mainViewSubTitle": null,
    "pieEnabled": true,
    "eppAccessoryTermsAndConditionDisplay": false,
    "googleMapAPI": {
      "client": "gme-verizonwireless2",
      "channel": "vzw-mobile",
      "draggable": true
    },
    "selectedShippingType": {
      "type": "SHIPPING",
      "shippingTypeName": "FREE 2 Day by 8pm",
      "price": 0.0,
      "discountPrice": 0.0,
      "estimatedDeliveryDate": "2018-11-28 00:00:00",
      "selectedFormattedWindow": null
    },
    "applePaymentRequest": {
      "totalAmount": "132.40",
      "orderTotalLabel": "VERIZON (TOTAL PENDING)",
      "showAvailableShippingOptions": false,
      "requestBillingInfoFromApple": [
        "postalAddress"
      ],
      "requestShippingInfoFromApple": [
        "email"
      ],
      "lineItems": [
        {
          "label": "PAYMENT NOT PROCESSED UNTIL WE VERIFY YOUR ORDER",
          "amount": "0.0",
          "type": "pending"
        }
      ] 
    },
    "applePayEnabled": true,
    "appleMerchantIdentifier": "merchant.com.vzw.test",
    "useISPUCC": true,
    "bannerContent": {
      "returnPolicy": {
        "header": "Don't worry, you have 14 days to make a return or exchange. - should be replaced with Purchase with confidence with our holiday return policy.T",
        "tooltip": "Purchases made between Nov. 22 and Dec. 31, 2018 may be returned or exchanged through Jan. 15, 2019. Otherwise, you may return or exchange wireless devices and accessories purchased from Verizon Wireless within 14 days of purchase. A restocking fee of $50 applies to any return or exchange of a wireless device (excluding Hawaii).T"
      }
    },
    "bicRepresentationChangeEnabled": true,
    "isHLLPlanInOrder": false
  },
  "errorMap": null,
  "statusMessage": "Service completed Successfully.",
  "statusCode": "00"
};
