export const ASYNC_FETCH = 'ASYNC_FETCH';
export const ASYNC_FETCH_SUCCESS = 'ASYNC_FETCH_SUCCESS';
export const ASYNC_FETCH_FAILURE = 'ASYNC_FETCH_FAILURE';
export const ASYNC_FETCH_INVALIDATE = 'ASYNC_FETCH_INVALIDATE';
export const API_SUCCESS_CODE = '00';
export const API_FAILURE_CODE = '01';

/*
Recommended accessories
 */
export const RECOMM_ACC_FETCH = 'RECOMM_ACC_FETCH';
export const RECOMM_ACC_FETCH_SUCCESS = 'RECOMM_ACC_FETCH_SUCCESS';
export const RECOMM_ACC_FETCH_FAILURE = 'RECOMM_ACC_FETCH_FAILURE';
export const RECOMM_ACC_FETCH_INVALIDATE = 'RECOMM_ACC_FETCH_INVALIDATE';