


const mdnJSON = 

/*
{
  "statusCode": "00",
  "errorMap": null,
  "output": {
    "mtnDetailsList": [
      {
        "upgradeEligbile": true,
        "displayMtn": "434.989.1881",
        "mtn": "4349891881",
        "fiveGEligibleMessage": "With this line, get a free 5G moto mod today",
				"isModDevice": true,
				"imei":"355419090492599",
        "encryptedMTN": "clsM8DDe3jcTs8dlDieyXA==",
        "upgradeMessage": null,
        "nickname": "KENNY               B SMITH-1881",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/home_phone_connect_f256vw?$device-thumb$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": {
          "title": "Here's how you can upgrade today.",
          "subtitle": "You have a balance of $480.00",
          "paidToDate": "$0.00 Paid to date",
          "totalPrice": "$480.00 total price",
          "returnOptionTitle": null,
          "returnOptionDescription": null,
          "returnOptionLegal": null,
          "keepOptionTitle": null,
          "keepOptionDescription": "To upgrade this device, it must be paid off in full. If you would like to upgrade today, just pay off the remaining balance of $480.00.",
          "keepOptionLegal": null,
          "legalDisclaimer": null,
          "bogoInd": null,
          "bogoPresent": false,
          "bogoUpgradeMessage": "",
          "displayReturnOption": false,
          "displayKeepOption": false,
          "deviceMismatchText": null,
          "returnOptionAmt": null,
          "keepOptionAmt": "$480.00",
          "edgeUpRequiredPercentage": "100",
          "paidAmountPercentage": "0.0",
          "upgradeSummary": null,
          "deviceAgreementText": "Check out your full Device Payment Agreement online at MyVerizon.com.",
          "deviceAgreementLink": null
        },
        "annualUpgradeMessage": null,
        "deviceType": "Smartphone",
        "familyType": "Phone",
        "familyTypeRestricted": false,
        "contractTermMisMatch": false,
        "brand": "Motorola",
        "deviceId": "355550090644092",
        "twoYearContract": null,
        "annualUpgrade": false,
        "displayDeviceName": "Motorola moto z<sup>3</sup> in ceramic black",
        "deviceName": "MOTO Z3",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge",
          "2 Year"
        ],
        "mtnAddedToTheCart": false,
        "lineSharingIndicator": "",
        "buyoutRestrictedForEdge": false,
        "showTransferUpgrade": false,
        "transferUpgradeInProgress": false,
        "transferredFromMtn": null,
        "transferredToMtn": null,
        "tradeinPromoInfo": null,
        "upgradeEligibilityDate": "08/17/2020",
        "clickTransferUpgrade": false,
        "operatingSystem": "Android",
        "myOffers": null,
        "alwaysEligibleForUpgrade": false,
        "sorDeviceType": "4GE",
        "daccCode": "01153",
        "deviceProdId": "dev10320067",
        "estimatedTradeInValue": "0.00",
        "fiveGOrFourGDevice": true,
        "annualUpgradeWarning": false
      }
    ],
    "accountLevelInEligibleCode": null,
    "accountLevelInEligibleMessage": null,
    "sharedCartDetailsInfo": null,
    "selectedMTN": "",
    "aalRedirect": null,
    "accountLevelInEligibleDetails": null,
    "cartRedirect": "/od/cust/auth/cart/getCartDetails",
    "shopLandingRedirect": "/od/cust/auth/shoplanding/",
    "mtnMainTitle": "Would you like to upgrade or add a new device?",
    "catergoryCode": null,
    "unlimitedPlan": "N",
    "pastDueDetails": null,
    "submitAddALineUrl": "/od/cust/submitaddaline",
    "transferGiverMTNs": null,
    "transferTakerMTNs": null,
    "transferUpgradeUrl": "/od/cust/auth/account/transferUpgrade",
    "enableTradeInForAgent": false,
    "customerType": "B2C",
    "edgeEligible": true,
    "ajaxCallUrl": "/od/cust/submitSummary",
    "ajaxCallSelectedMTN": "/od/cust/mtnDetail/json?flow=EUP&t=",
    "redirectURL": null,
    "myOfferRedirectURL": null,
    "sharedPlan": true,
    "submitByodRedirectUrl": "/od/cust/auth/byod/bring-your-own-device",
    "sharedCartRetrieved": null,
    "aalAllowed": true,
    "byodAllowed": true,
    "aalboxEnable": false
  },
  "cpcRequired": false
};
*/

{
  "statusCode": "00",
  "errorMap": null,
  "output": {
    "mtnDetailsList": [
      {
        "upgradeEligbile": false,
        "displayMtn": "860.306.1264",
        "mtn": "8603061264",
        "encryptedMTN": "WdcpXDF/6Dlk4RQaZu6xHA==",
        "upgradeMessage": null,
        "nickname": "MASARATH              MOHAMMED-1264",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/palm-dubs-gold?$device-thumb$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": null,
        "annualUpgradeMessage": null,
        "deviceType": "Connected Device",
        "familyType": "",
        "familyTypeRestricted": true,
        "contractTermMisMatch": false,
        "brand": "Motorola",
        "deviceId": "35905208014523",
        "twoYearContract": null,
        "annualUpgrade": false,
        "displayDeviceName": "5G MOTO MOD sku",
        "deviceName": "5G MOTO MOD",
        "eligibleUpgradeTypeList": [
          "Retail",
          "Edge",
          "2 Year"
        ],
        "mtnAddedToTheCart": false,
        "lineSharingIndicator": "",
        "buyoutRestrictedForEdge": false,
        "showTransferUpgrade": false,
        "transferUpgradeInProgress": false,
        "transferredFromMtn": null,
        "transferredToMtn": null,
        "tradeinPromoInfo": null,
        "upgradeEligibilityDate": "11/20/2018",
        "clickTransferUpgrade": false,
        "operatingSystem": "Android",
        "fiveGEligibleMessage": "Eligible for 5G moto mod when you upgrade to moto z3",
        "imei": "35905208014523",
        "myOffers": {
          "offerAvailable": false,
          "offers": [
            
          ],
          "primaryCTA": null,
          "secondaryCTA": null,
          "athenaSessionID": null,
          "offerType": null,
          "availOffers": null,
          "cqContent": {
            "cqContent": {
              "added": "Added",
              "seeDetails": "See Details",
              "addThisPromo": "Add this promo"
            },
            "offerListPrimaryCTA": null,
            "selectOfferSecondaryCTA": null,
            "selectOfferPrimaryCTA": {
              "redirectURL": "/od/cust/auth/myoffer/accept"
            },
            "selectOfferDisclaimerCopy": null
          }
        },
        "alwaysEligibleForUpgrade": false,
        "sorDeviceType": "5GA",
        "daccCode": "01193",
        "deviceProdId": "dev10720043",
        "estimatedTradeInValue": "0.00",
        "fiveGOrFourGDevice": true,
        "modDevice": true,
        "annualUpgradeWarning": false
      },
      {
        "upgradeEligbile": true,
        "displayMtn": "469.243.9565",
        "mtn": "4692439565",
        "encryptedMTN": "CiXiLOi7QJb0DQYlumQRpw==",
        "upgradeMessage": null,
        "nickname": "MASARATH              MOHAMMED-9565",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/motorola-moto-z3-exclusive-black?$device-thumb$",
        "inEligibleCode": null,
        "inEligibleDetails": null,
        "loanInfo": null,
        "annualUpgradeMessage": null,
        "deviceType": "Smartphone",
        "familyType": "Phone",
        "familyTypeRestricted": false,
        "contractTermMisMatch": true,
        "brand": "Motorola",
        "deviceId": "35555009201391",
        "twoYearContract": null,
        "annualUpgrade": false,
        "displayDeviceName": "Motorola moto z<sup>3</sup> in ceramic black",
        "deviceName": "MOTO Z3",
        "eligibleUpgradeTypeList": [
          "Retail"
        ],
        "mtnAddedToTheCart": false,
        "lineSharingIndicator": "",
        "buyoutRestrictedForEdge": false,
        "showTransferUpgrade": false,
        "transferUpgradeInProgress": false,
        "transferredFromMtn": null,
        "transferredToMtn": null,
        "tradeinPromoInfo": null,
        "upgradeEligibilityDate": "11/12/2020",
        "clickTransferUpgrade": false,
        "operatingSystem": "Android",
        "fiveGEligibleMessage": "With this line, get a free 5G moto mod today",
        "imei": "35555009201391",
        "myOffers": {
          "offerAvailable": false,
          "offers": [
            
          ],
          "primaryCTA": null,
          "secondaryCTA": null,
          "athenaSessionID": null,
          "offerType": null,
          "availOffers": null,
          "cqContent": {
            "cqContent": {
              "added": "Added",
              "seeDetails": "See Details",
              "addThisPromo": "Add this promo"
            },
            "offerListPrimaryCTA": null,
            "selectOfferSecondaryCTA": null,
            "selectOfferPrimaryCTA": {
              "redirectURL": "/od/cust/auth/myoffer/accept"
            },
            "selectOfferDisclaimerCopy": null
          }
        },
        "alwaysEligibleForUpgrade": false,
        "sorDeviceType": "4GE",
        "daccCode": "01153",
        "deviceProdId": "dev10320067",
        "estimatedTradeInValue": "0.00",
        "fiveGOrFourGDevice": false,
        "modDevice": false,
        "annualUpgradeWarning": false
      }
    ],
    "accountLevelInEligibleCode": null,
    "accountLevelInEligibleMessage": null,
    "sharedCartDetailsInfo": null,
    "selectedMTN": "",
    "aalRedirect": null,
    "accountLevelInEligibleDetails": null,
    "cartRedirect": "/od/cust/auth/cart/getCartDetails",
    "shopLandingRedirect": "/od/cust/auth/shoplanding/",
    "mtnMainTitle": "Would you like to upgrade or add a new device?",
    "catergoryCode": null,
    "unlimitedPlan": "N",
    "pastDueDetails": null,
    "submitAddALineUrl": "/od/cust/submitaddaline",
    "transferGiverMTNs": null,
    "transferTakerMTNs": null,
    "transferUpgradeUrl": "/od/cust/auth/account/transferUpgrade",
    "enableTradeInForAgent": false,
    "customerType": "B2C",
    "edgeEligible": true,
    "ajaxCallUrl": "/od/cust/submitSummary",
    "ajaxCallSelectedMTN": "/od/cust/mtnDetail/json?flow=EUP&t=",
    "redirectURL": null,
    "myOfferRedirectURL": null,
    "sharedPlan": false,
    "submitByodRedirectUrl": "/od/cust/auth/byod/bring-your-own-device",
    "aalAllowed": true,
    "byodAllowed": true,
    "aalboxEnable": true,
    "sharedCartRetrieved": null
  },
  "cpcRequired": false
};

export default mdnJSON;
