const accessoriesJSON = {
  "output": {
    "selectedDeviceName": "Pixel 2 XL",
    "addToCartUrl": "/od/cust/auth/cart/addOrRemoveAccessory",
    "nextCTALink": "/od/cust/auth/cart/getCartDetails",
    "mtnDetailUrl": "/od/cust/auth/mtnDetail?ignoreCache=true",
    "recommendedAccessoriesDetails": [
      {
        "brand": "mophie",
        "displayName": "powerstation XXL 20000",
        "capacity": 0,
        "productID": "acc6520110",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/mophie-powerstation-xxl-20000-space-gray-mophpsxxl20gry-iset?$acc-med$",
        "connectedDevice": false,
        "pdpUrl": "/od/cust/auth/accessoryDetails/?accProdId=acc6520110",
        "skuDetails": [
          {
            "id": "sku2090593",
            "quantity": 0,
            "type": null,
            "skuId": null,
            "productId": null,
            "sorId": "MOPHPSXXL20GRY",
            "itemAmount": 0,
            "itemAmountOriginal": 0,
            "dueMonthly": 0,
            "dueMonthlyOriginal": null,
            "itemDiscount": 0,
            "displayName": null,
            "skuDisplayName": null,
            "listPrice": 0,
            "rawTotalAmount": 0,
            "pricingDetails": null,
            "orderId": null,
            "version": 0,
            "delete": false,
            "inventoryLevel": 0,
            "taxDetails": null,
            "itemTaxes": 0,
            "deviceLineItemId": null,
            "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/mophie-powerstation-xxl-20000-space-gray-mophpsxxl20gry-iset?$acc-med$",
            "bogoType": null,
            "recycleStateInd": null,
            "color": true,
            "size": null,
            "capacity": null,
            "lastModifiedDate": null,
            "deviceManufacturerName": null,
            "accessoryType": null,
            "ispuEligibleFlag": true,
            "bundleSkuLineItems": null,
            "bundleDesciption": null,
            "vzwSbdOfferlist": null,
            "promotions": null,
            "purchasePath": null,
            "priceType": null,
            "appleCare": false,
            "expectedShippingDate": null,
            "shipCommitInd": null,
            "sameDayDelivery": false,
            "skipEcpdDiscount": false,
            "networkExtenderFlag": null,
            "subclasscode": null,
            "recycleCreditAllocatedAmount": 0,
            "ecpdItemAmount": null,
            "ecpdItemDiscount": 0,
            "standaloneaccessory": false,
            "batteryAccessory": false,
            "accSeoUrl": null,
            "featureDropped": false,
            "name": "powerstation XXL 20000 - Space Gray",
            "price": "99.99",
            "discountedPrice": null,
            "preSelected": true,
            "comingSoonAcc": false,
            "inCart": false,
            "learnMoreLink": null,
            "colorCodes": [
              "#807F84"
            ],
            "inventoryStatus": 0,
            "skuStockStatus": null,
            "colorDisplayName": "Space Gray",
            "pdpUrl": "/od/cust/auth/accessoryDetails/?accProdId=acc6520110#/chooseCapacity/skuId=sku2090593",
            "sizeDisplayName": null,
            "available": true,
            "sizeAvailable": false
          },
          {
            "id": "sku2090600",
            "quantity": 0,
            "type": null,
            "skuId": null,
            "productId": null,
            "sorId": "MOPHPSXXL20RGLD",
            "itemAmount": 0,
            "itemAmountOriginal": 0,
            "dueMonthly": 0,
            "dueMonthlyOriginal": null,
            "itemDiscount": 0,
            "displayName": null,
            "skuDisplayName": null,
            "listPrice": 0,
            "rawTotalAmount": 0,
            "pricingDetails": null,
            "orderId": null,
            "version": 0,
            "delete": false,
            "inventoryLevel": 0,
            "taxDetails": null,
            "itemTaxes": 0,
            "deviceLineItemId": null,
            "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/mophie-powerstation-xxl-20000-rose-gold-mophpsxxl20rgld-iset?$acc-med$",
            "bogoType": null,
            "recycleStateInd": null,
            "color": true,
            "size": null,
            "capacity": null,
            "lastModifiedDate": null,
            "deviceManufacturerName": null,
            "accessoryType": null,
            "ispuEligibleFlag": true,
            "bundleSkuLineItems": null,
            "bundleDesciption": null,
            "vzwSbdOfferlist": null,
            "promotions": null,
            "purchasePath": null,
            "priceType": null,
            "appleCare": false,
            "expectedShippingDate": null,
            "shipCommitInd": null,
            "sameDayDelivery": false,
            "skipEcpdDiscount": false,
            "networkExtenderFlag": null,
            "subclasscode": null,
            "recycleCreditAllocatedAmount": 0,
            "ecpdItemAmount": null,
            "ecpdItemDiscount": 0,
            "standaloneaccessory": false,
            "batteryAccessory": false,
            "accSeoUrl": null,
            "featureDropped": false,
            "name": "powerstation XXL 20000 - Rose Gold",
            "price": "99.99",
            "discountedPrice": null,
            "preSelected": true,
            "comingSoonAcc": false,
            "inCart": false,
            "learnMoreLink": null,
            "colorCodes": [
              "#edccbd"
            ],
            "inventoryStatus": 0,
            "skuStockStatus": null,
            "colorDisplayName": "Rose Gold",
            "pdpUrl": "/od/cust/auth/accessoryDetails/?accProdId=acc6520110#/chooseCapacity/skuId=sku2090600",
            "sizeDisplayName": null,
            "available": true,
            "sizeAvailable": false
          }
        ]
      },
      {
        "brand": "Verizon",
        "displayName": "USB-C Car and Wall Charger Combo Pack",
        "capacity": 0,
        "productID": "acc7040017",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/verizon-usb-c-car-and-wall-charger-combo-pack-combopdtype-m-55193-iset?$acc-med$",
        "connectedDevice": false,
        "pdpUrl": "/od/cust/auth/accessoryDetails/?accProdId=acc7040017",
        "skuDetails": [
          {
            "id": "sku2230161",
            "quantity": 0,
            "type": null,
            "skuId": null,
            "productId": null,
            "sorId": "COMBOPDTYPE-M",
            "itemAmount": 0,
            "itemAmountOriginal": 0,
            "dueMonthly": 0,
            "dueMonthlyOriginal": null,
            "itemDiscount": 0,
            "displayName": null,
            "skuDisplayName": null,
            "listPrice": 0,
            "rawTotalAmount": 0,
            "pricingDetails": null,
            "orderId": null,
            "version": 0,
            "delete": false,
            "inventoryLevel": 0,
            "taxDetails": null,
            "itemTaxes": 0,
            "deviceLineItemId": null,
            "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/verizon-usb-c-car-and-wall-charger-combo-pack-combopdtype-m-55193-iset?$acc-med$",
            "bogoType": null,
            "recycleStateInd": null,
            "color": false,
            "size": null,
            "capacity": null,
            "lastModifiedDate": null,
            "deviceManufacturerName": null,
            "accessoryType": null,
            "ispuEligibleFlag": true,
            "bundleSkuLineItems": null,
            "bundleDesciption": null,
            "vzwSbdOfferlist": null,
            "promotions": null,
            "purchasePath": null,
            "priceType": null,
            "appleCare": false,
            "expectedShippingDate": null,
            "shipCommitInd": null,
            "sameDayDelivery": false,
            "skipEcpdDiscount": false,
            "networkExtenderFlag": null,
            "subclasscode": null,
            "recycleCreditAllocatedAmount": 0,
            "ecpdItemAmount": null,
            "ecpdItemDiscount": 0,
            "standaloneaccessory": false,
            "batteryAccessory": false,
            "accSeoUrl": null,
            "featureDropped": false,
            "name": "USB-C Car and Wall Charger Combo Pack",
            "price": "69.99",
            "discountedPrice": null,
            "preSelected": true,
            "comingSoonAcc": false,
            "inCart": false,
            "learnMoreLink": null,
            "colorCodes": null,
            "inventoryStatus": 0,
            "skuStockStatus": null,
            "colorDisplayName": null,
            "pdpUrl": null,
            "sizeDisplayName": null,
            "available": true,
            "sizeAvailable": false
          }
        ]
      },
      {
        "brand": "Verizon",
        "displayName": "Micro USB to USB Type-C Adapter",
        "capacity": 0,
        "productID": "acc6520238",
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/vzw-micro-usb-type-c-adapter-typectomicro-iset?$acc-med$",
        "connectedDevice": false,
        "pdpUrl": "/od/cust/auth/accessoryDetails/?accProdId=acc6520238",
        "skuDetails": [
          {
            "id": "sku2090847",
            "quantity": 0,
            "type": null,
            "skuId": null,
            "productId": null,
            "sorId": "MICROTOTYPEC",
            "itemAmount": 0,
            "itemAmountOriginal": 0,
            "dueMonthly": 0,
            "dueMonthlyOriginal": null,
            "itemDiscount": 0,
            "displayName": null,
            "skuDisplayName": null,
            "listPrice": 0,
            "rawTotalAmount": 0,
            "pricingDetails": null,
            "orderId": null,
            "version": 0,
            "delete": false,
            "inventoryLevel": 0,
            "taxDetails": null,
            "itemTaxes": 0,
            "deviceLineItemId": null,
            "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/vzw-micro-usb-type-c-adapter-typectomicro-iset?$acc-med$",
            "bogoType": null,
            "recycleStateInd": null,
            "color": false,
            "size": null,
            "capacity": null,
            "lastModifiedDate": null,
            "deviceManufacturerName": null,
            "accessoryType": null,
            "ispuEligibleFlag": true,
            "bundleSkuLineItems": null,
            "bundleDesciption": null,
            "vzwSbdOfferlist": null,
            "promotions": null,
            "purchasePath": null,
            "priceType": null,
            "appleCare": false,
            "expectedShippingDate": null,
            "shipCommitInd": null,
            "sameDayDelivery": false,
            "skipEcpdDiscount": false,
            "networkExtenderFlag": null,
            "subclasscode": null,
            "recycleCreditAllocatedAmount": 0,
            "ecpdItemAmount": null,
            "ecpdItemDiscount": 0,
            "standaloneaccessory": false,
            "batteryAccessory": false,
            "accSeoUrl": null,
            "featureDropped": false,
            "name": "Micro USB to USB Type-C Adapter",
            "price": "9.99",
            "discountedPrice": null,
            "preSelected": true,
            "comingSoonAcc": false,
            "inCart": false,
            "learnMoreLink": null,
            "colorCodes": null,
            "inventoryStatus": 0,
            "skuStockStatus": null,
            "colorDisplayName": null,
            "pdpUrl": null,
            "sizeDisplayName": null,
            "available": true,
            "sizeAvailable": false
          }
        ]
      }
    ],
    "bundleAccessories": []
  },
  "errorMap": null,
  "statusMessage": "addUpdateAccessory",
  "statusCode": "00"
};

exports.accessoriesJSON = accessoriesJSON;
