/**
 * Created by hmahad on 1/18/2017.
 */
 const cartJSON = {
   output: {
     orderId: 's391238117',
     redirectionURL: null,
     isPOBODeviceInCart: false,
     dueTodayPOBOHeader: null,
     items: [
       {
         deviceProdId: 'dev6640012',
         deviceManufactureName: 'Apple',
         deviceProductDisplayName: 'iPhone&reg; 7',
         colorName: 'Rose Gold',
         capacity: '32GB',
         flow: 'EUP',
         mtn: '9495547008',
         deviceImageUrl: 'https://mobile.vzw.com/hybridClient/is/image/VerizonWireless/iphone7-front-rsgld?$device-mini$',
         activationFee: 0,
         waivedActivationFeePromo: false,
         upgradeFee: 30,
         waivedUpgradeFeePromo: false,
         edgeDevice: true,
         price: 27.08,
         priceText: 'Device payment',
         priceSubTitle: 'For 24 months.0% APR.Retail Price: $649.99',
         edgeItemDownPaymentAmount: 0,
         installmentBalance: 649.99,
         deviceEdgeUpAmount: 0,
         deviceEdgeBuyOutAmount: 0,
         protectionOption: {
           name: 'Decline Equipment Protection',
           price: 0,
           featureType: 'INSURANCE',
         },
         commerceItemId: 'SDC206648621',
         deviceSkuId: 'sku2150054',
         deviceSORId: 'MNAF2LL/A',
         lacPrice: 20,
         lacText: null,
         numberShareDevice:true,
         changeNumShareUrl: "numberSharePrompt",
         inventoryStatus: 'InStock',
         inventoryAvailableDate: null,
         hasEcpdDiscount: false,
         hasEcpdDiscountForDevicePayment: false,
         devicePromotionList: [

         ],
         bicOfferApplied: false,
         bicContractPrice: 0,
         bicDiscountedContractPrice: 0,
         bicSavings: 0,
         bicMessage: null,
         bicMessagetooltip: null,
       },
     ],
     accessories: null,
     taxDetails: {
       taxPrice: 50.37,
       cityStateString: 'Irvine, CA',
       stateTaxLabel: null,
       zipCode: null,
     },
     totalDueToday: 80.37,
     totalDueMonthly: 97.08,
     employeeDiscount: 0,
     pastDueBalance: 0,
     emptyCartFlag: false,
     edgeContractDeviceInCart: true,
     totalEdgeUpAmount: 0,
     totalEdgeUpBuyOutAmount: 0,
     totalEdgeOrderDownPayment: 0.0,
     tradeInCredit: 0,
     tradeInPromoDetails: null,
     promotionList: [

     ],
     cartMessages: {
       cartReadyforCheckout: true,
       message: null,
       code: null,
     },
     cartItemCount: 0,
     mailInRebateTotal: 0,
     mailInRebateDetails: null,
     promoCodes: null,
     promoCodeHeader: 'Promo Code? Lucky you.',
     promoCodeLabel: 'Promo code',
     addAnotherPromoCodeText: 'Add another promo code',
     applyBtn: 'Apply',
     emptyCartMessage: 'There are no items in your cart',
     shopBtn: 'Shop',
     tradeInPromoEligible: true,
     eligibleForSingleDeviceRibbon: false,
     eligibleForMultiDeviceAllocation: false,
     retrieveCartSuccessful: false,
     standaloneAccessories: false,
     dueTodayText: 'Due Today',
     dueMonthlyText: 'Due Monthly',
     mainCartHeader: 'Time to review your cart',
     mainCartSubTitle: 'Enjoy free 2 day shipping',
     shopMoreBtnText: 'Shop More',
     checkoutBtn: 'Checkout',
     editBtn: 'Edit',
     removeLinkText: 'Remove',
     mainCartFooterText: 'Want to start over?',
     mainCartFooterLinkText: ' Empty your cart',
     shopMoreLink: '/vzw/devices/',
     activationFeeText: 'Activation Fee',
     waivedActivationText: 'Waived Activation Fee',
     upgradeFeeText: 'Upgrade Fee',
     waivedUpgradeFeeText: 'Waived Upgrade Fee',
     saveBtnLabel: 'Save',
     zipCodeHeader: 'Please enter a new ZIP code',
     tradeInCreditHeader: 'Trade in credit for this device',
     tradeInFooterLink: 'Tell me more',
     tradeInOfferDetailsHeader: 'Offer Details',
     tradeInOfferDetailsMsg: 'long block of text',
     tradeInConfirmationBtn: 'Got it',
   },
   ErrorMap: null,
   statusMessage: 'Service completed Successfully.',
   statusCode: '00',
 };

 export default cartJSON;
