/**
 * Created by hmahad on 1/18/2017.
 */
 const cartJSON =  {
  "statusCode": "00",
  "output": {
    "orderId": "SDC3696a56c01a9a4e1713198742890ff34{ss1}",
    "tradeInPromoDetails": {
      "tradeInDeviceDppMsg": "Once you add a device, we'll send a prepaid shipping box so you can mail your trade-in.",
      "tradeInDeviceHeaderMsg": "You'll see an estimated $265.00 credit with 1-2 bill cycles.",
      "tradeInDevices": [
        {
          "success": true,
          "errorMessage": null,
          "warningMessage": null,
          "promoCodeError": null,
          "deviceId": "ID: 9874556568778888",
          "modelImage": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-lg$",
          "displayName": "iPhone 7",
          "color": "Gold",
          "size": "32GB",
          "mtn": null,
          "nickName": null,
          "tradeInDeviceFooter": null,
          "dppCredit": "0.0",
          "originalAppraisalPrice": "265.00",
          "tradeInCredit": "265.00",
          "tradeInCreditMsg": "Trade-in credit: $265.00",
          "offerDetailsMsg": null
        },
        {
          "success": true,
          "errorMessage": null,
          "warningMessage": null,
          "promoCodeError": null,
          "deviceId": "ID: 9874556568778888",
          "modelImage": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-lg$",
          "displayName": "iPhone 7",
          "color": "Gold",
          "size": "32GB",
          "mtn": null,
          "nickName": null,
          "tradeInDeviceFooter": null,
          "dppCredit": "0.0",
          "originalAppraisalPrice": "265.00",
          "tradeInCredit": "265.00",
          "tradeInCreditMsg": "Trade-in credit: $265.00",
          "offerDetailsMsg": null
        }
      ]
    },
    "redirectionURL": null,
    "isPOBODeviceInCart": false,
    "dueTodayPOBOHeader": null,
    "items": [
      {
        "deviceProdId": "dev6640012",
        "deviceManufactureName": "Apple",
        "deviceProductDisplayName": "iPhone&reg; 7",
        "colorName": "Gold",
        "capacity": "128GB",
        "flow": "AAL",
        "mtn": null,
        "displayMtn": "708-227-XXXX",
        "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-med$&fmt=jpeg&wid=75&hei=150",
        "deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device$&bgc=ffffff&wid=158&hei=300",
        "activationFee": "0.00",
        "waivedActivationFeePromo": false,
        "upgradeFee": "0.00",
        "waivedUpgradeFeePromo": false,
        "edgeDevice": true,
        "price": "27.08",
        "priceText": "Device payment",
        "priceSubTitle": "For 24 months, 0% APR.Retail Price: $649.99",
        "edgeItemDownPaymentAmount": "0.00",
        "installmentBalance": "0.00",
        "deviceEdgeUpAmount": "0.00",
        "deviceEdgeBuyOutAmount": "0.00",
        "protectionOption": {
          "name": "Decline Equipment Protection",
          "price": "0.00",
          "featureType": "INS",
          "featureSkuId": "sku401064",
          "hideEditProtection": false,
          "displayMsg": null,
          "tapExists": false
        },
        "commerceItemId": "SDC3696a56c01a9a4e1713198742890ff34{ss1}_device_1",
        "deviceSkuId": "sku2150057",
        "deviceSORId": "MNAL2LL/A",
        "lacPrice": "50.00",
        "lacText": "SMARTPHONE line access",
        "inventoryStatus": "1000",
        "inventoryAvailableDate": null,
        "hasEcpdDiscount": true,
        "hasEcpdDiscountForDevicePayment": false,
        "devicePromotionList": [],
        "bicOfferApplied": false,
        "bicContractPrice": 0,
        "bicDiscountedContractPrice": 0,
        "bicSavings": 0,
        "myOfferWaiveUpgradeFee": false,
        "shipCommitInd": null,
        "promoLACMessage": null,
        "additionalFeatures": [],
        "bicMessage": null,
        "bicMessagetooltip": null,
        "editDeviceUrl": "/od/cust/auth/device/expressconfig/?commerceItemId=SDC3696a56c01a9a4e1713198742890ff34%7Bss1%7D_device_1&deviceProdId=dev6640012&deviceSkuId=sku2150057&editDevice=true&flow=AAL",
        "fullRetailPrice": "649.99",
        "fromSavedCart": false,
        "numberShareDevice": false,
        "numberSharedMtn": null,
        "itemOnJaxPlan": true,
        "humCarDetails": null,
        "monthlyPriceAfterDownPaymentBeforeDiscount": 0,
        "originalFullRetailPrice": 0,
        "hasReducedRetailPrice": false,
        "hasReducedDueMonthly": false,
        "originalDueMonthly": 0,
        "lineAccessPromotionText": null,
        "downPaymentPromotionText": null,
        "contractTerm": "99",
        "deviceType": null,
        "activationFeeText": null,
        "promoOfferText": null,
        "promoApplied": false,
        "portIn": false,
        "deviceNickName": "iPhone&reg; 7",
        "totalNumberShareExtension": 0,
        "sbdOffer": {
          "sbdHeaderMsg": "Congratulations! You are getting this device for only $6.25/mo. instead of $27.08/mo for 24 mos.",
          "sbdPromoMsg": "New line of service & $649.99 device payment purchase required. Less $500.00 bill credit applied to account over 24 mos; begins w/in 1-2 cycles & ends when balance is paid; 0% APR. Upgrade ineligible. Max 5 lines.",
          "sbdDiscountAmount": 500,
          "sbdItemMonthlyAmount": 6.25,
          "itemRetailPrice": 649.99,
          "itemMonthlyPrice": 27.08,
          "itemStrikeThroughPrice": 27.08,
          "noOfBicOccurences": 24
        },
        "hostCommerceItemId": null,
        "trunkMtn": null
      },
      {
        "deviceProdId": "dev8760136",
        "deviceManufactureName": "Google",
        "deviceProductDisplayName": "Pixel 2 XL",
        "colorName": "Just Black",
        "capacity": "64GB",
        "flow": "AAL",
        "mtn": null,
        "displayMtn": "708-227-XXXX",
        "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/GOOGLE_Taiman_Blk?$device-med$&fmt=jpeg&wid=75&hei=150",
        "deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/GOOGLE_Taiman_Blk?$device$&bgc=ffffff&wid=158&hei=300",
        "activationFee": "0.00",
        "waivedActivationFeePromo": false,
        "upgradeFee": "0.00",
        "waivedUpgradeFeePromo": false,
        "edgeDevice": true,
        "price": "35.41",
        "priceText": "Device payment",
        "priceSubTitle": "For 24 months, 0% APR.Retail Price: $849.99",
        "edgeItemDownPaymentAmount": "0.00",
        "installmentBalance": "0.00",
        "deviceEdgeUpAmount": "0.00",
        "deviceEdgeBuyOutAmount": "0.00",
        "protectionOption": {
          "name": "Decline Equipment Protection",
          "price": "0.00",
          "featureType": "INS",
          "featureSkuId": "sku401064",
          "hideEditProtection": false,
          "displayMsg": null,
          "tapExists": false
        },
        "commerceItemId": "SDC3696a56c01a9a4e1713198742890ff34{ss1}_device_2",
        "deviceSkuId": "sku2690595",
        "deviceSORId": "GA00151-US",
        "lacPrice": "50.00",
        "lacText": "SMARTPHONE line access",
        "inventoryStatus": "1000",
        "inventoryAvailableDate": null,
        "hasEcpdDiscount": true,
        "hasEcpdDiscountForDevicePayment": false,
        "devicePromotionList": [],
        "bicOfferApplied": false,
        "bicContractPrice": 0,
        "bicDiscountedContractPrice": 0,
        "bicSavings": 0,
        "myOfferWaiveUpgradeFee": false,
        "shipCommitInd": null,
        "promoLACMessage": null,
        "additionalFeatures": [],
        "bicMessage": null,
        "bicMessagetooltip": null,
        "editDeviceUrl": "/od/cust/auth/device/expressconfig/?commerceItemId=SDC3696a56c01a9a4e1713198742890ff34%7Bss1%7D_device_2&deviceProdId=dev8760136&deviceSkuId=sku2690595&editDevice=true&flow=AAL",
        "fullRetailPrice": "849.99",
        "fromSavedCart": false,
        "numberShareDevice": false,
        "numberSharedMtn": null,
        "itemOnJaxPlan": true,
        "humCarDetails": null,
        "monthlyPriceAfterDownPaymentBeforeDiscount": 0,
        "originalFullRetailPrice": 0,
        "hasReducedRetailPrice": false,
        "hasReducedDueMonthly": false,
        "originalDueMonthly": 0,
        "lineAccessPromotionText": null,
        "downPaymentPromotionText": null,
        "contractTerm": "99",
        "deviceType": null,
        "activationFeeText": null,
        "promoOfferText": null,
        "promoApplied": false,
        "portIn": false,
        "deviceNickName": "Pixel 2 XL",
        "totalNumberShareExtension": 0,
        "sbdOffer": {
          "sbdHeaderMsg": "Congratulations! You are getting this device for only $22.92/mo. instead of $35.41/mo for 24 mos.",
          "sbdPromoMsg": "New line of service & $849.99 device payment purchase required. Less $300.00 bill credit applied to account over 24 mos; begins w/in 1-2 cycles & ends when balance is paid; 0% APR. Upgrade ineligible. Max 5 lines.",
          "sbdDiscountAmount": 300,
          "sbdItemMonthlyAmount": 22.92,
          "itemRetailPrice": 849.99,
          "itemMonthlyPrice": 35.41,
          "itemStrikeThroughPrice": 35.41,
          "noOfBicOccurences": 24
        },
        "hostCommerceItemId": null,
        "trunkMtn": null
      }
    ],
    "accessories": [],
    "accessoriesBundle": null,
    "taxDetails": {
      "taxPrice": "0.00",
      "cityStateString": null,
      "stateTaxLabel": null,
      "zipCode": null
    },
    "totalDueToday": "0.00",
    "totalDueMonthly": "62.49",
    "employeeDiscount": 0,
    "pastDueBalance": "0.00",
    "emptyCartFlag": false,
    "edgeContractDeviceInCart": true,
    "totalEdgeUpAmount": "0.00",
    "totalEdgeUpBuyOutAmount": "0.00",
    "totalEdgeOrderDownPayment": "0.00",
    "tradeInCredit": "-265.00",
    "promotionList": [],
    "cartMessages": {
      "cartReadyforCheckout": true,
      "message": "",
      "code": null
    },
    "cartItemCount": 2,
    "mailInRebateTotal": 0,
    "mailInRebateDetails": null,
    "promoCodes": [],
    "promoCodeHeader": "Promo code? Lucky you.",
    "promoCodeLabel": "Promo code",
    "addAnotherPromoCodeText": "Add another promo code",
    "applyBtn": "Apply",
    "emptyCartMessage": "There are no items in your cart",
    "shopBtn": "Shop",
    "tradeInPromoEligible": true,
    "eligibleForSingleDeviceRibbon": false,
    "eligibleForMultiDeviceAllocation": false,
    "retrieveCartSuccessful": false,
    "standaloneAccessories": false,
    "dueTodayText": "Due today",
    "dueMonthlyText": "Due Monthly",
    "mainCartHeader": "Time to review your cart.",
    "mainCartSubTitle": "Enjoy free 2-day shipping.",
    "shopMoreBtnText": "Shop more",
    "checkoutBtn": "Check out",
    "editBtn": "Edit",
    "removeLinkText": "Remove",
    "mainCartFooterText": "Want to start over?",
    "mainCartFooterLinkText": "Emtpy your cart",
    "shopMoreLink": "/preorder/shoplanding/",
    "activationFeeText": "Activation Fee",
    "waivedActivationText": "Waived Activation Fee",
    "upgradeFeeText": "Upgrade Fee",
    "waivedUpgradeFeeText": "Waived Upgrade Fee",
    "saveBtnLabel": "Save",
    "zipCodeHeader": "Please enter a new ZIP code",
    "tradeInCreditHeader": "Trade-in Credit for this device",
    "tradeInFooterLink": "Tell me more",
    "tradeInOfferDetailsHeader": "Offer Details",
    "tradeInOfferDetailsMsg": "long block of text",
    "tradeInConfirmationBtn": "Got it",
    "lonelyCartMessage": "Your cart is lonely.",
    "checkoutButtonURL": "/preorder/checkout/initiateCheckout",
    "tradeInUrl": "/preorder/promos/tradeauth?gotoCart=true",
    "mainInRebateDetails": null,
    "deviceProtectionDetails": {
      "deviceProtectionDetailsHeader": "device protection details",
      "deviceProtectionDetailsSubTitle": "Five things you need to know about Equipment Protection",
      "deviceProtectionDetailsText": "<div> <p>Cost per Month and Individual Service Availability. Total Mobile Protection (TMP) Single Device and Total Mobile Protection Multi-Device are a combination of multiple products, each of which is available separately per device: Wireless Phone Protection (WPP) $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; Verizon Wireless Extended Warranty (EW) $3.00; and Verizon Tech Coach $7.00. You may also purchase Total Equipment Coverage (TEC) for $7.00/Basic Devices &amp; Tablets or for $9.00/Smartphones &amp; iPhone Devices. TEC is a combination of 2 products, each of which is available separately: WPP $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; and Verizon Wireless EW for $3.00.</p> <p> Applicability and Amount of Deductible.  For lost, stolen and damaged device claims, deductibles are $49 for basic phones and, depending on device, $49-$199 for smartphones and tablets. For a full list of deductibles click here <a href='http://phoneclaim.com/verizon/deductible' target='_blank'>http://phoneclaim.com/verizon/deductible.</a> </p> <p>Claim Limits for loss, stolen and damaged devices. Equipment claim maximum is $400 or $1,500, depending on device, and limited to three claims per 12-month period for TMP Single Device and up to nine claims per 12-month period for TMP Multi-Device.</p> <p>Covered and Replacement Equipment. If your device is lost, stolen or damaged, your accessories are covered too ï¿1Ž2 one each of the following: standard battery, standard car charger, standard case, standard home charger and standard earbud. It is our goal to provide you with a replacement device that is the same color and has the same features, but this cannot be guaranteed. If the same make and model you claim is not available, a similar make and model will be substituted. Your replacement device could be new or refurbished. You may also receive generic accessories with lost, stolen or damaged claims.</p> <p>Cancellation Policy. Change your mind? You can cancel your coverage at any time and receive a pro-rated refund of your monthly fee.</p> </div>"
    },
    "preOrderAlertMsg": "Your order contains one or more items that are not in stock. All items will ship together when everything is available.",
    "bicText": null,
    "hasSubmittedTradein": false,
    "cpcSucessful": false,
    "cpcSucessfulNotification": false,
    "protectionURL": "/od/cust/auth/protection",
    "itemsFromRetrievedCart": false,
    "totalActivationFee": "0.00",
    "itemOnJaxPlan": true,
    "anyLineFreeSPO": null,
    "bicOfferMessage": null,
    "cartMFCompatible": false,
    "cartValidationDetailsVo": {
      "cartReadyforCheckout": true,
      "cartIncompleteCode": null,
      "cartIncompleteMessage": null,
      "orderId": "SDC3696a56c01a9a4e1713198742890ff34{ss1}"
    },
    "cartEdited": false,
    "iconicFlow": false,
    "plans": {
      "planOnlyDueMonthly": "300.00",
      "dueMonthly": "300.00",
      "dueToday": "0.00",
      "items": [
        {
          "planType": "Beyond Unlimited",
          "planSorId": "99231",
          "planProdId": "plan2880001",
          "planSkuId": "sku2580029",
          "planLetter": null,
          "planDescription": "",
          "planDisplayName": "Beyond Unlimited",
          "planChangeURL": null,
          "planImageURL": null,
          "accountAccess": {
            "name": "Beyond Unlimited",
            "price": "300.00",
            "discountPrice": 0,
            "promoMessage": null,
            "hasEcpdDiscount": false,
            "planAmount": "300.00"
          }
        }
      ]
    },
    "removePromoCodeURL": "/od/cust/auth/cart/removePromoCode",
    "applyPromoCodeURL": "/od/cust/auth/cart/applyPromoCode",
    "clearCartURL": "/od/cust/auth/cart/clearCart",
    "addOrUpdateDeviceURL": "/od/cust/auth/cart/addOrUpdateDevice",
    "addOrRemoveAccessoryURL": "/od/cust/auth/cart/addOrRemoveAccessory",
    "changeZipCodeURL": "/od/cust/authcart/changeZipCode/",
    "addOrUpdateFeatureURL": "/od/cust/auth/cart/addOrUpdateFeature",
    "initiateCheckoutURL": "/od/cust/auth/checkout/initiateCheckout",
    "accountMember": false,
    "splitShipment": false
  },
  "errorMap": null,
  "statusMessage": ""
};

 export default cartJSON;
