/**
 * Created by hmahad on 1/18/2017.
 */
 const cartJSON = {
   output: {
     orderId: 'S17822599',
     redirectionURL: null,
     isPOBODeviceInCart: false,
     dueTodayPOBOHeader: null,
     items: [
       {
         deviceProdId: 'dev6640012',
         deviceManufactureName: 'Apple',
         deviceProductDisplayName: 'iPhone&reg; 7',
         colorName: 'Apple Black',
         capacity: '128GB',
         flow: 'EUP',
         mtn: '7046518382',
         displayMtn: '704.651.8382',
         deviceImageUrl: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-matblk?$device-mini$',
         activationFee: 0.0,
         waivedActivationFeePromo: false,
         upgradeFee: 30.0,
         waivedUpgradeFeePromo: false,
         edgeDevice: true,
         price: 31.24,
         priceText: 'Device payment',
         priceSubTitle: 'For 24 months.0% APR.Retail Price: $749.99',
         edgeItemDownPaymentAmount: 0.0,
         installmentBalance: 749.99,
         deviceEdgeUpAmount: 0.0,
         deviceEdgeBuyOutAmount: 0.0,
         protectionOption: {
           name: 'Total Mobile Protection Multi-Device',
           price: 33.0,
           displayMsg: '$33.0 /mo existing charges for all devices manager your protection plan on our website',
           featureType: 'SPO',
         },
         commerceItemId: 'SDC3023082',
         deviceSkuId: 'sku2150060',
         deviceSORId: 'MNAJ2LL/A',
         lacPrice: 20.0,
         lacText: null,
         inventoryStatus: 'InStock',
         inventoryAvailableDate: null,
         hasEcpdDiscount: false,
         hasEcpdDiscountForDevicePayment: false,
         devicePromotionList: [

         ],
         bicOfferApplied: false,
         bicContractPrice: 0.0,
         bicDiscountedContractPrice: 0.0,
         bicSavings: 0.0,
         bicMessage: null,
         bicMessagetooltip: null,
         editDeviceUrl: '/digital/device/deviceOptions/?deviceProdId=dev6640012&editDevice=true&commerceItemId=SDC3023082',
       },
     ],
     accessories: null,
     taxDetails: {
       taxPrice: 56.55,
       cityStateString: 'Charlotte, NC',
       stateTaxLabel: null,
       zipCode: null,
     },
     totalDueToday: 86.55,
     totalDueMonthly: 51.24,
     employeeDiscount: 0,
     pastDueBalance: 0,
     emptyCartFlag: false,
     edgeContractDeviceInCart: true,
     totalEdgeUpAmount: 0,
     totalEdgeUpBuyOutAmount: 0,
     totalEdgeOrderDownPayment: 0.0,
     tradeInCredit: 0.0,
     tradeInPromoDetails: null,
     promotionList: [

     ],
     cartMessages: {
       cartReadyforCheckout: true,
       message: null,
       code: null,
     },
     bicText: "You'll see a  27.08/mo trade-in promo credit within 2-3 billing cycles.",
     cartItemCount: 0,
     mailInRebateTotal: 0,
     mailInRebateDetails: null,
     promoCodes: null,
     promoCodeHeader: 'Promo Code? Lucky you.',
     promoCodeLabel: 'Promo code',
     addAnotherPromoCodeText: 'Add another promo code',
     applyBtn: 'Apply',
     emptyCartMessage: 'There are no items in your cart',
     shopBtn: 'Shop',
     tradeInPromoEligible: true,
     eligibleForSingleDeviceRibbon: false,
     eligibleForMultiDeviceAllocation: false,
     retrieveCartSuccessful: false,
     standaloneAccessories: false,
     dueTodayText: 'Due today',
     dueMonthlyText: 'Due monthly',
     mainCartHeader: 'Time to review your cart.',
     mainCartSubTitle: 'Enjoy free 2-day shipping.',
     shopMoreBtnText: 'Shop more',
     checkoutBtn: 'Check out',
     editBtn: 'Edit',
     removeLinkText: 'Remove',
     mainCartFooterText: 'Want to start over?',
     mainCartFooterLinkText: ' Empty your cart',
     shopMoreLink: '/digital/smartphones/',
     activationFeeText: 'Activation Fee',
     waivedActivationText: 'Waived Activation Fee',
     upgradeFeeText: 'Upgrade Fee',
     waivedUpgradeFeeText: 'Waived Upgrade Fee',
     saveBtnLabel: 'Save',
     zipCodeHeader: 'Please enter a new ZIP code.',
     tradeInCreditHeader: 'Trade in credit for this device',
     tradeInFooterLink: 'Tell me more',
     tradeInOfferDetailsHeader: 'Offer Details',
     tradeInOfferDetailsMsg: 'long block of text',
     tradeInConfirmationBtn: 'Got it',
     lonelyCartMessage: 'Your cart is lonely',
     checkoutButtonURL: '/digital/checkout/initiateCheckout',
     tradeInUrl: '/digital/tradein/prompt?deviceProdId=dev6640012',
     mainInRebateDetails: null,
     deviceProtectionDetails: {
       deviceProtectionDetailsHeader: 'DeviceProtectionDetails',
       deviceProtectionDetailsSubTitle: 'Five things you need to know about Equipment Protection',
       deviceProtectionDetailsText: 'Text Shoud come here',
     },
     preOrderAlertMsg: null,
   },
   ErrorMap: null,
   statusMessage: 'Service completed Successfully.',
   statusCode: '00',
 };

 export default cartJSON;
