const deviceConfigJson = {
  statusCode: '00',
  errorMap: null,
  output: {
    productDetails: {
      badgeRetailIconImageName: null,
      manufacturerDisplayName: 'Samsung',
      badgeTwoYearToolTip: null,
      lineAccess: null,
      dealInStoreStaticUrl: 'https://forms.verizonwireless.com/dgf/optin/2012/06282012_omni_thankyou/index.html',
      cqContent: null,
      badgeEdgeIconImageName: null,
      brandName: 'Samsung',
      categoryName: 'smartphones',
      rectangularBadgeText: null,
      badgeTwoYearIconImageName: null,
      badgeRetailDisplayName: null,
      deviceType: '4G Smartphone',
      badgeEdgeToolTip: null,
      skuDetails: [
        {
          colorName: 'Black',
          imageUrl: 'https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S5_Black?$device-lg$',
          upgradeOptionEllPDPLbl50: null,
          promotionDetails: null,
          restrictionFlag: false,
          upgradeOptionEllPDPLbl70: null,
          devicePrice: [
            {
              mailInRebateAmount: 0,
              priceListId: 'edgeRemainingMonthPriceListId',
              bicOfferApplied: false,
              ecpdDiscountOffer: false,
              bicAdditionalContractText: null,
              edgeFullRetailPrice: 552,
              alwaysEligibleDownPaymentPercentage: null,
              mailInRebateText: null,
              sedEcpdDiscountPercentage: 0,
              selected: true,
              edgeEnabled: true,
              earlyTerminationText: null,
              rebateAmount: 0,
              orgiginalMonthlyPrice: 0,
              alwaysEligibleDownPaymentPercentageText: null,
              orignalFullRetailPrice: 0,
              edgeDownpayment: 276,
              mailInRebateIndicator: false,
              edgeType: null,
              upgradeFee: 0,
              activationFee: 30,
              bicDiscountedContractPrice: 0,
              waivedActivationFeePromo: false,
              discountPrice: 11.5,
              ecpdDiscount: 0,
              bicContractPrice: 0,
              contractDetail: '/mo.',
              contractPrice: '11.50',
              contractTerm: 99,
              originalPrice: 11.5,
              creditOptionVOList: null,
              fullRetailPrice: 552,
              waivedUpgradeFeePromo: false,
              contractTitle: 'For 24 months with $276.00 down. 0% APR Retail Price: $552.00',
              contractName: '24 Monthly Payments',
              contractToDevicePaymentEligibilityInd: false,
              puEligibleFlag: false,
            },
            {
              mailInRebateAmount: 0,
              priceListId: 'fullRetailPriceListId',
              bicOfferApplied: false,
              ecpdDiscountOffer: false,
              bicAdditionalContractText: null,
              edgeFullRetailPrice: 552,
              alwaysEligibleDownPaymentPercentage: null,
              mailInRebateText: null,
              sedEcpdDiscountPercentage: 0,
              selected: false,
              edgeEnabled: false,
              earlyTerminationText: null,
              rebateAmount: 0,
              orgiginalMonthlyPrice: 0,
              alwaysEligibleDownPaymentPercentageText: null,
              orignalFullRetailPrice: 0,
              edgeDownpayment: 0,
              mailInRebateIndicator: false,
              edgeType: null,
              upgradeFee: 0,
              activationFee: 0,
              bicDiscountedContractPrice: 0,
              waivedActivationFeePromo: false,
              discountPrice: 552,
              ecpdDiscount: 0,
              bicContractPrice: 0,
              contractDetail: null,
              contractPrice: '552.00',
              contractTerm: 0,
              originalPrice: 552,
              creditOptionVOList: null,
              fullRetailPrice: 552,
              waivedUpgradeFeePromo: false,
              contractTitle: 'No Early Termination Fee',
              contractName: 'Retail Price',
              contractToDevicePaymentEligibilityInd: false,
              puEligibleFlag: false,
            },
          ],
          skuImageName: 'Samsung_Galaxy_S5_Black',
          upgradeOptionEllPDPTip70: null,
          selected: true,
          upgradeOptionEllPDPTip50: null,
          restrictionMessage: null,
          sameDayDeliveryFlag: false,
          capacity: '16GB',
          inventoryStatus: 1002,
          deviceSkuId: 'sku900083',
          devicePaymentPercentage: '100',
          deviceSorId: 'SMG900VZKV',
          skuListDiscountPricing: {
            skuListPrice: [
              {
                priceListId: 'edgeFullRetailPriceListId',
                price: 552,
              },
              {
                priceListId: 'twoYearPriceListId',
                price: 99.99,
              },
              {
                priceListId: 'edgeFirstMonthPriceListId',
                price: 23,
              },
              {
                priceListId: 'fullRetailPriceListId',
                price: 552,
              },
              {
                priceListId: 'edgeRemainingMonthPriceListId',
                price: 23,
              },
            ],
            skuDiscountPrice: [
              {
                priceListId: 'twoYearPriceListId',
                price: 99.99,
              },
              {
                priceListId: 'fullRetailPriceListId',
                price: 552,
              },
              {
                priceListId: 'edgeRemainingMonthPriceListId',
                price: 23,
              },
            ],
          },
          colorImage: null,
          upgradeOptionCode: 'DP',
          annualUpgradeEligible: false,
          displayName: 'Samsung Galaxy S&reg; 5 in Charcoal Black',
          colorCode: '#000000',
          mobileAppImageName: 'https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S5_Black_front_mf?$device-lg$',
          shippingDateLabel: 'Ships by Jan 11',
          shippingDateStatusCode: 1002,
        },
        {
          colorName: 'White',
          imageUrl: 'https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S5_White?$device-lg$',
          upgradeOptionEllPDPLbl50: null,
          promotionDetails: null,
          restrictionFlag: false,
          upgradeOptionEllPDPLbl70: null,
          devicePrice: [
            {
              mailInRebateAmount: 0,
              priceListId: 'edgeRemainingMonthPriceListId',
              bicOfferApplied: false,
              ecpdDiscountOffer: false,
              bicAdditionalContractText: null,
              edgeFullRetailPrice: 552,
              alwaysEligibleDownPaymentPercentage: null,
              mailInRebateText: null,
              sedEcpdDiscountPercentage: 0,
              selected: true,
              edgeEnabled: true,
              earlyTerminationText: null,
              rebateAmount: 0,
              orgiginalMonthlyPrice: 0,
              alwaysEligibleDownPaymentPercentageText: null,
              orignalFullRetailPrice: 0,
              edgeDownpayment: 276,
              mailInRebateIndicator: false,
              edgeType: null,
              upgradeFee: 0,
              activationFee: 30,
              bicDiscountedContractPrice: 0,
              waivedActivationFeePromo: false,
              discountPrice: 11.5,
              ecpdDiscount: 0,
              bicContractPrice: 0,
              contractDetail: '/mo.',
              contractPrice: '11.50',
              contractTerm: 99,
              originalPrice: 11.5,
              creditOptionVOList: null,
              fullRetailPrice: 552,
              waivedUpgradeFeePromo: false,
              contractTitle: 'For 24 months with $276.00 down. 0% APR Retail Price: $552.00',
              contractName: '24 Monthly Payments',
              contractToDevicePaymentEligibilityInd: false,
              puEligibleFlag: true,
            },
            {
              mailInRebateAmount: 0,
              priceListId: 'fullRetailPriceListId',
              bicOfferApplied: false,
              ecpdDiscountOffer: false,
              bicAdditionalContractText: null,
              edgeFullRetailPrice: 552,
              alwaysEligibleDownPaymentPercentage: null,
              mailInRebateText: null,
              sedEcpdDiscountPercentage: 0,
              selected: false,
              edgeEnabled: false,
              earlyTerminationText: null,
              rebateAmount: 0,
              orgiginalMonthlyPrice: 0,
              alwaysEligibleDownPaymentPercentageText: null,
              orignalFullRetailPrice: 0,
              edgeDownpayment: 0,
              mailInRebateIndicator: false,
              edgeType: null,
              upgradeFee: 0,
              activationFee: 0,
              bicDiscountedContractPrice: 0,
              waivedActivationFeePromo: false,
              discountPrice: 552,
              ecpdDiscount: 0,
              bicContractPrice: 0,
              contractDetail: null,
              contractPrice: '552.00',
              contractTerm: 0,
              originalPrice: 552,
              creditOptionVOList: null,
              fullRetailPrice: 552,
              waivedUpgradeFeePromo: false,
              contractTitle: 'No Early Termination Fee',
              contractName: 'Retail Price',
              contractToDevicePaymentEligibilityInd: false,
              puEligibleFlag: false,
            },
          ],
          skuImageName: 'Samsung_Galaxy_S5_White',
          upgradeOptionEllPDPTip70: null,
          selected: false,
          upgradeOptionEllPDPTip50: null,
          restrictionMessage: null,
          sameDayDeliveryFlag: false,
          capacity: '16GB',
          inventoryStatus: 1000,
          deviceSkuId: 'sku900080',
          devicePaymentPercentage: '100',
          deviceSorId: 'SMG900VZWV',
          skuListDiscountPricing: {
            skuListPrice: [
              {
                priceListId: 'edgeFullRetailPriceListId',
                price: 552,
              },
              {
                priceListId: 'twoYearPriceListId',
                price: 99.99,
              },
              {
                priceListId: 'edgeFirstMonthPriceListId',
                price: 23,
              },
              {
                priceListId: 'fullRetailPriceListId',
                price: 552,
              },
              {
                priceListId: 'edgeRemainingMonthPriceListId',
                price: 23,
              },
            ],
            skuDiscountPrice: [
              {
                priceListId: 'twoYearPriceListId',
                price: 99.99,
              },
              {
                priceListId: 'fullRetailPriceListId',
                price: 552,
              },
              {
                priceListId: 'edgeRemainingMonthPriceListId',
                price: 23,
              },
            ],
          },
          colorImage: null,
          upgradeOptionCode: 'DP',
          annualUpgradeEligible: false,
          displayName: 'Samsung Galaxy S&reg; 5 in Shimmery White',
          colorCode: '#FFFFFF',
          mobileAppImageName: 'https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S5_White_front_mf?$device-lg$',
          shippingDateLabel: null,
          shippingDateStatusCode: 1000,
        },
      ],
      pdpBadgeFullRetail: null,
      creditOptionsAvailabilityVO: null,
      deviceId: 'dev2080010',
      badgeTwoYearDisplayName: null,
      seoCategoryName: 'smartphones',
      marketingTout: null,
      badgeEdgeDisplayName: null,
      circularBadgeText: null,
      canonicalURL: 'smartphones/galaxy-s-5/',
      priceDisclaimer: null,
      displayName: 'Galaxy S&reg; 5',
      pdpBadgePayment: null,
      badgeRetailToolTip: null,
      seoBrandName: 'samsung',
      mobileAppImageName: 'https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S5_Black_front_mf?$device-lg$',
    },
  },
  statusMessage: 'Service completed Successfully.',
};
export default deviceConfigJson;
