window.confirmationJSON = {
	"output": {
		"title": "You're all set.",
		"subtitle": null,
		"orderId": "402323319514175",
		"estimatedDelivery": "",
		"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/1.3_MV_BuyandUpgrade_ConfirmationPage_Interstital?$device-med$",
		"tradeInStatus": false,
		"confirmationMessage": "Thanks for ordering from verizonwireless.com. Your order receipt is sent to MANOJ.SUBRAMANI@VERIZON.COM.",
		"doneButtonText": "Got it",
		"doneButtonLink": "/od/cust/auth/shoplanding/",
		"userNote": "TODO",
		"notNowButtonText": "TODO",
		"accessoryGWURL": "/od/cust/auth/accessories/",
		"notNowButtonLink": "TODO",
		"learnHowButtonText": null,
		"learnHowButtonLink": "/od/cust/auth/learnHow",
		"numberOfDevice": 1,
		"confirmationNumberText": "Confirmation Number",
		"iconicFlow": true,
		"protectionURL": null,
		"accessoriesURL": null,
		"tapFlag": false,
		"cjmTagUrl": null,
		"pepperJamTagUrl": null,
		"selectedPaymentMode": null,
		"confirmationEmail": "MANOJ.SUBRAMANI@VERIZON.COM",
		"plans": {
			"dueMonthly": "295.00",
			"dueToday": "0.00",
			"planOnlyDueMonthly": "295.00",
			"items": [{
				"planType": "Beyond Unlimited",
				"lineAccessCharges": [{
					"name": "Apple iPhone&reg; 7 Plus 32GB in Black",
					"mtn": null,
					"price": "55.00",
					"discountPrice": "0.00",
					"retailPrice": "0.00",
					"hasEcpdDiscount": false,
					"promoMessage": null,
					"originalPrice": "0.00",
					"wasPrice": "0.00",
					"deviceName": "iPhone&reg; 7 Plus",
					"color": "Black",
					"size": "32GB",
					"instantCreditAmount": "0.00",
					"amountAfterInstantCredit": "0.00",
					"disountedInstantCreditAmt": "0.00"
				}],
				"accountAccess": {
					"name": "Beyond Unlimited",
					"mtn": null,
					"price": "295.00",
					"discountPrice": "0.00",
					"retailPrice": "0.00",
					"hasEcpdDiscount": false,
					"promoMessage": null,
					"originalPrice": "0.00",
					"wasPrice": "0.00",
					"deviceName": null,
					"color": null,
					"size": null,
					"instantCreditAmount": "0.00",
					"amountAfterInstantCredit": "0.00",
					"disountedInstantCreditAmt": "0.00"
				},
				"accountLevelFeatures": null,
				"totalMonthlyPlanCost": "295.00",
				"spoBadgeMessage": null,
				"planDisplayName": "Beyond Unlimited",
				"planImageURL": null,
				"planLetter": null,
				"planDescrption": null,
				"planDescription": null
			}],
			"upgradeDevices": [],
			"newDevices": [{
				"name": "iPhone&reg; 7 Plus",
				"price": "55.00",
				"discountPrice": 0.0,
				"hasEcpdDiscount": false,
				"mtn": null,
				"listPrice": 55.0,
				"deviceLineItemId": "Sfe63943a3729dc9b771b0fffb13d2cff{ss3}_device_1",
				"discountPriceVal": "0.00"
			}],
			"existingDevices": [{
				"name": "Google Pixel 2 XL 64GB in Black & White",
				"price": "55.00",
				"discountPrice": 0.0,
				"hasEcpdDiscount": false,
				"mtn": "6054530233",
				"listPrice": 55.0,
				"deviceLineItemId": null,
				"discountPriceVal": "0.00"
			}, {
				"name": "Apple&reg; iPhone&reg; 8 256GB in Silver",
				"price": "55.00",
				"discountPrice": 0.0,
				"hasEcpdDiscount": false,
				"mtn": "6054530234",
				"listPrice": 55.0,
				"deviceLineItemId": null,
				"discountPriceVal": "0.00"
			}, {
				"name": "Apple&reg; iPhone&reg; 5c 8GB in Yellow",
				"price": "55.00",
				"discountPrice": 0.0,
				"hasEcpdDiscount": false,
				"mtn": "6054530235",
				"listPrice": 55.0,
				"deviceLineItemId": null,
				"discountPriceVal": "0.00"
			}, {
				"name": "Google Pixel 2 64 GB in Kinda Blue",
				"price": "55.00",
				"discountPrice": 0.0,
				"hasEcpdDiscount": false,
				"mtn": "6054530236",
				"listPrice": 55.0,
				"deviceLineItemId": null,
				"discountPriceVal": "0.00"
			}, {
				"name": "Samsung Gear S3 frontier in Black",
				"price": "20.00",
				"discountPrice": 0.0,
				"hasEcpdDiscount": false,
				"mtn": "8457097926",
				"listPrice": 20.0,
				"deviceLineItemId": null,
				"discountPriceVal": "0.00"
			}],
			"dueMonthlyPlanWithLAC": "295.00",
			"discountedDueMonthlyPlanWithLAC": "0.00",
			"hasEcpdDiscount": false,
			"totalLineAccessCharges": "55.00"
		},
		"featureList": [{
			"id": "Sfe63943a3729dc9b771b0fffb13d2cff{ss3}_feature_1",
			"quantity": 1,
			"type": "NAF,VMDF",
			"skuId": "sku2560179",
			"productId": "sfo80079",
			"sorId": "85433",
			"itemAmount": 0.0,
			"itemAmountOriginal": 0.0,
			"dueMonthly": 0.0,
			"dueMonthlyOriginal": null,
			"itemDiscount": 0.0,
			"displayName": "Phone Plan",
			"skuDisplayName": null,
			"listPrice": 0.0,
			"rawTotalAmount": 0.0,
			"pricingDetails": [{
				"pricingAdjustmentId": null,
				"itemId": "Sfe63943a3729dc9b771b0fffb13d2cff{ss3}_feature_1",
				"orderId": "Sfe63943a3729dc9b771b0fffb13d2cff{ss3}",
				"offerId": null,
				"offerAmount": 0.0,
				"description": "List Price description",
				"offerType": null,
				"priceListId": null,
				"listPrice": 0.0,
				"offerName": null,
				"creationDate": 1526026761915,
				"lastModifiedDate": 1526026761915,
				"version": 1
			}],
			"orderId": "Sfe63943a3729dc9b771b0fffb13d2cff{ss3}",
			"version": 1,
			"delete": false,
			"inventoryLevel": 0,
			"taxDetails": null,
			"itemTaxes": 0.0,
			"deviceLineItemId": "Sfe63943a3729dc9b771b0fffb13d2cff{ss3}_device_1",
			"featureCharge": 0.0,
			"featureType": "LAC",
			"lastModifiedDate": 1526026744178
		}, {
			"id": "Sfe63943a3729dc9b771b0fffb13d2cff{ss3}_feature_2",
			"quantity": 1,
			"type": null,
			"skuId": "sku2880234",
			"productId": "spo1640003",
			"sorId": "1167",
			"itemAmount": 0.0,
			"itemAmountOriginal": 39.0,
			"dueMonthly": 39.0,
			"dueMonthlyOriginal": null,
			"itemDiscount": 0.0,
			"displayName": "Total Mobile Protection Multi-Device",
			"skuDisplayName": null,
			"listPrice": 39.0,
			"rawTotalAmount": 0.0,
			"pricingDetails": [{
				"pricingAdjustmentId": null,
				"itemId": "Sfe63943a3729dc9b771b0fffb13d2cff{ss3}_feature_2",
				"orderId": "Sfe63943a3729dc9b771b0fffb13d2cff{ss3}",
				"offerId": null,
				"offerAmount": 0.0,
				"description": "List Price description",
				"offerType": null,
				"priceListId": null,
				"listPrice": 39.0,
				"offerName": null,
				"creationDate": 1526026761915,
				"lastModifiedDate": 1526026761915,
				"version": 1
			}],
			"orderId": "Sfe63943a3729dc9b771b0fffb13d2cff{ss3}",
			"version": 1,
			"delete": false,
			"inventoryLevel": 0,
			"taxDetails": null,
			"itemTaxes": 0.0,
			"deviceLineItemId": "Sfe63943a3729dc9b771b0fffb13d2cff{ss3}_device_1",
			"featureCharge": 0.0,
			"featureType": "SPO",
			"lastModifiedDate": 1526026744180
		}],
		"accessoryList": [{
			"id": "Sfe63943a3729dc9b771b0fffb13d2cff{ss3}_accessory_1",
			"quantity": 1,
			"type": null,
			"skuId": "sku2920042",
			"productId": "12100003",
			"sorId": null,
			"itemAmount": 214.95999999999998,
			"itemAmountOriginal": 0.0,
			"dueMonthly": 0.0,
			"dueMonthlyOriginal": null,
			"itemDiscount": 0.0,
			"displayName": "Presidio Clear Power, Protection, & Stereo Bundle for iPhone 8 Plus",
			"skuDisplayName": null,
			"listPrice": 214.95999999999998,
			"rawTotalAmount": 214.95999999999998,
			"pricingDetails": [{
				"pricingAdjustmentId": null,
				"itemId": "Sfe63943a3729dc9b771b0fffb13d2cff{ss3}_accessory_1",
				"orderId": "Sfe63943a3729dc9b771b0fffb13d2cff{ss3}",
				"offerId": null,
				"offerAmount": 0.0,
				"description": "List Price description",
				"offerType": null,
				"priceListId": null,
				"listPrice": 214.95999999999998,
				"offerName": null,
				"creationDate": 1526026761916,
				"lastModifiedDate": 1526026761916,
				"version": 1
			}],
			"orderId": "Sfe63943a3729dc9b771b0fffb13d2cff{ss3}",
			"version": 1,
			"delete": false,
			"inventoryLevel": 0,
			"taxDetails": null,
			"itemTaxes": 0.0,
			"deviceLineItemId": "Sfe63943a3729dc9b771b0fffb13d2cff{ss3}_device_1",
			"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone-8-plus-7-15960-ga-enhanced-bundle-iset?$acc-med$",
			"bogoType": null,
			"recycleStateInd": null,
			"color": null,
			"size": null,
			"capacity": null,
			"lastModifiedDate": 1526026744251,
			"deviceManufacturerName": null,
			"accessoryType": "BUNDLE_ACCESSORIES",
			"ispuEligibleFlag": true,
			"bundleSkuLineItems": [{
				"brand": "",
				"displayName": "Presidio Clear for iPhone 8 Plus",
				"capacity": 10,
				"productID": "sku2640024",
				"skuDetails": [{
					"id": "sku2640024",
					"quantity": 1,
					"type": null,
					"skuId": "sku2640024",
					"productId": null,
					"sorId": "103124-5085",
					"itemAmount": 44.99,
					"itemAmountOriginal": 0.0,
					"dueMonthly": 0.0,
					"dueMonthlyOriginal": null,
					"itemDiscount": 0.0,
					"displayName": "Presidio Clear for iPhone 8 Plus/7 Plus/6s Plus/6 Plus",
					"skuDisplayName": "Speck Presidio Clear for iP8/iP7/iP6s/iP6 Plus - Clear/Clear",
					"listPrice": 44.99,
					"rawTotalAmount": 44.99,
					"pricingDetails": [{
						"pricingAdjustmentId": null,
						"itemId": "sku2640024",
						"orderId": null,
						"offerId": null,
						"offerAmount": 0.0,
						"description": "List Price description",
						"offerType": null,
						"priceListId": null,
						"listPrice": 44.99,
						"offerName": null,
						"creationDate": 1526026761916,
						"lastModifiedDate": 1526026761916,
						"version": 1
					}],
					"orderId": null,
					"version": 0,
					"delete": false,
					"inventoryLevel": 0,
					"taxDetails": [{
						"taxLineItemId": null,
						"lineItemId": "sku2640024",
						"itemType": "accessory",
						"sorSkuId": "103124-5085",
						"taxType": "taxes_fees",
						"taxAmount": 0.17,
						"taxDescription": "NY Local Sales Tax",
						"version": 0,
						"orderId": null,
						"createdDate": 1526026773349
					}, {
						"taxLineItemId": null,
						"lineItemId": "sku2640024",
						"itemType": "accessory",
						"sorSkuId": "103124-5085",
						"taxType": "taxes_fees",
						"taxAmount": 1.8,
						"taxDescription": "NY State Sales Tax",
						"version": 0,
						"orderId": null,
						"createdDate": 1526026773349
					}, {
						"taxLineItemId": null,
						"lineItemId": "sku2640024",
						"itemType": "accessory",
						"sorSkuId": "103124-5085",
						"taxType": "taxes_fees",
						"taxAmount": 1.8,
						"taxDescription": "NY Local Sales Tax",
						"version": 0,
						"orderId": null,
						"createdDate": 1526026773349
					}],
					"itemTaxes": 3.77,
					"deviceLineItemId": null,
					"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/speck-presidio-clear-ip7-ip6s-ip6-plus-clear-clear-103124-5085-iset?$acc-med$",
					"bogoType": null,
					"recycleStateInd": null,
					"color": false,
					"size": null,
					"capacity": null,
					"lastModifiedDate": null,
					"deviceManufacturerName": null,
					"accessoryType": null,
					"ispuEligibleFlag": false,
					"bundleSkuLineItems": null,
					"bundleDesciption": null,
					"vzwSbdOfferlist": [],
					"promotions": null,
					"purchasePath": null,
					"appleCare": false,
					"expectedShippingDate": null,
					"shipCommitInd": null,
					"sameDayDelivery": false,
					"recycleCreditAllocatedAmount": 0.0,
					"ecpdItemAmount": null,
					"ecpdItemDiscount": 0.0,
					"standaloneaccessory": false,
					"batteryAccessory": false,
					"accSeoUrl": null,
					"name": "Presidio Clear for iPhone 8 Plus/7 Plus/6s Plus/6 Plus",
					"price": "44.99",
					"discountedPrice": "34.99",
					"preSelected": false,
					"comingSoonAcc": false,
					"inCart": false,
					"learnMoreLink": "/od/cust/auth/accessoryDetails/?accProdId=acc8560024",
					"discount_price": null,
					"available": false
				}]
			}, {
				"brand": "",
				"displayName": "ZAGG InvisibleShield Glass+ Screen Protector for iPhone 8 Plus",
				"capacity": 10,
				"productID": "sku2120065",
				"skuDetails": [{
					"id": "sku2120065",
					"quantity": 1,
					"type": null,
					"skuId": "sku2120065",
					"productId": null,
					"sorId": "I7LLGC-F00",
					"itemAmount": 39.99,
					"itemAmountOriginal": 0.0,
					"dueMonthly": 0.0,
					"dueMonthlyOriginal": null,
					"itemDiscount": 0.0,
					"displayName": "InvisibleShield Glass+ Screen Protector for iPhone 8 Plus/7 Plus/6s Plus/6 Plus",
					"skuDisplayName": "ZAGG InvisibleShield Glass for iP8/iP7/iP6/iP6s Plus",
					"listPrice": 39.99,
					"rawTotalAmount": 39.99,
					"pricingDetails": [{
						"pricingAdjustmentId": null,
						"itemId": "sku2120065",
						"orderId": null,
						"offerId": null,
						"offerAmount": 0.0,
						"description": "List Price description",
						"offerType": null,
						"priceListId": null,
						"listPrice": 39.99,
						"offerName": null,
						"creationDate": 1526026761916,
						"lastModifiedDate": 1526026761916,
						"version": 1
					}],
					"orderId": null,
					"version": 0,
					"delete": false,
					"inventoryLevel": 0,
					"taxDetails": [{
						"taxLineItemId": null,
						"lineItemId": "sku2120065",
						"itemType": "accessory",
						"sorSkuId": "I7LLGC-F00",
						"taxType": "taxes_fees",
						"taxAmount": 0.15,
						"taxDescription": "NY Local Sales Tax",
						"version": 0,
						"orderId": null,
						"createdDate": 1526026773349
					}, {
						"taxLineItemId": null,
						"lineItemId": "sku2120065",
						"itemType": "accessory",
						"sorSkuId": "I7LLGC-F00",
						"taxType": "taxes_fees",
						"taxAmount": 1.6,
						"taxDescription": "NY State Sales Tax",
						"version": 0,
						"orderId": null,
						"createdDate": 1526026773349
					}, {
						"taxLineItemId": null,
						"lineItemId": "sku2120065",
						"itemType": "accessory",
						"sorSkuId": "I7LLGC-F00",
						"taxType": "taxes_fees",
						"taxAmount": 1.6,
						"taxDescription": "NY Local Sales Tax",
						"version": 0,
						"orderId": null,
						"createdDate": 1526026773349
					}],
					"itemTaxes": 3.35,
					"deviceLineItemId": null,
					"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/zagg-invisibleshield-glass-iphone-6-plus-iset-ippglc-f00?$acc-med$",
					"bogoType": null,
					"recycleStateInd": null,
					"color": false,
					"size": null,
					"capacity": null,
					"lastModifiedDate": null,
					"deviceManufacturerName": null,
					"accessoryType": null,
					"ispuEligibleFlag": false,
					"bundleSkuLineItems": null,
					"bundleDesciption": null,
					"vzwSbdOfferlist": [],
					"promotions": null,
					"purchasePath": null,
					"appleCare": false,
					"expectedShippingDate": null,
					"shipCommitInd": null,
					"sameDayDelivery": false,
					"recycleCreditAllocatedAmount": 0.0,
					"ecpdItemAmount": null,
					"ecpdItemDiscount": 0.0,
					"standaloneaccessory": false,
					"batteryAccessory": false,
					"accSeoUrl": null,
					"name": "InvisibleShield Glass+ Screen Protector for iPhone 8 Plus/7 Plus/6s Plus/6 Plus",
					"price": "39.99",
					"discountedPrice": "32.5",
					"preSelected": false,
					"comingSoonAcc": false,
					"inCart": false,
					"learnMoreLink": "/od/cust/auth/accessoryDetails/?accProdId=acc6640065",
					"discount_price": null,
					"available": false
				}]
			}, {
				"brand": "",
				"displayName": "Lightning Wall Charger",
				"capacity": 10,
				"productID": "sku2180059",
				"skuDetails": [{
					"id": "sku2180059",
					"quantity": 1,
					"type": null,
					"skuId": "sku2180059",
					"productId": null,
					"sorId": "TVL24LGHT-M",
					"itemAmount": 29.99,
					"itemAmountOriginal": 0.0,
					"dueMonthly": 0.0,
					"dueMonthlyOriginal": null,
					"itemDiscount": 0.0,
					"displayName": "Lightning Wall Charger",
					"skuDisplayName": "Verizon 2.4A Apple Lightning Travel Charger",
					"listPrice": 29.99,
					"rawTotalAmount": 29.99,
					"pricingDetails": [{
						"pricingAdjustmentId": null,
						"itemId": "sku2180059",
						"orderId": null,
						"offerId": null,
						"offerAmount": 0.0,
						"description": "List Price description",
						"offerType": null,
						"priceListId": null,
						"listPrice": 29.99,
						"offerName": null,
						"creationDate": 1526026761916,
						"lastModifiedDate": 1526026761916,
						"version": 1
					}],
					"orderId": null,
					"version": 0,
					"delete": false,
					"inventoryLevel": 0,
					"taxDetails": [{
						"taxLineItemId": null,
						"lineItemId": "sku2180059",
						"itemType": "accessory",
						"sorSkuId": "TVL24LGHT-M",
						"taxType": "taxes_fees",
						"taxAmount": 0.11,
						"taxDescription": "NY Local Sales Tax",
						"version": 0,
						"orderId": null,
						"createdDate": 1526026773349
					}, {
						"taxLineItemId": null,
						"lineItemId": "sku2180059",
						"itemType": "accessory",
						"sorSkuId": "TVL24LGHT-M",
						"taxType": "taxes_fees",
						"taxAmount": 1.2,
						"taxDescription": "NY Local Sales Tax",
						"version": 0,
						"orderId": null,
						"createdDate": 1526026773349
					}, {
						"taxLineItemId": null,
						"lineItemId": "sku2180059",
						"itemType": "accessory",
						"sorSkuId": "TVL24LGHT-M",
						"taxType": "taxes_fees",
						"taxAmount": 1.2,
						"taxDescription": "NY State Sales Tax",
						"version": 0,
						"orderId": null,
						"createdDate": 1526026773349
					}],
					"itemTaxes": 2.51,
					"deviceLineItemId": null,
					"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/vzw-2-4a-apple-lightning-travel-charger-tvl24lght-m-iset?$acc-med$",
					"bogoType": null,
					"recycleStateInd": null,
					"color": false,
					"size": null,
					"capacity": null,
					"lastModifiedDate": null,
					"deviceManufacturerName": null,
					"accessoryType": null,
					"ispuEligibleFlag": false,
					"bundleSkuLineItems": null,
					"bundleDesciption": null,
					"vzwSbdOfferlist": [],
					"promotions": null,
					"purchasePath": null,
					"appleCare": false,
					"expectedShippingDate": null,
					"shipCommitInd": null,
					"sameDayDelivery": false,
					"recycleCreditAllocatedAmount": 0.0,
					"ecpdItemAmount": null,
					"ecpdItemDiscount": 0.0,
					"standaloneaccessory": false,
					"batteryAccessory": false,
					"accSeoUrl": null,
					"name": "Lightning Wall Charger",
					"price": "29.99",
					"discountedPrice": "22.5",
					"preSelected": false,
					"comingSoonAcc": false,
					"inCart": false,
					"learnMoreLink": "/od/cust/auth/accessoryDetails/?accProdId=acc6880031",
					"discount_price": null,
					"available": false
				}]
			}, {
				"brand": "",
				"displayName": "Braven Stryde 360",
				"capacity": 10,
				"productID": "sku2490050",
				"skuDetails": [{
					"id": "sku2490050",
					"quantity": 1,
					"type": null,
					"skuId": "sku2490050",
					"productId": null,
					"sorId": "BBRVFCSG",
					"itemAmount": 99.99,
					"itemAmountOriginal": 0.0,
					"dueMonthly": 0.0,
					"dueMonthlyOriginal": null,
					"itemDiscount": 0.0,
					"displayName": "Stryde 360 - Silver/Green",
					"skuDisplayName": "Braven Stryde 360 Degree Sound - Silver Green",
					"listPrice": 99.99,
					"rawTotalAmount": 99.99,
					"pricingDetails": [{
						"pricingAdjustmentId": null,
						"itemId": "sku2490050",
						"orderId": null,
						"offerId": null,
						"offerAmount": 0.0,
						"description": "List Price description",
						"offerType": null,
						"priceListId": null,
						"listPrice": 99.99,
						"offerName": null,
						"creationDate": 1526026761916,
						"lastModifiedDate": 1526026761916,
						"version": 1
					}],
					"orderId": null,
					"version": 0,
					"delete": false,
					"inventoryLevel": 0,
					"taxDetails": [{
						"taxLineItemId": null,
						"lineItemId": "sku2490050",
						"itemType": "accessory",
						"sorSkuId": "BBRVFCSG",
						"taxType": "taxes_fees",
						"taxAmount": 4.0,
						"taxDescription": "NY Local Sales Tax",
						"version": 0,
						"orderId": null,
						"createdDate": 1526026773349
					}, {
						"taxLineItemId": null,
						"lineItemId": "sku2490050",
						"itemType": "accessory",
						"sorSkuId": "BBRVFCSG",
						"taxType": "taxes_fees",
						"taxAmount": 4.0,
						"taxDescription": "NY State Sales Tax",
						"version": 0,
						"orderId": null,
						"createdDate": 1526026773349
					}, {
						"taxLineItemId": null,
						"lineItemId": "sku2490050",
						"itemType": "accessory",
						"sorSkuId": "BBRVFCSG",
						"taxType": "taxes_fees",
						"taxAmount": 0.37,
						"taxDescription": "NY Local Sales Tax",
						"version": 0,
						"orderId": null,
						"createdDate": 1526026773349
					}],
					"itemTaxes": 8.37,
					"deviceLineItemId": null,
					"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/braven-stryde-360-silver-green-bbrvfcsg-iset?$acc-med$",
					"bogoType": null,
					"recycleStateInd": null,
					"color": false,
					"size": null,
					"capacity": null,
					"lastModifiedDate": null,
					"deviceManufacturerName": null,
					"accessoryType": null,
					"ispuEligibleFlag": false,
					"bundleSkuLineItems": null,
					"bundleDesciption": null,
					"vzwSbdOfferlist": [],
					"promotions": null,
					"purchasePath": null,
					"appleCare": false,
					"expectedShippingDate": null,
					"shipCommitInd": null,
					"sameDayDelivery": false,
					"recycleCreditAllocatedAmount": 0.0,
					"ecpdItemAmount": null,
					"ecpdItemDiscount": 0.0,
					"standaloneaccessory": false,
					"batteryAccessory": false,
					"accSeoUrl": null,
					"name": "Stryde 360 - Silver/Green",
					"price": "99.99",
					"discountedPrice": "50.0",
					"preSelected": false,
					"comingSoonAcc": false,
					"inCart": false,
					"learnMoreLink": "/od/cust/auth/accessoryDetails/?accProdId=acc7960018",
					"discount_price": null,
					"available": false
				}]
			}],
			"bundleDesciption": null,
			"vzwSbdOfferlist": null,
			"promotions": null,
			"purchasePath": "AAL",
			"appleCare": false,
			"expectedShippingDate": null,
			"shipCommitInd": null,
			"sameDayDelivery": false,
			"recycleCreditAllocatedAmount": 0.0,
			"ecpdItemAmount": null,
			"ecpdItemDiscount": 0.0,
			"standaloneaccessory": false,
			"batteryAccessory": false,
			"accSeoUrl": ""
		}],
		"paymentGroup": null,
		"contactInfo": {
			"id": null,
			"emailAddress": "MANOJ.SUBRAMANI@VERIZON.COM",
			"phoneNumber": "7777777773",
			"lastName": "HQSAUTOTEST",
			"firstName": "CSLPOS",
			"zipCode": "10962",
			"orderId": null,
			"userId": null,
			"npaNxxNumber": null,
			"address1": "2000 CORPORATE DR MALL",
			"address2": null,
			"city": "Orangeburg",
			"state": "NY",
			"addressVerified": true,
			"textAlertOptin": false,
			"newsLetterOptin": false,
			"paperFreeBillingIndicatorFlag": false,
			"middleName": null,
			"firmName": null,
			"businessName": null,
			"apartmentNum": "",
			"addressDirection": "",
			"poBox": "",
			"streetNumber": "2000",
			"streetName": "CORPORATE",
			"streetType": "DR",
			"ruralRoute": null,
			"ruralDel": "",
			"zipCode4": null,
			"zipCode5": null,
			"faxNumber": null,
			"addressType": null,
			"country": "",
			"prefix": null,
			"suffix": null,
			"postbox": null,
			"companyname": null,
			"ruralrte": "",
			"county": null,
			"address3": null,
			"postalcode": "10962",
			"version": 0,
			"lastModifiedDate": null,
			"addressConfirmationStatus": null
		},
		"tradeInDevicesDetails": null,
		"tradeInPromoDetails": null,
		"transformedTradeInPromoDetails": null,
		"subOrders": null,
		"comboOrder": false,
		"totalDueToday": "448.95",
		"totalDueMonthly": "46.70",
		"subTotalDueToday": "399.96",
		"securityDepositAmount": "0.00",
		"stateSalesTax": "48.99",
		"employeeDiscount": "448.95",
		"pastDueExist": false,
		"pastDueAmountPaid": false,
		"pastDueAmount": "0.00",
		"shippingInfo": {
			"shippingInfoUpdated": false,
			"sameAsBilling": true,
			"ispuEligibleFlag": true,
			"addressInfo": {
				"firstName": "CSLPOS",
				"lastName": "HQSAUTOTEST",
				"companyName": null,
				"address1": "2000 CORPORATE DR MALL",
				"address2": null,
				"city": "Orangeburg",
				"state": "NY",
				"zipcode": "10962",
				"businessName": null,
				"postalCode": null,
				"email": "MANOJ.SUBRAMANI@VERIZON.COM",
				"phoneNumber": "7777777773"
			},
			"contactInfo": {
				"emailAddress": "MANOJ.SUBRAMANI@VERIZON.COM",
				"phoneNumber": "7777777773",
				"firstName": "CSLPOS",
				"lastName": "HQSAUTOTEST",
				"smsMdn": null,
				"activeSMSCapableMtnList": ["6054530235", "6054530234", "6054530233", "6054530236", "8457097926"]
			},
			"shippingTypesInfo": [{
				"estimatedDeliveryDate": "2018-05-15 00:00:00",
				"estimatedDeliveryDateText": "Tue 5/15",
				"shippingDescription": "Free 2 Day by 8pm",
				"shippingOptionId": "SHP002",
				"shippingCost": "0.00",
				"shortDescription": "Free 2 Day by 8pm",
				"active": true,
				"addedShippingOptionId": true,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Tue, May 15 if ordered by 4pm today. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}, {
				"estimatedDeliveryDate": "2018-05-14 00:00:00",
				"estimatedDeliveryDateText": "Mon 5/14",
				"shippingDescription": "Next Day by 8pm",
				"shippingOptionId": "SHP004",
				"shippingCost": "12.99",
				"shortDescription": "Next Day by 8pm",
				"active": true,
				"addedShippingOptionId": false,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Mon, May 14. Next Day by 8pm. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}, {
				"estimatedDeliveryDate": "2018-05-14 10:30:00",
				"estimatedDeliveryDateText": "Mon 5/14 by 10:30AM",
				"shippingDescription": "Next Day by 10:30am",
				"shippingOptionId": "SHP005",
				"shippingCost": "14.99",
				"shortDescription": "Next Day by 10:30am",
				"active": true,
				"addedShippingOptionId": false,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Mon, May 14. Next Day by 10:30am. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}, {
				"estimatedDeliveryDate": "2018-05-12 00:00:00",
				"estimatedDeliveryDateText": "Sat 5/12",
				"shippingDescription": "Saturday by 12pm",
				"shippingOptionId": "SHP006",
				"shippingCost": "19.99",
				"shortDescription": "Saturday by 12pm",
				"active": true,
				"addedShippingOptionId": false,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Sat, May 12. Saturday by 12pm. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}],
			"storeDetail": {
				"storeHeader": null,
				"storeName": null,
				"storeAddress": null,
				"deviceAvailable": false,
				"distance": null,
				"appendedStoreTiming": null,
				"longitude": null,
				"storeId": null,
				"netaceLocationCode": null,
				"latitude": null,
				"seoUrlName": null,
				"storeClosingTime": null
			},
			"tradeIn": false,
			"tradeInAddress": null,
			"nonSddEligibleMsg": null,
			"selectedSDDWindow": null,
			"poboMessage": null,
			"ispudetailsInfo": {
				"storeAddress": null,
				"storeHours": null,
				"storeId": null,
				"storeName": null,
				"phoneNumber": null,
				"distance": null,
				"totalItems": 0,
				"availItems": 0,
				"latitdude": 0.0,
				"longtitude": 0.0,
				"availItemName": null
			}
		},
		"billingInfo": {
			"billToAccountEligible": false,
			"creditCardZipEditable": false,
			"billingAddress": {
				"firstName": "CSLPOS",
				"lastName": "HQSAUTOTEST",
				"businessName": null,
				"zipcode": "10962",
				"state": "NY",
				"address2": null,
				"address1": "2000 CORPORATE DR MALL",
				"companyName": null,
				"city": "Orangeburg",
				"sameAsShipping": false
			},
			"masterpass3DSecure": null,
			"billToAccountNumber": null,
			"creditCardInfo": {
				"savedCardNickName": null,
				"preselectCard": null,
				"creditCardNumber": "XXXX XXXX XXXX-1111",
				"creditCardExpMonth": "02",
				"creditCardExpYear": "2019",
				"billingZipCode": null,
				"creditCardType": "visa",
				"creditCardVerificationNumber": null,
				"creditCardBIN": null,
				"cvvRequired": false
			},
			"selectedPaymentMode": "newCard",
			"giftCardList": [],
			"savedCardInfo": [],
			"applePayResponseInfo": null,
			"masterpassResponseInfo": {
				"emailAddress": null,
				"cardType": null,
				"lastDigits": null,
				"creditCardBIN": null
			},
			"masterpassError": false,
			"masterpassErrorMessage": null,
			"paypalEmailAddress": null,
			"expirationMonths": ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
			"expirationYears": ["2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027"]
		},
		"devices": {
			"dueMonthly": 46.7,
			"totalActivationFee": 0.0,
			"deviceTotalDueMonthly": 7.7,
			"dueToday": 185.0,
			"accessories": [],
			"accessoriesBundle": [{
				"discountedPrice": 214.96,
				"imgUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone-8-plus-7-15960-ga-enhanced-bundle-iset?$acc-med$",
				"regularPrice": 214.96,
				"savedPrice": 0.0,
				"displayName": "Presidio Clear Power, Protection, & Stereo Bundle for iPhone 8 Plus",
				"bundleDescription": null,
				"skuID": "sku2920042",
				"discountPercentage": null,
				"discounted": false
			}],
			"items": [{
				"deviceName": "iPhone&reg; 7 Plus",
				"dueMonthly": "7.70",
				"dueToday": "0.00",
				"upgradeFee": "0.00",
				"originalUpgradeFee": "0.00",
				"activationFee": "30.00",
				"dueTodayOriginal": "0.00",
				"dueMonthlyOriginal": "20.21",
				"dueTodayDiscounted": false,
				"dueMonthlyDiscounted": true,
				"mtn": null,
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-matblk?$device-med$&fmt=jpeg&wid=75&hei=150",
				"protectionFeature": {
					"name": "Total Mobile Protection Multi-Device",
					"mtn": null,
					"price": "39.00",
					"discountPrice": "0.00",
					"retailPrice": "0.00",
					"hasEcpdDiscount": false,
					"promoMessage": null,
					"originalPrice": "0.00",
					"wasPrice": "0.00",
					"deviceName": null,
					"color": null,
					"size": null,
					"instantCreditAmount": "0.00",
					"amountAfterInstantCredit": "0.00",
					"disountedInstantCreditAmt": "0.00"
				},
				"optionalFeatures": [],
				"installmentBalance": "184.99",
				"edgeRetailPrice": "669.99",
				"edgeItemDownPaymentAmount": "185.00",
				"mailInRebateAmount": "0.00",
				"transferredFromMtn": null,
				"devicePromotionList": [{
					"promotionalMessage": null,
					"promoDescription": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION BIC YES",
					"promoName": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION",
					"promoAmount": "300.00",
					"priceSubTitle": "1st installment will appear on your bill.",
					"barCodeId": null,
					"itemCode": "MNR12LL/A",
					"itemType": "ITA",
					"sedOffer": true,
					"isUpgradeFeeWaivedOffer": false,
					"promoContentText": null
				}],
				"bicOfferApplied": false,
				"bicContractPrice": "0.00",
				"bicDiscountedContractPrice": "-1.00",
				"bicAdditionalContractText": null,
				"bicMessageMap": null,
				"edgeUpAmount": 0.0,
				"displayDeviceDueMonthly": 46.7,
				"deviceLACFee": "55.00",
				"manufactureName": "Apple",
				"color": "Black",
				"colorCode": "#000000",
				"size": "32GB",
				"displayName": "iPhone&reg; 7 Plus",
				"contractTerm": "99",
				"edgeUpBuyOutAmount": 0.0,
				"fullRetailPrice": "669.99",
				"alwaysEligibleForUpgrade": false,
				"numberShareDevice": false,
				"activationFeeText": "One-time activation fee of $30.00 charged to your next monthly bill.",
				"numberSharedMtn": null,
				"promoContentText": null,
				"itemOnJaxPlan": true,
				"humCarDetails": null,
				"simDetails": null,
				"imeiId": null,
				"displayImeiId": null,
				"poboDateLabel": null,
				"promoOfferText": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION",
				"promoApplied": true,
				"commerceItemId": "Sfe63943a3729dc9b771b0fffb13d2cff{ss3}_device_1",
				"loanTerm": 24,
				"sbdHeaderMsg": null,
				"percentage": null,
				"waivedActivationFeePromo": false,
				"flow": "AAL",
				"edgeDevice": true,
				"instantCreditAmount": "0.00",
				"amountAfterInstantCredit": "0.00",
				"accessory": false,
				"eupdevice": false,
				"disountedInstantCreditAmt": "0.00"
			}],
			"buddyUpgrade": false
		},
		"accessories": null,
		"selectedShippingType": {
			"type": "SHIPPING",
			"shippingTypeName": "FREE 2 Day by 8pm",
			"price": 0.0,
			"discountPrice": 0.0,
			"estimatedDeliveryDate": "2018-05-15 00:00:00"
		},
		"dueMonthlyView": {
			"title": "Due Monthly (device only)",
			"dueMonthlyPrice": "46.70",
			"items": [{
				"name": "iPhone&reg; 7 Plus",
				"description": "iPhone&reg; 7 Plus",
				"manufacturer": "Apple",
				"color": "Black",
				"size": "32GB",
				"priceBreakDown": [{
					"lable": "Total Mobile Protection Multi-Device",
					"price": "39.00",
					"description": null,
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": true,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 0.0,
					"itemStrikeThroughPrice": 0.0,
					"noOfBicOccurences": 0
				}, {
					"lable": "Device Payment",
					"price": "7.70",
					"description": "For 24 months, 0% APR with down payment. Reduced retail price: <span class='textDecLineThrough red'>$669.99</span> $184.99",
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 7.7,
					"itemStrikeThroughPrice": 20.21,
					"noOfBicOccurences": 0
				}],
				"edge": true
			}],
			"tmpMd": {
				"lable": "Total Mobile Protection Multi-Device",
				"price": "39.00",
				"description": "",
				"linkText": null,
				"linkUrl": null,
				"originalPrice": 0.0,
				"tmpMdOpted": true,
				"discountedEdgeRetailPrice": null,
				"sbdPromoMsg": null,
				"sbdDiscountAmount": 0.0,
				"sbdItemMonthlyAmount": 0.0,
				"itemRetailPrice": 0.0,
				"itemMonthlyPrice": 0.0,
				"itemStrikeThroughPrice": 0.0,
				"noOfBicOccurences": 0
			}
		},
		"balanceCreditCardAmount": "448.95",
		"cpcOrder": false,
		"totalDueMonthlyPlanAndDevice": "101.70",
		"deviceConfigInfo": {
			"devices": [{
				"deviceId": "Sfe63943a3729dc9b771b0fffb13d2cff{ss3}_device_1",
				"deviceName": "iPhone&reg; 7 Plus",
				"deviceSetupMode": null,
				"mtnNumber": null,
				"flow": "AAL",
				"serviceAddress": {
					"firstName": "CSLPOS",
					"lastName": "HQSAUTOTEST",
					"address1": "2000 CORPORATE DR MALL",
					"address2": "",
					"city": "Orangeburg",
					"state": "NY",
					"zipCode": "10962",
					"emailAddress": "MANOJ.SUBRAMANI@VERIZON.COM",
					"phoneNumber": "7777777773"
				},
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-matblk?$device-med$&fmt=jpeg&wid=75&hei=150",
				"mobileAppImageName": null,
				"npaNxxnumber": "404-922-XXXX",
				"npnxxCustomerSelection": "new",
				"npaNxxdetails": null,
				"manufactureName": "Apple",
				"color": "Black",
				"size": "32GB",
				"numberShareDevice": false,
				"numberSharedMtn": null,
				"deviceNickName": null,
				"numberSharedDeviceName": null,
				"portInDetails": null
			}],
			"npaNxxdetails": {
				"zipCode": null,
				"state": null,
				"city": null,
				"success": false,
				"mtns": null,
				"states": null,
				"cities": null
			},
			"deviceAddressUpdated": false,
			"accessories": null
		},
		"checkoutStates": {
			"shippingAddressRequired": false,
			"shippingAddressChangeRequired": false,
			"shippingMethodRequired": false,
			"paymentRequired": false,
			"pastDuePaymentRequired": false,
			"showPaymentSection": true,
			"showShippingAddress": true,
			"showDeliveryMethod": true,
			"newCard": false,
			"cvvNeeded": false,
			"contactInfoRequired": false
		},
		"totalEdgeItemDownPaymentAmount": "185.00",
		"totalEdgeUpAmount": "0.00",
		"totalEdgeUpBuyOutAmount": "0.00",
		"multiOrderDetails": null,
		"hasRio": false,
		"splitShipment": false
	}
};