const mdnAALJSON = {
  "statusCode": "00",
  "errorMap": null,
  "output": {
    "mtnDetailsList": [{
      "upgradeEligbile": false,
      "displayMtn": "301.785.7876",
      "mtn": "3017857876",
      "encryptedMTN": "424uj+jSrRQNAq0hbkE33g==",
      "upgradeMessage": null,
      "nickname": "JACK REYES",
      "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iphone_4s_white?$device-lg$",
      "inEligibleCode": null,
      "inEligibleDetails": null,
      "loanInfo": null,
      "annualUpgradeMessage": null,
      "deviceType": "Smartphone",
      "familyType": "Phone",
      "familyTypeRestricted": false,
      "contractTermMisMatch": false,
      "brand": "Apple",
      "deviceId": "",
      "twoYearContract": null,
      "annualUpgrade": false,
      "displayDeviceName": "iPhone&reg; 4s",
      "deviceName": "Apple&reg; iPhone&reg; 4S White 16GB",
      "eligibleUpgradeTypeList": ["Retail", "Edge", "2 Year"],
      "mtnAddedToTheCart": false,
      "deviceProductId": "dev440044",
      "alwaysEligibleForUpgrade": false,
      "myOffersPromoText": null,
      "annualUpgradeWarning": false
    }, {
      "upgradeEligbile": false,
      "displayMtn": "301.785.7873",
      "mtn": "3017857873",
      "encryptedMTN": "424uj+jSrRQqZXoHhch+kA==",
      "upgradeMessage": null,
      "nickname": "JACK REYES",
      "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iphone_4s_white?$device-lg$",
      "inEligibleCode": null,
      "inEligibleDetails": null,
      "loanInfo": null,
      "annualUpgradeMessage": null,
      "deviceType": "Smartphone",
      "familyType": "Phone",
      "familyTypeRestricted": false,
      "contractTermMisMatch": false,
      "brand": "Apple",
      "deviceId": "",
      "twoYearContract": null,
      "annualUpgrade": false,
      "displayDeviceName": "iPhone&reg; 4s",
      "deviceName": "Apple&reg; iPhone&reg; 4S White 16GB",
      "eligibleUpgradeTypeList": ["Retail", "Edge", "2 Year"],
      "mtnAddedToTheCart": false,
      "deviceProductId": "dev440044",
      "alwaysEligibleForUpgrade": false,
      "myOffersPromoText": null,
      "annualUpgradeWarning": false
    }, {
      "upgradeEligbile": false,
      "displayMtn": "301.518.5453",
      "mtn": "3015185453",
      "encryptedMTN": "dsod4AWLki4jpIcvb1X5KA==",
      "upgradeMessage": null,
      "nickname": "JOSEPH REYES",
      "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iphone_4s_black?$device-lg$",
      "inEligibleCode": null,
      "inEligibleDetails": null,
      "loanInfo": null,
      "annualUpgradeMessage": null,
      "deviceType": "Smartphone",
      "familyType": "Phone",
      "familyTypeRestricted": false,
      "contractTermMisMatch": false,
      "brand": "Apple",
      "deviceId": "",
      "twoYearContract": null,
      "annualUpgrade": false,
      "displayDeviceName": "iPhone&reg; 4s",
      "deviceName": "Apple&reg; iPhone&reg; 4S Black 16GB",
      "eligibleUpgradeTypeList": ["Retail", "Edge", "2 Year"],
      "mtnAddedToTheCart": false,
      "deviceProductId": "dev440044",
      "alwaysEligibleForUpgrade": false,
      "myOffersPromoText": null,
      "annualUpgradeWarning": false
    }, {
      "upgradeEligbile": false,
      "displayMtn": "301.518.5452",
      "mtn": "3015185452",
      "encryptedMTN": "dsod4AWLki76tlqaqaJ0yg==",
      "upgradeMessage": null,
      "nickname": "ETHAN REYES",
      "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple_iphone_4s_black?$device-lg$",
      "inEligibleCode": null,
      "inEligibleDetails": null,
      "loanInfo": null,
      "annualUpgradeMessage": null,
      "deviceType": "Smartphone",
      "familyType": "Phone",
      "familyTypeRestricted": false,
      "contractTermMisMatch": false,
      "brand": "Apple",
      "deviceId": "",
      "twoYearContract": null,
      "annualUpgrade": false,
      "displayDeviceName": "iPhone&reg; 4s",
      "deviceName": "Apple&reg; iPhone&reg; 4S Black 16GB",
      "eligibleUpgradeTypeList": ["Retail", "Edge", "2 Year"],
      "mtnAddedToTheCart": false,
      "deviceProductId": "dev440044",
      "alwaysEligibleForUpgrade": false,
      "myOffersPromoText": null,
      "annualUpgradeWarning": false
    }],
    "accountLevelInEligibleCode": null,
    "accountLevelInEligibleMessage": null,
    "selectedMTN": null,
    "aalRedirect": "",
    "accountLevelInEligibleDetails": {
      "accountLevelEUPInEligibleDetails": null,
      "accountLevelAALInEligibleDetails": {
        "accountLevelInEligibleCode": "CART_DEVICE_MAX_LIMIT_REACHED",
        "accountLevelInEligibleMessage": "Cart has reached/ exceeded the maximum devices allowed",
        "accountLevelInEligibleDetails": {
          "title": "You have a plan change pending.",
          "subTitle": "To continue with your order, you need to cancel your scheduled plan change. Do you want to do this?",
          "buttonText": "Yes, cancel my plan change.",
          "linkText": "No, don't cancel my plan change",
          "linkURL": null,
          "customerServiceNumber": "(800) 922-0204",
          "cancelPlanChangeURL": null
        }
      }
    },
    "cartRedirect": "/digital/cart/getCartDetails",
    "shopLandingRedirect": "/digital/shoplanding/",
    "mtnMainTitle": "Would you like to upgrade another line?",
    "unlimitedPlan": "N",
    "pastDueDetails": null,
    "aalboxEnable": true,
    "aalAllowed": false
  },
  "ajaxCallUrl": "/digital/submitSummary"
};

export default mdnAALJSON;
