const cqJSON = {
  "html": {
    "OD_PDP_DOWN_PAYMENT_MODAL_HTML": "<p class='pad10 onlyTopPad'> Due to the nature of your account history, we'll need a down payment for your device before we can start your monthly payments.</p><p class='pad10 onlyTopPad'> This payment will be required if you choose to purchase the device in store as well. But don't worry, this is something we ask of many customers, so you're not alone.</p><p class='pad10 onlyTopPad'>Plus a down payment means your monthly payments will be even lower going forward.</p>"
  },
  "label": {
    "OD_PDP_NEXT_BUTTON_TEXT": "Select",
    "OD_PDP_BACK_BUTTON_TEXT": "Back",
    "OD_PDP_PRICE_FROM_TEXT": "From",
    "OD_PDP_DETAIL_SPECS_TITLE_TEXT": "Here's some more technical detail",
    "OD_PDP_DETAIL_REVIEWS_TITLE_TEXT": "most helpful reviews",
    "OD_PDP_PRICE_MODAL_TITLE_TEXT": "How would you like to view prices?",
    "OD_PDP_SPLASH_SCREEN_TITLE": "Upgrade right here, right now.",
    "OD_PDP_PRICE_MODAL_BUTTON_TEXT": "Done",
    "OD_PDP_RATINGS_TITLE": "The ratings are in.",
    "OD_PDP_RATINS_RECOMMEND_DEVICE_TITLE": "% of users recommend the device",
    "OD_PDP_RATINGS_OVER_ALL_RATINGS_REVIEWS_TEXT": "Overall Rating",
    "OD_PDP_RATINGS_VIEW_TEXT": "Views",
    "OD_PDP_REVIEWS_READ_MORE_TEXT": "Read more",
    "OD_PDP_SHIPS_BY_MODAL_TITLE_TEXT": "Estimated to ship on",
    "OD_PDP_SHIPS_BY_MODAL_ITEM_AVAILABILITY_TEXT": "Item availability",
    "OD_PDP_SHIPS_BY_MODAL_SHIPPING_DATE_TEXT": "Shipping date",
    "OD_PDP_SHIPS_BY_MODAL_PAYMENT_TEXT": "Payment",
    "OD_PDP_SPECS_SEE_DETAILED_SPECS_TEXT": "See Detailed specs",
    "OD_PDP_SHIP_BY_MODAL_TITLE1_TEXT": "Item availability",
    "OD_PDP_SHIP_BY_MODAL_DESCRIPTION1_TEXT": "This item is currently out of stock, but if you place your order we'll ship it as soon as we have more.",
    "OD_PDP_SHIP_BY_MODAL_TITLE2_TEXT": "Shipping date",
    "OD_PDP_SHIP_BY_MODAL_DESCRIPTION2_TEXT": "Our shipping dates are just estimates, but we'll be sure to email you when your order is on the way",
    "OD_PDP_SHIP_BY_MODAL_TITLE3_TEXT": "Payment",
    "OD_PDP_SHIP_BY_MODAL_DESCRIPTION3_TEXT": "Don't worry.you won't be charged until your order ships.",
    "OD_PDP_DOWN_PAYMENT_LINK": "Why a down payment?",
    "OD_PDP_DOWN_PAYMENT_MODAL_TITLE": "Make a down payment and you'll be all set",
    "OD_PDP_SPLASH_SCREEN_IMG_URL": "build/images/get-started-w80.png",
    "OD_PDP_SPLASH_SCREEN_DESCRIPTION": "Trade in a device for up to $200, customize a new one, and we'll help you transfer what's important.",
    "OD_PDP_SPLASH_SCREEN_BUTTON_CTA": "Let's go",
    "OD_PDP_CURRENTLY_UNAVAILABLE_TEXT": "Currently Unavailable",
    "OD_PDP_ANNUAL_UPGRADE_WARNING_TITLE": "Your new device is not eligible for annual upgrade.",
    "OD_PDP_ANNUAL_UPGRADE_WARNING_SUBTITLE": "You may still upgrade to this device, but you will no longer have the benefits of the annual upgrade program.",
    "OD_PDP_ANNUAL_UPGRADE_WARNING_ACCEPT_CTA": "Cancel",
    "OD_PDP_RETAIL_PRICE_TEXT": "Total price will be due today.",
    "OD_PDP_MONTHLY_PAYMENT_TEXT": "Pay in 24 monthly installments, interest-free.",
    "OD_PDP_TWO_YEAR_CONTRACT_TEXT": "Early termination fee upto $350.",
    "OD_PDP_SHIPS_BY_TITLE_TEXT": "Ships by",
    "OD_PDP_ANNUAL_UPGRADE_WARNING_CANCEL_CTA": "Accept",
    "OD_CART_LIMIT_EXCEEDED_HEADER": "You've hit the maximum number of devices for this transaction.",
    "OD_CART_LIMIT_EXCEEDED_MSG": "If you still want to add this device, you can empty your cart, replace a device in your cart or finish this purchase as a separate transaction.",
    "OD_VIEW_CART_LBL": "View cart",
    "OD_PDP_SPLASH_SCREEN_TITLE_AAL": "Get a new device right here, right now.",
    "OD_PDP_SPLASH_SCREEN_DESCRIPTION_AAL": "Get free 2-day shipping. Your order will be at your doorstep in no time, at no additional cost to you.",
    "OD_PDP_ANNUAL_UPGRADE_TITLE": "Your new device is not eligible for annual upgrade.",
    "OD_PDP_ANNUAL_UPGRADE_CONTENT": "You may still upgrade to this device, but you will no longer have the benefits of the annual upgrade program.",
    "OD_PDP_CANCEL_BTN": "Cancel",
    "OD_PDP_ACCEPT_BTN": "Accept",
    "OD_PDP_FEATURE_TAB": "Features",
    "OD_PDP_REVIEWS_TAB": "Reviews",
    "OD_PDP_SPECS_TAB": "Specs",
    "OD_PDP_RATINGS_OUT_OF": "out of 5 stars"
  },
  "error": {}
};

export default cqJSON;
