/**
 * Created by sgumma on 17-02-2017.
 */
exports.protections = {
  output: {
    mtnDeviceInfo: {
      mtn: null,
      equipmentProtectionList: [{
        sorSfoType: 'INSUR,I',
        priceTerm: '/mo',
        sfoSkuId: 'sku1230442',
        price: 11.0,
        wasPrice: 0.0,
        introText: ' <p>Next day replacement for loss, theft, damage & post&ndash;warranty defects and unlimited access to Tech Coach experts.</p>',
        displayName: 'Total Mobile Protection',
        preSelected: false,
        sfoSORId: '81497',
        hasEcpdDiscount: false,
        defaultDisplayFlag: false,
      }, {
        sorSfoType: 'INSUR,W',
        priceTerm: '/mo',
        sfoSkuId: 'sku1230437',
        price: 9.0,
        wasPrice: 0.0,
        introText: '<p>Next day replacement for loss, theft, damage, and post&ndash;warranty defects.</p>',
        displayName: 'Total Equipment Coverage',
        preSelected: false,
        sfoSORId: '81495',
        hasEcpdDiscount: false,
        defaultDisplayFlag: false,
      }, {
        sorSfoType: 'INSUR,I',
        priceTerm: '/mo',
        sfoSkuId: 'sku1230447',
        price: 7.15,
        wasPrice: 0.0,
        introText: '<p>Next day replacement for loss, theft, and damage.</p>',
        displayName: 'Wireless Phone Protection',
        preSelected: false,
        sfoSORId: '81493',
        hasEcpdDiscount: false,
        defaultDisplayFlag: false,
      }, {
        sorSfoType: 'INSUR,W',
        priceTerm: '/mo',
        sfoSkuId: 'sku401085',
        price: 3.0,
        wasPrice: 0.0,
        introText: '<p>Next day replacement for post&ndash;warranty mechanical or electrical defect coverage.</p>',
        displayName: 'Extended Warranty',
        preSelected: false,
        sfoSORId: '79184',
        hasEcpdDiscount: false,
        defaultDisplayFlag: false,
      }, {
        sorSfoType: 'INSUR,G',
        priceTerm: '/mo',
        sfoSkuId: 'sku401075',
        price: 7.0,
        wasPrice: 0.0,
        introText: '<p>Advanced technical support. Does not include protection.</p>',
        displayName: 'Tech Coach',
        preSelected: false,
        sfoSORId: '77963',
        hasEcpdDiscount: false,
        defaultDisplayFlag: false,
      }, {
        sorSfoType: 'INSUR,D',
        priceTerm: '/mo',
        sfoSkuId: 'sku401064',
        price: 0.0,
        wasPrice: 0.0,
        introText: '<p>No device coverage plan for your device. If your device is lost, stolen, damaged (including liquid damage), or experiences a post&ndash;warranty defect, the replacement cost may be as high as the retail price.</p>',
        displayName: 'Decline Equipment Protection',
        preSelected: true,
        sfoSORId: '66332',
        hasEcpdDiscount: false,
        defaultDisplayFlag: false,
      }],
      tapFeatureInfo: null,
      tapExist: false,
      tapEligible: false,
      tapMsg: null,
    },
    cq: {
      protectionHeader: 'Which protection plan would you like?',
      protectionSubtitle: 'You can change your mind whithin 30 days of activating your device',
      currentProtectionText: 'Current device protection',
      protectionFooterText: 'For more information see device protection details',
      moreDetailsHeader: '5 things to know about Equipment Protection',
      moreDetailsSubtitle: null,
      modeDetailsText: 'Lorem ipsum dolor sit amet',
      tmpDisclosureMsg: 'You can add total mobile protection multi device on your website within 30 days of purchase',
    },
  },
  ErrorMap: null,
  statusMessage: 'Service completed Successfully.',
  statusCode: '00',
};
