
const cartJSON = {
  "statusCode": "00",
  "output": {
    "orderId": "S2c2fa8b2fef2991cbd1c82fbcd7cc40b{ss3}",
    "redirectionURL": null,
    "isPOBODeviceInCart": false,
    "dueTodayPOBOHeader": null,
    "items": [
      {
        "deviceProdId": "dev6720118",
        "deviceManufactureName": "Google",
        "deviceProductDisplayName": "Pixel, Phone by Google",
        "colorName": "Quite Black",
        "capacity": "32GB",
        "flow": "AAL",
        "mtn": null,
        "displayMtn": "808-264-XXXX",
        "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Google_Sailfish_Slate?$device-med$&fmt=jpeg&wid=75&hei=150",
        "deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/Google_Sailfish_Slate?$device$&bgc=ffffff&wid=158&hei=300",
        "activationFee": "30.00",
        "waivedActivationFeePromo": false,
        "upgradeFee": "0.00",
        "waivedUpgradeFeePromo": false,
        "edgeDevice": true,
        "price": "22.91",
        "priceText": "Device payment",
        "priceSubTitle": "For 24 months, 0% APR.Retail Price: $549.99",
        "edgeItemDownPaymentAmount": "0.00",
        "installmentBalance": "0.00",
        "deviceEdgeUpAmount": "0.00",
        "deviceEdgeBuyOutAmount": "0.00",
        "protectionOption": {
          "name": "Decline Equipment Protection",
          "price": "0.00",
          "featureType": "INS",
          "featureSkuId": "sku401064",
          "hideEditProtection": false,
          "displayMsg": null,
          "tapOpted": false
        },
        "commerceItemId": "S2c2fa8b2fef2991cbd1c82fbcd7cc40b{ss3}_device_1",
        "deviceSkuId": "sku2170529",
        "deviceSORId": "G-2PW4100-021-A",
        "lacPrice": "0.00",
        "lacText": "SMARTPHONE line access",
        "inventoryStatus": "1000",
        "inventoryAvailableDate": null,
        "hasEcpdDiscount": true,
        "hasEcpdDiscountForDevicePayment": false,
        "devicePromotionList": [],
        "bicOfferApplied": false,
        "bicContractPrice": 0,
        "bicDiscountedContractPrice": 0,
        "bicSavings": 0,
        "myOfferWaiveUpgradeFee": false,
        "shipCommitInd": null,
        "promoLACMessage": null,
        "additionalFeatures": [],
        "bicMessage": null,
        "bicMessagetooltip": null,
        "editDeviceUrl": "/od/cust/auth/device/expressconfig/?commerceItemId=S2c2fa8b2fef2991cbd1c82fbcd7cc40b%7Bss3%7D_device_1&deviceProdId=dev6720118&deviceSkuId=sku2170529&editDevice=true&flow=AAL",
        "fullRetailPrice": "549.99",
        "fromSavedCart": false,
        "numberShareDevice": false,
        "numberSharedMtn": null,
        "itemOnJaxPlan": false,
        "humCarDetails": null,
        "monthlyPriceAfterDownPaymentBeforeDiscount": 0,
        "originalFullRetailPrice": 0,
        "hasReducedRetailPrice": false,
        "hasReducedDueMonthly": false,
        "originalDueMonthly": 0,
        "lineAccessPromotionText": null,
        "downPaymentPromotionText": null,
        "contractTerm": "99",
        "deviceType": null,
        "activationFeeText": null,
        "promoOfferText": null,
        "promoApplied": false,
        "portIn": false,
        "deviceNickName": "Pixel, Phone by Google",
        "totalNumberShareExtension": 0,
        "sbdOffer": null,
        "hostCommerceItemId": null,
        "trunkMtn": null
      },
      {
        "deviceProdId": "dev2160046",
        "deviceManufactureName": "Samsung",
        "deviceProductDisplayName": "Gusto&reg; 3",
        "colorName": "Black",
        "capacity": null,
        "flow": "AAL",
        "mtn": null,
        "displayMtn": "808-264-XXXX",
        "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Gusto_3_Flipphone?$device-med$&fmt=jpeg&wid=75&hei=150",
        "deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Gusto_3_Flipphone?$device$&bgc=ffffff&wid=158&hei=300",
        "activationFee": "30.00",
        "waivedActivationFeePromo": false,
        "upgradeFee": "0.00",
        "waivedUpgradeFeePromo": false,
        "edgeDevice": true,
        "price": "71.99",
        "priceText": "Full Retail Device Price",
        "priceSubTitle": null,
        "edgeItemDownPaymentAmount": "0.00",
        "installmentBalance": "0.00",
        "deviceEdgeUpAmount": "0.00",
        "deviceEdgeBuyOutAmount": "0.00",
        "protectionOption": {
          "name": "Decline Equipment Protection",
          "price": "0.00",
          "featureType": "INS",
          "featureSkuId": "sku401064",
          "hideEditProtection": false,
          "displayMsg": null,
          "tapOpted": false
        },
        "commerceItemId": "S2c2fa8b2fef2991cbd1c82fbcd7cc40b{ss3}_device_2",
        "deviceSkuId": "sku920295",
        "deviceSORId": "SMB311ZKA",
        "lacPrice": "0.00",
        "lacText": null,
        "inventoryStatus": "1000",
        "inventoryAvailableDate": null,
        "hasEcpdDiscount": true,
        "hasEcpdDiscountForDevicePayment": false,
        "devicePromotionList": [],
        "bicOfferApplied": false,
        "bicContractPrice": 0,
        "bicDiscountedContractPrice": 0,
        "bicSavings": 0,
        "myOfferWaiveUpgradeFee": false,
        "shipCommitInd": null,
        "promoLACMessage": null,
        "additionalFeatures": [],
        "bicMessage": null,
        "bicMessagetooltip": null,
        "editDeviceUrl": "/od/cust/auth/device/expressconfig/?commerceItemId=S2c2fa8b2fef2991cbd1c82fbcd7cc40b%7Bss3%7D_device_2&deviceProdId=dev2160046&deviceSkuId=sku920295&editDevice=true&flow=AAL",
        "fullRetailPrice": "0.00",
        "fromSavedCart": false,
        "numberShareDevice": false,
        "numberSharedMtn": null,
        "itemOnJaxPlan": false,
        "humCarDetails": null,
        "monthlyPriceAfterDownPaymentBeforeDiscount": 0,
        "originalFullRetailPrice": 0,
        "hasReducedRetailPrice": false,
        "hasReducedDueMonthly": false,
        "originalDueMonthly": 0,
        "lineAccessPromotionText": null,
        "downPaymentPromotionText": null,
        "contractTerm": "0",
        "deviceType": null,
        "activationFeeText": null,
        "promoOfferText": null,
        "promoApplied": false,
        "portIn": false,
        "deviceNickName": "Gusto&reg; 3",
        "totalNumberShareExtension": 0,
        "sbdOffer": null,
        "hostCommerceItemId": null,
        "trunkMtn": null
      }
    ],
    "accessories": [],
    "accessoriesBundle": null,
    "taxDetails": {
      "taxPrice": "25.91",
      "cityStateString": "Kahului, HI",
      "stateTaxLabel": null,
      "zipCode": null
    },
    "totalDueToday": "97.90",
    "totalDueMonthly": "22.91",
    "employeeDiscount": 0,
    "pastDueBalance": "0.00",
    "emptyCartFlag": false,
    "edgeContractDeviceInCart": true,
    "totalEdgeUpAmount": "0.00",
    "totalEdgeUpBuyOutAmount": "0.00",
    "totalEdgeOrderDownPayment": "0.00",
    "tradeInCredit": null,
    "tradeInPromoDetails": null,
    "promotionList": [],
    "cartMessages": {
      "cartReadyforCheckout": true,
      "message": "",
      "code": null
    },
    "cartItemCount": 2,
    "mailInRebateTotal": 0,
    "mailInRebateDetails": null,
    "promoCodes": [],
    "promoCodeHeader": "Promo code? Lucky you.",
    "promoCodeLabel": "Promo code",
    "addAnotherPromoCodeText": "Add another promo code",
    "applyBtn": "Apply",
    "emptyCartMessage": "There are no items in your cart",
    "shopBtn": "Shop",
    "tradeInPromoEligible": true,
    "eligibleForSingleDeviceRibbon": false,
    "eligibleForMultiDeviceAllocation": false,
    "retrieveCartSuccessful": false,
    "standaloneAccessories": false,
    "dueTodayText": "Due today",
    "dueMonthlyText": "Due Monthly",
    "mainCartHeader": "Time to review your cart.",
    "mainCartSubTitle": "Enjoy free 2-day shipping.",
    "shopMoreBtnText": "Shop more",
    "checkoutBtn": "Check out",
    "editBtn": "Edit",
    "removeLinkText": "Remove",
    "mainCartFooterText": "Want to start over?",
    "mainCartFooterLinkText": "Emtpy your cart",
    "shopMoreLink": "/od/cust/auth/shoplanding/",
    "activationFeeText": "Activation Fee",
    "waivedActivationText": "Waived Activation Fee",
    "upgradeFeeText": "Upgrade Fee",
    "waivedUpgradeFeeText": "Waived Upgrade Fee",
    "saveBtnLabel": "Save",
    "zipCodeHeader": "Please enter a new ZIP code",
    "tradeInCreditHeader": "Trade-in Credit for this device",
    "tradeInFooterLink": "Tell me more",
    "tradeInOfferDetailsHeader": "Offer Details",
    "tradeInOfferDetailsMsg": "long block of text",
    "tradeInConfirmationBtn": "Got it",
    "lonelyCartMessage": "Your cart is lonely.",
    "checkoutButtonURL": "/od/cust/auth/checkout/initiateCheckout",
    "tradeInUrl": "/od/cust/auth/tradein/prompt?gotoCart=true",
    "mainInRebateDetails": null,
    "deviceProtectionDetails": {
      "deviceProtectionDetailsHeader": "device protection details",
      "deviceProtectionDetailsSubTitle": "Five things you need to know about Equipment Protection",
      "deviceProtectionDetailsText": "<div> <p>Cost per Month and Individual Service Availability. Total Mobile Protection (TMP) Single Device and Total Mobile Protection Multi-Device are a combination of multiple products, each of which is available separately per device: Wireless Phone Protection (WPP) $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; Verizon Wireless Extended Warranty (EW) $3.00; and Verizon Tech Coach $7.00. You may also purchase Total Equipment Coverage (TEC) for $7.00/Basic Devices &amp; Tablets or for $9.00/Smartphones &amp; iPhone Devices. TEC is a combination of 2 products, each of which is available separately: WPP $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; and Verizon Wireless EW for $3.00.</p> <p> Applicability and Amount of Deductible. For lost, stolen and damaged device claims, deductibles are $49 for basic phones and, depending on device, $49-$199 for smartphones and tablets. For a full list of deductibles click here <a href='http://phoneclaim.com/verizon/deductible' target='_blank'>http://phoneclaim.com/verizon/deductible.</a> </p> <p>Claim Limits for loss, stolen and damaged devices. Equipment claim maximum is $400 or $1,500, depending on device, and limited to three claims per 12-month period for TMP Single Device and up to nine claims per 12-month period for TMP Multi-Device.</p> <p>Covered and Replacement Equipment. If your device is lost, stolen or damaged, your accessories are covered too ï¿1Ž2 one each of the following: standard battery, standard car charger, standard case, standard home charger and standard earbud. It is our goal to provide you with a replacement device that is the same color and has the same features, but this cannot be guaranteed. If the same make and model you claim is not available, a similar make and model will be substituted. Your replacement device could be new or refurbished. You may also receive generic accessories with lost, stolen or damaged claims.</p> <p>Cancellation Policy. Change your mind? You can cancel your coverage at any time and receive a pro-rated refund of your monthly fee.</p> </div>"
    },
    "preOrderAlertMsg": "Your order contains one or more items that are not in stock. All items will ship together when everything is available.",
    "bicText": null,
    "hasSubmittedTradein": false,
    "cpcSucessful": false,
    "cpcSucessfulNotification": false,
    "protectionURL": "/od/cust/auth/protection",
    "itemsFromRetrievedCart": false,
    "totalActivationFee": "60.00",
    "itemOnJaxPlan": false,
    "anyLineFreeSPO": null,
    "bicOfferMessage": null,
    "cartMFCompatible": false,
    "cartValidationDetailsVo": {
      "cartReadyforCheckout": true,
      "cartIncompleteCode": null,
      "cartIncompleteMessage": null,
      "orderId": "S2c2fa8b2fef2991cbd1c82fbcd7cc40b{ss3}"
    },
    "cartEdited": false,
    "iconicFlow": false,
    "plans": {
      "planOnlyDueMonthly": "70.00",
      "dueMonthly": "70.00",
      "dueToday": "0.00",
      "items": [
        {
          "planType": "The new Verizon Plan Large 8 GB",
          "planSorId": "96328",
          "planProdId": "plan2880001",
          "planSkuId": "sku2040017",
          "planLetter": null,
          "planDescription": "",
          "planDisplayName": "The new Verizon Plan Large 8 GB",
          "planChangeURL": null,
          "planImageURL": null,
          "accountAccess": {
            "name": "The new Verizon Plan Large 8 GB",
            "price": "70.00",
            "discountPrice": 0,
            "promoMessage": null,
            "hasEcpdDiscount": false,
            "planAmount": "70.00"
          }
        }
      ]
    },
    "removePromoCodeURL": "/od/cust/auth/cart/removePromoCode",
    "applyPromoCodeURL": "/od/cust/auth/cart/applyPromoCode",
    "clearCartURL": "/od/cust/auth/cart/clearCart",
    "addOrUpdateDeviceURL": "/od/cust/auth/cart/addOrUpdateDevice",
    "addOrRemoveAccessoryURL": "/od/cust/auth/cart/addOrRemoveAccessory",
    "changeZipCodeURL": "/od/cust/authcart/changeZipCode/",
    "addOrUpdateFeatureURL": "/od/cust/auth/cart/addOrUpdateFeature",
    "initiateCheckoutURL": "/od/cust/auth/checkout/initiateCheckout",
    "accountMember": false,
    "tmpMdOpted": false,
    "tmpMd": null,
    "splitShipment": false,
    "authenticated": false
  },
  "errorMap": null,
  "statusMessage": ""
}

export default cartJSON;
