exports.cartJSON = {
  "output": {
    "orderId": "",
    "redirectionURL": null,
    "isPOBODeviceInCart": false,
    "accGuestCheckoutEnabled": false,
    "dueTodayPOBOHeader": null,
    "items": null,
    "existingDevices": null,
    "plans": null,
    "accessories": [
      
    ],
    "cartEdited": false,
    "iconicFlow": false,
    "removePromoCodeURL": "/od/cust/auth/cart/removePromoCode",
    "applyPromoCodeURL": "/od/cust/auth/cart/applyPromoCode",
    "clearCartURL": "/od/cust/auth/cart/clearCart",
    "addOrUpdateDeviceURL": "/od/cust/auth/cart/addOrUpdateDevice",
    "addOrRemoveAccessoryURL": "/od/cust/auth/cart/addOrRemoveAccessory",
    "changeZipCodeURL": "/od/cust/auth/cart/changezipcode/",
    "addOrUpdateFeatureURL": "/od/cust/auth/cart/addOrUpdateFeature",
    "initiateCheckoutURL": "/od/cust/auth/checkout/initiateCheckout",
    "guestCheckoutSignInURL": null,
    "accountMember": false,
    "removeDeviceURL": "/digital/cpc/removeDevice",
    "enableRemoveDeviceAndMMPlan": false,
    "accessoriesBundle": null,
    "taxDetails": null,
    "totalDueToday": "0.00",
    "totalDueMonthly": "0.00",
    "employeeDiscount": 0,
    "pastDueBalance": "0.00",
    "emptyCartFlag": true,
    "edgeContractDeviceInCart": false,
    "totalEdgeUpAmount": "0.00",
    "totalEdgeUpBuyOutAmount": "0.00",
    "totalEdgeOrderDownPayment": "0.00",
    "tradeInCredit": null,
    "tradeInPromoDetails": null,
    "promotionList": null,
    "cartMessages": {
      "cartReadyforCheckout": false,
      "message": null,
      "code": null
    },
    "cartItemCount": 0,
    "mailInRebateTotal": 0,
    "mailInRebateDetails": null,
    "promoCodes": null,
    "promoCodeHeader": "Promo code? Lucky you.",
    "promoCodeLabel": "Promo code",
    "addAnotherPromoCodeText": "Add another promo code",
    "applyBtn": "Apply",
    "emptyCartMessage": "There are no items in your cart",
    "shopBtn": "Shop",
    "tradeInPromoEligible": true,
    "eligibleForSingleDeviceRibbon": false,
    "eligibleForMultiDeviceAllocation": false,
    "retrieveCartSuccessful": false,
    "standaloneAccessories": false,
    "dueTodayText": "Due today",
    "dueMonthlyText": "Due Monthly",
    "mainCartHeader": "Time to review your cart.",
    "mainCartSubTitle": "Enjoy free 2-day shipping",
    "mainCartNextDayShippingMessage": null,
    "shopMoreBtnText": "Shop more",
    "checkoutBtn": "Check out",
    "editBtn": "Edit",
    "removeLinkText": "Remove",
    "mainCartFooterText": "Want to start over?",
    "mainCartFooterLinkText": "Emtpy your cart",
    "shopMoreLink": "/od/cust/auth/shoplanding/",
    "activationFeeText": "Activation Fee",
    "waivedActivationText": "Waived Activation Fee",
    "upgradeFeeText": "Upgrade Fee",
    "waivedUpgradeFeeText": "Waived Upgrade Fee",
    "saveBtnLabel": "Save",
    "zipCodeHeader": "Please enter a new ZIP code",
    "tradeInCreditHeader": "Trade-in Credit for this device",
    "tradeInFooterLink": "Tell me more",
    "tradeInOfferDetailsHeader": "Offer Details",
    "tradeInOfferDetailsMsg": "long block of text",
    "tradeInConfirmationBtn": "Got it",
    "lonelyCartMessage": "Your cart is lonely.",
    "lonelyCartSubMessage": null,
    "checkoutButtonURL": "/od/cust/auth/checkout/initiateCheckout",
    "tradeInUrl": null,
    "mainInRebateDetails": null,
    "deviceProtectionDetails": {
      "deviceProtectionDetailsHeader": "device protection details",
      "deviceProtectionDetailsSubTitle": "Five things you need to know about Equipment Protection",
      "deviceProtectionDetailsText": "<div> <p>Cost per Month and Individual Service Availability. Total Mobile Protection (TMP) Single Device and Total Mobile Protection Multi-Device are a combination of multiple products, each of which is available separately per device: Wireless Phone Protection (WPP) $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; Verizon Wireless Extended Warranty (EW) $3.00; and Verizon Tech Coach $7.00. You may also purchase Total Equipment Coverage (TEC) for $7.00/Basic Devices &amp; Tablets or for $9.00/Smartphones &amp; iPhone Devices. TEC is a combination of 2 products, each of which is available separately: WPP $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; and Verizon Wireless EW for $3.00.</p> <p> Applicability and Amount of Deductible.  For lost, stolen and damaged device claims, deductibles are $49 for basic phones and, depending on device, $49-$199 for smartphones and tablets. For a full list of deductibles click here <a href='http://phoneclaim.com/verizon/deductible' target='_blank'>http://phoneclaim.com/verizon/deductible.</a> </p> <p>Claim Limits for loss, stolen and damaged devices. Equipment claim maximum is $400 or $1,500, depending on device, and limited to three claims per 12-month period for TMP Single Device and up to nine claims per 12-month period for TMP Multi-Device.</p> <p>Covered and Replacement Equipment. If your device is lost, stolen or damaged, your accessories are covered too ??1?2 one each of the following: standard battery, standard car charger, standard case, standard home charger and standard earbud. It is our goal to provide you with a replacement device that is the same color and has the same features, but this cannot be guaranteed. If the same make and model you claim is not available, a similar make and model will be substituted. Your replacement device could be new or refurbished. You may also receive generic accessories with lost, stolen or damaged claims.</p> <p>Cancellation Policy. Change your mind? You can cancel your coverage at any time and receive a pro-rated refund of your monthly fee.</p> </div>"
    },
    "preOrderAlertMsg": "Your order contains one or more items that are not in stock. All items will ship together when everything is available.",
    "bicText": null,
    "hasSubmittedTradein": false,
    "cpcSucessful": false,
    "cpcSucessfulNotification": false,
    "protectionURL": "/od/cust/auth/protection",
    "itemsFromRetrievedCart": false,
    "totalActivationFee": "0.00",
    "itemOnJaxPlan": false,
    "anyLineFreeSPO": null,
    "paypalEnabled": false,
    "paypalApi": "/od/cust/auth/checkout/paypal/cmpilookup?triggerFrom=PAYMENT",
    "aalUrl": "/od/cust/auth/shop?flow=AAL",
    "eupUrl": "/od/cust/auth/shop?flow=EUP",
    "rawSubTotalDueToday": null,
    "overallDueMonthly": "0.00",
    "additionalCharges": [
      
    ],
    "accessoryGWURL": null,
    "accessoryPDPURL": null,
    "removeTradeInURL": "/od/trade-in/removeTradeIn",
    "masterpassEnabled": true,
    "targetter": {
      "freeShippingText": "Free Shipping or In-Store Pickup",
      "freeShippingDesc": "Free shipping \n Free 2-day shipping when you order online M-F by 8PM EST, Sat by 2PM EST (excluding holidays), will deliver in two business days within the U.S. only (excluding AK & HI). 2-day orders placed after 2PM EST on Sat will deliver by Wednesday. Overnight shipping to destinations within the U.S. (excluding AK & HI) is generally available for orders placed M-F until 11PM EST, excluding holidays. Orders that contain a pre-order or backorder will ship via 2-day shipping on or prior to the committed date. Subject to credit authorization, verification and inventory availability.",
      "nextDayText": "Want it tomorrow? Order by 11PM ET w/Next Day Shipping. Pre-order devices excl'd",
      "nextDayDesc": "Depending on inventory availability for destinations within the US (excluding AK, HI) for orders placed M-F (excluding holidays). Next Day Shipping is not available for devices in pre-order status. Pre-order devices will ship as inventory becomes available",
      "contentText": "Keep your content.",
      "contentDesc": "Don't worry, we've got you covered. We'll make sure all of your pictures, contacts and content transfer from one phone to the other without issue.",
      "returnPolicyText": "14 day return policy",
      "returnPolicyDesc": "You may return or exchange wireless devices and accessories purchased from Verizon Wireless within 14 days of purchase. A restocking fee of $35 applies to any return or exchange of a wireless device (excluding Hawaii)."
    },
    "overallDiscountedAmount": "0.00",
    "ecpdDueTodayDiscountedAmount": "0.00",
    "ecpdDueMonthlySavings": "0.00",
    "devicesURL": "/od/devices/",
    "autoPayApplied": false,
    "globalPromotion": null,
    "cartURL": "/od/cust/auth/cart/getCartDetails?format=json",
    "byodUrl": "/od/cust/auth/shop?flow=NSO",
    "masterpassConfigInfo": null,
    "accessoryShopURL": "/accessories",
    "bicOfferMessage": null,
    "cartMFCompatible": false,
    "cartValidationDetailsVo": null,
    "tmpMdOpted": false,
    "tmpMd": null,
    "frontEndPersonalization": null,
    "allowAAL": true,
    "allowEUP": true,
    "isHLLPlanInOrder": false,
    "accountLevelDiscountList": null,
    "planNotFoundRedirect": null,
    "protectionNotFoundRedirect": null,
    "mmplanEnabled": false,
    "smartFamilyInCart": false,
    "authenticated": true,
    "splitShipment": false
  },
  "errorMap": null,
  "statusMessage": "",
  "statusCode": "00"
};