
 const cartJSON =
{
  "statusCode": "00",
  "output": {
    "orderId": "Sd2810242635e6b1f9ec1111af653849d{ss2}",
    "redirectionURL": null,
    "isPOBODeviceInCart": false,
    "dueTodayPOBOHeader": null,
    "items": [
      {
        "deviceProdId": "dev5400100",
        "deviceManufactureName": "Verizon",
        "deviceProductDisplayName": "Hum342<sup>&#43;</sup>",
        "colorName": "Black",
        "capacity": null,
        "flow": "AAL",
        "mtn": null,
        "humCarDetails":{
          "year":"2016",
          "make":"Acula",
          "model":"irlx",
          "color":"red"
        },
        "displayMtn": null,
        "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/hum-plus-vzw?$device-med$&fmt=jpeg&wid=75&hei=150",
        "deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/hum-plus-vzw?$device$&bgc=ffffff&wid=158&hei=300",
        "activationFee": "30.00",
        "waivedActivationFeePromo": false,
        "upgradeFee": "0.00",
        "waivedUpgradeFeePromo": false,
        "edgeDevice": true,
        "price": "120.00",
        "priceText": "Full Retail Device Price",
        "priceSubTitle": null,
        "edgeItemDownPaymentAmount": "0.00",
        "installmentBalance": "0.00",
        "deviceEdgeUpAmount": "0.00",
        "deviceEdgeBuyOutAmount": "0.00",
        "protectionOption": {
          "name": "Decline Equipment Protection",
          "price": "0.00",
          "featureType": "INS",
          "featureSkuId": "sku401064",
          "displayMsg": null,
          "hideEditProtection" : true
        },
        "commerceItemId": "Sd2810242635e6b1f9ec1111af653849d{ss2}_device_1",
        "deviceSkuId": "sku1800159",
        "deviceSORId": "VZ-0750-001-US",
        "lacPrice": "0.00",
        "lacText": "CONNECTED_DEVICE line access",
        "inventoryStatus": "1000",
        "inventoryAvailableDate": null,
        "hasEcpdDiscount": true,
        "hasEcpdDiscountForDevicePayment": false,
        "devicePromotionList": [],
        "bicOfferApplied": false,
        "bicContractPrice": 0,
        "bicDiscountedContractPrice": 0,
        "bicSavings": 0,
        "myOfferWaiveUpgradeFee": false,
        "shipCommitInd": null,
        "promoLACMessage": null,
        "additionalFeatures": [
          {
            "name": "Hum by Verizon",
            "price": "5.00",
            "featureType": "OPT",
            "featureSkuId": "sku1830299",
            "displayMsg": null
          }
        ],
        "bicMessage": null,
        "bicMessagetooltip": null,
        "editDeviceUrl": "/preorder/device/expressconfig/?commerceItemId=Sd2810242635e6b1f9ec1111af653849d%7Bss2%7D_device_1&deviceProdId=dev5400100&deviceSkuId=sku1800159&editDevice=true&flow=AAL",
        "fullRetailPrice": "0.00",
        "fromSavedCart": false,
        "numberShareDevice": false,
        "numberSharedMtn": null,
        "itemOnJaxPlan": false,
        "monthlyPriceAfterDownPaymentBeforeDiscount": 0,
        "originalFullRetailPrice": 0,
        "hasReducedRetailPrice": false,
        "hasReducedDueMonthly": false,
        "originalDueMonthly": 0,
        "lineAccessPromotionText": null,
        "downPaymentPromotionText": null,
        "contractTerm": "0",
        "deviceType": null,
        "activationFeeText": null,
        "promoOfferText": null,
        "promoApplied": false,
        "portIn": false,
        "deviceNickName": "Hum<sup>&#43;</sup>",
        "totalNumberShareExtension": 0,
        "sbdOffer": null,
        "hostCommerceItemId": null,
        "trunkMtn": null
      }
    ],
    "accessories": [],
    "accessoriesBundle": null,
    "taxDetails": {
      "taxPrice": "8.10",
      "cityStateString": "Southport, NC",
      "stateTaxLabel": null,
      "zipCode": null
    },
    "totalDueToday": "128.10",
    "totalDueMonthly": "5.00",
    "employeeDiscount": 0,
    "pastDueBalance": "0.00",
    "emptyCartFlag": false,
    "edgeContractDeviceInCart": true,
    "totalEdgeUpAmount": "0.00",
    "totalEdgeUpBuyOutAmount": "0.00",
    "totalEdgeOrderDownPayment": "0.00",
    "tradeInCredit": null,
    "tradeInPromoDetails": null,
    "promotionList": null,
    "cartMessages": {
      "cartReadyforCheckout": true,
      "message": null,
      "code": null
    },
    "cartItemCount": 1,
    "mailInRebateTotal": 0,
    "mailInRebateDetails": null,
    "promoCodes": null,
    "promoCodeHeader": "Promo code? Lucky you.",
    "promoCodeLabel": "Promo code",
    "addAnotherPromoCodeText": "Add another promo code",
    "applyBtn": "Apply",
    "emptyCartMessage": "There are no items in your cart",
    "shopBtn": "Shop",
    "tradeInPromoEligible": true,
    "eligibleForSingleDeviceRibbon": false,
    "eligibleForMultiDeviceAllocation": false,
    "retrieveCartSuccessful": false,
    "standaloneAccessories": false,
    "dueTodayText": "Due today",
    "dueMonthlyText": "Due Monthly",
    "mainCartHeader": "Time to review your cart.",
    "mainCartSubTitle": "Enjoy free 2-day shipping.",
    "shopMoreBtnText": "Shop more",
    "checkoutBtn": "Check out",
    "editBtn": "Edit",
    "removeLinkText": "Remove",
    "mainCartFooterText": "Want to start over?",
    "mainCartFooterLinkText": "Emtpy your cart",
    "shopMoreLink": "/preorder/device/expressconfig/",
    "activationFeeText": "Activation Fee",
    "waivedActivationText": "Waived Activation Fee",
    "upgradeFeeText": "Upgrade Fee",
    "waivedUpgradeFeeText": "Waived Upgrade Fee",
    "saveBtnLabel": "Save",
    "zipCodeHeader": "Please enter a new ZIP code",
    "tradeInCreditHeader": "Trade-in Credit for this device",
    "tradeInFooterLink": "Tell me more",
    "tradeInOfferDetailsHeader": "Offer Details",
    "tradeInOfferDetailsMsg": "long block of text",
    "tradeInConfirmationBtn": "Got it",
    "lonelyCartMessage": "Your cart is lonely.",
    "checkoutButtonURL": "/preorder/checkout/initiateCheckout",
    "tradeInUrl": "/preorder/tradein/prompt?gotoCart=true",
    "mainInRebateDetails": null,
    "deviceProtectionDetails": {
      "deviceProtectionDetailsHeader": "device protection details",
      "deviceProtectionDetailsSubTitle": "Five things you need to know about Equipment Protection",
      "deviceProtectionDetailsText": "<div> <p>Cost per Month and Individual Service Availability. Total Mobile Protection (TMP) Single Device and Total Mobile Protection Multi-Device are a combination of multiple products, each of which is available separately per device: Wireless Phone Protection (WPP) $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; Verizon Wireless Extended Warranty (EW) $3.00; and Verizon Tech Coach $7.00. You may also purchase Total Equipment Coverage (TEC) for $7.00/Basic Devices &amp; Tablets or for $9.00/Smartphones &amp; iPhone Devices. TEC is a combination of 2 products, each of which is available separately: WPP $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; and Verizon Wireless EW for $3.00.</p> <p> Applicability and Amount of Deductible.  For lost, stolen and damaged device claims, deductibles are $49 for basic phones and, depending on device, $49-$199 for smartphones and tablets. For a full list of deductibles click here <a href='http://phoneclaim.com/verizon/deductible' target='_blank'>http://phoneclaim.com/verizon/deductible.</a> </p> <p>Claim Limits for loss, stolen and damaged devices. Equipment claim maximum is $400 or $1,500, depending on device, and limited to three claims per 12-month period for TMP Single Device and up to nine claims per 12-month period for TMP Multi-Device.</p> <p>Covered and Replacement Equipment. If your device is lost, stolen or damaged, your accessories are covered too ï¿1Ž2 one each of the following: standard battery, standard car charger, standard case, standard home charger and standard earbud. It is our goal to provide you with a replacement device that is the same color and has the same features, but this cannot be guaranteed. If the same make and model you claim is not available, a similar make and model will be substituted. Your replacement device could be new or refurbished. You may also receive generic accessories with lost, stolen or damaged claims.</p> <p>Cancellation Policy. Change your mind? You can cancel your coverage at any time and receive a pro-rated refund of your monthly fee.</p> </div>"
    },
    "preOrderAlertMsg": "Your order contains one or more items that are not in stock. All items will ship together when everything is available.",
    "bicText": null,
    "hasSubmittedTradein": false,
    "cpcSucessful": false,
    "cpcSucessfulNotification": false,
    "protectionURL": "/preorder/protection",
    "itemsFromRetrievedCart": false,
    "totalActivationFee": "30.00",
    "itemOnJaxPlan": false,
    "bicOfferMessage": null,
    "cartMFCompatible": false,
    "cartValidationDetailsVo": {
      "cartReadyforCheckout": true,
      "cartIncompleteCode": null,
      "cartIncompleteMessage": null,
      "orderId": "Sd2810242635e6b1f9ec1111af653849d{ss2}"
    },
    "cartEdited": false,
    "iconicFlow": true,
    "plans": {
      "planOnlyDueMonthly": "100.00",
      "dueMonthly": "100.00",
      "dueToday": "0.00",
      "items": [
        {
          "planType": "The Verizon Plan XX Large 18GB",
          "planSorId": "94679",
          "planProdId": "plan2440001",
          "planSkuId": "sku1730130",
          "planLetter": null,
          "planDescription": "",
          "planDisplayName": "The Verizon Plan XX Large 18GB",
          "planChangeURL": null,
          "planImageURL": null,
          "accountAccess": {
            "name": "The Verizon Plan XX Large 18GB",
            "price": "100.00",
            "discountPrice": 0,
            "promoMessage": null,
            "hasEcpdDiscount": false,
            "planAmount": "100.00"
          }
        }
      ]
    },
    "removePromoCodeURL": "/preorder/cart/removePromoCode",
    "applyPromoCodeURL": "/preorder/cart/applyPromoCode",
    "clearCartURL": "/preorder/cart/clearCart",
    "addOrUpdateDeviceURL": "/preorder/cart/addOrUpdateDevice",
    "addOrRemoveAccessoryURL": "/preorder/cart/addOrRemoveAccessory",
    "changeZipCodeURL": "/preordercart/changeZipCode/",
    "addOrUpdateFeatureURL": "/preorder/cart/addOrUpdateFeature",
    "initiateCheckoutURL": "/preorder/checkout/initiateCheckout",
    "splitShipment": false
  },
  "errorMap": null,
  "statusMessage": ""
};

 export default cartJSON;
