const cartJSON =
{
  "statusCode": "00",
  "output": {
    "orderId": "S54ba8f3e0cbb18fbf293e8ca320415e3{d4}",
    "redirectionURL": null,
    "isPOBODeviceInCart": false,
    "dueTodayPOBOHeader": null,
    "items": null,
    "accessories": [
      {
        "scene7ImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/universal-leather-case-iset-unisdpchmd1?$acc-med$",
        "name": "Universal Vegan Leather Pouch with Belt Clip - Medium",
        "quantity": 11,
        "commerceItemId": "S54ba8f3e0cbb18fbf293e8ca320415e3{d4}_accessory_1",
        "color": null,
        "size": null,
        "inventoryStatus": "1000",
        "inventoryAvailableDate": null,
        "prodId": "acc1960127",
        "skuId": "sku850127",
        "sorId": "UNISDPCHMD1",
        "hasEcpdDiscount": false,
        "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/universal-leather-case-iset-unisdpchmd1?$acc-med$",
        "hasBogoDiscount": false,
        "price": 28.99,
        "wasPrice": 29.99,
        "discounted": true,
        "discountPercentage": 3.33,
        "discountPrice": 1,
        "editAccessoryUrl": "/preorder/accessoryDetails/?accProdId=acc1960127&action=edit&accCommerceId=S54ba8f3e0cbb18fbf293e8ca320415e3{d4}_accessory_1&contractTerm=0&deviceSkuId=null#/chooseColor/skuId=sku850127"
      }
    ],
    "accessoriesBundle": null,
    "taxDetails": {
      "taxPrice": "31.24",
      "cityStateString": "Glendale, CA",
      "stateTaxLabel": null,
      "zipCode": null
    },
    "totalDueToday": "60.23",
    "totalDueMonthly": "0.00",
    "employeeDiscount": 0,
    "pastDueBalance": "0.00",
    "emptyCartFlag": false,
    "edgeContractDeviceInCart": true,
    "totalEdgeUpAmount": "0.00",
    "totalEdgeUpBuyOutAmount": "0.00",
    "totalEdgeOrderDownPayment": "0.00",
    "tradeInCredit": null,
    "tradeInPromoDetails": null,
    "promotionList": [
      {
        "promoMsg": "BUY ANY CASE GET ONE EQUAL OR LESSER HALF OFF 4 99",
        "promoAmount": "1.00",
        "barcode": null,
        "skuId": "UNISDPCHMD1"
      }
    ],
    "cartMessages": {
      "cartReadyforCheckout": true,
      "message": "cart ready for checkout",
      "code": ""
    },
    "cartItemCount": 1,
    "mailInRebateTotal": 0,
    "mailInRebateDetails": null,
    "promoCodes": [
      null
    ],
    "promoCodeHeader": "Promo code? Lucky you.",
    "promoCodeLabel": "Promo code",
    "addAnotherPromoCodeText": "Add another promo code",
    "applyBtn": "Apply",
    "emptyCartMessage": "There are no items in your cart",
    "shopBtn": "Shop",
    "tradeInPromoEligible": true,
    "eligibleForSingleDeviceRibbon": false,
    "eligibleForMultiDeviceAllocation": false,
    "retrieveCartSuccessful": false,
    "standaloneAccessories": true,
    "dueTodayText": "Due today",
    "dueMonthlyText": "Due Monthly",
    "mainCartHeader": "Time to review your cart.",
    "mainCartSubTitle": "Enjoy free 2-day shipping.",
    "shopMoreBtnText": "Shop more",
    "checkoutBtn": "Check out",
    "editBtn": "Edit",
    "removeLinkText": "Remove",
    "mainCartFooterText": "Want to start over?",
    "mainCartFooterLinkText": "Emtpy your cart",
    "shopMoreLink": "/preorder/shoplanding/",
    "activationFeeText": "Activation Fee",
    "waivedActivationText": "Waived Activation Fee",
    "upgradeFeeText": "Upgrade Fee",
    "waivedUpgradeFeeText": "Waived Upgrade Fee",
    "saveBtnLabel": "Save",
    "zipCodeHeader": "Please enter a new ZIP code",
    "tradeInCreditHeader": "Trade-in Credit for this device",
    "tradeInFooterLink": "Tell me more",
    "tradeInOfferDetailsHeader": "Offer Details",
    "tradeInOfferDetailsMsg": "long block of text",
    "tradeInConfirmationBtn": "Got it",
    "lonelyCartMessage": "Your cart is lonely.",
    "checkoutButtonURL": "/preorder/checkout/initiateCheckout",
    "tradeInUrl": null,
    "mainInRebateDetails": null,
    "deviceProtectionDetails": {
      "deviceProtectionDetailsHeader": "device protection details",
      "deviceProtectionDetailsSubTitle": "Five things you need to know about Equipment Protection",
      "deviceProtectionDetailsText": "<div> <p>Cost per Month and Individual Service Availability. Total Mobile Protection (TMP) Single Device and Total Mobile Protection Multi-Device are a combination of multiple products, each of which is available separately per device: Wireless Phone Protection (WPP) $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; Verizon Wireless Extended Warranty (EW) $3.00; and Verizon Tech Coach $7.00. You may also purchase Total Equipment Coverage (TEC) for $7.00/Basic Devices &amp; Tablets or for $9.00/Smartphones &amp; iPhone Devices. TEC is a combination of 2 products, each of which is available separately: WPP $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; and Verizon Wireless EW for $3.00.</p> <p> Applicability and Amount of Deductible.  For lost, stolen and damaged device claims, deductibles are $49 for basic phones and, depending on device, $49-$199 for smartphones and tablets. For a full list of deductibles click here <a href='http://phoneclaim.com/verizon/deductible' target='_blank'>http://phoneclaim.com/verizon/deductible.</a> </p> <p>Claim Limits for loss, stolen and damaged devices. Equipment claim maximum is $400 or $1,500, depending on device, and limited to three claims per 12-month period for TMP Single Device and up to nine claims per 12-month period for TMP Multi-Device.</p> <p>Covered and Replacement Equipment. If your device is lost, stolen or damaged, your accessories are covered too ï¿1Ž2 one each of the following: standard battery, standard car charger, standard case, standard home charger and standard earbud. It is our goal to provide you with a replacement device that is the same color and has the same features, but this cannot be guaranteed. If the same make and model you claim is not available, a similar make and model will be substituted. Your replacement device could be new or refurbished. You may also receive generic accessories with lost, stolen or damaged claims.</p> <p>Cancellation Policy. Change your mind? You can cancel your coverage at any time and receive a pro-rated refund of your monthly fee.</p> </div>"
    },
    "preOrderAlertMsg": "Your order contains one or more items that are not in stock. All items will ship together when everything is available.",
    "bicText": null,
    "hasSubmittedTradein": false,
    "cpcSucessful": false,
    "cpcSucessfulNotification": false,
    "protectionURL": "/preorder/protection",
    "itemsFromRetrievedCart": false,
    "totalActivationFee": "0.00",
    "itemOnJaxPlan": false,
    "anyLineFreeSPO": null,
    "bicOfferMessage": null,
    "cartMFCompatible": false,
    "cartValidationDetailsVo": {
      "cartReadyforCheckout": true,
      "cartIncompleteCode": "",
      "cartIncompleteMessage": "cart ready for checkout",
      "orderId": "S54ba8f3e0cbb18fbf293e8ca320415e3{d4}"
    },
    "cartEdited": false,
    "iconicFlow": false,
    "plans": null,
    "removePromoCodeURL": null,
    "applyPromoCodeURL": null,
    "clearCartURL": null,
    "addOrUpdateDeviceURL": null,
    "addOrRemoveAccessoryURL": null,
    "changeZipCodeURL": null,
    "addOrUpdateFeatureURL": null,
    "initiateCheckoutURL": null,
    "accountMember": true,
    "splitShipment": false
  },
  "errorMap": null,
  "statusMessage": ""
};
export default cartJSON;
