
 const cartJSON ={
  "statusCode": "00",
  "output": {
    "tmpMdOpted": true,
    "orderId": "Sb8332bbad45908f215511ee7a2fbe7d0{d6}",
    "redirectionURL": null,
    "isPOBODeviceInCart": false,
    "dueTodayPOBOHeader": null,
    "items": [
      {
        "deviceProdId": "dev6640012",
        "deviceManufactureName": "Apple",
        "deviceProductDisplayName": "iPhone&reg; 7",
        "colorName": "Gold",
        "capacity": "128GB",
        "flow": "AAL",
        "mtn": null,
        "displayMtn": "518-603-XXXX",
        "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-med$&fmt=jpeg&wid=75&hei=150",
        "deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device$&bgc=ffffff&wid=158&hei=300",
        "activationFee": "30.00",
        "waivedActivationFeePromo": false,
        "upgradeFee": "0.00",
        "waivedUpgradeFeePromo": false,
        "edgeDevice": true,
        "price": "649.99",
        "priceText": "Full Retail Device Price",
        "priceSubTitle": null,
        "edgeItemDownPaymentAmount": "0.00",
        "installmentBalance": "0.00",
        "deviceEdgeUpAmount": "0.00",
        "deviceEdgeBuyOutAmount": "0.00",
        "protectionOption": {
          "name": "Total Mobile Protection Multi-Device",
          "price": "33.00",
          "featureType": "SPO",
          "featureSkuId": "sku2120289",
          "hideEditProtection": false,
          "displayMsg": null,
          "tapOpted": true
        },
        "commerceItemId": "Sb8332bbad45908f215511ee7a2fbe7d0{d6}_device_1",
        "deviceSkuId": "sku2150057",
        "deviceSORId": "MNAL2LL/A",
        "lacPrice": "65.00",
        "lacText": "SMARTPHONE line access",
        "inventoryStatus": "1000",
        "inventoryAvailableDate": null,
        "hasEcpdDiscount": true,
        "hasEcpdDiscountForDevicePayment": false,
        "devicePromotionList": [
          
        ],
        "bicOfferApplied": false,
        "bicContractPrice": 0,
        "bicDiscountedContractPrice": 0,
        "bicSavings": 0,
        "myOfferWaiveUpgradeFee": false,
        "shipCommitInd": null,
        "promoLACMessage": null,
        "additionalFeatures": [
          
        ],
        "bicMessage": null,
        "bicMessagetooltip": null,
        "editDeviceUrl": "/preorder/device/expressconfig/?commerceItemId=Sb8332bbad45908f215511ee7a2fbe7d0%7Bd6%7D_device_1&deviceProdId=dev6640012&deviceSkuId=sku2150057&editDevice=true&flow=AAL",
        "fullRetailPrice": "0.00",
        "fromSavedCart": false,
        "numberShareDevice": false,
        "numberSharedMtn": null,
        "itemOnJaxPlan": true,
        "humCarDetails": null,
        "monthlyPriceAfterDownPaymentBeforeDiscount": 0,
        "originalFullRetailPrice": 0,
        "hasReducedRetailPrice": false,
        "hasReducedDueMonthly": false,
        "originalDueMonthly": 0,
        "lineAccessPromotionText": null,
        "downPaymentPromotionText": null,
        "contractTerm": "0",
        "deviceType": null,
        "activationFeeText": null,
        "promoOfferText": null,
        "promoApplied": false,
        "portIn": false,
        "deviceNickName": "iPhone&reg; 7",
        "totalNumberShareExtension": 0,
        "sbdOffer": null,
        "hostCommerceItemId": null,
        "trunkMtn": null
      },
      {
        "deviceProdId": "dev6720118",
        "deviceManufactureName": "Google",
        "deviceProductDisplayName": "Pixel, Phone by Google",
        "colorName": "Really Blue",
        "capacity": "32GB",
        "flow": "AAL",
        "mtn": null,
        "displayMtn": "518-603-XXXX",
        "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Google_Sailfish_Blue?$device-med$&fmt=jpeg&wid=75&hei=150",
        "deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/Google_Sailfish_Blue?$device$&bgc=ffffff&wid=158&hei=300",
        "activationFee": "30.00",
        "waivedActivationFeePromo": false,
        "upgradeFee": "0.00",
        "waivedUpgradeFeePromo": false,
        "edgeDevice": true,
        "price": "549.99",
        "priceText": "Full Retail Device Price",
        "priceSubTitle": null,
        "edgeItemDownPaymentAmount": "0.00",
        "installmentBalance": "0.00",
        "deviceEdgeUpAmount": "0.00",
        "deviceEdgeBuyOutAmount": "0.00",
        "protectionOption": {
          "name": "Total Mobile Protection Multi-Device",
          "price": "42.00",
          "featureType": "SPO",
          "featureSkuId": "sku2120289",
          "hideEditProtection": false,
          "displayMsg": null,
          "tapOpted": true
        },
        "commerceItemId": "Sb8332bbad45908f215511ee7a2fbe7d0{d6}_device_2",
        "deviceSkuId": "sku2170525",
        "deviceSORId": "G-2PW4100-021-C",
        "lacPrice": "65.00",
        "lacText": "SMARTPHONE line access",
        "inventoryStatus": "1000",
        "inventoryAvailableDate": null,
        "hasEcpdDiscount": true,
        "hasEcpdDiscountForDevicePayment": false,
        "devicePromotionList": [
          
        ],
        "bicOfferApplied": false,
        "bicContractPrice": 0,
        "bicDiscountedContractPrice": 0,
        "bicSavings": 0,
        "myOfferWaiveUpgradeFee": false,
        "shipCommitInd": null,
        "promoLACMessage": null,
        "additionalFeatures": [
          
        ],
        "bicMessage": null,
        "bicMessagetooltip": null,
        "editDeviceUrl": "/preorder/device/expressconfig/?commerceItemId=Sb8332bbad45908f215511ee7a2fbe7d0%7Bd6%7D_device_2&deviceProdId=dev6720118&deviceSkuId=sku2170525&editDevice=true&flow=AAL",
        "fullRetailPrice": "0.00",
        "fromSavedCart": false,
        "numberShareDevice": false,
        "numberSharedMtn": null,
        "itemOnJaxPlan": true,
        "humCarDetails": null,
        "monthlyPriceAfterDownPaymentBeforeDiscount": 0,
        "originalFullRetailPrice": 0,
        "hasReducedRetailPrice": false,
        "hasReducedDueMonthly": false,
        "originalDueMonthly": 0,
        "lineAccessPromotionText": null,
        "downPaymentPromotionText": null,
        "contractTerm": "0",
        "deviceType": null,
        "activationFeeText": null,
        "promoOfferText": null,
        "promoApplied": false,
        "portIn": false,
        "deviceNickName": "Pixel, Phone by Google",
        "totalNumberShareExtension": 0,
        "sbdOffer": null,
        "hostCommerceItemId": null,
        "trunkMtn": null
      }
    ],
    "tmpMd": {
          "name": "Total Mobile Protection Multi-Device",
          "price": "33.00",
          "featureType": "SPO",
          "featureSkuId": "sku2120289",
          "hideEditProtection": false,
          "displayMsg": null,
          "tapOpted": true
        },
    "accessories": [
      
    ],
    "accessoriesBundle": null,
    "taxDetails": {
      "taxPrice": "88.50",
      "cityStateString": "Lake Park, MN",
      "stateTaxLabel": null,
      "zipCode": null
    },
    "totalDueToday": "1288.48",
    "totalDueMonthly": "11.00",
    "employeeDiscount": 0,
    "pastDueBalance": "0.00",
    "emptyCartFlag": false,
    "edgeContractDeviceInCart": true,
    "totalEdgeUpAmount": "0.00",
    "totalEdgeUpBuyOutAmount": "0.00",
    "totalEdgeOrderDownPayment": "0.00",
    "tradeInCredit": null,
    "tradeInPromoDetails": null,
    "promotionList": null,
    "cartMessages": {
      "cartReadyforCheckout": true,
      "message": "The device has been added with Full Retail Price as account is not eligible for Device Payment.",
      "code": null
    },
    "cartItemCount": 2,
    "mailInRebateTotal": 0,
    "mailInRebateDetails": null,
    "promoCodes": null,
    "promoCodeHeader": "Promo code? Lucky you.",
    "promoCodeLabel": "Promo code",
    "addAnotherPromoCodeText": "Add another promo code",
    "applyBtn": "Apply",
    "emptyCartMessage": "There are no items in your cart",
    "shopBtn": "Shop",
    "tradeInPromoEligible": true,
    "eligibleForSingleDeviceRibbon": false,
    "eligibleForMultiDeviceAllocation": false,
    "retrieveCartSuccessful": false,
    "standaloneAccessories": false,
    "dueTodayText": "Due today",
    "dueMonthlyText": "Due Monthly",
    "mainCartHeader": "Time to review your cart.",
    "mainCartSubTitle": "Enjoy free 2-day shipping.",
    "shopMoreBtnText": "Shop more",
    "checkoutBtn": "Check out",
    "editBtn": "Edit",
    "removeLinkText": "Remove",
    "mainCartFooterText": "Want to start over?",
    "mainCartFooterLinkText": "Emtpy your cart",
    "shopMoreLink": "/preorder/shoplanding/",
    "activationFeeText": "Activation Fee",
    "waivedActivationText": "Waived Activation Fee",
    "upgradeFeeText": "Upgrade Fee",
    "waivedUpgradeFeeText": "Waived Upgrade Fee",
    "saveBtnLabel": "Save",
    "zipCodeHeader": "Please enter a new ZIP code",
    "tradeInCreditHeader": "Trade-in Credit for this device",
    "tradeInFooterLink": "Tell me more",
    "tradeInOfferDetailsHeader": "Offer Details",
    "tradeInOfferDetailsMsg": "long block of text",
    "tradeInConfirmationBtn": "Got it",
    "lonelyCartMessage": "Your cart is lonely.",
    "checkoutButtonURL": "/preorder/checkout/initiateCheckout",
    "tradeInUrl": "/preorder/tradein/prompt?gotoCart=true",
    "mainInRebateDetails": null,
    "deviceProtectionDetails": {
      "deviceProtectionDetailsHeader": "device protection details",
      "deviceProtectionDetailsSubTitle": "Five things you need to know about Equipment Protection",
      "deviceProtectionDetailsText": "<div> <p>Cost per Month and Individual Service Availability. Total Mobile Protection (TMP) Single Device and Total Mobile Protection Multi-Device are a combination of multiple products, each of which is available separately per device: Wireless Phone Protection (WPP) $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; Verizon Wireless Extended Warranty (EW) $3.00; and Verizon Tech Coach $7.00. You may also purchase Total Equipment Coverage (TEC) for $7.00/Basic Devices &amp; Tablets or for $9.00/Smartphones &amp; iPhone Devices. TEC is a combination of 2 products, each of which is available separately: WPP $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; and Verizon Wireless EW for $3.00.</p> <p> Applicability and Amount of Deductible.  For lost, stolen and damaged device claims, deductibles are $49 for basic phones and, depending on device, $49-$199 for smartphones and tablets. For a full list of deductibles click here <a href='http://phoneclaim.com/verizon/deductible' target='_blank'>http://phoneclaim.com/verizon/deductible.</a> </p> <p>Claim Limits for loss, stolen and damaged devices. Equipment claim maximum is $400 or $1,500, depending on device, and limited to three claims per 12-month period for TMP Single Device and up to nine claims per 12-month period for TMP Multi-Device.</p> <p>Covered and Replacement Equipment. If your device is lost, stolen or damaged, your accessories are covered too ï¿1Ž2 one each of the following: standard battery, standard car charger, standard case, standard home charger and standard earbud. It is our goal to provide you with a replacement device that is the same color and has the same features, but this cannot be guaranteed. If the same make and model you claim is not available, a similar make and model will be substituted. Your replacement device could be new or refurbished. You may also receive generic accessories with lost, stolen or damaged claims.</p> <p>Cancellation Policy. Change your mind? You can cancel your coverage at any time and receive a pro-rated refund of your monthly fee.</p> </div>"
    },
    "preOrderAlertMsg": "Your order contains one or more items that are not in stock. All items will ship together when everything is available.",
    "bicText": null,
    "hasSubmittedTradein": false,
    "cpcSucessful": false,
    "cpcSucessfulNotification": false,
    "protectionURL": "/preorder/protection",
    "itemsFromRetrievedCart": false,
    "totalActivationFee": "60.00",
    "itemOnJaxPlan": true,
    "anyLineFreeSPO": null,
    "bicOfferMessage": null,
    "cartMFCompatible": false,
    "cartValidationDetailsVo": {
      "cartReadyforCheckout": true,
      "cartIncompleteCode": null,
      "cartIncompleteMessage": null,
      "orderId": "Sb8332bbad45908f215511ee7a2fbe7d0{d6}"
    },
    "cartEdited": false,
    "iconicFlow": false,
    "plans": {
      "planOnlyDueMonthly": "255.00",
      "dueMonthly": "255.00",
      "dueToday": "0.00",
      "items": [
        {
          "planType": "Beyond Unlimited",
          "planSorId": "99231",
          "planProdId": "plan2880001",
          "planSkuId": "sku2580029",
          "planLetter": null,
          "planDescription": "",
          "planDisplayName": "Beyond Unlimited",
          "planChangeURL": null,
          "planImageURL": null,
          "accountAccess": {
            "name": "Beyond Unlimited",
            "price": "255.00",
            "discountPrice": 0,
            "promoMessage": null,
            "hasEcpdDiscount": false,
            "planAmount": "255.00"
          }
        }
      ]
    },
    "removePromoCodeURL": "/preorder/cart/removePromoCode",
    "applyPromoCodeURL": "/preorder/cart/applyPromoCode",
    "clearCartURL": "/preorder/cart/clearCart",
    "addOrUpdateDeviceURL": "/preorder/cart/addOrUpdateDevice",
    "addOrRemoveAccessoryURL": "/preorder/cart/addOrRemoveAccessory",
    "changeZipCodeURL": "/preordercart/changeZipCode/",
    "addOrUpdateFeatureURL": "/preorder/cart/addOrUpdateFeature",
    "initiateCheckoutURL": "/preorder/checkout/initiateCheckout",
    "accountMember": true,
    "splitShipment": false
  },
  "errorMap": null,
  "statusMessage": ""
};
/*{
  "statusCode": "00",
  "output": {
    "tmpMdOpted" : true,
    "orderId": "Sb8332bbad45908f215511ee7a2fbe7d0{d6}",
    "redirectionURL": null,
    "isPOBODeviceInCart": false,
    "dueTodayPOBOHeader": null,
    "items": [
      {
        "deviceProdId": "dev6640012",
        "deviceManufactureName": "Apple",
        "deviceProductDisplayName": "iPhone&reg; 7",
        "colorName": "Gold",
        "capacity": "128GB",
        "flow": "AAL",
        "mtn": null,
        "displayMtn": "518-603-XXXX",
        "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-med$&fmt=jpeg&wid=75&hei=150",
        "deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device$&bgc=ffffff&wid=158&hei=300",
        "activationFee": "30.00",
        "waivedActivationFeePromo": false,
        "upgradeFee": "0.00",
        "waivedUpgradeFeePromo": false,
        "edgeDevice": true,
        "price": "649.99",
        "priceText": "Full Retail Device Price",
        "priceSubTitle": null,
        "edgeItemDownPaymentAmount": "0.00",
        "installmentBalance": "0.00",
        "deviceEdgeUpAmount": "0.00",
        "deviceEdgeBuyOutAmount": "0.00",
        "protectionOption": {
          "name": "Total Mobile Protection Multi-Device",
          "price": "33.00",
          "featureType": "SPO",
          "featureSkuId": "sku2120289",
          "hideEditProtection": false,
          "displayMsg": null,
          "tapOpted": true
        },
        "commerceItemId": "Sb8332bbad45908f215511ee7a2fbe7d0{d6}_device_1",
        "deviceSkuId": "sku2150057",
        "deviceSORId": "MNAL2LL/A",
        "lacPrice": "65.00",
        "lacText": "SMARTPHONE line access",
        "inventoryStatus": "1000",
        "inventoryAvailableDate": null,
        "hasEcpdDiscount": true,
        "hasEcpdDiscountForDevicePayment": false,
        "devicePromotionList": [],
        "bicOfferApplied": false,
        "bicContractPrice": 0,
        "bicDiscountedContractPrice": 0,
        "bicSavings": 0,
        "myOfferWaiveUpgradeFee": false,
        "shipCommitInd": null,
        "promoLACMessage": null,
        "additionalFeatures": [],
        "bicMessage": null,
        "bicMessagetooltip": null,
        "editDeviceUrl": "/preorder/device/expressconfig/?commerceItemId=Sb8332bbad45908f215511ee7a2fbe7d0%7Bd6%7D_device_1&deviceProdId=dev6640012&deviceSkuId=sku2150057&editDevice=true&flow=AAL",
        "fullRetailPrice": "0.00",
        "fromSavedCart": false,
        "numberShareDevice": false,
        "numberSharedMtn": null,
        "itemOnJaxPlan": true,
        "humCarDetails": null,
        "monthlyPriceAfterDownPaymentBeforeDiscount": 0,
        "originalFullRetailPrice": 0,
        "hasReducedRetailPrice": false,
        "hasReducedDueMonthly": false,
        "originalDueMonthly": 0,
        "lineAccessPromotionText": null,
        "downPaymentPromotionText": null,
        "contractTerm": "0",
        "deviceType": null,
        "activationFeeText": null,
        "promoOfferText": null,
        "promoApplied": false,
        "portIn": false,
        "deviceNickName": "iPhone&reg; 7",
        "totalNumberShareExtension": 0,
        "sbdOffer": null,
        "hostCommerceItemId": null,
        "trunkMtn": null
      },
      {
        "deviceProdId": "dev6720118",
        "deviceManufactureName": "Google",
        "deviceProductDisplayName": "Pixel, Phone by Google",
        "colorName": "Really Blue",
        "capacity": "32GB",
        "flow": "AAL",
        "mtn": null,
        "displayMtn": "518-603-XXXX",
        "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/Google_Sailfish_Blue?$device-med$&fmt=jpeg&wid=75&hei=150",
        "deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/Google_Sailfish_Blue?$device$&bgc=ffffff&wid=158&hei=300",
        "activationFee": "30.00",
        "waivedActivationFeePromo": false,
        "upgradeFee": "0.00",
        "waivedUpgradeFeePromo": false,
        "edgeDevice": true,
        "price": "549.99",
        "priceText": "Full Retail Device Price",
        "priceSubTitle": null,
        "edgeItemDownPaymentAmount": "0.00",
        "installmentBalance": "0.00",
        "deviceEdgeUpAmount": "0.00",
        "deviceEdgeBuyOutAmount": "0.00",
        "protectionOption": {
          "name": "Total Mobile Protection Multi-Device",
          "price": "42.00",
          "featureType": "SPO",
          "featureSkuId": "sku2120289",
          "hideEditProtection": false,
          "displayMsg": null,
          "tapOpted": true
        },
        "commerceItemId": "Sb8332bbad45908f215511ee7a2fbe7d0{d6}_device_2",
        "deviceSkuId": "sku2170525",
        "deviceSORId": "G-2PW4100-021-C",
        "lacPrice": "65.00",
        "lacText": "SMARTPHONE line access",
        "inventoryStatus": "1000",
        "inventoryAvailableDate": null,
        "hasEcpdDiscount": true,
        "hasEcpdDiscountForDevicePayment": false,
        "devicePromotionList": [],
        "bicOfferApplied": false,
        "bicContractPrice": 0,
        "bicDiscountedContractPrice": 0,
        "bicSavings": 0,
        "myOfferWaiveUpgradeFee": false,
        "shipCommitInd": null,
        "promoLACMessage": null,
        "additionalFeatures": [],
        "bicMessage": null,
        "bicMessagetooltip": null,
        "editDeviceUrl": "/preorder/device/expressconfig/?commerceItemId=Sb8332bbad45908f215511ee7a2fbe7d0%7Bd6%7D_device_2&deviceProdId=dev6720118&deviceSkuId=sku2170525&editDevice=true&flow=AAL",
        "fullRetailPrice": "0.00",
        "fromSavedCart": false,
        "numberShareDevice": false,
        "numberSharedMtn": null,
        "itemOnJaxPlan": true,
        "humCarDetails": null,
        "monthlyPriceAfterDownPaymentBeforeDiscount": 0,
        "originalFullRetailPrice": 0,
        "hasReducedRetailPrice": false,
        "hasReducedDueMonthly": false,
        "originalDueMonthly": 0,
        "lineAccessPromotionText": null,
        "downPaymentPromotionText": null,
        "contractTerm": "0",
        "deviceType": null,
        "activationFeeText": null,
        "promoOfferText": null,
        "promoApplied": false,
        "portIn": false,
        "deviceNickName": "Pixel, Phone by Google",
        "totalNumberShareExtension": 0,
        "sbdOffer": null,
        "hostCommerceItemId": null,
        "trunkMtn": null
      }
    ],
    "accessories": [],
    "accessoriesBundle": null,
    "taxDetails": {
      "taxPrice": "88.50",
      "cityStateString": "Lake Park, MN",
      "stateTaxLabel": null,
      "zipCode": null
    },
    "totalDueToday": "1288.48",
    "totalDueMonthly": "11.00",
    "employeeDiscount": 0,
    "pastDueBalance": "0.00",
    "emptyCartFlag": false,
    "edgeContractDeviceInCart": true,
    "totalEdgeUpAmount": "0.00",
    "totalEdgeUpBuyOutAmount": "0.00",
    "totalEdgeOrderDownPayment": "0.00",
    "tradeInCredit": null,
    "tradeInPromoDetails": null,
    "promotionList": null,
    "cartMessages": {
      "cartReadyforCheckout": true,
      "message": "The device has been added with Full Retail Price as account is not eligible for Device Payment.",
      "code": null
    },
    "cartItemCount": 2,
    "mailInRebateTotal": 0,
    "mailInRebateDetails": null,
    "promoCodes": null,
    "promoCodeHeader": "Promo code? Lucky you.",
    "promoCodeLabel": "Promo code",
    "addAnotherPromoCodeText": "Add another promo code",
    "applyBtn": "Apply",
    "emptyCartMessage": "There are no items in your cart",
    "shopBtn": "Shop",
    "tradeInPromoEligible": true,
    "eligibleForSingleDeviceRibbon": false,
    "eligibleForMultiDeviceAllocation": false,
    "retrieveCartSuccessful": false,
    "standaloneAccessories": false,
    "dueTodayText": "Due today",
    "dueMonthlyText": "Due Monthly",
    "mainCartHeader": "Time to review your cart.",
    "mainCartSubTitle": "Enjoy free 2-day shipping.",
    "shopMoreBtnText": "Shop more",
    "checkoutBtn": "Check out",
    "editBtn": "Edit",
    "removeLinkText": "Remove",
    "mainCartFooterText": "Want to start over?",
    "mainCartFooterLinkText": "Emtpy your cart",
    "shopMoreLink": "/preorder/shoplanding/",
    "activationFeeText": "Activation Fee",
    "waivedActivationText": "Waived Activation Fee",
    "upgradeFeeText": "Upgrade Fee",
    "waivedUpgradeFeeText": "Waived Upgrade Fee",
    "saveBtnLabel": "Save",
    "zipCodeHeader": "Please enter a new ZIP code",
    "tradeInCreditHeader": "Trade-in Credit for this device",
    "tradeInFooterLink": "Tell me more",
    "tradeInOfferDetailsHeader": "Offer Details",
    "tradeInOfferDetailsMsg": "long block of text",
    "tradeInConfirmationBtn": "Got it",
    "lonelyCartMessage": "Your cart is lonely.",
    "checkoutButtonURL": "/preorder/checkout/initiateCheckout",
    "tradeInUrl": "/preorder/tradein/prompt?gotoCart=true",
    "mainInRebateDetails": null,
    "deviceProtectionDetails": {
      "deviceProtectionDetailsHeader": "device protection details",
      "deviceProtectionDetailsSubTitle": "Five things you need to know about Equipment Protection",
      "deviceProtectionDetailsText": "<div> <p>Cost per Month and Individual Service Availability. Total Mobile Protection (TMP) Single Device and Total Mobile Protection Multi-Device are a combination of multiple products, each of which is available separately per device: Wireless Phone Protection (WPP) $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; Verizon Wireless Extended Warranty (EW) $3.00; and Verizon Tech Coach $7.00. You may also purchase Total Equipment Coverage (TEC) for $7.00/Basic Devices &amp; Tablets or for $9.00/Smartphones &amp; iPhone Devices. TEC is a combination of 2 products, each of which is available separately: WPP $5.00/Basic Devices &amp; Tablets or for $7.15/Smartphones &amp; iPhone Devices; and Verizon Wireless EW for $3.00.</p> <p> Applicability and Amount of Deductible.  For lost, stolen and damaged device claims, deductibles are $49 for basic phones and, depending on device, $49-$199 for smartphones and tablets. For a full list of deductibles click here <a href='http://phoneclaim.com/verizon/deductible' target='_blank'>http://phoneclaim.com/verizon/deductible.</a> </p> <p>Claim Limits for loss, stolen and damaged devices. Equipment claim maximum is $400 or $1,500, depending on device, and limited to three claims per 12-month period for TMP Single Device and up to nine claims per 12-month period for TMP Multi-Device.</p> <p>Covered and Replacement Equipment. If your device is lost, stolen or damaged, your accessories are covered too ï¿1Ž2 one each of the following: standard battery, standard car charger, standard case, standard home charger and standard earbud. It is our goal to provide you with a replacement device that is the same color and has the same features, but this cannot be guaranteed. If the same make and model you claim is not available, a similar make and model will be substituted. Your replacement device could be new or refurbished. You may also receive generic accessories with lost, stolen or damaged claims.</p> <p>Cancellation Policy. Change your mind? You can cancel your coverage at any time and receive a pro-rated refund of your monthly fee.</p> </div>"
    },
    "preOrderAlertMsg": "Your order contains one or more items that are not in stock. All items will ship together when everything is available.",
    "bicText": null,
    "hasSubmittedTradein": false,
    "cpcSucessful": false,
    "cpcSucessfulNotification": false,
    "protectionURL": "/preorder/protection",
    "itemsFromRetrievedCart": false,
    "totalActivationFee": "60.00",
    "itemOnJaxPlan": true,
    "anyLineFreeSPO": null,
    "bicOfferMessage": null,
    "cartMFCompatible": false,
    "cartValidationDetailsVo": {
      "cartReadyforCheckout": true,
      "cartIncompleteCode": null,
      "cartIncompleteMessage": null,
      "orderId": "Sb8332bbad45908f215511ee7a2fbe7d0{d6}"
    },
    "cartEdited": false,
    "iconicFlow": false,
    "plans": {
      "planOnlyDueMonthly": "255.00",
      "dueMonthly": "255.00",
      "dueToday": "0.00",
      "items": [
        {
          "planType": "Beyond Unlimited",
          "planSorId": "99231",
          "planProdId": "plan2880001",
          "planSkuId": "sku2580029",
          "planLetter": null,
          "planDescription": "",
          "planDisplayName": "Beyond Unlimited",
          "planChangeURL": null,
          "planImageURL": null,
          "accountAccess": {
            "name": "Beyond Unlimited",
            "price": "255.00",
            "discountPrice": 0,
            "promoMessage": null,
            "hasEcpdDiscount": false,
            "planAmount": "255.00"
          }
        }
      ]
    },
    "removePromoCodeURL": "/preorder/cart/removePromoCode",
    "applyPromoCodeURL": "/preorder/cart/applyPromoCode",
    "clearCartURL": "/preorder/cart/clearCart",
    "addOrUpdateDeviceURL": "/preorder/cart/addOrUpdateDevice",
    "addOrRemoveAccessoryURL": "/preorder/cart/addOrRemoveAccessory",
    "changeZipCodeURL": "/preordercart/changeZipCode/",
    "addOrUpdateFeatureURL": "/preorder/cart/addOrUpdateFeature",
    "initiateCheckoutURL": "/preorder/checkout/initiateCheckout",
    "accountMember": true,
    "splitShipment": false
  },
  "errorMap": null,
  "statusMessage": ""
};*/

 export default cartJSON;
