const reviewOrderJSON = {
  "statusCode": "00",
  "output": {
    "orderId": "SDC08e4f6939570593db04ac7d88b151d3c{ss2}",
    "redirectionURL": null,
    "isPOBODeviceInCart": false,
    "dueTodayPOBOHeader": null,
    "items": [
      {
        "deviceProdId": "dev5160002",
        "deviceManufactureName": "Apple",
        "deviceProductDisplayName": "iPhone&reg; 6s",
        "colorName": "Space Gray",
        "capacity": "32GB",
        "flow": "EUP",
        "mtn": "7656203802",
        "displayMtn": "765.620.3802",
        "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone6s-spgry-front?$device-med$&fmt=jpeg&wid=75&hei=150",
        "deviceImageUrlLarge": "https://ss7.vzw.com/is/image/VerizonWireless/iphone6s-spgry-front?$device$&bgc=ffffff&wid=158&hei=300",
        "activationFee": "0.00",
        "waivedActivationFeePromo": false,
        "upgradeFee": "30.00",
        "waivedUpgradeFeePromo": false,
        "edgeDevice": true,
        "price": "449.99",
        "originalPrice": "449.99",
        "priceText": "Full Retail Device Price",
        "priceSubTitle": null,
        "edgeItemDownPaymentAmount": "0.00",
        "installmentBalance": "0.00",
        "deviceEdgeUpAmount": "0.00",
        "deviceEdgeBuyOutAmount": "0.00",
        "protectionOption": {
          "name": "Total Equipment Coverage",
          "price": "9.00",
          "featureType": "INS",
          "featureSkuId": "sku1230437",
          "hideEditProtection": false,
          "displayMsg": null,
          "tapOpted": false
        },
        "commerceItemId": "SDC08e4f6939570593db04ac7d88b151d3c{ss2}_device_1",
        "deviceSkuId": "sku2160047",
        "deviceSORId": "MN1M2LL/A",
        "lacPrice": "85.00",
        "lacText": "SMARTPHONE line access",
        "inventoryStatus": "1000",
        "inventoryAvailableDate": null,
        "hasEcpdDiscount": false,
        "hasEcpdDiscountForDevicePayment": false,
        "devicePromotionList": [],
        "bicOfferApplied": false,
        "bicContractPrice": 0,
        "bicDiscountedContractPrice": 0,
        "bicSavings": 0,
        "myOfferWaiveUpgradeFee": false,
        "shipCommitInd": null,
        "promoLACMessage": null,
        "additionalFeatures": [],
        "bicMessage": null,
        "bicMessagetooltip": null,
        "editDeviceUrl": "/od/cust/auth/device/expressconfig/?commerceItemId=SDC08e4f6939570593db04ac7d88b151d3c%7Bss2%7D_device_1&deviceProdId=dev5160002&deviceSkuId=sku2160047&editDevice=true&flow=EUP",
        "fullRetailPrice": "0.00",
        "fromSavedCart": false,
        "numberShareDevice": false,
        "numberSharedMtn": null,
        "itemOnJaxPlan": true,
        "humCarDetails": null,
        "monthlyPriceAfterDownPaymentBeforeDiscount": 0,
        "originalFullRetailPrice": 0,
        "hasReducedRetailPrice": false,
        "hasReducedDueMonthly": false,
        "originalDueMonthly": 0,
        "lineAccessPromotionText": null,
        "downPaymentPromotionText": null,
        "contractTerm": "0",
        "deviceType": null,
        "activationFeeText": null,
        "promoOfferText": null,
        "promoApplied": false,
        "portIn": false,
        "deviceNickName": "MATT                  JETER-3802",
        "totalNumberShareExtension": 0,
        "sbdOffer": {
          "sbdHeaderMsg": null,
          "sbdPromoMsg": null,
          "sbdDiscountAmount": 0,
          "sbdItemMonthlyAmount": 0,
          "itemRetailPrice": 0,
          "itemMonthlyPrice": 0,
          "itemStrikeThroughPrice": 0,
          "noOfBicOccurences": 0
        },
        "hostCommerceItemId": null,
        "trunkMtn": null
      }
    ],
    "accessories": [],
    "accessoriesBundle": null,
    "taxDetails": {
      "taxPrice": "33.60",
      "cityStateString": "Anderson, IN",
      "stateTaxLabel": null,
      "zipCode": null
    },
    "totalDueToday": "513.59",
    "totalDueMonthly": "9.00",
    "employeeDiscount": 0,
    "pastDueBalance": "0.00",
    "emptyCartFlag": false,
    "edgeContractDeviceInCart": true,
    "totalEdgeUpAmount": "0.00",
    "totalEdgeUpBuyOutAmount": "0.00",
    "totalEdgeOrderDownPayment": "0.00",
    "tradeInCredit": "-1.00",
    "tradeInPromoDetails": {
      "tradeInDeviceDppMsg": "Once you upgrade, we'll send a prepaid shipping box so you can mail your trade-in.",
      "warningMessage": null,
      "tradeInDeviceHeaderMsg": "You'll see an estimated $1.00 credit with 1-2 bill cycles.",
      "tradeInCredit": "-1.00",
      "tradeInDevices": [
        {
          "activeDevice": null,
          "tradeInCredit": "1.00",
          "tradeInDeviceFooter": null,
          "offerDetailsMsg": null,
          "tradeInDeviceHeaderMsg": null,
          "tradeInCreditMsg": "Trade-in credit: $1.00",
          "bicApplied": null,
          "color": "Silver",
          "dataWipeText": null,
          "deviceBrand": null,
          "deviceId": "ID: 00618160743071",
          "discAmt": null,
          "disconnectedDate": null,
          "displayName": "Gusto 2",
          "dppCredit": "0.0",
          "dppAppliedCommerceItemId": null,
          "dppAppliedMdn": null,
          "errorMessage": null,
          "modalOsName": null,
          "modelImage": "https://ss7.vzw.com/is/image/VerizonWireless/SamsungGusto2?$device-lg$",
          "modelName": null,
          "mtn": null,
          "nickName": null,
          "originalAppraisalPrice": "1.00",
          "price": null,
          "promoCodeError": null,
          "promoCreditType": null,
          "promoQualifyMessage": null,
          "promoValue": null,
          "shortDisplayName": null,
          "size": "128MB",
          "success": true
        }
      ]
    },
    "promotionList": [],
    "cartMessages": {
      "cartReadyforCheckout": true,
      "message": "The line you are attempting to upgrade is associated with Monthly Device Payment Agreement. If you continue, please note that you will be responsible for the remaining balance of your Verizon Monthly Device Payment installment agreement.",
      "code": null
    },
    "cartItemCount": 1,
    "mailInRebateTotal": 0,
    "mailInRebateDetails": null,
    "promoCodes": [],
    "promoCodeHeader": "Promo Code? Lucky you.",
    "promoCodeLabel": "Promo code",
    "addAnotherPromoCodeText": "Add another promo code",
    "applyBtn": "Apply",
    "emptyCartMessage": "There are no items in your cart",
    "shopBtn": "Shop",
    "tradeInPromoEligible": true,
    "eligibleForSingleDeviceRibbon": false,
    "eligibleForMultiDeviceAllocation": false,
    "retrieveCartSuccessful": false,
    "standaloneAccessories": false,
    "dueTodayText": "Due today",
    "dueMonthlyText": "Due monthly",
    "mainCartHeader": "Time to review your cart.",
    "mainCartSubTitle": "Enjoy free 2-day shipping.",
    "shopMoreBtnText": "Shop more",
    "checkoutBtn": "Check out",
    "editBtn": "Edit",
    "removeLinkText": "Remove",
    "mainCartFooterText": "Want to start over?",
    "mainCartFooterLinkText": "Empty your cart",
    "shopMoreLink": "/od/cust/auth/shoplanding/",
    "activationFeeText": "Activation Fee",
    "waivedActivationText": "Waived Activation Fee",
    "upgradeFeeText": "Upgrade Fee",
    "waivedUpgradeFeeText": "Waived Upgrade Fee",
    "saveBtnLabel": "Save",
    "zipCodeHeader": "Please enter a new ZIP code.",
    "tradeInCreditHeader": "Trade in credit for this device",
    "tradeInFooterLink": "Tell me more",
    "tradeInOfferDetailsHeader": "Offer Details",
    "tradeInOfferDetailsMsg": "long block of text",
    "tradeInConfirmationBtn": "Got it",
    "lonelyCartMessage": "Your cart is lonely",
    "checkoutButtonURL": "/od/cust/auth/checkout/initiateCheckout",
    "tradeInUrl": "/od/trade-in/auth?gotoCart=true",
    "mainInRebateDetails": null,
    "deviceProtectionDetails": {
      "deviceProtectionDetailsHeader": "device protection details",
      "deviceProtectionDetailsSubTitle": "Five things you need to know about Equipment Protection",
      "deviceProtectionDetailsText": "Text Shoud come here"
    },
    "preOrderAlertMsg": "One or more items is on pre order. All items will ship together when everything is available",
    "bicText": null,
    "hasSubmittedTradein": false,
    "cpcSucessful": false,
    "cpcSucessfulNotification": false,
    "protectionURL": "/od/cust/auth/protection",
    "itemsFromRetrievedCart": false,
    "totalActivationFee": "0.00",
    "itemOnJaxPlan": true,
    "anyLineFreeSPO": null,
    "bicOfferMessage": null,
    "cartMFCompatible": false,
    "cartValidationDetailsVo": {
      "cartReadyforCheckout": true,
      "cartIncompleteCode": null,
      "cartIncompleteMessage": null,
      "orderId": "SDC08e4f6939570593db04ac7d88b151d3c{ss2}"
    },
    "cartEdited": false,
    "iconicFlow": false,
    "plans": {
      "planOnlyDueMonthly": "170.00",
      "dueMonthly": "170.00",
      "dueToday": "0.00",
      "items": [
        {
          "planType": "Beyond Unlimited",
          "planSorId": "99231",
          "planProdId": "plan2880001",
          "planSkuId": "sku2580029",
          "planLetter": null,
          "planDescription": "",
          "planDisplayName": "Beyond Unlimited",
          "planChangeURL": null,
          "planImageURL": null,
          "accountAccess": {
            "name": "Beyond Unlimited",
            "price": "170.00",
            "discountPrice": 0,
            "promoMessage": null,
            "hasEcpdDiscount": false,
            "planAmount": "170.00"
          }
        }
      ]
    },
    "removePromoCodeURL": "/od/cust/auth/cart/removePromoCode",
    "applyPromoCodeURL": "/od/cust/auth/cart/applyPromoCode",
    "clearCartURL": "/od/cust/auth/cart/clearCart",
    "addOrUpdateDeviceURL": "/od/cust/auth/cart/addOrUpdateDevice",
    "addOrRemoveAccessoryURL": "/od/cust/auth/cart/addOrRemoveAccessory",
    "changeZipCodeURL": "/od/cust/authcart/changeZipCode/",
    "addOrUpdateFeatureURL": "/od/cust/auth/cart/addOrUpdateFeature",
    "initiateCheckoutURL": "/od/cust/auth/checkout/initiateCheckout",
    "accountMember": false,
    "tmpMdOpted": false,
    "tmpMd": null,
    "splitShipment": false,
    "authenticated": true
  },
  "errorMap": null,
  "statusMessage": ""
};
export default reviewOrderJSON;
