export const ASYNC_FETCH = 'byod/ASYNC_FETCH';
export const ASYNC_FETCH_SUCCESS = 'byod/ASYNC_FETCH_SUCCESS';
export const ASYNC_FETCH_FAILURE = 'byod/ASYNC_FETCH_FAILURE';
export const ASYNC_FETCH_CLEAR = 'byod/ASYNC_FETCH_CLEAR';
export const SELECTED_DEVICE_TYPE = 'byod/SELECTED_DEVICE_TYPE';
export const SELECTED_IMEI = 'byod/SELECTED_IMEI';
export const VALIDATE_IMEI_RESPONSE = 'byod/VALIDATE_IMEI_RESPONSE';
export const SEARCH_RESULTS = 'byod/SEARCH_RESULTS';
export const SEARCH_RESULTS_LINK = 'byod/SEARCH_RESULTS_LINK';
export const SEARCH_RESULTS_INPUT = 'byod/SEARCH_RESULTS_INPUT';
export const SEARCH_RESULTS_BRAND = 'byod/SEARCH_RESULTS_BRAND';
export const INPUT_VAL = 'byod/INPUT_VAL';

