const deviceConfigJson = {
  statusCode: '00',
  errorMap: null,
  output: {
    productDetails: {
      badgeRetailIconImageName: null,
      manufacturerDisplayName: 'Apple',
      badgeTwoYearToolTip: null,
      lineAccess: null,
      dealInStoreStaticUrl: 'https://forms.verizonwireless.com/dgf/optin/2012/06282012_omni_thankyou/index.html',
      cqContent: null,
      badgeEdgeIconImageName: 'https://ss7.vzw.com/is/image/VerizonWireless/special-offer',
      brandName: 'Apple',
      categoryName: 'smartphones',
      rectangularBadgeText: null,
      badgeTwoYearIconImageName: null,
      badgeRetailDisplayName: null,
      deviceType: '4G Smartphone',
      badgeEdgeToolTip: 'Device payment purchase required for iPhone. 2-yr activation required for iPad. $200 instant savings off the retail price of the iPad.',
      skuDetails: [{
        colorName: 'Silver',
        imageUrl: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-svr?$device-lg$',
        upgradeOptionEllPDPLbl50: '\n            ',
        promotionDetails: null,
        restrictionFlag: false,
        upgradeOptionEllPDPLbl70: '\n            ',
        devicePrice: [{
          mailInRebateAmount: 0.0,
          priceListId: 'edgeRemainingMonthPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 969.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: true,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 40.41,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: '/mo.',
          contractPrice: '40.41',
          contractTerm: 99,
          originalPrice: 40.41,
          creditOptionVOList: null,
          fullRetailPrice: 969.99,
          waivedUpgradeFeePromo: false,
          contractTitle: '$0 Down (for qualified customers) $40.41/mo for 24 months; 0% APR Retail Price: $969.99',
          contractName: '24 Monthly Payments',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }, {
          mailInRebateAmount: 0.0,
          priceListId: 'fullRetailPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 969.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: false,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 969.99,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: null,
          contractPrice: '969.99',
          contractTerm: 0,
          originalPrice: 969.99,
          creditOptionVOList: null,
          fullRetailPrice: 969.99,
          waivedUpgradeFeePromo: false,
          contractTitle: 'No Early Termination Fee',
          contractName: 'Retail Price',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }],
        skuImageName: 'iphone7-plus-front-svr',
        upgradeOptionEllPDPTip70: '\n            ',
        selected: false,
        upgradeOptionEllPDPTip50: '\n            ',
        restrictionMessage: null,
        sameDayDeliveryFlag: true,
        capacity: '256GB',
        inventoryStatus: 1001,
        deviceSkuId: 'sku2150078',
        devicePaymentPercentage: '50',
        deviceSorId: 'MN602LL/A',
        skuListDiscountPricing: {
          skuListPrice: [{
            priceListId: 'edgeFullRetailPriceListId',
            price: 969.99,
          }, {
            priceListId: 'twoYearPriceListId',
            price: 519.99,
          }, {
            priceListId: 'edgeFirstMonthPriceListId',
            price: 40.56,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 969.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 40.41,
          }],
          skuDiscountPrice: [{
            priceListId: 'twoYearPriceListId',
            price: 519.99,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 969.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 40.41,
          }],
        },
        colorImage: null,
        upgradeOptionCode: 'UO',
        annualUpgradeEligible: true,
        displayName: 'Apple&reg; iPhone&reg; 7 Plus 256GB in Silver',
        colorCode: '#d7d7d7',
        mobileAppImageName: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-svr?$device-lg$',
        shippingDateLabel: null,
        shippingDateStatusCode: 1001,
      }, {
        colorName: 'Apple Black',
        imageUrl: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-matblk?$device-lg$',
        upgradeOptionEllPDPLbl50: '\n            ',
        promotionDetails: null,
        restrictionFlag: false,
        upgradeOptionEllPDPLbl70: '\n            ',
        devicePrice: [{
          mailInRebateAmount: 0.0,
          priceListId: 'edgeRemainingMonthPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 769.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: true,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 32.08,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: '/mo.',
          contractPrice: '32.08',
          contractTerm: 99,
          originalPrice: 32.08,
          creditOptionVOList: null,
          fullRetailPrice: 769.99,
          waivedUpgradeFeePromo: false,
          contractTitle: '$0 Down (for qualified customers) $32.08/mo for 24 months; 0% APR Retail Price: $769.99',
          contractName: '24 Monthly Payments',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }, {
          mailInRebateAmount: 0.0,
          priceListId: 'fullRetailPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 769.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: false,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 769.99,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: null,
          contractPrice: '769.99',
          contractTerm: 0,
          originalPrice: 769.99,
          creditOptionVOList: null,
          fullRetailPrice: 769.99,
          waivedUpgradeFeePromo: false,
          contractTitle: 'No Early Termination Fee',
          contractName: 'Retail Price',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }],
        skuImageName: 'iphone7-plus-front-matblk',
        upgradeOptionEllPDPTip70: '\n            ',
        selected: true,
        upgradeOptionEllPDPTip50: '\n            ',
        restrictionMessage: null,
        sameDayDeliveryFlag: true,
        capacity: '32GB',
        inventoryStatus: 1000,
        deviceSkuId: 'sku2150070',
        devicePaymentPercentage: '50',
        deviceSorId: 'MNR12LL/A',
        skuListDiscountPricing: {
          skuListPrice: [{
            priceListId: 'edgeFullRetailPriceListId',
            price: 769.99,
          }, {
            priceListId: 'twoYearPriceListId',
            price: 319.99,
          }, {
            priceListId: 'edgeFirstMonthPriceListId',
            price: 32.15,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 769.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 32.08,
          }],
          skuDiscountPrice: [{
            priceListId: 'twoYearPriceListId',
            price: 319.99,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 769.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 32.08,
          }],
        },
        colorImage: null,
        upgradeOptionCode: 'UO',
        annualUpgradeEligible: true,
        displayName: 'Apple&reg; iPhone&reg; 7 Plus 32GB in Black',
        colorCode: '#2e3034',
        mobileAppImageName: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-matblk?$device-lg$',
        shippingDateLabel: null,
        shippingDateStatusCode: 1000,
      }, {
        colorName: 'Silver',
        imageUrl: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-svr?$device-lg$',
        upgradeOptionEllPDPLbl50: '\n            ',
        promotionDetails: null,
        restrictionFlag: false,
        upgradeOptionEllPDPLbl70: '\n            ',
        devicePrice: [{
          mailInRebateAmount: 0.0,
          priceListId: 'edgeRemainingMonthPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 769.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: true,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 32.08,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: '/mo.',
          contractPrice: '32.08',
          contractTerm: 99,
          originalPrice: 32.08,
          creditOptionVOList: null,
          fullRetailPrice: 769.99,
          waivedUpgradeFeePromo: false,
          contractTitle: '$0 Down (for qualified customers) $32.08/mo for 24 months; 0% APR Retail Price: $769.99',
          contractName: '24 Monthly Payments',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }, {
          mailInRebateAmount: 0.0,
          priceListId: 'fullRetailPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 769.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: false,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 769.99,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: null,
          contractPrice: '769.99',
          contractTerm: 0,
          originalPrice: 769.99,
          creditOptionVOList: null,
          fullRetailPrice: 769.99,
          waivedUpgradeFeePromo: false,
          contractTitle: 'No Early Termination Fee',
          contractName: 'Retail Price',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }],
        skuImageName: 'iphone7-plus-front-svr',
        upgradeOptionEllPDPTip70: '\n            ',
        selected: false,
        upgradeOptionEllPDPTip50: '\n            ',
        restrictionMessage: null,
        sameDayDeliveryFlag: true,
        capacity: '32GB',
        inventoryStatus: 1001,
        deviceSkuId: 'sku2150069',
        devicePaymentPercentage: '50',
        deviceSorId: 'MNR22LL/A',
        skuListDiscountPricing: {
          skuListPrice: [{
            priceListId: 'edgeFullRetailPriceListId',
            price: 769.99,
          }, {
            priceListId: 'twoYearPriceListId',
            price: 319.99,
          }, {
            priceListId: 'edgeFirstMonthPriceListId',
            price: 32.15,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 769.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 32.08,
          }],
          skuDiscountPrice: [{
            priceListId: 'twoYearPriceListId',
            price: 319.99,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 769.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 32.08,
          }],
        },
        colorImage: null,
        upgradeOptionCode: 'UO',
        annualUpgradeEligible: true,
        displayName: 'Apple&reg; iPhone&reg; 7 Plus 32GB in Silver',
        colorCode: '#d7d7d7',
        mobileAppImageName: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-svr?$device-lg$',
        shippingDateLabel: null,
        shippingDateStatusCode: 1001,
      }, {
        colorName: 'Gold',
        imageUrl: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-gld?$device-lg$',
        upgradeOptionEllPDPLbl50: '\n            ',
        promotionDetails: null,
        restrictionFlag: false,
        upgradeOptionEllPDPLbl70: '\n            ',
        devicePrice: [{
          mailInRebateAmount: 0.0,
          priceListId: 'edgeRemainingMonthPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 769.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: true,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 32.08,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: '/mo.',
          contractPrice: '32.08',
          contractTerm: 99,
          originalPrice: 32.08,
          creditOptionVOList: null,
          fullRetailPrice: 769.99,
          waivedUpgradeFeePromo: false,
          contractTitle: '$0 Down (for qualified customers) $32.08/mo for 24 months; 0% APR Retail Price: $769.99',
          contractName: '24 Monthly Payments',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }, {
          mailInRebateAmount: 0.0,
          priceListId: 'fullRetailPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 769.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: false,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 769.99,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: null,
          contractPrice: '769.99',
          contractTerm: 0,
          originalPrice: 769.99,
          creditOptionVOList: null,
          fullRetailPrice: 769.99,
          waivedUpgradeFeePromo: false,
          contractTitle: 'No Early Termination Fee',
          contractName: 'Retail Price',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }],
        skuImageName: 'iphone7-plus-front-gld',
        upgradeOptionEllPDPTip70: '\n            ',
        selected: false,
        upgradeOptionEllPDPTip50: '\n            ',
        restrictionMessage: null,
        sameDayDeliveryFlag: true,
        capacity: '32GB',
        inventoryStatus: 1001,
        deviceSkuId: 'sku2150067',
        devicePaymentPercentage: '50',
        deviceSorId: 'MNR32LL/A',
        skuListDiscountPricing: {
          skuListPrice: [{
            priceListId: 'edgeFullRetailPriceListId',
            price: 769.99,
          }, {
            priceListId: 'twoYearPriceListId',
            price: 319.99,
          }, {
            priceListId: 'edgeFirstMonthPriceListId',
            price: 32.15,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 769.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 32.08,
          }],
          skuDiscountPrice: [{
            priceListId: 'twoYearPriceListId',
            price: 319.99,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 769.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 32.08,
          }],
        },
        colorImage: null,
        upgradeOptionCode: 'UO',
        annualUpgradeEligible: true,
        displayName: 'Apple&reg; iPhone&reg; 7 Plus 32GB in Gold',
        colorCode: '#CFBEA9',
        mobileAppImageName: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-gld?$device-lg$',
        shippingDateLabel: null,
        shippingDateStatusCode: 1001,
      }, {
        colorName: 'Rose Gold',
        imageUrl: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-rsgld?$device-lg$',
        upgradeOptionEllPDPLbl50: '\n            ',
        promotionDetails: null,
        restrictionFlag: false,
        upgradeOptionEllPDPLbl70: '\n            ',
        devicePrice: [{
          mailInRebateAmount: 0.0,
          priceListId: 'edgeRemainingMonthPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 769.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: true,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 32.08,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: '/mo.',
          contractPrice: '32.08',
          contractTerm: 99,
          originalPrice: 32.08,
          creditOptionVOList: null,
          fullRetailPrice: 769.99,
          waivedUpgradeFeePromo: false,
          contractTitle: '$0 Down (for qualified customers) $32.08/mo for 24 months; 0% APR Retail Price: $769.99',
          contractName: '24 Monthly Payments',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }, {
          mailInRebateAmount: 0.0,
          priceListId: 'fullRetailPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 769.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: false,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 769.99,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: null,
          contractPrice: '769.99',
          contractTerm: 0,
          originalPrice: 769.99,
          creditOptionVOList: null,
          fullRetailPrice: 769.99,
          waivedUpgradeFeePromo: false,
          contractTitle: 'No Early Termination Fee',
          contractName: 'Retail Price',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }],
        skuImageName: 'iphone7-plus-front-rsgld',
        upgradeOptionEllPDPTip70: '\n            ',
        selected: false,
        upgradeOptionEllPDPTip50: '\n            ',
        restrictionMessage: null,
        sameDayDeliveryFlag: true,
        capacity: '32GB',
        inventoryStatus: 1000,
        deviceSkuId: 'sku2150068',
        devicePaymentPercentage: '50',
        deviceSorId: 'MNR42LL/A',
        skuListDiscountPricing: {
          skuListPrice: [{
            priceListId: 'edgeFullRetailPriceListId',
            price: 769.99,
          }, {
            priceListId: 'twoYearPriceListId',
            price: 319.99,
          }, {
            priceListId: 'edgeFirstMonthPriceListId',
            price: 32.15,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 769.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 32.08,
          }],
          skuDiscountPrice: [{
            priceListId: 'twoYearPriceListId',
            price: 319.99,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 769.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 32.08,
          }],
        },
        colorImage: null,
        upgradeOptionCode: 'UO',
        annualUpgradeEligible: true,
        displayName: 'Apple&reg; iPhone&reg; 7 Plus 32GB in Rose Gold',
        colorCode: '#edccbd',
        mobileAppImageName: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-rsgld?$device-lg$',
        shippingDateLabel: null,
        shippingDateStatusCode: 1000,
      }, {
        colorName: 'Apple Jet Black',
        imageUrl: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-jetblk?$device-lg$',
        upgradeOptionEllPDPLbl50: '\n            ',
        promotionDetails: null,
        restrictionFlag: false,
        upgradeOptionEllPDPLbl70: '\n            ',
        devicePrice: [{
          mailInRebateAmount: 0.0,
          priceListId: 'edgeRemainingMonthPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 869.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: true,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 36.24,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: '/mo.',
          contractPrice: '36.24',
          contractTerm: 99,
          originalPrice: 36.24,
          creditOptionVOList: null,
          fullRetailPrice: 869.99,
          waivedUpgradeFeePromo: false,
          contractTitle: '$0 Down (for qualified customers) $36.24/mo for 24 months; 0% APR Retail Price: $869.99',
          contractName: '24 Monthly Payments',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }, {
          mailInRebateAmount: 0.0,
          priceListId: 'fullRetailPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 869.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: false,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 869.99,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: null,
          contractPrice: '869.99',
          contractTerm: 0,
          originalPrice: 869.99,
          creditOptionVOList: null,
          fullRetailPrice: 869.99,
          waivedUpgradeFeePromo: false,
          contractTitle: 'No Early Termination Fee',
          contractName: 'Retail Price',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }],
        skuImageName: 'iphone7-plus-front-jetblk',
        upgradeOptionEllPDPTip70: '\n            ',
        selected: false,
        upgradeOptionEllPDPTip50: '\n            ',
        restrictionMessage: null,
        sameDayDeliveryFlag: true,
        capacity: '128GB',
        inventoryStatus: 1001,
        deviceSkuId: 'sku2150075',
        devicePaymentPercentage: '50',
        deviceSorId: 'MN5X2LL/A',
        skuListDiscountPricing: {
          skuListPrice: [{
            priceListId: 'edgeFullRetailPriceListId',
            price: 869.99,
          }, {
            priceListId: 'twoYearPriceListId',
            price: 419.99,
          }, {
            priceListId: 'edgeFirstMonthPriceListId',
            price: 36.47,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 869.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 36.24,
          }],
          skuDiscountPrice: [{
            priceListId: 'twoYearPriceListId',
            price: 419.99,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 869.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 36.24,
          }],
        },
        colorImage: null,
        upgradeOptionCode: 'UO',
        annualUpgradeEligible: true,
        displayName: 'Apple&reg; iPhone&reg; 7 Plus 128GB in Jet Black',
        colorCode: '#000000',
        mobileAppImageName: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-jetblk?$device-lg$',
        shippingDateLabel: null,
        shippingDateStatusCode: 1001,
      }, {
        colorName: 'Apple Black',
        imageUrl: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-matblk?$device-lg$',
        upgradeOptionEllPDPLbl50: '\n            ',
        promotionDetails: null,
        restrictionFlag: false,
        upgradeOptionEllPDPLbl70: '\n            ',
        devicePrice: [{
          mailInRebateAmount: 0.0,
          priceListId: 'edgeRemainingMonthPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 869.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: true,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 36.24,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: '/mo.',
          contractPrice: '36.24',
          contractTerm: 99,
          originalPrice: 36.24,
          creditOptionVOList: null,
          fullRetailPrice: 869.99,
          waivedUpgradeFeePromo: false,
          contractTitle: '$0 Down (for qualified customers) $36.24/mo for 24 months; 0% APR Retail Price: $869.99',
          contractName: '24 Monthly Payments',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }, {
          mailInRebateAmount: 0.0,
          priceListId: 'fullRetailPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 869.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: false,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 869.99,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: null,
          contractPrice: '869.99',
          contractTerm: 0,
          originalPrice: 869.99,
          creditOptionVOList: null,
          fullRetailPrice: 869.99,
          waivedUpgradeFeePromo: false,
          contractTitle: 'No Early Termination Fee',
          contractName: 'Retail Price',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }],
        skuImageName: 'iphone7-plus-front-matblk',
        upgradeOptionEllPDPTip70: '\n            ',
        selected: false,
        upgradeOptionEllPDPTip50: '\n            ',
        restrictionMessage: null,
        sameDayDeliveryFlag: true,
        capacity: '128GB',
        inventoryStatus: 1001,
        deviceSkuId: 'sku2150074',
        devicePaymentPercentage: '50',
        deviceSorId: 'MN5T2LL/A',
        skuListDiscountPricing: {
          skuListPrice: [{
            priceListId: 'edgeFullRetailPriceListId',
            price: 869.99,
          }, {
            priceListId: 'twoYearPriceListId',
            price: 419.99,
          }, {
            priceListId: 'edgeFirstMonthPriceListId',
            price: 36.47,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 869.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 36.24,
          }],
          skuDiscountPrice: [{
            priceListId: 'twoYearPriceListId',
            price: 419.99,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 869.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 36.24,
          }],
        },
        colorImage: null,
        upgradeOptionCode: 'UO',
        annualUpgradeEligible: true,
        displayName: 'Apple&reg; iPhone&reg; 7 Plus 128GB in Black',
        colorCode: '#2e3034',
        mobileAppImageName: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-matblk?$device-lg$',
        shippingDateLabel: null,
        shippingDateStatusCode: 1001,
      }, {
        colorName: 'Silver',
        imageUrl: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-svr?$device-lg$',
        upgradeOptionEllPDPLbl50: '\n            ',
        promotionDetails: null,
        restrictionFlag: false,
        upgradeOptionEllPDPLbl70: '\n            ',
        devicePrice: [{
          mailInRebateAmount: 0.0,
          priceListId: 'edgeRemainingMonthPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 869.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: true,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 36.24,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: '/mo.',
          contractPrice: '36.24',
          contractTerm: 99,
          originalPrice: 36.24,
          creditOptionVOList: null,
          fullRetailPrice: 869.99,
          waivedUpgradeFeePromo: false,
          contractTitle: '$0 Down (for qualified customers) $36.24/mo for 24 months; 0% APR Retail Price: $869.99',
          contractName: '24 Monthly Payments',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }, {
          mailInRebateAmount: 0.0,
          priceListId: 'fullRetailPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 869.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: false,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 869.99,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: null,
          contractPrice: '869.99',
          contractTerm: 0,
          originalPrice: 869.99,
          creditOptionVOList: null,
          fullRetailPrice: 869.99,
          waivedUpgradeFeePromo: false,
          contractTitle: 'No Early Termination Fee',
          contractName: 'Retail Price',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }],
        skuImageName: 'iphone7-plus-front-svr',
        upgradeOptionEllPDPTip70: '\n            ',
        selected: false,
        upgradeOptionEllPDPTip50: '\n            ',
        restrictionMessage: null,
        sameDayDeliveryFlag: true,
        capacity: '128GB',
        inventoryStatus: 1001,
        deviceSkuId: 'sku2150073',
        devicePaymentPercentage: '50',
        deviceSorId: 'MN5U2LL/A',
        skuListDiscountPricing: {
          skuListPrice: [{
            priceListId: 'edgeFullRetailPriceListId',
            price: 869.99,
          }, {
            priceListId: 'twoYearPriceListId',
            price: 419.99,
          }, {
            priceListId: 'edgeFirstMonthPriceListId',
            price: 36.47,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 869.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 36.24,
          }],
          skuDiscountPrice: [{
            priceListId: 'twoYearPriceListId',
            price: 419.99,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 869.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 36.24,
          }],
        },
        colorImage: null,
        upgradeOptionCode: 'UO',
        annualUpgradeEligible: true,
        displayName: 'Apple&reg; iPhone&reg; 7 Plus 128GB in Silver',
        colorCode: '#d7d7d7',
        mobileAppImageName: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-svr?$device-lg$',
        shippingDateLabel: null,
        shippingDateStatusCode: 1001,
      }, {
        colorName: 'Gold',
        imageUrl: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-gld?$device-lg$',
        upgradeOptionEllPDPLbl50: '\n            ',
        promotionDetails: null,
        restrictionFlag: false,
        upgradeOptionEllPDPLbl70: '\n            ',
        devicePrice: [{
          mailInRebateAmount: 0.0,
          priceListId: 'edgeRemainingMonthPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 869.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: true,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 36.24,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: '/mo.',
          contractPrice: '36.24',
          contractTerm: 99,
          originalPrice: 36.24,
          creditOptionVOList: null,
          fullRetailPrice: 869.99,
          waivedUpgradeFeePromo: false,
          contractTitle: '$0 Down (for qualified customers) $36.24/mo for 24 months; 0% APR Retail Price: $869.99',
          contractName: '24 Monthly Payments',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }, {
          mailInRebateAmount: 0.0,
          priceListId: 'fullRetailPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 869.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: false,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 869.99,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: null,
          contractPrice: '869.99',
          contractTerm: 0,
          originalPrice: 869.99,
          creditOptionVOList: null,
          fullRetailPrice: 869.99,
          waivedUpgradeFeePromo: false,
          contractTitle: 'No Early Termination Fee',
          contractName: 'Retail Price',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }],
        skuImageName: 'iphone7-plus-front-gld',
        upgradeOptionEllPDPTip70: '\n            ',
        selected: false,
        upgradeOptionEllPDPTip50: '\n            ',
        restrictionMessage: null,
        sameDayDeliveryFlag: true,
        capacity: '128GB',
        inventoryStatus: 1001,
        deviceSkuId: 'sku2150071',
        devicePaymentPercentage: '50',
        deviceSorId: 'MN5V2LL/A',
        skuListDiscountPricing: {
          skuListPrice: [{
            priceListId: 'edgeFullRetailPriceListId',
            price: 869.99,
          }, {
            priceListId: 'twoYearPriceListId',
            price: 419.99,
          }, {
            priceListId: 'edgeFirstMonthPriceListId',
            price: 36.47,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 869.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 36.24,
          }],
          skuDiscountPrice: [{
            priceListId: 'twoYearPriceListId',
            price: 419.99,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 869.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 36.24,
          }],
        },
        colorImage: null,
        upgradeOptionCode: 'UO',
        annualUpgradeEligible: true,
        displayName: 'Apple&reg; iPhone&reg; 7 Plus 128GB in Gold',
        colorCode: '#CFBEA9',
        mobileAppImageName: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-gld?$device-lg$',
        shippingDateLabel: null,
        shippingDateStatusCode: 1001,
      }, {
        colorName: 'Rose Gold',
        imageUrl: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-rsgld?$device-lg$',
        upgradeOptionEllPDPLbl50: '\n            ',
        promotionDetails: null,
        restrictionFlag: false,
        upgradeOptionEllPDPLbl70: '\n            ',
        devicePrice: [{
          mailInRebateAmount: 0.0,
          priceListId: 'edgeRemainingMonthPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 869.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: true,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 36.24,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: '/mo.',
          contractPrice: '36.24',
          contractTerm: 99,
          originalPrice: 36.24,
          creditOptionVOList: null,
          fullRetailPrice: 869.99,
          waivedUpgradeFeePromo: false,
          contractTitle: '$0 Down (for qualified customers) $36.24/mo for 24 months; 0% APR Retail Price: $869.99',
          contractName: '24 Monthly Payments',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }, {
          mailInRebateAmount: 0.0,
          priceListId: 'fullRetailPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 869.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: false,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 869.99,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: null,
          contractPrice: '869.99',
          contractTerm: 0,
          originalPrice: 869.99,
          creditOptionVOList: null,
          fullRetailPrice: 869.99,
          waivedUpgradeFeePromo: false,
          contractTitle: 'No Early Termination Fee',
          contractName: 'Retail Price',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }],
        skuImageName: 'iphone7-plus-front-rsgld',
        upgradeOptionEllPDPTip70: '\n            ',
        selected: false,
        upgradeOptionEllPDPTip50: '\n            ',
        restrictionMessage: null,
        sameDayDeliveryFlag: true,
        capacity: '128GB',
        inventoryStatus: 1000,
        deviceSkuId: 'sku2150072',
        devicePaymentPercentage: '50',
        deviceSorId: 'MN5W2LL/A',
        skuListDiscountPricing: {
          skuListPrice: [{
            priceListId: 'edgeFullRetailPriceListId',
            price: 869.99,
          }, {
            priceListId: 'twoYearPriceListId',
            price: 419.99,
          }, {
            priceListId: 'edgeFirstMonthPriceListId',
            price: 36.47,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 869.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 36.24,
          }],
          skuDiscountPrice: [{
            priceListId: 'twoYearPriceListId',
            price: 419.99,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 869.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 36.24,
          }],
        },
        colorImage: null,
        upgradeOptionCode: 'UO',
        annualUpgradeEligible: true,
        displayName: 'Apple&reg; iPhone&reg; 7 Plus 128GB in Rose Gold',
        colorCode: '#edccbd',
        mobileAppImageName: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-rsgld?$device-lg$',
        shippingDateLabel: null,
        shippingDateStatusCode: 1000,
      }, {
        colorName: 'Apple Jet Black',
        imageUrl: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-jetblk?$device-lg$',
        upgradeOptionEllPDPLbl50: '\n            ',
        promotionDetails: null,
        restrictionFlag: false,
        upgradeOptionEllPDPLbl70: '\n            ',
        devicePrice: [{
          mailInRebateAmount: 0.0,
          priceListId: 'edgeRemainingMonthPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 969.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: true,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 40.41,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: '/mo.',
          contractPrice: '40.41',
          contractTerm: 99,
          originalPrice: 40.41,
          creditOptionVOList: null,
          fullRetailPrice: 969.99,
          waivedUpgradeFeePromo: false,
          contractTitle: '$0 Down (for qualified customers) $40.41/mo for 24 months; 0% APR Retail Price: $969.99',
          contractName: '24 Monthly Payments',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }, {
          mailInRebateAmount: 0.0,
          priceListId: 'fullRetailPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 969.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: false,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 969.99,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: null,
          contractPrice: '969.99',
          contractTerm: 0,
          originalPrice: 969.99,
          creditOptionVOList: null,
          fullRetailPrice: 969.99,
          waivedUpgradeFeePromo: false,
          contractTitle: 'No Early Termination Fee',
          contractName: 'Retail Price',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }],
        skuImageName: 'iphone7-plus-front-jetblk',
        upgradeOptionEllPDPTip70: '\n            ',
        selected: false,
        upgradeOptionEllPDPTip50: '\n            ',
        restrictionMessage: null,
        sameDayDeliveryFlag: true,
        capacity: '256GB',
        inventoryStatus: 1001,
        deviceSkuId: 'sku2150080',
        devicePaymentPercentage: '50',
        deviceSorId: 'MN632LL/A',
        skuListDiscountPricing: {
          skuListPrice: [{
            priceListId: 'edgeFullRetailPriceListId',
            price: 969.99,
          }, {
            priceListId: 'twoYearPriceListId',
            price: 519.99,
          }, {
            priceListId: 'edgeFirstMonthPriceListId',
            price: 40.56,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 969.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 40.41,
          }],
          skuDiscountPrice: [{
            priceListId: 'twoYearPriceListId',
            price: 519.99,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 969.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 40.41,
          }],
        },
        colorImage: null,
        upgradeOptionCode: 'UO',
        annualUpgradeEligible: true,
        displayName: 'Apple&reg; iPhone&reg; 7 Plus 256GB in Jet Black',
        colorCode: '#000000',
        mobileAppImageName: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-jetblk?$device-lg$',
        shippingDateLabel: null,
        shippingDateStatusCode: 1001,
      }, {
        colorName: 'Apple Black',
        imageUrl: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-matblk?$device-lg$',
        upgradeOptionEllPDPLbl50: '\n            ',
        promotionDetails: null,
        restrictionFlag: false,
        upgradeOptionEllPDPLbl70: '\n            ',
        devicePrice: [{
          mailInRebateAmount: 0.0,
          priceListId: 'edgeRemainingMonthPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 969.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: true,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 40.41,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: '/mo.',
          contractPrice: '40.41',
          contractTerm: 99,
          originalPrice: 40.41,
          creditOptionVOList: null,
          fullRetailPrice: 969.99,
          waivedUpgradeFeePromo: false,
          contractTitle: '$0 Down (for qualified customers) $40.41/mo for 24 months; 0% APR Retail Price: $969.99',
          contractName: '24 Monthly Payments',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }, {
          mailInRebateAmount: 0.0,
          priceListId: 'fullRetailPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 969.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: false,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 969.99,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: null,
          contractPrice: '969.99',
          contractTerm: 0,
          originalPrice: 969.99,
          creditOptionVOList: null,
          fullRetailPrice: 969.99,
          waivedUpgradeFeePromo: false,
          contractTitle: 'No Early Termination Fee',
          contractName: 'Retail Price',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }],
        skuImageName: 'iphone7-plus-front-matblk',
        upgradeOptionEllPDPTip70: '\n            ',
        selected: false,
        upgradeOptionEllPDPTip50: '\n            ',
        restrictionMessage: null,
        sameDayDeliveryFlag: true,
        capacity: '256GB',
        inventoryStatus: 1001,
        deviceSkuId: 'sku2150079',
        devicePaymentPercentage: '50',
        deviceSorId: 'MN5Y2LL/A',
        skuListDiscountPricing: {
          skuListPrice: [{
            priceListId: 'edgeFullRetailPriceListId',
            price: 969.99,
          }, {
            priceListId: 'twoYearPriceListId',
            price: 519.99,
          }, {
            priceListId: 'edgeFirstMonthPriceListId',
            price: 40.56,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 969.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 40.41,
          }],
          skuDiscountPrice: [{
            priceListId: 'twoYearPriceListId',
            price: 519.99,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 969.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 40.41,
          }],
        },
        colorImage: null,
        upgradeOptionCode: 'UO',
        annualUpgradeEligible: true,
        displayName: 'Apple&reg; iPhone&reg; 7 Plus 256GB in Black',
        colorCode: '#2e3034',
        mobileAppImageName: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-matblk?$device-lg$',
        shippingDateLabel: null,
        shippingDateStatusCode: 1001,
      }, {
        colorName: 'Gold',
        imageUrl: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-gld?$device-lg$',
        upgradeOptionEllPDPLbl50: '\n            ',
        promotionDetails: null,
        restrictionFlag: false,
        upgradeOptionEllPDPLbl70: '\n            ',
        devicePrice: [{
          mailInRebateAmount: 0.0,
          priceListId: 'edgeRemainingMonthPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 969.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: true,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 40.41,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: '/mo.',
          contractPrice: '40.41',
          contractTerm: 99,
          originalPrice: 40.41,
          creditOptionVOList: null,
          fullRetailPrice: 969.99,
          waivedUpgradeFeePromo: false,
          contractTitle: '$0 Down (for qualified customers) $40.41/mo for 24 months; 0% APR Retail Price: $969.99',
          contractName: '24 Monthly Payments',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }, {
          mailInRebateAmount: 0.0,
          priceListId: 'fullRetailPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 969.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: false,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 969.99,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: null,
          contractPrice: '969.99',
          contractTerm: 0,
          originalPrice: 969.99,
          creditOptionVOList: null,
          fullRetailPrice: 969.99,
          waivedUpgradeFeePromo: false,
          contractTitle: 'No Early Termination Fee',
          contractName: 'Retail Price',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }],
        skuImageName: 'iphone7-plus-front-gld',
        upgradeOptionEllPDPTip70: '\n            ',
        selected: false,
        upgradeOptionEllPDPTip50: '\n            ',
        restrictionMessage: null,
        sameDayDeliveryFlag: true,
        capacity: '256GB',
        inventoryStatus: 1001,
        deviceSkuId: 'sku2150076',
        devicePaymentPercentage: '50',
        deviceSorId: 'MN612LL/A',
        skuListDiscountPricing: {
          skuListPrice: [{
            priceListId: 'edgeFullRetailPriceListId',
            price: 969.99,
          }, {
            priceListId: 'twoYearPriceListId',
            price: 519.99,
          }, {
            priceListId: 'edgeFirstMonthPriceListId',
            price: 40.56,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 969.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 40.41,
          }],
          skuDiscountPrice: [{
            priceListId: 'twoYearPriceListId',
            price: 519.99,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 969.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 40.41,
          }],
        },
        colorImage: null,
        upgradeOptionCode: 'UO',
        annualUpgradeEligible: true,
        displayName: 'Apple&reg; iPhone&reg; 7 Plus 256GB in Gold',
        colorCode: '#CFBEA9',
        mobileAppImageName: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-gld?$device-lg$',
        shippingDateLabel: null,
        shippingDateStatusCode: 1001,
      }, {
        colorName: 'Rose Gold',
        imageUrl: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-rsgld?$device-lg$',
        upgradeOptionEllPDPLbl50: '\n            ',
        promotionDetails: null,
        restrictionFlag: false,
        upgradeOptionEllPDPLbl70: '\n            ',
        devicePrice: [{
          mailInRebateAmount: 0.0,
          priceListId: 'edgeRemainingMonthPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 969.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: true,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 40.41,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: '/mo.',
          contractPrice: '40.41',
          contractTerm: 99,
          originalPrice: 40.41,
          creditOptionVOList: null,
          fullRetailPrice: 969.99,
          waivedUpgradeFeePromo: false,
          contractTitle: '$0 Down (for qualified customers) $40.41/mo for 24 months; 0% APR Retail Price: $969.99',
          contractName: '24 Monthly Payments',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }, {
          mailInRebateAmount: 0.0,
          priceListId: 'fullRetailPriceListId',
          bicOfferApplied: false,
          ecpdDiscountOffer: false,
          bicAdditionalContractText: null,
          edgeFullRetailPrice: 969.99,
          alwaysEligibleDownPaymentPercentage: null,
          mailInRebateText: null,
          sedEcpdDiscountPercentage: 0.0,
          selected: false,
          edgeEnabled: false,
          earlyTerminationText: null,
          rebateAmount: 0.0,
          orgiginalMonthlyPrice: 0.0,
          alwaysEligibleDownPaymentPercentageText: null,
          orignalFullRetailPrice: 0.0,
          edgeDownpayment: 0.0,
          mailInRebateIndicator: false,
          edgeType: null,
          upgradeFee: 0.0,
          activationFee: 0.0,
          bicDiscountedContractPrice: 0.0,
          waivedActivationFeePromo: false,
          discountPrice: 969.99,
          ecpdDiscount: 0.0,
          bicContractPrice: 0.0,
          contractDetail: null,
          contractPrice: '969.99',
          contractTerm: 0,
          originalPrice: 969.99,
          creditOptionVOList: null,
          fullRetailPrice: 969.99,
          waivedUpgradeFeePromo: false,
          contractTitle: 'No Early Termination Fee',
          contractName: 'Retail Price',
          contractToDevicePaymentEligibilityInd: false,
          puEligibleFlag: false,
        }],
        skuImageName: 'iphone7-plus-front-rsgld',
        upgradeOptionEllPDPTip70: '\n            ',
        selected: false,
        upgradeOptionEllPDPTip50: '\n            ',
        restrictionMessage: null,
        sameDayDeliveryFlag: true,
        capacity: '256GB',
        inventoryStatus: 1001,
        deviceSkuId: 'sku2150077',
        devicePaymentPercentage: '50',
        deviceSorId: 'MN622LL/A',
        skuListDiscountPricing: {
          skuListPrice: [{
            priceListId: 'edgeFullRetailPriceListId',
            price: 969.99,
          }, {
            priceListId: 'twoYearPriceListId',
            price: 519.99,
          }, {
            priceListId: 'edgeFirstMonthPriceListId',
            price: 40.56,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 969.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 40.41,
          }],
          skuDiscountPrice: [{
            priceListId: 'twoYearPriceListId',
            price: 519.99,
          }, {
            priceListId: 'fullRetailPriceListId',
            price: 969.99,
          }, {
            priceListId: 'edgeRemainingMonthPriceListId',
            price: 40.41,
          }],
        },
        colorImage: null,
        upgradeOptionCode: 'UO',
        annualUpgradeEligible: true,
        displayName: 'Apple&reg; iPhone&reg; 7 Plus 256GB in Rose Gold',
        colorCode: '#edccbd',
        mobileAppImageName: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-rsgld?$device-lg$',
        shippingDateLabel: null,
        shippingDateStatusCode: 1001,
      }],
      pdpBadgeFullRetail: null,
      creditOptionsAvailabilityVO: null,
      deviceId: 'dev6640013',
      badgeTwoYearDisplayName: null,
      seoCategoryName: 'smartphones',
      marketingTout: null,
      badgeEdgeDisplayName: '$200 off any iPad w/purchase.',
      circularBadgeText: '$200 off any iPad w/purchase.',
      canonicalURL: 'smartphones/apple-iphone-7-plus/',
      priceDisclaimer: 'Your employee discounts have been applied.',
      displayName: 'iPhone&reg; 7 Plus',
      pdpBadgePayment: null,
      badgeRetailToolTip: null,
      seoBrandName: 'apple',
      mobileAppImageName: 'https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-matblk?$device-lg$',
    },
  },
  statusMessage: 'Service completed Successfully.',
};


export default deviceConfigJson;
