window.confirmationJSON = {
  "output": {
    "title": "You're all set.",
    "subtitle": null,
    "orderId": "804760191176449",
    "estimatedDelivery": "",
    "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/1.3_MV_BuyandUpgrade_ConfirmationPage_Interstital?$device-med$",
    "tradeInStatus": false,
    "confirmationMessage": "Thanks for ordering from verizonwireless.com. Your order receipt is sent to SIVARAMCHANDHAR.VENKATACHALAPATHY@VERIZON.COM.<br> Please follow the instructions on http://www.vzw.com/digitalrebatecenter to get your free Google Home Mini",
    "doneButtonText": "Got it",
    "doneButtonLink": "/od/cust/auth/shoplanding/",
    "userNote": "TODO",
    "notNowButtonText": "TODO",
    "notNowButtonLink": "TODO",
    "learnHowButtonText": null,
    "learnHowButtonLink": "/od/cust/auth/learnHow",
    "numberOfDevice": 1,
    "confirmationNumberText": "Confirmation Number",
    "iconicFlow": true,
    "protectionURL": null,
    "accessoriesURL": null,
    "tapFlag": false,
    "cjmTagUrl": null,
    "pepperJamTagUrl": null,
    "selectedPaymentMode": null,
    "confirmationEmail": "SIVARAMCHANDHAR.VENKATACHALAPATHY@VERIZON.COM",
    "plans": {
      "dueMonthly": "205.00",
      "dueToday": "0.00",
      "planOnlyDueMonthly": "205.00",
      "items": [
        {
          "planType": "Go Unlimited",
          "lineAccessCharges": [
            {
              "name": "Google Pixel 2 XL 64GB in Black and White",
              "mtn": null,
              "price": "55.00",
              "discountPrice": "0.00",
              "retailPrice": "0.00",
              "hasEcpdDiscount": false,
              "promoMessage": null,
              "originalPrice": "0.00",
              "wasPrice": "0.00",
              "deviceName": "Pixel 2 XL",
              "color": "Black and White",
              "size": "64GB",
              "introText": null,
              "smartFamily": false,
              "freeTrial": false,
              "instantCreditAmount": "0.00",
              "amountAfterInstantCredit": "0.00",
              "disountedInstantCreditAmt": "0.00",
              "tapfeature": false
            }
          ],
          "accountAccess": {
            "name": "Go Unlimited",
            "mtn": null,
            "price": "205.00",
            "discountPrice": "0.00",
            "retailPrice": "0.00",
            "hasEcpdDiscount": false,
            "promoMessage": null,
            "originalPrice": "0.00",
            "wasPrice": "0.00",
            "deviceName": null,
            "color": null,
            "size": null,
            "introText": null,
            "smartFamily": false,
            "freeTrial": false,
            "instantCreditAmount": "0.00",
            "amountAfterInstantCredit": "0.00",
            "disountedInstantCreditAmt": "0.00",
            "tapfeature": false
          },
          "accountLevelFeatures": null,
          "totalMonthlyPlanCost": "205.00",
          "spoBadgeMessage": null,
          "planDisplayName": "Go Unlimited",
          "planImageURL": null,
          "planLetter": null,
          "planDescrption": null,
          "planDescription": null,
          "quantity": 0,
          "skuId": null,
          "productId": null,
          "itemAmount": null,
          "itemAmountOriginal": null,
          "dueMonthly": null,
          "dueMonthlyOriginal": null,
          "itemDiscount": null,
          "displayName": null,
          "skuDisplayName": null,
          "listPrice": null,
          "rawTotalAmount": null,
          "planGroupCode": null,
          "autoPayEnabled": false,
          "numberSharePlan": false,
          "planCommerceItemId": null,
          "autoPayPrice": null,
          "autoPayText": null,
          "termsAndConditionKey": null,
          "unitOfMeasure": null,
          "planSize": null
        }
      ],
      "upgradeDevices": [],
      "newDevices": [
        {
          "name": "Pixel 2 XL",
          "price": "55.00",
          "discountPrice": 0,
          "hasEcpdDiscount": false,
          "mtn": null,
          "listPrice": 55,
          "deviceLineItemId": "S925cdf411b04821730b1dfdca7e08b30{ss1}_device_1",
          "discountPriceVal": "0.00",
          "planCommerceItemId": null,
          "nickName": null,
          "numberShareDevice": false,
          "featureDropped": false,
          "deviceType": null,
          "trunkMtn": null,
          "changePlanUrl": null,
          "rioDevice": false
        }
      ],
      "existingDevices": [
        {
          "name": "Apple&reg; iPad&reg; with Wi&ndash;Fi + Cellular White 64GB",
          "price": "20.00",
          "discountPrice": 0,
          "hasEcpdDiscount": false,
          "mtn": "2064915081",
          "listPrice": 20,
          "deviceLineItemId": null,
          "discountPriceVal": "0.00",
          "planCommerceItemId": null,
          "nickName": null,
          "numberShareDevice": false,
          "featureDropped": false,
          "deviceType": null,
          "trunkMtn": null,
          "changePlanUrl": null,
          "rioDevice": false
        },
        {
          "name": "Samsung Galaxy S&reg; 5 in Charcoal Black",
          "price": "55.00",
          "discountPrice": 0,
          "hasEcpdDiscount": false,
          "mtn": "4257808580",
          "listPrice": 55,
          "deviceLineItemId": null,
          "discountPriceVal": "0.00",
          "planCommerceItemId": null,
          "nickName": null,
          "numberShareDevice": false,
          "featureDropped": false,
          "deviceType": null,
          "trunkMtn": null,
          "changePlanUrl": null,
          "rioDevice": false
        },
        {
          "name": "Apple&reg; iPhone&reg; 7 Plus 32GB in Black",
          "price": "55.00",
          "discountPrice": 0,
          "hasEcpdDiscount": false,
          "mtn": "4259671407",
          "listPrice": 55,
          "deviceLineItemId": null,
          "discountPriceVal": "0.00",
          "planCommerceItemId": null,
          "nickName": null,
          "numberShareDevice": false,
          "featureDropped": false,
          "deviceType": null,
          "trunkMtn": null,
          "changePlanUrl": null,
          "rioDevice": false
        },
        {
          "name": "Verizon Ellipsis&reg; 7 LTE in Black",
          "price": "20.00",
          "discountPrice": 0,
          "hasEcpdDiscount": false,
          "mtn": "9099535181",
          "listPrice": 20,
          "deviceLineItemId": null,
          "discountPriceVal": "0.00",
          "planCommerceItemId": null,
          "nickName": null,
          "numberShareDevice": false,
          "featureDropped": false,
          "deviceType": null,
          "trunkMtn": null,
          "changePlanUrl": null,
          "rioDevice": false
        }
      ],
      "dueMonthlyPlanWithLAC": "205.00",
      "discountedDueMonthlyPlanWithLAC": "0.00",
      "hasEcpdDiscount": false,
      "totalLineAccessCharges": "55.00"
    },
    "tradeInDevicesDetails": null,
    "tradeInPromoDetails": null,
    "transformedTradeInPromoDetails": {
      "tradeInDeviceDppMsg": "We'll send you a prepaid box to mail in your trade-in. This is only an estimate until we receive and appraise your device.",
      "warningMessage": null,
      "tradeInDeviceHeaderMsg": "You'll see an estimated $200.00 credit within 1-2 bill cycles.",
      "tradeInCredit": "-200.00",
      "tradeInSubmissionIdRequried": false,
      "tradeInSubmissionIdUrl": null,
      "tradeInDevices": [
        {
          "activeDevice": null,
          "tradeInCredit": "200.00",
          "tradeInDeviceFooter": null,
          "offerDetailsMsg": null,
          "tradeInDeviceHeaderMsg": null,
          "tradeInCreditMsg": "Trade-in credit: $200.00",
          "bicApplied": null,
          "color": "Black",
          "dataWipeText": null,
          "deviceBrand": null,
          "deviceId": "ID: 990004493548857",
          "discAmt": null,
          "disconnectedDate": null,
          "displayName": "Galaxy S 5",
          "dppCredit": "0.0",
          "dppAppliedCommerceItemId": null,
          "dppAppliedMdn": null,
          "errorMessage": null,
          "modalOsName": null,
          "modelImage": "https://ss7.vzw.com/is/image/VerizonWireless/Samsung_Galaxy_S5_Black?$device-lg$",
          "modelName": null,
          "mtn": null,
          "nickName": null,
          "originalAppraisalPrice": "27.00",
          "price": null,
          "promoCodeError": null,
          "promoCreditType": null,
          "promoQualifyMessage": null,
          "promoValue": null,
          "shortDisplayName": null,
          "size": "16GB",
          "success": true,
          "regularPromoApplied": null,
          "existingAppraisedReferenceId": null,
          "appraiseTradeInDeviceWithOutDeviceId": false,
          "flow": null,
          "submissionId": "22021702548"
        }
      ],
      "orginaltradeInCredit": null
    },
    "subOrders": null,
    "comboOrder": false,
    "totalDueToday": "56.65",
    "totalDueMonthly": "61.91",
    "subTotalDueToday": "0.00",
    "securityDepositAmount": "0.00",
    "stateSalesTax": "56.65",
    "employeeDiscount": "0.00",
    "pastDueExist": false,
    "pastDueAmountPaid": false,
    "pastDueAmount": "0.00",
    "shippingInfo": {
      "shippingInfoUpdated": false,
      "sameAsBilling": true,
      "ispuEligibleFlag": true,
      "addressInfo": {
        "firstName": "KENNY",
        "lastName": "NICKS",
        "companyName": null,
        "address1": "9433 244TH ST SW APT A303",
        "address2": null,
        "city": "Edmonds",
        "state": "WA",
        "zipcode": "98020",
        "businessName": null,
        "postalCode": null,
        "email": "SIVARAMCHANDHAR.VENKATACHALAPATHY@VERIZON.COM",
        "phoneNumber": "1019631140"
      },
      "contactInfo": {
        "emailAddress": "SIVARAMCHANDHAR.VENKATACHALAPATHY@VERIZON.COM",
        "phoneNumber": "1019631140",
        "firstName": "KENNY",
        "lastName": "NICKS",
        "smsMdn": null,
        "activeSMSCapableMtnList": [
          "2064915081",
          "4257808580",
          "4259671407",
          "9099535181"
        ]
      },
      "shippingTypesInfo": null,
      "storeDetail": {
        "storeHeader": null,
        "storeName": null,
        "storeAddress": null,
        "deviceAvailable": false,
        "distance": null,
        "appendedStoreTiming": null,
        "longitude": null,
        "storeId": null,
        "netaceLocationCode": null,
        "latitude": null,
        "seoUrlName": null,
        "storeClosingTime": null
      },
      "tradeIn": true,
      "tradeInAddress": {
        "firstName": "KENNY",
        "lastName": "NICKS",
        "address1": "9433 244TH ST SW APT A303",
        "address2": null,
        "city": "Edmonds",
        "state": "WA",
        "zipcode": "98020",
        "companyName": null
      },
      "nonSddEligibleMsg": null,
      "selectedSDDWindow": null,
      "poboMessage": null,
      "ispudetailsInfo": {
        "storeAddress": null,
        "storeHours": null,
        "storeId": null,
        "storeName": null,
        "phoneNumber": null,
        "distance": null,
        "totalItems": 0,
        "availItems": 0,
        "latitdude": 0,
        "longtitude": 0,
        "availItemName": null
      }
    },
    "billingInfo": {
      "billToAccountEligible": true,
      "creditCardZipEditable": false,
      "billingAddress": {
        "firstName": "KENNY",
        "lastName": "NICKS",
        "businessName": null,
        "zipcode": "98020",
        "state": "WA",
        "address2": null,
        "address1": "9433 244TH ST SW APT A303",
        "companyName": null,
        "city": "Edmonds",
        "sameAsShipping": false
      },
      "masterpass3DSecure": null,
      "billToAccountNumber": "#XXXXXXX-0001",
      "creditCardInfo": {
        "savedCardNickName": null,
        "preselectCard": null,
        "creditCardNumber": null,
        "creditCardExpMonth": null,
        "creditCardExpYear": null,
        "billingZipCode": null,
        "creditCardType": null,
        "creditCardVerificationNumber": null,
        "creditCardBIN": null,
        "cvvRequired": false
      },
      "selectedPaymentMode": "BTA",
      "giftCardList": [],
      "savedCardInfo": null,
      "applePayResponseInfo": null,
      "masterpassResponseInfo": {
        "emailAddress": null,
        "cardType": null,
        "lastDigits": null,
        "creditCardBIN": null
      },
      "masterpassError": false,
      "masterpassErrorMessage": null,
      "paypalEmailAddress": null,
      "expirationMonths": null,
      "expirationYears": null
    },
    "devices": {
      "dueMonthly": 61.91,
      "totalActivationFee": 0,
      "deviceTotalDueMonthly": 22.91,
      "dueToday": 0,
      "accessories": [],
      "accessoriesBundle": [],
      "items": [
        {
          "deviceName": "Pixel 2 XL",
          "dueMonthly": "22.91",
          "dueToday": "0.00",
          "upgradeFee": "0.00",
          "originalUpgradeFee": "0.00",
          "activationFee": "30.00",
          "dueTodayOriginal": "0.00",
          "dueMonthlyOriginal": "35.42",
          "dueTodayDiscounted": false,
          "dueMonthlyDiscounted": true,
          "mtn": null,
          "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/GOOGLE_Taiman_Wht?$device-med$&fmt=jpeg&wid=75&hei=150",
          "protectionFeature": {
            "name": "Total Mobile Protection Multi-Device",
            "mtn": null,
            "price": "39.00",
            "discountPrice": "0.00",
            "retailPrice": "0.00",
            "hasEcpdDiscount": false,
            "promoMessage": null,
            "originalPrice": "0.00",
            "wasPrice": "0.00",
            "deviceName": null,
            "color": null,
            "size": null,
            "introText": null,
            "smartFamily": false,
            "freeTrial": false,
            "instantCreditAmount": "0.00",
            "amountAfterInstantCredit": "0.00",
            "disountedInstantCreditAmt": "0.00",
            "tapfeature": true
          },
          "optionalFeatures": [],
          "installmentBalance": "549.99",
          "edgeRetailPrice": "849.99",
          "edgeItemDownPaymentAmount": "0.00",
          "mailInRebateAmount": "0.00",
          "transferredFromMtn": null,
          "devicePromotionList": [
            {
              "promotionalMessage": null,
              "promoDescription": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION BIC YES",
              "promoName": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION",
              "promoAmount": "300.00",
              "priceSubTitle": "1st installment will appear on your bill.",
              "barCodeId": null,
              "itemCode": "GA00152-US",
              "itemType": "ITA",
              "sedOffer": true,
              "isUpgradeFeeWaivedOffer": false,
              "promoContentText": null
            }
          ],
          "bicOfferApplied": false,
          "bicContractPrice": "0.00",
          "bicDiscountedContractPrice": "-1.00",
          "bicAdditionalContractText": null,
          "bicMessageMap": null,
          "edgeUpAmount": 0,
          "displayDeviceDueMonthly": 61.91,
          "deviceLACFee": "55.00",
          "manufactureName": "Google",
          "color": "Black and White",
          "colorCode": "#F5F5F5",
          "size": "64GB",
          "displayName": "Pixel 2 XL",
          "contractTerm": "99",
          "edgeUpBuyOutAmount": 0,
          "fullRetailPrice": "849.99",
          "alwaysEligibleForUpgrade": false,
          "numberShareDevice": false,
          "activationFeeText": "One-time activation fee of $30.00 charged to your next monthly bill.",
          "numberSharedMtn": null,
          "promoContentText": null,
          "itemOnJaxPlan": true,
          "humCarDetails": null,
          "simDetails": null,
          "imeiId": null,
          "displayImeiId": null,
          "poboDateLabel": null,
          "nickName": null,
          "planCommerceItemId": null,
          "displayMtn": null,
          "promoOfferText": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION",
          "promoApplied": true,
          "commerceItemId": "S925cdf411b04821730b1dfdca7e08b30{ss1}_device_1",
          "loanTerm": 24,
          "sbdHeaderMsg": null,
          "percentage": null,
          "waivedActivationFeePromo": false,
          "flow": "AAL",
          "accessory": false,
          "edgeDevice": true,
          "eupdevice": false,
          "instantCreditAmount": "0.00",
          "amountAfterInstantCredit": "0.00",
          "disountedInstantCreditAmt": "0.00"
        }
      ],
      "buddyUpgrade": false
    },
    "accessories": null,
    "selectedShippingType": {
      "type": "SHIPPING",
      "shippingTypeName": "FREE 2 Day by 8pm",
      "price": 0,
      "discountPrice": 0,
      "estimatedDeliveryDate": "2018-06-12 00:00:00"
    },
    "balanceCreditCardAmount": "56.65",
    "cpcOrder": false,
    "totalDueMonthlyPlanAndDevice": "116.91",
    "deviceConfigInfo": {
      "devices": [
        {
          "deviceId": "S925cdf411b04821730b1dfdca7e08b30{ss1}_device_1",
          "deviceName": "Pixel 2 XL",
          "deviceSetupMode": null,
          "mtnNumber": null,
          "flow": "AAL",
          "serviceAddress": {
            "firstName": "KENNY",
            "lastName": "NICKS",
            "address1": "9433 244TH ST SW APT A303",
            "address2": "",
            "city": "EDMONDS",
            "state": "WA",
            "zipCode": "98020",
            "emailAddress": "SIVARAMCHANDHAR.VENKATACHALAPATHY@VERIZON.COM",
            "phoneNumber": "1019631140"
          },
          "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/GOOGLE_Taiman_Wht?$device-med$&fmt=jpeg&wid=75&hei=150",
          "mobileAppImageName": "https://ss7.vzw.com/is/image/VerizonWireless/GOOGLE_Taiman_Wht?$device-lg$",
          "npaNxxnumber": "478-331-XXXX",
          "npnxxCustomerSelection": "new",
          "npaNxxdetails": null,
          "manufactureName": null,
          "color": null,
          "size": null,
          "numberShareDevice": false,
          "numberSharedMtn": null,
          "deviceNickName": null,
          "numberSharedDeviceName": null,
          "displayImeiId": null,
          "portInDetails": null
        }
      ],
      "npaNxxdetails": {
        "zipCode": null,
        "state": null,
        "city": null,
        "success": false,
        "mtns": null,
        "states": null,
        "cities": null
      },
      "deviceAddressUpdated": true,
      "accessories": null
    },
    "checkoutStates": {
      "shippingAddressRequired": false,
      "shippingAddressChangeRequired": false,
      "poBoxShippingAddress": false,
      "shippingAddressValidationError": false,
      "shippingMethodRequired": false,
      "paymentRequired": false,
      "pastDuePaymentRequired": false,
      "showPaymentSection": true,
      "showShippingAddress": true,
      "showDeliveryMethod": true,
      "newCard": false,
      "cvvNeeded": true,
      "contactInfoRequired": false
    },
    "totalEdgeItemDownPaymentAmount": "0.00",
    "totalEdgeUpAmount": "0.00",
    "totalEdgeUpBuyOutAmount": "0.00",
    "standaloneAccessories": false,
    "multiOrderDetails": null,
    "hasRio": false,
    "splitShipment": false,
    "isHLLPlanInOrder": false
  }
};