/*window.confirmationJSON = {
	"output": {
		"title": "You're all set.",
		"subtitle": null,
		"orderId": "156078871466110",
		"estimatedDelivery": "",
		"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/1.3_MV_BuyandUpgrade_ConfirmationPage_Interstital?$device-med$",
		"tradeInStatus": false,
		"confirmationMessage": "Thanks for ordering from verizonwireless.com. Your order receipt is sent to MEENA.KATADI@VERIZONWIRELESS.COM.",
		"doneButtonText": "Got it",
		"doneButtonLink": "/od/cust/auth/shoplanding/",
		"userNote": "TODO",
		"notNowButtonText": "TODO",
		"notNowButtonLink": "TODO",
		"learnHowButtonText": null,
		"learnHowButtonLink": "/od/cust/auth/learnHow",
		"numberOfDevice": 1,
		"confirmationNumberText": "Confirmation Number",
		"iconicFlow": true,
		"protectionURL": null,
		"accessoriesURL": null,
		"tapFlag": false,
		"cjmTagUrl": null,
		"pepperJamTagUrl": null,
		"selectedPaymentMode": null,
		"confirmationEmail": "MEENA.KATADI@VERIZONWIRELESS.COM",
		"shipToAddresss": null,
		"billToAddress": null,
		"deviceList": null,
		"planList": null,
		"plans": {
			"dueMonthly": null,
			"dueToday": null,
			"planOnlyDueMonthly": null,
			"items": [{
				"planType": null,
				"lineAccessCharges": null,
				"accountAccess": null,
				"accountLevelFeatures": null,
				"totalMonthlyPlanCost": null,
				"spoBadgeMessage": null,
				"planDisplayName": "",
				"planImageURL": null,
				"planLetter": null,
				"planDescrption": null,
				"planDescription": null,
				"quantity": 0,
				"skuId": "sku3060011",
				"productId": "plan5600003",
				"itemAmount": -1.7976931348623157E308,
				"itemAmountOriginal": 90.0,
				"dueMonthly": 0.0,
				"dueMonthlyOriginal": 0.0,
				"itemDiscount": 1.7976931348623157E308,
				"displayName": null,
				"skuDisplayName": null,
				"listPrice": 90.0,
				"rawTotalAmount": 0.0,
				"planGroupCode": null,
				"autoPayEnabled": false,
				"numberSharePlan": false,
				"planCommerceItemId": "Sa0b3a68b7d1925462076f8b3bc26408e{d3}_plan_1",
				"autoPayPrice": 0.0,
				"autoPayText": null,
				"termsAndConditionKey": null
			}, {
				"planType": null,
				""lineAccessCharges"": null,
				"accountAccess": null,
				"accountLevelFeatures": null,
				"totalMonthlyPlanCost": null,
				"spoBadgeMessage": null,
				"planDisplayName": "",
				"planImageURL": null,
				"planLetter": null,
				"planDescrption": null,
				"planDescription": null,
				"quantity": 0,
				"skuId": "sku3060015",
				"productId": "plan5720001",
				"itemAmount": 0.0,
				"itemAmountOriginal": 20.0,
				"dueMonthly": 0.0,
				"dueMonthlyOriginal": 0.0,
				"itemDiscount": 0.0,
				"displayName": null,
				"skuDisplayName": null,
				"listPrice": 20.0,
				"rawTotalAmount": 0.0,
				"planGroupCode": null,
				"autoPayEnabled": false,
				"numberSharePlan": false,
				"planCommerceItemId": "Sa0b3a68b7d1925462076f8b3bc26408e{d3}_plan_2",
				"autoPayPrice": 0.0,
				"autoPayText": null,
				"termsAndConditionKey": null
			}],
			"upgradeDevices": null,
			"newDevices": null,
			"existingDevices": [{
				"name": null,
				"price": "20.0",
				"discountPrice": 20.0,
				"hasEcpdDiscount": false,
				"mtn": "6159397769",
				"listPrice": 20.0,
				"deviceLineItemId": null,
				"discountPriceVal": null,
				"planCommerceItemId": "Sa0b3a68b7d1925462076f8b3bc26408e{d3}_plan_2",
				"nickName": "",
				"numberShareDevice": false,
				"featureDropped": false
			}],
			"dueMonthlyPlanWithLAC": null,
			"discountedDueMonthlyPlanWithLAC": null,
			"hasEcpdDiscount": false
		},
		"featureList": [{
			"id": "Sa0b3a68b7d1925462076f8b3bc26408e{d3}_feature_1",
			"quantity": 1,
			"type": "INSUR,D",
			"skuId": "sku401064",
			"productId": "sfo80072",
			"sorId": "66332",
			"itemAmount": 0.0,
			"itemAmountOriginal": 0.0,
			"dueMonthly": 0.0,
			"dueMonthlyOriginal": null,
			"itemDiscount": 0.0,
			"displayName": "Decline Equipment Protection",
			"skuDisplayName": null,
			"listPrice": 0.0,
			"rawTotalAmount": 0.0,
			"pricingDetails": [{
				"pricingAdjustmentId": null,
				"itemId": "Sa0b3a68b7d1925462076f8b3bc26408e{d3}_feature_1",
				"orderId": "Sa0b3a68b7d1925462076f8b3bc26408e{d3}",
				"offerId": null,
				"offerAmount": 0.0,
				"description": "List Price description",
				"offerType": null,
				"priceListId": null,
				"listPrice": 0.0,
				"offerName": null,
				"creationDate": 1526369559893,
				"lastModifiedDate": 1526369559893,
				"version": 1
			}],
			"orderId": "Sa0b3a68b7d1925462076f8b3bc26408e{d3}",
			"version": 1,
			"delete": false,
			"inventoryLevel": 0,
			"taxDetails": null,
			"itemTaxes": 0.0,
			"deviceLineItemId": "Sa0b3a68b7d1925462076f8b3bc26408e{d3}_device_1",
			"featureCharge": 0.0,
			"featureType": "INS",
			"lastModifiedDate": 1526369555946
		}],
		"accessoryList": null,
		"paymentGroup": null,
		"contactInfo": {
			"id": null,
			"emailAddress": "MEENA.KATADI@VERIZONWIRELESS.COM",
			"phoneNumber": "9999999999",
			"lastName": "JONES",
			"firstName": "EDWARD",
			"zipCode": "37160",
			"orderId": null,
			"userId": null,
			"npaNxxNumber": null,
			"address1": "3540 HWY 231 NORTH APT WH6",
			"address2": null,
			"city": "Shelbyville",
			"state": "TN",
			"addressVerified": true,
			"textAlertOptin": false,
			"newsLetterOptin": false,
			"paperFreeBillingIndicatorFlag": false,
			"middleName": null,
			"firmName": null,
			"businessName": null,
			"apartmentNum": "WH6",
			"addressDirection": "N",
			"poBox": "",
			"streetNumber": "3540",
			"streetName": "HIGHWAY 231",
			"streetType": "",
			"ruralRoute": null,
			"ruralDel": "",
			"zipCode4": null,
			"zipCode5": null,
			"faxNumber": null,
			"addressType": null,
			"country": "",
			"prefix": null,
			"suffix": null,
			"postbox": null,
			"companyname": null,
			"ruralrte": "",
			"county": null,
			"address3": null,
			"postalcode": "37160",
			"version": 0,
			"lastModifiedDate": null,
			"addressConfirmationStatus": null
		},
		"tradeInDevicesDetails": null,
		"tradeInPromoDetails": null,
		"transformedTradeInPromoDetails": null,
		"subOrders": null,
		"comboOrder": false,
		"totalDueToday": "219.78",
		"totalDueMonthly": "10.41",
		"subTotalDueToday": "162.48",
		"securityDepositAmount": "0.00",
		"stateSalesTax": "27.30",
		"employeeDiscount": "219.78",
		"pastDueExist": false,
		"pastDueAmountPaid": false,
		"pastDueAmount": "0.00",
		"shippingInfo": {
			"shippingInfoUpdated": false,
			"sameAsBilling": true,
			"ispuEligibleFlag": true,
			"addressInfo": {
				"firstName": "EDWARD",
				"lastName": "JONES",
				"companyName": null,
				"address1": "3540 HWY 231 NORTH APT WH6",
				"address2": null,
				"city": "Shelbyville",
				"state": "TN",
				"zipcode": "37160",
				"businessName": null,
				"postalCode": null,
				"email": "MEENA.KATADI@VERIZONWIRELESS.COM",
				"phoneNumber": "9999999999"
			},
			"contactInfo": {
				"emailAddress": "MEENA.KATADI@VERIZONWIRELESS.COM",
				"phoneNumber": "9999999999",
				"firstName": "EDWARD",
				"lastName": "JONES",
				"smsMdn": null,
				"activeSMSCapableMtnList": ["6159397769", "4236372140"]
			},
			"shippingTypesInfo": [{
				"estimatedDeliveryDate": "2018-05-17 00:00:00",
				"estimatedDeliveryDateText": "Thu 5/17",
				"shippingDescription": "Free 2 Day by 8pm",
				"shippingOptionId": "SHP002",
				"shippingCost": "0.00",
				"shortDescription": "Free 2 Day by 8pm",
				"active": true,
				"addedShippingOptionId": true,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Thu, May 17 if ordered by 4pm today. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}, {
				"estimatedDeliveryDate": "2018-05-16 00:00:00",
				"estimatedDeliveryDateText": "Wed 5/16",
				"shippingDescription": "Next Day by 8pm",
				"shippingOptionId": "SHP004",
				"shippingCost": "12.99",
				"shortDescription": "Next Day by 8pm",
				"active": true,
				"addedShippingOptionId": false,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Wed, May 16. Next Day by 8pm. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}, {
				"estimatedDeliveryDate": "2018-05-16 10:30:00",
				"estimatedDeliveryDateText": "Wed 5/16 by 10:30AM",
				"shippingDescription": "Next Day by 10:30am",
				"shippingOptionId": "SHP005",
				"shippingCost": "14.99",
				"shortDescription": "Next Day by 10:30am",
				"active": true,
				"addedShippingOptionId": false,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Wed, May 16. Next Day by 10:30am. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}],
			"storeDetail": {
				"storeHeader": null,
				"storeName": null,
				"storeAddress": null,
				"deviceAvailable": false,
				"distance": null,
				"appendedStoreTiming": null,
				"longitude": null,
				"storeId": null,
				"netaceLocationCode": null,
				"latitude": null,
				"seoUrlName": null,
				"storeClosingTime": null
			},
			"tradeIn": false,
			"tradeInAddress": null,
			"nonSddEligibleMsg": null,
			"selectedSDDWindow": null,
			"poboMessage": null,
			"ispudetailsInfo": {
				"storeAddress": null,
				"storeHours": null,
				"storeId": null,
				"storeName": null,
				"phoneNumber": null,
				"distance": null,
				"totalItems": 0,
				"availItems": 0,
				"latitdude": 0.0,
				"longtitude": 0.0,
				"availItemName": null
			}
		},
		"billingInfo": {
			"billToAccountEligible": false,
			"creditCardZipEditable": false,
			"billingAddress": {
				"firstName": "EDWARD",
				"lastName": "JONES",
				"businessName": null,
				"zipcode": "37160",
				"state": "TN",
				"address2": null,
				"address1": "3540 HWY 231 NORTH APT WH6",
				"companyName": null,
				"city": "Shelbyville"
			},
			"masterpass3DSecure": null,
			"billToAccountNumber": null,
			"creditCardInfo": {
				"savedCardNickName": null,
				"preselectCard": null,
				"creditCardNumber": "XXXX XXXX XXXX-0002",
				"creditCardExpMonth": "01",
				"creditCardExpYear": "2020",
				"billingZipCode": null,
				"creditCardType": "visa",
				"creditCardVerificationNumber": null,
				"creditCardBIN": null,
				"cvvRequired": false
			},
			"selectedPaymentMode": "newCard",
			"giftCardList": [],
			"savedCardInfo": [],
			"applePayResponseInfo": null,
			"masterpassResponseInfo": {
				"emailAddress": null,
				"cardType": null,
				"lastDigits": null,
				"creditCardBIN": null
			},
			"masterpassError": false,
			"masterpassErrorMessage": null,
			"paypalEmailAddress": null,
			"expirationMonths": ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
			"expirationYears": ["2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027"]
		},
		"devices": {
			"dueMonthly": 10.41,
			"totalActivationFee": 0.0,
			"deviceTotalDueMonthly": 10.41,
			"dueToday": 0.0,
			"accessories": [],
			"accessoriesBundle": [],
			"items": [{
				"deviceName": "iPhone&reg; 7",
				"dueMonthly": "10.41",
				"dueToday": "0.00",
				"upgradeFee": "30.00",
				"activationFee": "0.00",
				"dueTodayOriginal": "0.00",
				"dueMonthlyOriginal": "22.92",
				"dueTodayDiscounted": false,
				"dueMonthlyDiscounted": true,
				"mtn": "4236372140",
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-med$&fmt=jpeg&wid=75&hei=150",
				"protectionFeature": {
					"name": "Decline Equipment Protection",
					"mtn": null,
					"price": "0.00",
					"discountPrice": "0.00",
					"retailPrice": "0.00",
					"hasEcpdDiscount": false,
					"promoMessage": null,
					"originalPrice": "0.00",
					"wasPrice": "0.00",
					"deviceName": null,
					"color": null,
					"size": null,
					"instantCreditAmount": "0.00",
					"amountAfterInstantCredit": "0.00",
					"disountedInstantCreditAmt": "0.00"
				},
				"optionalFeatures": [],
				"installmentBalance": "249.99",
				"edgeRetailPrice": "549.99",
				"edgeItemDownPaymentAmount": "0.00",
				"mailInRebateAmount": "0.00",
				"transferredFromMtn": null,
				"devicePromotionList": [{
					"promotionalMessage": null,
					"promoDescription": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION BIC YES",
					"promoName": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION",
					"promoAmount": "300.00",
					"priceSubTitle": "1st installment will appear on your bill.",
					"barCodeId": null,
					"itemCode": "MNAE2LL/A",
					"itemType": "ITA",
					"sedOffer": true,
					"promoContentText": null
				}],
				"bicOfferApplied": false,
				"bicContractPrice": "0.00",
				"bicDiscountedContractPrice": "-1.00",
				"bicAdditionalContractText": null,
				"bicMessageMap": null,
				"edgeUpAmount": 0.0,
				"displayDeviceDueMonthly": 10.41,
				"deviceLACFee": "0.00",
				"manufactureName": "Apple",
				"color": "Gold",
				"colorCode": "#CFBEA9",
				"size": "32GB",
				"displayName": "iPhone&reg; 7",
				"contractTerm": "99",
				"edgeUpBuyOutAmount": 162.48,
				"fullRetailPrice": "549.99",
				"alwaysEligibleForUpgrade": false,
				"numberShareDevice": false,
				"activationFeeText": null,
				"numberSharedMtn": null,
				"promoContentText": null,
				"itemOnJaxPlan": false,
				"humCarDetails": null,
				"simDetails": null,
				"imeiId": null,
				"displayImeiId": null,
				"poboDateLabel": null,
				"nickName": null,
				"planCommerceItemId": null,
				"displayMtn": null,
				"promoOfferText": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION",
				"promoApplied": true,
				"commerceItemId": "Sa0b3a68b7d1925462076f8b3bc26408e{d3}_device_1",
				"loanTerm": 24,
				"sbdHeaderMsg": null,
				"percentage": null,
				"waivedActivationFeePromo": false,
				"flow": "EUP",
				"edgeDevice": true,
				"instantCreditAmount": "0.00",
				"amountAfterInstantCredit": "0.00",
				"eupdevice": false,
				"accessory": false,
				"disountedInstantCreditAmt": "0.00"
			}],
			"buddyUpgrade": false
		},
		"accessories": null,
		"selectedShippingType": {
			"type": "SHIPPING",
			"shippingTypeName": "FREE 2 Day by 8pm",
			"price": 0.0,
			"discountPrice": 0.0,
			"estimatedDeliveryDate": null
		},
		"dueMonthlyView": {
			"title": "Due Monthly (device only)",
			"dueMonthlyPrice": "10.41",
			"items": [{
				"name": "iPhone&reg; 7",
				"description": "iPhone&reg; 7",
				"manufacturer": "Apple",
				"color": "Gold",
				"size": "32GB",
				"priceBreakDown": [{
					"lable": "Line Access Charge",
					"price": "0.00",
					"description": null,
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 0.0,
					"itemStrikeThroughPrice": 0.0,
					"noOfBicOccurences": 0
				}, {
					"lable": "Decline Equipment Protection",
					"price": "0.00",
					"description": null,
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 0.0,
					"itemStrikeThroughPrice": 0.0,
					"noOfBicOccurences": 0
				}, {
					"lable": "Device Payment",
					"price": "10.41",
					"description": "For 24 months, 0% APR with down payment. Reduced retail price: <span class='textDecLineThrough red'>$549.99</span> $249.99",
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 10.41,
					"itemStrikeThroughPrice": 22.92,
					"noOfBicOccurences": 0
				}],
				"nickName": null,
				"planCommerceItemId": null,
				"displayMtn": "4236372140",
				"numberShareDevice": false,
				"edge": true
			}],
			"tmpMd": null
		},
		"balanceCreditCardAmount": "219.78",
		"cpcOrder": true,
		"totalDueMonthlyPlanAndDevice": "10.41",
		"deviceConfigInfo": {
			"devices": [{
				"deviceId": "Sa0b3a68b7d1925462076f8b3bc26408e{d3}_device_1",
				"deviceName": "iPhone&reg; 7",
				"deviceSetupMode": null,
				"mtnNumber": "4236372140",
				"flow": "EUP",
				"serviceAddress": {
					"firstName": "EDWARD",
					"lastName": "JONES",
					"address1": "3540 HWY 231 NORTH APT WH6",
					"address2": "",
					"city": "Shelbyville",
					"state": "TN",
					"zipCode": "37160",
					"emailAddress": "MEENA.KATADI@VERIZONWIRELESS.COM",
					"phoneNumber": "9999999999"
				},
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-med$&fmt=jpeg&wid=75&hei=150",
				"mobileAppImageName": null,
				"npaNxxnumber": null,
				"npnxxCustomerSelection": null,
				"npaNxxdetails": null,
				"manufactureName": "Apple",
				"color": "Gold",
				"size": "32GB",
				"numberShareDevice": false,
				"numberSharedMtn": null,
				"portInDetails": null
			}],
			"npaNxxdetails": {
				"zipCode": null,
				"state": null,
				"city": null,
				"success": false,
				"mtns": null,
				"states": null,
				"cities": null
			},
			"deviceAddressUpdated": false,
			"accessories": null
		},
		"checkoutStates": {
			"shippingAddressRequired": false,
			"shippingAddressChangeRequired": false,
			"shippingMethodRequired": false,
			"paymentRequired": false,
			"pastDuePaymentRequired": false,
			"showPaymentSection": true,
			"showShippingAddress": true,
			"showDeliveryMethod": true,
			"newCard": false,
			"cvvNeeded": false
		},
		"totalEdgeItemDownPaymentAmount": "0.00",
		"totalEdgeUpAmount": "0.00",
		"totalEdgeUpBuyOutAmount": "162.48",
		"multiOrderDetails": null,
		"hasRio": false,
		"splitShipment": false
	}
};*/
window.confirmationJSON = {
	"output": {
		"title": "You're all set.",
		"subtitle": null,
		"orderId": "924232121099955",
		"estimatedDelivery": "",
		"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/1.3_MV_BuyandUpgrade_ConfirmationPage_Interstital?$device-med$",
		"tradeInStatus": false,
		"confirmationMessage": "Thanks for ordering from verizonwireless.com. Your order receipt is sent to VZW@VZW.COM.",
		"doneButtonText": "Got it",
		"doneButtonLink": "/od/cust/auth/shoplanding/",
		"userNote": "TODO",
		"notNowButtonText": "TODO",
		"notNowButtonLink": "TODO",
		"learnHowButtonText": null,
		"learnHowButtonLink": "/od/cust/auth/learnHow",
		"numberOfDevice": 0,
		"confirmationNumberText": "Confirmation Number",
		"iconicFlow": true,
		"protectionURL": null,
		"accessoriesURL": null,
		"tapFlag": false,
		"cjmTagUrl": null,
		"pepperJamTagUrl": null,
		"selectedPaymentMode": null,
		"confirmationEmail": "VZW@VZW.COM",
		"shipToAddresss": null,
		"billToAddress": null,
		"deviceList": null,
		"planList": null,
		"plans": {
			"dueMonthly": null,
			"dueToday": null,
			"planOnlyDueMonthly": null,
			"items": [{
				"planType": null,
				"lineAccessCharges": null,
				"accountAccess": null,
				"accountLevelFeatures": null,
				"totalMonthlyPlanCost": null,
				"spoBadgeMessage": null,
				"planDisplayName": "",
				"planImageURL": null,
				"planLetter": null,
				"planDescrption": null,
				"planDescription": null,
				"quantity": 0,
				"skuId": "sku3060010",
				"productId": "plan5600003",
				"itemAmount": 0.0,
				"itemAmountOriginal": 40.0,
				"dueMonthly": 0.0,
				"dueMonthlyOriginal": 0.0,
				"itemDiscount": 0.0,
				"displayName": null,
				"skuDisplayName": null,
				"listPrice": 40.0,
				"rawTotalAmount": 0.0,
				"planGroupCode": null,
				"autoPayEnabled": false,
				"numberSharePlan": false,
				"planCommerceItemId": "S382ee9ccd1c01e2a9b83422ad8fbadbd{d4}_plan_1",
				"autoPayPrice": 0.0,
				"autoPayText": null,
				"termsAndConditionKey": null
			}],
			"upgradeDevices": null,
			"newDevices": null,
			"existingDevices": [],
			"dueMonthlyPlanWithLAC": null,
			"discountedDueMonthlyPlanWithLAC": null,
			"hasEcpdDiscount": false
		},
		"featureList": [{
			"id": "S382ee9ccd1c01e2a9b83422ad8fbadbd{d4}_feature_1",
			"quantity": 1,
			"type": "INSUR,D",
			"skuId": "sku401064",
			"productId": "sfo80072",
			"sorId": "66332",
			"itemAmount": 0.0,
			"itemAmountOriginal": 0.0,
			"dueMonthly": 0.0,
			"dueMonthlyOriginal": null,
			"itemDiscount": 0.0,
			"displayName": "Decline Equipment Protection",
			"skuDisplayName": null,
			"listPrice": 0.0,
			"rawTotalAmount": 0.0,
			"pricingDetails": [{
				"pricingAdjustmentId": null,
				"itemId": "S382ee9ccd1c01e2a9b83422ad8fbadbd{d4}_feature_1",
				"orderId": "S382ee9ccd1c01e2a9b83422ad8fbadbd{d4}",
				"offerId": null,
				"offerAmount": 0.0,
				"description": "List Price description",
				"offerType": null,
				"priceListId": null,
				"listPrice": 0.0,
				"offerName": null,
				"creationDate": 1526386179012,
				"lastModifiedDate": 1526386179012,
				"version": 1
			}],
			"orderId": "S382ee9ccd1c01e2a9b83422ad8fbadbd{d4}",
			"version": 1,
			"delete": false,
			"inventoryLevel": 0,
			"taxDetails": null,
			"itemTaxes": 0.0,
			"deviceLineItemId": "S382ee9ccd1c01e2a9b83422ad8fbadbd{d4}_device_1",
			"featureCharge": 0.0,
			"featureType": "INS",
			"lastModifiedDate": 1526386176954
		}],
		"accessoryList": [{
			"id": "S382ee9ccd1c01e2a9b83422ad8fbadbd{d4}_accessory_1",
			"quantity": 1,
			"type": null,
			"skuId": "sku2310063",
			"productId": "10000001",
			"sorId": null,
			"itemAmount": 144.97,
			"itemAmountOriginal": 0.0,
			"dueMonthly": 0.0,
			"dueMonthlyOriginal": null,
			"itemDiscount": 0.0,
			"displayName": "Defender Power & Protection Bundle for iPhone 7 Plus",
			"skuDisplayName": null,
			"listPrice": 144.97,
			"rawTotalAmount": 144.97,
			"pricingDetails": [{
				"pricingAdjustmentId": null,
				"itemId": "S382ee9ccd1c01e2a9b83422ad8fbadbd{d4}_accessory_1",
				"orderId": "S382ee9ccd1c01e2a9b83422ad8fbadbd{d4}",
				"offerId": null,
				"offerAmount": 0.0,
				"description": "List Price description",
				"offerType": null,
				"priceListId": null,
				"listPrice": 144.97,
				"offerName": null,
				"creationDate": 1526386179012,
				"lastModifiedDate": 1526386179012,
				"version": 1
			}],
			"orderId": "S382ee9ccd1c01e2a9b83422ad8fbadbd{d4}",
			"version": 1,
			"delete": false,
			"inventoryLevel": 0,
			"taxDetails": null,
			"itemTaxes": 0.0,
			"deviceLineItemId": "S382ee9ccd1c01e2a9b83422ad8fbadbd{d4}_device_1",
			"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphone7-plus-defender-power-protection-bundle-15885-gg-bundle-iset?$acc-med$",
			"bogoType": null,
			"recycleStateInd": null,
			"color": null,
			"size": null,
			"capacity": null,
			"lastModifiedDate": 1526386177090,
			"deviceManufacturerName": null,
			"accessoryType": "BUNDLE_ACCESSORIES",
			"ispuEligibleFlag": true,
			"bundleSkuLineItems": [{
				"brand": "",
				"displayName": "Symmetry Clear Series Case for iPhone 7 Plus - Clear",
				"capacity": 10,
				"productID": "sku2120010",
				"skuDetails": [{
					"id": "sku2120010",
					"quantity": 1,
					"type": null,
					"skuId": "sku2120010",
					"productId": null,
					"sorId": "77-54181",
					"itemAmount": 49.99,
					"itemAmountOriginal": 0.0,
					"dueMonthly": 0.0,
					"dueMonthlyOriginal": null,
					"itemDiscount": 0.0,
					"displayName": "Symmetry Clear Series Case for iPhone 7 Plus - Clear",
					"skuDisplayName": "OtterBox Symmetry Series clear for iPhone 7 Plus - Clear",
					"listPrice": 49.99,
					"rawTotalAmount": 49.99,
					"pricingDetails": [{
						"pricingAdjustmentId": null,
						"itemId": "sku2120010",
						"orderId": null,
						"offerId": null,
						"offerAmount": 0.0,
						"description": "List Price description",
						"offerType": null,
						"priceListId": null,
						"listPrice": 49.99,
						"offerName": null,
						"creationDate": 1526386179012,
						"lastModifiedDate": 1526386179012,
						"version": 1
					}],
					"orderId": null,
					"version": 0,
					"delete": false,
					"inventoryLevel": 0,
					"taxDetails": [{
						"taxLineItemId": null,
						"lineItemId": "sku2120010",
						"itemType": "accessory",
						"sorSkuId": "77-54181",
						"taxType": "taxes_fees",
						"taxAmount": 3.44,
						"taxDescription": "NJ State Sales Tax",
						"version": 0,
						"orderId": null,
						"createdDate": 1526386216912
					}],
					"itemTaxes": 3.44,
					"deviceLineItemId": null,
					"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/otterbox-symmetry-clear-series-case-iphone-6s-plus-clear-77-54181-iset?$acc-med$",
					"bogoType": null,
					"recycleStateInd": null,
					"color": false,
					"size": null,
					"capacity": null,
					"lastModifiedDate": null,
					"deviceManufacturerName": null,
					"accessoryType": null,
					"ispuEligibleFlag": false,
					"bundleSkuLineItems": null,
					"bundleDesciption": null,
					"vzwSbdOfferlist": [],
					"promotions": null,
					"purchasePath": null,
					"appleCare": false,
					"expectedShippingDate": null,
					"shipCommitInd": null,
					"sameDayDelivery": false,
					"recycleCreditAllocatedAmount": 0.0,
					"ecpdItemAmount": null,
					"ecpdItemDiscount": 0.0,
					"standaloneaccessory": false,
					"batteryAccessory": false,
					"accSeoUrl": null,
					"featureDropped": false,
					"name": "Symmetry Clear Series Case for iPhone 7 Plus - Clear",
					"price": "49.99",
					"discountedPrice": "0.0",
					"preSelected": false,
					"comingSoonAcc": false,
					"inCart": false,
					"learnMoreLink": "/od/cust/auth/accessoryDetails/?accProdId=acc6640010",
					"discount_price": null,
					"available": false
				}]
			}, {
				"brand": "",
				"displayName": "InvisibleShield Privacy Glass+ for iPhone 6 Plus/6s Plus/7 Plus",
				"capacity": 10,
				"productID": "sku2120275",
				"skuDetails": [{
					"id": "sku2120275",
					"quantity": 1,
					"type": null,
					"skuId": "sku2120275",
					"productId": null,
					"sorId": "I7LGPC-F00",
					"itemAmount": 44.99,
					"itemAmountOriginal": 0.0,
					"dueMonthly": 0.0,
					"dueMonthlyOriginal": null,
					"itemDiscount": 0.0,
					"displayName": "InvisibleShield Privacy Glass+ for iPhone 8 Plus/7 Plus/6s Plus/6 Plus",
					"skuDisplayName": "ZAGG InvisibleShield Privacy Glass for iP8/iP7/iP6/iP6s Plus",
					"listPrice": 44.99,
					"rawTotalAmount": 44.99,
					"pricingDetails": [{
						"pricingAdjustmentId": null,
						"itemId": "sku2120275",
						"orderId": null,
						"offerId": null,
						"offerAmount": 0.0,
						"description": "List Price description",
						"offerType": null,
						"priceListId": null,
						"listPrice": 44.99,
						"offerName": null,
						"creationDate": 1526386179012,
						"lastModifiedDate": 1526386179012,
						"version": 1
					}],
					"orderId": null,
					"version": 0,
					"delete": false,
					"inventoryLevel": 0,
					"taxDetails": [{
						"taxLineItemId": null,
						"lineItemId": "sku2120275",
						"itemType": "accessory",
						"sorSkuId": "I7LGPC-F00",
						"taxType": "taxes_fees",
						"taxAmount": 3.09,
						"taxDescription": "NJ State Sales Tax",
						"version": 0,
						"orderId": null,
						"createdDate": 1526386216912
					}],
					"itemTaxes": 3.09,
					"deviceLineItemId": null,
					"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/invisibleshield-privacy-glass-for-iphone-6-plus-6s-plus-7-plus-i7lgpc-f00-iset?$acc-med$",
					"bogoType": null,
					"recycleStateInd": null,
					"color": false,
					"size": null,
					"capacity": null,
					"lastModifiedDate": null,
					"deviceManufacturerName": null,
					"accessoryType": null,
					"ispuEligibleFlag": false,
					"bundleSkuLineItems": null,
					"bundleDesciption": null,
					"vzwSbdOfferlist": [],
					"promotions": null,
					"purchasePath": null,
					"appleCare": false,
					"expectedShippingDate": null,
					"shipCommitInd": null,
					"sameDayDelivery": false,
					"recycleCreditAllocatedAmount": 0.0,
					"ecpdItemAmount": null,
					"ecpdItemDiscount": 0.0,
					"standaloneaccessory": false,
					"batteryAccessory": false,
					"accSeoUrl": null,
					"featureDropped": false,
					"name": "InvisibleShield Privacy Glass+ for iPhone 8 Plus/7 Plus/6s Plus/6 Plus",
					"price": "44.99",
					"discountedPrice": "0.0",
					"preSelected": false,
					"comingSoonAcc": false,
					"inCart": false,
					"learnMoreLink": "/od/cust/auth/accessoryDetails/?accProdId=acc6640217",
					"discount_price": null,
					"available": false
				}]
			}, {
				"brand": "",
				"displayName": "powerstation 6000 - Space Gray",
				"capacity": 10,
				"productID": "sku2090609",
				"skuDetails": [{
					"id": "sku2090609",
					"quantity": 1,
					"type": null,
					"skuId": "sku2090609",
					"productId": null,
					"sorId": "MOPHPS62GRY",
					"itemAmount": 49.99,
					"itemAmountOriginal": 0.0,
					"dueMonthly": 0.0,
					"dueMonthlyOriginal": null,
					"itemDiscount": 0.0,
					"displayName": "powerstation 6000 - Space Gray",
					"skuDisplayName": "mophie powerstation 6000 - Space Gray",
					"listPrice": 49.99,
					"rawTotalAmount": 49.99,
					"pricingDetails": [{
						"pricingAdjustmentId": null,
						"itemId": "sku2090609",
						"orderId": null,
						"offerId": null,
						"offerAmount": 0.0,
						"description": "List Price description",
						"offerType": null,
						"priceListId": null,
						"listPrice": 49.99,
						"offerName": null,
						"creationDate": 1526386179012,
						"lastModifiedDate": 1526386179012,
						"version": 1
					}],
					"orderId": null,
					"version": 0,
					"delete": false,
					"inventoryLevel": 0,
					"taxDetails": [{
						"taxLineItemId": null,
						"lineItemId": "sku2090609",
						"itemType": "accessory",
						"sorSkuId": "MOPHPS62GRY",
						"taxType": "taxes_fees",
						"taxAmount": 3.44,
						"taxDescription": "NJ State Sales Tax",
						"version": 0,
						"orderId": null,
						"createdDate": 1526386216912
					}],
					"itemTaxes": 3.44,
					"deviceLineItemId": null,
					"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/mophie-powerstation-6200-space-gray-mophps62gry-iset?$acc-med$",
					"bogoType": null,
					"recycleStateInd": null,
					"color": false,
					"size": null,
					"capacity": null,
					"lastModifiedDate": null,
					"deviceManufacturerName": null,
					"accessoryType": null,
					"ispuEligibleFlag": false,
					"bundleSkuLineItems": null,
					"bundleDesciption": null,
					"vzwSbdOfferlist": [],
					"promotions": null,
					"purchasePath": null,
					"appleCare": false,
					"expectedShippingDate": null,
					"shipCommitInd": null,
					"sameDayDelivery": false,
					"recycleCreditAllocatedAmount": 0.0,
					"ecpdItemAmount": null,
					"ecpdItemDiscount": 0.0,
					"standaloneaccessory": false,
					"batteryAccessory": false,
					"accSeoUrl": null,
					"featureDropped": false,
					"name": "powerstation 6000 - Space Gray",
					"price": "49.99",
					"discountedPrice": "0.0",
					"preSelected": false,
					"comingSoonAcc": false,
					"inCart": false,
					"learnMoreLink": "/od/cust/auth/accessoryDetails/?accProdId=acc6520126",
					"discount_price": null,
					"available": false
				}]
			}],
			"bundleDesciption": null,
			"vzwSbdOfferlist": null,
			"promotions": null,
			"purchasePath": "EUP",
			"appleCare": false,
			"expectedShippingDate": null,
			"shipCommitInd": null,
			"sameDayDelivery": false,
			"recycleCreditAllocatedAmount": 0.0,
			"ecpdItemAmount": null,
			"ecpdItemDiscount": 0.0,
			"standaloneaccessory": false,
			"batteryAccessory": false,
			"accSeoUrl": "",
			"featureDropped": false
		}],
		"paymentGroup": null,
		"contactInfo": {
			"id": null,
			"emailAddress": "VZW@VZW.COM",
			"phoneNumber": "9464436332",
			"lastName": "SMITH",
			"firstName": "BOB",
			"zipCode": "07107",
			"orderId": null,
			"userId": null,
			"npaNxxNumber": null,
			"address1": "250 GEORGIA KING VLG APT 15G",
			"address2": null,
			"city": "Newark",
			"state": "NJ",
			"addressVerified": true,
			"textAlertOptin": false,
			"newsLetterOptin": false,
			"paperFreeBillingIndicatorFlag": false,
			"middleName": null,
			"firmName": null,
			"businessName": null,
			"apartmentNum": "15G",
			"addressDirection": "",
			"poBox": "",
			"streetNumber": "250",
			"streetName": "GEORGIA KING",
			"streetType": "VL",
			"ruralRoute": null,
			"ruralDel": "",
			"zipCode4": null,
			"zipCode5": null,
			"faxNumber": null,
			"addressType": null,
			"country": "",
			"prefix": null,
			"suffix": null,
			"postbox": null,
			"companyname": null,
			"ruralrte": "",
			"county": null,
			"address3": null,
			"postalcode": "07107",
			"version": 0,
			"lastModifiedDate": null,
			"addressConfirmationStatus": null
		},
		"tradeInDevicesDetails": null,
		"tradeInPromoDetails": null,
		"transformedTradeInPromoDetails": null,
		"subOrders": null,
		"comboOrder": false,
		"totalDueToday": "212.44",
		"totalDueMonthly": "55.41",
		"subTotalDueToday": "144.97",
		"securityDepositAmount": "0.00",
		"stateSalesTax": "37.47",
		"employeeDiscount": "212.44",
		"pastDueExist": false,
		"pastDueAmountPaid": false,
		"pastDueAmount": "0.00",
		"shippingInfo": {
			"shippingInfoUpdated": false,
			"sameAsBilling": true,
			"ispuEligibleFlag": true,
			"addressInfo": {
				"firstName": "BOB",
				"lastName": "SMITH",
				"companyName": null,
				"address1": "250 GEORGIA KING VLG APT 15G",
				"address2": null,
				"city": "Newark",
				"state": "NJ",
				"zipcode": "07107",
				"businessName": null,
				"postalCode": null,
				"email": "VZW@VZW.COM",
				"phoneNumber": "9464436332"
			},
			"contactInfo": {
				"emailAddress": "VZW@VZW.COM",
				"phoneNumber": "9464436332",
				"firstName": "BOB",
				"lastName": "SMITH",
				"smsMdn": null,
				"activeSMSCapableMtnList": ["8622362409", "8622722534", "8627041232", "9735293955"]
			},
			"shippingTypesInfo": [{
				"estimatedDeliveryDate": "2018-05-17 00:00:00",
				"estimatedDeliveryDateText": "Thu 5/17",
				"shippingDescription": "Free 2 Day by 8pm",
				"shippingOptionId": "SHP002",
				"shippingCost": "0.00",
				"shortDescription": "Free 2 Day by 8pm",
				"active": true,
				"addedShippingOptionId": true,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Thu, May 17 if ordered by 4pm today. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}, {
				"estimatedDeliveryDate": "2018-05-16 00:00:00",
				"estimatedDeliveryDateText": "Wed 5/16",
				"shippingDescription": "Next Day by 8pm",
				"shippingOptionId": "SHP004",
				"shippingCost": "12.99",
				"shortDescription": "Next Day by 8pm",
				"active": true,
				"addedShippingOptionId": false,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Wed, May 16. Next Day by 8pm. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}, {
				"estimatedDeliveryDate": "2018-05-16 10:30:00",
				"estimatedDeliveryDateText": "Wed 5/16 by 10:30AM",
				"shippingDescription": "Next Day by 10:30am",
				"shippingOptionId": "SHP005",
				"shippingCost": "14.99",
				"shortDescription": "Next Day by 10:30am",
				"active": true,
				"addedShippingOptionId": false,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Wed, May 16. Next Day by 10:30am. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}],
			"storeDetail": {
				"storeHeader": null,
				"storeName": null,
				"storeAddress": null,
				"deviceAvailable": false,
				"distance": null,
				"appendedStoreTiming": null,
				"longitude": null,
				"storeId": null,
				"netaceLocationCode": null,
				"latitude": null,
				"seoUrlName": null,
				"storeClosingTime": null
			},
			"tradeIn": false,
			"tradeInAddress": null,
			"nonSddEligibleMsg": null,
			"selectedSDDWindow": null,
			"poboMessage": null,
			"ispudetailsInfo": {
				"storeAddress": null,
				"storeHours": null,
				"storeId": null,
				"storeName": null,
				"phoneNumber": null,
				"distance": null,
				"totalItems": 0,
				"availItems": 0,
				"latitdude": 0.0,
				"longtitude": 0.0,
				"availItemName": null
			}
		},
		"billingInfo": {
			"billToAccountEligible": true,
			"creditCardZipEditable": true,
			"billingAddress": {
				"firstName": "BOB",
				"lastName": "SMITH",
				"businessName": null,
				"zipcode": "07107",
				"state": "NJ",
				"address2": null,
				"address1": "250 GEORGIA KING VLG APT 15G",
				"companyName": null,
				"city": "Newark"
			},
			"masterpass3DSecure": null,
			"billToAccountNumber": "#XXXXXXX-0001",
			"creditCardInfo": {
				"savedCardNickName": null,
				"preselectCard": null,
				"creditCardNumber": null,
				"creditCardExpMonth": null,
				"creditCardExpYear": null,
				"billingZipCode": null,
				"creditCardType": null,
				"creditCardVerificationNumber": null,
				"creditCardBIN": null,
				"cvvRequired": false
			},
			"selectedPaymentMode": "BTA",
			"giftCardList": [],
			"savedCardInfo": [{
				"savedCardNickName": "BOGUS",
				"preselectCard": null,
				"creditCardNumber": "XXXX-XXXX-XXXX-9124",
				"creditCardExpMonth": "12",
				"creditCardExpYear": "29",
				"billingZipCode": "07107",
				"creditCardType": "masterCard",
				"creditCardVerificationNumber": null,
				"creditCardBIN": "509105",
				"cvvRequired": true
			}, {
				"savedCardNickName": "test",
				"preselectCard": null,
				"creditCardNumber": "XXXX-XXXXXX-X1005",
				"creditCardExpMonth": "05",
				"creditCardExpYear": "18",
				"billingZipCode": "30329",
				"creditCardType": "americanExpress",
				"creditCardVerificationNumber": null,
				"creditCardBIN": "373953",
				"cvvRequired": true
			}],
			"applePayResponseInfo": null,
			"masterpassResponseInfo": {
				"emailAddress": null,
				"cardType": null,
				"lastDigits": null,
				"creditCardBIN": null
			},
			"masterpassError": false,
			"masterpassErrorMessage": null,
			"paypalEmailAddress": null,
			"expirationMonths": ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
			"expirationYears": ["2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027"]
		},
		"devices": {
			"dueMonthly": 0.0,
			"totalActivationFee": 0.0,
			"deviceTotalDueMonthly": 0.0,
			"dueToday": 0.0,
			"accessories": [],
			"accessoriesBundle": [{
				"discountedPrice": 144.97,
				"imgUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphone7-plus-defender-power-protection-bundle-15885-gg-bundle-iset?$acc-med$",
				"regularPrice": 144.97,
				"savedPrice": 0.0,
				"displayName": "Defender Power & Protection Bundle for iPhone 7 Plus",
				"bundleDescription": null,
				"skuID": "sku2310063",
				"discountPercentage": null,
				"discounted": false
			}],
			"items": null,
			"buddyUpgrade": false
		},
		"accessories": null,
		"selectedShippingType": {
			"type": "SHIPPING",
			"shippingTypeName": "FREE 2 Day by 8pm",
			"price": 0.0,
			"discountPrice": 0.0,
			"estimatedDeliveryDate": null
		},
		"dueMonthlyView": {
			"title": null,
			"dueMonthlyPrice": null,
			"items": null,
			"tmpMd": null
		},
		"balanceCreditCardAmount": "212.44",
		"cpcOrder": false,
		"totalDueMonthlyPlanAndDevice": "55.41",
		"deviceConfigInfo": {
			"devices": [{
				"deviceId": "S382ee9ccd1c01e2a9b83422ad8fbadbd{d4}_device_1",
				"deviceName": "iPhone&reg; 7 Plus",
				"deviceSetupMode": null,
				"mtnNumber": "8622722534",
				"flow": "EUP",
				"serviceAddress": {
					"firstName": "BOB",
					"lastName": "SMITH",
					"address1": "250 GEORGIA KING VLG APT 15G",
					"address2": "",
					"city": "Newark",
					"state": "NJ",
					"zipCode": "07107",
					"emailAddress": "VZW@VZW.COM",
					"phoneNumber": "9464436332"
				},
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-plus-front-matblk?$device-med$&fmt=jpeg&wid=75&hei=150",
				"mobileAppImageName": null,
				"npaNxxnumber": null,
				"npnxxCustomerSelection": null,
				"npaNxxdetails": null,
				"manufactureName": "Apple",
				"color": "Black",
				"size": "32GB",
				"numberShareDevice": false,
				"numberSharedMtn": null,
				"portInDetails": null
			}],
			"npaNxxdetails": {
				"zipCode": null,
				"state": null,
				"city": null,
				"success": false,
				"mtns": null,
				"states": null,
				"cities": null
			},
			"deviceAddressUpdated": false,
			"accessories": null
		},
		"checkoutStates": {
			"shippingAddressRequired": false,
			"shippingAddressChangeRequired": false,
			"shippingMethodRequired": false,
			"paymentRequired": false,
			"pastDuePaymentRequired": false,
			"showPaymentSection": true,
			"showShippingAddress": true,
			"showDeliveryMethod": true,
			"newCard": false,
			"cvvNeeded": false
		},
		"totalEdgeItemDownPaymentAmount": "0.00",
		"totalEdgeUpAmount": "0.00",
		"totalEdgeUpBuyOutAmount": "0.00",
		"multiOrderDetails": null,
		"hasRio": false,
		"splitShipment": false,
		"isHLLPlanInOrder": true
	}
};