window.confirmationJSON = {
	"output": {
		"title": "You're all set.",
		"subtitle": null,
		"orderId": "376617825642854",
		"estimatedDelivery": "",
		"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/1.3_MV_BuyandUpgrade_ConfirmationPage_Interstital?$device-med$",
		"tradeInStatus": false,
		"confirmationMessage": "Thanks for ordering from verizonwireless.com. Your order receipt is sent to VZW@VZW.COM.",
		"doneButtonText": "Got it",
		"doneButtonLink": "/od/cust/auth/shoplanding/",
		"userNote": "TODO",
		"notNowButtonText": "TODO",
		"notNowButtonLink": "TODO",
		"learnHowButtonText": null,
		"learnHowButtonLink": "/od/cust/auth/learnHow",
		"numberOfDevice": 3,
		"confirmationNumberText": "Confirmation Number",
		"iconicFlow": true,
		"protectionURL": null,
		"accessoriesURL": null,
		"tapFlag": false,
		"cjmTagUrl": null,
		"pepperJamTagUrl": null,
		"selectedPaymentMode": null,
		"confirmationEmail": "VZW@VZW.COM",
		"accessoryGWURL": "/od/cust/auth/accessories/",
		"shipToAddresss": null,
		"billToAddress": null,
		"deviceList": null,
		"planList": null,
		"plans": {
			"dueMonthly": null,
			"dueToday": null,
			"planOnlyDueMonthly": null,
			"items": [{
				"planType": null,
				"lineAccessCharges": null,
				"accountAccess": null,
				"accountLevelFeatures": null,
				"totalMonthlyPlanCost": null,
				"spoBadgeMessage": null,
				"planDisplayName": "",
				"planImageURL": null,
				"planLetter": null,
				"planDescrption": null,
				"planDescription": null,
				"quantity": 0,
				"skuId": "sku3060019",
				"productId": "plan5600003",
				"itemAmount": -1.7976931348623157E308,
				"itemAmountOriginal": 55.0,
				"dueMonthly": 0.0,
				"dueMonthlyOriginal": 0.0,
				"itemDiscount": 1.7976931348623157E308,
				"displayName": null,
				"skuDisplayName": null,
				"listPrice": 55.0,
				"rawTotalAmount": 0.0,
				"planGroupCode": null,
				"autoPayEnabled": false,
				"numberSharePlan": false,
				"planCommerceItemId": "S7a80dc3a41cff306e4bb20de88749f97{ss1}_plan_1",
				"autoPayPrice": 0.0,
				"autoPayText": null,
				"termsAndConditionKey": null
			}, {
				"planType": null,
				"lineAccessCharges": null,
				"accountAccess": null,
				"accountLevelFeatures": null,
				"totalMonthlyPlanCost": null,
				"spoBadgeMessage": null,
				"planDisplayName": "",
				"planImageURL": null,
				"planLetter": null,
				"planDescrption": null,
				"planDescription": null,
				"quantity": 0,
				"skuId": "sku3060020",
				"productId": "plan5600003",
				"itemAmount": 0.0,
				"itemAmountOriginal": 45.0,
				"dueMonthly": 0.0,
				"dueMonthlyOriginal": 0.0,
				"itemDiscount": 0.0,
				"displayName": null,
				"skuDisplayName": null,
				"listPrice": 45.0,
				"rawTotalAmount": 0.0,
				"planGroupCode": null,
				"autoPayEnabled": false,
				"numberSharePlan": false,
				"planCommerceItemId": "S7a80dc3a41cff306e4bb20de88749f97{ss1}_plan_2",
				"autoPayPrice": 0.0,
				"autoPayText": null,
				"termsAndConditionKey": null
			}, {
				"planType": null,
				"lineAccessCharges": null,
				"accountAccess": null,
				"accountLevelFeatures": null,
				"totalMonthlyPlanCost": null,
				"spoBadgeMessage": null,
				"planDisplayName": "",
				"planImageURL": null,
				"planLetter": null,
				"planDescrption": null,
				"planDescription": null,
				"quantity": 0,
				"skuId": "sku3060010",
				"productId": "plan5600003",
				"itemAmount": 0.0,
				"itemAmountOriginal": 45.0,
				"dueMonthly": 0.0,
				"dueMonthlyOriginal": 0.0,
				"itemDiscount": 0.0,
				"displayName": null,
				"skuDisplayName": null,
				"listPrice": 45.0,
				"rawTotalAmount": 0.0,
				"planGroupCode": null,
				"autoPayEnabled": false,
				"numberSharePlan": false,
				"planCommerceItemId": "S7a80dc3a41cff306e4bb20de88749f97{ss1}_plan_3",
				"autoPayPrice": 0.0,
				"autoPayText": null,
				"termsAndConditionKey": null
			}],
			"upgradeDevices": null,
			"newDevices": null,
			"existingDevices": [{
				"name": null,
				"price": "55.0",
				"discountPrice": 55.0,
				"hasEcpdDiscount": false,
				"mtn": "8564302170",
				"listPrice": 55.0,
				"deviceLineItemId": null,
				"discountPriceVal": null,
				"planCommerceItemId": "S7a80dc3a41cff306e4bb20de88749f97{ss1}_plan_1",
				"nickName": "",
				"numberShareDevice": false,
				"featureDropped": false
			}, {
				"name": null,
				"price": "45.0",
				"discountPrice": 45.0,
				"hasEcpdDiscount": false,
				"mtn": "8564304782",
				"listPrice": 45.0,
				"deviceLineItemId": null,
				"discountPriceVal": null,
				"planCommerceItemId": "S7a80dc3a41cff306e4bb20de88749f97{ss1}_plan_2",
				"nickName": "",
				"numberShareDevice": false,
				"featureDropped": false
			}, {
				"name": null,
				"price": "45.0",
				"discountPrice": 45.0,
				"hasEcpdDiscount": false,
				"mtn": "8562877564",
				"listPrice": 45.0,
				"deviceLineItemId": null,
				"discountPriceVal": null,
				"planCommerceItemId": "S7a80dc3a41cff306e4bb20de88749f97{ss1}_plan_3",
				"nickName": "",
				"numberShareDevice": false,
				"featureDropped": false
			}],
			"dueMonthlyPlanWithLAC": null,
			"discountedDueMonthlyPlanWithLAC": null,
			"hasEcpdDiscount": false
		},
		"featureList": [{
			"id": "S7a80dc3a41cff306e4bb20de88749f97{ss1}_feature_1",
			"quantity": 1,
			"type": "INSUR,I",
			"skuId": "sku2880128",
			"productId": "sfo80072",
			"sorId": "85915",
			"itemAmount": 0.0,
			"itemAmountOriginal": 13.0,
			"dueMonthly": 13.0,
			"dueMonthlyOriginal": null,
			"itemDiscount": 0.0,
			"displayName": "Total Mobile Protection",
			"skuDisplayName": null,
			"listPrice": 13.0,
			"rawTotalAmount": 0.0,
			"pricingDetails": [{
				"pricingAdjustmentId": null,
				"itemId": "S7a80dc3a41cff306e4bb20de88749f97{ss1}_feature_1",
				"orderId": "S7a80dc3a41cff306e4bb20de88749f97{ss1}",
				"offerId": null,
				"offerAmount": 0.0,
				"description": "List Price description",
				"offerType": null,
				"priceListId": null,
				"listPrice": 13.0,
				"offerName": null,
				"creationDate": 1526461179662,
				"lastModifiedDate": 1526461179662,
				"version": 1
			}],
			"orderId": "S7a80dc3a41cff306e4bb20de88749f97{ss1}",
			"version": 1,
			"delete": false,
			"inventoryLevel": 0,
			"taxDetails": null,
			"itemTaxes": 0.0,
			"deviceLineItemId": "S7a80dc3a41cff306e4bb20de88749f97{ss1}_device_1",
			"featureCharge": 0.0,
			"featureType": "INS",
			"lastModifiedDate": 1526461177330
		}],
		"accessoryList": null,
		"paymentGroup": null,
		"contactInfo": {
			"id": null,
			"emailAddress": "VZW@VZW.COM",
			"phoneNumber": "9346693693",
			"lastName": "WRIGHT",
			"firstName": "KENNY",
			"zipCode": "08034",
			"orderId": null,
			"userId": null,
			"npaNxxNumber": null,
			"address1": "1916 OLD CUTHBERT RD STE A4",
			"address2": null,
			"city": "Cherry Hill",
			"state": "NJ",
			"addressVerified": true,
			"textAlertOptin": false,
			"newsLetterOptin": false,
			"paperFreeBillingIndicatorFlag": false,
			"middleName": null,
			"firmName": null,
			"businessName": null,
			"apartmentNum": "A4",
			"addressDirection": "",
			"poBox": "",
			"streetNumber": "1916",
			"streetName": "OLD CUTHBERT",
			"streetType": "RD",
			"ruralRoute": null,
			"ruralDel": "",
			"zipCode4": null,
			"zipCode5": null,
			"faxNumber": null,
			"addressType": null,
			"country": "",
			"prefix": null,
			"suffix": null,
			"postbox": null,
			"companyname": null,
			"ruralrte": "",
			"county": null,
			"address3": null,
			"postalcode": "08034",
			"version": 0,
			"lastModifiedDate": null,
			"addressConfirmationStatus": null
		},
		"tradeInDevicesDetails": null,
		"tradeInPromoDetails": null,
		"transformedTradeInPromoDetails": null,
		"subOrders": null,
		"comboOrder": false,
		"totalDueToday": "36.44",
		"totalDueMonthly": "107.73",
		"subTotalDueToday": "0.00",
		"securityDepositAmount": "0.00",
		"stateSalesTax": "36.44",
		"employeeDiscount": "0.00",
		"pastDueExist": false,
		"pastDueAmountPaid": false,
		"pastDueAmount": "0.00",
		"shippingInfo": {
			"shippingInfoUpdated": false,
			"sameAsBilling": true,
			"ispuEligibleFlag": true,
			"addressInfo": {
				"firstName": "KENNY",
				"lastName": "WRIGHT",
				"companyName": null,
				"address1": "1916 OLD CUTHBERT RD STE A4",
				"address2": null,
				"city": "Cherry Hill",
				"state": "NJ",
				"zipcode": "08034",
				"businessName": null,
				"postalCode": null,
				"email": "VZW@VZW.COM",
				"phoneNumber": "9346693693"
			},
			"contactInfo": {
				"emailAddress": "VZW@VZW.COM",
				"phoneNumber": "9346693693",
				"firstName": "KENNY",
				"lastName": "WRIGHT",
				"smsMdn": null,
				"activeSMSCapableMtnList": ["8564302170", "8562877564"]
			},
			"shippingTypesInfo": [{
				"estimatedDeliveryDate": "2018-05-18 00:00:00",
				"estimatedDeliveryDateText": "Fri 5/18",
				"shippingDescription": "Free 2 Day by 8pm",
				"shippingOptionId": "SHP002",
				"shippingCost": "0.00",
				"shortDescription": "Free 2 Day by 8pm",
				"active": true,
				"addedShippingOptionId": true,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Fri, May 18 if ordered by 4pm today. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}, {
				"estimatedDeliveryDate": "2018-05-17 00:00:00",
				"estimatedDeliveryDateText": "Thu 5/17",
				"shippingDescription": "Next Day by 8pm",
				"shippingOptionId": "SHP004",
				"shippingCost": "12.99",
				"shortDescription": "Next Day by 8pm",
				"active": true,
				"addedShippingOptionId": false,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Thu, May 17. Next Day by 8pm. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}, {
				"estimatedDeliveryDate": "2018-05-17 10:30:00",
				"estimatedDeliveryDateText": "Thu 5/17 by 10:30AM",
				"shippingDescription": "Next Day by 10:30am",
				"shippingOptionId": "SHP005",
				"shippingCost": "14.99",
				"shortDescription": "Next Day by 10:30am",
				"active": true,
				"addedShippingOptionId": false,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Thu, May 17. Next Day by 10:30am. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}],
			"storeDetail": {
				"storeHeader": null,
				"storeName": null,
				"storeAddress": null,
				"deviceAvailable": false,
				"distance": null,
				"appendedStoreTiming": null,
				"longitude": null,
				"storeId": null,
				"netaceLocationCode": null,
				"latitude": null,
				"seoUrlName": null,
				"storeClosingTime": null
			},
			"tradeIn": false,
			"tradeInAddress": null,
			"nonSddEligibleMsg": null,
			"selectedSDDWindow": null,
			"poboMessage": null,
			"ispudetailsInfo": {
				"storeAddress": null,
				"storeHours": null,
				"storeId": null,
				"storeName": null,
				"phoneNumber": null,
				"distance": null,
				"totalItems": 0,
				"availItems": 0,
				"latitdude": 0.0,
				"longtitude": 0.0,
				"availItemName": null
			}
		},
		"billingInfo": {
			"billToAccountEligible": true,
			"creditCardZipEditable": false,
			"billingAddress": {
				"firstName": "KENNY",
				"lastName": "WRIGHT",
				"businessName": null,
				"zipcode": "08034",
				"state": "NJ",
				"address2": null,
				"address1": "1916 OLD CUTHBERT RD STE A4",
				"companyName": null,
				"city": "Cherry Hill"
			},
			"masterpass3DSecure": null,
			"billToAccountNumber": "#XXXXXXX-0001",
			"creditCardInfo": {
				"savedCardNickName": null,
				"preselectCard": null,
				"creditCardNumber": null,
				"creditCardExpMonth": null,
				"creditCardExpYear": null,
				"billingZipCode": null,
				"creditCardType": null,
				"creditCardVerificationNumber": null,
				"creditCardBIN": null,
				"cvvRequired": false
			},
			"selectedPaymentMode": "BTA",
			"giftCardList": [],
			"savedCardInfo": [],
			"applePayResponseInfo": null,
			"masterpassResponseInfo": {
				"emailAddress": null,
				"cardType": null,
				"lastDigits": null,
				"creditCardBIN": null
			},
			"masterpassError": false,
			"masterpassErrorMessage": null,
			"paypalEmailAddress": null,
			"expirationMonths": ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
			"expirationYears": ["2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027"]
		},
		"devices": {
			"dueMonthly": 107.73,
			"totalActivationFee": 0.0,
			"deviceTotalDueMonthly": 68.73,
			"dueToday": 0.0,
			"accessories": [],
			"accessoriesBundle": [],
			"items": [{
				"deviceName": "iPhone&reg; 7",
				"dueMonthly": "22.91",
				"dueToday": "0.00",
				"upgradeFee": "0.00",
				"activationFee": "0.00",
				"dueTodayOriginal": "0.00",
				"dueMonthlyOriginal": null,
				"dueTodayDiscounted": false,
				"dueMonthlyDiscounted": false,
				"mtn": null,
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-med$&fmt=jpeg&wid=75&hei=150",
				"protectionFeature": {
					"name": "Total Mobile Protection",
					"mtn": null,
					"price": "13.00",
					"discountPrice": "0.00",
					"retailPrice": "0.00",
					"hasEcpdDiscount": false,
					"promoMessage": null,
					"originalPrice": "0.00",
					"wasPrice": "0.00",
					"deviceName": null,
					"color": null,
					"size": null,
					"instantCreditAmount": "0.00",
					"amountAfterInstantCredit": "0.00",
					"disountedInstantCreditAmt": "0.00"
				},
				"optionalFeatures": [],
				"installmentBalance": "549.99",
				"edgeRetailPrice": "549.99",
				"edgeItemDownPaymentAmount": "0.00",
				"mailInRebateAmount": "0.00",
				"transferredFromMtn": null,
				"devicePromotionList": [],
				"bicOfferApplied": false,
				"bicContractPrice": "0.00",
				"bicDiscountedContractPrice": "-1.00",
				"bicAdditionalContractText": null,
				"bicMessageMap": null,
				"edgeUpAmount": 0.0,
				"displayDeviceDueMonthly": 35.91,
				"deviceLACFee": "0.00",
				"manufactureName": "Apple",
				"color": "Gold",
				"colorCode": "#CFBEA9",
				"size": "32GB",
				"displayName": "iPhone&reg; 7",
				"contractTerm": "99",
				"edgeUpBuyOutAmount": 0.0,
				"fullRetailPrice": "549.99",
				"alwaysEligibleForUpgrade": false,
				"numberShareDevice": false,
				"activationFeeText": null,
				"numberSharedMtn": null,
				"promoContentText": null,
				"itemOnJaxPlan": false,
				"humCarDetails": null,
				"simDetails": null,
				"imeiId": null,
				"displayImeiId": null,
				"poboDateLabel": null,
				"nickName": null,
				"planCommerceItemId": null,
				"displayMtn": null,
				"promoOfferText": null,
				"promoApplied": false,
				"commerceItemId": "S7a80dc3a41cff306e4bb20de88749f97{ss1}_device_1",
				"loanTerm": 24,
				"sbdHeaderMsg": null,
				"percentage": null,
				"waivedActivationFeePromo": false,
				"flow": "AAL",
				"instantCreditAmount": "0.00",
				"amountAfterInstantCredit": "0.00",
				"accessory": false,
				"edgeDevice": true,
				"eupdevice": false,
				"disountedInstantCreditAmt": "0.00"
			}, {
				"deviceName": "iPhone&reg; 7",
				"dueMonthly": "22.91",
				"dueToday": "0.00",
				"upgradeFee": "0.00",
				"activationFee": "0.00",
				"dueTodayOriginal": "0.00",
				"dueMonthlyOriginal": null,
				"dueTodayDiscounted": false,
				"dueMonthlyDiscounted": false,
				"mtn": null,
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-med$&fmt=jpeg&wid=75&hei=150",
				"protectionFeature": {
					"name": "Total Mobile Protection",
					"mtn": null,
					"price": "13.00",
					"discountPrice": "0.00",
					"retailPrice": "0.00",
					"hasEcpdDiscount": false,
					"promoMessage": null,
					"originalPrice": "0.00",
					"wasPrice": "0.00",
					"deviceName": null,
					"color": null,
					"size": null,
					"instantCreditAmount": "0.00",
					"amountAfterInstantCredit": "0.00",
					"disountedInstantCreditAmt": "0.00"
				},
				"optionalFeatures": [],
				"installmentBalance": "549.99",
				"edgeRetailPrice": "549.99",
				"edgeItemDownPaymentAmount": "0.00",
				"mailInRebateAmount": "0.00",
				"transferredFromMtn": null,
				"devicePromotionList": [],
				"bicOfferApplied": false,
				"bicContractPrice": "0.00",
				"bicDiscountedContractPrice": "-1.00",
				"bicAdditionalContractText": null,
				"bicMessageMap": null,
				"edgeUpAmount": 0.0,
				"displayDeviceDueMonthly": 35.91,
				"deviceLACFee": "0.00",
				"manufactureName": "Apple",
				"color": "Gold",
				"colorCode": "#CFBEA9",
				"size": "32GB",
				"displayName": "iPhone&reg; 7",
				"contractTerm": "99",
				"edgeUpBuyOutAmount": 0.0,
				"fullRetailPrice": "549.99",
				"alwaysEligibleForUpgrade": false,
				"numberShareDevice": false,
				"activationFeeText": null,
				"numberSharedMtn": null,
				"promoContentText": null,
				"itemOnJaxPlan": false,
				"humCarDetails": null,
				"simDetails": null,
				"imeiId": null,
				"displayImeiId": null,
				"poboDateLabel": null,
				"nickName": null,
				"planCommerceItemId": null,
				"displayMtn": null,
				"promoOfferText": null,
				"promoApplied": false,
				"commerceItemId": "S7a80dc3a41cff306e4bb20de88749f97{ss1}_device_1",
				"loanTerm": 24,
				"sbdHeaderMsg": null,
				"percentage": null,
				"waivedActivationFeePromo": false,
				"flow": "AAL",
				"instantCreditAmount": "0.00",
				"amountAfterInstantCredit": "0.00",
				"accessory": false,
				"edgeDevice": true,
				"eupdevice": false,
				"disountedInstantCreditAmt": "0.00"
			}, {
				"deviceName": "iPhone&reg; 7",
				"dueMonthly": "22.91",
				"dueToday": "0.00",
				"upgradeFee": "0.00",
				"activationFee": "0.00",
				"dueTodayOriginal": "0.00",
				"dueMonthlyOriginal": null,
				"dueTodayDiscounted": false,
				"dueMonthlyDiscounted": false,
				"mtn": null,
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-med$&fmt=jpeg&wid=75&hei=150",
				"protectionFeature": {
					"name": "Total Mobile Protection",
					"mtn": null,
					"price": "13.00",
					"discountPrice": "0.00",
					"retailPrice": "0.00",
					"hasEcpdDiscount": false,
					"promoMessage": null,
					"originalPrice": "0.00",
					"wasPrice": "0.00",
					"deviceName": null,
					"color": null,
					"size": null,
					"instantCreditAmount": "0.00",
					"amountAfterInstantCredit": "0.00",
					"disountedInstantCreditAmt": "0.00"
				},
				"optionalFeatures": [],
				"installmentBalance": "549.99",
				"edgeRetailPrice": "549.99",
				"edgeItemDownPaymentAmount": "0.00",
				"mailInRebateAmount": "0.00",
				"transferredFromMtn": null,
				"devicePromotionList": [],
				"bicOfferApplied": false,
				"bicContractPrice": "0.00",
				"bicDiscountedContractPrice": "-1.00",
				"bicAdditionalContractText": null,
				"bicMessageMap": null,
				"edgeUpAmount": 0.0,
				"displayDeviceDueMonthly": 35.91,
				"deviceLACFee": "0.00",
				"manufactureName": "Apple",
				"color": "Gold",
				"colorCode": "#CFBEA9",
				"size": "32GB",
				"displayName": "iPhone&reg; 7",
				"contractTerm": "99",
				"edgeUpBuyOutAmount": 0.0,
				"fullRetailPrice": "549.99",
				"alwaysEligibleForUpgrade": false,
				"numberShareDevice": false,
				"activationFeeText": null,
				"numberSharedMtn": null,
				"promoContentText": null,
				"itemOnJaxPlan": false,
				"humCarDetails": null,
				"simDetails": null,
				"imeiId": null,
				"displayImeiId": null,
				"poboDateLabel": null,
				"nickName": null,
				"planCommerceItemId": null,
				"displayMtn": null,
				"promoOfferText": null,
				"promoApplied": false,
				"commerceItemId": "S7a80dc3a41cff306e4bb20de88749f97{ss1}_device_1",
				"loanTerm": 24,
				"sbdHeaderMsg": null,
				"percentage": null,
				"waivedActivationFeePromo": false,
				"flow": "AAL",
				"instantCreditAmount": "0.00",
				"amountAfterInstantCredit": "0.00",
				"accessory": false,
				"edgeDevice": true,
				"eupdevice": false,
				"disountedInstantCreditAmt": "0.00"
			}],
			"buddyUpgrade": false
		},
		"accessories": null,
		"selectedShippingType": {
			"type": "SHIPPING",
			"shippingTypeName": "FREE 2 Day by 8pm",
			"price": 0.0,
			"discountPrice": 0.0,
			"estimatedDeliveryDate": null
		},
		"dueMonthlyView": {
			"title": "Due Monthly (device only)",
			"dueMonthlyPrice": "107.73",
			"items": [{
				"name": "iPhone&reg; 7",
				"description": "iPhone&reg; 7",
				"manufacturer": "Apple",
				"color": "Gold",
				"size": "32GB",
				"priceBreakDown": [{
					"lable": "Line Access Charge",
					"price": "0.00",
					"description": null,
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 0.0,
					"itemStrikeThroughPrice": 0.0,
					"noOfBicOccurences": 0
				}, {
					"lable": "Total Mobile Protection",
					"price": "13.00",
					"description": null,
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 0.0,
					"itemStrikeThroughPrice": 0.0,
					"noOfBicOccurences": 0
				}, {
					"lable": "Device Payment",
					"price": "22.91",
					"description": "For 24 months, 0% APR Retail price: $549.99",
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 22.91,
					"itemStrikeThroughPrice": 0.0,
					"noOfBicOccurences": 0
				}],
				"nickName": null,
				"planCommerceItemId": null,
				"displayMtn": null,
				"numberShareDevice": false,
				"edge": true
			}, {
				"name": "iPhone&reg; 7",
				"description": "iPhone&reg; 7",
				"manufacturer": "Apple",
				"color": "Gold",
				"size": "32GB",
				"priceBreakDown": [{
					"lable": "Line Access Charge",
					"price": "0.00",
					"description": null,
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 0.0,
					"itemStrikeThroughPrice": 0.0,
					"noOfBicOccurences": 0
				}, {
					"lable": "Total Mobile Protection",
					"price": "13.00",
					"description": null,
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 0.0,
					"itemStrikeThroughPrice": 0.0,
					"noOfBicOccurences": 0
				}, {
					"lable": "Device Payment",
					"price": "22.91",
					"description": "For 24 months, 0% APR Retail price: $549.99",
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 22.91,
					"itemStrikeThroughPrice": 0.0,
					"noOfBicOccurences": 0
				}],
				"nickName": null,
				"planCommerceItemId": null,
				"displayMtn": null,
				"numberShareDevice": false,
				"edge": true
			}, {
				"name": "iPhone&reg; 7",
				"description": "iPhone&reg; 7",
				"manufacturer": "Apple",
				"color": "Gold",
				"size": "32GB",
				"priceBreakDown": [{
					"lable": "Line Access Charge",
					"price": "0.00",
					"description": null,
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 0.0,
					"itemStrikeThroughPrice": 0.0,
					"noOfBicOccurences": 0
				}, {
					"lable": "Total Mobile Protection",
					"price": "13.00",
					"description": null,
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 0.0,
					"itemStrikeThroughPrice": 0.0,
					"noOfBicOccurences": 0
				}, {
					"lable": "Device Payment",
					"price": "22.91",
					"description": "For 24 months, 0% APR Retail price: $549.99",
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 22.91,
					"itemStrikeThroughPrice": 0.0,
					"noOfBicOccurences": 0
				}],
				"nickName": null,
				"planCommerceItemId": null,
				"displayMtn": null,
				"numberShareDevice": false,
				"edge": true
			}],
			"tmpMd": null
		},
		"balanceCreditCardAmount": "36.44",
		"cpcOrder": true,
		"totalDueMonthlyPlanAndDevice": "107.73",
		"deviceConfigInfo": {
			"devices": [{
				"deviceId": "S7a80dc3a41cff306e4bb20de88749f97{ss1}_device_1",
				"deviceName": "iPhone&reg; 7",
				"deviceSetupMode": null,
				"mtnNumber": null,
				"flow": "AAL",
				"serviceAddress": {
					"firstName": "KENNY",
					"lastName": "WRIGHT",
					"address1": "1916 OLD CUTHBERT RD STE A4",
					"address2": "",
					"city": "Cherry Hill",
					"state": "NJ",
					"zipCode": "08034",
					"emailAddress": "VZW@VZW.COM",
					"phoneNumber": "9346693693"
				},
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-med$&fmt=jpeg&wid=75&hei=150",
				"mobileAppImageName": null,
				"npaNxxnumber": "null",
				"npnxxCustomerSelection": "new",
				"npaNxxdetails": null,
				"manufactureName": "Apple",
				"color": "Gold",
				"size": "32GB",
				"numberShareDevice": false,
				"numberSharedMtn": null,
				"portInDetails": null
			}],
			"npaNxxdetails": {
				"zipCode": null,
				"state": null,
				"city": null,
				"success": false,
				"mtns": null,
				"states": null,
				"cities": null
			},
			"deviceAddressUpdated": false,
			"accessories": null
		},
		"checkoutStates": {
			"shippingAddressRequired": false,
			"shippingAddressChangeRequired": false,
			"shippingMethodRequired": false,
			"paymentRequired": false,
			"pastDuePaymentRequired": false,
			"showPaymentSection": true,
			"showShippingAddress": true,
			"showDeliveryMethod": true,
			"newCard": false,
			"cvvNeeded": false
		},
		"accountLevelDiscountList": [{
			"productId": "1089",
			"cost": "-15.00",
			"level": "A",
			"productName": "$15 MILITARY/VETERAN DISCOUNT",
			"productType": "SPO",
			"discountProductInd": null
		}],
		"totalEdgeItemDownPaymentAmount": "0.00",
		"totalEdgeUpAmount": "0.00",
		"totalEdgeUpBuyOutAmount": "0.00",
		"multiOrderDetails": null,
		"hasRio": false,
		"splitShipment": false,
		"isHLLPlanInOrder": false,
		"recommendedAccessoriesUrl": "/od/cust/auth/accessories/?format=json"
}
};