window.confirmationJSON =  /*{
 	"output": {
 		"title": "You're all set.",
 		"subtitle": null,
 		"orderId": "871430118082609",
 		"estimatedDelivery": "",
 		"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/1.3_MV_BuyandUpgrade_ConfirmationPage_Interstital?$device-med$",
 		"tradeInStatus": false,
 		"confirmationMessage": "Thanks for ordering from verizonwireless.com. Your order receipt is sent to VZW@VZW.COM.",
 		"doneButtonText": "Got it",
 		"doneButtonLink": "/od/cust/auth/shoplanding/",
 		"userNote": "TODO",
 		"notNowButtonText": "TODO",
 		"notNowButtonLink": "TODO",
 		"learnHowButtonText": null,
 		"learnHowButtonLink": "/od/cust/auth/learnHow",
 		"numberOfDevice": 3,
 		"confirmationNumberText": "Confirmation Number",
 		"iconicFlow": true,
 		"protectionURL": null,
 		"accessoriesURL": null,
 		"tapFlag": false,
 		"cjmTagUrl": null,
 		"pepperJamTagUrl": null,
 		"selectedPaymentMode": null,
 		"confirmationEmail": "VZW@VZW.COM",
 		"shipToAddresss": null,
 		"billToAddress": null,
 		"deviceList": null,
 		"planList": null,
 		"plans": {
 			"dueMonthly": null,
 			"dueToday": null,
 			"planOnlyDueMonthly": null,
 			"items": [{
 				"planType": null,
 				"lineAccessCharges": null,
 				"accountAccess": null,
 				"accountLevelFeatures": null,
 				"totalMonthlyPlanCost": null,
 				"spoBadgeMessage": null,
 				"planDisplayName": "",
 				"planImageURL": null,
 				"planLetter": null,
 				"planDescrption": null,
 				"planDescription": null,
 				"quantity": 0,
 				"skuId": "sku3060019",
 				"productId": "plan5600003",
 				"itemAmount": -1.7976931348623157E308,
 				"itemAmountOriginal": 55.0,
 				"dueMonthly": 0.0,
 				"dueMonthlyOriginal": 0.0,
 				"itemDiscount": 1.7976931348623157E308,
 				"displayName": null,
 				"skuDisplayName": null,
 				"listPrice": 55.0,
 				"rawTotalAmount": 0.0,
 				"planGroupCode": null,
 				"autoPayEnabled": false,
 				"numberSharePlan": false,
 				"planCommerceItemId": "Sf98cbf72deaa904c1dc8b4f60092b06a{ss3}_plan_1",
 				"autoPayPrice": 0.0,
 				"autoPayText": null,
 				"termsAndConditionKey": null
 			}],
 			"upgradeDevices": null,
 			"newDevices": null,
 			"existingDevices": [{
 				"name": null,
 				"price": "55.0",
 				"discountPrice": 55.0,
 				"hasEcpdDiscount": false,
 				"mtn": "8108692805",
 				"listPrice": 55.0,
 				"deviceLineItemId": null,
 				"discountPriceVal": null,
 				"planCommerceItemId": "Sf98cbf72deaa904c1dc8b4f60092b06a{ss3}_plan_1",
 				"nickName": "",
 				"numberShareDevice": false,
 				"featureDropped": false
 			}, {
 				"name": null,
 				"price": "55.0",
 				"discountPrice": 55.0,
 				"hasEcpdDiscount": false,
 				"mtn": "8108454548",
 				"listPrice": 55.0,
 				"deviceLineItemId": null,
 				"discountPriceVal": null,
 				"planCommerceItemId": "Sf98cbf72deaa904c1dc8b4f60092b06a{ss3}_plan_1",
 				"nickName": "",
 				"numberShareDevice": false,
 				"featureDropped": false
 			}, {
 				"name": null,
 				"price": "55.0",
 				"discountPrice": 55.0,
 				"hasEcpdDiscount": false,
 				"mtn": "8108695482",
 				"listPrice": 55.0,
 				"deviceLineItemId": null,
 				"discountPriceVal": null,
 				"planCommerceItemId": "Sf98cbf72deaa904c1dc8b4f60092b06a{ss3}_plan_1",
 				"nickName": "",
 				"numberShareDevice": false,
 				"featureDropped": false
 			}],
 			"dueMonthlyPlanWithLAC": null,
 			"discountedDueMonthlyPlanWithLAC": null,
 			"hasEcpdDiscount": false
 		},
 		"featureList": [{
 			"id": "Sf98cbf72deaa904c1dc8b4f60092b06a{ss3}_feature_1",
 			"quantity": 1,
 			"type": "INSUR,D",
 			"skuId": "sku401064",
 			"productId": "sfo80072",
 			"sorId": "66332",
 			"itemAmount": 0.0,
 			"itemAmountOriginal": 0.0,
 			"dueMonthly": 0.0,
 			"dueMonthlyOriginal": null,
 			"itemDiscount": 0.0,
 			"displayName": "Decline Equipment Protection",
 			"skuDisplayName": null,
 			"listPrice": 0.0,
 			"rawTotalAmount": 0.0,
 			"pricingDetails": [{
 				"pricingAdjustmentId": null,
 				"itemId": "Sf98cbf72deaa904c1dc8b4f60092b06a{ss3}_feature_1",
 				"orderId": "Sf98cbf72deaa904c1dc8b4f60092b06a{ss3}",
 				"offerId": null,
 				"offerAmount": 0.0,
 				"description": "List Price description",
 				"offerType": null,
 				"priceListId": null,
 				"listPrice": 0.0,
 				"offerName": null,
 				"creationDate": 1526424306417,
 				"lastModifiedDate": 1526424306417,
 				"version": 1
 			}],
 			"orderId": "Sf98cbf72deaa904c1dc8b4f60092b06a{ss3}",
 			"version": 1,
 			"delete": false,
 			"inventoryLevel": 0,
 			"taxDetails": null,
 			"itemTaxes": 0.0,
 			"deviceLineItemId": "Sf98cbf72deaa904c1dc8b4f60092b06a{ss3}_device_1",
 			"featureCharge": 0.0,
 			"featureType": "INS",
 			"lastModifiedDate": 1526424295411
 		}],
 		"accessoryList": null,
 		"paymentGroup": null,
 		"contactInfo": {
 			"id": null,
 			"emailAddress": "VZW@VZW.COM",
 			"phoneNumber": "9204360630",
 			"lastName": "JACOBS",
 			"firstName": "RAVI",
 			"zipCode": "48423",
 			"orderId": null,
 			"userId": null,
 			"npaNxxNumber": null,
 			"address1": "8217 KENSINGTON BLVD APT 582B",
 			"address2": null,
 			"city": "Davison",
 			"state": "MI",
 			"addressVerified": true,
 			"textAlertOptin": false,
 			"newsLetterOptin": false,
 			"paperFreeBillingIndicatorFlag": false,
 			"middleName": null,
 			"firmName": null,
 			"businessName": null,
 			"apartmentNum": "582B",
 			"addressDirection": "",
 			"poBox": "",
 			"streetNumber": "8217",
 			"streetName": "KENSINGTON",
 			"streetType": "BLVD",
 			"ruralRoute": null,
 			"ruralDel": "",
 			"zipCode4": null,
 			"zipCode5": null,
 			"faxNumber": null,
 			"addressType": null,
 			"country": "",
 			"prefix": null,
 			"suffix": null,
 			"postbox": null,
 			"companyname": null,
 			"ruralrte": "",
 			"county": null,
 			"address3": null,
 			"postalcode": "48423",
 			"version": 0,
 			"lastModifiedDate": null,
 			"addressConfirmationStatus": null
 		},
 		"tradeInDevicesDetails": null,
 		"tradeInPromoDetails": null,
 		"transformedTradeInPromoDetails": null,
 		"subOrders": null,
 		"comboOrder": false,
 		"totalDueToday": "33.00",
 		"totalDueMonthly": "68.73",
 		"subTotalDueToday": "0.00",
 		"securityDepositAmount": "0.00",
 		"stateSalesTax": "33.00",
 		"employeeDiscount": "33.00",
 		"pastDueExist": false,
 		"pastDueAmountPaid": false,
 		"pastDueAmount": "0.00",
 		"shippingInfo": {
 			"shippingInfoUpdated": false,
 			"sameAsBilling": true,
 			"ispuEligibleFlag": true,
 			"addressInfo": {
 				"firstName": "RAVI",
 				"lastName": "JACOBS",
 				"companyName": null,
 				"address1": "8217 KENSINGTON BLVD APT 582B",
 				"address2": null,
 				"city": "Davison",
 				"state": "MI",
 				"zipcode": "48423",
 				"businessName": null,
 				"postalCode": null,
 				"email": "VZW@VZW.COM",
 				"phoneNumber": "9204360630"
 			},
 			"contactInfo": {
 				"emailAddress": "VZW@VZW.COM",
 				"phoneNumber": "9204360630",
 				"firstName": "RAVI",
 				"lastName": "JACOBS",
 				"smsMdn": null,
 				"activeSMSCapableMtnList": ["8108692805", "8108454548", "8108695482"]
 			},
 			"shippingTypesInfo": [{
 				"estimatedDeliveryDate": "2018-05-18 00:00:00",
 				"estimatedDeliveryDateText": "Fri 5/18",
 				"shippingDescription": "Free 2 Day by 8pm",
 				"shippingOptionId": "SHP002",
 				"shippingCost": "0.00",
 				"shortDescription": "Free 2 Day by 8pm",
 				"active": true,
 				"addedShippingOptionId": true,
 				"signatureRequired": "true",
 				"description": "Estimated to arrive on Fri, May 18 if ordered by 4pm today. Signature required.",
 				"depletionLocationCode": null,
 				"sddAvailableWindows": null
 			}, {
 				"estimatedDeliveryDate": "2018-05-17 00:00:00",
 				"estimatedDeliveryDateText": "Thu 5/17",
 				"shippingDescription": "Next Day by 8pm",
 				"shippingOptionId": "SHP004",
 				"shippingCost": "12.99",
 				"shortDescription": "Next Day by 8pm",
 				"active": true,
 				"addedShippingOptionId": false,
 				"signatureRequired": "true",
 				"description": "Estimated to arrive on Thu, May 17. Next Day by 8pm. Signature required.",
 				"depletionLocationCode": null,
 				"sddAvailableWindows": null
 			}, {
 				"estimatedDeliveryDate": "2018-05-17 10:30:00",
 				"estimatedDeliveryDateText": "Thu 5/17 by 10:30AM",
 				"shippingDescription": "Next Day by 10:30am",
 				"shippingOptionId": "SHP005",
 				"shippingCost": "14.99",
 				"shortDescription": "Next Day by 10:30am",
 				"active": true,
 				"addedShippingOptionId": false,
 				"signatureRequired": "true",
 				"description": "Estimated to arrive on Thu, May 17. Next Day by 10:30am. Signature required.",
 				"depletionLocationCode": null,
 				"sddAvailableWindows": null
 			}],
 			"storeDetail": {
 				"storeHeader": null,
 				"storeName": null,
 				"storeAddress": null,
 				"deviceAvailable": false,
 				"distance": null,
 				"appendedStoreTiming": null,
 				"longitude": null,
 				"storeId": null,
 				"netaceLocationCode": null,
 				"latitude": null,
 				"seoUrlName": null,
 				"storeClosingTime": null
 			},
 			"tradeIn": false,
 			"tradeInAddress": null,
 			"nonSddEligibleMsg": null,
 			"selectedSDDWindow": null,
 			"poboMessage": null,
 			"ispudetailsInfo": {
 				"storeAddress": null,
 				"storeHours": null,
 				"storeId": null,
 				"storeName": null,
 				"phoneNumber": null,
 				"distance": null,
 				"totalItems": 0,
 				"availItems": 0,
 				"latitdude": 0.0,
 				"longtitude": 0.0,
 				"availItemName": null
 			}
 		},
 		"billingInfo": {
 			"billToAccountEligible": true,
 			"creditCardZipEditable": true,
 			"billingAddress": {
 				"firstName": "RAVI",
 				"lastName": "JACOBS",
 				"businessName": null,
 				"zipcode": "48423",
 				"state": "MI",
 				"address2": null,
 				"address1": "8217 KENSINGTON BLVD APT 582B",
 				"companyName": null,
 				"city": "Davison"
 			},
 			"masterpass3DSecure": null,
 			"billToAccountNumber": "#XXXXXXX-0001",
 			"creditCardInfo": {
 				"savedCardNickName": null,
 				"preselectCard": null,
 				"creditCardNumber": null,
 				"creditCardExpMonth": null,
 				"creditCardExpYear": null,
 				"billingZipCode": null,
 				"creditCardType": null,
 				"creditCardVerificationNumber": null,
 				"creditCardBIN": null,
 				"cvvRequired": false
 			},
 			"selectedPaymentMode": "BTA",
 			"giftCardList": [],
 			"savedCardInfo": [{
 				"savedCardNickName": "BOGUS",
 				"preselectCard": null,
 				"creditCardNumber": "XXXX-XXXX-XXXX-7389",
 				"creditCardExpMonth": "12",
 				"creditCardExpYear": "29",
 				"billingZipCode": "48423",
 				"creditCardType": "masterCard",
 				"creditCardVerificationNumber": null,
 				"creditCardBIN": "509133",
 				"cvvRequired": false
 			}],
 			"applePayResponseInfo": null,
 			"masterpassResponseInfo": {
 				"emailAddress": null,
 				"cardType": null,
 				"lastDigits": null,
 				"creditCardBIN": null
 			},
 			"masterpassError": false,
 			"masterpassErrorMessage": null,
 			"paypalEmailAddress": null,
 			"expirationMonths": ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
 			"expirationYears": ["2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027"]
 		},
 		"devices": {
 			"dueMonthly": 68.73,
 			"totalActivationFee": 0.0,
 			"deviceTotalDueMonthly": 68.73,
 			"dueToday": 0.0,
 			"accessories": [],
 			"accessoriesBundle": [],
 			"items": [{
 				"deviceName": "iPhone&reg; 7",
 				"dueMonthly": "22.91",
 				"dueToday": "0.00",
 				"upgradeFee": "0.00",
 				"activationFee": "0.00",
 				"dueTodayOriginal": "0.00",
 				"dueMonthlyOriginal": null,
 				"dueTodayDiscounted": false,
 				"dueMonthlyDiscounted": false,
 				"mtn": null,
 				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-med$&fmt=jpeg&wid=75&hei=150",
 				"protectionFeature": {
 					"name": "Decline Equipment Protection",
 					"mtn": null,
 					"price": "0.00",
 					"discountPrice": "0.00",
 					"retailPrice": "0.00",
 					"hasEcpdDiscount": false,
 					"promoMessage": null,
 					"originalPrice": "0.00",
 					"wasPrice": "0.00",
 					"deviceName": null,
 					"color": null,
 					"size": null,
 					"instantCreditAmount": "0.00",
 					"amountAfterInstantCredit": "0.00",
 					"disountedInstantCreditAmt": "0.00"
 				},
 				"optionalFeatures": [],
 				"installmentBalance": "549.99",
 				"edgeRetailPrice": "549.99",
 				"edgeItemDownPaymentAmount": "0.00",
 				"mailInRebateAmount": "0.00",
 				"transferredFromMtn": null,
 				"devicePromotionList": [],
 				"bicOfferApplied": false,
 				"bicContractPrice": "0.00",
 				"bicDiscountedContractPrice": "-1.00",
 				"bicAdditionalContractText": null,
 				"bicMessageMap": null,
 				"edgeUpAmount": 0.0,
 				"displayDeviceDueMonthly": 22.91,
 				"deviceLACFee": "0.00",
 				"manufactureName": "Apple",
 				"color": "Gold",
 				"colorCode": "#CFBEA9",
 				"size": "32GB",
 				"displayName": "iPhone&reg; 7",
 				"contractTerm": "99",
 				"edgeUpBuyOutAmount": 0.0,
 				"fullRetailPrice": "549.99",
 				"alwaysEligibleForUpgrade": false,
 				"numberShareDevice": false,
 				"activationFeeText": null,
 				"numberSharedMtn": null,
 				"promoContentText": null,
 				"itemOnJaxPlan": false,
 				"humCarDetails": null,
 				"simDetails": null,
 				"imeiId": null,
 				"displayImeiId": null,
 				"poboDateLabel": null,
 				"nickName": null,
 				"planCommerceItemId": null,
 				"displayMtn": null,
 				"promoOfferText": null,
 				"promoApplied": false,
 				"commerceItemId": "Sf98cbf72deaa904c1dc8b4f60092b06a{ss3}_device_1",
 				"loanTerm": 24,
 				"sbdHeaderMsg": null,
 				"percentage": null,
 				"waivedActivationFeePromo": false,
 				"flow": "AAL",
 				"instantCreditAmount": "0.00",
 				"amountAfterInstantCredit": "0.00",
 				"eupdevice": false,
 				"accessory": false,
 				"edgeDevice": true,
 				"disountedInstantCreditAmt": "0.00"
 			}, {
 				"deviceName": "iPhone&reg; 7",
 				"dueMonthly": "22.91",
 				"dueToday": "0.00",
 				"upgradeFee": "0.00",
 				"activationFee": "0.00",
 				"dueTodayOriginal": "0.00",
 				"dueMonthlyOriginal": null,
 				"dueTodayDiscounted": false,
 				"dueMonthlyDiscounted": false,
 				"mtn": null,
 				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-med$&fmt=jpeg&wid=75&hei=150",
 				"protectionFeature": {
 					"name": "Decline Equipment Protection",
 					"mtn": null,
 					"price": "0.00",
 					"discountPrice": "0.00",
 					"retailPrice": "0.00",
 					"hasEcpdDiscount": false,
 					"promoMessage": null,
 					"originalPrice": "0.00",
 					"wasPrice": "0.00",
 					"deviceName": null,
 					"color": null,
 					"size": null,
 					"instantCreditAmount": "0.00",
 					"amountAfterInstantCredit": "0.00",
 					"disountedInstantCreditAmt": "0.00"
 				},
 				"optionalFeatures": [],
 				"installmentBalance": "549.99",
 				"edgeRetailPrice": "549.99",
 				"edgeItemDownPaymentAmount": "0.00",
 				"mailInRebateAmount": "0.00",
 				"transferredFromMtn": null,
 				"devicePromotionList": [],
 				"bicOfferApplied": false,
 				"bicContractPrice": "0.00",
 				"bicDiscountedContractPrice": "-1.00",
 				"bicAdditionalContractText": null,
 				"bicMessageMap": null,
 				"edgeUpAmount": 0.0,
 				"displayDeviceDueMonthly": 22.91,
 				"deviceLACFee": "0.00",
 				"manufactureName": "Apple",
 				"color": "Gold",
 				"colorCode": "#CFBEA9",
 				"size": "32GB",
 				"displayName": "iPhone&reg; 7",
 				"contractTerm": "99",
 				"edgeUpBuyOutAmount": 0.0,
 				"fullRetailPrice": "549.99",
 				"alwaysEligibleForUpgrade": false,
 				"numberShareDevice": false,
 				"activationFeeText": null,
 				"numberSharedMtn": null,
 				"promoContentText": null,
 				"itemOnJaxPlan": false,
 				"humCarDetails": null,
 				"simDetails": null,
 				"imeiId": null,
 				"displayImeiId": null,
 				"poboDateLabel": null,
 				"nickName": null,
 				"planCommerceItemId": null,
 				"displayMtn": null,
 				"promoOfferText": null,
 				"promoApplied": false,
 				"commerceItemId": "Sf98cbf72deaa904c1dc8b4f60092b06a{ss3}_device_1",
 				"loanTerm": 24,
 				"sbdHeaderMsg": null,
 				"percentage": null,
 				"waivedActivationFeePromo": false,
 				"flow": "AAL",
 				"instantCreditAmount": "0.00",
 				"amountAfterInstantCredit": "0.00",
 				"eupdevice": false,
 				"accessory": false,
 				"edgeDevice": true,
 				"disountedInstantCreditAmt": "0.00"
 			}, {
 				"deviceName": "iPhone&reg; 7",
 				"dueMonthly": "22.91",
 				"dueToday": "0.00",
 				"upgradeFee": "0.00",
 				"activationFee": "0.00",
 				"dueTodayOriginal": "0.00",
 				"dueMonthlyOriginal": null,
 				"dueTodayDiscounted": false,
 				"dueMonthlyDiscounted": false,
 				"mtn": null,
 				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-med$&fmt=jpeg&wid=75&hei=150",
 				"protectionFeature": {
 					"name": "Decline Equipment Protection",
 					"mtn": null,
 					"price": "0.00",
 					"discountPrice": "0.00",
 					"retailPrice": "0.00",
 					"hasEcpdDiscount": false,
 					"promoMessage": null,
 					"originalPrice": "0.00",
 					"wasPrice": "0.00",
 					"deviceName": null,
 					"color": null,
 					"size": null,
 					"instantCreditAmount": "0.00",
 					"amountAfterInstantCredit": "0.00",
 					"disountedInstantCreditAmt": "0.00"
 				},
 				"optionalFeatures": [],
 				"installmentBalance": "549.99",
 				"edgeRetailPrice": "549.99",
 				"edgeItemDownPaymentAmount": "0.00",
 				"mailInRebateAmount": "0.00",
 				"transferredFromMtn": null,
 				"devicePromotionList": [],
 				"bicOfferApplied": false,
 				"bicContractPrice": "0.00",
 				"bicDiscountedContractPrice": "-1.00",
 				"bicAdditionalContractText": null,
 				"bicMessageMap": null,
 				"edgeUpAmount": 0.0,
 				"displayDeviceDueMonthly": 22.91,
 				"deviceLACFee": "0.00",
 				"manufactureName": "Apple",
 				"color": "Gold",
 				"colorCode": "#CFBEA9",
 				"size": "32GB",
 				"displayName": "iPhone&reg; 7",
 				"contractTerm": "99",
 				"edgeUpBuyOutAmount": 0.0,
 				"fullRetailPrice": "549.99",
 				"alwaysEligibleForUpgrade": false,
 				"numberShareDevice": false,
 				"activationFeeText": null,
 				"numberSharedMtn": null,
 				"promoContentText": null,
 				"itemOnJaxPlan": false,
 				"humCarDetails": null,
 				"simDetails": null,
 				"imeiId": null,
 				"displayImeiId": null,
 				"poboDateLabel": null,
 				"nickName": null,
 				"planCommerceItemId": null,
 				"displayMtn": null,
 				"promoOfferText": null,
 				"promoApplied": false,
 				"commerceItemId": "Sf98cbf72deaa904c1dc8b4f60092b06a{ss3}_device_1",
 				"loanTerm": 24,
 				"sbdHeaderMsg": null,
 				"percentage": null,
 				"waivedActivationFeePromo": false,
 				"flow": "AAL",
 				"instantCreditAmount": "0.00",
 				"amountAfterInstantCredit": "0.00",
 				"eupdevice": false,
 				"accessory": false,
 				"edgeDevice": true,
 				"disountedInstantCreditAmt": "0.00"
 			}],
 			"buddyUpgrade": false
 		},
 		"accessories": null,
 		"selectedShippingType": {
 			"type": "SHIPPING",
 			"shippingTypeName": "FREE 2 Day by 8pm",
 			"price": 0.0,
 			"discountPrice": 0.0,
 			"estimatedDeliveryDate": null
 		},
 		"dueMonthlyView": {
 			"title": "Due Monthly (device only)",
 			"dueMonthlyPrice": "68.73",
 			"items": [{
 				"name": "iPhone&reg; 7",
 				"description": "iPhone&reg; 7",
 				"manufacturer": "Apple",
 				"color": "Gold",
 				"size": "32GB",
 				"priceBreakDown": [{
 					"lable": "Line Access Charge",
 					"price": "0.00",
 					"description": null,
 					"linkText": null,
 					"linkUrl": null,
 					"originalPrice": 0.0,
 					"tmpMdOpted": false,
 					"discountedEdgeRetailPrice": null,
 					"sbdPromoMsg": null,
 					"sbdDiscountAmount": 0.0,
 					"sbdItemMonthlyAmount": 0.0,
 					"itemRetailPrice": 0.0,
 					"itemMonthlyPrice": 0.0,
 					"itemStrikeThroughPrice": 0.0,
 					"noOfBicOccurences": 0
 				}, {
 					"lable": "Decline Equipment Protection",
 					"price": "0.00",
 					"description": null,
 					"linkText": null,
 					"linkUrl": null,
 					"originalPrice": 0.0,
 					"tmpMdOpted": false,
 					"discountedEdgeRetailPrice": null,
 					"sbdPromoMsg": null,
 					"sbdDiscountAmount": 0.0,
 					"sbdItemMonthlyAmount": 0.0,
 					"itemRetailPrice": 0.0,
 					"itemMonthlyPrice": 0.0,
 					"itemStrikeThroughPrice": 0.0,
 					"noOfBicOccurences": 0
 				}, {
 					"lable": "Device Payment",
 					"price": "22.91",
 					"description": "For 24 months, 0% APR Retail price: $549.99",
 					"linkText": null,
 					"linkUrl": null,
 					"originalPrice": 0.0,
 					"tmpMdOpted": false,
 					"discountedEdgeRetailPrice": null,
 					"sbdPromoMsg": null,
 					"sbdDiscountAmount": 0.0,
 					"sbdItemMonthlyAmount": 0.0,
 					"itemRetailPrice": 0.0,
 					"itemMonthlyPrice": 22.91,
 					"itemStrikeThroughPrice": 0.0,
 					"noOfBicOccurences": 0
 				}],
 				"nickName": null,
 				"planCommerceItemId": null,
 				"displayMtn": null,
 				"numberShareDevice": false,
 				"edge": true
 			}, {
 				"name": "iPhone&reg; 7",
 				"description": "iPhone&reg; 7",
 				"manufacturer": "Apple",
 				"color": "Gold",
 				"size": "32GB",
 				"priceBreakDown": [{
 					"lable": "Line Access Charge",
 					"price": "0.00",
 					"description": null,
 					"linkText": null,
 					"linkUrl": null,
 					"originalPrice": 0.0,
 					"tmpMdOpted": false,
 					"discountedEdgeRetailPrice": null,
 					"sbdPromoMsg": null,
 					"sbdDiscountAmount": 0.0,
 					"sbdItemMonthlyAmount": 0.0,
 					"itemRetailPrice": 0.0,
 					"itemMonthlyPrice": 0.0,
 					"itemStrikeThroughPrice": 0.0,
 					"noOfBicOccurences": 0
 				}, {
 					"lable": "Decline Equipment Protection",
 					"price": "0.00",
 					"description": null,
 					"linkText": null,
 					"linkUrl": null,
 					"originalPrice": 0.0,
 					"tmpMdOpted": false,
 					"discountedEdgeRetailPrice": null,
 					"sbdPromoMsg": null,
 					"sbdDiscountAmount": 0.0,
 					"sbdItemMonthlyAmount": 0.0,
 					"itemRetailPrice": 0.0,
 					"itemMonthlyPrice": 0.0,
 					"itemStrikeThroughPrice": 0.0,
 					"noOfBicOccurences": 0
 				}, {
 					"lable": "Device Payment",
 					"price": "22.91",
 					"description": "For 24 months, 0% APR Retail price: $549.99",
 					"linkText": null,
 					"linkUrl": null,
 					"originalPrice": 0.0,
 					"tmpMdOpted": false,
 					"discountedEdgeRetailPrice": null,
 					"sbdPromoMsg": null,
 					"sbdDiscountAmount": 0.0,
 					"sbdItemMonthlyAmount": 0.0,
 					"itemRetailPrice": 0.0,
 					"itemMonthlyPrice": 22.91,
 					"itemStrikeThroughPrice": 0.0,
 					"noOfBicOccurences": 0
 				}],
 				"nickName": null,
 				"planCommerceItemId": null,
 				"displayMtn": null,
 				"numberShareDevice": false,
 				"edge": true
 			}, {
 				"name": "iPhone&reg; 7",
 				"description": "iPhone&reg; 7",
 				"manufacturer": "Apple",
 				"color": "Gold",
 				"size": "32GB",
 				"priceBreakDown": [{
 					"lable": "Line Access Charge",
 					"price": "0.00",
 					"description": null,
 					"linkText": null,
 					"linkUrl": null,
 					"originalPrice": 0.0,
 					"tmpMdOpted": false,
 					"discountedEdgeRetailPrice": null,
 					"sbdPromoMsg": null,
 					"sbdDiscountAmount": 0.0,
 					"sbdItemMonthlyAmount": 0.0,
 					"itemRetailPrice": 0.0,
 					"itemMonthlyPrice": 0.0,
 					"itemStrikeThroughPrice": 0.0,
 					"noOfBicOccurences": 0
 				}, {
 					"lable": "Decline Equipment Protection",
 					"price": "0.00",
 					"description": null,
 					"linkText": null,
 					"linkUrl": null,
 					"originalPrice": 0.0,
 					"tmpMdOpted": false,
 					"discountedEdgeRetailPrice": null,
 					"sbdPromoMsg": null,
 					"sbdDiscountAmount": 0.0,
 					"sbdItemMonthlyAmount": 0.0,
 					"itemRetailPrice": 0.0,
 					"itemMonthlyPrice": 0.0,
 					"itemStrikeThroughPrice": 0.0,
 					"noOfBicOccurences": 0
 				}, {
 					"lable": "Device Payment",
 					"price": "22.91",
 					"description": "For 24 months, 0% APR Retail price: $549.99",
 					"linkText": null,
 					"linkUrl": null,
 					"originalPrice": 0.0,
 					"tmpMdOpted": false,
 					"discountedEdgeRetailPrice": null,
 					"sbdPromoMsg": null,
 					"sbdDiscountAmount": 0.0,
 					"sbdItemMonthlyAmount": 0.0,
 					"itemRetailPrice": 0.0,
 					"itemMonthlyPrice": 22.91,
 					"itemStrikeThroughPrice": 0.0,
 					"noOfBicOccurences": 0
 				}],
 				"nickName": null,
 				"planCommerceItemId": null,
 				"displayMtn": null,
 				"numberShareDevice": false,
 				"edge": true
 			}],
 			"tmpMd": null
 		},
 		"balanceCreditCardAmount": "33.00",
 		"cpcOrder": true,
 		"totalDueMonthlyPlanAndDevice": "68.73",
 		"deviceConfigInfo": {
 			"devices": [{
 				"deviceId": "Sf98cbf72deaa904c1dc8b4f60092b06a{ss3}_device_1",
 				"deviceName": "iPhone&reg; 7",
 				"deviceSetupMode": null,
 				"mtnNumber": null,
 				"flow": "AAL",
 				"serviceAddress": {
 					"firstName": "RAVI",
 					"lastName": "JACOBS",
 					"address1": "8217 KENSINGTON BLVD APT 582B",
 					"address2": "",
 					"city": "Davison",
 					"state": "MI",
 					"zipCode": "48423",
 					"emailAddress": "VZW@VZW.COM",
 					"phoneNumber": "9204360630"
 				},
 				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-med$&fmt=jpeg&wid=75&hei=150",
 				"mobileAppImageName": null,
 				"npaNxxnumber": "248-369-XXXX",
 				"npnxxCustomerSelection": null,
 				"npaNxxdetails": null,
 				"manufactureName": "Apple",
 				"color": "Gold",
 				"size": "32GB",
 				"numberShareDevice": false,
 				"numberSharedMtn": null,
 				"portInDetails": null
 			}],
 			"npaNxxdetails": {
 				"zipCode": null,
 				"state": null,
 				"city": null,
 				"success": false,
 				"mtns": null,
 				"states": null,
 				"cities": null
 			},
 			"deviceAddressUpdated": false,
 			"accessories": null
 		},
 		"checkoutStates": {
 			"shippingAddressRequired": false,
 			"shippingAddressChangeRequired": false,
 			"shippingMethodRequired": false,
 			"paymentRequired": false,
 			"pastDuePaymentRequired": false,
 			"showPaymentSection": true,
 			"showShippingAddress": true,
 			"showDeliveryMethod": true,
 			"newCard": false,
 			"cvvNeeded": false
 		},
 		"totalEdgeItemDownPaymentAmount": "0.00",
 		"totalEdgeUpAmount": "0.00",
 		"totalEdgeUpBuyOutAmount": "0.00",
 		"multiOrderDetails": null,
 		"hasRio": false,
 		"splitShipment": false
 	}
 };*/
 {
	"output": {
		"title": "You're all set.",
		"subtitle": null,
		"orderId": "801701970836573",
		"estimatedDelivery": "",
		"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/1.3_MV_BuyandUpgrade_ConfirmationPage_Interstital?$device-med$",
		"tradeInStatus": false,
		"confirmationMessage": "Thanks for ordering from verizonwireless.com. Your order receipt is sent to VZW@VZW.COM.",
		"doneButtonText": "Got it",
		"doneButtonLink": "/od/cust/auth/shoplanding/",
		"userNote": "TODO",
		"notNowButtonText": "TODO",
		"notNowButtonLink": "TODO",
		"learnHowButtonText": null,
		"learnHowButtonLink": "/od/cust/auth/learnHow",
		"numberOfDevice": 1,
		"confirmationNumberText": "Confirmation Number",
		"iconicFlow": true,
		"protectionURL": null,
		"accessoriesURL": null,
		"tapFlag": false,
		"cjmTagUrl": null,
		"pepperJamTagUrl": null,
		"selectedPaymentMode": null,
		"confirmationEmail": "VZW@VZW.COM",
		"plans": {
			"dueMonthly": null,
			"dueToday": null,
			"planOnlyDueMonthly": null,
			"items": [{
				"planType": null,
				"lineAccessCharges": null,
				"accountAccess": null,
				"accountLevelFeatures": null,
				"totalMonthlyPlanCost": null,
				"spoBadgeMessage": null,
				"planDisplayName": "Go Unlimited",
				"planImageURL": "//ss7.vzw.com/is/image/VerizonWireless/U_083s_022317",
				"planLetter": null,
				"planDescrption": null,
				"planDescription": null,
				"quantity": 0,
				"skuId": "sku3060010",
				"productId": "plan5600003",
				"itemAmount": "-179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.00",
				"itemAmountOriginal": "70.00",
				"dueMonthly": "70.00",
				"dueMonthlyOriginal": "0.00",
				"itemDiscount": "179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.00",
				"displayName": null,
				"skuDisplayName": null,
				"listPrice": "70.00",
				"rawTotalAmount": "0.00",
				"planGroupCode": null,
				"autoPayEnabled": false,
				"numberSharePlan": false,
				"planCommerceItemId": "S99a7227ed1bd93ab779b57f8199c60ab{d3}_plan_1",
				"autoPayPrice": "0.00",
				"autoPayText": "Save $0.0 when you signup for paper-free billing and AutoPay.",
				"termsAndConditionKey": null,
				"unitOfMeasure": "GB",
				"planSize": "50"
			}, {
				"planType": null,
				"lineAccessCharges": null,
				"accountAccess": null,
				"accountLevelFeatures": null,
				"totalMonthlyPlanCost": null,
				"spoBadgeMessage": null,
				"planDisplayName": "CONNECTED HOME DATA ONLY 20GB",
				"planImageURL": "",
				"planLetter": null,
				"planDescrption": null,
				"planDescription": null,
				"quantity": 0,
				"skuId": "sku2190340",
				"productId": "plan3200001",
				"itemAmount": "0.00",
				"itemAmountOriginal": "90.00",
				"dueMonthly": "90.00",
				"dueMonthlyOriginal": "0.00",
				"itemDiscount": "90.00",
				"displayName": null,
				"skuDisplayName": null,
				"listPrice": "90.00",
				"rawTotalAmount": "0.00",
				"planGroupCode": null,
				"autoPayEnabled": false,
				"numberSharePlan": false,
				"planCommerceItemId": "S99a7227ed1bd93ab779b57f8199c60ab{d3}_plan_2",
				"autoPayPrice": "0.00",
				"autoPayText": "Save $0.0 when you signup for paper-free billing and AutoPay.",
				"termsAndConditionKey": null,
				"unitOfMeasure": "GB",
				"planSize": "20"
			}, {
				"planType": null,
				"lineAccessCharges": null,
				"accountAccess": null,
				"accountLevelFeatures": null,
				"totalMonthlyPlanCost": null,
				"spoBadgeMessage": null,
				"planDisplayName": "WIRELESS HOME PHONE UNLIMITED",
				"planImageURL": "",
				"planLetter": null,
				"planDescrption": null,
				"planDescription": null,
				"quantity": 0,
				"skuId": "sku665243",
				"productId": "plan160005",
				"itemAmount": "0.00",
				"itemAmountOriginal": "20.00",
				"dueMonthly": "20.00",
				"dueMonthlyOriginal": "0.00",
				"itemDiscount": "20.00",
				"displayName": null,
				"skuDisplayName": null,
				"listPrice": "20.00",
				"rawTotalAmount": "0.00",
				"planGroupCode": null,
				"autoPayEnabled": false,
				"numberSharePlan": false,
				"planCommerceItemId": "S99a7227ed1bd93ab779b57f8199c60ab{d3}_plan_3",
				"autoPayPrice": "0.00",
				"autoPayText": "Save $0.0 when you signup for paper-free billing and AutoPay.",
				"termsAndConditionKey": null,
				"unitOfMeasure": null,
				"planSize": null
			}, {
				"planType": null,
				"lineAccessCharges": null,
				"accountAccess": null,
				"accountLevelFeatures": null,
				"totalMonthlyPlanCost": null,
				"spoBadgeMessage": null,
				"planDisplayName": "1GB Single Device Plan",
				"planImageURL": "",
				"planLetter": null,
				"planDescrption": null,
				"planDescription": null,
				"quantity": 0,
				"skuId": "sku2290336",
				"productId": "plan3480073",
				"itemAmount": "0.00",
				"itemAmountOriginal": "15.00",
				"dueMonthly": "15.00",
				"dueMonthlyOriginal": "0.00",
				"itemDiscount": "15.00",
				"displayName": null,
				"skuDisplayName": null,
				"listPrice": "15.00",
				"rawTotalAmount": "0.00",
				"planGroupCode": null,
				"autoPayEnabled": false,
				"numberSharePlan": false,
				"planCommerceItemId": "S99a7227ed1bd93ab779b57f8199c60ab{d3}_plan_4",
				"autoPayPrice": "0.00",
				"autoPayText": "Save $0.0 when you signup for paper-free billing and AutoPay.",
				"termsAndConditionKey": null,
				"unitOfMeasure": "GB",
				"planSize": "1"
			}],
			"upgradeDevices": null,
			"newDevices": null,
			"existingDevices": [{
				"name": null,
				"price": "90.00",
				"discountPrice": 90.0,
				"hasEcpdDiscount": false,
				"mtn": "6232381661",
				"listPrice": 90.0,
				"deviceLineItemId": null,
				"discountPriceVal": null,
				"planCommerceItemId": "S99a7227ed1bd93ab779b57f8199c60ab{d3}_plan_2",
				"nickName": "6232381661",
				"numberShareDevice": false,
				"featureDropped": false
			}, {
				"name": null,
				"price": "70.00",
				"discountPrice": 70.0,
				"hasEcpdDiscount": false,
				"mtn": "6026193200",
				"listPrice": 70.0,
				"deviceLineItemId": null,
				"discountPriceVal": null,
				"planCommerceItemId": "S99a7227ed1bd93ab779b57f8199c60ab{d3}_plan_1",
				"nickName": "6026193200",
				"numberShareDevice": false,
				"featureDropped": false
			}, {
				"name": null,
				"price": "20.00",
				"discountPrice": 20.0,
				"hasEcpdDiscount": false,
				"mtn": "6234352641",
				"listPrice": 20.0,
				"deviceLineItemId": null,
				"discountPriceVal": null,
				"planCommerceItemId": "S99a7227ed1bd93ab779b57f8199c60ab{d3}_plan_3",
				"nickName": "6234352641",
				"numberShareDevice": false,
				"featureDropped": false
			}, {
				"name": null,
				"price": "15.00",
				"discountPrice": 15.0,
				"hasEcpdDiscount": false,
				"mtn": "6023906305",
				"listPrice": 15.0,
				"deviceLineItemId": null,
				"discountPriceVal": null,
				"planCommerceItemId": "S99a7227ed1bd93ab779b57f8199c60ab{d3}_plan_4",
				"nickName": "6023906305",
				"numberShareDevice": false,
				"featureDropped": false
			}, {
				"name": null,
				"price": "15.00",
				"discountPrice": 15.0,
				"hasEcpdDiscount": false,
				"mtn": "4804317571",
				"listPrice": 15.0,
				"deviceLineItemId": null,
				"discountPriceVal": null,
				"planCommerceItemId": "S99a7227ed1bd93ab779b57f8199c60ab{d3}_plan_4",
				"nickName": "4804317571",
				"numberShareDevice": false,
				"featureDropped": false
			}],
			"dueMonthlyPlanWithLAC": null,
			"discountedDueMonthlyPlanWithLAC": null,
			"hasEcpdDiscount": false,
			"totalLineAccessCharges": null
		},
		"featureList": [{
			"id": "S99a7227ed1bd93ab779b57f8199c60ab{d3}_feature_1",
			"quantity": 1,
			"type": "INSUR,D",
			"skuId": "sku401064",
			"productId": "sfo80072",
			"sorId": "66332",
			"itemAmount": 0.0,
			"itemAmountOriginal": 0.0,
			"dueMonthly": 0.0,
			"dueMonthlyOriginal": null,
			"itemDiscount": 0.0,
			"displayName": "Decline Equipment Protection",
			"skuDisplayName": null,
			"listPrice": 0.0,
			"rawTotalAmount": 0.0,
			"pricingDetails": [{
				"pricingAdjustmentId": null,
				"itemId": "S99a7227ed1bd93ab779b57f8199c60ab{d3}_feature_1",
				"orderId": "S99a7227ed1bd93ab779b57f8199c60ab{d3}",
				"offerId": null,
				"offerAmount": 0.0,
				"description": "List Price description",
				"offerType": null,
				"priceListId": null,
				"listPrice": 0.0,
				"offerName": null,
				"creationDate": 1527016733690,
				"lastModifiedDate": 1527016733690,
				"version": 1
			}],
			"orderId": "S99a7227ed1bd93ab779b57f8199c60ab{d3}",
			"version": 1,
			"delete": false,
			"inventoryLevel": 0,
			"taxDetails": null,
			"itemTaxes": 0.0,
			"deviceLineItemId": "S99a7227ed1bd93ab779b57f8199c60ab{d3}_device_1",
			"featureCharge": 0.0,
			"featureType": "INS",
			"lastModifiedDate": 1527016723348
		}],
		"accessoryList": null,
		"paymentGroup": null,
		"contactInfo": {
			"id": null,
			"emailAddress": "VZW@VZW.COM",
			"phoneNumber": "4636336462",
			"lastName": "PHILLIPS",
			"firstName": "JAKE",
			"zipCode": "85302",
			"orderId": null,
			"userId": null,
			"npaNxxNumber": null,
			"address1": "6201 W OLIVE AVE APT 3113",
			"address2": null,
			"city": "Glendale",
			"state": "AZ",
			"addressVerified": true,
			"textAlertOptin": false,
			"newsLetterOptin": false,
			"paperFreeBillingIndicatorFlag": false,
			"middleName": null,
			"firmName": null,
			"businessName": null,
			"apartmentNum": "3113",
			"addressDirection": "",
			"poBox": "",
			"streetNumber": "6201",
			"streetName": "W OLIVE",
			"streetType": "AVE",
			"ruralRoute": null,
			"ruralDel": "",
			"zipCode4": null,
			"zipCode5": null,
			"faxNumber": null,
			"addressType": null,
			"country": "",
			"prefix": null,
			"suffix": null,
			"postbox": null,
			"companyname": null,
			"ruralrte": "",
			"county": null,
			"address3": null,
			"postalcode": "85302",
			"version": 0,
			"lastModifiedDate": null,
			"addressConfirmationStatus": null
		},
		"tradeInDevicesDetails": null,
		"tradeInPromoDetails": null,
		"transformedTradeInPromoDetails": null,
		"subOrders": null,
		"comboOrder": false,
		"totalDueToday": "0.00",
		"totalDueMonthly": "22.91",
		"subTotalDueToday": "0.00",
		"securityDepositAmount": "0.00",
		"stateSalesTax": "0.00",
		"employeeDiscount": "0.00",
		"pastDueExist": false,
		"pastDueAmountPaid": false,
		"pastDueAmount": "0.00",
		"shippingInfo": {
			"shippingInfoUpdated": false,
			"sameAsBilling": true,
			"ispuEligibleFlag": true,
			"addressInfo": {
				"firstName": "JAKE",
				"lastName": "PHILLIPS",
				"companyName": null,
				"address1": "6201 W OLIVE AVE APT 3113",
				"address2": null,
				"city": "Glendale",
				"state": "AZ",
				"zipcode": "85302",
				"businessName": null,
				"postalCode": null,
				"email": "VZW@VZW.COM",
				"phoneNumber": "4636336462"
			},
			"contactInfo": {
				"emailAddress": "VZW@VZW.COM",
				"phoneNumber": "4636336462",
				"firstName": "JAKE",
				"lastName": "PHILLIPS",
				"smsMdn": null,
				"activeSMSCapableMtnList": ["6232381661", "6026193200", "6023906305", "4804317571"]
			},
			"shippingTypesInfo": [{
				"estimatedDeliveryDate": "2018-05-24 00:00:00",
				"estimatedDeliveryDateText": "Thu 5/24",
				"shippingDescription": "Free 2 Day by 8pm",
				"shippingOptionId": "SHP002",
				"shippingCost": "0.00",
				"shortDescription": "Free 2 Day by 8pm",
				"active": true,
				"addedShippingOptionId": true,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Thu, May 24 if ordered by 4pm today. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}, {
				"estimatedDeliveryDate": "2018-05-23 00:00:00",
				"estimatedDeliveryDateText": "Wed 5/23",
				"shippingDescription": "Next Day by 8pm",
				"shippingOptionId": "SHP004",
				"shippingCost": "12.99",
				"shortDescription": "Next Day by 8pm",
				"active": true,
				"addedShippingOptionId": false,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Wed, May 23. Next Day by 8pm. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}, {
				"estimatedDeliveryDate": "2018-05-23 10:30:00",
				"estimatedDeliveryDateText": "Wed 5/23 by 10:30AM",
				"shippingDescription": "Next Day by 10:30am",
				"shippingOptionId": "SHP005",
				"shippingCost": "14.99",
				"shortDescription": "Next Day by 10:30am",
				"active": true,
				"addedShippingOptionId": false,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Wed, May 23. Next Day by 10:30am. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}],
			"storeDetail": {
				"storeHeader": null,
				"storeName": null,
				"storeAddress": null,
				"deviceAvailable": false,
				"distance": null,
				"appendedStoreTiming": null,
				"longitude": null,
				"storeId": null,
				"netaceLocationCode": null,
				"latitude": null,
				"seoUrlName": null,
				"storeClosingTime": null
			},
			"tradeIn": false,
			"tradeInAddress": null,
			"nonSddEligibleMsg": null,
			"selectedSDDWindow": null,
			"poboMessage": null,
			"ispudetailsInfo": {
				"storeAddress": null,
				"storeHours": null,
				"storeId": null,
				"storeName": null,
				"phoneNumber": null,
				"distance": null,
				"totalItems": 0,
				"availItems": 0,
				"latitdude": 0.0,
				"longtitude": 0.0,
				"availItemName": null
			}
		},
		"billingInfo": {
			"billToAccountEligible": false,
			"creditCardZipEditable": false,
			"billingAddress": {
				"firstName": "JAKE",
				"lastName": "PHILLIPS",
				"businessName": null,
				"zipcode": "85302",
				"state": "AZ",
				"address2": null,
				"address1": "6201 W OLIVE AVE APT 3113",
				"companyName": null,
				"city": "Glendale",
				"sameAsShipping": false
			},
			"masterpass3DSecure": null,
			"billToAccountNumber": null,
			"creditCardInfo": {
				"savedCardNickName": null,
				"preselectCard": null,
				"creditCardNumber": "XXXX XXXX XXXX-1111",
				"creditCardExpMonth": "03",
				"creditCardExpYear": "2020",
				"billingZipCode": null,
				"creditCardType": "visa",
				"creditCardVerificationNumber": null,
				"creditCardBIN": null,
				"cvvRequired": false
			},
			"selectedPaymentMode": "newCard",
			"giftCardList": [],
			"savedCardInfo": [],
			"applePayResponseInfo": null,
			"masterpassResponseInfo": {
				"emailAddress": null,
				"cardType": null,
				"lastDigits": null,
				"creditCardBIN": null
			},
			"masterpassError": false,
			"masterpassErrorMessage": null,
			"paypalEmailAddress": null,
			"expirationMonths": ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
			"expirationYears": ["2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027"]
		},
		"devices": {
			"dueMonthly": 22.91,
			"totalActivationFee": 0.0,
			"deviceTotalDueMonthly": 22.91,
			"dueToday": 0.0,
			"accessories": [],
			"accessoriesBundle": [],
			"items": [{
				"deviceName": "iPhone&reg; 7",
				"dueMonthly": "22.91",
				"dueToday": "0.00",
				"upgradeFee": "0.00",
				"originalUpgradeFee": "0.00",
				"activationFee": "30.00",
				"dueTodayOriginal": "0.00",
				"dueMonthlyOriginal": null,
				"dueTodayDiscounted": false,
				"dueMonthlyDiscounted": false,
				"mtn": null,
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-med$&fmt=jpeg&wid=75&hei=150",
				"protectionFeature": {
					"name": "Decline Equipment Protection",
					"mtn": null,
					"price": "0.00",
					"discountPrice": "0.00",
					"retailPrice": "0.00",
					"hasEcpdDiscount": false,
					"promoMessage": null,
					"originalPrice": "0.00",
					"wasPrice": "0.00",
					"deviceName": null,
					"color": null,
					"size": null,
					"instantCreditAmount": "0.00",
					"amountAfterInstantCredit": "0.00",
					"disountedInstantCreditAmt": "0.00"
				},
				"optionalFeatures": [],
				"installmentBalance": "549.99",
				"edgeRetailPrice": "549.99",
				"edgeItemDownPaymentAmount": "0.00",
				"mailInRebateAmount": "0.00",
				"transferredFromMtn": null,
				"devicePromotionList": [],
				"bicOfferApplied": false,
				"bicContractPrice": "0.00",
				"bicDiscountedContractPrice": "-1.00",
				"bicAdditionalContractText": null,
				"bicMessageMap": null,
				"edgeUpAmount": 0.0,
				"displayDeviceDueMonthly": 22.91,
				"deviceLACFee": "0.00",
				"manufactureName": "Apple",
				"color": "Gold",
				"colorCode": "#CFBEA9",
				"size": "32GB",
				"displayName": "iPhone&reg; 7",
				"contractTerm": "99",
				"edgeUpBuyOutAmount": 0.0,
				"fullRetailPrice": "549.99",
				"alwaysEligibleForUpgrade": false,
				"numberShareDevice": false,
				"activationFeeText": "One-time activation fee of $30.00 charged to your next monthly bill.",
				"numberSharedMtn": null,
				"promoContentText": null,
				"itemOnJaxPlan": false,
				"humCarDetails": null,
				"simDetails": null,
				"imeiId": null,
				"displayImeiId": null,
				"poboDateLabel": null,
				"nickName": null,
				"planCommerceItemId": "S99a7227ed1bd93ab779b57f8199c60ab{d3}_plan_1",
				"displayMtn": null,
				"promoOfferText": null,
				"promoApplied": false,
				"commerceItemId": "S99a7227ed1bd93ab779b57f8199c60ab{d3}_device_1",
				"loanTerm": 24,
				"sbdHeaderMsg": null,
				"percentage": null,
				"waivedActivationFeePromo": false,
				"flow": "AAL",
				"edgeDevice": true,
				"eupdevice": false,
				"instantCreditAmount": "0.00",
				"amountAfterInstantCredit": "0.00",
				"accessory": false,
				"disountedInstantCreditAmt": "0.00"
			}],
			"buddyUpgrade": false
		},
		"accessories": null,
		"selectedShippingType": {
			"type": "SHIPPING",
			"shippingTypeName": "FREE 2 Day by 8pm",
			"price": 0.0,
			"discountPrice": 0.0,
			"estimatedDeliveryDate": "2018-05-24 00:00:00"
		},
		"dueMonthlyView": {
			"title": "Due Monthly (device only)",
			"dueMonthlyPrice": "22.91",
			"items": [{
				"name": "iPhone&reg; 7",
				"description": "iPhone&reg; 7",
				"manufacturer": "Apple",
				"color": "Gold",
				"size": "32GB",
				"priceBreakDown": [{
					"lable": "Line Access Charge",
					"price": "0.00",
					"description": null,
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 0.0,
					"itemStrikeThroughPrice": 0.0,
					"noOfBicOccurences": 0
				}, {
					"lable": "Decline Equipment Protection",
					"price": "0.00",
					"description": null,
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 0.0,
					"itemStrikeThroughPrice": 0.0,
					"noOfBicOccurences": 0
				}, {
					"lable": "Device Payment",
					"price": "22.91",
					"description": "For 24 months, 0% APR Retail price: $549.99",
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 22.91,
					"itemStrikeThroughPrice": 0.0,
					"noOfBicOccurences": 0
				}],
				"nickName": null,
				"planCommerceItemId": "S99a7227ed1bd93ab779b57f8199c60ab{d3}_plan_1",
				"displayMtn": null,
				"numberShareDevice": false,
				"edge": true
			}],
			"tmpMd": null
		},
		"balanceCreditCardAmount": "0.00",
		"cpcOrder": true,
		"totalDueMonthlyPlanAndDevice": "302.91",
		"deviceConfigInfo": {
			"devices": [{
				"deviceId": "S99a7227ed1bd93ab779b57f8199c60ab{d3}_device_1",
				"deviceName": "iPhone&reg; 7",
				"deviceSetupMode": null,
				"mtnNumber": null,
				"flow": "AAL",
				"serviceAddress": {
					"firstName": "JAKE",
					"lastName": "PHILLIPS",
					"address1": "6201 W OLIVE AVE APT 3113",
					"address2": "",
					"city": "Glendale",
					"state": "AZ",
					"zipCode": "85302",
					"emailAddress": "VZW@VZW.COM",
					"phoneNumber": "4636336462"
				},
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-med$&fmt=jpeg&wid=75&hei=150",
				"mobileAppImageName": null,
				"npaNxxnumber": "845-395-XXXX",
				"npnxxCustomerSelection": "new",
				"npaNxxdetails": null,
				"manufactureName": "Apple",
				"color": "Gold",
				"size": "32GB",
				"numberShareDevice": false,
				"numberSharedMtn": null,
				"deviceNickName": null,
				"numberSharedDeviceName": null,
				"portInDetails": null
			}],
			"npaNxxdetails": {
				"zipCode": null,
				"state": null,
				"city": null,
				"success": false,
				"mtns": null,
				"states": null,
				"cities": null
			},
			"deviceAddressUpdated": false,
			"accessories": null
		},
		"checkoutStates": {
			"shippingAddressRequired": false,
			"shippingAddressChangeRequired": false,
			"shippingMethodRequired": false,
			"paymentRequired": false,
			"pastDuePaymentRequired": false,
			"showPaymentSection": true,
			"showShippingAddress": true,
			"showDeliveryMethod": true,
			"newCard": false,
			"cvvNeeded": false,
			"contactInfoRequired": false
		},
		"totalEdgeItemDownPaymentAmount": "0.00",
		"totalEdgeUpAmount": "0.00",
		"totalEdgeUpBuyOutAmount": "0.00",
		"multiOrderDetails": null,
		"hasRio": false,
		"splitShipment": false,
		"isHLLPlanInOrder": true
	}
};