/*window.confirmationJSON = {
	"output": {
		"title": "You're all set.",
		"subtitle": null,
		"orderId": "517810430893052",
		"estimatedDelivery": "",
		"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/1.3_MV_BuyandUpgrade_ConfirmationPage_Interstital?$device-med$",
		"tradeInStatus": false,
		"confirmationMessage": "Thanks for ordering from verizonwireless.com. Your order receipt is sent to MANOJ.SUBRAMANI@VERIZON.COM.",
		"doneButtonText": "Got it",
		"doneButtonLink": "/od/cust/auth/shoplanding/",
		"userNote": "TODO",
		"notNowButtonText": "TODO",
		"notNowButtonLink": "TODO",
		"learnHowButtonText": null,
		"learnHowButtonLink": "/od/cust/auth/learnHow",
		"numberOfDevice": 1,
		"confirmationNumberText": "Confirmation Number",
		"iconicFlow": true,
		"protectionURL": null,
		"accessoriesURL": null,
		"tapFlag": false,
		"cjmTagUrl": null,
		"pepperJamTagUrl": null,
		"selectedPaymentMode": null,
		"confirmationEmail": "MANOJ.SUBRAMANI@VERIZON.COM",
		"plans": {
			"dueMonthly": null,
			"dueToday": null,
			"planOnlyDueMonthly": null,
			"items": [{
				"planType": null,
				"lineAccessCharges": null,
				"accountAccess": null,
				"accountLevelFeatures": null,
				"totalMonthlyPlanCost": null,
				"spoBadgeMessage": null,
				"planDisplayName": "Above Unlimited",
				"planImageURL": "//ss7.vzw.com/is/image/VerizonWireless/U_083s_022317",
				"planLetter": null,
				"planDescrption": null,
				"planDescription": null,
				"quantity": 0,
				"skuId": "sku3060011",
				"productId": "plan5600003",
				"itemAmount": 0.0,
				"itemAmountOriginal": 65.0,
				"dueMonthly": 65.0,
				"dueMonthlyOriginal": 0.0,
				"itemDiscount": 0.0,
				"displayName": null,
				"skuDisplayName": null,
				"listPrice": 65.0,
				"rawTotalAmount": 0.0,
				"planGroupCode": null,
				"autoPayEnabled": false,
				"numberSharePlan": false,
				"planCommerceItemId": "Se87532820d2769ca4585f3ef421472ef{d4}_plan_1",
				"autoPayPrice": 0.0,
				"autoPayText": null,
				"termsAndConditionKey": null
			}],
			"upgradeDevices": null,
			"newDevices": null,
			"existingDevices": [{
				"name": null,
				"price": "65.0",
				"discountPrice": 65.0,
				"hasEcpdDiscount": false,
				"mtn": "6188307724",
				"listPrice": 65.0,
				"deviceLineItemId": null,
				"discountPriceVal": null,
				"planCommerceItemId": "Se87532820d2769ca4585f3ef421472ef{d4}_plan_1",
				"nickName": "6188307724",
				"numberShareDevice": false,
				"featureDropped": false
			}, {
				"name": null,
				"price": "65.0",
				"discountPrice": 65.0,
				"hasEcpdDiscount": false,
				"mtn": "6189748060",
				"listPrice": 65.0,
				"deviceLineItemId": null,
				"discountPriceVal": null,
				"planCommerceItemId": "Se87532820d2769ca4585f3ef421472ef{d4}_plan_1",
				"nickName": "6189748060",
				"numberShareDevice": false,
				"featureDropped": false
			}, {
				"name": null,
				"price": "65.0",
				"discountPrice": 65.0,
				"hasEcpdDiscount": false,
				"mtn": "6187929371",
				"listPrice": 65.0,
				"deviceLineItemId": null,
				"discountPriceVal": null,
				"planCommerceItemId": "Se87532820d2769ca4585f3ef421472ef{d4}_plan_1",
				"nickName": "6187929371",
				"numberShareDevice": false,
				"featureDropped": false
			}, {
				"name": null,
				"price": "65.0",
				"discountPrice": 65.0,
				"hasEcpdDiscount": false,
				"mtn": "6183638784",
				"listPrice": 65.0,
				"deviceLineItemId": null,
				"discountPriceVal": null,
				"planCommerceItemId": "Se87532820d2769ca4585f3ef421472ef{d4}_plan_1",
				"nickName": "6183638784",
				"numberShareDevice": false,
				"featureDropped": false
			}],
			"dueMonthlyPlanWithLAC": null,
			"discountedDueMonthlyPlanWithLAC": null,
			"hasEcpdDiscount": false,
			"totalLineAccessCharges": null
		},
		"featureList": [{
			"id": "Se87532820d2769ca4585f3ef421472ef{d4}_feature_1",
			"quantity": 1,
			"type": "INSUR,I",
			"skuId": "sku2880128",
			"productId": "sfo80072",
			"sorId": "85915",
			"itemAmount": 0.0,
			"itemAmountOriginal": 13.0,
			"dueMonthly": 13.0,
			"dueMonthlyOriginal": null,
			"itemDiscount": 0.0,
			"displayName": "Total Mobile Protection",
			"skuDisplayName": null,
			"listPrice": 13.0,
			"rawTotalAmount": 0.0,
			"pricingDetails": [{
				"pricingAdjustmentId": null,
				"itemId": "Se87532820d2769ca4585f3ef421472ef{d4}_feature_1",
				"orderId": "Se87532820d2769ca4585f3ef421472ef{d4}",
				"offerId": null,
				"offerAmount": 0.0,
				"description": "List Price description",
				"offerType": null,
				"priceListId": null,
				"listPrice": 13.0,
				"offerName": null,
				"creationDate": 1526800851212,
				"lastModifiedDate": 1526800851212,
				"version": 1
			}],
			"orderId": "Se87532820d2769ca4585f3ef421472ef{d4}",
			"version": 1,
			"delete": false,
			"inventoryLevel": 0,
			"taxDetails": null,
			"itemTaxes": 0.0,
			"deviceLineItemId": "Se87532820d2769ca4585f3ef421472ef{d4}_device_1",
			"featureCharge": 0.0,
			"featureType": "INS",
			"lastModifiedDate": 1526800849320
		}],
		"accessoryList": [{
			"id": "Se87532820d2769ca4585f3ef421472ef{d4}_accessory_1",
			"quantity": 1,
			"type": null,
			"skuId": "sku1760050",
			"productId": "acc5240003",
			"sorId": "S5556LL/A",
			"itemAmount": 129.97,
			"itemAmountOriginal": 0.0,
			"dueMonthly": 0.0,
			"dueMonthlyOriginal": null,
			"itemDiscount": 0.0,
			"displayName": "AppleCare+ for iPhone 8, 7, 6s, or 6",
			"skuDisplayName": "AppleCare+ for iPhone 8, 7, 6s, or 6",
			"listPrice": 129.97,
			"rawTotalAmount": 129.97,
			"pricingDetails": [{
				"pricingAdjustmentId": null,
				"itemId": "Se87532820d2769ca4585f3ef421472ef{d4}_accessory_1",
				"orderId": "Se87532820d2769ca4585f3ef421472ef{d4}",
				"offerId": null,
				"offerAmount": 0.0,
				"description": "List Price description",
				"offerType": null,
				"priceListId": null,
				"listPrice": 129.97,
				"offerName": null,
				"creationDate": 1526800851212,
				"lastModifiedDate": 1526800851212,
				"version": 1
			}],
			"orderId": "Se87532820d2769ca4585f3ef421472ef{d4}",
			"version": 1,
			"delete": false,
			"inventoryLevel": 1000,
			"taxDetails": [],
			"itemTaxes": 0.0,
			"deviceLineItemId": "Se87532820d2769ca4585f3ef421472ef{d4}_device_1",
			"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/applecareplus-cc3000?$acc-med$",
			"bogoType": null,
			"recycleStateInd": null,
			"color": null,
			"size": null,
			"capacity": null,
			"lastModifiedDate": 1526800849380,
			"deviceManufacturerName": "Apple",
			"accessoryType": "INLINE_ACCESSORIES",
			"ispuEligibleFlag": true,
			"bundleSkuLineItems": null,
			"bundleDesciption": null,
			"vzwSbdOfferlist": [],
			"promotions": null,
			"purchasePath": "AAL",
			"appleCare": true,
			"expectedShippingDate": null,
			"shipCommitInd": null,
			"sameDayDelivery": false,
			"recycleCreditAllocatedAmount": 0.0,
			"ecpdItemAmount": null,
			"ecpdItemDiscount": 0.0,
			"standaloneaccessory": false,
			"batteryAccessory": false,
			"accSeoUrl": "",
			"featureDropped": false
		}, {
			"id": "Se87532820d2769ca4585f3ef421472ef{d4}_accessory_2",
			"quantity": 1,
			"type": null,
			"skuId": "sku2690302",
			"productId": "11100003",
			"sorId": null,
			"itemAmount": 109.97,
			"itemAmountOriginal": 0.0,
			"dueMonthly": 0.0,
			"dueMonthlyOriginal": null,
			"itemDiscount": 0.0,
			"displayName": "Tech 21 Evo Check Case Bundle for iPhone 8/7/6s/6",
			"skuDisplayName": null,
			"listPrice": 109.97,
			"rawTotalAmount": 109.97,
			"pricingDetails": [{
				"pricingAdjustmentId": null,
				"itemId": "Se87532820d2769ca4585f3ef421472ef{d4}_accessory_2",
				"orderId": "Se87532820d2769ca4585f3ef421472ef{d4}",
				"offerId": null,
				"offerAmount": 0.0,
				"description": "List Price description",
				"offerType": null,
				"priceListId": null,
				"listPrice": 109.97,
				"offerName": null,
				"creationDate": 1526800851212,
				"lastModifiedDate": 1526800851212,
				"version": 1
			}],
			"orderId": "Se87532820d2769ca4585f3ef421472ef{d4}",
			"version": 1,
			"delete": false,
			"inventoryLevel": 0,
			"taxDetails": null,
			"itemTaxes": 0.0,
			"deviceLineItemId": "Se87532820d2769ca4585f3ef421472ef{d4}_device_1",
			"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphone7-tech21-evo-check-case-bundle-6453-gg-bundle-iset?$acc-med$",
			"bogoType": null,
			"recycleStateInd": null,
			"color": null,
			"size": null,
			"capacity": null,
			"lastModifiedDate": 1526800849427,
			"deviceManufacturerName": null,
			"accessoryType": "BUNDLE_ACCESSORIES",
			"ispuEligibleFlag": true,
			"bundleSkuLineItems": [{
				"brand": "",
				"displayName": "Tech 21 Evo Check Case",
				"capacity": 10,
				"productID": "sku2120069",
				"skuDetails": [{
					"id": "sku2120069",
					"quantity": 1,
					"type": null,
					"skuId": "sku2120069",
					"productId": null,
					"sorId": "T21-5329",
					"itemAmount": 39.99,
					"itemAmountOriginal": 0.0,
					"dueMonthly": 0.0,
					"dueMonthlyOriginal": null,
					"itemDiscount": 0.0,
					"displayName": "Evo Check Case for iPhone 8/7 - Smokey/Black",
					"skuDisplayName": "Tech21 Evo Check for iPhone 8/7 - Smokey/Black",
					"listPrice": 39.99,
					"rawTotalAmount": 39.99,
					"pricingDetails": [{
						"pricingAdjustmentId": null,
						"itemId": "sku2120069",
						"orderId": null,
						"offerId": null,
						"offerAmount": 0.0,
						"description": "List Price description",
						"offerType": null,
						"priceListId": null,
						"listPrice": 39.99,
						"offerName": null,
						"creationDate": 1526800851212,
						"lastModifiedDate": 1526800851212,
						"version": 1
					}],
					"orderId": null,
					"version": 0,
					"delete": false,
					"inventoryLevel": 0,
					"taxDetails": [{
						"taxLineItemId": null,
						"lineItemId": "sku2120069",
						"itemType": "accessory",
						"sorSkuId": "T21-5329",
						"taxType": "taxes_fees",
						"taxAmount": 1.6,
						"taxDescription": "GA Local Sales Tax",
						"version": 0,
						"orderId": null,
						"createdDate": 1526800885721
					}, {
						"taxLineItemId": null,
						"lineItemId": "sku2120069",
						"itemType": "accessory",
						"sorSkuId": "T21-5329",
						"taxType": "taxes_fees",
						"taxAmount": 1.6,
						"taxDescription": "GA State Sales Tax",
						"version": 0,
						"orderId": null,
						"createdDate": 1526800885721
					}],
					"itemTaxes": 3.2,
					"deviceLineItemId": null,
					"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/tech21-evo-check-case-iphone-6-6s-smokey-black-t21-5329-iset?$acc-med$",
					"bogoType": null,
					"recycleStateInd": null,
					"color": false,
					"size": null,
					"capacity": null,
					"lastModifiedDate": null,
					"deviceManufacturerName": null,
					"accessoryType": null,
					"ispuEligibleFlag": false,
					"bundleSkuLineItems": null,
					"bundleDesciption": null,
					"vzwSbdOfferlist": [],
					"promotions": null,
					"purchasePath": null,
					"appleCare": false,
					"expectedShippingDate": null,
					"shipCommitInd": null,
					"sameDayDelivery": false,
					"recycleCreditAllocatedAmount": 0.0,
					"ecpdItemAmount": null,
					"ecpdItemDiscount": 0.0,
					"standaloneaccessory": false,
					"batteryAccessory": false,
					"accSeoUrl": null,
					"featureDropped": false,
					"name": "Evo Check Case for iPhone 8/7 - Smokey/Black",
					"price": "39.99",
					"discountedPrice": "34.0",
					"preSelected": false,
					"comingSoonAcc": false,
					"inCart": false,
					"learnMoreLink": "/od/cust/auth/accessoryDetails/?accProdId=acc6640069",
					"discount_price": null,
					"available": false
				}]
			}, {
				"brand": "",
				"displayName": "InvisibleShield Glass+ Screen Protector for iPhone 8/7/6s/6",
				"capacity": 10,
				"productID": "sku2120020",
				"skuDetails": [{
					"id": "sku2120020",
					"quantity": 1,
					"type": null,
					"skuId": "sku2120020",
					"productId": null,
					"sorId": "IP7LGC-F00",
					"itemAmount": 39.99,
					"itemAmountOriginal": 0.0,
					"dueMonthly": 0.0,
					"dueMonthlyOriginal": null,
					"itemDiscount": 0.0,
					"displayName": "InvisibleShield Glass+ Screen Protector for iPhone 8/7/6s/6",
					"skuDisplayName": "ZAGG InvisibleShield Glass for iPhone 8/7/6s/6",
					"listPrice": 39.99,
					"rawTotalAmount": 39.99,
					"pricingDetails": [{
						"pricingAdjustmentId": null,
						"itemId": "sku2120020",
						"orderId": null,
						"offerId": null,
						"offerAmount": 0.0,
						"description": "List Price description",
						"offerType": null,
						"priceListId": null,
						"listPrice": 39.99,
						"offerName": null,
						"creationDate": 1526800851212,
						"lastModifiedDate": 1526800851212,
						"version": 1
					}],
					"orderId": null,
					"version": 0,
					"delete": false,
					"inventoryLevel": 0,
					"taxDetails": [{
						"taxLineItemId": null,
						"lineItemId": "sku2120020",
						"itemType": "accessory",
						"sorSkuId": "IP7LGC-F00",
						"taxType": "taxes_fees",
						"taxAmount": 1.6,
						"taxDescription": "GA Local Sales Tax",
						"version": 0,
						"orderId": null,
						"createdDate": 1526800885721
					}, {
						"taxLineItemId": null,
						"lineItemId": "sku2120020",
						"itemType": "accessory",
						"sorSkuId": "IP7LGC-F00",
						"taxType": "taxes_fees",
						"taxAmount": 1.6,
						"taxDescription": "GA State Sales Tax",
						"version": 0,
						"orderId": null,
						"createdDate": 1526800885721
					}],
					"itemTaxes": 3.2,
					"deviceLineItemId": null,
					"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/zagg-invisibleshield-glass-iphone-6-iset-ip6glc-f00?$acc-med$",
					"bogoType": null,
					"recycleStateInd": null,
					"color": false,
					"size": null,
					"capacity": null,
					"lastModifiedDate": null,
					"deviceManufacturerName": null,
					"accessoryType": null,
					"ispuEligibleFlag": false,
					"bundleSkuLineItems": null,
					"bundleDesciption": null,
					"vzwSbdOfferlist": [],
					"promotions": null,
					"purchasePath": null,
					"appleCare": false,
					"expectedShippingDate": null,
					"shipCommitInd": null,
					"sameDayDelivery": false,
					"recycleCreditAllocatedAmount": 0.0,
					"ecpdItemAmount": null,
					"ecpdItemDiscount": 0.0,
					"standaloneaccessory": false,
					"batteryAccessory": false,
					"accSeoUrl": null,
					"featureDropped": false,
					"name": "InvisibleShield Glass+ Screen Protector for iPhone 8/7/6s/6",
					"price": "39.99",
					"discountedPrice": "34.0",
					"preSelected": false,
					"comingSoonAcc": false,
					"inCart": false,
					"learnMoreLink": "/od/cust/auth/accessoryDetails/?accProdId=acc6640020",
					"discount_price": null,
					"available": false
				}]
			}, {
				"brand": "",
				"displayName": "Lightning Car Charger",
				"capacity": 10,
				"productID": "sku2180048",
				"skuDetails": [{
					"id": "sku2180048",
					"quantity": 1,
					"type": null,
					"skuId": "sku2180048",
					"productId": null,
					"sorId": "VPC24LGHT-M",
					"itemAmount": 29.99,
					"itemAmountOriginal": 0.0,
					"dueMonthly": 0.0,
					"dueMonthlyOriginal": null,
					"itemDiscount": 0.0,
					"displayName": "Lightning Car Charger",
					"skuDisplayName": "Verizon 2.4A Apple Lightning Vehicle Charger",
					"listPrice": 29.99,
					"rawTotalAmount": 29.99,
					"pricingDetails": [{
						"pricingAdjustmentId": null,
						"itemId": "sku2180048",
						"orderId": null,
						"offerId": null,
						"offerAmount": 0.0,
						"description": "List Price description",
						"offerType": null,
						"priceListId": null,
						"listPrice": 29.99,
						"offerName": null,
						"creationDate": 1526800851212,
						"lastModifiedDate": 1526800851212,
						"version": 1
					}],
					"orderId": null,
					"version": 0,
					"delete": false,
					"inventoryLevel": 0,
					"taxDetails": [{
						"taxLineItemId": null,
						"lineItemId": "sku2180048",
						"itemType": "accessory",
						"sorSkuId": "VPC24LGHT-M",
						"taxType": "taxes_fees",
						"taxAmount": 1.2,
						"taxDescription": "GA Local Sales Tax",
						"version": 0,
						"orderId": null,
						"createdDate": 1526800885721
					}, {
						"taxLineItemId": null,
						"lineItemId": "sku2180048",
						"itemType": "accessory",
						"sorSkuId": "VPC24LGHT-M",
						"taxType": "taxes_fees",
						"taxAmount": 1.2,
						"taxDescription": "GA State Sales Tax",
						"version": 0,
						"orderId": null,
						"createdDate": 1526800885721
					}],
					"itemTaxes": 2.4,
					"deviceLineItemId": null,
					"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/vzw-2-4a-apple-lightning-vehicle-charger-vpc24lght-m-iset?$acc-med$",
					"bogoType": null,
					"recycleStateInd": null,
					"color": false,
					"size": null,
					"capacity": null,
					"lastModifiedDate": null,
					"deviceManufacturerName": null,
					"accessoryType": null,
					"ispuEligibleFlag": false,
					"bundleSkuLineItems": null,
					"bundleDesciption": null,
					"vzwSbdOfferlist": [],
					"promotions": null,
					"purchasePath": null,
					"appleCare": false,
					"expectedShippingDate": null,
					"shipCommitInd": null,
					"sameDayDelivery": false,
					"recycleCreditAllocatedAmount": 0.0,
					"ecpdItemAmount": null,
					"ecpdItemDiscount": 0.0,
					"standaloneaccessory": false,
					"batteryAccessory": false,
					"accSeoUrl": null,
					"featureDropped": false,
					"name": "Lightning Car Charger",
					"price": "29.99",
					"discountedPrice": "21.99",
					"preSelected": false,
					"comingSoonAcc": false,
					"inCart": false,
					"learnMoreLink": "/od/cust/auth/accessoryDetails/?accProdId=acc6880020",
					"discount_price": null,
					"available": false
				}]
			}],
			"bundleDesciption": null,
			"vzwSbdOfferlist": null,
			"promotions": null,
			"purchasePath": "AAL",
			"appleCare": false,
			"expectedShippingDate": null,
			"shipCommitInd": null,
			"sameDayDelivery": false,
			"recycleCreditAllocatedAmount": 0.0,
			"ecpdItemAmount": null,
			"ecpdItemDiscount": 0.0,
			"standaloneaccessory": false,
			"batteryAccessory": false,
			"accSeoUrl": "",
			"featureDropped": false
		}],
		"paymentGroup": null,
		"contactInfo": {
			"id": null,
			"emailAddress": "MANOJ.SUBRAMANI@VERIZON.COM",
			"phoneNumber": "4291313064",
			"lastName": "MANNING",
			"firstName": "KYLE",
			"zipCode": "30329",
			"orderId": null,
			"userId": null,
			"npaNxxNumber": null,
			"address1": "2480 CLAIRMONT ROAD NE",
			"address2": null,
			"city": "Atlanta",
			"state": "GA",
			"addressVerified": true,
			"textAlertOptin": false,
			"newsLetterOptin": false,
			"paperFreeBillingIndicatorFlag": false,
			"middleName": null,
			"firmName": null,
			"businessName": null,
			"apartmentNum": "",
			"addressDirection": "NE",
			"poBox": "",
			"streetNumber": "2480",
			"streetName": "CLAIRMONT",
			"streetType": "RD",
			"ruralRoute": null,
			"ruralDel": "",
			"zipCode4": null,
			"zipCode5": null,
			"faxNumber": null,
			"addressType": null,
			"country": "",
			"prefix": null,
			"suffix": null,
			"postbox": null,
			"companyname": null,
			"ruralrte": "",
			"county": null,
			"address3": null,
			"postalcode": "30329",
			"version": 0,
			"lastModifiedDate": null,
			"addressConfirmationStatus": null
		},
		"tradeInDevicesDetails": null,
		"tradeInPromoDetails": null,
		"transformedTradeInPromoDetails": null,
		"subOrders": null,
		"comboOrder": false,
		"totalDueToday": "268.74",
		"totalDueMonthly": "23.41",
		"subTotalDueToday": "239.94",
		"securityDepositAmount": "0.00",
		"stateSalesTax": "28.80",
		"employeeDiscount": "0.00",
		"pastDueExist": false,
		"pastDueAmountPaid": false,
		"pastDueAmount": "0.00",
		"shippingInfo": {
			"shippingInfoUpdated": false,
			"sameAsBilling": true,
			"ispuEligibleFlag": true,
			"addressInfo": {
				"firstName": "KYLE",
				"lastName": "MANNING",
				"companyName": null,
				"address1": "2480 CLAIRMONT ROAD NE",
				"address2": null,
				"city": "Atlanta",
				"state": "GA",
				"zipcode": "30329",
				"businessName": null,
				"postalCode": null,
				"email": "MANOJ.SUBRAMANI@VERIZON.COM",
				"phoneNumber": "4291313064"
			},
			"contactInfo": {
				"emailAddress": "MANOJ.SUBRAMANI@VERIZON.COM",
				"phoneNumber": "4291313064",
				"firstName": "KYLE",
				"lastName": "MANNING",
				"smsMdn": null,
				"activeSMSCapableMtnList": ["6188307724", "6189748060", "6187929371", "6183638784"]
			},
			"shippingTypesInfo": [{
				"estimatedDeliveryDate": "2018-05-24 00:00:00",
				"estimatedDeliveryDateText": "Thu 5/24",
				"shippingDescription": "Free 2 Day by 8pm",
				"shippingOptionId": "SHP002",
				"shippingCost": "0.00",
				"shortDescription": "Free 2 Day by 8pm",
				"active": true,
				"addedShippingOptionId": true,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Thu, May 24 if ordered by 4pm today. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}, {
				"estimatedDeliveryDate": "2018-05-23 00:00:00",
				"estimatedDeliveryDateText": "Wed 5/23",
				"shippingDescription": "Next Day by 8pm",
				"shippingOptionId": "SHP004",
				"shippingCost": "12.99",
				"shortDescription": "Next Day by 8pm",
				"active": true,
				"addedShippingOptionId": false,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Wed, May 23. Next Day by 8pm. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}, {
				"estimatedDeliveryDate": "2018-05-23 10:30:00",
				"estimatedDeliveryDateText": "Wed 5/23 by 10:30AM",
				"shippingDescription": "Next Day by 10:30am",
				"shippingOptionId": "SHP005",
				"shippingCost": "14.99",
				"shortDescription": "Next Day by 10:30am",
				"active": true,
				"addedShippingOptionId": false,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Wed, May 23. Next Day by 10:30am. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}],
			"storeDetail": {
				"storeHeader": null,
				"storeName": null,
				"storeAddress": null,
				"deviceAvailable": false,
				"distance": null,
				"appendedStoreTiming": null,
				"longitude": null,
				"storeId": null,
				"netaceLocationCode": null,
				"latitude": null,
				"seoUrlName": null,
				"storeClosingTime": null
			},
			"tradeIn": false,
			"tradeInAddress": null,
			"nonSddEligibleMsg": null,
			"selectedSDDWindow": null,
			"poboMessage": null,
			"ispudetailsInfo": {
				"storeAddress": null,
				"storeHours": null,
				"storeId": null,
				"storeName": null,
				"phoneNumber": null,
				"distance": null,
				"totalItems": 0,
				"availItems": 0,
				"latitdude": 0.0,
				"longtitude": 0.0,
				"availItemName": null
			}
		},
		"billingInfo": {
			"billToAccountEligible": true,
			"creditCardZipEditable": false,
			"billingAddress": {
				"firstName": "KYLE",
				"lastName": "MANNING",
				"businessName": null,
				"zipcode": "30329",
				"state": "GA",
				"address2": null,
				"address1": "2480 CLAIRMONT ROAD NE",
				"companyName": null,
				"city": "Atlanta",
				"sameAsShipping": false
			},
			"masterpass3DSecure": null,
			"billToAccountNumber": "#XXXXXXX-0001",
			"creditCardInfo": {
				"savedCardNickName": null,
				"preselectCard": null,
				"creditCardNumber": null,
				"creditCardExpMonth": null,
				"creditCardExpYear": null,
				"billingZipCode": null,
				"creditCardType": null,
				"creditCardVerificationNumber": null,
				"creditCardBIN": null,
				"cvvRequired": false
			},
			"selectedPaymentMode": "BTA",
			"giftCardList": [],
			"savedCardInfo": [],
			"applePayResponseInfo": null,
			"masterpassResponseInfo": {
				"emailAddress": null,
				"cardType": null,
				"lastDigits": null,
				"creditCardBIN": null
			},
			"masterpassError": false,
			"masterpassErrorMessage": null,
			"paypalEmailAddress": null,
			"expirationMonths": ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
			"expirationYears": ["2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027"]
		},
		"devices": {
			"dueMonthly": 23.41,
			"totalActivationFee": 0.0,
			"deviceTotalDueMonthly": 10.41,
			"dueToday": 0.0,
			"accessories": [{
				"scene7ImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/applecareplus-cc3000?$acc-med$",
				"name": "AppleCare+ for iPhone 8, 7, 6s, or 6",
				"actualPrice": 129.97,
				"originalPrice": 129.97,
				"percentageOffTxt": null,
				"itemTotal": 129.97,
				"quantity": 1,
				"commerceItemId": "Se87532820d2769ca4585f3ef421472ef{d4}_accessory_1",
				"color": null,
				"size": null,
				"inventoryStatus": "",
				"inventoryAvailableDate": "",
				"prodId": "acc5240003",
				"skuId": "sku1760050",
				"sorId": "S5556LL/A",
				"promoMessage": null,
				"hasEcpdDiscount": false,
				"mobileAppImageName": "",
				"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/applecareplus-cc3000?$acc-med$",
				"hasBogoDiscount": false,
				"price": 129.97,
				"discountPrice": 0.0,
				"retailPrice": 129.97,
				"associatedDeviceSkus": null,
				"prodName": "",
				"discounted": false
			}],
			"accessoriesBundle": [{
				"discountedPrice": 109.97,
				"imgUrl": "https://ss7.vzw.com/is/image/VerizonWireless/apple-iphone7-tech21-evo-check-case-bundle-6453-gg-bundle-iset?$acc-med$",
				"regularPrice": 109.97,
				"savedPrice": 0.0,
				"displayName": "Tech 21 Evo Check Case Bundle for iPhone 8/7/6s/6",
				"bundleDescription": null,
				"skuID": "sku2690302",
				"discountPercentage": 0.0,
				"discounted": false
			}],
			"items": [{
				"deviceName": "iPhone&reg; 7",
				"dueMonthly": "10.41",
				"dueToday": "0.00",
				"upgradeFee": "0.00",
				"originalUpgradeFee": "0.00",
				"activationFee": "30.00",
				"dueTodayOriginal": "0.00",
				"dueMonthlyOriginal": "22.92",
				"dueTodayDiscounted": false,
				"dueMonthlyDiscounted": true,
				"mtn": null,
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-med$&fmt=jpeg&wid=75&hei=150",
				"protectionFeature": {
					"name": "Total Mobile Protection",
					"mtn": null,
					"price": "13.00",
					"discountPrice": "0.00",
					"retailPrice": "0.00",
					"hasEcpdDiscount": false,
					"promoMessage": null,
					"originalPrice": "0.00",
					"wasPrice": "0.00",
					"deviceName": null,
					"color": null,
					"size": null,
					"instantCreditAmount": "0.00",
					"amountAfterInstantCredit": "0.00",
					"disountedInstantCreditAmt": "0.00"
				},
				"optionalFeatures": [],
				"installmentBalance": "249.99",
				"edgeRetailPrice": "549.99",
				"edgeItemDownPaymentAmount": "0.00",
				"mailInRebateAmount": "0.00",
				"transferredFromMtn": null,
				"devicePromotionList": [{
					"promotionalMessage": null,
					"promoDescription": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION BIC YES",
					"promoName": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION",
					"promoAmount": "300.00",
					"priceSubTitle": "1st installment will appear on your bill.",
					"barCodeId": null,
					"itemCode": "MNAE2LL/A",
					"itemType": "ITA",
					"sedOffer": true,
					"isUpgradeFeeWaivedOffer": false,
					"promoContentText": null
				}],
				"bicOfferApplied": false,
				"bicContractPrice": "0.00",
				"bicDiscountedContractPrice": "-1.00",
				"bicAdditionalContractText": null,
				"bicMessageMap": null,
				"edgeUpAmount": 0.0,
				"displayDeviceDueMonthly": 23.41,
				"deviceLACFee": "0.00",
				"manufactureName": "Apple",
				"color": "Gold",
				"colorCode": "#CFBEA9",
				"size": "32GB",
				"displayName": "iPhone&reg; 7",
				"contractTerm": "99",
				"edgeUpBuyOutAmount": 0.0,
				"fullRetailPrice": "549.99",
				"alwaysEligibleForUpgrade": false,
				"numberShareDevice": false,
				"activationFeeText": "One-time activation fee of $30.00 charged to your next monthly bill.",
				"numberSharedMtn": null,
				"promoContentText": null,
				"itemOnJaxPlan": false,
				"humCarDetails": null,
				"simDetails": null,
				"imeiId": null,
				"displayImeiId": null,
				"poboDateLabel": null,
				"nickName": null,
				"planCommerceItemId": "Se87532820d2769ca4585f3ef421472ef{d4}_plan_1",
				"displayMtn": null,
				"promoOfferText": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION",
				"promoApplied": true,
				"commerceItemId": "Se87532820d2769ca4585f3ef421472ef{d4}_device_1",
				"loanTerm": 24,
				"sbdHeaderMsg": null,
				"percentage": null,
				"waivedActivationFeePromo": false,
				"flow": "AAL",
				"edgeDevice": true,
				"instantCreditAmount": "0.00",
				"amountAfterInstantCredit": "0.00",
				"eupdevice": false,
				"accessory": false,
				"disountedInstantCreditAmt": "0.00"
			}],
			"buddyUpgrade": false
		},
		"accessories": null,
		"selectedShippingType": {
			"type": "SHIPPING",
			"shippingTypeName": "FREE 2 Day by 8pm",
			"price": 0.0,
			"discountPrice": 0.0,
			"estimatedDeliveryDate": "2018-05-24 00:00:00"
		},
		"dueMonthlyView": {
			"title": "Due Monthly (device only)",
			"dueMonthlyPrice": "23.41",
			"items": [{
				"name": "iPhone&reg; 7",
				"description": "iPhone&reg; 7",
				"manufacturer": "Apple",
				"color": "Gold",
				"size": "32GB",
				"priceBreakDown": [{
					"lable": "Line Access Charge",
					"price": "0.00",
					"description": null,
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 0.0,
					"itemStrikeThroughPrice": 0.0,
					"noOfBicOccurences": 0
				}, {
					"lable": "Total Mobile Protection",
					"price": "13.00",
					"description": null,
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 0.0,
					"itemStrikeThroughPrice": 0.0,
					"noOfBicOccurences": 0
				}, {
					"lable": "Device Payment",
					"price": "10.41",
					"description": "For 24 months, 0% APR with down payment. Reduced retail price: <span class='textDecLineThrough red'>$549.99</span> $249.99",
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 10.41,
					"itemStrikeThroughPrice": 22.92,
					"noOfBicOccurences": 0
				}],
				"nickName": null,
				"planCommerceItemId": "Se87532820d2769ca4585f3ef421472ef{d4}_plan_1",
				"displayMtn": null,
				"numberShareDevice": false,
				"edge": true
			}],
			"tmpMd": null
		},
		"balanceCreditCardAmount": "268.74",
		"cpcOrder": true,
		"totalDueMonthlyPlanAndDevice": "348.41",
		"deviceConfigInfo": {
			"devices": [{
				"deviceId": "Se87532820d2769ca4585f3ef421472ef{d4}_device_1",
				"deviceName": "iPhone&reg; 7",
				"deviceSetupMode": null,
				"mtnNumber": null,
				"flow": "AAL",
				"serviceAddress": {
					"firstName": "KYLE",
					"lastName": "MANNING",
					"address1": "2480 CLAIRMONT ROAD NE",
					"address2": "",
					"city": "Atlanta",
					"state": "GA",
					"zipCode": "30329",
					"emailAddress": "MANOJ.SUBRAMANI@VERIZON.COM",
					"phoneNumber": "4291313064"
				},
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-med$&fmt=jpeg&wid=75&hei=150",
				"mobileAppImageName": null,
				"npaNxxnumber": "470-631-XXXX",
				"npnxxCustomerSelection": null,
				"npaNxxdetails": null,
				"manufactureName": "Apple",
				"color": "Gold",
				"size": "32GB",
				"numberShareDevice": false,
				"numberSharedMtn": null,
				"deviceNickName": null,
				"numberSharedDeviceName": null,
				"portInDetails": null
			}],
			"npaNxxdetails": {
				"zipCode": "30329",
				"state": "GA",
				"city": "Atlanta",
				"success": true,
				"mtns": ["470-631-XXXX", "470-717-XXXX", "470-725-XXXX", "470-728-XXXX", "470-733-XXXX", "470-747-XXXX", "470-755-XXXX", "470-825-XXXX", "470-867-XXXX", "470-891-XXXX", "470-925-XXXX"],
				"states": null,
				"cities": null
			},
			"deviceAddressUpdated": false,
			"accessories": null
		},
		"checkoutStates": {
			"shippingAddressRequired": false,
			"shippingAddressChangeRequired": false,
			"shippingMethodRequired": false,
			"paymentRequired": false,
			"pastDuePaymentRequired": false,
			"showPaymentSection": true,
			"showShippingAddress": true,
			"showDeliveryMethod": true,
			"newCard": false,
			"cvvNeeded": true,
			"contactInfoRequired": false
		},
		"totalEdgeItemDownPaymentAmount": "0.00",
		"totalEdgeUpAmount": "0.00",
		"totalEdgeUpBuyOutAmount": "0.00",
		"multiOrderDetails": null,
		"hasRio": false,
		"splitShipment": false,
		"isHLLPlanInOrder": true
	}
};*/
window.confirmationJSON = {
	"output": {
		"title": "You're all set.",
		"subtitle": null,
		"orderId": "109015746234349",
		"estimatedDelivery": "",
		"imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/1.3_MV_BuyandUpgrade_ConfirmationPage_Interstital?$device-med$",
		"tradeInStatus": false,
		"confirmationMessage": "Thanks for ordering from verizonwireless.com. Your order receipt is sent to VZW@VZW.COM.",
		"doneButtonText": "Got it",
		"doneButtonLink": "/od/cust/auth/shoplanding/",
		"userNote": "TODO",
		"notNowButtonText": "TODO",
		"notNowButtonLink": "TODO",
		"learnHowButtonText": null,
		"learnHowButtonLink": "/od/cust/auth/learnHow",
		"numberOfDevice": 1,
		"confirmationNumberText": "Confirmation Number",
		"iconicFlow": true,
		"protectionURL": null,
		"accessoriesURL": null,
		"tapFlag": false,
		"cjmTagUrl": null,
		"pepperJamTagUrl": null,
		"selectedPaymentMode": null,
		"confirmationEmail": "VZW@VZW.COM",
		"plans": {
			"dueMonthly": null,
			"dueToday": null,
			"planOnlyDueMonthly": null,
			"items": [{
				"planType": null,
				"lineAccessCharges": null,
				"accountAccess": null,
				"accountLevelFeatures": null,
				"totalMonthlyPlanCost": null,
				"spoBadgeMessage": null,
				"planDisplayName": "Go Unlimited",
				"planImageURL": "//ss7.vzw.com/is/image/VerizonWireless/U_083s_022317",
				"planLetter": null,
				"planDescrption": null,
				"planDescription": null,
				"quantity": 0,
				"skuId": "sku3060010",
				"productId": "plan5600003",
				"itemAmount": -1.7976931348623157E308,
				"itemAmountOriginal": 55.0,
				"dueMonthly": 55.0,
				"dueMonthlyOriginal": 0.0,
				"itemDiscount": 1.7976931348623157E308,
				"displayName": null,
				"skuDisplayName": null,
				"listPrice": 55.0,
				"rawTotalAmount": 0.0,
				"planGroupCode": null,
				"autoPayEnabled": false,
				"numberSharePlan": false,
				"planCommerceItemId": "S7b7d102e3b9811f4a42e1cae3e7e96e9{d1}_plan_1",
				"autoPayPrice": 0.0,
				"autoPayText": null,
				"termsAndConditionKey": null
			}],
			"upgradeDevices": null,
			"newDevices": null,
			"existingDevices": [{
				"name": null,
				"price": "55.0",
				"discountPrice": 55.0,
				"hasEcpdDiscount": false,
				"mtn": "2069401387",
				"listPrice": 55.0,
				"deviceLineItemId": null,
				"discountPriceVal": null,
				"planCommerceItemId": "S7b7d102e3b9811f4a42e1cae3e7e96e9{d1}_plan_1",
				"nickName": "2069401387",
				"numberShareDevice": false,
				"featureDropped": false
			}, {
				"name": null,
				"price": "55.0",
				"discountPrice": 55.0,
				"hasEcpdDiscount": false,
				"mtn": "2533186453",
				"listPrice": 55.0,
				"deviceLineItemId": null,
				"discountPriceVal": null,
				"planCommerceItemId": "S7b7d102e3b9811f4a42e1cae3e7e96e9{d1}_plan_1",
				"nickName": "2533186453",
				"numberShareDevice": false,
				"featureDropped": false
			}],
			"dueMonthlyPlanWithLAC": null,
			"discountedDueMonthlyPlanWithLAC": null,
			"hasEcpdDiscount": false,
			"totalLineAccessCharges": null
		},
		"featureList": [{
			"id": "S7b7d102e3b9811f4a42e1cae3e7e96e9{d1}_feature_1",
			"quantity": 1,
			"type": null,
			"skuId": "sku2880234",
			"productId": "spo1960001",
			"sorId": "1167",
			"itemAmount": 0.0,
			"itemAmountOriginal": 39.0,
			"dueMonthly": 39.0,
			"dueMonthlyOriginal": null,
			"itemDiscount": 0.0,
			"displayName": "Total Mobile Protection Multi-Device",
			"skuDisplayName": null,
			"listPrice": 39.0,
			"rawTotalAmount": 0.0,
			"pricingDetails": [{
				"pricingAdjustmentId": null,
				"itemId": "S7b7d102e3b9811f4a42e1cae3e7e96e9{d1}_feature_1",
				"orderId": "S7b7d102e3b9811f4a42e1cae3e7e96e9{d1}",
				"offerId": null,
				"offerAmount": 0.0,
				"description": "List Price description",
				"offerType": null,
				"priceListId": null,
				"listPrice": 39.0,
				"offerName": null,
				"creationDate": 1526794824226,
				"lastModifiedDate": 1526794824226,
				"version": 1
			}],
			"orderId": "S7b7d102e3b9811f4a42e1cae3e7e96e9{d1}",
			"version": 1,
			"delete": false,
			"inventoryLevel": 0,
			"taxDetails": null,
			"itemTaxes": 0.0,
			"deviceLineItemId": "S7b7d102e3b9811f4a42e1cae3e7e96e9{d1}_device_1",
			"featureCharge": 0.0,
			"featureType": "SPO",
			"lastModifiedDate": 1526794781922
		}],
		"accessoryList": null,
		"paymentGroup": null,
		"contactInfo": {
			"id": null,
			"emailAddress": "VZW@VZW.COM",
			"phoneNumber": "8482198433",
			"lastName": "edara",
			"firstName": "satheesh",
			"zipCode": "08817",
			"orderId": null,
			"userId": null,
			"npaNxxNumber": null,
			"address1": "1135 Blueberry ct",
			"address2": "null",
			"city": "EDISON",
			"state": "NJ",
			"addressVerified": true,
			"textAlertOptin": false,
			"newsLetterOptin": false,
			"paperFreeBillingIndicatorFlag": false,
			"middleName": null,
			"firmName": null,
			"businessName": null,
			"apartmentNum": "",
			"addressDirection": "",
			"poBox": "",
			"streetNumber": "1135",
			"streetName": "BLUEBERRY",
			"streetType": "CT",
			"ruralRoute": null,
			"ruralDel": "",
			"zipCode4": "2609",
			"zipCode5": null,
			"faxNumber": null,
			"addressType": "R",
			"country": "",
			"prefix": null,
			"suffix": null,
			"postbox": null,
			"companyname": null,
			"ruralrte": "",
			"county": null,
			"address3": null,
			"postalcode": "08817",
			"version": 0,
			"lastModifiedDate": null,
			"addressConfirmationStatus": null
		},
		"tradeInDevicesDetails": null,
		"tradeInPromoDetails": null,
		"transformedTradeInPromoDetails": null,
		"subOrders": null,
		"comboOrder": false,
		"totalDueToday": "16.56",
		"totalDueMonthly": "49.41",
		"subTotalDueToday": "0.00",
		"securityDepositAmount": "0.00",
		"stateSalesTax": "16.56",
		"employeeDiscount": "0.00",
		"pastDueExist": false,
		"pastDueAmountPaid": false,
		"pastDueAmount": "0.00",
		"shippingInfo": {
			"shippingInfoUpdated": true,
			"sameAsBilling": false,
			"ispuEligibleFlag": true,
			"addressInfo": {
				"firstName": "satheesh",
				"lastName": "edara",
				"companyName": null,
				"address1": "1135 Blueberry ct",
				"address2": null,
				"city": "EDISON",
				"state": "NJ",
				"zipcode": "08817",
				"businessName": null,
				"postalCode": "08817",
				"email": "VZW@VZW.COM",
				"phoneNumber": "8482198433"
			},
			"contactInfo": {
				"emailAddress": "VZW@VZW.COM",
				"phoneNumber": "8482198433",
				"firstName": "satheesh",
				"lastName": "edara",
				"smsMdn": "",
				"activeSMSCapableMtnList": ["2069401387", "2533186453"]
			},
			"shippingTypesInfo": [{
				"estimatedDeliveryDate": "2018-05-24 00:00:00",
				"estimatedDeliveryDateText": "Thu 5/24",
				"shippingDescription": "Free 2 Day by 8pm",
				"shippingOptionId": "SHP002",
				"shippingCost": "0.00",
				"shortDescription": "Free 2 Day by 8pm",
				"active": true,
				"addedShippingOptionId": true,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Thu, May 24 if ordered by 4pm today. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}, {
				"estimatedDeliveryDate": "2018-05-23 00:00:00",
				"estimatedDeliveryDateText": "Wed 5/23",
				"shippingDescription": "Next Day by 8pm",
				"shippingOptionId": "SHP004",
				"shippingCost": "12.99",
				"shortDescription": "Next Day by 8pm",
				"active": true,
				"addedShippingOptionId": false,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Wed, May 23. Next Day by 8pm. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}, {
				"estimatedDeliveryDate": "2018-05-23 10:30:00",
				"estimatedDeliveryDateText": "Wed 5/23 by 10:30AM",
				"shippingDescription": "Next Day by 10:30am",
				"shippingOptionId": "SHP005",
				"shippingCost": "14.99",
				"shortDescription": "Next Day by 10:30am",
				"active": true,
				"addedShippingOptionId": false,
				"signatureRequired": "true",
				"description": "Estimated to arrive on Wed, May 23. Next Day by 10:30am. Signature required.",
				"depletionLocationCode": null,
				"sddAvailableWindows": null
			}],
			"storeDetail": {
				"storeHeader": null,
				"storeName": null,
				"storeAddress": null,
				"deviceAvailable": false,
				"distance": null,
				"appendedStoreTiming": null,
				"longitude": "0.0",
				"storeId": null,
				"netaceLocationCode": null,
				"latitude": "0.0",
				"seoUrlName": null,
				"storeClosingTime": null
			},
			"tradeIn": false,
			"tradeInAddress": null,
			"nonSddEligibleMsg": null,
			"selectedSDDWindow": null,
			"poboMessage": null,
			"ispudetailsInfo": {
				"storeAddress": null,
				"storeHours": null,
				"storeId": null,
				"storeName": null,
				"phoneNumber": null,
				"distance": null,
				"totalItems": 0,
				"availItems": 0,
				"latitdude": 0.0,
				"longtitude": 0.0,
				"availItemName": null
			}
		},
		"billingInfo": {
			"billToAccountEligible": true,
			"creditCardZipEditable": false,
			"billingAddress": {
				"firstName": "EDWARD",
				"lastName": "CLEMENS",
				"businessName": null,
				"zipcode": "96789",
				"state": "HI",
				"address2": null,
				"address1": "95-45 5 KUAHELANI AVE APT 104",
				"companyName": null,
				"city": "Mililani",
				"sameAsShipping": false
			},
			"masterpass3DSecure": null,
			"billToAccountNumber": "#XXXXXXX-0001",
			"creditCardInfo": {
				"savedCardNickName": null,
				"preselectCard": null,
				"creditCardNumber": null,
				"creditCardExpMonth": null,
				"creditCardExpYear": null,
				"billingZipCode": null,
				"creditCardType": null,
				"creditCardVerificationNumber": null,
				"creditCardBIN": null,
				"cvvRequired": false
			},
			"selectedPaymentMode": "BTA",
			"giftCardList": [],
			"savedCardInfo": [{
				"savedCardNickName": "BOGUS",
				"preselectCard": null,
				"creditCardNumber": "XXXX-XXXX-XXXX-4254",
				"creditCardExpMonth": "12",
				"creditCardExpYear": "29",
				"billingZipCode": "",
				"creditCardType": "visa",
				"creditCardVerificationNumber": null,
				"creditCardBIN": "409109",
				"cvvRequired": false
			}],
			"applePayResponseInfo": null,
			"masterpassResponseInfo": {
				"emailAddress": null,
				"cardType": null,
				"lastDigits": null,
				"creditCardBIN": null
			},
			"masterpassError": false,
			"masterpassErrorMessage": null,
			"paypalEmailAddress": null,
			"expirationMonths": ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"],
			"expirationYears": ["2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027"]
		},
		"devices": {
			"dueMonthly": 49.41,
			"totalActivationFee": 0.0,
			"deviceTotalDueMonthly": 10.41,
			"dueToday": 0.0,
			"accessories": [],
			"accessoriesBundle": [],
			"items": [{
				"deviceName": "iPhone&reg; 7",
				"dueMonthly": "10.41",
				"dueToday": "0.00",
				"upgradeFee": "0.00",
				"originalUpgradeFee": "0.00",
				"activationFee": "30.00",
				"dueTodayOriginal": "0.00",
				"dueMonthlyOriginal": "22.92",
				"dueTodayDiscounted": false,
				"dueMonthlyDiscounted": true,
				"mtn": null,
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-med$&fmt=jpeg&wid=75&hei=150",
				"protectionFeature": {
					"name": "Total Mobile Protection Multi-Device",
					"mtn": null,
					"price": "39.00",
					"discountPrice": "0.00",
					"retailPrice": "0.00",
					"hasEcpdDiscount": false,
					"promoMessage": null,
					"originalPrice": "0.00",
					"wasPrice": "0.00",
					"deviceName": null,
					"color": null,
					"size": null,
					"instantCreditAmount": "0.00",
					"amountAfterInstantCredit": "0.00",
					"disountedInstantCreditAmt": "0.00"
				},
				"optionalFeatures": [],
				"installmentBalance": "249.99",
				"edgeRetailPrice": "549.99",
				"edgeItemDownPaymentAmount": "0.00",
				"mailInRebateAmount": "0.00",
				"transferredFromMtn": null,
				"devicePromotionList": [{
					"promotionalMessage": null,
					"promoDescription": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION BIC YES",
					"promoName": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION",
					"promoAmount": "300.00",
					"priceSubTitle": "1st installment will appear on your bill.",
					"barCodeId": null,
					"itemCode": "MNAE2LL/A",
					"itemType": "ITA",
					"sedOffer": true,
					"isUpgradeFeeWaivedOffer": false,
					"promoContentText": null
				}],
				"bicOfferApplied": false,
				"bicContractPrice": "0.00",
				"bicDiscountedContractPrice": "-1.00",
				"bicAdditionalContractText": null,
				"bicMessageMap": null,
				"edgeUpAmount": 0.0,
				"displayDeviceDueMonthly": 49.41,
				"deviceLACFee": "0.00",
				"manufactureName": "Apple",
				"color": "Gold",
				"colorCode": "#CFBEA9",
				"size": "32GB",
				"displayName": "iPhone&reg; 7",
				"contractTerm": "99",
				"edgeUpBuyOutAmount": 0.0,
				"fullRetailPrice": "549.99",
				"alwaysEligibleForUpgrade": false,
				"numberShareDevice": false,
				"activationFeeText": "One-time activation fee of $30.00 charged to your next monthly bill.",
				"numberSharedMtn": null,
				"promoContentText": null,
				"itemOnJaxPlan": false,
				"humCarDetails": null,
				"simDetails": null,
				"imeiId": null,
				"displayImeiId": null,
				"poboDateLabel": null,
				"nickName": null,
				"planCommerceItemId": "S7b7d102e3b9811f4a42e1cae3e7e96e9{d1}_plan_1",
				"displayMtn": null,
				"promoOfferText": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION",
				"promoApplied": true,
				"commerceItemId": "S7b7d102e3b9811f4a42e1cae3e7e96e9{d1}_device_1",
				"loanTerm": 24,
				"sbdHeaderMsg": null,
				"percentage": null,
				"waivedActivationFeePromo": false,
				"flow": "AAL",
				"edgeDevice": true,
				"instantCreditAmount": "0.00",
				"amountAfterInstantCredit": "0.00",
				"eupdevice": false,
				"accessory": false,
				"disountedInstantCreditAmt": "0.00"
			}],
			"buddyUpgrade": false
		},
		"accessories": null,
		"selectedShippingType": {
			"type": "SHIPPING",
			"shippingTypeName": "Free 2 Day by 8pm",
			"price": 0.0,
			"discountPrice": 0.0,
			"estimatedDeliveryDate": "2018-05-24 00:00:00"
		},
		"dueMonthlyView": {
			"title": "Due Monthly",
			"dueMonthlyPrice": "49.41",
			"items": [{
				"name": "iPhone&reg; 7",
				"description": "iPhone&reg; 7",
				"manufacturer": "Apple",
				"color": "Gold",
				"size": "32GB",
				"priceBreakDown": [{
					"lable": "Line Access Charge",
					"price": "0.00",
					"description": null,
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 0.0,
					"itemStrikeThroughPrice": 0.0,
					"noOfBicOccurences": 0
				}, {
					"lable": "Total Mobile Protection Multi-Device",
					"price": "39.00",
					"description": null,
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 0.0,
					"itemStrikeThroughPrice": 0.0,
					"noOfBicOccurences": 0
				}, {
					"lable": "Device Payment",
					"price": "10.41",
					"description": "For 24 months, 0% APR with down payment. Reduced retail price: <span class='textDecLineThrough red'>$549.99</span> $249.99",
					"linkText": null,
					"linkUrl": null,
					"originalPrice": 0.0,
					"tmpMdOpted": false,
					"discountedEdgeRetailPrice": null,
					"sbdPromoMsg": null,
					"sbdDiscountAmount": 0.0,
					"sbdItemMonthlyAmount": 0.0,
					"itemRetailPrice": 0.0,
					"itemMonthlyPrice": 10.41,
					"itemStrikeThroughPrice": 22.92,
					"noOfBicOccurences": 0
				}],
				"nickName": null,
				"planCommerceItemId": null,
				"displayMtn": null,
				"numberShareDevice": false,
				"edge": false
			}],
			"tmpMd": {
				"lable": "Total Mobile Protection Multi-Device",
				"price": "39.00",
				"description": "",
				"linkText": null,
				"linkUrl": null,
				"originalPrice": 0.0,
				"tmpMdOpted": true,
				"discountedEdgeRetailPrice": null,
				"sbdPromoMsg": null,
				"sbdDiscountAmount": 0.0,
				"sbdItemMonthlyAmount": 0.0,
				"itemRetailPrice": 0.0,
				"itemMonthlyPrice": 0.0,
				"itemStrikeThroughPrice": 0.0,
				"noOfBicOccurences": 0
			}
		},
		"balanceCreditCardAmount": "16.56",
		"cpcOrder": true,
		"totalDueMonthlyPlanAndDevice": "214.41",
		"deviceConfigInfo": {
			"devices": [{
				"deviceId": "S7b7d102e3b9811f4a42e1cae3e7e96e9{d1}_device_1",
				"deviceName": "iPhone&reg; 7",
				"deviceSetupMode": null,
				"mtnNumber": null,
				"flow": "AAL",
				"serviceAddress": {
					"firstName": "satheesh",
					"lastName": "edara",
					"address1": "1135 Blueberry ct",
					"address2": "null",
					"city": "EDISON",
					"state": "NJ",
					"zipCode": "08817",
					"emailAddress": "VZW@VZW.COM",
					"phoneNumber": "8482198433"
				},
				"deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-med$&fmt=jpeg&wid=75&hei=150",
				"mobileAppImageName": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-lg$",
				"npaNxxnumber": "845-325-XXXX",
				"npnxxCustomerSelection": "new",
				"npaNxxdetails": null,
				"manufactureName": null,
				"color": null,
				"size": null,
				"numberShareDevice": false,
				"numberSharedMtn": null,
				"deviceNickName": null,
				"numberSharedDeviceName": null,
				"portInDetails": null
			}],
			"npaNxxdetails": {
				"zipCode": null,
				"state": null,
				"city": null,
				"success": false,
				"mtns": null,
				"states": null,
				"cities": null
			},
			"deviceAddressUpdated": true,
			"accessories": null
		},
		"checkoutStates": {
			"shippingAddressRequired": false,
			"shippingAddressChangeRequired": false,
			"shippingMethodRequired": false,
			"paymentRequired": false,
			"pastDuePaymentRequired": false,
			"showPaymentSection": true,
			"showShippingAddress": true,
			"showDeliveryMethod": true,
			"newCard": false,
			"cvvNeeded": false,
			"contactInfoRequired": false
		},
		"totalEdgeItemDownPaymentAmount": "0.00",
		"totalEdgeUpAmount": "0.00",
		"totalEdgeUpBuyOutAmount": "0.00",
		"multiOrderDetails": null,
		"hasRio": false,
		"splitShipment": false,
		"isHLLPlanInOrder": true
	}
};