window.confirmationJSON = {
  "output": {
    "title": "You're all set.",
    "subtitle": null,
    "orderId": "462657335945970",
    "estimatedDelivery": "",
    "imageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/1.3_MV_BuyandUpgrade_ConfirmationPage_Interstital?$device-med$",
    "tradeInStatus": false,
    "confirmationMessage": "Thanks for ordering from verizonwireless.com. Your order receipt is sent to VZW@VZW.COM.",
    "doneButtonText": "Got it",
    "doneButtonLink": "/od/cust/auth/shoplanding/",
    "userNote": "TODO",
    "notNowButtonText": "TODO",
    "notNowButtonLink": "TODO",
    "learnHowButtonText": null,
    "learnHowButtonLink": "/od/cust/auth/learnHow",
    "numberOfDevice": 1,
    "confirmationNumberText": "Confirmation Number",
    "iconicFlow": true,
    "protectionURL": null,
    "accessoriesURL": null,
    "tapFlag": false,
    "cjmTagUrl": null,
    "pepperJamTagUrl": null,
    "selectedPaymentMode": null,
    "confirmationEmail": "VZW@VZW.COM",
    "plans": {
      "dueMonthly": "32.80",
      "dueToday": "0.00",
      "planOnlyDueMonthly": "32.80",
      "items": [
        {
          "planType": "The new Verizon Plan Single Smartphone 5 GB",
          "lineAccessCharges": [
            {
              "name": "Apple iPhone&reg; 7 32GB in Gold",
              "mtn": null,
              "price": "20.00",
              "discountPrice": "0.00",
              "retailPrice": "0.00",
              "hasEcpdDiscount": false,
              "promoMessage": null,
              "originalPrice": "20.00",
              "wasPrice": "20.00",
              "deviceName": "iPhone&reg; 7",
              "color": "Gold",
              "size": "32GB",
              "instantCreditAmount": "0.00",
              "amountAfterInstantCredit": "0.00",
              "disountedInstantCreditAmt": "0.00",
              "tapfeature": false
            }
          ],
          "accountAccess": {
            "name": "The new Verizon Plan Single Smartphone 5 GB",
            "mtn": null,
            "price": "32.80",
            "discountPrice": "0.00",
            "retailPrice": "0.00",
            "hasEcpdDiscount": false,
            "promoMessage": null,
            "originalPrice": "0.00",
            "wasPrice": "0.00",
            "deviceName": null,
            "color": null,
            "size": null,
            "instantCreditAmount": "0.00",
            "amountAfterInstantCredit": "0.00",
            "disountedInstantCreditAmt": "0.00",
            "tapfeature": false
          },
          "accountLevelFeatures": null,
          "totalMonthlyPlanCost": "32.80",
          "spoBadgeMessage": null,
          "planDisplayName": "The new Verizon Plan Single Smartphone 5 GB",
          "planImageURL": "https://ss7.vzw.com/is/image/VerizonWireless/2017-plan-5gb-black",
          "planLetter": null,
          "planDescrption": "<span>5 GB  </span><span>Shared Data,  </span><span>Carryover Data, </span><span>Unlimited </span><span>Talk &amp; Text </span>",
          "planDescription": "<span>5 GB  </span><span>Shared Data,  </span><span>Carryover Data, </span><span>Unlimited </span><span>Talk &amp; Text </span>",
          "quantity": 0,
          "skuId": null,
          "productId": null,
          "itemAmount": null,
          "itemAmountOriginal": null,
          "dueMonthly": null,
          "dueMonthlyOriginal": null,
          "itemDiscount": null,
          "displayName": null,
          "skuDisplayName": null,
          "listPrice": null,
          "rawTotalAmount": null,
          "planGroupCode": null,
          "autoPayEnabled": false,
          "numberSharePlan": false,
          "planCommerceItemId": null,
          "autoPayPrice": null,
          "autoPayText": null,
          "termsAndConditionKey": null,
          "unitOfMeasure": null,
          "planSize": null
        }
      ],
      "upgradeDevices": [
        
      ],
      "newDevices": [
        {
          "name": "iPhone&reg; 7",
          "price": "20.00",
          "discountPrice": 0.0,
          "hasEcpdDiscount": false,
          "mtn": null,
          "listPrice": 20.0,
          "deviceLineItemId": "sku2150053",
          "discountPriceVal": "0.00",
          "planCommerceItemId": null,
          "nickName": null,
          "numberShareDevice": false,
          "featureDropped": false,
          "deviceType": null,
          "changePlanUrl": null,
          "rioDevice": false
        }
      ],
      "existingDevices": [
        {
          "name": "Verizon Jetpack&reg; 4G LTE MHS MiFi 7730L",
          "price": "10.00",
          "discountPrice": 0.0,
          "hasEcpdDiscount": false,
          "mtn": "4783632373",
          "listPrice": 10.0,
          "deviceLineItemId": null,
          "discountPriceVal": "0.00",
          "planCommerceItemId": null,
          "nickName": null,
          "numberShareDevice": false,
          "featureDropped": false,
          "deviceType": null,
          "changePlanUrl": null,
          "rioDevice": false
        }
      ],
      "dueMonthlyPlanWithLAC": "70.00",
      "discountedDueMonthlyPlanWithLAC": "32.80",
      "hasEcpdDiscount": true,
      "totalLineAccessCharges": "20.00"
    },
    "tradeInDevicesDetails": null,
    "tradeInPromoDetails": null,
    "transformedTradeInPromoDetails": null,
    "subOrders": null,
    "comboOrder": false,
    "totalDueToday": "17.50",
    "totalDueMonthly": "30.41",
    "subTotalDueToday": "0.00",
    "securityDepositAmount": "0.00",
    "stateSalesTax": "17.50",
    "employeeDiscount": "0.00",
    "pastDueExist": false,
    "pastDueAmountPaid": false,
    "pastDueAmount": "0.00",
    "shippingInfo": {
      "shippingInfoUpdated": false,
      "sameAsBilling": true,
      "ispuEligibleFlag": true,
      "addressInfo": {
        "firstName": "TYLER",
        "lastName": "LEE",
        "companyName": null,
        "address1": "2456 GRANDVIEW DR NE APT B DR",
        "address2": null,
        "city": "Milledgeville",
        "state": "GA",
        "zipcode": "31061",
        "businessName": null,
        "postalCode": null,
        "email": "VZW@VZW.COM",
        "phoneNumber": "6496364362"
      },
      "contactInfo": {
        "emailAddress": "VZW@VZW.COM",
        "phoneNumber": "6496364362",
        "firstName": "TYLER",
        "lastName": "LEE",
        "smsMdn": null,
        "activeSMSCapableMtnList": [
          "4783632373"
        ]
      },
      "shippingTypesInfo": null,
      "storeDetail": {
        "storeHeader": null,
        "storeName": null,
        "storeAddress": null,
        "deviceAvailable": false,
        "distance": null,
        "appendedStoreTiming": null,
        "longitude": null,
        "storeId": null,
        "netaceLocationCode": null,
        "latitude": null,
        "seoUrlName": null,
        "storeClosingTime": null
      },
      "tradeIn": false,
      "tradeInAddress": null,
      "nonSddEligibleMsg": null,
      "selectedSDDWindow": null,
      "poboMessage": null,
      "ispudetailsInfo": {
        "storeAddress": null,
        "storeHours": null,
        "storeId": null,
        "storeName": null,
        "phoneNumber": null,
        "distance": null,
        "totalItems": 0,
        "availItems": 0,
        "latitdude": 0.0,
        "longtitude": 0.0,
        "availItemName": null
      }
    },
    "billingInfo": {
      "billToAccountEligible": true,
      "creditCardZipEditable": false,
      "billingAddress": {
        "firstName": "TYLER",
        "lastName": "LEE",
        "businessName": null,
        "zipcode": "31061",
        "state": "GA",
        "address2": null,
        "address1": "2456 GRANDVIEW DR NE APT B DR",
        "companyName": null,
        "city": "Milledgeville",
        "sameAsShipping": false
      },
      "masterpass3DSecure": null,
      "billToAccountNumber": "#XXXXXXX-0002",
      "creditCardInfo": {
        "savedCardNickName": null,
        "preselectCard": null,
        "creditCardNumber": null,
        "creditCardExpMonth": null,
        "creditCardExpYear": null,
        "billingZipCode": null,
        "creditCardType": null,
        "creditCardVerificationNumber": null,
        "creditCardBIN": null,
        "cvvRequired": false
      },
      "selectedPaymentMode": "BTA",
      "giftCardList": [
        
      ],
      "savedCardInfo": null,
      "applePayResponseInfo": null,
      "masterpassResponseInfo": {
        "emailAddress": null,
        "cardType": null,
        "lastDigits": null,
        "creditCardBIN": null
      },
      "masterpassError": false,
      "masterpassErrorMessage": null,
      "paypalEmailAddress": null,
      "expirationMonths": null,
      "expirationYears": null
    },
    "devices": {
      "dueMonthly": 10.41,
      "totalActivationFee": 0.0,
      "deviceTotalDueMonthly": 10.41,
      "dueToday": 0.0,
      "accessories": [
        
      ],
      "accessoriesBundle": [
        
      ],
      "items": [
        {
          "deviceName": "iPhone&reg; 7",
          "dueMonthly": "10.41",
          "dueToday": "0.00",
          "upgradeFee": "0.00",
          "originalUpgradeFee": "0.00",
          "activationFee": "30.00",
          "dueTodayOriginal": "0.00",
          "dueMonthlyOriginal": "22.92",
          "dueTodayDiscounted": false,
          "dueMonthlyDiscounted": true,
          "mtn": null,
          "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-med$&fmt=jpeg&wid=75&hei=150",
          "protectionFeature": {
            "name": "Decline Equipment Protection",
            "mtn": null,
            "price": "0.00",
            "discountPrice": "0.00",
            "retailPrice": "0.00",
            "hasEcpdDiscount": false,
            "promoMessage": null,
            "originalPrice": "0.00",
            "wasPrice": "0.00",
            "deviceName": null,
            "color": null,
            "size": null,
            "instantCreditAmount": "0.00",
            "amountAfterInstantCredit": "0.00",
            "disountedInstantCreditAmt": "0.00",
            "tapfeature": false
          },
          "optionalFeatures": [
            
          ],
          "installmentBalance": "249.99",
          "edgeRetailPrice": "549.99",
          "edgeItemDownPaymentAmount": "0.00",
          "mailInRebateAmount": "0.00",
          "transferredFromMtn": null,
          "devicePromotionList": [
            {
              "promotionalMessage": null,
              "promoDescription": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION BIC YES",
              "promoName": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION",
              "promoAmount": "300.00",
              "priceSubTitle": "1st installment will appear on your bill.",
              "barCodeId": null,
              "itemCode": "MNAE2LL/A",
              "itemType": "ITA",
              "sedOffer": true,
              "isUpgradeFeeWaivedOffer": false,
              "promoContentText": null
            }
          ],
          "bicOfferApplied": false,
          "bicContractPrice": "0.00",
          "bicDiscountedContractPrice": "-1.00",
          "bicAdditionalContractText": null,
          "bicMessageMap": null,
          "edgeUpAmount": 0.0,
          "displayDeviceDueMonthly": 30.41,
          "deviceLACFee": "20.00",
          "manufactureName": "Apple",
          "color": "Gold",
          "colorCode": "#CFBEA9",
          "size": "32GB",
          "displayName": "iPhone&reg; 7",
          "contractTerm": "99",
          "edgeUpBuyOutAmount": 0.0,
          "fullRetailPrice": "549.99",
          "alwaysEligibleForUpgrade": false,
          "numberShareDevice": false,
          "activationFeeText": "One-time activation fee of $30.00 charged to your next monthly bill.",
          "numberSharedMtn": null,
          "promoContentText": null,
          "itemOnJaxPlan": false,
          "humCarDetails": null,
          "simDetails": null,
          "imeiId": null,
          "displayImeiId": null,
          "poboDateLabel": null,
          "nickName": null,
          "planCommerceItemId": null,
          "displayMtn": null,
          "promoOfferText": "UAT CM 300 00 OFF ANY PHONE CDMA MIGRATION",
          "promoApplied": true,
          "commerceItemId": "S94db7fbfa31f65e1b7839175c3125c4a{ss100}_device_1",
          "loanTerm": 24,
          "sbdHeaderMsg": null,
          "percentage": null,
          "waivedActivationFeePromo": false,
          "flow": "AAL",
          "edgeDevice": true,
          "instantCreditAmount": "0.00",
          "amountAfterInstantCredit": "0.00",
          "accessory": false,
          "eupdevice": false,
          "disountedInstantCreditAmt": "0.00"
        }
      ],
      "buddyUpgrade": false
    },
    "accessories": null,
    "selectedShippingType": {
      "type": "SHIPPING",
      "shippingTypeName": "FREE 2 Day by 8pm",
      "price": 0.0,
      "discountPrice": 0.0,
      "estimatedDeliveryDate": "2018-06-04 00:00:00"
    },
    "balanceCreditCardAmount": "17.50",
    "cpcOrder": true,
    "totalDueMonthlyPlanAndDevice": "43.21",
    "deviceConfigInfo": {
      "devices": [
        {
          "deviceId": "S94db7fbfa31f65e1b7839175c3125c4a{ss100}_device_1",
          "deviceName": "iPhone&reg; 7",
          "deviceSetupMode": null,
          "mtnNumber": null,
          "flow": "AAL",
          "serviceAddress": {
            "firstName": "TYLER",
            "lastName": "LEE",
            "address1": "2456 GRANDVIEW DR NE APT B DR",
            "address2": "",
            "city": "Milledgeville",
            "state": "GA",
            "zipCode": "31061",
            "emailAddress": "VZW@VZW.COM",
            "phoneNumber": "6496364362"
          },
          "deviceImageUrl": "https://ss7.vzw.com/is/image/VerizonWireless/iphone7-front-gld?$device-med$&fmt=jpeg&wid=75&hei=150",
          "mobileAppImageName": null,
          "npaNxxnumber": "478-234-XXXX",
          "npnxxCustomerSelection": null,
          "npaNxxdetails": null,
          "manufactureName": "Apple",
          "color": "Gold",
          "size": "32GB",
          "numberShareDevice": false,
          "numberSharedMtn": null,
          "deviceNickName": null,
          "numberSharedDeviceName": null,
          "portInDetails": null
        }
      ],
      "npaNxxdetails": {
        "zipCode": "31061",
        "state": "GA",
        "city": "Milledgeville",
        "success": true,
        "mtns": [
          "478-234-XXXX"
        ],
        "states": null,
        "cities": null
      },
      "deviceAddressUpdated": false,
      "accessories": null
    },
    "checkoutStates": {
      "shippingAddressRequired": false,
      "shippingAddressChangeRequired": false,
      "poBoxShippingAddress": false,
      "shippingAddressValidationError": false,
      "shippingMethodRequired": false,
      "paymentRequired": false,
      "pastDuePaymentRequired": false,
      "showPaymentSection": true,
      "showShippingAddress": true,
      "showDeliveryMethod": true,
      "newCard": false,
      "cvvNeeded": true,
      "contactInfoRequired": false
    },
    "totalEdgeItemDownPaymentAmount": "0.00",
    "totalEdgeUpAmount": "0.00",
    "totalEdgeUpBuyOutAmount": "0.00",
    "multiOrderDetails": null,
    "hasRio": false,
    "splitShipment": false,
    "isHLLPlanInOrder": false
  }
};